### ISSUE TITLE
Don't go in there!

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1003]
Mog house has a two out of three chance to cause camera to lock in place, zoning out of mog house causes the camera to actually stay facing away from mog house but locked at the actual mog house. So you can run away from it all you want but camera actually doesn't follow your toon. Not being able to see any npc's or where you're going makes it impossible to see if zoning again would fix the issue. Also a third of the time the framerate drops suddenly and locks itself at 9fps. Leaving mog house doesn't fix that either.

**Comment by teschnei** [comment]
any mog house? a specific mog house? your server? did you change jobs (would it have given you the home point set cutscene)?

**Comment by maxtherabbit** [comment]
think it's a video driver issue, I started noticing it after my most recent driver update

**Comment by timmifshode** [comment]
Sorry, its old school server, happens usually as soon as the mog appears if its going to happen, only tried bastok mog house so far, which is missing furniture placed in it, dont know if that matters or not. Changed jobs and accessed every menu on the list but once it happens I'm stuck at 9fps until I relog.

**Comment by timmifshode** [comment]
Tested this and had it happen on a separate machine with a different video card, older driver too and it still happens. Leaving the mog house will sometimes fix the fps drop but camera stays stuck in place

**Comment by maxtherabbit** [comment]
That's curious, there was also a client update around the time I started noticing this

**Comment by teschnei** [comment]
i was going to say, might be something weird with retail, but I can't think of a reason why they'd need to change something in the mog house (the moogle appearing)

**Comment by TeoTwawki** [comment]
May have something to do with furnishings in mog house going glitched. When I was trying to figure out the placement bugs with that, I had my camera go crazy a few times.

**Comment by teschnei** [comment]
maybe, but that would only apply to your own mog house i think

**Comment by TeoTwawki** [comment]
I read that wrong, thought he was saying he camera went nuts on entering, when he was saying it was on coming out of it.

**Comment by timmifshode** [comment]
Well the camera locks upon entering, but stays locked after exiting. The FPS drop is only while inside mog house though. I've found that its like a 9/10 chance it will happen on one character but rarely ever happens on the other characters.

**Comment by maxtherabbit** [comment]
as a related note, my moog house keeps buggin out with all these invisible walls i have to go around on my test server

**Comment by teschnei** [comment]
i'm sure both problems are caused by items that are trying to be shown as
furniture that aren't furniture - maybe you should check the extra data of
all of your items

**Comment by timmifshode** [comment]
Could be, since none of the furniture is where it should be after you place it and zone out/back in. I did make a big 69 out of chests and I guess it didn't like it so much. going to the layout menu actually releases the FPS lock, but trying to rearrange any of the furniture causes pol.exe to crash immediately.

**Comment by teschnei** [comment]
yep, best to figure what item is doing that then

**Comment by TeoTwawki** [comment]
ok, this *does* look related to #851 after all from what he's showing. And I can reproduce #851 on a fresh clean with clean database just buy placing random furniture and logging out.

**Comment by teschnei** [comment]
replace "random furniture" with specific furniture in specific places and
we got a deal

**Comment by TeoTwawki** [comment]
See screenshots in other issue, just use those if you want one that for sure works (although EVERY furniture item I have tried at all, has done it...)
