### ISSUE TITLE
Ru'Aun Gardens Teleporters

### ISSUE THREAD

**Issue by TheMuffinPirate** [DarkstarProject/darkstar#1007]
All of the teleport pads in Ru'Aun Gardens are non functional.

**Comment by RunAwayDSP** [comment]
working for my server (updated on march 4th 2015). Could use more information about the issue.

**Comment by Scavenge** [comment]
very likely the offset in the zone lua or the lua for the whatsitcalled. pincerstone

**Comment by TheMuffinPirate** [comment]
All the teleporters are non functional, including the ones that are unrelated to pincerstones.

**Comment by maxtherabbit** [comment]
this doesn't seem to be a problem for anyone else, I'm going to close for now unless someone can corroborate
