### ISSUE TITLE
New Adventurer Status causes footsteps to be muted

### ISSUE THREAD

**Issue by BrosephJ** [DarkstarProject/darkstar#1008]
Create a new character, have New Adventurer Status icon left of your name, and your footsteps become muted.

This is what I've been trying to find for the past week and a half and now I've found it. The reason nobody had this issue is because they already had existing characters that weren't new adventurers. Please confirm my findings. I'm not certain if this qualifies as a server or client bug, though.

http://www.mediafire.com/view/k2bxqb46hyg5q5u/Recording-2015-03-01-0302-01.mp4

**Comment by TeoTwawki** [comment]
I've confirmed, he's correct. Having new adventurer flag mutes a few sound effects and is most noticeable with the footsteps.

**Comment by teschnei** [comment]
1affa83791a3864ec212aa0ff8319a93c6948aca
