### ISSUE TITLE
Charybdis PH Respawn @17 minutes

### ISSUE THREAD

**Issue by Mozzy4Ever** [DarkstarProject/darkstar#1009]
Charybdis' placeholder, according to Wiki (http://wiki.ffxiclopedia.org/wiki/Charybdis) should have a 5 minute respawn timer. Instead, it has a 17 minute 36 second one which is the "default" for the Sea Monk family

**Comment by Fiocitrine** [comment]
I feel this is depending on the server. If it's old school, it'll be 5 minute respawn. If it's newschool, most mobs will have a 5.5 respawn time.

**Comment by Mozzy4Ever** [comment]
But this one has a 17 minute 36 second time, not 5 or 5.5.
I'm on Era btw

**Comment by xdemolish** [comment]
@scavenge @sisternEra would need to double check the db cause custom content
