### ISSUE TITLE
Conquest overflow/underflow

### ISSUE THREAD

**Issue by LordKaT** [DarkstarProject/darkstar#1017]
Conquest calculations do not seem to bounds check to protect against integer underflow/overflow, resulting in powers that have minimal influence suddenly have staggeringly large influence.

Example: hosting a private server, while in East Ronfaure San d'Oria will control this area and the beastmen influence will drop significantly. After the next conquest update the influence will underflow from -2147483647 to 2147483647, squashing anything else in the area.

**Comment by LordKaT** [comment]
Here, I did some sanity checking for a 64-bit system. It's not portable to a 32-bit system. 32767/-32767 would be the absolute max/min under 32-bits, but the source base has some serious namespace issues when compiling under g++, making things like INT_MAX inaccessible. You could make it better by making iNum a pointer and passing numbers via reference but idgaf.

Now, after having a mudhole stomped into them, the Beastmen don't suddenly rise to power. Especially useful in newbie zones.

	/************************************************************************
    *    GainInfluencePoints                                                *
    *    +1 point for nation							                    *
    *						                                                *
    ************************************************************************/

    /* Arbitrary numbers thus far. */
    #define CONQUEST_MIN    -300000000
    #define CONQUEST_MAX    300000000

    /* Sanity checking. -lk */
    int BoundsCheck(int iNum, int iMin, int iMax) {
        if (iNum < iMin) { iNum = iMin; }
        if (iNum > iMax) { iNum = iMax; }
        return iNum;
    }

    void GainInfluencePoints(CCharEntity* PChar, uint32 points)
    {
        REGIONTYPE region = PChar->loc.zone->GetRegionID();
        if (region == REGIONTYPE::REGION_UNKNOWN)
            return;

        std::string Query = "SELECT sandoria_influence, bastok_influence, windurst_influence, beastmen_influence FROM conquest_system WHERE region_id = %d;";

        int ret = Sql_Query(SqlHandle, Query.c_str(), region);

        if (ret != SQL_ERROR && Sql_NextRow(SqlHandle) == SQL_SUCCESS)
        {
            int san_inf = Sql_GetIntData(SqlHandle, 0);
            int bas_inf = Sql_GetIntData(SqlHandle, 1);
            int win_inf = Sql_GetIntData(SqlHandle, 2);
            int bst_inf = Sql_GetIntData(SqlHandle, 3);

            /* 2147483647 */
            switch (PChar->profile.nation)
            {
                case 0:
                {
                    int total = bas_inf + win_inf + bst_inf;
                    total = this->BoundsCheck(total, CONQUEST_MIN, CONQUEST_MAX);
                    if (total == 0) total = 1; // Div by 0 crash
                    double bas_rat = (float)bas_inf / total;
                    double win_rat = (float)win_inf / total;
                    double bst_rat = (float)bst_inf / total;
                    san_inf += points;
                    san_inf = BoundsCheck(san_inf, CONQUEST_MIN, CONQUEST_MAX);
                    bas_inf = (total - points) * bas_rat;
                    bas_inf = BoundsCheck(bas_inf, CONQUEST_MIN, CONQUEST_MAX);
                    win_inf = (total - points) * win_rat;
                    win_inf = BoundsCheck(win_inf, CONQUEST_MIN, CONQUEST_MAX);
                    bst_inf = (total - points) * bst_rat;
                    bst_inf = BoundsCheck(bst_inf, CONQUEST_MIN, CONQUEST_MAX);
                    break;
                }
                case 1:
                {
                    int total = san_inf + win_inf + bst_inf;
                    total = this->BoundsCheck(total, CONQUEST_MIN, CONQUEST_MAX);
                    if (total == 0) total = 1; // Div by 0 crash
                    double san_rat = (float)san_inf / total;
                    double win_rat = (float)win_inf / total;
                    double bst_rat = (float)bst_inf / total;
                    bas_inf += points;
                    bas_inf = BoundsCheck(bas_inf, CONQUEST_MIN, CONQUEST_MAX);
                    san_inf = (total - points) * san_rat;
                    san_inf = BoundsCheck(san_inf, CONQUEST_MIN, CONQUEST_MAX);
                    win_inf = (total - points) * win_rat;
                    win_inf = BoundsCheck(win_inf, CONQUEST_MIN, CONQUEST_MAX);
                    bst_inf = (total - points) * bst_rat;
                    bst_inf = BoundsCheck(bst_inf, CONQUEST_MIN, CONQUEST_MAX);
                    break;
                }
                case 2:
                {
                    int total = san_inf + bas_inf + bst_inf;
                    total = this->BoundsCheck(total, CONQUEST_MIN, CONQUEST_MAX);
                    if (total == 0) total = 1; // Div by 0 crash
                    double san_rat = (float)san_inf / total;
                    double bas_rat = (float)bas_inf / total;
                    double bst_rat = (float)bst_inf / total;
                    win_inf += points;
                    win_inf = BoundsCheck(win_inf, CONQUEST_MIN, CONQUEST_MAX);
                    san_inf = (total - points) * san_rat;
                    san_inf = BoundsCheck(san_inf, CONQUEST_MIN, CONQUEST_MAX);
                    bas_inf = (total - points) * bas_rat;
                    bas_inf = BoundsCheck(bas_inf, CONQUEST_MIN, CONQUEST_MAX);
                    bst_inf = (total - points) * bst_rat;
                    bst_inf = BoundsCheck(bst_inf, CONQUEST_MIN, CONQUEST_MAX);
                    break;
                }
                default:
                    break;
            }
            Sql_Query(SqlHandle, "UPDATE conquest_system SET sandoria_influence = %d, bastok_influence = %d, "
                "windurst_influence = %d, beastmen_influence = %d WHERE region_id = %d;", san_inf, bas_inf, win_inf, bst_inf, region);
        }
    }

	/************************************************************************
    *    LoseInfluencePoints                                                *
    *    -x point for nation							                    *
    *    +x point for beastmen                                              *
    ************************************************************************/

	void LoseInfluencePoints(CCharEntity* PChar)
	{
		REGIONTYPE region = PChar->loc.zone->GetRegionID();
		uint16 point = 0;

		switch (region)
		{
			case REGION_RONFAURE:
			case REGION_GUSTABERG:
			case REGION_SARUTABARUTA:
			{
				point = 10;
                break;
			}
			case REGION_ZULKHEIM:
			case REGION_KOLSHUSHU:
			case REGION_NORVALLEN:
			case REGION_DERFLAND:
			case REGION_ARAGONEU:
			{
				point = 50;
                break;
			}
			case REGION_QUFIMISLAND:
			case REGION_LITELOR:
			case REGION_KUZOTZ:
			case REGION_ELSHIMOLOWLANDS:
			{
				point = 75;
                break;
			}
			case REGION_VOLLBOW:
			case REGION_VALDEAUNIA:
			case REGION_FAUREGANDI:
			case REGION_ELSHIMOUPLANDS:
			{
				point = 300;
                break;
			}
			case REGION_TULIA:
			case REGION_MOVALPOLOS:
			case REGION_TAVNAZIA:
			{
				point = 600;
                break;
			}
		}
        std::string Query = "SELECT sandoria_influence, bastok_influence, windurst_influence, beastmen_influence FROM conquest_system WHERE region_id = %d;";

        int ret = Sql_Query(SqlHandle, Query.c_str(), region);

        if (ret != SQL_ERROR && Sql_NextRow(SqlHandle) == SQL_SUCCESS)
        {
            int san_inf = Sql_GetIntData(SqlHandle, 0);
            int bas_inf = Sql_GetIntData(SqlHandle, 1);
            int win_inf = Sql_GetIntData(SqlHandle, 2);
            int bst_inf = Sql_GetIntData(SqlHandle, 3);
            int total = san_inf + bas_inf + win_inf;
            total = this->BoundsCheck(total, CONQUEST_MIN, CONQUEST_MAX);
            if (total == 0) total = 1; // Div by 0 crash
            double san_rat = (float)san_inf / total;
            double bas_rat = (float)bas_inf / total;
            double win_rat = (float)win_inf / total;
            bst_inf += point;
            bst_inf = BoundsCheck(bst_inf, CONQUEST_MIN, CONQUEST_MAX);
            san_inf = (total - point) * san_rat;
            san_inf = BoundsCheck(san_inf, CONQUEST_MIN, CONQUEST_MAX);
            bas_inf = (total - point) * bas_rat;
            bas_inf = BoundsCheck(bas_inf, CONQUEST_MIN, CONQUEST_MAX);
            win_inf = (total - point) * win_rat;
            win_inf = BoundsCheck(win_inf, CONQUEST_MIN, CONQUEST_MAX);

            Sql_Query(SqlHandle, "UPDATE conquest_system SET sandoria_influence = %d, bastok_influence = %d, "
                "windurst_influence = %d, beastmen_influence = %d WHERE region_id = %d;", san_inf, bas_inf, win_inf, bst_inf, region);
        }
	}

**Comment by teschnei** [comment]
I do not know why you would use INT_MAX over the specific sized ones in
cstdint (like INT32_MAX), unless you actually did want them to be different
on different platforms (which makes no sense, unless I'm missing what you
were planning to use it for)

**Comment by teschnei** [comment]
But, either way, the more emails I get about it the more likely I am to
remember to look at it.. I'll see if I can whip it back into shape tonight

**Comment by LordKaT** [comment]
While compiling, there were several instances of INT_MAX being used in the code, which caused namespace issues. I had assumed this was standard to the code.

**Comment by teschnei** [comment]
I'd have to look to see where they are to give you an answer on that one.
Most of the stuff in common is external stuff that we don't touch often, so
they're usually behind on standards/etc

**Comment by LordKaT** [comment]
Not a big deal. I was just offering up one solution to the issue.
