### ISSUE TITLE
some status effects removed when they should not be

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1025]
Set status effect in database to not be removed by anything, not zoning, not death, nothing. Now log out and back in. status effect gone (or zone). Not sure wtf the trigger is exactly. Some stay, some don't, but each status effect that does/doesn't is consistent about it, its not random. GoV food buff will stay and GoV Prowess buff will be lost, no matter how you set the flagging. Flag seems to be ignored entirely.

**Comment by TeoTwawki** [comment]
(yes I know its called on zone, not on logout, but as much as I'd like them not to be those are basically the same thing here)

**Comment by maxtherabbit** [comment]
did your test character happen to be in a party when testing this?

**Comment by maxtherabbit** [comment]
I can't duplicate this bug on current rev, I suggest you try setting breakpoints at the beginnings of CStatusEffectContainer::DelStatusEffectsByFlag and CStatusEffectContainer::DelStatusEffectSilent

**Comment by TeoTwawki** [comment]
I've seen it both solo and party, which status effect were you trying with?

**Comment by maxtherabbit** [comment]
pro/shell/ss/phalanx/blink/aquaveil/enspell/barspell/refresh/regen/haste

pretty much anything I could cast on my self

**Comment by TeoTwawki** [comment]
2 simple proofs of bug, reproducible on fresh clone with clean/new database:
changed flag of EFFECT_PROWESS to be 0x200 (512, silent removal) instead of 0x300 (768, silent remove and wears off on zone). Get the effect and zone. watch it get removed. This same change was in the pull request I cancelled.

created dummy effect named EFFECT_TESTDUMMY with ID 999, set flags 512 in db (thats 0x200, silent removal), used a script to do
```lua
player:addStatusEffectEX(EFFECT_TESTDUMMY, EFFECT_CONCENTRATION,0,0,60); -- confront.status used to give it a visible icon, any other effect will do
```
used [at]goto <me> to zonemyself. Boom effect gone.

And yes I def ran the sql change and restarted. This cannot be just me. And setting the flag food uses prevents things from wearing off, without using the zone flag at all. So I guess I could cheat and use that flag, but I have no idea what side effects that could cause.. I'll be asleep shortly I'll talk to you tomorrow.

**Comment by maxtherabbit** [comment]
I swear I'm trying to figure this out, but I can't find anything in core that explains it yet

try unsetting flag 0x200 and see if it stops removing on zone

**Comment by TeoTwawki** [comment]
Still gets removed on zone.

**Comment by xdemolish** [comment]
is this still a thing?

**Comment by TeoTwawki** [comment]
yes.

**Comment by xdemolish** [comment]
so... status effects with 0 duration (infinite duration) don't get saved
not sure why CStatusEffectContainer::KillAllStatusEffects() skips removing them from the list either

**Comment by teschnei** [comment]
I don't know why it doesn't save infinite durations, but killall's behavior
is intended. It's mostly just used for clearing effects on death, and
sometimes a mob needs a permanent effect to do what it's supposed to.
Though to be honest, I am not sure why I did not check the effect flag for
death when I wrote that function
