### ISSUE TITLE
Enemies that kinda sorta spawn almost

### ISSUE THREAD

**Issue by LordKaT** [DarkstarProject/darkstar#1034]
In Beadeaux I have noticed several mobs "sorta" spawn - they have AI, they attack me, they link, etc ... but they're nowhere to be seen! They exist as a point on the map without any loaded models or textures. This makes them impossible to target (which also makes Sandy 4-1 impossible).

This happens with a Bronze Quadav, and almost always with De'Vyu Headhunter.

Can anyone point me in any direction where I can look to solve this issue?

**Comment by teschnei** [comment]
depends, does their name show up?

**Comment by LordKaT** [comment]
Their names are not visible in game; however, their actions appear in the battle log, and they ARE targetable once they start to attack you. They just appear to be the floor (and no, I checked, they're not under the map either).

**Comment by teschnei** [comment]
check your server log, do you get "NPC is wrong type" or something similar to that?

**Comment by LordKaT** [comment]
Nope, not a damn thing in the log.

**Comment by Scavenge** [comment]
name/model could be hidden? i strangely found a few of the jailers would spawn this way so i had to put in things like name/mob? :isHidden false etc.

**Comment by teschnei** [comment]
check if your client received the packet to spawn it or not (use a packet capper or set breakpoints in the source)

**Comment by LordKaT** [comment]
I can confirm that the client is receiving the packets.

**Comment by vampirexhunter** [comment]
are you sure the mobs are not aggro'in from underneath the floor? I know in Beaudeaux in certain spots, you can aggro mobs beneath you.

**Comment by LordKaT** [comment]
No they are not spawning under the ground. A similar problem occurs in the Cloister of Tremors where the ??? to get the Tremorstone is not spawning. No packets are being sent that actually spawns it.

**Comment by Joeyjohjjo** [comment]
Do you have Wings of the Goddess installed? Wings of the Goddess changed the models of several monsters in old regions.

**Comment by LordKaT** [comment]
Huh. Yeah we do have WotG installed. I'll have to look into it.

**Comment by LordKaT** [comment]
this issue appears to have fixed itself over the past 20 days.
