### ISSUE TITLE
More like upper disconnect's tower

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1041]
Zone into lower delkfutt's, pass through the door that requires the key, make your way to the door that leads to upper delkfutt's, use the updraft that takes you to the tenth floor. R0. R0 R0 R0 R0 R0 R0 R0. Every single time. Then log in two or three times and attempt to move off of the elevator to save yourself. Eventually the server recognizes you're no longer standing on the elevator on the tenth floor and allows you to connect without instant R0. Forever and ever. This happened six months ago before I took a hiatus, this happened when for some idiotic reason it was one of the first places I visited after returning, it happened again just now. This is currently on Old school server and has occurred on more than one machine from more than one IP. Maybe we can at least change the dialogue for the door leading to upper delkfutt's to read "JUST DON'T FUCKING BOTHER."

**Comment by teschnei** [comment]
i was already planning on fixing the cause tonight or tomorrow

**Comment by timmifshode** [comment]
Would be fantastic, I'm actually on attempt number 6 right now to just get my character out of the zone, but the one time I thought I had survived the dc, it was actually just the client freezing before the r0's started appearing.

**Comment by nesstea** [comment]
I lowered the packet buffer size in the config to 1200 and those issues disappeared.
