### ISSUE TITLE
Retaliation poorly implemented

### ISSUE THREAD

**Issue by vickycat** [DarkstarProject/darkstar#1065]
http://wiki.ffxiclopedia.org/wiki/Retaliation

Issues:
1. You can retaliate attacks from enemies you are not facing.
2. 100% proc rate (basically Hundred Fists against Charybdis even though you'll die. try it on test server it's funny).
3. Procs even when using "defensive job abilities" such as Defender
4. If you take the first hit from an enemy with multiple attacks (such as a triple attack from bunnies), you will retaliate against all following attacks even if they are misses.

**Comment by teschnei** [comment]
3 is correct (you can retaliate with defender up)

**Comment by TeoTwawki** [comment]
1. when i tested I didn't get a single proc with my back to the enemy,

2. I tested that quite a bit and definitely was not seeing anywhere close to 100% proc rate. retaliation is based on hitrate, and there is not even a log message when it doesn't proc. If you go up againast charby at lv99 I wouldn't be surprised to find your hitrate capped.

3. that does not mean what you think it does. It means if another defensive ability (parried the attack) happens, you cannot retaliate.

4. That may be a problem. Didn't think of that.

**Comment by TeoTwawki** [comment]
someone broke something, just went out and retested on latest trunk...I don't understand that, far as I know hasn't been touched since I implemented it.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/blob/cc409d74a1059f2db98efdc6e12cffcd4010a796/src/map/utils/battleutils.cpp#L545

That was working before..

**Comment by maxtherabbit** [comment]
isFaceing(PAttacker->loc.p, PDefender->loc.p, 40)

the arguments are reversed - PAttacker is the mob here

**Comment by TeoTwawki** [comment]
it was working back when I pull requested, and I didn't change it max. And counter, 3rd eye, etc have those arguments in same order.

**Comment by TeoTwawki** [comment]
After testing it, max is right and I've fixed that part. Got several hits in my log with no retaliation proc proving ist not 100%, and saw several instances where it didn't proc on all hits of a multi attack.

**Comment by maxtherabbit** [comment]
any remaining issues with this are attributable to mobs having low evasion, the retaliation implementation is good to go
