### ISSUE TITLE
Dread Spikes

### ISSUE THREAD

**Issue by TheMuffinPirate** [DarkstarProject/darkstar#1069]
Dread Spikes lasts for its full duration regardless of damage drained, It should wear off after draining 50% of the casters max hp.

**Comment by maxtherabbit** [comment]
is the max drain value calced at casting time?

**Comment by TheMuffinPirate** [comment]
I'm not sure but that sounds like the only way that would make sense.

**Comment by Hozu** [comment]
This is resolved now with https://github.com/DarkstarProject/darkstar/commit/1559417cb47e932791e1d1479c8efe04bd9ce443
