### ISSUE TITLE
HP and MP do not reset to 100% immediately after level up.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1074]
To work around this issue, you can /heal (which will tick both up to 100% immediately), or acquire EXP again by defeating another enemy, which will also cause both to tick up to 100% immediately.

Edit:

When in a party with someone who has leveled up; other players will not see that persons HP/MP reset to 100%, even if the person who leveled up has seen it tick up.

**Comment by teschnei** [comment]
sounds like the packet isn't being sent

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/compare/824dd2c476c6...47854cf98e37
