### ISSUE TITLE
Puks using no TP moves

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1079]
Lua files exists and the mobskills exists for the mob "Puk"

SELECT \* FROM `mob_skill` where family_id=198;

Doesn't use them.

**Comment by nesstea** [comment]
1/8 mobs used zephyr mantle once. nothing else.

**Comment by Hozu** [comment]
It seems like specific Puks are unable to gain TP under most circumstances for some unknown reason. I know it's that because when I kept casting physical BLU spells on them they would eventually use one of their mobskills, so it's not like they can't use them.

**Comment by zynjec** [comment]
Unable to repro this, open another issue if someone is still having this issue.
