### ISSUE TITLE
Antican tag not obtainable.

### ISSUE THREAD

**Issue by Zazmo** [DarkstarProject/darkstar#1089]
None of the qms in quicksand caves give the antican tag item. I tried looking through the script files here 
https://github.com/DarkstarProject/darkstar/tree/master/scripts/zones/Quicksand_Caves/npcs 
but the antican tag does not appear to be coded for any of the qms.  Tribunus (the mob spawned using antican tag) appears to be coded correctly though. Thanks.

**Comment by whasf** [comment]
This isn't a bug, it's just not coded yet.
