### ISSUE TITLE
Monsters aggro through the floor in certain areas, need z-index checking.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1092]
Might be wise to make the z-index aggro range configurable until its perfected

**Comment by teschnei** [comment]
Y index*. Should be +/-16. No point in being configurable since it becomes
redundant with navigation anyways

**Comment by dazusu** [comment]
Y yeah sorry. Was thinking of FFACE's implementation which has y/z reversed. Either way mobs in KRT aggro through the floor namely bats.

**Comment by teschnei** [comment]
I think 16 should be enough. Maybe less, iirc stuff in the main area of
korroloka won't aggro people on the walkways, and that could be less than
16. Maybe 8.

**Comment by Joeyjohjjo** [comment]
In my experience, Gigas do indeed aggro players on the walkways in Korroloka.

**Comment by TeoTwawki** [comment]
Vertical sight agro range and and agro types could use diff value maybe.

**Comment by bendangelo** [comment]
The navmeshes fix this issue by checking line of sight before aggro, so just enable navmeshes. Closing.
