### ISSUE TITLE
Auction houses only return 12 of items that stack to 99

### ISSUE THREAD

**Issue by Joeyjohjjo** [DarkstarProject/darkstar#1094]
Examples are scorpion arrowheads or imperial bronze pieces.
I think the issue might start here:
https://github.com/DarkstarProject/darkstar/commit/234c3c9b7db417c7572f9fba2e2836a2b87102ad#diff-96f1a820c5729557122d0622acd1f8c9R498

**Comment by whasf** [comment]
Why are you pointing to the expire code, that has nothing to do with what's returned for a search

**Comment by teschnei** [comment]
I'm pretty sure he meant that expired items don't send stacks of 99

**Comment by Joeyjohjjo** [comment]
Yeah, I meant that when you put a stack of 99 items on the auction house and they get sent back to your delivery box after the time limit expires, you only get 12 of those 99 items back. Stacks of 99 still show up in auction house searches.

**Comment by maxtherabbit** [comment]
wait so I was justified in assigning this to @whasf after all?

**Comment by teschnei** [comment]
Yeah? He's the one who wrote it

**Comment by whasf** [comment]
fixed in 01d570c8de56e9e86fa50c59d56eaeb7b6fe9985
