### ISSUE TITLE
Deadly zonelines

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1096]
Oldschool server, seems to have issue since update around 8pm est that 2/3 times zoning causes infinite data loading screens, and characters while multiboxing to get mixed up between each other. Zoning into dyna-bastok caused every character to dc or mixup upon zone and then full server crash.

**Comment by maxtherabbit** [comment]
I blame demo

**Comment by xdemolish** [comment]
i'd take the blame if the bug only bug'd out recently, but im pretty sure this has been an issue since like forever

**Comment by maxtherabbit** [comment]
did this happen only upon entering dynamis or what?
if it happened elsewhere, were you in a party at the time?

**Comment by timmifshode** [comment]
Happens at any time, yes in a party but happens outside of one as well. This was not an issue until after the most recent update

**Comment by xdemolish** [comment]
@whasf could you get me a dump next time this happens

**Comment by xdemolish** [comment]
ya, wasn't able to reproduce the mixup/infinite downloading data
the crash seems to be an unrelated problem though

**Comment by maxtherabbit** [comment]
*think* this is fixed
