### ISSUE TITLE
Crash when disbanding alliance when last person left

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#1101]
https://www.dropbox.com/s/pxfw7ahj1vomyb4/GS_03-17-2015_11-29.7z?dl=0

**Comment by Scavenge** [comment]
did we already fix this? i remember kj saying there was 4 parties in the alliance and 3 were empty when it happened

**Comment by xdemolish** [comment]
havent seen an alliance crashdump in like a month so l8r
