### ISSUE TITLE
Windurst Misson 7-2 'Awakening of the Gods' Known issues:

### ISSUE THREAD

**Issue by Djcocha** [DarkstarProject/darkstar#1105]
(DSOldSchool Server)
So, at first I had to get GM to cancel(or something similar not sure exact terminology should be used) quest list from Leepe-Hoppe before it gave me the mission CS instead of Fenrir quest (The Moonlit Path).

After that I got Cursed Key from Bonze Marberry, and when trading Cursed Key to the Granite Door see: #1086 

So after both Gedads fix, then Whasf fix, I finally got Key Item and now I take it back to Leepe-Hoppe and he is ignoring the mission again. I have since had GM manually fix for my individual character but was told to post bug so a real fix can be made.

**Comment by zynjec** [comment]
Stale, if this is still an issue please open another issue.
