### ISSUE TITLE
Feature request: lua mobDisengage()

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1106]
I am not very good at writing lua functions.

Many of the ENMs I'm trying to code will need some way to disengage entirely. Just wondering if a function could be written to use the action ACTION_DISENGAGE.

**Comment by teschnei** [comment]
They will just go back to attacking the second they get hit with something
new. I don't think they disengage on retail (they stay in battle
animation), so you should figure out how to script them to do what you want
in their battle script (it should currently be possible)
