### ISSUE TITLE
Ppl repeatedly "fixing" same npc's

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1117]
Short version: f---ing Halver.

He need completely redone instead of a million and one patchwork fixes that fix the mission 1 person is on and break another for someone else. I am not volunteering. The indention is such sh--t I can't even finish reading that script to see which thing is wrong now.

Also, years ago the earliest coded missions started off with status 1, and later it was decided all missions start at zero and only use/increment that var when actually required (makes much more sense). Look way back in the history (before the move to github, way before) and you can even see the commit I am talking about.

However when this was changed, to avoid breaking mission progress of ppl mid mission a bunch were made to jump straight from zero to a value of two, skipping the value of one altogether. Since then, people keep "fixing" these by making things check for status of one before setting it to two. Multiple times now, i have seen these older missions "fixed" only to immediately have people unable to progress after pulling the changes. In most of these cases the only way to get a var of one is from another mission (usually the optional repeats) leaving a var behind, or a GM messing with player vars because they dunno wtf they are doing.

Halver has multiple error right now that will stop some players dead in their tracks depending on which parts of his rats nest of conditionals fire off, but he's not the only mission npc with probs, its all the older pre-zilart missions that jumo from zero to two that need reviewed. I'm going to go take a look at a few and try to make them go zero-one-two and ensure they work start to finish...But I ain't touching Halver. /endrant

**Comment by Novah1** [comment]
A lovely shout out to Yoran-Oran and Shantotto, as well.

**Comment by TeoTwawki** [comment]
Hey diddly doodle, I heard Shantotto screwed the poodle!

**Comment by Ex0r** [comment]
I think the best solution for this, would be to completely redo the Halver script, and anybody who is on this mission/questline will need to restart it from the beginning to ensure they are able to finish it.
