### ISSUE TITLE
Namas Arrow SC Properties

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1139]
Namas arrow WS is Opening and closing Darkness, when it's only SC properties are 

Skillchain Properties: Light/Distortion

It's also doing the incorrect of damage as it's hitting much harder then sidewinder, when it's damage should be marginally less then Sidewinder (as it was on retail anyway). That's easily fixed in lua though. Thanks for your time.

**Comment by Fr0zt** [comment]
I just checked both sidewinder and namas arrow's scripts and they are correct. Are you testing on the same mob lvl and type for consistent results?
