### ISSUE TITLE
/sea all seems to be capped at 23 players; can never get more to display - even when more people are online.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1141]
This could be due to other issues; however - there is a message in the chat log indicating that the /sea all list has been truncated; though why it would be cut as short as 23 people is uknown to me.

**Comment by teschnei** [comment]
unfortunately, search packets are a vacuum nobody wants to look at (which is why half the search parameters dont work either)

**Comment by xdemolish** [comment]
liar i added half+1 of them a while ago

**Comment by zynjec** [comment]
This appears to have been fixed at some point, if this is still an issue please open another issue.
