### ISSUE TITLE
Crafting NPCs hard crash the server

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1153]
I get an array out of bounds. Pretty much going to assume KJ onry.

![screenshot 2015-03-24 23 56 24](https://cloud.githubusercontent.com/assets/1483915/6820666/9bb4b1c0-d28e-11e4-8817-6a9065f61eba.png)

Happens when I talk to any of the NPCs with crafting above 30.

**Comment by maxtherabbit** [comment]
I didn't get a crash, but found some issues in crafting.lua trying to send keyitem array in cs, fixed in 0dd588a

lmk if you still have a problem, but that may fix this issue

**Comment by teschnei** [comment]
click retry

**Comment by nesstea** [comment]
It's only crashing if you have rank 10 it seems.

**Comment by maxtherabbit** [comment]
@teschnei the problem here is the GPItem vector array is only 7 elements long, and rank 10 attempts to index m_GPItems[rank - 3]

idk what you want to do about it so I'll let you handle it

**Comment by teschnei** [comment]
AFAIK rank 10 (expert) isnt implemented on DSP

**Comment by teschnei** [comment]
I'll fix it regardless of course, though
