### ISSUE TITLE
Force-popped NMs are not claimed on pop (for example, WHM AF1 NM, and NIN SJ Quest Leeches)

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1157]
The initial popper should have hate on pop; and monsters should be claimed.

Currently a random person gains hate, and the mosnter(s) remain unclaimed.

**Comment by nesstea** [comment]
You can update the enmity but it doesn't claim them. I would like there there to be a lua function to set the claim. :)

**Comment by nesstea** [comment]
@TeoTwawki mentioned something about adding a lua bind for us at some point. :+1:

**Comment by TeoTwawki** [comment]
I'll take a look sometime in next few days, see if I can do that

**Comment by jovianlabs** [comment]
If this hasn't been done yet, I have added functionality for this.  I can post an update for it this evening, I added an LUA function as well.

**Comment by TeoTwawki** [comment]
if you got something to pull request then yes please do. My main monitor died and its been difficult for me to get anything done because I can't see very well on this low res pos I am currently using.

**Comment by Setz0r** [comment]
I have submitted the pull request #1397 .  You can now set monsters as claimed once spawned via updateClaim(player) in script.  I put an example in the commit comment.

**Comment by TeoTwawki** [comment]
Excellent.

**Comment by nesstea** [comment]
tyty
@Setz0r WTB your fishing changes.

**Comment by xdemolish** [comment]
i'd do it but too many NMs to go through

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/92567ef6c810ba5c285077000d1b10f07068f056
