### ISSUE TITLE
When "all mobs drop gil" is turned on; and you are in an alliance - gil is only distributed between the leading party.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1159]

**Comment by nesstea** [comment]
I verify this.

**Comment by TeoTwawki** [comment]
But when its off a normal gil drop gets spread out to whole Alliance?

**Comment by dazusu** [comment]
It's never being alliance distributed, as only the party is being looped through in the code; needs an alliance check and I guess each party looped individually. I need to learn to use git properly so I can fix this shit too ^_^

**Comment by TeoTwawki** [comment]
K so its not really the setting then. That's what I thought, because was pretty sure that setting only overrides the individual mob canDropGil() check.

**Comment by dazusu** [comment]
Actually, it seems like the gil is going to the party that gets the kill; not necessarily the lead party

**Comment by TeoTwawki** [comment]
I see, in the prob is in in charutils around line 2823 in the DistributeGil() function. I think I can fix this soonish if nobody beats me to it.

**Comment by TeoTwawki** [comment]
Will have a pull req for this up sometime tomorrow after I multibox myself an alliance to test and be sure I didn't break anything.

**Comment by maxtherabbit** [comment]
make @TeoTwawki a dev so I can assign him

**Comment by xdemolish** [comment]
i already called for everyone to be dev'd for like a minute so i can assign them all issues and de-dev them :(

**Comment by TeoTwawki** [comment]
And done!

**Comment by nesstea** [comment]
ty teo
