### ISSUE TITLE
Draw in may drop players below floor in some circumstances

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1162]
If a mob uses draw in and is not on a perfectly level surface, such as a terrain bump or a slope/hillside, players have a chance to have their position set below the floor. This might be correctable by simply tweaking the Y coordinate slightly, since the client will drop the player down to the ground before they can even see where they landed. I haven't tried it busy with other stuff.

**Comment by Scavenge** [comment]
this can happen during G2 with the boreal hound/coeurl/tiger, whichever ones draw in, being in those narrow caves.  also tiamat/jorm/fafnir ifyou're too close to a wall, so the height value might fix the floor terrain but in xarcabard doing G2, we were about the same height as before except we were on the other side of the wall

**Comment by TeoTwawki** [comment]
If mob moved into wall at all just prior the pos data used with draw in would do that too. No good way to avoid that without fixing the fact mob can go into wall though (navmesh stuff currently only method).

**Comment by bendangelo** [comment]
I will change draw in to place you a little bit higher than the ground. To ensure players don't get stuck I'll use the map's navmesh to confirm the draw-in location is valid.

**Comment by TeoTwawki** [comment]
Thanks Ben.
