### ISSUE TITLE
Server crash at loading zones

### ISSUE THREAD

**Issue by thyris** [DarkstarProject/darkstar#1167]
https://drive.google.com/file/d/0B1lzkNs9FPVocFNnU1FuVHd6akk/view?usp=sharing

Here's the link to my dump file.  The program crashes during the step loading zones, and there appears to be multiple break points.

**Comment by teschnei** [comment]
Are you using trunk code without any modifications?

**Comment by thyris** [comment]
I customized the server XP rates and allowed all the expansions,  I changed some other rates as well according to the comments within some of the .conf files.  I haven't touched any of the other bits of code.

**Comment by teschnei** [comment]
OK, that should all be fine.

**Comment by thyris** [comment]
Thanks for such a prompt response.  I was complaining in the forum about
this process, cuz I'm old and stubborn and am used to using svn from back
in the mangos days :P  But I see now that this is probably the easiest bug
fix and tracking solution, and how cool that you can just reply to the
email?!

**Comment by teschnei** [comment]
That's how I can always answer quickly from work :)

**Comment by xdemolish** [comment]
ya, it's why i linked that wiki page to get a dump on here so we'd be notified instantly on any updates (the lazy link wasn't an attack on you, just linking you to the best way to inform us of server crashing bugs)

**Comment by thyris** [comment]
I understand, and thank you :)

**Comment by xdemolish** [comment]
is harvest festival enabled? that could be the cause of the crash

**Comment by teschnei** [comment]
Its March. Who harvests in March?

**Comment by xdemolish** [comment]
it was one of the h's, just couldn't remember which!

**Comment by thyris** [comment]
I have the halloween festival thing all year round enable from one of the configuration files.  Perhaps that's the issue, I'll edit that file and disable it and see what happens

**Comment by thyris** [comment]
Fixed.

**Comment by teschnei** [comment]
Still a bug, though. Get fixin, demolish

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/issues/539

**Comment by xdemolish** [comment]
COUNTER

**Comment by teschnei** [comment]
Shit, forgot I said that.

Oh well, won't be hard to do. I'll give you the design and you can do it!

**Comment by thyris** [comment]
Hi there!
Thyris has invited you to Pinterest.
Sign up today to discover and save creative ideas for cooking, travel, home improvement and more.Accept Invite: https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&amp;invite_code=5d918e404c772ddc93eaf679afeb280a&amp;utm_campaign=binvite&amp;e_t=68281bb1d56f4c0c865bc81af8517b5d&amp;utm_medium=2000&amp;utm_source=31&amp;e_t_s=cta
See what Thyris has discovered



LOL!
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=1&utm_content=99290366757416736&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



Happy Patient Prey and crap I forgot what the last ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=2&utm_content=99290366755144063&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



Circular Gallifreyan Alphabet. More detailed makes me want to open ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=3&utm_content=99290366757516825&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



Circular Gallifreyan Alphabet. More detailed makes me want to open ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=4&utm_content=99290366757516826&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



Guys, Britain did it...they set fire to the rain ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=5&utm_content=99290366757516830&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



hmm
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=1&utm_content=99290366754282439&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



haha, this is kind of awesome, and kind of ...conflicting ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=2&utm_content=99290366754285138&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



Einstein - &#34;The only reason for time is so that everything ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=3&utm_content=99290366757516821&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



britnickkesh.jpg (550×350)
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=4&utm_content=99290366757436344&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



ke-ha-britney-spears-nicki-minaj.jpg (650×366)
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=5&utm_content=99290366757436345&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



Everything We Need to Know We Learned from Disney Movies ...
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=6&utm_content=99290366757436443&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000



LessThan3research by Ke$ha&amp;βritneyβ$Bit$h on SoundCloud
https://www.pinterest.com/invited/?inviter_user_id=99290504193114981&invite_code=5d918e404c772ddc93eaf679afeb280a&utm_campaign=binvite&utm_term=7&utm_content=99290366757436509&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_source=31&e_t_s=pins&utm_medium=2000


Pinterest: http://www.pinterest.com/Pinterest/?utm_campaign=binvite&e_t=68281bb1d56f4c0c865bc81af8517b5d&utm_medium=2000&utm_source=31&e_t_s=footer
Facebook: https://www.facebook.com/Pinterest
Twitter: https://www.twitter.com/Pinterest
Google: https://plus.google.com/+Pinterest/
Blog: http://blog.pinterest.com


Don't want to receive this type of email? https://www.pinterest.com/email/unsubscribe/?od=tydDXumw5EkpMv2wbOCnEg7WIdzDoqXfcvNvRl4TQDNNjaC126isiXMvL%2FVckt8JqSu9TSvY7B60%0AUoKiPQgqYSdd94h2elfAT%2FDe%2BuAVHRMdAcGpKxH%2FsQUGThYDqzhkIqLMbot2qtBGiAT5xPyUnyBp%0A%2BT3L2edx66m4FPqb2xvTdT9k3fiRU%2BGRJktS8p1MEWCuRzcKfAl8UGhAQmymIJJDrBmXvZbosZqU%0A5x3DGneFvrLMsjBlL%2B3%2F0R6KKj3Cxo7wnihV3XHE0d9Q75Uf8YFv1uv9VWsmJ2sJk8oWDBXX5Dj%2B%0A6mSyQ%2F%2Ff7rIcoCB3893J%2BonVG6SfbBtYQ6HwS6DGV%2B2yjgxTJ9Eaa7WSrc%2BAJ6vojYP7E0rc4qhe%0AQOzZeuDP0hvnOvxLYGrymNefkaNwEAx%2BsJQrXCQi2Kc0sy3h3ggc51LQgHD9FrnUOYdrj9sVAcVj%0AEa3j5W5EoSAMkghyL8pNOb5ab%2Bzd5PkQbd%2F7tdqGSbE0S75mTTgGMUiO9CLgI6wnV%2Foh7HwygIsQ%0A3gQ9Qo2sTBWKTzqGQL%2B99RUJ89h%2B6%2FpzmC3i7FfzkasT%0A&amp;user_id=cmVwbHkrMDBiMjE0NTY4YzIyNGVlOTRkY2M2Nzc4OTgyZWJhNzNhOTI2ZjQ5NzA0NzhlNTNkOTJj%0AZjAwMDAwMDAxMTEyYzM4NzI5MmExNjljZTAzZGEzYWZkQHJlcGx5LmdpdGh1Yi5jb20%3D%0A&amp;utm_campaign=binvite&amp;e_t=68281bb1d56f4c0c865bc81af8517b5d&amp;utm_medium=2000&amp;utm_source=31&amp;e_t_s=footer

Have a question? Visit our Help Center: https://www.pinterest.com/help/?utm_campaign=binvite&amp;e_t=68281bb1d56f4c0c865bc81af8517b5d&amp;utm_medium=2000&amp;utm_source=31&amp;e_t_s=footer

Copyright Pinterest, Inc. * All Rights Reserved.
Privacy Policy: https://www.pinterest.com/_/_/about/privacy/
Terms and Conditions: https://www.pinterest.com/_/_/about/terms/
