### ISSUE TITLE
Bastok mission beyond Fetichism unreachable through gameplay options (trade crystals or repeat Fetichism) [possible rank system issue?]

### ISSUE THREAD

**Issue by thyris** [DarkstarProject/darkstar#1168]
My character is up to this mission and can't advance beyond it in any way through gameplay (I also don't know if there's a GM way to increase rank points or not, but I'd be happy to know of it if there is) I've turned in the fetichism quest several times and the rank points do not increase.  I'd like to try to fix it though, I'm just not sure where to look.  My primary focus on fixing bugs within my own server will be on storyline advancement specifically, and I'll be repairing (and reporting here to figure out where to look) anything that stops my character from continuing the storyline, and this is the first :)

**Comment by teschnei** [comment]
your rank points are stored in char_profile, i believe you mentioned trading to guards didnt work either - more specific would be helpful (did he take your crystals? are there any errors in the server log?) 

otherwise it might just be that someone forgot to add rank points when you finish fetichism

**Comment by thyris** [comment]
I think the issue is only with fetichism's rank updates, I just remembered something totally silly.  I tried trading crystals to the mission giver npc, and not the one with I.M. above his head.  I'm attempting that now.

**Comment by thyris** [comment]
okay. trading crystals worked, I just was trying to trade to the wrong guy. My mistake :)  But, I did, accidentally, find an issue born possibly of laziness (not judging, I'm as lazy as it gets) with the rank points simply not being included as an award from the fetichism repeated mission, since it didn't have to be done with the crystal trades working.  I'd be interested to take a crack at fixing that.  It should be in missions.lua right?  I'll be connecting to the retail servers every now and again to check the awards and I will modify it's base award as close to the retail version as I can.   

Provided missions.lua is the place to make those changes, I guess I don't need anything further from ya on this specific issue, I'll pastebin my changes or something for you when I've made them.

**Comment by metalfiiish** [comment]
Would be inside the npc lua file. Each gateguard npc calls in the global/missions.lu for the basic framework but each npc contains the script to handle the missions. It would require adding rank points somewhere in each of the npc's lua scripts. Example one:

https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Bastok_Markets/npcs/Cleades.lua

**Comment by TeoTwawki** [comment]
fixed by #5939 after laying forgotten for a long ass time, thanks @lyptt
