### ISSUE TITLE
Bowl of goblin stew 880 issue

### ISSUE THREAD

**Issue by thyris** [DarkstarProject/darkstar#1169]
I used @additem 4094 to try and get the Bowl of Goblin Stew 880 item for trade to Bluffnix for the Gobbie bag quests and it said in the usual green "Obtained: Bowl of Goblin stew 880" but, as you see in the screenshot, nothing entered my inventory.

![thyris_2015 03 26_224113](https://cloud.githubusercontent.com/assets/11670614/6863138/472ead8c-d409-11e4-9f0a-8fca3174f0c9.png)

I hope this doesn't annoy you guys, cuz...I'm going to be reporting everything I find that doesn't work if I try to use it while playing ^_^

**Comment by teschnei** [comment]
Do not expect newer items to work. If it was added to the game less than 2
years ago, you should not be surprised if it doesn't work. I'll close this
because this is a newer item, but I would prefer not to see an issue for
every item that's not implemented (there are a lot of them)
