### ISSUE TITLE
Buying an item from a bazaar does not reload inventory. Purchased items do not appear until you send a sort packet to the server.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1174]

**Comment by Scavenge** [comment]
agreed and the sorting issue is very old, has even been mentioned previously in its own issue report. unfortunately it is inconsistent as far as i can tell, but maybe this circumstance changes that.

**Comment by zynjec** [comment]
Unable to repro on master, open another issue if you're still having this issue.
