### ISSUE TITLE
mobskill "Sand Pit" causing server crashes

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1189]
Triggers a crash when bst jug pet antlions use it. Its got code specific to an NM that was recently added but the move script can be exec'd by many diff antlions including jug pets.

**Comment by xdemolish** [comment]
have fun @nesstea

**Comment by teschnei** [comment]
the code added for that NM has nothing to do with the pet

**Comment by TeoTwawki** [comment]
@teschnei code added specifically for that NM is breaking on jug pets, so yes it does.

**Comment by nesstea** [comment]
https://github.com/DarkstarProject/darkstar/pull/1195
it wasn't necessary. sorry about that.
