### ISSUE TITLE
Lower Delkfutts stuck goblins

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1192]
One of the goblin whm and blm near the entrance to the zone are stuck in place, unable to follow or do anything but stand and cast spells. The problem whm/leecher whatever is the one not in the center of the room.

**Comment by gedads** [comment]
Hi, i couldn't find the goblin in the 2 areas near the entrance from qufim, where did that happened?

**Comment by nesstea** [comment]
I cannot reproduce this. No idea.

**Comment by timmifshode** [comment]
I'll check it and see if its still happening, it was in the first grouping of goblins in lower delkfutts and the only reason I noticed it was because I would pull one to kill it and run back, but the goblin would never follow

**Comment by xdemolish** [comment]
sounds like the standback/melee range bug
