### ISSUE TITLE
Call for halp

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1193]
Calls for help don't open mob up for attack for anyone, but do appear on the map and changes their name color. The mob forever after remains on the map and color changed even after characters that called for help leave.

**Comment by Scavenge** [comment]
not sure if related but i've even seen cases of mobs spawning with their name already orange

**Comment by Hozu** [comment]
This is still an issue, unfortunately. I was going to make an issue about it but this one already exists.
