### ISSUE TITLE
AOE stuffs

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1194]
AOE attacks from mobs, whether they are spells or abilities hit pc's outside of the party involved in the fight. Also I saw a yagudo buff a crab with bard songs.

**Comment by bendangelo** [comment]
I'll take a look at this.

**Comment by teschnei** [comment]
there's a flag that is supposed to allow this (fafnir hurricane wing/spike flail etc), not sure what happened on that front
