### ISSUE TITLE
Divine Waltz TP cost seems to be run per target instead of per use.

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1200]
I've been seeing people complain in game that it took more TP than it was supposed to. Much more. When I look in the script the correct amount is deducted. I see a recent change (#1130) moving this deduction from onAbilityCheck into onAbilityUse. The way I would expect the scripts to work is they run once, having their effects on all targets but if I am correct, the script is run separately on each target instead? That's the only thing I can think of to explain the TP cost discrepancy that multiple people have confirmed.

The code says
```lua
player:delTP(40);
```
and people have seen 1800 deducted in a party of 4 (400 x 4).

**Comment by teschnei** [comment]
Yes, it's for each target. It could be easily fixed to deduct only if
player = target, assuming aoe waltz must target yourself

**Comment by TeoTwawki** [comment]
fix incoming then

**Comment by teschnei** [comment]
This only works if aoe dances can only be cast on self, though. Make sure
that's the case

**Comment by TeoTwawki** [comment]
It is self target, hits anyone near dnc but client won't let you target others for it.

**Comment by teschnei** [comment]
That should work fine then

**Comment by TeoTwawki** [comment]
@teschnei like so?
https://github.com/DarkstarProject/darkstar/compare/master...TeoTwawki:misc?expand=1#diff-3fa917516567b65c6d5470f9c67a8978R35

**Comment by teschnei** [comment]
I think that will work. Best to try of course

**Comment by TeoTwawki** [comment]
Had to change it a bit, using getID().
