### ISSUE TITLE
Stoneskin effect applied by Afflatus Solace cannot be over-written by regular Stoneskin.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1202]
Should be able to over-write the Afflatus Solace inflicted Stoneskin with regular Stoneskin.

**Comment by maxtherabbit** [comment]
have you tested this on retail? only information I can find on wikia and bg says:

"Stoneskin will not overwrite Stoneskin and gives a "has no effect" error." 

and does not distinguish stoneskin from the afflatus solace cures from the enhancing spell

**Comment by dazusu** [comment]
Yes. I played WHM main for 11 years until I quit retail 12 months ago. The stone skin offered by solace curing is overwritten by a regular stone skin. The one offered by solace lasts only 30 seconds and usually isn't as potent (depending on cure amount).

**Comment by dazusu** [comment]
This is still an issue, want me to screenshot/video this on retail to confirm it?

**Comment by maxtherabbit** [comment]
No, I believe you
