### ISSUE TITLE
When the target player-character evades an AoE TP move; all other possible targets also evade it.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1203]
Tested this with Spike Flail; if the original target evades - an entire alliance of 18 also evades.

This may also likely applies to all other TP moves.

**Comment by ashdam** [comment]
Nice bug!

**Comment by bendangelo** [comment]
I'll take a look at this. Does this only effect alliances?

**Comment by teschnei** [comment]
no, everyone

**Comment by xdemolish** [comment]
duplicate of https://github.com/DarkstarProject/darkstar/issues/1194
