### ISSUE TITLE
item duping bug

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1205]
Trying to get more information now but multiple players have now informed me of items returned from AH getting "stuck" in their inventory, allowing them to resell or mail it infinite - the client isn't even allowing them to drop it. Attempting a trade seems to unstick it and allow it to be dropped.

I will update this when I find out how to reproduce, as so far its not happening to my own test character at all. Its not anything custom because no source there was touched either in map server or search server. I'll have to find what these players did that tripped it.

***Update:***
It is definitely the quantity field being incorrectly (or not at all) set when an item expires on AH.

**Comment by teschnei** [comment]
Guess it's time to make sure those deletions actually happen in trades and
auction house stuff before trading/posting!

**Comment by TeoTwawki** [comment]
Somehow they have the item in inventory with a quantity of zero when its returned from AH expiration. I set that items quantity to 1 and had them relog and they were no longer able to sell it without it being removed from inventory - the attempt removed it.

**Comment by whasf** [comment]
Fixed in 29e95e3cf21025b5d119a9c6c8b587cc28f7471d

**Comment by TeoTwawki** [comment]
Ty Whasf
