### ISSUE TITLE
Sandy 9-2

### ISSUE THREAD

**Issue by Turttle** [DarkstarProject/darkstar#1206]
On the bcmn fight The Heir to the Light in Qu'Bia Arena. Trion Spawns 5 times instead of once on the second part. Anyone even if not on that mission can enter the fight.The Yukvok of Clan Death (Orc RNG, mob ids 17621017, 17621031, 17621045) does not spawn on Part 1 of the fight. After killing all the mobs on the second part no CS/event is triggered, meaning the player:setVar("SANDO92",4); does not run. The mission can not be completed.

**Comment by gedads** [comment]
hi, try updating

**Comment by Turttle** [comment]
Going to rebuild tonight. I saw that now the Mobs in second part will use 2hrs!! that is grate! Still the issue is when exiting the BCNM. In console I get "leacecode = 2" and "win" but the if statement that follows the "printf("win");" does not execute. I have also try to manually execute "@cs 0x7d01" during and after the bcmn and all I get is a Zide cs talking about the Shadowlord (5-1 maybe?). Note: this is all before updating the client.

**Comment by Turttle** [comment]
also disabling the if statement and just leaving the "player:startEvent(0x7d01..." sets the players var "SANDO92" (now "MissionStatues") to the correct value, but no CS is played.

**Comment by Turttle** [comment]
After updating both client and server every thing is working correctly. Only thing i noticed is that the Yukvok of Clan Death (Orc RNG, mob ids 17621017, 17621031, 17621045) did 2 EES in a row.
