### ISSUE TITLE
mob_groups

### ISSUE THREAD

**Issue by armadarift** [DarkstarProject/darkstar#1224]
I have mob_groups that up lvl for Abyssea mobs and Seeker zones. But all the mobs is still showing Too-Weak and they are set above the lvl I am. Not sure what I am missing to fix this. Please help.

**Comment by xdemolish** [comment]
for help with adding content/working on stuff, ask on the forums (or irc for a quicker response)
should only post bug reports on github for bugs that occur on an unmodified copy of the server

**Comment by armadarift** [comment]
Well I was gonna share this once. I had found out why that lvl not taken. But goes that idea.
