### ISSUE TITLE
Mob_groups Level

### ISSUE THREAD

**Issue by armadaxi** [DarkstarProject/darkstar#1231]
Ok so with Mobs Levels in Seeker zones suppose be least 99+ and when I am set as lvl 90 they showing too weak but if I set myself to lvl 85 showing as DC but in DataBase showing all seeker zone mobs as least 99-107 and higher for some zones. In Past I know they was working fine. I even set the Abyssea mobs to lvl for 99 so players could merit or have small party's but now they can not anymore in these zone. I have tested this with current DS Build and Mod Build and both act same. If I am missing something please share, This been tested on a Main and a Test server same results.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/settings.lua#L38
Did you set your min/max in settings?

**Comment by armadaxi** [comment]
Actually I didnt kno had fix that, I will try that and test and report it back. Thanks Teo

**Comment by armadaxi** [comment]
Ok it is fix and was gonna close it but seems xdemolish close it without me report back that it worked.
