### ISSUE TITLE
Mobs with the job "Mage/Bard" will lock-up after casting 2 songs, and cease using TP moves, or moving towards their target.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1233]
Monsters such as Roc and Simurgh will remain in combat - but won't move if their target moves away; and won't use TP moves.  This seems to consistently happen after they've used 2-3 songs.

It's a  pain in the manhole.

Halp!

**Comment by dazusu** [comment]
Update: This affects all monsters that cast spells of any kind. Occasionally after casting they will cease to follow players/move; but still use attack if you're in range, and still cast spells.

**Comment by teschnei** [comment]
are you sure you aren't observing intended mage behaviour? IIRC, they are
intended to stand away while blasting you with spells until their HP gets
lower

**Comment by dazusu** [comment]
you're thinking about rangers.

Mobs that cast spells will always be in melee range if they can move. Mobs that cast spells generally don't cast them frequently enough to maintain a distance to cast (usually only every 15-30 secs).

**Comment by dazusu** [comment]
For the first 2 BCNMs - the Sobbing Eyes worked fine; followed me while kiting - then on the third BCNM - it stopped; and every subsequent BCNM after it didn't work from the start at all - The only thing that will fix it now is a server reboot. So this problem persists between spawns once the mob is "locked".

**Comment by teschnei** [comment]
No, I am thinking about the AI implemented in DSP :p that is how it is
written (on purpose)

**Comment by teschnei** [comment]
AI fudging up between respawns is different though. That would probably
deserve to be in the title

**Comment by dazusu** [comment]
Well, like I said - the first 2 BCNMs, it was following me (and stopped running to cast, then start following me again) - this is proper bnehavior.  Then all of a sudden, it just stopped (the fact is also stopped using TP moves proves there's more to this than intended behavior...?)

**Comment by dazusu** [comment]
Plus.. Roc and Simurgh... they only cast Elegy and Lullaby; - and again - they work for a while, then just randomly stop working.

**Comment by dazusu** [comment]
Incidentally - they also do this all the way until their death; not just a certain HP. so I think that debunks your intended theory :P

**Comment by xdemolish** [comment]
they refuse to move at all after casting two spells, even after respawning (didn't look like their AI was stuck when i had a go at it)
gotta restart for them to underp

**Comment by teschnei** [comment]
Will have to see if their AI is getting locked or just standback being
retarded. They won't tp if there's no move in range, though

**Comment by dazusu** [comment]
Right -- but this is when we're meleeing the mobs in-range. They just hit us - but don't use TP. This is after they've broken, it goes hand in hand.

1. Stop chasing players if they run away.
2. Stop using TP moves completely (regardless of target range)
3. Continue to cast spells, and attack, if a target is in range.
