### ISSUE TITLE
Level Cap in Promyvion areas reduces level - but leaves stats, hp and mp at pre-cap amounts.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1241]
I see the "Level Cap" icon. The UI tells me I'm level 30 now; but my HP is still 717, my MP still 651 - and my stats still that of a level 55 WHM.

Stat scaling is not applied to level cap.

**Comment by teschnei** [comment]
ec869496b6c689f617dba93d46fc0be2c70be29b
