### ISSUE TITLE
Combat Caster's Quiver not dispensing arrows

### ISSUE THREAD

**Issue by Zazmo** [DarkstarProject/darkstar#1244]
Just picked up a combat caster's  quiver and it will not give me the option to use it. Hence, I cannot get arrows to dispense from it.

**Comment by nesstea** [comment]
There is no Lua file for it. Code one! Look at Holy bolt quivers

**Comment by lichtl** [comment]
Just tested. Lua does exist and item work with latest code (need to be equipped on the waist)
