### ISSUE TITLE
Promyvian bosses not doing the moves that make them hard.

### ISSUE THREAD

**Issue by jamiehavok** [DarkstarProject/darkstar#1246]
Promyvian dem does not use Fission to summon offspring
Promyvian holla does not use Shadow Spread
Promyvian mea does not use Impalement

**Comment by xdemolish** [comment]
best issue name evar

**Comment by personaone** [comment]
LMFAO

**Comment by ashdam** [comment]
XDDDDD

**Comment by maxtherabbit** [comment]
outstanding

**Comment by jamiehavok** [comment]
ok no pun intended lol but this is still an issue!

**Comment by TeoTwawki** [comment]
Need to make the anima items for them work too.

**Comment by bendangelo** [comment]
I just implemented all of their skills except Fission. That one will take a bit more work.

**Comment by jamiehavok** [comment]
awesome that the promyvian bosses do these moves now, thanks! Are you able to get mammets to do the transmog move and Diabolos to do nightmare? i'd really like the promathia missions to be back to their former glory!

**Comment by bendangelo** [comment]
Can you open an other issue for those and I'll fix them.

**Comment by teschnei** [comment]
Mammets have had transmogrify/mind wall since February

**Comment by zynjec** [comment]
Looks like this was fixed, if they're still not using the appropriate skills just open another issue.
