### ISSUE TITLE
linkshell message messed up a bit

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1251]
With latest client + latest DarkStar (as of 9pm eastern time tonight) I am seeing linkshell message twice and in wrong message type at login.

The /lsmes of first LS shows as the 3rd ls that SE never implemented in client (there are message types and colors for 3, rather than 2).

Also changing the lsmes seems to have been broken. No custom code involved.

**Comment by Scavenge** [comment]
second this

**Comment by teschnei** [comment]
It's got a new packet structure that I haven't looked at yet. Not hard,
though
