### ISSUE TITLE
Guildworker's Union NPC's no longer allow signup

### ISSUE THREAD

**Issue by lichtl** [DarkstarProject/darkstar#1255]
It seems that the NPC's no longer allow you to sign up.

**Comment by teschnei** [comment]
working fine for me, closing unless more info can be provided

**Comment by lichtl** [comment]
I've just tried it again with a fresh installation. Maybe this is only related to a linux server build as the local windows installation is working fine.

While taking to the NPC I get the selection to sign up. however on sign up no message appear and when talk to the NPC again he again ask me to sign up.

This is from the dsgame log

[11:16:11][Debug] CLIENT Dave PERFORMING ACTION 00
[11:17:22][Info] parse: 05B | 02FE 02FD 0A from user: Dave (not signed up)
[11:17:25][Info] parse: 01A | 0305 0304 08 from user: Dave
[11:17:25][Debug] CLIENT Dave PERFORMING ACTION 00
[11:17:32][Info] parse: 05B | 0317 0316 0A from user: Dave (not signed up)
[11:17:34][Info] parse: 01A | 031C 031B 08 from user: Dave
[11:17:34][Debug] CLIENT Dave PERFORMING ACTION 00
[11:17:41][Info] parse: 05B | 032B 032A 0A from user: Dave (signed up)
[11:17:44][Info] parse: 01A | 0330 032F 08 from user: Dave
[11:17:44][Debug] CLIENT Dave PERFORMING ACTION 00

using git current latest version (GIT Commit: commit 998d22f44a428dabb838afeff272a908a41510c7
)

Here's a video
https://dl.dropboxusercontent.com/u/9237831/FFXI%20Bug/2015-04-10-1319-03.flv

ubuntu@ip-172-31-9-17:~/darkstar$ uname -a
Linux ip-172-31-9-17 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-9-17:~/darkstar$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2

Please let me know if you need any more details.

**Comment by teschnei** [comment]
I'll double check on Linux. I did use an underflow on purpose, so I'll make
sure it works. Is the Linux character new? What is their current guild var
in char_vars? Should be called [GUILD]CurrentGuild or something similar. It
should not exist if you have no guild and should never be -1

**Comment by lichtl** [comment]
Hi,

just checked char_vars.
Currently the following char does have Guild_Member = 320

The character was created around a week ago. When updating my local repo I checked and keepd the database up to date.

**Comment by teschnei** [comment]
Ok.. Delete that var, and let me know if that happens again. It should only
ever be 0 to 10 or something.  I think I know how that might accidentally
happen, I will make sure to check for that case in the guild script next
time I change it.

**Comment by lichtl** [comment]
Hi,

just cleared the var. And after signup at the Leathercraft guild I received Guild_Member = 128

I'm now using the latest code: 1ef6c1dc915842462c49f24c8c6593fcd432e52c

**Comment by lichtl** [comment]
Is 128 expected? Since the NPC still don't allow sign up to earn guild points

**Comment by teschnei** [comment]
No, I'll be looking into it tonight possibly.

**Comment by lichtl** [comment]
Hi,

any idea or a suggestion? From what I see that should be all lua only.

**Comment by teschnei** [comment]
oops, forgot to reopen it, but it should be fine now:

f79d6b30a0305b488f1443ecef6fa5a76f0c277a
