### ISSUE TITLE
weather wrong for multiple zones

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1257]
Seeing multiple zones get weather they aren't even supposed to have at all.

**Comment by teschnei** [comment]
Specifics?

**Comment by TeoTwawki** [comment]
In other words go find each and every mistake and list them all?

**Comment by teschnei** [comment]
In other words, tell me one so I can see if its a db problem or core problem

**Comment by TeoTwawki** [comment]
have to wait for random weather to pop up again, currently jumping zone to zone, and luck is not with me.

**Comment by TeoTwawki** [comment]
Haven't had the time or luck to catch it again, will open new issue when I can give you a specific zone.
