### ISSUE TITLE
Crash: Looks like something to do with deleting packets for the character

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#1266]
https://www.dropbox.com/s/bvp9p319wid5304/GS_04-09-2015_08-52.7z?dl=0

**Comment by teschnei** [comment]
got no call stack!

**Comment by personaone** [comment]
does this happen when you examine your own character? I just crashed the game server by doing that o_O

**Comment by xdemolish** [comment]
you're lucky i forgot to kill my server! i'll have a look now

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/6788b81f95add8b06fd3417b4d2c5d286b7c5c13
don't even know if this is the same as whasf's crash but it definitely fixed something!

**Comment by personaone** [comment]
nice one! Cheers.

**Comment by teschnei** [comment]
Oh, that's not right, forgot we still can't do sizeof data now. Use
PACKET_SIZE

**Comment by xdemolish** [comment]
want me to do the same with guild_menu_buy/sell, menu_merit, and shop_items packets? they're still using sizeof data and subtracting the header size (i think -4 is the header size anyways)

**Comment by teschnei** [comment]
Everything that used sizeof(data) would be replaced with
sizeof(PACKET_SIZE-4). Then apply any extra to that (so data - 7 turns into
packet size - 11). Think that'll be good

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/e6c6fb0e6bbbe5c55c2901f0281b4d7c8f372381
tested the changed packets and no crash so im assuming that's it

**Comment by teschnei** [comment]
Almost. Have to subtract 4 more from all of them. Then its good

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/d4123dbd5d0801a6d26012217d52879dfcf310b0
I THINK IT'S GUD THIS TIME

**Comment by teschnei** [comment]
Should be!

**Comment by personaone** [comment]
not sure but this has started to occur, updated to latest build today from 4412012.

![untitled](https://cloud.githubusercontent.com/assets/8123295/7100758/2d515522-e034-11e4-99d3-4897b8e15daa.png)

**Comment by xdemolish** [comment]
not getting the crash, click 'Debug the program' > Visual Studio > Save Dump As 
or w/e i wrote on the wiki  (https://wiki.dspt.info/index.php/How_to_Dump)
and send us a dump

**Comment by z16** [comment]
@personaone That bug has likely been already fixed as of commit d59dbbb .

**Comment by xdemolish** [comment]
i don't even think it's possible to get packet related crashes on startup

**Comment by personaone** [comment]
Just did a clean>rebuild, same thing, rebuilt the SQL db as well. The dump is 600mb :/

**Comment by z16** [comment]
Unfortunately I'm not getting any debug info on this dump.

The problem is that it's trying to dereference an uninitialized pointer. But I cannot figure out where it occurs. What are you doing when it happens? Is it really on startup? Is it when someone logs in, or performs a certain action? I assume you built the server yourself, so you could attach Visual Studio when you run it (faster to just run it from inside Visual Studio), then it should be more accurate about where and why it happens.

**Comment by xdemolish** [comment]
inb4 halloween enabled in settings.lua

**Comment by xdemolish** [comment]
also, need the exe, pdb and log too

**Comment by personaone** [comment]
ok here's the exe and pdb packed in the rar:

https://www.mediafire.com/?9iqe2ji96fk4s7z

Here's what it looks like when ran in VS2013 Update 4:

![untitled2](https://cloud.githubusercontent.com/assets/8123295/7101592/44a3fb90-e060-11e4-84c2-dd0e6b268dca.png)

**Comment by z16** [comment]
The symbol file you provided does not match the crash dump. If you rebuilt the server since then the symbol file and executable will differ.

Can try removing line 136 in `basic.h`, the file that's crashing at the point it's crashing, i.e. this:
```c++
        DSP_DEBUG_BREAK_IF(!(index < 2 * size));
```

Just remove it, rebuild it, see if it will work.

**Comment by personaone** [comment]
ok i managed to sort it out, deleted mysql, reinstalled it, did a complete new pull of git, works as it did before. Could have been something with the data being corrupted in the db :/ sorry.

**Comment by z16** [comment]
I'm pretty sure it was what I told you, and it has been fixed since commit 54a481d.
