### ISSUE TITLE
Sealed Dagger - no model displayed [NIN quest]

### ISSUE THREAD

**Issue by personaone** [DarkstarProject/darkstar#1270]
Hi Guys,

Forgot to report this before, but the ninja quests key item [Sealed Dagger] doesn't have a model attached to it and it invisible in the final cutscene for the quest. It's been like this since i remember actually.

**Comment by teschnei** [comment]
Key items can't have models attached to them

**Comment by personaone** [comment]
I wonder what's causing the dagger not to appear in the cutscene o_O
![alex_2015 04 10_180752](https://cloud.githubusercontent.com/assets/8123295/7092051/f49ef976-dfae-11e4-9465-de21ba1bbce1.png)

**Comment by teschnei** [comment]
Cs param maybe

**Comment by xdemolish** [comment]
wasn't able to find the param, it might just be an npc

**Comment by xdemolish** [comment]
yep, it's another Kaede entry with the sword part of the model
not sure how to get that npc to display instead in this one cutscene, though

**Comment by teschnei** [comment]
They usually use different IDs for different models

**Comment by xdemolish** [comment]
time to flip the IDs and see what happens!

**Comment by xdemolish** [comment]
ok that was easy

**Comment by personaone** [comment]
good news :D

**Comment by xdemolish** [comment]
aaaand starlightknight no longer exists
owell, https://github.com/DarkstarProject/darkstar/commit/4412012091b385c83859a9b345b103806e7a5f1e

**Comment by teschnei** [comment]
Make sure she displays correctly in the other cs too ;)

**Comment by xdemolish** [comment]
psh i actually test m8
like the first cs i triggered talking to her normally displayed fine so it should be gud

**Comment by teschnei** [comment]
Copying this message for later

**Comment by xdemolish** [comment]
you get to assign me as many issues as you want if it doesn't work ;p
