### ISSUE TITLE
smn magic cait_sith don't work, please check it

### ISSUE THREAD

**Issue by ffxisf** [DarkstarProject/darkstar#1273]
I like SMN and PET, Cait Sith don't work , help please

**Comment by Altreer** [comment]
It requires changing mob_family_system.sql, mob_pools.sql, and pet_list.sql files, as well as adding a spell lua file to even begin implementing it.

**Comment by TeoTwawki** [comment]
There's much more needs done with smn before anyone even thinks about adding more pets to its spell list. Wanna help? Parse some dmg info for BP's and Astral Flow's and bring that to the devs.
