### ISSUE TITLE
CoP mission GARDEN_OF_ANTIQUITY bug

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1280]
Logic for Rubious Crystal NPC's in Al'Taieu is wrong, I am able to trigger the NM's without even being on the mission. There is a valid mission check there but the
```lua
(stuff and stuff) or (stuff)
```
is combined improperly, and I don't have time to fix this, so I'm passing the buck to another minion.

**Comment by nesstea** [comment]
But you should only have access if you are on the correct mission.

**Comment by TeoTwawki** [comment]
There's a mission check in the script, and the authors intention is not what happens. Can argue that mission check shouldn't even be there and that its not out prob if somehow some server has ppl getting there early, but fact remains the logic of the exist check still needs adjusted anyway even if its taken out. Its not checking what its author intended to check.

**Comment by TeoTwawki** [comment]
@nesstea actually, still need to check it because can pop them after mission was already completed as well, because it does need that mission check to work with screwing up vars on players on the next mission. Which it did some folks last night and I had to fix them just now.

**Comment by nesstea** [comment]
I'll look into this Teo.

**Comment by nesstea** [comment]
Yeah it's letting a player check south tower 3 times and it's setting the vars as if they were running around and hitting each.
