### ISSUE TITLE
Pets do not respawn when zoning.

### ISSUE THREAD

**Issue by joncloud** [DarkstarProject/darkstar#1286]
packet_system.cpp SmallPacket0x00C does appears to handle respawning pets upon zoning, however the original PChar gets deleted, and the current PChar is a new instance thus petZoningInfo.respawnPet is false.

Is there a specific technique that the PetInfo_t data should be persisted with?  It seems like it would be necessary to put it into the database, because the character could be zoning into a completely different server.

**Comment by teschnei** [comment]
It would be necessary to do that, yes

**Comment by joncloud** [comment]
Any preferences on the database structure (existing table, new table, names, etc)?  It seems like it would be beneficial to store this in a table that is related to chars to prevent having to migrate user-specific data.

**Comment by teschnei** [comment]
char_stats probably (most of it is just temp stuff specifically for
zoning/logging out)

**Comment by xdemolish** [comment]
should probably set it to 0 on logging out/shutting down (if it's retail behaviour, that is)

**Comment by teschnei** [comment]
Nah, your pet comes back on login
