### ISSUE TITLE
multi server instance feature Request: specify log file name in command line argument

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1296]
like:
```
DSGame-server.exe --ip 127.0.0.1 --port 54230 --log mainmap.log
DSGame-server.exe --ip 127.0.0.1 --port 54231 --log bcnm.log
DSGame-server.exe --ip 127.0.0.1 --port 54232 --log dynamis.log
```
etc.

Currently if you run them from same place they all wright to the same log file at the same time. Good luck sorting out which one did what, unless you make 3 diff directories to contain them and copy over the scripts specific to each ones zones, which is stupid.

**Comment by xdemolish** [comment]
wright

**Comment by TeoTwawki** [comment]
spellcheckfail+notgivingashit=wright!
