### ISSUE TITLE
[GUILD POINTS] Bonecrafting always returning 0 points

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1297]
@teschnei 
Seems to be bonecrafting all the time. The other guilds seem to work. The acquisition of points works fine, but it won't let me buy items.

![points](https://cloud.githubusercontent.com/assets/1483915/7147587/cebcab9a-e2b0-11e4-95dd-fa2c58e3193c.PNG)
![chatlog](https://cloud.githubusercontent.com/assets/1483915/7147589/d4a7d55c-e2b0-11e4-8d64-45bd74ca7e4a.PNG)

**Comment by teschnei** [comment]
Yeah nesstea! Fix your own bugs! :p

**Comment by nesstea** [comment]
shit...
