### ISSUE TITLE
Some homepoint bugs & the corrections

### ISSUE THREAD

**Issue by b03605079** [DarkstarProject/darkstar#1299]
darkstar / scripts / zones / Giddeus / npcs / HomePoint#1.lua
26  -homepointMenu( player, 0x21fc, 22); 
26  +homepointMenu( player, 0x21fc, 54); 

darkstar / scripts / zones / Bastok_Mines / npcs / HomePoint#3.lua 
45  -if(csid == 0x21fd) then 
45  +if(csid == 0x21fe) then

**Comment by xdemolish** [comment]
https://help.github.com/articles/creating-a-pull-request/
