### ISSUE TITLE
Save my Sister bugs & corrections

### ISSUE THREAD

**Issue by b03605079** [DarkstarProject/darkstar#1301]
darkstar / scripts / zones / The_Eldieme_Necropolis / npcs / Brazier.lua 

61  -if(npcID == 17576340) then --(F-9) 
61  +if(npcID == 17576343) then --(F-9)

70  -if(npcID == 17576341) then --(H-7) 
70  +if(npcID == 17576344) then --(H-7)

80  -if(npcID == 17576342) then --(F-7) 
80  +if(npcID == 17576345) then --(F-7)

90  -if(npcID == 17576343) then --(H-9) 
90  +if(npcID == 17576346) then --(H-9)

**Comment by maxtherabbit** [comment]
if you know exactly what changes need to be made, please make a pull request instead of opening an issue

**Comment by nesstea** [comment]
@b03605079 Do you need help making a pull request?
