### ISSUE TITLE
Fishing mini-game no workie anymore

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1307]
I know fishing was borked already, but now every time a player catches something, there is no mini-game and the rod just does the moving animation indefinitely.

**Comment by nesstea** [comment]
@teschnei  I haven't been able to get ahold of your fishing guy yet. I doubt it will happen.

**Comment by jono659** [comment]
It has been this way since about 2 updates ago.

**Comment by maxtherabbit** [comment]
9cdf53d
