### ISSUE TITLE
server message+mog house homepoint reminder event = pol crash

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1313]
If a player ends up a in a situation where they would get the the mog house exit "do you want to set your homepoint / its dangerous out there blah blah" event at login their client will crash as soon as the server message attempts to display. I tripped this by getting dc'd while exiting my mog house.

Other client crashes have been found related to the server message trying to display during a cs event firing off at login (@xdemolish mentioned the crash @gedads found was from server message trying to display). 

I think we need to prevent them from happening at the same time. Not sure which of the 2 retail does first.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/issues/518
