### ISSUE TITLE
NPC lua files names containing "@" will crash the server.

### ISSUE THREAD

**Issue by Turttle** [DarkstarProject/darkstar#1317]
I have tried to implement the PsoXja lifts script, but the npcs in the npc_list.lua have a name that contains "@". http://puu.sh/hhoZ9/3751a1336b.png After trying to test the new lua files i get this error. http://tinyurl.com/DSGame-server-dump
Affected NPC in Pso'Xja (Zone 9):
@09a, @090, @091, @092, @093, @094, @095, @096, @097, @098, @099

**Comment by gedads** [comment]
it was working (except the disappearing mobs probably coming from disappearing tiles) before elevators were removed from db.
@09... is their true names usually it's better to leave those as they're officially named.
[02:06:49] 0x0E, 64 Bytes - (Update) Entity
   0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
   -----------------------------------------------
   0E 20 C1 09 A9 91 00 01 A9 01 07 00 00 00 A0 C1    . Á.©‘..©..... Á
   00 00 68 41 00 00 A0 41 01 00 01 00 32 32 64 0B    ..hA.. A....22d.
   00 03 08 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
   03 00 00 00 40 30 39 34 FD 25 72 18 08 00 00 00    ....@094ý%%r.....
                                                      

   id: 16814505 targid: 425 xpos: -20 ypos: 14.5 zpos: 20 
   rotation: 0 sizetype: 7 moving: 1 speed: 50 speedsub: 50 
   animation: 11 status: 525056 unk: 3 nameprefix: 0 unk3: 0

**Comment by Turttle** [comment]
I copy the true name from the NPC_list.lua and made individual luas for each of the elevator with their true name, but the DSGame-server crashes when loading zones. Is that because they are not in the db?

**Comment by gedads** [comment]
i don't really know, they're still in elevators.lua . It might be best to ask demolish since he's the one who made the changes.

**Comment by teschnei** [comment]
commit your changes to your fork and i'll pull it and see why it's crashing

**Comment by Turttle** [comment]
The code i used was replicated from a working lift in Bastok Metalworks.

**Comment by Turttle** [comment]
#1318

**Comment by teschnei** [comment]
ah, its just a script error - lower door is the elevator (@090), upper door and elevator are both null (and it crashes because the elevator is null

i'll add some better debugging messages for that
