### ISSUE TITLE
BCM Issue

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1331]
On capped BCNMs, a level 75 can leave the BCNM with hate and the mob will chase them outside. Then they can fight it at level 75 cap and those inside still get credit. Don't know about the 75 who zones out though.

**Comment by TeoTwawki** [comment]
This usually means there is a mob that is spawned inside the bcnm without being part of the bcnm's tables or has wrong spawn type in the mob tables. For anyone to know which and to fix, would need to know which mob in which bcnm.

**Comment by m241dan** [comment]
My players are telling me Under Observation and Mission 5-1

**Comment by TeoTwawki** [comment]
Are you on latest dsp? I knew about that happening in 5-1 before long time ago, but thought that was fixed when Kj had me add the spawned skellies to the bcnm table.

**Comment by m241dan** [comment]
We're ont he most recent patch as of this Friday.

**Comment by nesstea** [comment]
@m241dan Check the lua file for the mobs and see if any of the mobs are spawned in their scripts.

The other thing I could think of is if there is party hate and a player wasn't registered for the bcnm, yet being added to some hate list.

**Comment by teschnei** [comment]
4b49477675318bf8d0dc8a0e82634f8056daf238
