### ISSUE TITLE
Matt Quests

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1335]
Hello
I  will like to know how to make Matt give us the mission, because he does not want to give it and I am stuck on level 50.

Matt says "You've got no business talking to me"

If somebody can help me it will be greatly appreciated.

**Comment by bendangelo** [comment]
Did you already start the quest? Is it in your log?

**Comment by AlexandreCA** [comment]
Im cap level 50 (in blue in the menu). I can not start the quest since Matt doesn't  want to talk. He says "You've got no business talking to me"

**Comment by Altalus** [comment]
Is the quest enabled in your settings.lua files ?

 

______________________________

Guillaume Gingras

**Comment by AlexandreCA** [comment]
Yes, I don't see in settings.lua, where are Matt. What's line? Altalus, are you the french canadian forum? This username told me something.

**Comment by Altalus** [comment]
I don’t know if there’s such a thing as a French Canadian forum but I am indeed French Canadian.

 

And check in the settings.lua for INITIAL_LEVEL_CAP and MAX_LEVEL. If you set your MAX_LEVEL to 50 nothing will allow Maat (not Matt) to give you the quest.

 

In fact, if you check the Maat script in Ru’Lude Garden, you will find this code:

 

elseif(inDefiantChallenge == QUEST_AVAILABLE and LvL >= 50 and player:levelCap() == 50 and MAX_LEVEL >= 55) then

                                player:startEvent(0x004f); -- Start Quest "In Defiant Challenge"

 

So it should work. Make sure you are at least lvl 50, that the level is blue and that the MAX_LEVEL in your settigns.lua is at least at 55 (should be between 75 and 99 normally, but it depends on your choices).

______________________________

Guillaume Gingras

**Comment by AlexandreCA** [comment]
haha, sorry for my english. But yes, you are the person when I think. I have you email adress. Anyway, I check that and I you come back
