### ISSUE TITLE
stealing null item while using +steal gear

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1336]
![stole null item](http://i61.tinypic.com/11rb0n9.png)
MOD_STEAL checks busted I guess? I can steal thf test perfectly fine from same mob after that player "successfully" stole a blank item. Had a player this was happening to take off his rabbit charm and other +steal gear, and it stopped happening.

**Comment by nesstea** [comment]
LOL that's pretty awesome...

**Comment by xdemolish** [comment]
can't reproduce, even with rabbit charm and MOD_STEAL set to 100

**Comment by TeoTwawki** [comment]
Huh, got no custom code involved and the prob definitely went away soon as I had them remove the gear. Will try and locate the trigger, has to be more to it than just MOD_STEAL I guess

**Comment by TeoTwawki** [comment]
Just tested : Rogue's Ring will trigger it easily, and that's odd because its a latent that seems to have been done in the script instead of the sql table (or both? someone needs slapped anyway). Item ID 13291. Looks like its not steal items in general, just someones half-assed attempt at latent +steal.
