### ISSUE TITLE
Clothcraft guildpoints npc loop

### ISSUE THREAD

**Issue by timmifshode** [DarkstarProject/darkstar#1339]
Hauh Colphioh npc that asks for and accepts items to obtain guild points for cc guild is stuck in a perpetual loop asking if you would like to sign a contract. 
![skeleton_2015 04 21_204332](https://cloud.githubusercontent.com/assets/7440856/7265402/3623d55e-e867-11e4-908b-47a7458499a4.png)

She just asks over and over if you would like to terminate your contract with the weavers guild to sign a contract with the weavers guild, damn cats.

**Comment by teschnei** [comment]
damn cats..

**Comment by teschnei** [comment]
can't reproduce, worked fine on both windows and linux (though the textIDs were wrong)
