### ISSUE TITLE
crash getting leader of party, after having already checked to be sure wasn't null...

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1353]
adfadsafdsa m(_ _)m 
Alright @teschnei, I give up. Here's a dump. https://yadi.sk/d/Xu4fFDOsgDC24

*Getting laughed at on IRC later* : +1

**Comment by teschnei** [comment]
pdb wasn't right, couldn't get debug info :p

**Comment by TeoTwawki** [comment]
Newer dump, this one should work https://yadi.sk/d/ngvQnVGKgdsja that's from revision cef9810560af103a3699c1f4f802159cb41ed5e4
@maxtherabbit since he's not going to be back for awhile yet, you mind taking a look at this and helping me prevent it? The trigger is trying to get the name of a party leader who's not on the same map server, but is otherwise valid. I incorrectly thought I could just make sure they weren't null first.

**Comment by teschnei** [comment]
GetLeader should give you null if they are on another server. If they are a
debug memory location instead of null, its a different problem
