### ISSUE TITLE
"No drop" from Quu Domi the Gallant

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#1354]
On attempt fifteen, got no drop at all from Quu Domi the Gallant. Script seems to indicate "either/or" drop for Strider Sword or Sarutobi Kyahan. No drop listed on screen. Relogged just to make sure there wasn't an issue updating inventory.

Revision: #2b823a6
Server: Classic

**Comment by nesstea** [comment]
SELECT * FROM `mob_droplist` where dropId=2916;

**Comment by xipies** [comment]
Seventeenth attempt, dropped both items. Looks like it's not entirely "either/or" drop behavior. Still at same revision.

**Comment by RunAwayDSP** [comment]
what server?

**Comment by nesstea** [comment]
Try doing something like this in the NM's lua file. Change the IDs accordingly and adjust the drop rates.

`Pulled from ix_aern_drg.lua`
function onMobSpawn(mob)
    if (math.random(0,1) > 0) then     
        SetDropRate(4396,1870,1000); -- Deed Of Sensib.
        SetDropRate(4396,1903,0);
    else
        SetDropRate(4396,1870,0);
        SetDropRate(4396,1903,1000); -- Vice Of Aspersion
    end
end;
