### ISSUE TITLE
Retail Capture Request

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1356]
Can someone grab the PUP/COR/BLU AF quest events? From the lvl 40 to 60 ones.

Thanks!

**Comment by teschnei** [comment]
Are they not in the event ID lists on the wiki?

**Comment by TeoTwawki** [comment]
https://wiki.dspt.info/index.php/Event_IDs
If they aren't there let me know in IRC and I'll update the wiki, because I am certain I have them laying around on a file on my HDD *somewhere*.

**Comment by nesstea** [comment]
I am guessing the eventIds are the same for all the quests with different parameters. Not sure.

**Comment by xdemolish** [comment]
that's what gm commands are for :D
params can probably be guessed once you find the right cutscene

**Comment by teschnei** [comment]
oh, if they're in whitegate, they might be under the second texttable
