### ISSUE TITLE
Kikoku damage proc not occuring.

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1360]
Pretty sure the issue is in SQL but it's damage mulitplier proc isn't happening at all.

**Comment by nesstea** [comment]
Isn't that a mod? can't remember

**Comment by Kthulupwns** [comment]
Its either item_mod or item_latent

**Comment by nesstea** [comment]
MOD_EXTRA_DMG_CHANCE          = 0x1FA -- Proc rate of MOD_OCC_DO_EXTRA_DMG. 111 would be 11.1% (modId = 506)
MOD_OCC_DO_EXTRA_DMG          = 0x1FB -- Multiplier for "Occasionally do x times normal damage". 250 would be 2.5 times damage. (modId = 507)

**Comment by personaone** [comment]
I can confirm this isn't working for me either.

**Comment by nesstea** [comment]
`SELECT * FROM item_mods where itemid=18312`

All the modifiers are there. I am not sure why it wouldn't he extra damage.

**Comment by personaone** [comment]
Maybe something's up with the battleutiles.cpp file? No other ideas :|

**Comment by nesstea** [comment]
https://github.com/DarkstarProject/darkstar/blob/f95ae01d1c2d2b8b0201f9e6ecfecd821efbaedd/src/map/utils/attackutils.cpp#L155
That works.

Are you using the 75 version or any of the others?

**Comment by personaone** [comment]
Cool, yep only the 75 version :)

**Comment by nesstea** [comment]
modify your onAdditionalEffect lua for the weapon to get the ID of the item.
post it here when you do that!

**Comment by nesstea** [comment]
Did you resolve this?

**Comment by Kthulupwns** [comment]
Yeah it's commited to the master, in the Item_mod.sql there was 2 extensions that were incorrect, 507, then 506

**Comment by Kthulupwns** [comment]
just look for ID 18312 in the item_mod.sql or just revise your master

**Comment by Kthulupwns** [comment]
and for the record kikoku is a 3X dmg proc with a 16% para chance, not 11/25

**Comment by Kthulupwns** [comment]
they were out of sequence was all  #1516
