### ISSUE TITLE
DRG AF quest Chasing Quotas stuck on Esca

### ISSUE THREAD

**Issue by Enignite** [DarkstarProject/darkstar#1363]
Esca (West Ronfaure) will not give me the the cut-scene for DRG AF quest Chasing Quotas, I believe it be related to The Pickpocket as apparently if you have not completed it then Quotas progresses normally.

I think it's because the quest status checks are in the wrong order in Esca.lua so it stops before checking Quotas progress if Pickpocket is completed

**Comment by nesstea** [comment]
I can take a look at it tomorrow.

**Comment by helixhamin** [comment]
Hmm, here is the script in onTrigger:
elseif (Quotas_Status == 4) then
		player:startEvent(137); -- My earring!  I stole the last dragoon's armor.  Chosen option does not matter.
	elseif (Quotas_Status == 5) then
		player:startEvent(138); -- Reminder for finding the armor.

It seems the startEvent is not in hex. Shouldn't it be 0x0089 for 137 and 0x008A for 138?

There is also this in onEventFinish:
elseif (csid == 137) then
		player:setVar("ChasingQuotas_Progress",5);
		player:delKeyItem(SHINY_EARRING);
	end;

Sorry, not sure if the decimal cs values work, but I would assume not.

**Comment by teschnei** [comment]
decimal and hex are just different ways of showing the same number, they're equivalent

**Comment by Enignite** [comment]
Esca has a different line of dialogue depending on whether you have finished the quest The Pickpocket. I have confirmed using an alt that this part works, my DRG main is getting a different line to the alt who has not started The Pickpocket. I think the only way this would happen is if (thePickpocket == 2) then player:startEvent(0x007b); checks to see if that quest is finished and shows the new dialogue while the last line player:startEvent(0x0077); is the default dialogue. As you can see by the order:

-- "The Pickpocket" Quest Dialog
if (thePickpocket == 1 and player:getVar("thePickpocketGiltGlasses") == 1)  then
	player:startEvent(0x0080);
elseif (thePickpocket == 1) then
	player:startEvent(0x0078);
elseif (thePickpocket == 2) then
	player:startEvent(0x007b);
elseif (Quotas_Status == 4) then
	player:startEvent(137); -- My earring!  I stole the last dragoon's armor.  Chosen option does not matter.
elseif (Quotas_Status == 5) then
	player:startEvent(138); -- Reminder for finding the armor.
else
	player:startEvent(0x0077);
end;

This means that if you have finished the quest (thePickpocket == 2) then it never checks for (Quotas_Status==4) and you cannot get the DRG AF CS. If this is what's happening then moving the lines checking (thePickpocket == 2) to the second to last in the list should fix it (could also move (Quotas_Status==4) to the top to give priority to AF quest but isn't necessary).

**Comment by helixhamin** [comment]
I checked and it looks like the variable never gets cleared. 

"Return to Port San d'Oria and trade the Gilt Glasses to Altiret for your reward." 

Should the var be wiped here? Sorry, I am not sure if we can just delete it at this point.
