### ISSUE TITLE
Mobs abilities does not work.

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1366]
Hello.

Yesterday, all is fine. But since the last update, I think, the mobs, when they uses  their abilities. They make 0 points of damage. One bug on a table or.. i don't know. One idea? 

Thank you very much

**Comment by dazusu** [comment]
An example of this:

The Goblin Shepherd uses Call Beast
The Goblin Shepherd takes 0 points of damage.

**Comment by bendangelo** [comment]
Mobskill message is not being set. Probably because of this commit: https://github.com/DarkstarProject/darkstar/commit/bc01370744634714a40839a49284525c46ac3824

**Comment by Altalus** [comment]
Referred 1367 to here (1366) and then closed 1366? :)

 

______________________________

Guillaume Gingras

**Comment by teschnei** [comment]
Yep. I normally close them after I push a commit that (is supposed to) fix
it

**Comment by Altalus** [comment]
Ok, I missed the commit then, sorry about this :)

 

______________________________

Guillaume Gingras
