### ISSUE TITLE
NMs that can cast magic... aren't doing so much at all anymore.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1368]
King Arthro used to cast a spell every 20~30 seconds; now he's casting 1 spell per fight with the latest code.

**Comment by dazusu** [comment]
Some additional information:

KA has a SpellScript defined. I added a printf() to this, and it is being called every 30 seconds; and  a spell ID is being returned, however - the NM never casts the spell that is returned.

**Comment by b03605079** [comment]
same here, nm dont cast most of their magics right now.
normal mobs seems alright?

**Comment by xdemolish** [comment]
it's loading the spells from the global spell list instead of the mob's spell list

i'd fix but lolCSpell::getJob/setJob
