### ISSUE TITLE
Areas not being added to search list

### ISSUE THREAD

**Issue by Xaver-Entropia** [DarkstarProject/darkstar#1369]
From some time now I've noticed that whenever you visit a new area, that area is not being added to the list in Search/Area.
I think I remember it was something like this...

Area
Region
World
Bastok[4]        <-- This doesnt appear, just an example.
Gustaberg[2]  <-- Another example, doesnt appear either

and so on...

**Comment by nesstea** [comment]
/sea all linkshell doesn't show current LS members as well.

**Comment by personaone** [comment]
yeah /sea <location> name didn't work for me for a long time either, guess this isn't implemented

**Comment by Xaver-Entropia** [comment]
@personaone The thing is this used to work fine, but I dont remember when they stoped working.
Or at least I remember it working, but i might be mixing it with retail... I dont think so, but might be.

**Comment by teschnei** [comment]
3f28b8d5d3be98405eef1897eaef9be87ae4e37e
