### ISSUE TITLE
Dsgame crash on Dynamics Sandy win

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1370]
Linux server, 64bit,crashes as soon as the boss is killed. Possible issue with spawning the ??? ?

**Comment by xdemolish** [comment]
got a dump?
@teschnei can tell you how cause i don't linux (he can update the wiki with info, too!)

**Comment by Cloudef** [comment]
You can obtain dump by building darkstar with debug symbols (IIRC this is done by default).

Then the following steps:
```
gdb ./darkstar-game
set logging on
set logging file my-dump
run
# play the game and wait for server to crash
bt full
```

Alternatively, if your distro has ``systemd`` and assuming you had binary with debug symbols (unlikely if you installed darkstar from package), your crash probably is already in ``coredumpctl``.

**Comment by m241dan** [comment]
![screenshot 2015-04-30 11 36 15](https://cloud.githubusercontent.com/assets/3581401/7416642/ec65cb38-ef2e-11e4-8c49-b405342d40c9.png)

no core, but that should help?

**Comment by Cloudef** [comment]
Yes, that helps. Kinda weird it's screenshot though.

**Comment by xdemolish** [comment]
cant get it to crash, gonna need an actual dump file to poke around any further

**Comment by m241dan** [comment]
I'll get one then

**Comment by xdemolish** [comment]
gonna need the dmp, pdb, exe and log in an archive (preferably 7z)
drop a link when it's uploaded and i'll take a look

**Comment by m241dan** [comment]
It's linux, how to get pdb file from that?

I'm still working on getting a dump but I don't have a test server and only do resets on Friday because the players get all uppity about server going up and down.

If it helps, I isolated the problem on the lua side. It comes in the "start second half" lua binding call. That's likely where a nullptr is.

**Comment by bendangelo** [comment]
Need a dump.

**Comment by m241dan** [comment]
I believe this one was resolved?

**Comment by bendangelo** [comment]
Ok then I'll close it.
