### ISSUE TITLE
R0 on login

### ISSUE THREAD

**Issue by sisternERA** [DarkstarProject/darkstar#1371]
i have noticed that some people will log a character in and will R0 within two seconds and the only way to fix it is to nullify the zones column in the sql char table.  While it allows the player to login it also wipes all spent merit points.
Dont know if it is relevant but started happening after i enabled the home point crystal teleports.

**Comment by sisternERA** [comment]
also it seems that it does not create an account sessions entry when it happens

**Comment by teschnei** [comment]
if it's zones in sql, it sounds like it's probably related to #1369, probably that section of the packet moved/bug invalidated it

**Comment by teschnei** [comment]
3f28b8d5d3be98405eef1897eaef9be87ae4e37e
