### ISSUE TITLE
AOE from mobs are dealing 0 dmg

### ISSUE THREAD

**Issue by spartan4** [DarkstarProject/darkstar#1373]
Hello everyone! AOE from Mobs such as Fafnir 'Hurricane Wing", Vrtra "Absolute Terror", and "Spike Flail" from all HNMs are yielding 0 dmg to players no matter what level they're at. Even Pandemonium Warden's "Bilgestorm" yields 0 dmg to every player fighting him. Tiamat's "Inferno Blast" and "Touchdown" Yields 0 dmg as well. Not sure if it's an AOE thing for mobs but they're all stuck at 0 from what I tested. Just throwing it out there. AOE WS from mobs seem to be broke on those but I'll keep up updating more once I test more.

**Comment by teschnei** [comment]
have you updated since this morning?

**Comment by spartan4** [comment]
Hey Tes! Not yet but I'm updating now and checking files. I'll get back to you once I'm done. I just got done fighting Tiamat with a group of people on the server and he wouldn't land at all even casting heavy magic on him. He would land for a half a second and then fly again right away. They were telling me he would jump right up in the air again once he went down but I'll post an update once I'm done.

**Comment by spartan4** [comment]
Yeah after latest update and testing these, they seem to be broke. Most of their AOE or TP moves yield 0 dmg from what I've seen. Just tested it again on Fafnir, He yielded 0 dmg on his TP moves.

**Comment by bendangelo** [comment]
It dealt 0 damage or it's just displaying 0 damage?

**Comment by teschnei** [comment]
it's working fine as of e5b33a66de3c41c609e4694e36358b8030ea8d67, so i'll chalk it up to not updated yet
