### ISSUE TITLE
Event Packet structure not correct?

### ISSUE THREAD

**Issue by ProjectTako** [DarkstarProject/darkstar#1375]
I was trying to implement the Imperial Silver Piece NPC (Kaduru-Haiduru). I am capturing packet information using an Ashita v2 Plugin. I took my structure from:
https://github.com/DarkstarProject/darkstar/blob/master/src/map/packets/event.cpp

The plugin captures the data like this:
uint32_t playerId = RBUFL(lpRawData, (0x04));
uint32_t param0 = RBUFL(lpRawData, (0x08));
uint32_t param1 = RBUFL(lpRawData, (0x0C));
uint32_t param2 = RBUFL(lpRawData, (0x10));
uint32_t param3 = RBUFL(lpRawData, (0x14));
uint32_t param4 = RBUFL(lpRawData, (0x18));
uint32_t param5 = RBUFL(lpRawData, (0x1C));
uint32_t param6 = RBUFL(lpRawData, (0x20));
uint32_t param7 = RBUFL(lpRawData, (0x24));
uint16_t targetIndex = RBUFW(lpRawData, (0x28));
uint16_t zoneId = RBUFW(lpRawData, (0x2A));
uint16_t eventId = RBUFW(lpRawData, (0x2C));
uint8_t cameraJump = RBUFB(lpRawData, (0x2E));
uint16_t textTable = RBUFW(lpRawData, (0x30));

This might not be the best/most efficient way of doing it, but it seems to be working for simple things like getting event IDs and params. So I take this data and I put it into chat as a new chat line, and this is what I see:

![image](https://cloud.githubusercontent.com/assets/5255628/7378886/b6aa2b0e-edbe-11e4-8e51-f67a6ee49df2.png)

This would lead me to believe that the event ID is event 151, however events 144-159 are all non events in client.

Maybe I am doing something incorrectly here to get the event ID, but this same structure seems to work for other events in the same zone (assault NPC, coming out of MH and asking if it should set HP etc);

**Comment by teschnei** [comment]
Most likely you are not parsing the packet correctly.  Hard to say without
seeing the actual capture

**Comment by teschnei** [comment]
Actually, looking at your player ID in your output, I'd say it's pretty
certain you are not parsing it correctly

**Comment by teschnei** [comment]
at any rate, the csid and params are right, I just put them in my server and the correct cs came up

my best guess would be that you forgot about text table (aht urhgan whitegate is the only zone that uses it), and got no cutscene because you left it at default.

closing because the packet structure is correct
