### ISSUE TITLE
D-Box EX Items

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1376]
It's a thing. Built last night. Tons of items.

![capture](https://cloud.githubusercontent.com/assets/1483915/7383790/51b9e39e-edda-11e4-996a-514d8aca0e0c.PNG)

**Comment by nesstea** [comment]
Seems some of the items are out of wack.

**Comment by xdemolish** [comment]
gj max
even though you haven't even done anything yet
