### ISSUE TITLE
Avatar Prime battles

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1379]
Summoners can't use bloodpacts and the Primes ignore pets and run straight to the player.
Happens in Ramuh, shiva, and garuda, so far.

**Comment by nesstea** [comment]
Happens in BCNMs and Limbus as well.

**Comment by nesstea** [comment]
Just change the started to 0 in its lua file.

**Comment by csundman** [comment]
A bunch of people on my server are seeing this issue.  Specifically that the Primes ignore the pets and only attack the player.  Could you please elaborate on what you mean by "change the started to 0 in it's lua file."  Is this a possible temporary fix?  Which file is this referencing?

**Comment by teschnei** [comment]
Cause: pets do not receive bcnm restriction buff that allows them to be targeted by other things in the bcnm
(todo)

**Comment by teschnei** [comment]
f4b5fa008e096023a5cbe8005827f0b19b4c271c
