### ISSUE TITLE
DSGame-Server.exe crash launch

### ISSUE THREAD

**Issue by Andrew-Best** [DarkstarProject/darkstar#1387]
Hey folks,

I tried to start my own server and loaded all the .sql files as necessary, built the code and when I attempt to run DSGame-Server.exe it crashes at the end of the while loop in LoadWeaponSkillsList(). The actual crash occurs in the list insert portion.

Any ideas as to what's happening?

**Comment by whasf** [comment]
Fixed in 88300f3e6f7aae889a1c3d6c5d54d17629c88004
