### ISSUE TITLE
navmesh error

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#1393]
It would be helpful if the navmesh errors (not just this one) showed the zoneID of where the error was occurring to make debugging easier on a server with >1 person online.

 CNavMesh::findRandomPath startRef is invalid (1000.000000, 1000.000000, 1000.000000)

**Comment by bendangelo** [comment]
Found the problem. I'll add the zoneid.

**Comment by bendangelo** [comment]
Forgot to link it. https://github.com/DarkstarProject/darkstar/commit/9c7378b80d4213a819f37e90fe85be1033c89ca8 Fixes it.
