### ISSUE TITLE
Unescapable Mog Garden

### ISSUE THREAD

**Issue by ElectronJunkie** [DarkstarProject/darkstar#1394]
Zilart Expansion only activated.
With mog house exit quest complete you are able to enter the mog garden but have no way to leave the zone by normal methods as there are no points with which to interact.
Warp item/spell or GM is required.

**Comment by TeoTwawki** [comment]
@ElectronJunkie last I checked the moogle there was able to send you back to home nation.
```lua
    elseif (csid == 1016 and option == 0xFFB00FF) then -- Leave this Mog Garden -> Whence I Came
        player:warp(); -- Ghetto for now, the last zone seems to get messed up due to mog house issues.
```
The code to do it is still there. Is the moogle not responding?

**Comment by teschnei** [comment]
He does not spawn if seekers is disabled.

**Comment by TeoTwawki** [comment]
He exists in retail even if you don't have seekers (I don't have seekers, was still able to go there and see the moogle) so we should change his flag exp. on NPC list to null.

**Comment by xdemolish** [comment]
get null'ing
