### ISSUE TITLE
Port Bastok Bridge - Stuck Open - Unusable

### ISSUE THREAD

**Issue by ElectronJunkie** [DarkstarProject/darkstar#1400]
On a clean server reboot/restart the bridge appears to work for a few minutes to hours. As time goes on the bridge becomes unpassable. The bridge can appear either up, down or half way up on the client but clients are unable to walk onto the bridge. The animation is also out of sync with the airship departure (visually closes early) but returns to a half raised position after airship leaves.

**Comment by nesstea** [comment]
change the bridge's lua file to started = 0

**Comment by ElectronJunkie** [comment]
I can confirm that this does indeed work and will keep an eye on it over the weekend to see if there are any changes.

\scripts\zones\Port_Bastok\npcs\_6kt.lua
started = 0

There is still a visual bug that I don't believe was in retail where as you approach the bridge it will render in the up position for split second. I am assuming the check if open starts from the up position?

**Comment by ElectronJunkie** [comment]
Update latest update has fixed the bridge, no need to set "started=0" anymore
