### ISSUE TITLE
zone change >> invalid key crap

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1409]
This is new..I was already in game. How the crap did I get invalid key crap just by changing areas. This is on latest trunk, as of 5 minutes ago. All I did was zone from lower Jeuno out into Rollanberry. **So, who do we burn at the stake?**

**Comment by xdemolish** [comment]
both zones on the same server?

**Comment by TeoTwawki** [comment]
what the...its 1 specific character on my test box. specifically the 1st character I created on this database. And only in rollanberry. If I edit the db to move him anywhere else I can log in fine and zone to anywhere except rollanberry...second I go into rolan his key is invalid just on zone change, and then can't be logged back in till I move him. Doesn't happen to any additional characters I create. This doesn't even make sense. This is going to be worse than that bloody homepoint bug.

...I have no sql errors in console logs at all, but I'm going to wipe the database anyway and remake the character (its only a testbox, nothing important) and see if I can make it happen again after that... I'll keep a backup of the current db for later analysis if I can't reproduce.

**Comment by TeoTwawki** [comment]
doesn't happen on new database. I had no sql errors, and my database was up to date (I did *NOT* miss executing changes) so i am very curious wtf aspect of that one character was triggering invalid keys. I'll leave it up to you if you want to close this, and I have a backup of the database to try and compare/reproduce it again later.

**Comment by bendangelo** [comment]
I had this happened right after prev_zone update.

**Comment by TeoTwawki** [comment]
Legion server inform me they now have a crapton of characters being effected by this or something like it in diff zones. Once a character is hit by it they can't get it to stop happening, but they have 47 ppl online right now with no problems so its not the same for every character - R3's own characters can't enter a zone I am presently in, north sandoria. Zone is fine for me but not for him.

**Comment by xdemolish** [comment]
set a breakpoint on the invalid key print
when it's hit, save a dump and post a link

**Comment by xdemolish** [comment]
managed to trigger it by adding every status effect up to 768
should be good with this https://github.com/DarkstarProject/darkstar/commit/f3d75ea3b85d271538022808bb7614c18f2bb520

**Comment by TeoTwawki** [comment]
Yes seems to be all fixed now, with a new very minor issue I'll make a new report for (doesn't really look related).
