### ISSUE TITLE
the trade does not work between players

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1410]
Hello, when I want to share a pearl for example to another player . The pearl is on the list, but did not Appare in the table of trade . The same thing happens for any player 

EDIT: The trade with the guard for crystals work, but a trade between players are not working. Strange..

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/85efac95bdb69b494cd9f91c6f897efd5c350e04
