### ISSUE TITLE
lua startEvent issues

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1411]
Build Linux. Updated today, that's when this started.

Seem to work fine from @cs but for example, my kirin teleporter just locks up after the event is selected. And, I've been getting a lot of players that are getting locked up in the same way on GoV books, Lower Delkfutts and Maze of Shakrami are two I have recorded.

No error messages.

@cs 5 in the Shrine will warp you to kirin but try to take the teleporter, which to my knowledge essentially does the same thing, locked up.

The books seem to be sporadic but the kirin teleporter is a constant.

**Comment by xdemolish** [comment]
it's due to the way zone 'regions' are handled (their luautils calls reset the player's event info)
easy fix is to just revert https://github.com/DarkstarProject/darkstar/commit/bda34c8935d6998326dec9ea2720e9fc7086a95d

til someone feels like working on handling regions better anyways

**Comment by xdemolish** [comment]
dumping on @teschnei (though i think he already fixed it)

**Comment by TeoTwawki** [comment]
open new issue if still experiencing problem (I think this was fixed)
