### ISSUE TITLE
rank 7 bastok does not work?

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1412]
Hello,
On the wiki darkstar site, the page said bastok rank 9 and I read rank 6?? But for the mission of Sand'oria, I'am Rank 9.

https://wiki.dspt.info/index.php/What_Works#Missions

Missions
All nation missions currently work up to rank 6 and therefore will be marked as green, as it does not hinder any game play to not be able to go further than that.

Bastok -- Rank 9

San d'Oria -- Rank 9

Windurst -- Rank 8

Rise of the Zilart 

but I am at the mission The Final Image of the rank 7. In the console of server, when I click ??? luautils::onTrigger: cannot open scripts/zones/RoMaeve/npcs/qm3.lua: Not such file or directory.

Any idea?

Thanks

**Comment by AlexandreCA** [comment]
Ok, so , to correct the problem . Go to scripts/zones/romaeve/npcs/
We must make a copy of the QM2 and paste . Rename it QM3

**Comment by Turttle** [comment]
I guess the wiki page has not been updated.... Sandy and Bastok rank 10 is OK, Windy still on rank 8.

**Comment by AlexandreCA** [comment]
Yeah but, nothing update on GitHub :(

**Comment by gedads** [comment]
depends, qm2 is the right one but is supposed to move in retail. did you try to find qm2?
qm3 is @ A-8, possible location for right ??? are     D-10 E-9 E-10 E-11 G-9 I-8/J-8 K-10 K-11 L-10 L-7
not sure if qm3 what you're looking for.

**Comment by AlexandreCA** [comment]
On nasomi after he had to make a copy paste of QM2 and rename the QM3 . This gives us QM2 and QM3 . And it turns out that it works. For cons , I had a big bug at the end of rank 8 when I finish the mission. A video is supposed to do and I got a black screen in place . When I review the NPC to him the mission but the mission is completed the menu is still active.
