### ISSUE TITLE
Conquest

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#1416]
Underflows all over in GainInfluencePoints()
Hopefully someone with more knowledge in C++ data types can fix it.

**Comment by whasf** [comment]
This is still happening as of latest rev

**Comment by whasf** [comment]
i reset conquest_system to imported table, login.. kill a mandy in east saru, and the values get all messed up still

**Comment by whasf** [comment]
@z16

**Comment by takhlaq** [comment]
i think this was fixed at some point but don't care to login and test
@whasf can you close if this is no longer an issue
