### ISSUE TITLE
Bastok Mission 9-1 problem

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1422]
I was the Bastok Mission 9-1 . The ??? brings up a monster after you kill the first ( gigaplam ), two other monsters appear (2 macroplasm ), but after that, instead of being replaced by 2 Microplam and then 2 nanoplasm . There is nothing!

 I click again on ??? and all this gigaplam reappears repeatedly. I can not have Miraclesalt (key item).

**Comment by Turttle** [comment]
Are you on the latest version of DSP?

**Comment by AlexandreCA** [comment]
yes

**Comment by madwraith** [comment]
Tested on windows and works. With those filename changes t4nk415 from irc says works on linux now.

**Comment by AlexandreCA** [comment]
thanks!
