### ISSUE TITLE
Zilart: BCNM Temple of Ugga causing hangup

### ISSUE THREAD

**Issue by Desufire** [DarkstarProject/darkstar#1425]
There are no errors that I can find, otherwise I'd upload a dump, but players are hanging up after win in BCNM Temple of Uggalepih. The cs plays and Grav'iton says:

"It all started with a mere crystal and the mysterious power that it held..." and then the game hangs on a black screen. 
Commands release and posfix do nothing to help. bring and homepoint get the player away from black screen, but mission flag does not update doing this and they must do the fight again.

I've looked into the scripts and couldn't see anything wrong with them.

**Comment by gedads** [comment]
remind me a fix from long ago... https://www.youtube.com/watch?v=5r4zcFHcLeU
where are you stuck, @ first cs, second cs or exit?

**Comment by Desufire** [comment]
First cs transitioning into the second.

Reported to me that they waited a few minutes in case of long load time. I didn't know I could add the KI to access the fight, so I'll be doing that now to see for myself. I hope I didn't just report this for no reason.

**Comment by Desufire** [comment]
Edit: After testing it, I was able to recreate the problem on 2 other GMs. Each allowed 5 minutes plus for CS to load and nothing happened. The only thing being shown is chat box. But again, there are no errors being shown on server logs, so I don't know what's going on.

**Comment by gedads** [comment]
ok i'll have a look.

**Comment by AlexandreCA** [comment]
the same problem.

**Comment by gedads** [comment]
same issue https://github.com/DarkstarProject/darkstar/issues/1411

**Comment by teschnei** [comment]
7b76bdaaa7993ed9a9e1fefb84b8b6de9d584993

**Comment by AlexandreCA** [comment]
I think there is still a small problem with the 2nd CS or we are told the story of Zillart . A black screen appears . The video in 4:03 min show good the situation.  

 https://www.youtube.com/watch?v=5r4zcFHcLeU

**Comment by teschnei** [comment]
3fe203c

**Comment by AlexandreCA** [comment]
Thank you , but no. The problem has not changed :(

**Comment by TeoTwawki** [comment]
@teschnei its stalling at the chang over from cs 0x0007 to 0x0008, 1 cs plays fien (unless they use the eternity plugin, which usually breaks it) and the 2nd never starts. The zone.lua script has onEventFinish for the 1st start the second.

if I (at)cs them, these both play just fine even causing one to trigger the other, because of that weirdness where the zone lua gets read for (at)cs.

**Comment by teschnei** [comment]
it's not stalling anymore, it just takes 10+ seconds to load all the NPCs (look at your server log! the 016 spam means it's requesting NPCs!)

**Comment by TeoTwawki** [comment]
No, it IS stalling when I try it. It ends the 1st cut scene and just releases me - second CS never starts. I went afk and left my char there for an hour while doing laundry, it never starts. And I didn't expect it to, since I was already released and able to move use menu's etc.

**Comment by AlexandreCA** [comment]
Teotwawki, It's just that

**Comment by TeoTwawki** [comment]
@AlexandreCA  When I revert changes to SmallPacket0x05B packet it works again (both the original change and its "fix"). But when I said I was still seeing a problem I was told it worked fine for him as trunk has it now. Doesn't for me.

**Comment by AlexandreCA** [comment]
Bah , I have the same problem as you. That 's what I mean. Despite the correction teschnei , the end of the CS is a black screen.

**Comment by TeoTwawki** [comment]
I understood you. :smile:

**Comment by AlexandreCA** [comment]
I had to use the command to GM has overcome this problem.

**Comment by Desufire** [comment]
Ok, here's a bit of a necro. Got another bcnm cs problem on mission 2-3 (Sandy). Player submitted that no cs plays on start, the bcnm loads with no fight. 

Took Gm in with him and confirmed. It just loads the bcnm without the dragon/eye, completely skipping the cs that should play.

No errors show on server.

**Comment by Hozu** [comment]
Ok the first ending CS of ZM4 completes, it grants the title, but when it goes to play the second CS it doesn't start. The people on the mission where able to cast Cure on me when I was properly exited due to having the mission completed long ago. They did not get the Dark Fragment nor did they get the next mission.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/63ecf03a203280f6df17a62edf80a78300d88831

**Comment by TeoTwawki** [comment]
@xdemolish go look at the diff on that. Seriously?

**Comment by TeoTwawki** [comment]
I still see issues with daisy chained CS's elsewhere (example: trying to implement cs's for voidwatch that dsp doesn't have yet, in pashow (s) the verdical conflux needs to start event 0x0008 immediately following event 0x0007..the second cs never plays, leaves character on black screen.

```lua
-----------------------------------
-- Area: Pashhow Marshlands [S]
--  NPC: Veridical Conflux
-----------------------------------
package.loaded["scripts/zones/Pashhow_Marshlands_[S]/TextIDs"] = nil;
-----------------------------------

require("scripts/globals/quests");
require("scripts/zones/Pashhow_Marshlands_[S]/TextIDs");

-----------------------------------
-- onTrade Action
-----------------------------------

function onTrade(player,npc,trade)
end;

-----------------------------------
-- onTrigger Action
-----------------------------------

function onTrigger(player,npc)
    if (player:getQuestStatus(CRYSTAL_WAR, GUARDIAN_OF_THE_VOID) == QUEST_AVAILABLE) then
        -- For stage IV Crimson, Indigo, and Jade, we set 1 bit each
        -- for VW_3_NATIONS instead of for a var named for the KIs.
        if (player:isMaskFull(player:getVar("VW_3_NATIONS"),3) == true) then
            player:startEvent(7);
        end
    elseif (player:getQuestStatus(CRYSTAL_WAR, A_CAIT_CALLS) == QUEST_ACCEPTED) then
        player:startEvent(9);
    end
end;

-----------------------------------
-- onEventUpdate
-----------------------------------

function onEventUpdate(player,csid,option)
    -- printf("CSID: %u",csid);
    -- printf("RESULT: %u",option);
end;

-----------------------------------
-- onEventFinish
-----------------------------------

function onEventFinish(player,csid,option)
    -- printf("CSID: %u",csid);
    -- printf("RESULT: %u",option);
    if (csid == 7) then
        player:startEvent(8);
    elseif (csid == 8) then
        player:addQuest(CRYSTAL_WAR, GUARDIAN_OF_THE_VOID);
        player:setVar("VW_3_NATIONS", 0);
    elseif (csid == 9) then
        player:startEvent(10);
    elseif (csid == 10) then
        player:completeQuest(CRYSTAL_WAR, A_CAIT_CALLS);
        player:addQuest(CRYSTAL_WAR, THE_TRUTH_IS_OUT_THERE);
    elseif (csid == 12) then
        -- player:addQuest(CRYSTAL_WAR, ???);
    end
end;
```

**Comment by TeoTwawki** [comment]
Opening new issue since this isn't specific to temple ugly.
