### ISSUE TITLE
flourish triggers debug break on MAX_SKILLTYPE

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1431]
https://github.com/DarkstarProject/darkstar/blob/a09dc8b30443232cac21da306e41c039963134a1/scripts/globals/abilities/violent_flourish.lua#L85

https://github.com/DarkstarProject/darkstar/blob/a09dc8b30443232cac21da306e41c039963134a1/scripts/globals/abilities/desperate_flourish.lua#L65

That call to getSkillLevel() in those scripts trips this debug break https://github.com/DarkstarProject/darkstar/blob/a61ee5e34c8aee9309c3e1de26124e6e4e347dae/src/map/lua/lua_baseentity.cpp#L1923 and since this commit https://github.com/DarkstarProject/darkstar/commit/7dce09bb1daff9c330d61af17306027232e310c0#diff-89a95d61edadcc18eafd55b82089169eR1923 added that check, I make this your problem @xdemolish  :stuck_out_tongue:

**Comment by xdemolish** [comment]
i dont even know how it'd get a value over MAX_SKILLTYPE
prolly gonna take a look at this later tonight

**Comment by sisternERA** [comment]
i know its not the only thing causing the max skilltype crash.  there a re corsair roll like magus causing this same issue

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/8a066b4fd866d9d8ff86f1cd432569b89ce4b019
