### ISSUE TITLE
DSGame-server crash on Trigger Many Synth Support NPCs

### ISSUE THREAD

**Issue by chipmungus** [DarkstarProject/darkstar#1435]
Southern San d'Oria, D-8
Orechiniel
Tek Lengyon
Kipopo

Bastok Markets
Ulrike
Wulfnoth

triggering any of these causes DSGame-server to crash. Possibly others. Issue not present on Smithing support NPCs @ North San d'Oria

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/8a5c89c2d41b113ea53f21381fa75eadb9988555

there's probably others that are using the wrong ids too so you can fix and pull req them! (if there are any)
