### ISSUE TITLE
Weapon delay is reset on engage

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1443]

**Comment by bendangelo** [comment]
Are you saying weapon delay is currently reset on engage? If so then what should happen?

**Comment by teschnei** [comment]
it's already fixed on AIRewrite

**Comment by dazusu** [comment]
When the delay for your first attack is calculated after engaging; it should be taken from your main hand weapon - discounting dual wield if you have a second weapon equipped.

If you have two daggers equipped, for example, and engage a monster, you might find yourself waiting 3-5 seconds for your first attack; in reality, it should be based on the delay of the main hand weapon only.

**Comment by dazusu** [comment]
derp, beaten by a few seconds :P

**Comment by teschnei** [comment]
No, the engage delay has nothing to do with your weapons delay

**Comment by dazusu** [comment]
Oh really; presumed it did. Just know that initial delay was way too long with two weapons. Thanks

**Comment by teschnei** [comment]
it's about one second with anything (I literally just attacked a tiger on
retail with my kogarasumaru to confirm) - just the re-engage delay is based
on your weapon delay
