### ISSUE TITLE
CoP Mission 0 - "Ancient Flames Beckon"

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#1445]
CS happens in Lower Delk's Tower, however eventually times out after even using @release on many many chars/logins. Seems to be a glitch with the mission, it also shows on all chars right now, that the mission is both "Current" and "Last Completed" but there is no text at all inside of it. Started after recent update to XI.

**Comment by helixhamin** [comment]
I can confirm. This is completely broken due to a new update. It will do a couple cutscenes, then nothing. If you don't have an at command, you are stuck there...

**Comment by dazusu** [comment]
Also experiencing this.

**Comment by helixhamin** [comment]
aka: It's dead Jim.

So, how do we bring it back to life? The code snippet that broke it has already been potentially identified: https://github.com/DarkstarProject/darkstar/blob/bda34c8935d6998326dec9ea2720e9fc7086a95d/src/map/packet_system.cpp#L2538

However, I have no idea how to fix it myself. Anyone want to look into it that understands the code better than me?

**Comment by teschnei** [comment]
You figure out why the event ids aren't equal

**Comment by xdemolish** [comment]
prolly same as this if its tele related https://github.com/DarkstarProject/darkstar/issues/1411

**Comment by teschnei** [comment]
7b76bdaaa7993ed9a9e1fefb84b8b6de9d584993
