### ISSUE TITLE
When a player is charmed by a Corse mob, the player does not move (the player should move and attack people on the mob's enmity list)

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1452]

**Comment by ashdam** [comment]
I think charm AI is not implemented yet.

**Comment by teschnei** [comment]
They will move and attack other people, but it won't display on their own
client yet

**Comment by dazusu** [comment]
The other people around them are not seeing it either (ie, the people 
getting attacked).

**Comment by teschnei** [comment]
Okay, I'll keep it in mind next week when I nuke the AI classes

**Comment by xdemolish** [comment]
yus, been waiting for AI rewrite for long tiem
