### ISSUE TITLE
En-Spells bug

### ISSUE THREAD

**Issue by Desufire** [DarkstarProject/darkstar#1455]
Nothing huge at all, but I can't figure out where to correct it.

The En-Spells are not applying to both weapons while dual wielding. Only Main Weapon is being effected.

**Comment by teschnei** [comment]
Enspell I or II?

**Comment by Desufire** [comment]
Sorry it has taken so long to answer. It's Tier 2 en-spells. So that would be the spell scripts I assume?

**Comment by TeoTwawki** [comment]
Tier 2 enspells aren't supposed to work with dual wield, retail makes them only proc 1st swing.

**Comment by Desufire** [comment]
It does? It's been a long time but I could've sworn it proced both on my rdm. I must be remembering wrong :(. Sorry to post an inaccurate issue then. I'll be sure to research more thoroughly in the future before submitting.
