### ISSUE TITLE
Porter moogle item loss

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1460]
@MalRD

Have received reports that "any piece of gear" and "lost all abjuration gear, sky gear, salvage gear, relic gear. fuck off" from a user who likely won't be getting his gear back if he doesn't apologize for his attitude.

Anyway, someone should recheck the code that moogle is using. I can't verify or adjust anything if it needs it right now, too much on my plate and am not familiar with scripts in question anyway.

**Comment by teschnei** [comment]
Db dump of relevant stuff probably useful (it's in the extra data in the
vouchers I think)

**Comment by TeoTwawki** [comment]
k, will dump that table and find his vouchers when I get a chance and post those sql entries here.

**Comment by TeoTwawki** [comment]
Dumped to a gist
https://gist.github.com/TeoTwawki/73d2d8bf98886220ea34#file-exdata-sql-for-storage-slips

**Comment by MalRD** [comment]
What pieces of gear is the player attempting to store and retrieve?

**Comment by TeoTwawki** [comment]
Got swore at instead of additional info, so I don't even know.

"*Hi I play a char of a name I won't tell you I lost items that I am not telling you which ones and I lost them at an npc that is somewhere in the northern hemisphere of vana'diel. But I will curse at you for my loss!*" I only knew which character to dump the sql of because another post elsewhere said his character name. Claimed all his abjuration gear and sky gear was lost but I've no idea what pieces he had.

This guys a real winner. I'll totally understand if you can't do anything without more info.

**Comment by teschnei** [comment]
looks like it's probably all still in the db, so it's just the event

**Comment by zynjec** [comment]
Stale, if anyone has this problem feel free to open another issue.
