### ISSUE TITLE
Perma-Buffs when Zoning

### ISSUE THREAD

**Issue by chipmungus** [DarkstarProject/darkstar#1461]
When a player changes zone as a buff (or debuff?) is about to wear off (~1/2 seconds), the buff and its effects become permanent. Doesn't happen every time. This persists through other zone changes, and even changing job.

At first this happened with flee, so I added to:

scripts\globals\player.lua

the following:

if (zoning) then
        player:delStatusEffect(EFFECT_FLEE)
end

which worked, but I've since discovered that it can happen with *any* buff. 

Don't wanna just remove all buffs on zoning due to stuff that shouldn't be removed; Signet/Dedication/FoV & GoV buffs and probably more that I can't think of.

**Comment by Desufire** [comment]
I had a player that had an Attack Down become permanent. Was a fairly potent one too. I told him to switch to a lvl 1 job and die. This cleared it up since death has a status erase.

**Comment by chipmungus** [comment]
Tried adding a loop to delete any statuses with less than a set duration, but it seems delStatusEffect doesn't support variables in the same way that addStatusEffect does.

Removing all non-essential statuses on zoning still leaves the possibility of infinite debuffs.

I'll leave it up to someone with more experience.

**Comment by TeoTwawki** [comment]
Durations between zero and one second seem to be erroneously saved as zero duration, which DSP uses for "infinite duration".

**Comment by teschnei** [comment]
423ff9ec82ac724eaa70b44e4c1dd31c6668bc67
