### ISSUE TITLE
stun locked

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1476]
Having an issue where mobs and sometimes players are permanently stunned until death, after being hit by a stun spell and occasionally sleep. 

Linux build.

**Comment by m241dan** [comment]
It puts them to sleep, mob action 27 and they never wake up

**Comment by m241dan** [comment]
I hacked a fix for this on my server but if someone wants to come up with a better solution go for it. I floored all my stun durations to 1. Base stun time is 5 but a 1/16th resist makes the duration 0. Well, Duration 0 status effects are not removed causing them to be totally stun locked.

**Comment by bendangelo** [comment]
I think that's the issue, duration of zero locks stun. I think some stuns are random and occasionally end up as duration zero.

**Comment by m241dan** [comment]
Yah, it definitely is. 1/16th is considered a resist but 1/8th isn't. 1/8th of 5 is less than one so its rounded to 0. And 0 Status Effects do not get removed. Raise the resist to 1/8th or floor stuns at 1 second. \(o.o)/

**Comment by bendangelo** [comment]
I'm looking at the code, there is no minimum value for status effects. Some status effects, obivously stun, should never be set lower than 1. I will work on a fix now.

**Comment by TeoTwawki** [comment]
May also be possible that zero duration ones should have resulted in no effect applied ie full resisted?
