### ISSUE TITLE
mistakes in mob spawn points list

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1478]
``` sql
INSERT INTO `mob_spawn_points` VALUES (17183442,'KaiserBehemoth','Auroral Alicorn',722,0,0,0,0);
```

Derp?

**Comment by bendangelo** [comment]
Is the in game name wrong? Want to fix it?

**Comment by TeoTwawki** [comment]
Its likely the there are a whole slew of mobs in that zone off by 1 or some such, that 2nd name column is extracted from the client. 

And no, posted this to pass the buck to other minions than myself because busy with other stuff + avoiding minor stuff till I get a better monitor again (My good one broke, this screen is downright puny, hard to see what I am doing).

**Comment by TeoTwawki** [comment]
p.s. 
there are also a ton of mobs mistakenly sharing group IDs near there, if anyone wants to volunteer to separate them.

**Comment by wrenffxi** [comment]
Original issue -- mobname and polutils_name not matching -- no longer occurs in mob_spawn_points.
