### ISSUE TITLE
level sync

### ISSUE THREAD

**Issue by magnusxi** [DarkstarProject/darkstar#1479]
It appears that if the person you are sync'd to dies and home points, the sync stays and you will remain at the level without it ever changing.

**Comment by xdemolish** [comment]
old bug (and from what i can see, doesn't look like this bug should exist in current code)

**Comment by magnusxi** [comment]
Thank you for the reply Tahir,

However, I just did an update on my server, and can verify that this issue
does still exist..

If the level synced party member dies and homepoints, the rest of the party
can continue to get experience at the synced level, I did not test what
would happen if any remaining members leveled to see if it would change the
sync, though I don't see why it would since the target's level did not
change.

If you want me to test anything let me know.

**Comment by xdemolish** [comment]
when did you last update? i pushed an update today which got rid of the permanent level sync bug

**Comment by magnusxi** [comment]
I updated this morning about 2-3 hours ago.. I'll look again

**Comment by magnusxi** [comment]
I checked the github and i guess i updated before your edit, but i made the
changes to packet_system.cpp and recompiled and it still remains, you can
even after homepointing the character you are synced to you can remove him
from party and stay solo in a party at the sync level.

I also tried leveling the character to see if the sync would wear and it
remained, also reinviting/inviting or removing players does not effect the
sync either, you can also resync to the synced level which will resync
everyone to your already synced level rather than your real level.

**Comment by xdemolish** [comment]
wrong commit :p 
pull from master and rebuild

**Comment by magnusxi** [comment]
You were right, I just had to re-pull/compile, however now when anyone
zones (warp, homepoint, ect..) other than the synced player it glitches the
sync to remain the level.
