### ISSUE TITLE
CoP mission issues - CS not happening

### ISSUE THREAD

**Issue by fallen45078** [DarkstarProject/darkstar#1487]
Not at home to give the exact error message right now, but upon arriving at the crag (doesn't matter which one), there is no cs. Players can still enter Promy, but upon arriving at the web of recollections, nothing happens and the player cannot enter. Will update later when I can get the actual error. CoP 1-3 Below the Arks

**Comment by fallen45078** [comment]
After rechecking, no error comes up (although I swear that a couple of days ago it referenced a missing script). The player gets the message "You hear a faint scraping noise, but the way is barred by a strange membrane"

**Comment by TeoTwawki** [comment]
The mission checks along the way are borked in multiple places. The BCNM entrance is checking for a mission you aren't on yet the way it is currently written. This mess happened because https://github.com/DarkstarProject/darkstar/pull/1355 was merged without anyone having tested it. Someone needs to run through from the beginning and fix each problem as they hit it. I'm not volunteering.

**Comment by fallen45078** [comment]
I put a bandaid on mine by changing the promy status check from 2 to 1, that seemed to bump the mission status up and allowed me to progress when testing. I will finish testing it tonight and see how far it will let me go before I stall again.

**Comment by Turttle** [comment]
Starting  on mission "0" or the lower dekuf tower (prob misspelled it) it does not give the CS, just a Black screen, the compass is not visible, and the player can not access any of the menus except the chat box.

**Comment by fallen45078** [comment]
Bumping the status check from 2 to 1 did allow the missions to continue to progress. I can confirm that it does indeed allow players to continue through to at least 3-2 (this is as far as I have been able to test to date due to time constraints)

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/65b59c810473ce7a04a7ecafabe947fb700cebd2 should have cleared this up.
