### ISSUE TITLE
Grave Concerns / Bat Hunt

### ISSUE THREAD

**Issue by smgorden** [DarkstarProject/darkstar#1488]
Somehow messages or flags associated with the Sandoria NPC quest Grave Concerns can override or take precedence over Bat Hunt mission such that King Ranperre's Tomb stone always says "There is a water skin lying here." and will never produce a cutscene, even if the Grave Concerns quest is complete. Server Host also tried fiddling around with quest flags as a GM for me, but alas... nothing could get me access to the tomb cutscene for Bat Hunt, effectively preventing completion of the quest via standard gameplay.

**Comment by The-Halcyon-Days** [comment]
Could not replicate the issue when I tested. The quest seems to be working properly at the moment.

**Comment by archbunkz** [comment]
I'm having this exact problem. I hoped completing Grave Concerns would help but it didn't.

**Comment by smgorden** [comment]
The only workaround was having my host update the server data such that the
quests were complete for my character (after I had performed all due
diligence to complete them the normal way), but I never got to see that
cutscene in-game. But at least I got to move and do other quests.

**Comment by Ninjistix** [comment]
I tired this today on our server BNetcc and I was unable to examine the tombstone to progress in the mission

**Comment by Fatalerror66** [comment]
I have this happening to me as i type.  I goto the tombstone and click on it to have it say "There is a water skin lying here."   When I went into the Tombtone.lua in zones folder and took out every thing that had to do with Grave Concerns the tombstone did nothing, I could click on it all day but couldnt get the cutscene to appear

**Comment by Sacshop** [comment]
Replicated the issue on a new build of dsp. Nothing else was flagged as it effected brand new characters that had nothing else done what so ever.

**Comment by teschnei** [comment]
ba78e7d4065904aabd4deb799e38fbde04916ee0
