### ISSUE TITLE
Null Zone Crashing Dynamis and Limbus

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1493]
https://www.dropbox.com/s/xwy1fv8vizq8n11/nullZone.7z?dl=0

**Comment by tagban** [comment]
Having similar issue

**Comment by TeoTwawki** [comment]
I've seen a few BCNM crashes that appear to be same crash as this. Something related to the change those status effects got in core a few weeks back maybe?

**Comment by tagban** [comment]
I completely blocked Dyna access til this is resolved. Not worth 4 reboots a day. Ever since disabling Dyna no crashes for me

**Comment by eraffxi** [comment]
https://www.dropbox.com/s/8dng4hoq1k4k9ux/dump.rar?dl=0
same issue, a few crashes for it from 6-8

**Comment by tagban** [comment]
Still having issues, just closed Dyna again.

**Comment by xdemolish** [comment]
reopen with a new dump if this is still an issue
