### ISSUE TITLE
GetMobList crash

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#1499]
something something GetMobList crash. not really sure if its a mod or something else. had a similar crash earlier in the evening but wasnt debugging at the time..   https://drive.google.com/file/d/0B_J1pbryqpPfN0ZNWnNTWWU2R0E/view?usp=sharing

**Comment by xdemolish** [comment]
in future compress using 7zip (should bring the size of the archive down to around 60mb)

**Comment by tagban** [comment]
I used 7zip but left it as a zip file for compatibility sorry lately been dealing with an asshole that uses exclusively winrar 5

**Comment by tagban** [comment]
Any luck deciphering what the heck caused it? If its something custom I will wipe the server  of all custom.crap.

**Comment by xdemolish** [comment]
leaving for @teschnei cause i gots no clue

**Comment by SwitchVII** [comment]
Not sure if it's related to this, but I've been experiencing server crashes when certain monsters are claimed.  Specifically I can confirm Poisonhand Gnadgad and Mee Deggi the Punisher.  Immediately upon taking action on them, server crash.
