### ISSUE TITLE
Upper Delkfutt's Tower - R0 and consistent disconnects in certain areas where monster population is high

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1504]

**Comment by teschnei** [comment]
Reproduction steps, for all bug reports, please. I had thought this fixed
because it stopped happening in my tests. "Certain areas" is not testable!

**Comment by dazusu** [comment]
Upper Delkfutts Tower @ -300 -175  22

**Comment by teschnei** [comment]
Thanks.  Should be sufficient

**Comment by gedads** [comment]
probably because of navmehses if you use them. same problem occurs in al zhabi

**Comment by dazusu** [comment]
Perhaps too many packets due to the sheer amount of mobs moving, and the client doesn't like it? @bendangelo

**Comment by teschnei** [comment]
Yes, that's probably why.  I already wrote something to recompress the packets if the final compressed size was too big, so it shouldn't be a big problem (just making sure it actually works and the size check is small enough)

**Comment by teschnei** [comment]
I'm not able to reproduce.  Are you sure it's consistent? Using @pos -300 -175 22 158

**Comment by dazusu** [comment]
Yes, but it might only occur with a navmesh loaded.

**Comment by teschnei** [comment]
if that's the case, where did you get a navmesh for upper delkfutt's tower?

**Comment by gedads** [comment]
dl it from my dropbox folder , i put it in the .rar test navmeshes

**Comment by teschnei** [comment]
please confirm as of 6b81a73b61b336edd282f25cfe84ed6988e00f3b whether the problem continues to happen

**Comment by bendangelo** [comment]
There is no navmesh for upper Delkfutt's Tower, I guess you're using one you created?

**Comment by dazusu** [comment]
Using one of Gedads.  I'll test this build later today to confirm it's 
fixed.

**Comment by dazusu** [comment]
Works perfect, thanks!
