### ISSUE TITLE
Zilart Mission 4 Bug

### ISSUE THREAD

**Issue by przemoc1** [DarkstarProject/darkstar#1507]
After defeating the BCNM for Temple of Uggalepih and watching first two cutscenes, the black screen strikes. Character can be moved around,chat window works, menus are accesible but the final cutscene doesn't start (no mission log update, no key item gain) Unfinishable.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/1425

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/1432

**Comment by xdemolish** [comment]
reopened older one cause apparently it's still an issue
