### ISSUE TITLE
Weaponskill Latent Weapons sql broken?

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1512]
I've poured over the code and can't seem to figure out whats wrong.

I've tested all of them Destroyers Senjuikiro, heart snatcher all of em, even when their variable is set to unlocked, they still retain their base characteristics and aren't modified.

**Comment by teschnei** [comment]
how are you checking they are modified or not?

**Comment by Kthulupwns** [comment]
Do you mean the item or the variable for them being locked/unlocked?

**Comment by Kthulupwns** [comment]
The issue is globally affecting all of these weapons, so Im just trying to deduce if each off these trial weapons sql in item_latent is wrong, or if theres another conflicting sql issue.

**Comment by teschnei** [comment]
the latent effect increases the DMG value and critical hit rate: how do you know these are not being applied?

**Comment by Kthulupwns** [comment]
because the actual combat damage your dealing to mobs doesn't change from when its locked to when its unlocked

**Comment by Kthulupwns** [comment]
for example if I equip Narigitsune and senj, they have the same 38 base value damage
when senj is unlocked, but even with it flagged, its still doing significantly less damage.

**Comment by teschnei** [comment]
Ah, okay. What are you editing to unlock them?

**Comment by Kthulupwns** [comment]
I just literally did 500 weapon skills with it equipped in the mainhand and relogged after.

**Comment by Kthulupwns** [comment]
still trying to figure out which table the variable saves to

**Comment by Kthulupwns** [comment]
chars.sql table Unlocked weapons tab

**Comment by teschnei** [comment]
Ah, okay. I'll look at it today or tomorrow. FYI, weaponskill points are
saved on the weapon itself in the extra data column in char_storage

**Comment by teschnei** [comment]
Oops, char_inventory

**Comment by Kthulupwns** [comment]
ah okay well i was looking at the unlocked weaposn tab in the char.sql
and it appears the blob data isn't recording correctly in that specific variable. Im still fairly new to the code so I may be mistaken but heres what I got 




"INSERT INTO `chars` VALUES (21993, 1155, 'Kthulu', 0, 245, 244, 20, 2.830, -4.799, 57.689, 0, 243, 65, -67.639, 6.000, -21.568, 0x0805020100000100000400040000000800080800000000000004020400000008080208080000000005000200030000000000040000000300000100000000050000050005000000000000000005050000000500050000050500000000000000000000000000000000000005050005000000000101000000000000000305000000000000000000000000000000000000000000000505000000000000000000000000000001000000010100010001010101010101050101010101010102000001010102040101020500000000000000000000000001010305010001010101010100000000050101010101000000000000000000000000000000000101010103030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0xFFFF01010101000100000000010101010101000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000FFFF00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000FFFF010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001B00010000000100010001000100010001000100010001000101010001000000000000000000000000000000000000000000000000000000000000000000000000000200010100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005C0001010101000100000000000000000001010101000100000000000001010101010101000000000000010101010000000000000000010001000000000001000000000101010100000000000000000101000101000000000001000001010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020001010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0x0400000000000010000040002000020000000000000000000000000000000000000408200000000C000034200008000000000000000000000000000000000000000800040000000000040000000000000000000000000000000000000000000002010012001007300001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200800400000007080E200000000000000000000000000000000000000000300200800100800000100000000000000000000000000000000000000000000000000200000A010108000088000000001F00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041900000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000900000000000000000000000000000AAF113000800000024000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 0x0003000008200001000000000000C0000045000010000000000000000000800000000000000000004A0000200F000000FEFFFFFFFFFFFFFF900F0000C0170000000000000000000050C00740300000000020002000000020C8100000B800000000300000000000000000000000000000004000000000040000800000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000FFFFFFFFFFFF000000000000002001000408000400000003000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000, 0xBED5BF720278EFFFFFFFC1E70FFDFF7C4F87EF9DF71E318410E3FF11C0F96170FC75FA3F00FF0140FFFF2F12040000000000000000000000000000400000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, NULL, 0x00000000000000000000105204000000000000000000000000000000000000000000000000000000000000000000, 0x0206849E16000700200100008004000000000100D80300C803C91600000000000060FC80023E000000000070AB40010000001A0000C10110FA349B1100000000000080202040000000000000000000000000000000000000000000000000, 0xF57FFFFFFF077D6612813608F0FFFFFFCDF8FFE7AFF71FDF7BFF3B50C4FFFF1F00000000, 6738199, 0x000000000000000000000000000100000000000000000000, 0, 0, 0, 0, 1);"

**Comment by teschnei** [comment]
pretty sure unlocked weapon is not used for anything anymore

**Comment by Kthulupwns** [comment]
my mistake then

**Comment by Kthulupwns** [comment]
okay so INSERT INTO `char_inventory` VALUES (21828, 1, 8, 17793, 1, 0, '', 0x710000000000000000000000000000000000000000000000)

**Comment by Kthulupwns** [comment]
is the variable in the char_inventory.sql table, from the blob file itself.

**Comment by Kthulupwns** [comment]
anyone had any luck on this?

**Comment by teschnei** [comment]
I think I looked into it and it was working fine

**Comment by Hozu** [comment]
This issue was resolved a while back, by the way.
