### ISSUE TITLE
Ix'aern DRG, Ix'aern DRK,not spawning at all.

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1513]
the mobids lua and their respective PH lua's look fine, so not sure if theres a missing variable or what but none of them are popping. Cleared many sets of ph's.

**Comment by Hozu** [comment]
Ix'DRG is currently set to spawn from a mob that doesn't spawn for whatever reason. The randomization doesn't happen on server boot, so it's defaulting to a mob that isn't even in one of the four rooms.

**Comment by xdemolish** [comment]
i blame @nesstea

**Comment by Hozu** [comment]
Ix'Aern DRG has been able to be spawned for a little while now.. Ix'Aern DRK is simply not implemented at all.

**Comment by nesstea** [comment]
Ix DRK needs reraise to work properly, along with all the other aerns
I still have my branch when I worked on it.

**Comment by TeoTwawki** [comment]
This was fixed, we forgot to close issue.
