### ISSUE TITLE
Kikoku relic damage proc not occuring on 75 cap, also paralyze working improperly

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1514]
pretty sure the item_mod sql needs to be updated for this specific item id 18312 (kikoku)

the paralyze proc on the weapon is proccing at the correct rate, but its not being overwritten by stronger versions of paralyze (I.E. Jubaku, Paralyze II, so on and so forth) which is a lua issue but I'm not sure how to correct it.) It is also overwriting stronger versions of paralyze which is parallel to the same issue.

**Comment by Kthulupwns** [comment]
-- Kikoku (75)
-- -------------------------------------------------------
INSERT INTO `item_mods` VALUES (18312, 23, 20);
INSERT INTO `item_mods` VALUES (18312, 355, 137);
INSERT INTO `item_mods` VALUES (18312, 431, 1); -- Add. Effect
INSERT INTO `item_mods` VALUES (18312, 506, 160); -- 16% chance of extra dmg.
INSERT INTO `item_mods` VALUES (18312, 507, 300); -- Occ. 3x dmg

INSERT INTO `item_mods` VALUES (18317, 356, 153);


The isse was these 2 lines,

INSERT INTO `item_mods` VALUES (18312, 507, 160); -- 16% chance of extra dmg.
INSERT INTO `item_mods` VALUES (18312, 506, 300); -- Occ. 3x dmg

their 2nd variable was inversed, merely adjusted the value. Should work now ^^

**Comment by TeoTwawki** [comment]
Regarding pralyze overwriting, is becaus enobody listened to me on how these are supposed to be written, so more thna dozen of teh existing item add.effect scripts are simply wrong.
```lua
target:delStatusEffect(EFFECT_PARALYSIS)
if (not target:hasStatusEffect(EFFECT_PARALYSIS)) then
    target:addStatusEffect(EFFECT_PARALYSIS, 15, 0, 30);
end
return SUBEFFECT_PARALYSIS, 160, EFFECT_PARALYSIS;
```
That is going to remove every paralyze on every proc and replace it. This is wrong behavior threes should be **no** delete of status effect happening and the paralyze being applied needs to be the correct power value. Then the core will decide if it should have no effect, overwrite, or be overwritten, based on the power level of the effect. A bunch of these were merged in this broken state and the author never adjusted his scripts after being told about it.

I have a few hundred scripts for items we don't have scripted at all yet, and every time I start prepping a pull request for them someone suddenly decided to share their version, and gets its mostly wrong. Makes me to not even touch this bs. A few of the ones I already shared have some mistakes with the power level or resist check, (and I think I messed up and mistakenly copied a mistake into the silence/sleep weapons) and I haven't gotten my fixed versions pull requested yet.

Anyway if you remove that delete lien and change the effect power, it'll behave. May also need to move the return into an if check on weather the effect applied to get 100% retail message behavior, I'd have to check that to be sure.

**Comment by TeoTwawki** [comment]
ps. aside from the range weapons the level checks/level correction in these items is also wrong. Research shows melee weapons proc at a static (or at least not level based - seems to be resist base donly) rate.
```lua
 if (target:getMainLvl() > player:getMainLvl()) then
    chance = chance - 5 * (target:getMainLvl() - player:getMainLvl())
    chance = utils.clamp(chance, 5, 95);
end
```

**Comment by Kthulupwns** [comment]
For sure. would just like to see this adjusted and pulled. It's been an issue for a long time now.

**Comment by Desufire** [comment]
Hmmm. Maybe that's why I haven't been able to get the Metasoma Katars working properly when I try scripting that effect. It's a pain with the 3 effects being "or" but I was noticing that everything seemed to get erased during the next attack round if something was applied.

**Comment by TeoTwawki** [comment]
I will try and get the adjustments in soon

If some random contributor not taking part in this thread shows up with a batch of 50-100 items again at the same time they better have it done correctly before causing an edit conflict on my branch or so help meeee...! 

If its done correctly I can just hit "use theirs" after mass selecting those files and boom no conflicts exist. If its done wrong I wind up having to edit a crapton of scripts for the 8 or 9th time and get discouraged form continuing to work on add effect items.

**Comment by TeoTwawki** [comment]
#1536  - note: may still need power/duration tweaking on the effect.
