### ISSUE TITLE
Monsters gain TP if they hit you for 0.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1517]

**Comment by bendangelo** [comment]
Looking at the logic, I think the affects players and pets as well. The player shouldn't gain tp if they get hit for zero as well right?

**Comment by bendangelo** [comment]
Opps missed a condition, I don't think this is a bug. Will need someone to confirm.

**Comment by dazusu** [comment]
Players should not gain TP if they are hit for 0.

**Comment by bendangelo** [comment]
This needs to be confirmed.

**Comment by ashdam** [comment]
As far as I remember when I left the game in ToAU when you or a monster hit
for 0 dmg, TP didn't increase.

**Comment by ashdam** [comment]
https://www.bg-wiki.com/bg/Tactical_Points
I found this and it says exactly that.

**Comment by maxtherabbit** [comment]
I don't think this is a bug, going to close unless someone confirms it

**Comment by dazusu** [comment]
Stand in Ronfaure and let a rabbit hit you for 5 minutes with stoneskin 
up. I guarantee it won't use a TP move.

If I must, I'll login and log it.

**Comment by dazusu** [comment]
In addition, taken from BG wiki (applies to players only in this statement): 

A player can accumulate TP in the following two basic ways:

Hitting the mob for more than 0 damage

More @ https://www.bg-wiki.com/bg/Tactical_Points

**Comment by bendangelo** [comment]
I believe this is expected behaviour but this has to be confirmed as a bug in darkstar. I looked at the code and it seems to be correct.

**Comment by bendangelo** [comment]
Just confirmed, doesn't happen.
