### ISSUE TITLE
Elemental Nukes damage increased substantially (too much) from recent update?

### ISSUE THREAD

**Issue by SwitchVII** [DarkstarProject/darkstar#1520]
https://github.com/DarkstarProject/darkstar/pull/1438

There's a lot of changes here that I don't totally understand, but it seems like this update has caused nukes in general to be significantly more powerful.  Was fighting King Arthro and his Waterga's were doing well over my maximum HP when I was 15 levels above him.  As another example, the Under Observation BCNM fight is now almost impossible to win as the Sobbing Eyes's spells destroy.  Even non-NM or battlefield monsters appear to be hitting noticeably harder with their nukes.

I'm not sure how to test/confirm these findings.  Anyone able to help?

Was a different update that caused this?

Maybe things were just weaker compared to retail before this change and I was simply used to the lower damaging spell system and should shut my mouth?

**Comment by teschnei** [comment]
Maybe. There could always be an error in the calculations somewhere, you
could math them to see if they match, etc

**Comment by SwitchVII** [comment]
I think there's definitely a problem here.  I went as a naked (yikes!) BLM75/RDM37 into East Saruta and nuked some Tiny Mandragora with multiple Fire III's and Aero III's.  Using the calculations in the "Damage Calculator - Magic BLM" spreadsheet found [here] (https://drive.google.com/folderview?id=0B0A0wGYYRRdaZjdlNTdkNTEtMDMyYy00OTVmLWI4N2ItNDMwMDI1N2VkYWZk&usp=sharing), this is what was expected vs my testing results:

**Spell**, **Expected**, **Actual***
Fire III, 686, 818
Aero III, 667, 795

I started with the BGWiki for the formulas, but eventually deferred to the spreadsheet to determine the expected values.  After seeing such a large gap, I decided to -- as you suggested -- run the calculations manually.  Here's the numbers:

**_BLM75/RDM37 (Naked) vs Tiny Mandragora_**

dINT = 67

		ΔINT0-49 	ΔINT50-99 	ΔINT100-199 	ΔINT200+
		V0 	M 	V50 	M 	V100 	M 	V200 	M 
-------------------------------------------------------------------------
Fire III 	290 	3.1 	445 	2.7 	580 	1.85 	765 	1 

D = mDMG + V + (dINT × M)
D = 0 + 445 + (17 * 2.7)
D = 445 + 45.9
D = 490.9

Damage Dealt = D × MTDR × Staff × Affinity × SDT × Resist × MB × MBB × Day & Weather × MAB/MDB × TMDA × Potency Multipliers 
Damage Dealt = 490.9 * 1 * 1 * 1 * 1 * 1 * 1 * 1 * 1 * 1.32 * 1 * 1
Damage Dealt = **647.988**

This number isn't the same as the spreadsheet.  I may have messed something up either in the spreadsheet or my manual calculation.  However, in either case, the expected vs actual is way off.

**Comment by teschnei** [comment]
is this dINT value as reported by the game server?

**Comment by SwitchVII** [comment]
No, it's based on the spreadsheet's dINT value for my job/level/gear vs the Tiny.  I didn't calculate it manually using the server data.

**Comment by teschnei** [comment]
you'll need to get the actual dINT from the server in order to figure out where the issue is

**Comment by SwitchVII** [comment]
I'm not sure how to do that... I can track the TIny Mandragora down to the mob_family_system.sql that shows Mandragora start with an INT of 4 (assuming I'm understanding that correctly).  These are the lowest level Mandragora, so does that mean the Tiny Mandragora have an INT of 4?  They're considered level 0, so is it less than 4?  My character's INT is 74, making a dINT of 70 rather than 67 if theirs is 4.

The using 70, the expected damage increases to 658.68, but that's still a far cry from the 818 actual on the server.

**Comment by teschnei** [comment]
add print(dINT) to magic.lua line 1446, execute the gm command reloadglobal magic, then cast again

**Comment by SwitchVII** [comment]
I run my server via services, so I don't see print output.  I changed it to:

caster:PrintToPlayer( string.format( "dINT: '%s'", dINT ) );

Hopefully everyone on the server enjoys knowing their dINT!  Anyway, it came back as 69.  However, I think I found the root of the problem.  Mandragora are weak to Fire and Wind.  I didn't realize that.  I thought it was Ice only.

I re-ran everything using dINT 69 and including their 25% damage taken increase and got the _exact_ numbers from my actual nukes that I was expecting.  This was using the damage formula off of BGWiki.

This wasn't testing every aspect of the formula on the server, of course, being naked and all.  Lots of variables left.

Thanks a lot for your time and help so far!

**Comment by dazusu** [comment]
Just to add onto this (without technical detail)

Just been killing Alastor Antlion, and it did Blizzard IV for 2131 to a player with Shell IV on. This shouldn't ever happen. The buff to Elemental Magic should have been for players only, but seems like it was also applied to monsters.

**Comment by xdemolish** [comment]
git gud

**Comment by SwitchVII** [comment]
Good point, Dazusu.  That was my original finding as well: monsters nuking me.  In my testing, however, I was doing the nuking and that ended up being accurate.

The problem very likely is related specifically to monsters' casting.

**Comment by teschnei** [comment]
@dazusu : the changes in that pull request barely affected monsters - the formulas were actually quite close except in extreme (high dINT) circumstances.  I've fixed the root cause of monsters very high spell damage now, though.
