### ISSUE TITLE
Test Data for SMN Implementation.

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1527]
So I've seen quite a few issues submitted about issues with summoner, and a common response has been that smn's aren't fully coded yet. So I was just curious what kind of test data we need so we can start moving towards its finalization. Appreciate any input and thanks guys. More then willing to compile most the data myself if needed.

**Comment by teschnei** [comment]
astral flow damage formulas

**Comment by korietsu** [comment]
@teschnei , If I can get a SMN onto retail right now, and can provide their stats, and get some damage numbers would that be enough for us to derive the damage formula?

**Comment by teschnei** [comment]
Depends how controlled the tests are.

**Comment by korietsu** [comment]
Same mob, same zone, each avatar ~100 uses of AF ability at same job level/gear (all stats/merits noted), with notations on day? Would that be controlled enough? Or is there a particular test plan you'd be willing to share?

**Comment by teschnei** [comment]
Just the summoner's stats and the damage amount probably isn't enough, need
to know how much int the target has (easily found by reversing the nuke
formula), how much int the avatar has (reversing a bp nuke), without
influence of day/weather/weaknesses, ideally repeated over a few level
ranges with level sync

**Comment by teschnei** [comment]
Ask me in irc later today when I'm home and I can outline it better

**Comment by teschnei** [comment]
0a46c30b03e511be3695d1ea76f4756c070eab97
