### ISSUE TITLE
Zvahl Treasure Chest requiring a Coffer key

### ISSUE THREAD

**Issue by SwitchVII** [DarkstarProject/darkstar#1530]
Simple script fix, which I've implemented on my own server, but a bug none the less.  I'm new to this whole github thing and am not totally comfortable with submitting a change to the repository.  So... I'll post this instead.  >.<

Replace 1048 (Coffer Key) with 1038 (Chest Key) in the scripts\zones\Castle_Zvahl_Baileys\npcs\Treasure_Chest.lua

**Comment by TeoTwawki** [comment]
#908

**Comment by TeoTwawki** [comment]
so..its actually opening with the other key now? Someone made the wrong "fix" perhaps.

**Comment by SwitchVII** [comment]
Both coffer and chest are requiring 1048 (coffer key) to open.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/issues/909
