### ISSUE TITLE
Puppetmaster Frames

### ISSUE THREAD

**Issue by RwNigma** [DarkstarProject/darkstar#1540]
Attempting to trade Ghatsad the Items for at least the Valoredge X-900 frame and head piece yields no results. Within the "Quests" there isn't a quest being logged for it either.

**Comment by teschnei** [comment]
did you get the cutscene for the quest?

**Comment by RwNigma** [comment]
Yeah. He's asking for the items. I attempt to trade and then he doesn't do anything.

**Comment by teschnei** [comment]
does he play the quest cutscene again if you talk to him again? remember seeing any errors in the server log when you picked up the quest?

**Comment by teschnei** [comment]
also, are you trading Tigerfangs or Patas?

**Comment by RwNigma** [comment]
He doesn't give the cutscene again if I talk to him. He just continues to ask for the "Brass Sheet", "Imperial Cement", "a pair of patas." and "wamoura cocoon". No error logs that I can see, and I am trading him "Patas"

**Comment by teschnei** [comment]
Ok. He hasn't been updated since the March 2015 update so you have to give him Tigerfangs instead of Patas

**Comment by RwNigma** [comment]
Ah alright. I am off to try that. Any advice for the other 5 heads? Are those also different than specified items?

**Comment by teschnei** [comment]
Just Heavy Crossbow -> Repeating Crossbow for Sharpshot.  Alternatively, you can update your server as I just pushed a commit to fix it

**Comment by RwNigma** [comment]
I would commit it, but I am not the GM for our server. Nesstea is. He commits typically on Sunday's and Thursdays, so it should get situated today. Thank you for your help teschnei.
