### ISSUE TITLE
crash server dynamis bastol, windurst and jeuno.

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1554]
When I made the dynamis of Windurst and Jeuno, at final boss, the server crash.

[18:20:51][Debug] duration: 9000*** Error in `./dsgame': malloc(): memory corruption: 0x000000001b44fde0 ***
Abandon (core dumped)

**Comment by m241dan** [comment]
Its the "spawn second half" lua binding that causes this. As to why, I don't know, I just commented it out on my server.

**Comment by AlexandreCA** [comment]
I don't have try for the other dynamis. I dare not of scared of crash the server again

**Comment by xdemolish** [comment]
duplicate of https://github.com/DarkstarProject/darkstar/issues/1370
