### ISSUE TITLE
Expired Item Stacks from the Auction House Become Bugged

### ISSUE THREAD

**Issue by Joeyjohjjo** [DarkstarProject/darkstar#1557]
When a stack of items expires on the auction house and is sent back to its seller, it becomes bugged in some strange ways. Instead of its icon displaying the number 12, it displays no number at all. The stack cannot be moved into any kind of storage. The stack can't be sold to an NPC. Zoning and relogging do not return them to normal. You can only get rid of them by dropping them. When you drop them, you get the message "You throw away 0 'xxx'." If you use one of them, its name becomes grayed out in your inventory and then cannot even be dropped until you relog.

Single items that are returned from the auction house are not bugged - only stacks.

The top-left of the linked picture (example is Rarab Tails) displays the gray-out bug; the bottom left displays the "0" bug.
http://i62.tinypic.com/1440h0.jpg

**Comment by whasf** [comment]
Fixed in bc70f99480b7d89dfd29dc41a5f744b4407456db
