### ISSUE TITLE
Buffs wearing on zone, only while using scholar in some aspect? 

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1570]
^

**Comment by teschnei** [comment]
Er.. What does this bug report mean? What buffs?

**Comment by m241dan** [comment]
All buffs, protect, shell, refresh, haste, you name it. Sometimes not all of them, sometimes only half. Not the same ones, but usually only happening when /sch or scholar. Something to do with Light Arts/Dark Arts?

**Comment by Zenny89** [comment]
Yeah, I've seen this recently - even with signet and exp band buff wearing. Seems exclusive to SCH.

**Comment by Hozu** [comment]
It's also with SCH sub, and it can happen without using Sublimation at all.

**Comment by Zenny89** [comment]
Yes, it has nothing do with sublimation because I've seen this as a lvl 24 SCH.

**Comment by teschnei** [comment]
17ba31b22994b19ffbd8a3e5cc2bf65bdc608622
