### ISSUE TITLE
Emperor vs Empress Band

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#1571]
Close this issue if intended, but Empress and Emperor Band have the same effect of 3000 bonus XP. This is not what the bands display in-game. Should it be changed to reflect current implementation?

**Comment by TeoTwawki** [comment]
Yes, needs to match what the in game item helptext says.

**Comment by Zenny89** [comment]
This issue was resolved by Pull Requests #1576 and #1577.
