### ISSUE TITLE
Pso'Xja Goblin Veterinarian and pet not functioning properly

### ISSUE THREAD

**Issue by SwitchVII** [DarkstarProject/darkstar#1582]
The best BLM pet solo Goblin Veterenarian mob in Pso'Xja (60 cap region, I-8) isn't working.  A Diremite Assaulter spawns by him.  It acts like his pet and he acts like its master (move together, tries to summon -- but fails -- repeatedly after the Diremite is killed).  The pet should be a Goblin's Bat.

mobid: 16814174
groupid: 278
poolid: 1742

**Comment by gedads** [comment]
You're right, offset should be 1 and not 2 in mob_pets.sql for mob 16814174

**Comment by bendangelo** [comment]
This was fixed a while ago.
