### ISSUE TITLE
Level Sync randomly syncs party member in different area

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1586]
1. Level Sync
2. Kill stuffs
3. Level up, the person in different area's level was then also adjusted to the sync level.
4. He would have to zone to remove link
5. Level sync target would level up then reapply AGAIN to the person in different area.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/2600647fa4429c00c439ee551a9dee776c8b2d91
