### ISSUE TITLE
Random SOA Areas Opened even when SOA closed on Servers

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1589]
Users are getting SOA homepoint options from homepoints even if SOA is closed on a server and they cannot get to SOA.

**Comment by xdemolish** [comment]
homepoints code has been modified quite a few times, just manually remove the SOA bits from all char_vars to double check it hasn't been fixed already

**Comment by TeoTwawki** [comment]
think this got fixed, if not somebody can open a new one
