### ISSUE TITLE
Head Butt BLU spell crashes the server

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#1591]
I noticed the spell was updated recently, and now just casting the spell just kills my stock server.

**Comment by xdemolish** [comment]
need a dump

**Comment by Hozu** [comment]
Sorry, was late when I posted the issue. Here's the dump: https://dl.dropboxusercontent.com/u/57303795/Head_Butt_Crash.7z

I couldn't find the .log file so I didn't include it.

**Comment by xdemolish** [comment]
@TeoTwawki can fix
head_butt's element is 18, resistMod only has like 8 elements, so https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/magic.lua#L381 causes it to crash

**Comment by TeoTwawki** [comment]
I'm on it. Confused as to how the F it got 18, but I'm on it

**Comment by TeoTwawki** [comment]
#1595 feexed
