### ISSUE TITLE
Three Main nation fame not increasing Jeuno Fame

### ISSUE THREAD

**Issue by XephyrDragonos** [DarkstarProject/darkstar#1596]
When completing quests in Bastok, San d'Oria and Windurst, Jeuno fame does not seem to be increasing at all. With fame entries at 945, 240, and 120 respectively, Jeuno was sitting at 60 (I had completed 2 quests located in Jeuno). It seems adding fame to the three main nations is no longer increasing fame in Jeuno.

**Comment by xdemolish** [comment]
in the db, no
when checking fame using player:getFame(JEUNO_FAME), yes
