### ISSUE TITLE
Equipsets: When using /equipset <int>, even if the same weapon is kept equipped, TP is lost.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1600]

**Comment by TheMuffinPirate** [comment]
Weapon slots should be selected as "Keep same piece" otherwise it will un-equip and re-equip the same weapon

**Comment by maxtherabbit** [comment]
what's the retail behavior here? does retail lose TP if you reequip the same weapon in that slot?

**Comment by teschnei** [comment]
Would make equip sets pretty useless if they did

**Comment by xdemolish** [comment]
i'd fix but not sure whether to store the id as localVar and then remove tp, or add m_lastEquip[slot] to char entities (array cause idek if anything else cares what was equipped in that slot previously)

**Comment by teschnei** [comment]
If your equip set attempts to equip something you have equipped, it should
do nothing. Thus, you wouldn't lose tp

**Comment by maxtherabbit** [comment]
If I'm remembering the equip logic correctly, the best way to fix this is to return before hitting the unequip for *any* equipment item if the item is already equipped in that slot. IIRC dsp is unequiping anything and everything in slot X when equipitem() is called.

**Comment by teschnei** [comment]
That would probably work, yeah. Less work on the server too even outside of
this bug (ie with gearswap)

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/0c6b819ebe494d8ed549d4ada8b9e6567ab0304a
