### ISSUE TITLE
Augments not working entirely right

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1605]
If you @additem 18139 1 18 0 25 0 535 2

You will get a bomb core with the augment HP|MP +33, STR -2 DEX -2 AGI +3, Attack +1

However, it will actually add 1 str and 1 dex instead of -2 str - 2 dex.

I did a quick look at the augment stuff and couldn't see a reason why \(o.o)/

Tried on multiple characters, including the person that got that augment.

Server is Linux, if that helps.

**Comment by xdemolish** [comment]
you increased each stat by 2 (535 2) should really add up to 0, not 1 for str and dex

**Comment by m241dan** [comment]
535 2 should be str -3 dex -3 agi +3

**Comment by Celyste** [comment]
found this problem as well where i put in -11 atk but instead returned as +9 atk
