### ISSUE TITLE
Spells disappearing from learned magic list

### ISSUE THREAD

**Issue by SwitchVII** [DarkstarProject/darkstar#1606]
I have noticed that some spells are disappearing from my learned spells list.  I noticed this specifically on BRD, but have now realized it is happening on other jobs as well (Specifically DRK).  I had previously used @addallspells on my account, but noticed that a few of the Carol spells (Earth and Water specifically) were missing on my list.  At this point, if I @addallspells to my character again, I have, at the bottom of my spell list, the missing spells:

Army's Paeon V
Earth Carol
Water Carol
Raptor Mazurka
Foe Sirvente
Adventurer's Dirge

I can cast the spells, sort my list, etc. no problem.  But, as soon as I zone, these spells disappear again.

**Comment by teschnei** [comment]
I assume you do not have all expansions enabled. GM commands do not check
those

**Comment by SwitchVII** [comment]
You are correct.  We are content locked at CoP.  That being said, some of the spells listed above should still be available in the CoP expansion.  Specifically the two Carols and Paeon V.

I'm looking in the database, and I think I see the problem.

441	earth_carol		1	7	0	129	40	0	8000	24000	230	0	421	4000	5	0	1	20	80	0	204	ABYSSEA

Earth Carol does not require Abyssea.

**Comment by teschnei** [comment]
It's been fixed already, which is why I asked

**Comment by SwitchVII** [comment]
Oh, man.  I totally didn't see this was patched a couple days ago.  That's what I get for running a server version 5 days old!
