### ISSUE TITLE
Armor Storage NPC no Longer accept PLD Gallant Set

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1635]
30150508_8

Caruvinda/Taulenne:

Trade PLD Gallant set to NPC, npc doesn't take, doesn't give claim slip:

It seems the armor storage NPCs are no longer accepting Gallant. I tried with WHM AF1 and the NPC accepted with no issues.

**Comment by helixhamin** [comment]
After testing, it is still not working. I have tested the following NPCS:
http://ffxiclopedia.wikia.com/wiki/Armor_Depository
Caruvinda	Lower Jeuno (J-6)
Tesch Garanjy	Windurst Woods (H-11)
Taulenne	Northern San d'Oria (G-8)
Sinon	Bastok Markets (H-9)
Ratonne	Tavnazian Safehold (F-8) (Main level)
Hajawaa	Aht Urhgan Whitegate (H-8)
Renadile	Southern San d'Oria (S) (L-6)
