### ISSUE TITLE
ai_battle

### ISSUE THREAD

**Issue by AdamGagorik** [DarkstarProject/darkstar#1636]
I think ai_battle.cpp was added to master by accident instead of the AIRewrite branch.  The file was created a day ago, and while the cpp is in master, the header only exists in AIRewrite.
![screenshot 2015-06-29 14 43 01](https://cloud.githubusercontent.com/assets/5294486/8416720/2b39fcb8-1e6d-11e5-9559-52885ba1586a.png)

**Comment by xdemolish** [comment]
i blame @teschnei

**Comment by teschnei** [comment]
blame is not misplaced. I will only use -u for git add from now on..
