### ISSUE TITLE
King Behemoth adjustments

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#1646]
I noticed King Behemoth cast meteor for the first time today, really cool. 

There are a few things still off about the fight though and I thought I'd bullet point them here in case someone wants to take a swing at it. 

~~1) The meteor needs to do a lot more than it currently is. I clocked retail KB meteor doing 1112 damage to my naked, unbuffed, rdm on a neutral day.~~
~~2) KB should be immune to silence~~
~~3) KB should be immune to stun~~
~~4) KB should have no regen~~
~~5) Thunderbolt does about 3x too much.~~
6) KB should have single target draw in, and only use it on the person who has hate when they leave the main behemoth area (past the stone columns)
7) KB has enstun on his melee hits, I'd eyeball it at 20% proc with about a 2 sec duration.
8) Kick out is doing ~3x too much damage and needs to be made an aoe.
9) Wild horn is doing ~3x too much damage
10) In addition to his double attack (which feels like an accurate rate) he has a ~10% triple attack.

I'll eventually muddle my way through the changes myself and do a pull request, but if someone more experienced can knock it out before then that'd be great. ~Wing

**Comment by TheMuffinPirate** [comment]
This all makes sense but he does use shockwave currently

**Comment by Deadwing888** [comment]
Great, I'll remove that one.

**Comment by Zenny89** [comment]
@Deadwing888 you say that Double Attack % looks right, but when I look in the code I don't see anywhere that he has Double Attack. Are you sure?

**Comment by TeoTwawki** [comment]
I can confirm DSP's King Behemoth has no double attack at all (not in in script nor mob_spawn_mods.sql nor mob_pool_mods.sql now in mob_family_mods.sql, and there is no place else for it to have been put, so it ain't there boys).

**Comment by Deadwing888** [comment]
Idk what the code says, but when you actually go out and actually pop it he does actually double attack at about a 10% rate. Could be on account of his job being set to war?

I'm also noticing that his delay is too high, I'd estimate retail KB has a delay of about 200 (though I never frame counted to be sure).

It's great that stuff on this list is getting knocked out, but it's important that the nerfs on the list happen as well as the buffs (especially thunderbolt), or he will be too hard for 75 era servers when it turns into a kite fight. Also if his draw-in can't be configured to be single target+ only used when someone walks past the columns it should probably be turned off all together. 75s will need to be able to kite properly.

**Comment by TeoTwawki** [comment]
If his job is set to war he'd get war's traits up to his level. I forgot to check his job.

**Comment by bendangelo** [comment]
Behemoth is not immune to stun I believe, just really resistant.
