### ISSUE TITLE
Opo-Opo Crown quest

### ISSUE THREAD

**Issue by ukkoclap** [DarkstarProject/darkstar#1647]
Hi,

I noticed that the quest that rewards Opo-Opo Crown is not working and there is no other way of obtaining Opo-Opo Crown.Quests like the SMN trial quest does work. Trial of Fire which requires the same amount of reputation does seem to work. Also my fame for Kazham is capped, but the NPC won't give me the quest for Opo-Opo Crown.

**Comment by The-Halcyon-Days** [comment]
This quest line is simply not implemented yet, not broken.

**Comment by waytim** [comment]
I was able to get the quest added, should be working.
