### ISSUE TITLE
Packet Crash in Dynamis

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1650]
https://www.dropbox.com/s/b26nhfvc9gk6a6w/packet%20crash%20while%20in%20dyna.7z?dl=0

**Comment by xdemolish** [comment]
wrong pdb

**Comment by TeoTwawki** [comment]
it opened for me..

**Comment by TeoTwawki** [comment]
oh, the archive was missing their exe - the pdb is fine you just need their exe, I'll have him re-up it.

**Comment by R3P0FFXI** [comment]
https://www.dropbox.com/s/b26nhfvc9gk6a6w/packet%20crash%20while%20in%20dyna.7z?dl=0
