### ISSUE TITLE
Players unable to complete Stage 4 Relic Gun

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1651]
Date & Time: 2:11am 7/1/2015
Frequency: All the time
FFXI Client Version: 30150619_2
Area & Coordinates: x:387 Y-12 Z-18
Party or Solo: Solo
NPC Name: Gunpowder room blank space
Monster Name:
Steps To Reproduce The Issue: Traded the items remaining to finish Annihalator, then tried to trade 10k byne and won't take the currency with the gun. Tried to talk and trade the gun. Won't take either. Blank dialogue.

Ferdinand
Necropsyche
Ethereal Fragment
Metalworks: Gunpowder Room

**Comment by Hozu** [comment]
Silly question, but did that person talk to the goblin in Castle Zvahl Baileys? There's a mini "cs" where the weapon talks to you. Viewing it is a requirement before obtaining stage 5 from the blank spot, where you need to trade the stage 4 weapon, the fragment, the necropsyche, and the 10k piece all at once.

**Comment by R3P0FFXI** [comment]
Yes they did

**Comment by korietsu** [comment]
I've also seen an issue where sometimes you have to wait longer to complete the CS and the Tradein. It could be one of the variables that controls the timer is longer than it should be.

**Comment by TeoTwawki** [comment]
From IRC: 
> (9:31:20 PM) Strafeous: After I remade the stage 4 gun, it worked perfectly, I guess something shifted between patches or something
> (9:31:49 PM) Teo: remade?
> (9:32:05 PM) Strafeous: Yup, I dropped the one with problems and I just made it from scratch
> (9:32:25 PM) Teo: isn't that like, a lot of currency to respend?
> (9:32:35 PM) Strafeous: like 60 100 pieces

Anyway he simply started the whole thing over and it worked. Guessing a variable didn't set the first time from multi boxing. A random occurrence I have noticed with ppl multi boxing is that sometimes a variable will not be set or a KI will not be obtained for one of the online characters, especially if both characters are present at the same NPC/CS/BCNM/etc. And I know this guy multi boxes a lot.
