### ISSUE TITLE
To many party members

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#1662]
If you are at 5/6 and invite two people, both can join. Experience is lowered to reflect 7 people. If you are at 5/6 and invite 5 people, party of 10. Experience is lowered to reflect 7 people still.

**Comment by Ma77o** [comment]
It should be noted that this doesn't seem to work every time, and I'm not entirely sure what specifics are required to reproduce it successfully. I can definitely confirm that it happens though.

**Comment by xdemolish** [comment]
got the fix on dev branch, gonna merge it later

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/135a5c5fff3afa41b2bb6ef7a3c59f274252e86e
