### ISSUE TITLE
Stats not recalculated properly on raising and gaining a level from 74 > 75

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#1663]
Stats are not recalculated properly when you raise after you delevel from dying and relevel to 75. Level 75 gear stats are duplicated. Do it again and you have it in triplicate. Repeat to become a god.

**Comment by TeoTwawki** [comment]
![use reraise](http://ecx.images-amazon.com/images/I/51gOTRD6UEL._SY344_BO1,204,203,200_.jpg)

**Comment by Scavenge** [comment]
whoever found that first must have felt like a god

**Comment by zynjec** [comment]
No longer an issue on master.
