### ISSUE TITLE
Fomor skill animations don't display correctly

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1664]
**Alternative title: "that Fomors thing from IRC"**
https://github.com/DarkstarProject/darkstar/blob/master/documentation/player_abilities.txt#L246
> (5:25:30 PM) kjLotus: most fomors use player ws animation
> (5:26:59 PM) kjLotus: theres no bug report for "fomor"
> (5:27:05 PM) kjLotus: aka nobody will fix it
> (5:27:29 PM) kjLotus: and for the love of god if you write it, dont just put "fomors", put an example

:grinning:

**Comment by teschnei** [comment]
since you reported it, it's your job to find a specific mob that exhibits this behaviour

**Comment by TeoTwawki** [comment]
but..you already said which ones! :disappointed:

**Comment by Hozu** [comment]
It's literally all mobs in the two? Fomor families. Aka the ones in Sacrarium/Aqueducts/Lufaise/Misaraux, as well as the Hydra in Dynamis. Also the ToAU Fomor,. Possibly more out there that I'm not aware of.

**Comment by maxtherabbit** [comment]
the core function I wrote to handle weaponskills is specifically designed to handle player entities only, it will require a bit of abstraction to allow mobs to use it but it's doable

**Comment by maxtherabbit** [comment]
disregard that I see this is just an animation issue

**Comment by TeoTwawki** [comment]
@maxtherabbit Yeah I realized a min ago that the mobskill function is doing everything right for these, even getting the ID that doesn't exist in the mobskill list (huh..hows it doin that..) https://github.com/DarkstarProject/darkstar/blob/master/documentation/monster_tp_moves.txt (thats extracted from client) so they are already using the player list for the message when ID is <255 I guess?

**Comment by TeoTwawki** [comment]
@maxtherabbit ff7fa56d18f74f8800c372b851df75d912169109 does fix them, as long as correct retail fomor is using it. Now we just need to stop wrong fomor using wrong moves.
