### ISSUE TITLE
Permement Level Sync

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#1665]
If party leader syncs to player, then kicks the sync, and right after that you resync to party leader, it makes everyone synced to that level until they zone.

If a party leader syncs to a player, and the player dies and hp's, the party is perma synced until zone.

**Comment by Ma77o** [comment]
As a caster, removing level sync does not seem to restore access to your higher level spells. It does however restore your correct HP and MP for said level.

**Comment by xdemolish** [comment]
works for me

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/222737764c1c8b4a088b6921791f40a21e02c59b

**Comment by Roamin** [comment]
This bug still occuring to me at least in The boyahda tree and Crawler's nest.
No kick needed , someone the sync just vanish , and then i can constantly sync to our level anyone who joins the party afterwards.
