### ISSUE TITLE
Avatars Should Have MAB Traits

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#1669]
I've been looking through the code, and I can't find anywhere it is listed that avatars have the MAB traits. For example, according to the wiki they should MAB IV at level 75. I would be happy to update this myself if someone could point me to where I would have to make these updates.

**Comment by teschnei** [comment]
They are black mages. They have all black mage traits

**Comment by Zenny89** [comment]
OK, that makes sense. Could I then implement SMN Magical Attack merits in a similar fashion to the BLM Potency ones by modifying the mobAddBonuses function in monstertpmoves.lua?
