### ISSUE TITLE
Addbonuses Function

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#1671]
In magic.lua, the addbonuses function expects five arguments, but in the same file, when other functions call it, they only have four arguments. Is this a problem? Why or why not?

**Comment by teschnei** [comment]
The fifth argument will just be nil (which is why it's checked for nil).

You should leave general questions for IRC, and use the issue tracker for
confirmed issues

**Comment by Zenny89** [comment]
Sorry, I didn't know there was an IRC.

**Comment by teschnei** [comment]
It's in the readme, which you are supposed to read :p

**Comment by Zenny89** [comment]
I'll get on it! Thanks!
