### ISSUE TITLE
Level Sync Crashing server

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1680]
Date & Time: 2015 July 8th
Frequency: Twice in a matter of 15 minutes
FFXI Client Version: 30150619_2
Character Name: Roamin / Redroam
Race: Tarutaru / Tarutaru
Main Job: Warrior / White Mage
Sub Job: Samurai / Red Mage
Area & Coordinates: Buburimu Penninsula , anywhere in zone

Party or Solo: Party

Multi-boxing? (multiple clients on same connection): Yes, running Ashita v2 twice on same PC, same connection
Steps To Reproduce The Issue: Not 100% sure, but I would rather stop testing the issue and not crash the server a third time.

Trying to reproduce another issue involving level sync, I am pretty sure I crashed the server twice. I level sync to level 27 on my 2nd character. Then I force the character with the sync to leave the area. While I am waiting 30 seconds for the sync to wear off, I go back in the party menu , and I can now re-sync to myself at 27. So now my level 83 is synced to itself at level 27. Let the second character walk back in. Change party leaders between the two. Have the 1st character (level 83 synced to himself to 27) to use @return command, and @return again. Then zone out, and keep playing around like that and eventually the server crashed for everyone , twice.

I was doing this because somehow the red dot had vanished from an earlier party, and I was stucked on level 17 forever, and wanted to find out exactly what happened that made the red dot vanish but keep the sync, because there is another ticket opened on that subject.

**Comment by xdemolish** [comment]
> keep playing around like that and eventually the server crashed for everyone , twice.

im gonna go with: it just happened to crash while d00d was playing around with sync
especially if it didn't happen every time
