### ISSUE TITLE
New Players not receiving proper Genkai/Gil

### ISSUE THREAD

**Issue by Desufire** [DarkstarProject/darkstar#1687]
New Players are being created with Initial Level Cap 50 and the retail starting gil. Settings.lua is set for 99 Initial Cap and 1 mil gil.

players.lua only modified for AddLS function. Nothing else has been touched.

**Comment by xdemolish** [comment]
are they getting their gear on creating a new char?

**Comment by Desufire** [comment]
They're getting everything but the proper genkai and Gil. I keep the server updated weekly. I actually updated yesterday lol. 

This started occurring after the June update. 

We're able to easily correct the issue via Navicat and givegil command. Is just one of those things that pops up.

**Comment by xdemolish** [comment]
something prolly went wrong when updating then (double check your settings.lua)
assignment removed cause i didnt break, take that kayjay

**Comment by Desufire** [comment]
Settings script hasn't changed at all.

**Comment by Desufire** [comment]
https://github.com/Desufire/darkstar/blob/Caladbolg/scripts/globals/settings.lua

Link to our settings script in our repository. This was pushed yesterday.

**Comment by xdemolish** [comment]
someone was saying that set/addGil wasnt updating properly
try getting the chars to relog and see if their crap shows as intended -  if it does, it's just an issue of the packet not being sent in the lua bindings

**Comment by zynjec** [comment]
This can probably be closed, `INITIAL_LEVEL_CAP, and `START_GIL` are both working on master.
