### ISSUE TITLE
"Enhances Rice Balls" bonus remains when changing gear.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#1693]
Right now it's possible to get food effect with +150atk/+90def/+15% DA via Shogun Rice Ball, on top of the regular effects regardless of gear. The food buff persists through even job change, so you could be on a level 1 job with that bonus.

The boost should be given by the gear with the effect instead, via a mod. Perhaps use the food value as the mod param.

**Comment by teschnei** [comment]
there's already a latent for food, it should have been using that (though I
suspect they were made long before I made the latent effects)

**Comment by Hozu** [comment]
LATENT_FOOD_ACTIVE = 49, //food effect (foodId) active - PARAM: FOOD ITEMID

That's perfect.

**Comment by xdemolish** [comment]
you can close once you pull request the fix :p

**Comment by Hozu** [comment]
I'll close this issue once my pull is merged.
