### ISSUE TITLE
3322 Error on character creation with name longer than 9 characters

### ISSUE THREAD

**Issue by ElectronJunkie** [DarkstarProject/darkstar#1703]
This was done a completely new vanilla install as I blew away my entire server due to an unrelated issue. Went to remake my GameMaster account named 'Gamemaster' of all things, and it would constantly 3322 when committing to creation. Changed the name to 'Test' and it worked just fine. Made more characters up to 9 and they all work but 10+ is a no go.

**Comment by xdemolish** [comment]
iirc there were some reserved names/client blocks you from making chars with certain names

**Comment by ElectronJunkie** [comment]
You are correct... Closing due to my own derpitude.
