### ISSUE TITLE
Magus roll causes crash

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#1709]
Magus's roll (the cor blue mage mdb roll) is causing a zone crash.

It may be a specific number that it hits when Double-Up is used.

**Comment by csundman** [comment]
FYI, this is because there are only 12 values in the local array for potency results in the magusroll lua script.  A 13th value is needed to show the potency if the roll busts.  As of now, if you bust using magus roll, it will crash the server because there is no 13th value in the array.
