### ISSUE TITLE
Ranged Attack TP return inaccurate

### ISSUE THREAD

**Issue by phil835** [DarkstarProject/darkstar#1712]
Ranged attacks return incorrect values of TP.

Reference: http://ffxi.allakhazam.com/forum.html?forum=261&mid=127897977681588297

A 524 Delay bow for example should return 151 (15.1) TP on hit with 90 delay arrows (611 delay total).

Instead it returns 137 (13.7), as if combined weapon + ammo delay is somewhere between 504 to 507.

I am curious how ranged attack TP return is calculated, because current TP return seem to be an arbitrary number.

**Comment by phil835** [comment]
Another example. Shooting a delay 216 crossbow with delay 192 ammo -

Combined delay: 408. Expected TP return: 104 (10.4)

Actual TP return: 57 (5.7)

Even if ammo delay isn't properly being combined with the ranged weapon's delay, it's still isn't correct. A 216 delay weapon would be expected to return 58 (5.8) TP.

**Comment by teschnei** [comment]
"I am curious how ranged attack TP return is calculated, because current TP
return seem to be an arbitrary number."

it's open source, so you can look for yourself!

to save you the time though, most likely it uses the old formula which was
changed a few months ago and nobody has bothered to update it yet.

**Comment by phil835** [comment]
Okay, I looked around. I found in battleentity that GetRangedWeaponDelay says it combines ranged weapon and ammo delay when applicable. I checked the CalculateBaseTP formulas, they seem all right (it uses the formulas before the June 2014 update, which I'm assuming you want).

The only weird thing I found is ranged weapon and ammo delay is stored as an offset of 240. So the Crossbow Bolt in my example has -48 delay in the database. Could those negative values be messing it up?

The only other thing I can think of is GetRangedWeaponDelay does not combine ranged weapon and ammunition delay correctly.

You must forgive me, I am not a coder. I only know that the TP return for ranged weapons is incorrect.

**Comment by phil835** [comment]
Since this has been ignored I'll close the issue.

**Comment by abriasffxi** [comment]
Hey Phil-

I'm sure you're not still around, but if you get an email could you point me to where you found the offset of 240 delay?  I'm noticing that the current code has ~2seconds too much delay.

**Comment by phil835** [comment]
Hi.

[https://github.com/DarkstarProject/darkstar/blob/965a1f5f0ad2c03bcd5a071ccffca265802609ee/sql/item_weapon.sql]

Example: Silver Bullet, delay is set to 0

[https://github.com/DarkstarProject/darkstar/blob/5e87b16f079e61f0d8752f752de0327ab587e643/sql/item_weapon.sql]

Example: Silver bullet, delay is now set to 240

It was this commit that somebody made. They went through and changed every single ammo item to have +240 delay which fixed the tp return. However now ranged weapons are slower by that amount I think.

**Comment by abriasffxi** [comment]
Alright, yeah that was the issue.  It was unresolved in the current Stable,
which is what I'm running.  I see someone has updated the offset to 0 in
master so I'm not too worried about it anymore but if anyone is reading
this who is still on stable you should pull in that change asap - it's a
huge reduction in DPS an annoyance to all ranged attacks.
