### ISSUE TITLE
Alliance Server Crash Glitch Issue

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1720]
Date & Time: 4:30 7/13/2015
Frequency: Only when we try to form an alliance at the same time
FFXI Client Version: Current
Area & Coordinates: Whitegare
Party or Solo: Alliance
NPC Name: N/A
Monster Name: N/a
Multi-boxing? (multiple clients on same connection): Yes
Steps To Reproduce The Issue:
The problem is when someone forms an alliance at the same time, then both parties accept. It's as easy as that. We would accidentally alliance each other at the same time and we'd both accept accept. It would break the alliance, and we'd try to dissolve it and fix it and it would crash.

**Comment by zynjec** [comment]
Stale, closing.
