### ISSUE TITLE
Character's stuck

### ISSUE THREAD

**Issue by zacharymillar** [DarkstarProject/darkstar#1721]
I logged onto my characters "Selunia, and Kalimar" and they froze outside of valkurm instead of zoning correctly. Ever since they have been showing as logged in but in reality when I try to log in i get a 3305 error and I can't fix it. :(
It's the Old school server

**Comment by whasf** [comment]
The "issues" part of this project on Github is for problems with the server/code itself, not for problems on specific servers. You need to contact the owner of the server.
With that said, since I run oldschool, I have fixed this issue. Next time post in the oldschool section of the forums :)

**Comment by zacharymillar** [comment]
Oh ok thanks sorry
