### ISSUE TITLE
Rank 6 Sand'Oria - Halver problem

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1729]
hello

I begin the rank 6. The guard gives me the mission, and he sends me see Halver , in the castle . Halver refuses to talk to me.

**Comment by The-Halcyon-Days** [comment]
This isn't a server issue and was related to prior use of GM commands. The issue has been fixed for them.

**Comment by AlexandreCA** [comment]
Ok thanks
