### ISSUE TITLE
On failed trades, unusable until zone

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1737]
If a trade fails under any circumstances, cancel, inventory full, etc, the item(s) put into the trade window will come back un-interactable and you have to zone to fix it.

**Comment by teschnei** [comment]
can't reproduce
1. trade with another char
2. put 10 fire crystals in trade window
3. walk out of range
4. can still use fire crystal

**Comment by m241dan** [comment]
Perhaps try with non-stackables. It might be a quantity 0 issue, because its just like the old item returned from auction house issue.

**Comment by TeoTwawki** [comment]
I've only seen this happen when 2 players both try to trade each other at same time, and one cancels and the other accepts. And even then its semi random so guessing unlucky timing issue.

**Comment by Hozu** [comment]
When I trade some non-stackables to an alt account character so I can move them easily between my main and mule, I have to zone the alt account char. I would trade items from mule to alt account char, but then when I go to trade them to my main, when I select the item they don't go into the trade window. Zoning fixes it.

**Comment by teschnei** [comment]
If you know how to reproduce it, give steps (exact items etc) so I don't
have to waste time figuring out how you did it

**Comment by Hozu** [comment]
Ok, three characters, A, B, and C. A trades a Kirin's Osode to B, then logs out to change to character C. When I try to trade the Osode from B to C, I select the item and nothing happens. After B zones, I can trade normally. I don't think zone would matter, but I was in Port Jeuno.

Soul Plates also wouldn't do anything, so it's not just equips.

**Comment by Ma77o** [comment]
Teschnei,

To add to this issue (it does happen with stackables) if someone has 4 empty slots and  is being traded 4+ items, the trade will fail. When attempting to trade again after making inventory room these items are untradable to the character.  (I do not believe they become unusable, for crafting etc). I've just worked around this by tossing them into my bazaar instead and buying from there on my other char.

Perhaps it also has something to do with inventory size locking items somehow.

**Comment by teschnei** [comment]
Does this still happen after my change yesterday? One of the things I fixed
was items not being unlocked after trading

**Comment by Ma77o** [comment]
That most likely fixed the issue then. Just adding my input in case it were different. I'll let you know if anything else comes up.
