### ISSUE TITLE
Jettatura crashes server

### ISSUE THREAD

**Issue by Dalthine** [DarkstarProject/darkstar#1772]
Was just experimenting a bit last night to find out what blue magic does and doesn't work, and discovered that trying to cast Jettatura will cause the server to crash. It might need to be disabled similar to head butt and voracious trunk until it can be fixed.

**Comment by Dalthine** [comment]
Pinecone bomb, not head butt.

**Comment by Hozu** [comment]
Whoops I forgot to remove the use of the var "power" for it when I was doing copypasta, my bad.

**Comment by Hozu** [comment]
My pull request has been accepted - this issue is now resolved.
