### ISSUE TITLE
Post make: *** [dsgame-ai_general.o] Erreur 1

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1777]
Hello, with the last update. When I want compiled

server@server-AU194AA-A2L-CQ5123F ~/darkstar $ make
g++ -std=c++1y -DHAVE_CONFIG_H -I. -I./src/common -DdsUDPSERV -I/usr//include/luajit-2.0 -I/usr/include/mysql -DBIG_JOINS=1 -fno-strict-aliasing -DTAOCRYPT_DISABLE_X86ASM -g -DNDEBUG -g -O2 -MT dsgame-ai_general.o -MD -MP -MF .deps/dsgame-ai_general.Tpo -c -o dsgame-ai_general.o `test -f 'src/map/ai/ai_general.cpp' || echo './'`src/map/ai/ai_general.cpp
src/map/ai/ai_general.cpp: In member function ‘void CAIGeneral::SetCurrentSpell(uint16)’:
src/map/ai/ai_general.cpp:289:28: error: ‘make_unique’ is not a member of ‘std’
m_PSpell = std::make_unique<CBlueSpell>(*static_cast<CBlueSpell*>(spell));
^
src/map/ai/ai_general.cpp:289:55: error: expected primary-expression before ‘>’ token
m_PSpell = std::make_unique<CBlueSpell>(*static_cast<CBlueSpell*>(spell));
^
src/map/ai/ai_general.cpp:293:28: error: ‘make_unique’ is not a member of ‘std’
m_PSpell = std::make_unique<CSpell>(*spell);
^
src/map/ai/ai_general.cpp:293:51: error: expected primary-expression before ‘>’ token
m_PSpell = std::make_unique<CSpell>(*spell);
^
make: *** [dsgame-ai_general.o] Erreur 1

**Comment by maxtherabbit** [comment]
GCC 4.9 is meant to support make_unique, I don't get it

**Comment by maxtherabbit** [comment]
maybe try “-std=c++14” instead of "-std=c++1y" ?

**Comment by teschnei** [comment]
you are not using gcc 4.9. Please see https://forums.dspt.info/viewtopic.php?f=4&t=2716 for how to install and use gcc 4.9.
