### ISSUE TITLE
Xstring crash on Zone

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1780]
https://www.dropbox.com/s/0gz8fths7a9lk9x/xstring%20crash%20on%20zone.7z?dl=0

**Comment by TeoTwawki** [comment]
This is the same crash demo was attempting to fix with null zone craps, which demo is done with and I was told by R3P0FFXI that @maxtherabbit was now looking into. He has a newer dump on the latest source from last night I told him to link here.

**Comment by TeoTwawki** [comment]
@maxtherabbit which he says he PM'd to you instead...

**Comment by R3P0FFXI** [comment]
https://www.dropbox.com/s/gzef6n0rb9mz052/backwards%20zone%20info%20-%20destination%20is%20current%20zone.7z?dl=0

**Comment by TeoTwawki** [comment]
@R3P0FFXI so you see my comment on the other one, then added it here after this was already closed so now you have 2 dumps and 2 issue reports both closed for an issue nobody will ever look at - brilliant decision there R3 :frowning:
