### ISSUE TITLE
Merit categories have swapped my merits around.

### ISSUE THREAD

**Issue by Roamin** [DarkstarProject/darkstar#1784]
After the july 23rd 2015 update, all my merits are screwed up.  Spells I haven't merited are now capped, skills i dont use are merited.  Shellra 5 is no longer available and has Devotion merited instead.  Seems a global issue.

**Comment by teschnei** [comment]
july? there hasn't been a july client update yet afaik

**Comment by R3P0FFXI** [comment]
Date & Time: 23/07/2015, 07:30am (gmt)
Frequency: Constant
FFXI Client Version: 30150619_2
Area & Coordinates: irrelevant
Party or Solo: Party or solo
NPC Name: Irrelevant
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: Unknown how this occurred, checked merits as soon as i logged on to the game and all my merits have been changed, like my enhancing had been merited but i merited enfeebling, also seems like all job merits have been changed as well. Also it seems its not just myself but all other players on the server.

**Comment by teschnei** [comment]
#1788
