### ISSUE TITLE
Random Backwards Zone Crash destination is current zone

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1786]
https://www.dropbox.com/s/gzef6n0rb9mz052/backwards%20zone%20info%20-%20destination%20is%20current%20zone.7z?dl=0

**Comment by TeoTwawki** [comment]
*sputter*
WHY?
I said to just put it in #1780, its the same crash but with newest source.

**Comment by TeoTwawki** [comment]
and its not really random - its pretty consistent when that guy crosses onto diff servers.
