### ISSUE TITLE
Merits are not resistant to schema changes

### ISSUE THREAD

**Issue by teschnei** [DarkstarProject/darkstar#1788]
Merits are stored as a blob in the database.  If the schema changes (ie. a new merit is added or removed that is not at the end), then every merit after that insertion/deletion will point to the wrong merit.  Suggested fix: new table (char_merit) containing charid, meritid, upgrades (key: charid+meritid)

See #1784

**Comment by Hozu** [comment]
With the new update combat skill and magic skill merits are boosting the one listed below it. ie. meriting Dagger adds to Sword skill, both in the Combat skills window and stats via /checkparam. I am unsure of the Other category, as meriting enmity+/- has always added Geomancy/Handbell skill to the Magic skills page, while the rest added an entry of ' there, though I've verified that crit merits worked long ago. Also I don't know how to check for those boosts.

Anything in Group 1 and Group 2 works fine (berserk had recast lowered, aggressive aim gave ranged acc bonus to aggressor).

**Comment by maxtherabbit** [comment]
7adb31f

conversion util to follow on forums tomorrow
