### ISSUE TITLE
nimrods null zone issues

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1796]
https://www.dropbox.com/s/gzef6n0rb9mz052/backwards%20zone%20info%20-%20destination%20is%20current%20zone.7z?dl=0

Its *seems* to be triggered by players who have upwards of 3 characters logged in with at least 2 of them in the same zone and and a another trying to enter that zone, from a different map server. The crashdump shows the "destination" as current zone rather than the zone it should have been, and the current zone as null.

 **2 characters in Abyssea Attohwa, 1 in Buburami, the one in Buburami tries to use the maw and Abyssea crashes, crashdump says this players "destination" was Buburami so the Abyssea map server crashes.**

I could be wrong but that is what it looks like to me based on the crashes always being on someone multiboxing 3+ characters and the destination in the dump not matching where they were actually headed in game.

This is the same crash from #1786 and #1780 and #1699 and #1654 and...You get the Idea. Some of the duplicates aren't entirely his fault : the dump would get so stale before anyone looked at it that the source no longer matched or he'd not understand this was the same one, and he'd open a new issue. Also each time it was thought to be fixed I'd tell him "well show them you have new dumps on latest source for the same issue". And up would go another one...

His lack of explaining things I already explained to him, has caused me to open this so it can actually be handled. Note this was built from source that has commits from the dev branch in it: demolish made multiple attempts to fix this in the dev branch. If you pull master into dev and look at this dump from there the source should match.

**Comment by teschnei** [comment]
dev was already merged to master a few days ago

**Comment by TeoTwawki** [comment]
Oh, didn't even see it. Well should match up with master then.

**Comment by teschnei** [comment]
no, was wrong, should have known you'd see it before i deleted it

**Comment by TeoTwawki** [comment]
my ninja xmpp notifier skills see all

**Comment by xdemolish** [comment]
> demolish made multiple attempts to fix this in the dev branch
pshaw my attempts were flawless, server just happened to crash in every way apart from the ones i expected it to

**Comment by xdemolish** [comment]
1 char in bastok
3 chars in dunes
had the 3 in dunes swap with 1 in bastok, no crash

tried like a couple of times and no crash so assuming completely unrelated to multiboxing

**Comment by TeoTwawki** [comment]
Its not an every time type of deal. How many attempts did you make?

Each and every instance of this happening I have looked at so far, the scenario I described fit perfectly. Given the frequency they triggered this on their server and the drastic reduction in its occurrence since I mad people stop doing that (a few don't listen or can't read English) it hard to believe its coincidental. But if you can't reproduce at all after many tries, I dunno what else it can be.

**Comment by xdemolish** [comment]
tried like 6 times and wasn't able to crash (yes, they were zoning between zones on different map servers)

**Comment by xdemolish** [comment]
closing cause newer issue with (possible) solution, though the steps to reproduce here will be helpful for sure
