### ISSUE TITLE
Spirits don't have MP.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#1802]
I was scripting Elemental Siphon, and once I got everything just about done I noticed that it's supposed to take MP from the spirit. So I added a check for that and it always returned 0, and when I did <petmpp it said 0. I couldn't figure out how to give it mp, or the best (ie. proper) way to go about such a change.

**Comment by teschnei** [comment]
they should get MP based on their job in the mob tables

**Comment by Hozu** [comment]
In mob_pools.sql? When I do ctrl+f for "spirit", I don't find them. Heck even searching for "pet_" only shows avatars and jug pets.

Also, the avatars are set to BLM main job, but they also say they have no mp when I do <petmpp> (says 0%).

**Comment by teschnei** [comment]
ah, they have MP - they just spawn with 0 MP
a1d7448
