### ISSUE TITLE
"Draw in" puts people under the map

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#1810]
I've noticed on retail when I get drawn in I spawn a yalm or so higher than the terrain and fall on it. 

I think the draw in function needs to somehow add 1 or 2 to the z axis and let people fall the rest of the way to insure they don't wind up under the map. Thoughts?

**Comment by teschnei** [comment]
up/down is the y-axis, but yeah, that sounds reasonable

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/issues/1162
