### ISSUE TITLE
sessions not being cleared when server exe's close

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#1819]
It was my understanding that sessions should get wiped if the server goes down. If I am wrong, just let me know when you close this out.

I was assisting someone again today when I noticed they had multiple stuck characters perma online except they weren't. All in party, all not in game but had a session and unable to log in because the database said they were already online. This persisted through multiple restarts of both the the lobby and map servers and even a physical reboot of the machine. 

I emptied out accounts_sessions and all was well (despite these people being in a party on search, accounts_parties has no entries for me to nuke).

**Comment by teschnei** [comment]
sessions get cleared when the exe is started (not closed)

**Comment by TeoTwawki** [comment]
huh. Still should have cleared then, just not at the moment I thought.

Whats the method on that, does each map server handle it or the lobby server handle it? Is each map server separately responsible for handling sessions for characters that are in a zone on that map server?

**Comment by teschnei** [comment]
IIRC, each map server nukes the sessions for its IP

**Comment by TeoTwawki** [comment]
I think I replicated what happened by changing zone settings. If you eliminate a map server and change those zones port setting to point to another map server, characters who had logged out from the server that no longer exists will have sessions that the server that now handles that zone will not clean out. I guess its like "*those ain't my sessions ima ignore those*" when it sees them.

**Comment by teschnei** [comment]
if you're eliminating map servers while people have sessions in it, yes,
they won't be cleared - that's on you to clear it manually

**Comment by TeoTwawki** [comment]
So not a bug, just a "gotcha" then? Kind of opposite of what most people would think "everybody is offline and nothing is open, I should be good to change things now" etc etc

**Comment by teschnei** [comment]
correct - not really any way to enforce removing sessions on server close

**Comment by TeoTwawki** [comment]
ok, thanks for you time man.
