### ISSUE TITLE
Part III - When Angels Fall - Chains of Promathia

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1825]
I think meeting a bug when 8-3 Chains of Promathia mission . With you retrieve the two key, Brand of Twilight and Brand of Dawn . The elevator acknowledges that I have the two key and put me . It's just the right rear Particle Gate remains closed although it should launch a CS to take us a battlefield .

**Comment by Kthulupwns** [comment]
it will remain closed on the third floor, you just simply talk to it for cs, then again after for bcnm. I'll look into it myself it's probably just a shifted ID most likely

**Comment by Kthulupwns** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/The_Garden_of_RuHmet/npcs/_0z0.lua

The lua itself is intact for said door, I'll submit the pull request later fixing the issue

**Comment by AlexandreCA** [comment]
The probleme was fixed or not? I have not checking that for the moment.

**Comment by Zenny89** [comment]
I'm unable to recreate this issue.

**Comment by AlexandreCA** [comment]
Well, hope that someone found the problem quickly .

**Comment by AlexandreCA** [comment]
I've fixed. It's good.
