### ISSUE TITLE
Claria Star - Bastok is not scripting.

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1828]
Just for saying, Clarion Star is not scripting..

http://ffxiclopedia.wikia.com/wiki/Clarion_Star

**Comment by TeoTwawki** [comment]
Nothing that NPC actually does is going to exist for a long time. I doubt Trust Magic will even be considered before Fellowship NPC is done.

**Comment by AlexandreCA** [comment]
I see many more new addition in the NPC missing the server , making the server partial received situation . If people want to do , I'll start working on it and maybe , hopefully my learning to hunt in non scripted NPC .
