### ISSUE TITLE
Missing NM: Ghillie Dhu

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#1832]
LS mate was looking for the NM. I'm not seeing any reference to it in the repo.

http://ffxiclopedia.wikia.com/wiki/Ghillie_Dhu

**Comment by TeoTwawki** [comment]
I'll add him in a couple days.

**Comment by TeoTwawki** [comment]
@xipies sorry I took longer on another project than I thought. I'm working on it today.

**Comment by TeoTwawki** [comment]
#1929 there ya go.

**Comment by TeoTwawki** [comment]
@xipies just so you know there is a ton of others missing, and I have a lot of those close to done just haven't finished up because I keep getting my time eaten by other stuff. It's been on my back burner all year.

**Comment by TeoTwawki** [comment]
#1930 had to redo it because github wouldn't let me reopen the previous one after I was done fixing a bug
