### ISSUE TITLE
Hasso/Seigan Not doubling recast timers.

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1833]
Kind of keep forgetting to post this but the issue is that SAM/NIN is just completely broken at the moment in terms of survability, not to mention that Third Eye and Utsusemi Stack, with utsusemi taking priority no less. Assuming this is just an oversight but it's a relevant issue that effects game balance.

**Comment by Kthulupwns** [comment]
Utsusemi and third eye should not stack btw, they are mutually exclusive buffs.

**Comment by metalfiiish** [comment]
Issue is with the script at:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/abilities/third_eye.lua

Bad code:
function onUseAbility(player,target,ability)
    player:addStatusEffect(EFFECT_THIRD_EYE,0,0,30); --power keeps track of procs
end;

Correct code:
function onUseAbility(player,target,ability)
if (player:hasStatusEffect(EFFECT_COPY_IMAGE) or player:hasStatusEffect(EFFECT_BLINK)) then
	return MSGBASIC_EFFECT_ALREADY_ACTIVE, 0;
else
    player:addStatusEffect(EFFECT_THIRD_EYE,0,0,30); --power keeps track of procs
end;
