### ISSUE TITLE
Mob Pathing when entering hitbox becomes erratic.

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1835]
Whenever you pull a mob or a mob aggros, as its pathing into your hitbox, it starts kind of going apeshit and seems to try and want to move behind you before "settling". I realize that if this was an easy fix it'd have been done by now but Just figured i'd throw it up regardless

**Comment by xdemolish** [comment]
prolly wont be fixed til navmeshing is done
that, or we dont have it recalculate its path every tick
