### ISSUE TITLE
9-2 Mission Sandoria - CS problem

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1876]
Yes, it's fixed for the final battle. But, after that, after FFXIEncyclopedia we need zoning at the entrance of Northern San d'Oria for a short cutscene . No cutscene begins. Here is a copy of the site to complete the mission .

Afterwards
Zone into Northern San d'Oria for short cutscene.
Return to Chateau d'Oraguille and click on the Great Hall for a cutscene.
Go to the heavy stone door in King Ranperre's Tomb at H-8 of the first map for a cutscene.
Optional: You can view two cutscenes by checking Pieuje's door and Trion's door in Chateau d'Oraguille.
Optional: If you check the Papal Chambers door at the top floor of the Cathedral, you can view another cutscene. This can also be done after completing the mission.
Report back to Halver for a final cutscene and your reward.
Optional: There are now two additional cutscenes at Pieuje's door and Trion's door. These do not show up in the Past Event Watcher list, but can be seen by Rank 10 San d'Orians.
Optional: There is an epilogue cutscene that can be viewed upon entering Southern San d'Oria.

**Comment by AlexandreCA** [comment]
anybody?

**Comment by xdemolish** [comment]
someone will get round to fixing it when they feel like it

**Comment by AlexandreCA** [comment]
ok
