### ISSUE TITLE
Errant letter 'g' at end of server message

### ISSUE THREAD

**Issue by ElectronJunkie** [DarkstarProject/darkstar#1886]
Not sure this rates and issue request but....
I have noticed that the letter 'g' is getting added to the end of my three line server message. Double checked the server_message.cnf so I am assuming it is getting added when called/printed.

If this is just me feel free to close.

**Comment by teschnei** [comment]
Not including your server message is not very helpful

**Comment by ElectronJunkie** [comment]
Message is comprised of the below three lines
--- Server Upgraded and Backed Up Every Monday.
--- Client Update REQUIRED Ver. 03 July 2015.
--- Update use /rom/rom0/0.dat delete/update method.

But will appear as
--- Server Upgraded and Backed Up Every Monday.
--- Client Update REQUIRED Ver. 03 July 2015.
--- Update use /rom/rom0/0.dat delete/update methodg

It happens no matter the message and with more testing and updating the message it appears to be actually deleting the last character and replacing it with a 'g'. So "Hello" becomes "Hellg"
Again not a huge issue, just something I noticed over the last few days.

**Comment by Cloudef** [comment]
Maybe upload the file somewhere, as it may contain hidden characters.

**Comment by ElectronJunkie** [comment]
I am starting to lean in that direction as well. If I copy the original file from DSP it works fine. If I edit it in either notepad or notepad++ it replaces the last character with a 'g'.

**Comment by ElectronJunkie** [comment]
5 minutes later I have figured it out.
You need to press return after the last line to insert the hidden characters for both "carriage return" and "line feed". It am guessing that the code that calls the server message looks for these as the end of line.
