### ISSUE TITLE
SMN Maths Stuff

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#1888]
Has anyone seen this?
http://kegsay.livejournal.com/5510.html

**Comment by teschnei** [comment]
yes, he even used to be a contributor a few years ago

**Comment by m241dan** [comment]
Ah, I was under the impression that all the SMN stuff was out of whack but I assume then that t his stuff is in line?

**Comment by teschnei** [comment]
closing this since it's not an actual issue
