### ISSUE TITLE
Someone Broke TOAU Mission 1

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1894]
Date & Time: august 4th 2015
FFXI Client Version: 30150619_2
Area & Coordinates: Aht Urghan Whitegate
Party or Solo: Party
NPC Name: Naja Salaheem
Monster Name: not applicable

Steps To Reproduce The Issue:
Talked with Naja Salaheem to start mission 1. Got cutscene approaching her door, telling me i have received a "Supplies Package" Checked my KI and nothing, and the NPC will not tell me anything. I tried talking to the NPC Mayeevaat I think the name is , at Ilrusi Atoll Staging Point , didnt say anything. Used the runic portal to return to whitegate.

I had tried last night to use the Ilrusi Atoll Staging Point to return home forgetting that i didnt have access yet, and it told me It can't let me pass.

**Comment by waytim** [comment]
Not sure if related or coincidence but I had someone stuck on this earlier today, they had not completed the Road to Aht Urgan quest. They had never went back to Faursel after being warped into Wajaom Woodlands. After completing the quest they were able to get the KI from the cs.

**Comment by TeoTwawki** [comment]
@waytim even if that were all that is wrong, that quest isn't even part of the mission and shouldn't be included - the mission is pre-flagged on retail on new characters because the "mission" literally begins in whitegate regardless of how you got there (if you manage to cheat your way there on retail, that cs would still fire off). 

All the appropriate places in script to prevent you from boating over there ahead of time etc. should already work correctly leaving zero reason for anyone to check that in mission. So if that's the case, someone still messed up.

**Comment by TeoTwawki** [comment]
Just a brief glance at the involves scripts and it becomes clear that someone took a previously working mission and made changes that they did not test. There is code in the wrong functions, unnecessary additional player variables, variables attempting to be cleared in onRegionLeave, and breaks with normal DSP convention by using new vars for every. single. mission. **even when that mission is literately only a single unavoidable cs that you can't escape without getting it completed.**

**Comment by TeoTwawki** [comment]
I caved in to temptation and ranted. Sue me.

**Comment by waytim** [comment]
This mission is a super pain in the butt at the moment because if you aren't standing in the right spot on CS trigger, it will keep looping the CS over and over. These changes must be the reason why it's suddenly been acting up the past month or so.

**Comment by TeoTwawki** [comment]
@waytim Yep.

The loop is from this:
https://github.com/DarkstarProject/darkstar/commit/6667e96bcb05d56bb83b535d0818002fea2bd050?w=1#diff-67bf81747e709ce6975326397b10f24bR81
And this:
https://github.com/DarkstarProject/darkstar/commit/6667e96bcb05d56bb83b535d0818002fea2bd050?w=1#diff-67bf81747e709ce6975326397b10f24bR107

The latter doesn't consistently happen. Usually never. So you usually get stuck with a var of one for eternity. It should just play the dang cs and nothing else, and the rest should happen in onEventFinish for that cs - no var needed.

**Comment by R3P0FFXI** [comment]
Still getting reports on this as of latest DSP pull

**Comment by waytim** [comment]
I tried cleaning up the file to remove the needless vars being added and removed on region enter and leave, but its STILL random about 50% of the time. So i'm totally stumped as to why this is random, nothing should be random. Here's my revised Zone.lua for Aht Urghan mission 1 if you want to try it yourself:
http://pastebin.com/04dVPSHm
