### ISSUE TITLE
weaponskill calculates both main and offhand weapon damage

### ISSUE THREAD

**Issue by abc3210** [DarkstarProject/darkstar#1907]
weaponskill calculates both main and offhand weapon damage causing higher damage than normal

**Comment by Hozu** [comment]
Isn't it supposed to use the offhand weapon damage to add one extra hit to a WS? ie. if you use Rampage with an offhand weapon, it counts as 6 hits, with the extra hit being from the offhand weapon.

Or is it using it for more than just that?

**Comment by abc3210** [comment]
it is using both weapons to calculate every hit

**Comment by teschnei** [comment]
That's pretty specific - can you point out why you think this is the case?

**Comment by abc3210** [comment]
upon examination it appears just to be augmented weapons with plus damage.  if you have both weapons augmented, all of the augmented plus damage is being applied to the weaponskills

**Comment by teschnei** [comment]
do you know which modifier or augment ID are being used in this case? I suspect it's just using the wrong modifier (as there's already a modifier to make sure it's only applied to the correct weapon)

**Comment by IxAalexI** [comment]
The augment ID currently set up in augments.sql is main hand damage only (August id 45 iirc,) no matter where you stick it. I.E. A neck with +DMG augment will have the same effect you are seeing now. There is a sub hand DMG modifier available, but it hasn't been stuck into the augments list yet because who's to say you're always going to subhand a single handed wep. Or mainhand for that matter.

**Comment by teschnei** [comment]
there's logic in the core to swap main hand damage to offhand damage for
regular mods and for latents if the weapon with the mod is equipped in the
offhand, but I doubt it works for augments.  Additionally, those mods would
never appear on anything but weapons, except in "custom content" scenarios,
which are out of scope anyways

**Comment by IxAalexI** [comment]
It doesn't work for augments, I tested it a while back, just trying to clear up the why for the OP.
