### ISSUE TITLE
crash server after the last update - Linux

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1909]
Hi, after the last update, the server crash in the dsgame terminal. This is the area of ​​change that the server crash.

[10/Aug] [20:55:00][Debug] CZone:: West_Ronfaure DecreaseZoneCounter <0> Elvano
*** Error in `./dsgame': free(): invalid pointer: 0x081bb5f4 ***
Abandon

One idea?

Thanks

**Comment by Cloudef** [comment]
Can you run valgrind on the server and cause the crash again. Valgrind helps track down memory problems.

**Comment by AlexandreCA** [comment]
I do not see what I can say. The error is always the same .

**Comment by Cloudef** [comment]
Install valgrind with your package manager, make sure darkstar is compiled with debug symbols. And run `valgrind --track-origins=yes --log-file=dsgame-valgrind.log ./dsgame` and post the dsgame-valgrind.log once it crashes.

Debugger (gdb) may not give useful stack trace for this as it looks like memory corruption issue.

**Comment by AlexandreCA** [comment]
it's good for now. Thanks
