### ISSUE TITLE
Merits showing "off by one"

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#1911]
I am still seeing issues with at least "Attributes", "Combat Skills", "Other", and "Monk" categories. All on one character. All the merits I have are shifted "up" by one slot, even going across categories, such as with H2H (Combat Skills) showing as +CHR (Attributes).

(I'm assuming 55cd5d3 is in effect on the server.)

Revision: a91653f
Client: 30150730_1
Server: Classic

**Comment by teschnei** [comment]
#1905
