### ISSUE TITLE
Incorrect Handling of BCNMs Outside of Door's Zone

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#1912]
Example is the door located in Pashhow Marshlands [S] connects to BCNM located in Ruhotz Silvermines. Particular BCNM I was looking at was Light in the Darkness.

**Comment by teschnei** [comment]
Ruhotz silvermines is not a bcnm zone. Thus it does not use the bcnm code

**Comment by Zenny89** [comment]
What code should it be using? There's a time limit to complete objectives after selecting the particular fight at the door.

**Comment by teschnei** [comment]
It's an instance, same as the assault zones.

**Comment by Zenny89** [comment]
Is there a working assault I can use as an example?

**Comment by teschnei** [comment]
Probably best not to bother yet until assault is finalized. If you really
want to, I think leujaoam cleansing is complete

**Comment by Hozu** [comment]
Try the CoP 8-3 pots fight.

**Comment by Zenny89** [comment]
Thank you.
