### ISSUE TITLE
Enmity update on invalid target

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#1917]
https://www.dropbox.com/s/mjv9nmag039k7d5/Crash.7z?dl=0

**Comment by bendangelo** [comment]
Need the commit the server was built on, or include the log.

**Comment by TeoTwawki** [comment]
Doubt he has either anymore after all this time, and it'll be to stale to look at with current source.

**Comment by TeoTwawki** [comment]
@R3P0FFXI if possible, once Legion catches up to current DSP revision, save a newer dump and save log from when it happens again.
