### ISSUE TITLE
Account splitting

### ISSUE THREAD

**Issue by Airiqa** [DarkstarProject/darkstar#1942]
Open an issue report And let me know which characters are being moved from which account to which other account:
Move: Character: Airiqa 
From: Account: Abinadi
To: Account: Airiqa

Thank You,

**Comment by TeoTwawki** [comment]
@Airiqa wrong issue tracker. This is the tracker for the DarkStar Project itself, not the server you play on.

**Comment by helixhamin** [comment]
@Airiqa 
I think you want to post here: https://github.com/LegionDark/Issues/issues
