### ISSUE TITLE
Kindred Demons in Ulegurand Range Are True Sight

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#1947]
The higher level kindred demons should not be true sight and aggro only by regular sight.

**Comment by bendangelo** [comment]
I just went through all the demons in the database and non of them are true sight. Closing.

**Comment by Hozu** [comment]
The high level demons use the same family as the ones in dynamis - they have their extra tp moves, use 2hrs, true aggro, etc.

**Comment by bendangelo** [comment]
Ok what are the names?

**Comment by Hozu** [comment]
All of the ones that are Kindred (insert job) like Kindred Dark Knight.
