### ISSUE TITLE
EX items are still tradable if the UI says it's not EX.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#1953]
That is to say, the EX flag that's set in the database doesn't do anything when it comes to trading. I'm sure someone could trade EX items by either modifying one of their .dats to remove the EX flag, or by packet injection.

**Comment by xdemolish** [comment]
are they supposed to fail the trade or just not update the slot

**Comment by teschnei** [comment]
Not update slot

**Comment by xdemolish** [comment]
including npcs trades?

**Comment by teschnei** [comment]
You can trade ex to NPCs

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/df50408e0bfc32b3955970d1e548f9b31720d902
