### ISSUE TITLE
Zilart Mission 8: Return to Delkfutt's Tower Cutscenes - not playing

### ISSUE THREAD

**Issue by Joeyjohjjo** [DarkstarProject/darkstar#1972]
Multiple cutscenes for ZM8 are not playing. The cutscene upon entering Lower Delkfutt's Tower does not play - the player enters the zone ordinarily.

The cutscene after defeating Kam'lanaut does not play, and leaves players stuck on a black screen. The spell Warp can be used to exit the black screen. The player does, however, receive credit for completing the mission and is able to continue the line of missions.

The optional cutscene at the beginning of ZM8 in Lower Jeuno was not tested.

From Nasomi server

**Comment by AlexandreCA** [comment]
It happens the same thing at home. After the fight against Kam'lanaut in Return to Delkfutt 's Tower - ZM8 , it ends with a black screen . But still , the mission can be continue, but I had to leave the game wildly.

However , still in Zillart , I note that the mission The Sealed Shrine - ZM15 , we must go back to Ru'Aun Gardens and subsequently Shrine of Ru'Avitau for a cutscene . Nothing is happening. No CS will start , so we can not finish the mission .

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/c2849e1ebbf7f40f89db6cb4a2ee4995e6590e7a
