### ISSUE TITLE
Wings of the godess -- mission problem

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1975]
an error appears when you want to click on the tree trunk (???) . Nothing happens and an error in the console appears .

[23/Aug] [13:51:36][Error] luautils::onMobRoam: scripts/zones/La_Vaule_[S]/mobs/Lobison.lua:22: attempt to perform arithmetic on global 'transformTime' (a nil value)

I want my information this link.
http://ffxiclopedia.wikia.com/wiki/Claws_of_the_Griffon

Also, I just noticed that successful missions are not being recorded in the missions menu. A forgotten in the script?

**Comment by Zenny89** [comment]
@xdemolish there appears to be a problem with qm's (they appear to be commented out). I noticed this one suffers from this problem. 

This is a quest, so it should be recorded in the completed quest log, not the mission log.

**Comment by AlexandreCA** [comment]
It's fixed now. Thanks
