### ISSUE TITLE
Wrath of the Griffon - Wings of the godess

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1985]
When I have to talk to Rholant - Southern San d'Oria (S) (E-7) . A CS must execute . And nothing is happening 

http://ffxiclopedia.wikia.com/wiki/Wrath_of_the_Griffon

**Comment by Zenny89** [comment]
That quest isn't implemented in DSP yet.

**Comment by AlexandreCA** [comment]
Ah! It's for that, thanks
