### ISSUE TITLE
1 exp when party member is weakened and exp ring in effect.

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#1987]
I was doing GoV in Boyahda Tree at level 68 and one of my chars got KO'd. All chars had chariot band effect. For any mob KO'd with the char weakened at any point in the fight, I only got 1 exp. Once weakness cleared and I fought a new mob, I got regular exp again.

Revision: 4a8e9d15ce
Server: Classic

**Comment by xipies** [comment]
Nevermind, I think these may have been mobs that had linked to NM.

**Comment by xipies** [comment]
May still be an issue. The mobs (same mobid) that I defeated and got 1 exp are still giving 1 exp after respawning and being defeated again.

**Comment by zynjec** [comment]
Not able to repro on master, if anyone still has this issue, feel free to open another issue.
