### ISSUE TITLE
Raptors in Ifrits Cauldron blood aggro

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#1998]
Raptors in Ifrits Cauldron (and possibly elsewhere) blood aggro.

![image](https://cloud.githubusercontent.com/assets/12477635/9535786/3e0c5912-4cf3-11e5-9920-88a97d06f8ae.png)

**Comment by Hozu** [comment]
Surprisingly, this page says they're blood aggro: http://ffxiclopedia.wikia.com/wiki/Eotyrannus

I have my doubts on that actually being the case, but yeah.

**Comment by Deadwing888** [comment]
This calls for an immediate trip to retail Ifrits Cauldron.

**Comment by Deadwing888** [comment]
CONFIRMED Raptors in Ifrit's Cauldron do not blood aggro. Wiki is incorrect.
