### ISSUE TITLE
Adjustments to Roc and Simurgh

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2003]
On retail Roc and Simurgh will hit 95% of the time ~~regardless of player evasion/level/whatever.~~ until you get over 500 evasion.

They should also hit about 2x as hard as they currently do.

**Comment by TeoTwawki** [comment]
> On retail Roc and Simurgh will hit 95% of the time regardless of player evasion/level/whatever.

uh uh, no way, I camped those enough to know better. Esp Simmy, till I finally pried MY boots off his cold dead feet! /spits

They have high acc, but its not always perma capped you can get enough eva to get their hitrate down. I've seen DRG evade Roc at a rate well above 5% while soloing it in 75 cap (poor fella died to it at 10%).

**Comment by Deadwing888** [comment]
Well I just remember tping in haste gear as thf because the eva set made no difference. My 99 rdm friend also said simurgh wasn't missing him so, take that for what you want.

**Comment by Deadwing888** [comment]
Took my 99 thf out to Simurgh, and my initial comment is incorrect. While simurgh's acc is high, it is possible to evade his hits:

Evasion doesn't start helping until you get more than 500.
Once you go over 700 evasion his hit rate is floored.

That seems to suggest he has around 600 acc?
