### ISSUE TITLE
Sky Adjustments

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2004]
I understand there's a lot to do, so I'm going to restrict this list to the major stuff. I have a google doc going filled with minutiae, but for now:

Seiryu: On darkstar Seiryu double attacks every attack round like a monk. On retail he has single attack rounds at (I think) 240 delay. He also should have a roughly 25.0% tp per tick regain causing him to weapon-skill constantly.

Byakko: He has about 15% double attack and 65% triple attack on retail. ~~His delay should also be 200, not 240.~~ Frame counted it and he is in fact a 240, sorry, it just feels faster because so many multi attacks.

Suzaku: Really quite close, but he does need a 15% double attack added.

Genbu: Also pretty close, although he should have a "ninja-counter" that doesn't appear in the log. Regular counter would be fine for this too I suppose, I'd estimate a 15% proc rate. Also he needs more defense, if you're interested in my guestimate I'd say 200 more.

Kirin: Not bad. Needs more regain (~50.0 tp a tick), more defense (maybe 200 more?), and crank mod_bindres mod_stunres mod_silenceres to full.

The portal to go up to the god platforms should disable when the gods are popped, and the portal down should wipe hate on the god.

All gods are immune to sleep.

All gods should wait 3 minutes before depopping.

God's additional effect should be a consistent ~60 damage, currently I'm seeing damage all the way from 1 to "131070" (which registered as 0 damage)

Not relevant until depopping is fixed: but all gods have 23' true sound.

**Comment by TeoTwawki** [comment]
> God's additional effect should be a consistent ~60 damage, currently I'm seeing damage all the way from 1 to "131070" (which registered as 0 damage)

Ah yet another time some dude adding something swore up and down he tested it, and later we find he was obviously flat out lying. Joy.

**Comment by TeoTwawki** [comment]
@Deadwing888 I need some player stats for what you got ~60 ish dmg for them at? lv job gear etc. Then I will try and fix the add affect dmg. I just want to set my test char up identically if possible.

**Comment by Deadwing888** [comment]
Want me to just hop over to your server and setup a Deadwing? I can do side-by-side comparison with my identical retail character.

**Comment by TeoTwawki** [comment]
My test box isn't set up for external access.

**Comment by Deadwing888** [comment]
Suzaku enfire= 73 dmg vs level 75 rdm with ~30 dmg phalanx shell4 and -15% mdb gear
Seiryu enaero = 130 vs level 75 rdm with no mdb/mdt, no shell, no phalanx
Byakko enlight= 30 dmg vs level 75 rdm with shell 4 (phalanx can fully cancel it)
Genbu enwater= 105 dmg vs level 75 rdm with shell 4, and no phalanx

**Comment by TeoTwawki** [comment]
@Deadwing888 I assume no ele resistance gear involved? And the fact light resistance isn't as easy to come by is prolly why they made ol Yakko's not as strong.

**Comment by Deadwing888** [comment]
Not enough ele resistance to matter yeah. 

That's another thing, DSP seems to have elemental resistance affecting MDB/MDT directly to some extent whereas in my experience in retail it only affected Meva (aside from some whm pants or merits or something). I should probably do some concrete testing and open up a separate issue about it, but I think it's common knowledge something is wacky with MDT/MDB/ele res.

And goodness yes, if Byakko had 100 damage enlight I shutter to think what those triple attacks would be like. Even as he is, I can't think of any mob in classic XI that could kill you quicker 1v1.

**Comment by TeoTwawki** [comment]
> Not enough ele resistance to matter yeah. 

I'd like to know if you had any at all and how much just to be safe. And I recall hearing that the elemental resist stat was doing wrong stuff on mobs, but not players, but I wouldn't know much about that.

I'm just gotta get the math doing what we know is correct thing before any gear stats/buffing is applied, and then any scaling problems after that at least we'll know its not the mob script's fault. Back to bed for now, wish I could stop waking back up nearly every hour :tired_face:

**Comment by Deadwing888** [comment]
It's hard to pinpoint off the video, if I had any at all it was less than 20. It wasn't giving me half resists in any event, and on retail it doesn't cut damage any other way than resists.

My understanding of the system has always been that players get a hidden "C" skill in magic evasion as they level, and then resist gear gets added on top of that for your resist check against the mob's magic accuracy.

At Tiamat for instance, because he is such a high level mob, barfire alone does absolutely nothing. A fire resist set alone does absolutely nothing. They're just "catching you up" to the magic accuracy of a level 95 mob. Put them together though and you start getting lots of 1/4 1/8 and 1/16th resists because you're now OVER his magic accuracy. I think the groundwork for meva on darkstar is pretty correct, because a fire resist set at dsp Tiamat feels like it should. But barfire is also affecting mdb/mdt in some fashion and I don't think that's correct.

I wonder, are there any mobs we've pinpointed that we have their magic attacks down precisely? Could then do some side by side tests with that mob on retail to see the mdb/mdt/resistance differences.

**Comment by TeoTwawki** [comment]
alright, gonna assume max dmg I see with what you gave me is the full unresisted for that lv and amount of mdef

**Comment by TeoTwawki** [comment]
> But barfire is also affecting mdb/mdt in some fashion and I don't think that's correct.

Hmm. that should be the case only with whm merit I think? maybe someone messed that up though.
