### ISSUE TITLE
CoP Dawn BCNM

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#2005]
The Promathia NPC is invisible in all of the cut scenes surrounding this BCNM, which causes client crash occasionally. Additionally, Prishe and Selh'teus do nothing the entire fight.

**Comment by gedads** [comment]
There was a small update introducing new high level bcnms, empyreal paradox sealion's den are concerned, need either starlightknight to run his script or to correct manually.

**Comment by teschnei** [comment]
The Prishe script is old and uses targID instead of long ID, so I don't
think the script would have automatically updated it.  I can fix the script
to use the long id, but I don't know what Promathia's ID should be now
(assuming it did shift)

**Comment by starlightknight** [comment]
Script will only update long ids. I didn't realize there was a small update that actually changed ids. I can rerun the batch in the next day or two

**Comment by teschnei** [comment]
I updated the Prishe/Promathia scripts to use long ids now

**Comment by zynjec** [comment]
This specific issue was fixed, if another issue has come up, feel free to open another issue.
