### ISSUE TITLE
Sleep effect from Shockwave WS wears immediately

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2009]
Tried on Old Opo-opo in Ifrit's Cauldron, both by 74 DRK and 74 PLD.

Revision: a3f2052
Server: Classic

**Comment by teschnei** [comment]
extension: the damage from the WS will remove its own sleep effect (same for any damaging skill that applies sleep)

**Comment by TeoTwawki** [comment]
Also all blue magic same problem as all WS, last I heard (or should that be its own issue? If so I'll delete comment and repost to one).

**Comment by teschnei** [comment]
yep, that's what I was getting at by "damaging skill"

**Comment by TeoTwawki** [comment]
Oh, I somehow I read that as "any damaging weapon skill" when that wasn't exactly what you said.
