### ISSUE TITLE
[NM] Silk Caterpillar does not spawn

### ISSUE THREAD

**Issue by rreina** [DarkstarProject/darkstar#2011]
Hello! This NM is supposed to spawn in Rolanberry Fields K-7 when the airship flies over the zone. I couldn't see the airship and the NM didn't appear in two Vana'diel days.

The link with this NM information is here: http://ffxiclopedia.wikia.com/wiki/Silk_Caterpillar

**Comment by Deadwing888** [comment]
It actually does spawn and immediately despawns. You've gotta be realllly good at claiming to get it, but it can be done (if you want to get your neckerchief before the bugfix)

**Comment by rreina** [comment]
Ops. I tried it with a mob running for a while around the whole K-7 and healing myself to generate aggro but I couldn't get it. Thank you

**Comment by Deadwing888** [comment]
This guy may well and truly not spawn anymore. Been out here for over an hour and nothing.

**Comment by berghaushouse** [comment]
Fixed in 6277c73

**Comment by wrenffxi** [comment]
This can close.  Current master has spawn mechanics for Silk Caterpillar in Rolanberry zone.lua
