### ISSUE TITLE
[Quest] Say It with Flowers - It is not given

### ISSUE THREAD

**Issue by rreina** [DarkstarProject/darkstar#2012]
Moari-Kaaori keeps crying instead of giving me the quest. I meet fame requirements and tried to zone and get it in different days without success.

This is the url to the quest in FFXIClopedia: http://ffxiclopedia.wikia.com/wiki/Say_It_with_Flowers

I hope this information is good for you to squash bugs hidden in the code. Thank you.

**Comment by Deadwing888** [comment]
The fame requirement NPC is broken and will often report you as being a higher fame level than you actually are. I can't confirm if the quest works or not, but if you're listening to the NPC just keep building fame and he may give it to you.

**Comment by rreina** [comment]
I know I have at least fame 3. I did Power Gi quest that requires that level of fame. This quest only asks for fame 2 according to the documentation.

**Comment by Sacshop** [comment]
Looking through this npcs lua - it is simply not scripted at all nor is it anywhere else

**Comment by metalfiiish** [comment]
You can check if a quest has been implemented in this routinely updated file:
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/quests.lua

Legend:
-- + --  Means implemented, NOT tested (by a third party, meaning only the DEV tested).
-- ± -- Means implemented and tested to be working.

If neither of those are listed it means not implemented.

Examples:
SAY_IT_WITH_FLOWERS             = 50;
HOIST_THE_JELLY_ROGER           = 51; -- + --
SOMETHING_FISHY                 = 52; -- + --
THE_THREE_MAGI                  = 66; -- ± --
RECOLLECTIONS                   = 67; -- ± --

Hope this helps in identifying if implemented. Yes, there is always the ability to check the npc's lua file as it should have some code written, this is good to check as some people don't properly update quests.lua (rare, but i know, who would REALLY do that!? :p)
