### ISSUE TITLE
`SetMobAbilityEnabled(false)` not working?

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2017]
This function is apparently busted, being told that mob scripts using it to disable their skills are still using those skills anyways.

https://github.com/DarkstarProject/darkstar/blob/e41c17615cdbcba03023f5961b875fd93e84e1fe/scripts/zones/PsoXja/mobs/Golden-Tongued_Culberry.lua#L13

Its also used with Shadowlord (his 2nd half only spams a scripted Implosion) and is being used in a recent pull request..

**Comment by TeoTwawki** [comment]
Make that 2 pull requests, because I told @waytim he could use this function for his, then he finds it not working.

**Comment by Hozu** [comment]
Make that 3 pull requests, using it for Bahamut v1 so it doesn't use any moves during the 2 second wait before starting to prepare Megaflare.

**Comment by TeoTwawki** [comment]
@Hozu that was the 1st one I was referring. :smile:

**Comment by teschnei** [comment]
can you verify that it is not working with shadow lord or some other mob
that used to work?

**Comment by TeoTwawki** [comment]
@teschnei the one I linked did vertical slash this morning.

**Comment by TeoTwawki** [comment]
@teschnei looking in core it looks like that bool is only checked in the part that does things like gigas ranged attack, not general mob skills. But I'm not very familiar with those AI parts so never sure what the intentions of what are often poorly named things were..

**Comment by teschnei** [comment]
ah, i'll let you test it here in a minute

**Comment by waytim** [comment]
@teschnei your fix is working fine for my mob https://github.com/DarkstarProject/darkstar/pull/2016.  The issue seems resolved.

**Comment by TeoTwawki** [comment]
Resolved by 88edd3724125772add28879b20df8f768b2c7a68
