### ISSUE TITLE
Debug messages

### ISSUE THREAD

**Issue by teschnei** [DarkstarProject/darkstar#2026]
While looking at a dump for old school, I realised that better/more debug messages would have really helped.

I'd really like to see some more debug messages with useful information.  Examples: trade initiated (with who), trade item added (which item id), trade complete, party created (with party id/leader name), party invitation sent, party invitation accepted/party member added, same for alliance, include the targid in the 0x01A handler.
These (especially the party ones) would really help in figuring out the cross server party issues that I still haven't fixed

**Comment by whasf** [comment]
051b475548a6e2e8b6f4f277a2b8303716d42462
