### ISSUE TITLE
Phorusrhacos/Picolaton

### ISSUE THREAD

**Issue by RwNigma** [DarkstarProject/darkstar#2027]
Picolaton isn't coded, but I can't even seem to find Phorusrhacos within Western Altepa Desert within script. They show up within the zone though. Trying to get used to it all. Could anyone direct me to the mob ID for Phorusrhacos?

**Comment by Sacshop** [comment]
https://forums.dspt.info/viewtopic.php?f=5&t=2208

**Comment by TeoTwawki** [comment]
And if its not in the mob_spawn_points sql table you can use this to find it: https://github.com/Windower/POLUtils

**Comment by RwNigma** [comment]
Thank you. Sorry for the long wait on a reply.
