### ISSUE TITLE
Trading and then zoning sometimes causes the server to crash

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2032]
After trading and then zoning, the server sometimes crashes. I think I have triggered it three times so far. Another player has triggered it once. AFAIK, the only instances of this are trading with multibox accounts. This first happened 2ish weeks ago, IIRC.

The last trade I made that did this was (Port Windurst) Ember -> Ash, 12x Honey, 12x Slime Oil, 12x Beehive Chip, 12x Bomb Ash. All full stacks. Only one-way trade. Zoning was Port Windurst -> Windurst Woods. The zoning was successful as I appeared in Windurst Woods upon logging back in after server restart.

Revision: f22e1de (currently, not necessarily when first crash occurred)
Server: Classic

**Comment by bendangelo** [comment]
Can't reproduce this. Would be better to supply a dump to get better context of the issue.

**Comment by teschnei** [comment]
whasf has a lot of them, but they are all heap corruption so they're not
really that useful to begin with

**Comment by teschnei** [comment]
df5c3ca
