### ISSUE TITLE
COP 5-3 Tenzen's Path KI Bug

### ISSUE THREAD

**Issue by towbes** [DarkstarProject/darkstar#2034]
Currently if a player forgets to check the ??? in Battalia Downs twice in order to get the KI Delkfutt Recognition Device, then they go and kill the Disaster Idol, their mission var gets set to 7 and they are unable to go back to obtain the KI in order to progress the mission.  According to the wiki http://ffxiclopedia.wikia.com/wiki/The_Pursuit_of_Paradise_(Tenzen%27s_Path) a player should be able to obtain the KI even after they kill the idol.

In the script darkstar/scripts/zones/Batallia_Downs/npcs/qm4.lua , the if statement should be

 player:getVar("COP_Tenzen_s_Path") == 6 or 7    

in order to allow the player to get the KI even after defeating the idol.

Another solution might be to not update the mission var if the player didn't have the KI yet, though I think the first example is more aligned with what the wiki says.

For example adding the KI check in
scripts/zones/Lower_Delkfutts_Tower/mobs/Disaster_Idol.lua

if (killer:getCurrentMission(COP) == THREE_PATHS and killer:getVar("COP_Tenzen_s_Path") == 6 and player:hasKeyItem(DELKFUTT_RECOGNITION_DEVICE) == true))  then 
      killer:setVar("COP_Tenzen_s_Path",7);

**Comment by Hozu** [comment]
They shouldn't even be able to spawn the Disaster Idol NM without the KI, and if someone else spawns it, it probably should not advance the mission progress. I'll have to double check that last one though.

**Comment by Hozu** [comment]
Oh right, this issue is now resolved.
