### ISSUE TITLE
Cerberus Adjustments

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2038]
Saw some tweaks to Cerberus being made, so I thought I'd share the information I've collected.

1) ~~Delay needs to be changed from 380 to 200~~
2) ~~Cerberus is a warrior not a dark knight (don't know how relevant this is)~~
3) ~~Cerberus has a double attack rate of ~20%~~
4) ~~Moving the combat damage multiplier from 125 to 175 got his hits feeling appropriately hard~~
5) ~~The magma hoplon spikes only deal about 25 damage, not ~60~~
6) ~~Undulation paralyze is fairly weak, maybe 20% chance to paralyze~~
7) ~~He needs an additional ~120 magic evasion~~
8) ~~Cerberus has a 1tp/tick regain until he gets under 25% health when it goes to 7.0% per tick~~
9) ~~Cerberus is immune to sleep and gravity~~
10) The spell stun needs to be more accurate to allow for stunning of gates of hades
11) ~~Gates should only go off under 25%~~ (looks like it's been fixed,)
12) He has a 1hp per tick regen~~
13) His movement speed is 80. He's currently moving fast but does so in a glitchy fashion.
14) He aggros true sound at 8' and true sight at 20'
15) ~~He has approximately 650 total defense~~
16) Cerberus has single target draw in
17) Cerberus will not wander out of his little area, and will draw people in who walk past a certain line (if they are his target)
18) ~~He should respawn on 1 hour windows from TOD. The code below is one way to do that, there may be a better way.~~

mob:setRespawnTime((math.random((0),(24))*3600)+172800); -- 48-72 hours with proper 1 hour windows

19) He should spawn 12-36 hours after the server comes up, also on one hour windows
20) ~~He should have more mnd, changing his mind setting from 6 to 1 felt about right~~
21) ~~Edit: local dmgmod on gates_of_hades.lua needs a boost from 1 to 1.5, but I'd recommend waiting on that till stun magic accuracy is fixed or the era servers are going to have a real problem on their hands.~~
22)  This is the stupidest of minor details, but if you want to go perfectly true to retail: when idle Cerberus will howl at the sky every 5 minutes.

23) I recently noticed Gates of Hades going off too quickly. Needs to be slowed down by at least 750 milliseconds. 12/9/15

I hope this is useful. Some of this I've written functional code for, though I've probably not done things as well as a dev could, still if you're stumped on something I share what I've tried.

**Comment by Hozu** [comment]
Out of curiosity, how much of this applies to Sarameya?

**Comment by Deadwing888** [comment]
Sarameya is widely similar to cerb but there are some differences; I'll try to list the stuff that's not on wiki. 

1) He attacks quicker, (think Ultima quick) circa 150-180 delay. 
2) He does not hit as hard, his hits are probably 2/3rds cerberus strength. 
3) Sarameya has a 50 hp/tick enpoison. 
4) The gates of hades does not hit as hard (maybe 75% that of cerb) I also am of the belief that it is not as accurate (though that's hard to pinpoint)
5) Lastly he goes through this whole thing where he howls, chainspells, spams gates etc. I assume that's all documented elsewhere. I have some footage of it happening someone want's to see how all that goes.

Khim and Hydra funciton with the same respawn times and spawn conditions. Now this isn't a proven fact but many years of retail hnming tell me that they're most likely to spawn in the first 3 windows or the last 3. Don't think it's worth coding, have no data to back it, but pretty sure it's true.

Rdm/drk stun is my primary concern, and if he were to get the meva boost I think other classes would struggle as well. Cerb is quite evasive to magic (for a 75) but is still quite susceptible to stun; it makes me think they can completely unhinge stun resistance from magic evasion/thunder resistance and set it at a particular value when they need to.

**Comment by nesstea** [comment]
You should get on IRC more. :(
I have a commit incoming for Sarameya.

**Comment by nesstea** [comment]
https://github.com/DarkstarProject/darkstar/pull/2246

**Comment by m241dan** [comment]
hey Deadwing888, recently got everything on the list except: 14, 16, 17, 22.

Any chance you got a Khimaira special in you?

**Comment by Deadwing888** [comment]
Coming right up

**Comment by m241dan** [comment]
Because of your awesome information provided!
