### ISSUE TITLE
Dynamis: Killing BST master makes pet bug out

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#2042]
Killing the Beastmaster master in Dynamis Bastok, I witnessed the pet's model disappeared but the name stayed and acted like a normal monster until itself was killed.

The pet shouldn't despawn whatsoever when it's master is killed.

**Comment by vickycat** [comment]
That invisible pet bug last night may have been due to being slept while despawning, after the master was killed. All of the other pets despawned normally (even if they shouldn't have)

**Comment by bendangelo** [comment]
Beastmaster pets shouldn't despawn when the master is killed. I can take a look at it.

**Comment by bendangelo** [comment]
@vickycat I just thought about that and it is possible to be slept while despawning. I will make a patch for that.
