### ISSUE TITLE
Dancer job abilities Flourishes III don't work.

### ISSUE THREAD

**Issue by Dimmabr** [DarkstarProject/darkstar#2045]
Date & Time: Sept 7, 2015
 Frequency: everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Nation: San'doria
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: All Area
 Party or Solo: Party and Solo
 NPC or Monster Name:
 ffxiah.com link (for inventory items only): 
 Multi-boxing? (multiple clients on same connection): 
 Steps To Reproduce The Issue: Job Ability "Flourishes III" don't work "Climactic, Striking and Ternary Flourich" folowing Presto, pls guys fix it because Flourishes III work to dancer so how sneak attack work to thfs.

**Comment by xdemolish** [comment]
post 75 content, feature request not a bug
