### ISSUE TITLE
DNC AF3 Maculele hands and legs(Status don't work)

### ISSUE THREAD

**Issue by Dimmabr** [DarkstarProject/darkstar#2046]
Date & Time: Sept 7, 2015
 Frequency: everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Nation: San'doria
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: All Area
 Party or Solo: Party and Solo
 NPC or Monster Name:
 ffxiah.com link (for inventory items only): 
 Multi-boxing? (multiple clients on same connection): Yes, but it don't when solo too
 Steps To Reproduce The Issue: Dancer AF3 maculele bangles and tights status don't work at all...dagger skill, haste, critical parry, everything dont work...

**Comment by xdemolish** [comment]
don't open issues for unimplemented post wotg content
