### ISSUE TITLE
Delivery box (receive) does not show Slot 1 result upon opening

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2053]
You have to move to another slot, then back to slot 1 to see the result in the chat log.

Revision: f6e4a76
Server: Classic

**Comment by Enignite** [comment]
Isn't this how it was in retail?

**Comment by TeoTwawki** [comment]
If we're only talking log messages, thats retail (annoyingly).

**Comment by teschnei** [comment]
The log message thing is entirely client side anyways IIRC. So we can't do
anything about it
