### ISSUE TITLE
Client Crashes due to Chat

### ISSUE THREAD

**Issue by Alexsis987** [DarkstarProject/darkstar#2055]
I submitted this issue a few days ago and teschnei closed my issue saying it was fixed but now I can cause the crash with a character name of 7 characters instead of the 14+ that was required before (haven't tested how short of a name will crash it).
His commit: https://github.com/DarkstarProject/darkstar/commit/7911a8527fa4fcb8218d660118fdca03d7dc1466

Previous issue message:
The max searchable character name is 14 characters; however, the game will allow you to create names up to 16 characters.

This issue occurs when a character whose name is 14 characters or greater in length. When this person attempts to send a max length chat message (can't just spam a single character as those messages get shortened). This message causes most of the recipients to crash (seems like about 75% of characters if you send it via party/ls and 100% via tells).

Not positive but I believe this is caused by the chat overflowing due to sendable messages being the max string length minus 14 characters for the name. This doesn't account for the fact that the recipient's message has a > added to it nor does it account for those non-searachable character names which go up 16 characters in length. If this is the case chat messages could be shortened by 4 characters to remove the overflow.

Edit: Sorry for making a new issue but I couldn't figure out how to reopen the old one if that's even possible?

**Comment by xdemolish** [comment]
there's a button to reopen

**Comment by teschnei** [comment]
I'm already looking into it. It's really stupid: I can replicate the exact
same packet but crash on dsp but be fine on retail. Might just add some
extra  buffer and call it a day

**Comment by teschnei** [comment]
Set buffer size to maximum.  Don't care atm that it's not retail, there seems to be some strange conditions for the maximum size of the message that I can't figure out.  It changes on zoning, but didn't change back when zoning back.  for now, I think this will work.  Reopen if there are still crashes
