### ISSUE TITLE
No fire weather (or the accompanying fire elementals)

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2058]
I have not seen any in what seems like a couple months or more now.

Revision: f6e4a76
Server: Classic

**Comment by Zenny89** [comment]
I think the problem is that the "Rare" flag for zones is too rare compared to retail. Fire weather does happen, just MUCH less frequently than I remember retail being.

**Comment by xipies** [comment]
Someone on server did see fire today (for smn quest), so it is happening, just super rare.

**Comment by Hozu** [comment]
This issue still exists but it should be renamed to something like "Rare weather happens too rarely".

**Comment by bendangelo** [comment]
Ok someone just has to make it less rare.

Plus, wtf guys upload an avatar!

**Comment by nesstea** [comment]
@bendangelo  lol

**Comment by nekolepsy** [comment]
I noticed this issue as well and did some digging into it. Zones that currently have data for fire weather are several times less likely to be common(50%), normal(35%), or rare(15%) than other weather types with the exception of light. Over 2160 game days you currently are about 14-20x less likely to find a fire weather zone than earth, wind, water, ice, or thunder and about 7x less than dark. To make things worse, many zones that should have fire weather don't have any data in the database for it. These include:

Crawler's Nest
Crawler's Nest [S]
Halvung
Meriphataud Mountains [S]
Mount Zhaylom
Rolanberry Fields
Rolanberry Fields [S]
The Shrine of Ru'Avitau - Atlas says no, ffxiclopedia says yes
Ve'Lugannon Palace - Atlas says yes, ffxiclopedia says no
Valkurm Dunes

Also some zones that have fire weather seem to be broken like Meriphataud Mountains and Castle Oztroja where there is just 1 day out of 2160 where there is a chance for fire weather.

I'd like to help fix this one, but I don't know where the zone_weather data comes from in the first place.
