### ISSUE TITLE
Dancer Curing Waltz V wrong animation... 

### ISSUE THREAD

**Issue by Dimmabr** [DarkstarProject/darkstar#2059]
Date & Time: Sept 11, 2015
 Frequency: everytime
 FFXI Client Version: 30150730_2
 Character Name: Dimma
 Race: Hume
 Nation: San'doria
 Main Job: DNC
 Sub Job: NIN
 Area & Coordinates: All Area
 Party or Solo: Party and Solo
 NPC or Monster Name:
 ffxiah.com link (for inventory items only): 
 Multi-boxing? (multiple clients on same connection): Yes,but it don't when solo too
 Steps To Reproduce The Issue: Curing Waltz in lergion Worth like flee of the thief and it need to be like curing waltz IV from dnc.

**Comment by xdemolish** [comment]
it's not even implemented in dsp https://github.com/DarkstarProject/darkstar/blob/master/sql/abilities.sql#L220

in future, report issues to your private server first, and then dsp (unless the issue is within the scope of what we're currently working on)
