### ISSUE TITLE
Mobs use *only* 2hr with MOBMOD_2HOUR_MULTI set.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2063]
The problem lies in this function: https://github.com/DarkstarProject/darkstar/blob/1cb73213612af86788851ade285689ac69b32fcc/src/map/ai/ai_mob_dummy.cpp#L730

The way mob 2hrs are done is if the 2hr main mobmod is set, the mob has enough TP, and the move is eligible to be used (see the onMobSkillCheck function in each script), the mob will use it, If not, then a regular mobskill would be used. Upon use, the 2hr mobmod gets set to 0, unless 2hr multi is set. Because of this, the mob will always use the 2hr if they meet the HP requirement if they have the 2hr multi mobmod set, and never any other skill.

I don't know the best way to handle this so I'm making it an issue.

**Comment by bendangelo** [comment]
I see what you're saying. The mobmod `2hour_multi` will cause mobs to only 2 hour. I think the 2 hour logic should be decoupled from mobskill into its own method. Also what mob's 2 hour multiple times? Maybe we can just script those mobs manually and remove this mod.

**Comment by teschnei** [comment]
I don't think there are many. Off the top of my head, I can only think of
neo ark angels, which are all timed or have special conditions

**Comment by Hozu** [comment]
The wiki has Gurfurlur and Jailer of Hope with the ability to 2hr multiple times, and I'm sure there are more. I noticed it when fighting Jailer of Hope.

**Comment by TeoTwawki** [comment]
This started happening only recently, because the 2hr trigger ceased being semi random and was set by another rmobmod. before that this worked as intended (but was never really needed).

**Comment by TeoTwawki** [comment]
..I know I have said this before but..
I really think all 2hr should just be scripted. Aside from dyna pretty much everything that does it gets gets a script anyway and wouldn't be that much script work to do them that way. The core bits doing 2hrs feels like ancient "still here for compatibility with old crap" code. >.>

**Comment by bendangelo** [comment]
We still need this 2 hour code for dynamis. I think this mob mod should be removed and have a new `useTwoHourAbility` method implemented for scripts to use.

**Comment by TeoTwawki** [comment]
No, we don't need a redundant function. We already have one that works just fine for making it go...

And dyna could easily have its mobs go without being done in core if we wanted to change that. Its not even that many scripts to add.

**Comment by TeoTwawki** [comment]
Hell dyna mobs don't even work as the in core comments describe as it is.

**Comment by Hozu** [comment]
There's a mobmod for 2hrs being called by the scripts, if it's set the script check will prevent its use, thus making it usable only if the script tells it to be used.

**Comment by TeoTwawki** [comment]
You can also just add to the mobs skill list while flagging it as a hr, and it will not use it unless forced by script.

**Comment by TeoTwawki** [comment]
```lua
function onMobFight(mob,target)
    local Did2hr = mob:getlocalVar("Used2hr");
    local MightyMisses = 432;
    if (Did2jr ==0  and mob:getHPP() < 60) then
        mob:useMobAbility(MightyMisses);
        mob:setLocalVar("Used2hr",1);
    end
end;
```
~~And hey look at that it didn't take any mobmod to set what HP to go off or to prevent it from using the 2hr in its skill list.~~ That field for flags needs to be in the other table now that the mob skill list stuff got refactored I can't per-mob flag skills anymore.

**Comment by TeoTwawki** [comment]
Which has me wondering how many scripted 2hrs are broken right now.

**Comment by bendangelo** [comment]
```
mob:setLocalVar("Used2hr",1);
```

Is it a good idea using this? I thought this got persisted through respawns, so this will never get reset on mob death.

`useMobAbility` should still work fine because the same skills still exist. Create a new skill list if you need a mob with different skills.

**Comment by TeoTwawki** [comment]
Nope, localVar gets destroyed when mob depops (including form being killed).

What I was saying about the skill flags: I think the flags should be on the mobs specific version of that skill rather than the global set of IDs we build its list from.

**Comment by TeoTwawki** [comment]
That or we can go modify scripts to blah:setFlag() it I suppose..

**Comment by teschnei** [comment]
The thing about scripted mobskills is that they don't need to be in the
mobs skill list at all.  When you do useMobAbility, it looks up the skill
from the global array and uses that.  So if you want it to only go off by
scripts, you just don't put it in the list.

**Comment by TeoTwawki** [comment]
@teschnei was that caused by the recent refactor? because very mob I have scripted 2hrs for up till now, has required a skill list entry or it would not work.

**Comment by bendangelo** [comment]
@TeoTwawki Yeah it was changed.

>What I was saying about the skill flags: I think the flags should be on the mobs specific version of that skill rather than the global set of IDs we build its list from.

Yeah I agree, that is a good idea. I think a new flags column or multiple param columns should be added to the mob_skill_lists table.

**Comment by teschnei** [comment]
No, I think it's better if they are scripted in some way.  What would be
the use case for it (other than what Teo was talking about, since that's
just excluding it from the list)?

**Comment by TeoTwawki** [comment]
@bendangelo @teschnei there sis probably a lot of stuff we can now do away with, thanks to this refactor making things make more sense. I can already see some mobmods no longer needed and that flag can probably be removed from the enumeration. I do still think that if we're having a flags field, it makes more sense logically in the other table, but I can't really think of a use case anymore if I can force skills by script without the mob even having them (which makes me rather happy in itself).

**Comment by ZirkSupernova** [comment]
Just pointing out a possible edge case, the testimony Hydra mobs in Dyna-Glacier can not only use their 2 hours multiple times, but they also have access to several different 2 hours (usually 3).
