### ISSUE TITLE
Benediction does not remove negative status effects

### ISSUE THREAD

**Issue by Altreer** [DarkstarProject/darkstar#2065]
Right what it says on the tin. According to in-game text and http://ffxiclopedia.wikia.com/wiki/Benediction most status ailments should be removed on use, but the current script only allows for healing and waking up slept characters.

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/abilities/benediction.lua#L22

Well that's there, but it doesn't seem to be doing anything? Or at least, it's only removing statuses that have the erasable flag set (like slow).

**Comment by Altreer** [comment]
It didn't seem to be removing things such as silence when it was used, strangely enough.
