### ISSUE TITLE
Zillart - ZM14 - Divine Might - Server crash (Linux)

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#2068]
I note that the mission The Sealed Shrine - ZM15 , we must go back to Ru'Aun Gardens and subsequently Shrine of Ru'Avitau for a cutscene . Nothing is happening. No CS will start , so we can not finish the mission .

http://ffxiclopedia.wikia.com/wiki/The_Sealed_Shrine

**Comment by Sacshop** [comment]
It is completely passable following the wiki. Also there is a check somewhere regarding your earrings as well following divine might.

**Comment by AlexandreCA** [comment]
Ok, for Divine Might. When I fight the forth boss, the server crashes. This is especially when I finish defeating Ark Angel's Wyvern that the server crashes . The console of the server said error segmentation. Nothing all.

**Comment by Sacshop** [comment]
Your saying when doing Divine Might - the server crash's every time you kill the wyvern?

**Comment by AlexandreCA** [comment]
yes

**Comment by Sacshop** [comment]
I literally just did this the other day and experienced the same issue with aldo but that is a rather easy fix. Now I was able to get the CS at the shrine with no issues and had several members do the same. In fact the only issue I saw at all was when people had more than the proper DM earring's and were not able to get past the check at gilgamesh (I think the check is at gilgamesh).

**Comment by AlexandreCA** [comment]
I'm afraid of not following you. I direct homepoint to Shrine of Ru'Avitau and I have no CS . I even tried to get out of Shrine of Ru'Avitau , return to Ru'Aun Gardens. Come back to Shrine of Ru'Avitau, and not CS again :(

**Comment by Sacshop** [comment]
The code is as follows for the onzonein cs

-- ZM 15 -> ZM 16
   if (ZilartMission == THE_SEALED_SHRINE and player:getVar("ZilartStatus") == 1 and
      xPos >= -45 and yPos >= -4 and zPos >= -240 and
      xPos <= -33 and yPos <= 0 and zPos <= -226 and DMEarrings <= NUMBER_OF_DM_EARRINGS) then -- Entered through main gate
         cs = 51;

Need to enter from the main entrance and here again we have a check for the proper number of DM earrings

**Comment by AlexandreCA** [comment]
Its perfect! Thanks!
