### ISSUE TITLE
Avatar Perpetuation Reduction Mods

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#2082]
MOD_PERPETUATION_REDUCTION = 346, // stores the MP/tick reduction from gear
MOD_AVATAR_PERPETUATION = 371, // stores base cost of current avatar

In item_mods.sql, Adhara Gages and Augur's Brais are using 371 as the modifier, while every other piece of reduction gear is using 346 despite having the same "Avatar Perpetuation Cost -X" attribute. Which is correct?

**Comment by teschnei** [comment]
Using 371 is not correct. Only avatars themselves set and use that
modifier. It either doesn't work or continuously drains mp when you equip it

**Comment by Zenny89** [comment]
Got it, I'll change them to use the 346 mod.
