### ISSUE TITLE
Trait Teirs

### ISSUE THREAD

**Issue by RwNigma** [DarkstarProject/darkstar#2085]
Referencing  darkstar/src/map/trait.h ,

There are no current teir's above teir one when it comes to traits. BLM only has "Magic Attack Bonus" at level 75, but should have II, III, and IV. Same with WHM having only "Magic Defense Bonus" at level 75, but should have II, III, and IV.

Not trying to be job specific just bringing up the issue since it would help mages. Plus mitigate the large amounts of damage that players take from spells.

**Comment by teschnei** [comment]
Are you saying the jobs are not receiving the higher tiers of traits or just that the enumeration doesn't have the tiers? If the former, have you tested this? If the latter, does it make sense to check 5 tiers of dual wield for whether a job can equip a weapon in their offhand?

**Comment by RwNigma** [comment]
I am saying that jobs are not recieving the higher teir traits. 

When you are a BLM level 75 you don't get the 2nd, 3rd, or 4th teir which all stack in retail. The same goes for Dual Wield 2, 3, 4 You should be getting these when you check your job traits.

**Comment by teschnei** [comment]
I believe they are not separate traits in your in game trait list, if
that's what you're saying (except treasure hunter).  The list in trait.h is
built out of the values from the client.

**Comment by teschnei** [comment]
I'll verify either way whether the tiers are applying or not when I get home, though

**Comment by RwNigma** [comment]
With testing this. BLM only does roughly 30 more damage than a RDM with teir 3 spells when they have the same INT. Its only a 0.8 increase. This just feels very miniscule to me.

**Comment by teschnei** [comment]
@exec print(GetPlayerByName('<yourname>'):getMod(28)) will print your MAB to the console

**Comment by RwNigma** [comment]
Ill have to give it a go on the test server, but cannot currently. Waiting for a maintenance.
When I was checking personally with spell casts and such it seems like its all implemented. Just feels like BLM should just do more than it does compared to a RDM.

**Comment by RwNigma** [comment]
There was a few random oddities with Moldy Earring though. Sometimes the damage from it was right/correct and other times when you had it equipped you would deal less damage than before. (Damage was not resisted)

**Comment by RwNigma** [comment]
Upon further testing a 75 BLM with the same INT as a RDM at 75 using Teir 3 spells deal the same damage or are off by about 20 damage. 
Using the GetPlayerByName to getMod(28) just displays 28 and using MOD_MATT it just again displays "28". Thinking this is just a memory location within satuses. I was messing around and trying to get it to display your actual MATT or any other base stat and it just goes back to the memory location.

**Comment by bendangelo** [comment]
I just outputted the numbers and magic bonus attack is being applied correctly. Bothing casting water III the numbers of off by about (528 - 496) 32. I think that's correct.

**Comment by teschnei** [comment]
I am also seeing 32 MAB for BLM75 and 24 MAB for RDM75, with the spells dealing appropriate damage based on this difference
