### ISSUE TITLE
Able to see Loot in a different area

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#2087]
Date & Time: 9/17/15
Frequency: Once
FFXI Client Version: 30150730_1
Area & Coordinates: Ordelles Caves (them)/Port Jeuno (me)
Party or Solo: Party
NPC or Monster Name: According to screenshot, .
ffxiah.com link (for inventory items only):
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue: Was in alliance, alliance dissolved. I was in Port Jeuno for a long while afk. I looked over, and i was able to see the treasure pool of the person who was solo farming in a different area. This has happened before, and ive been able to afk get book credit from gustav tunnel long ago purely by accident while i was in north sandoria.

http://imgur.com/rgHyA7m

As you can see, i was in Port Jeuno the entire time. And yes, the slime oil did go into my inventory.

**Comment by xdemolish** [comment]
still happening?
