### ISSUE TITLE
Dia/Bio tiers do not overwrite respectively 

### ISSUE THREAD

**Issue by Sacshop** [DarkstarProject/darkstar#2088]
dia>bio>dia2>bio2>dia3>bio3 is supposed to be the order in which the buffs replace each other. Currently they are just exclusive and no one will overwrite the other regardless if higher tier.

**Comment by Deadwing888** [comment]
They will also overwrite themselves which isn't retail. The way it works over there is you cast bio, then if you cast it again it will do a little damage but will not refresh the DOT effect.

**Comment by TeoTwawki** [comment]
Last I knew this worked correctly with default settings.lua value. Can you post what the DIA_OVERWRITE and BIO_OVERWRITE are set to are just so anyone reading this knows that isn't the issue?

**Comment by Sacshop** [comment]
DIA_OVERWRITE = 1
BIO_OVERWRITE = 0
Just retested this and dia>bio worked as expected - dia2 did not overwrite bio1 however

**Comment by bendangelo** [comment]
Just looked at the code. The system has to be completely redone to use sub power. Right now it compares power of the current spell to infer if it's dia I or II or III but that's not accurate because dia's power varies. So yeah someone has to go through it and correct it.

**Comment by Hozu** [comment]
It might be easier to just redo the effects themselves by swapping current power and subpower so it uses power for atk/def reduction and subpower for DoT.

**Comment by metalfiiish** [comment]
Built out branch to resolve this. Essentially, we start using the m_Tier setting for status_effect to check it inside of CanGainStatusEffect which is handled on addStatusEffect. Updated bio/dia to reflect the recent changes. Awaiting further scrutiny from Master branch. https://github.com/metalfiiish/darkstar/tree/Dia_Bio_Tiering

**Comment by TeoTwawki** [comment]
should work retail now, but the setting is gone though
