### ISSUE TITLE
The Goblins bat is missing on the Goblin Veterinarian in Pso

### ISSUE THREAD

**Issue by bendangelo** [DarkstarProject/darkstar#2093]
Just opening this as a reminder for me to fix this later.

Fix:
UPDATE `mob_pets` SET `pet_offset`='1' WHERE (`mob_mobid`='16814174');

**Comment by TeoTwawki** [comment]
#1973 should have already taken care of it if referring to that post on the forums.

**Comment by bendangelo** [comment]
I was in game and never saw the bat spawn. I'll have to confirm this.

**Comment by bendangelo** [comment]
This has been fixed, closing..
