### ISSUE TITLE
Sublimation Remains After Job Change

### ISSUE THREAD

**Issue by Zenny89** [DarkstarProject/darkstar#2100]
Charging Sublimation to full then changing jobs (to something not main or sub SCH) makes the sublimation effect remain and can't be removed.

**Comment by teschnei** [comment]
adding on to this, it should be removed when zoning into mog house

**Comment by Hozu** [comment]
This is a side effect of having it being not removable by dispel, and not lost on zone change - any buff like that can't be removed by job change. That was the case with Velocity Shot until I fixed it recently - I made it lost upon zoning as per the wiki.

**Comment by teschnei** [comment]
unfortunately, sublimation is not lost on zoning (unless it's to the mog
house)

**Comment by Zenny89** [comment]
So we'd need a new flag then?

**Comment by wrenffxi** [comment]
Fixed in PR #3432

**Comment by wrenffxi** [comment]
Can be closed.
