### ISSUE TITLE
crash server - linux

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#2103]
It's not a first time what happening... 

18/Sep] [17:17:16][Status] luautils::free:lua free...	 - [OK]
[18/Sep] [17:17:16][Warning] Memory manager: Memory leaks found and fixed.

**Comment by xdemolish** [comment]
paste your log\DSP.leaks

**Comment by teschnei** [comment]
nothing to do with free/leaks... it's what happened before that caused it
to start shutting down

**Comment by AlexandreCA** [comment]
I'll send you the paper or I guess, but describes the error but where I can find it?

**Comment by bendangelo** [comment]
You should run your server inside gdb. It'll give you more information, like the backtrace.

**Comment by AlexandreCA** [comment]
Thank you to bring me your help, but I know how to make use of gbd . Actually, I do not even know its existence .

**Comment by bendangelo** [comment]
Ok, do you have steps to reproduce? If not then I'll have to close this because we can't fix this without that info

**Comment by AlexandreCA** [comment]
I noticed is that we were an invitation to another player that the server crashes. When do I use it the invite, in the menu. The command for inviting in the chat barr work.

**Comment by bendangelo** [comment]
I fixed that bug today, closing. Pull latest.

**Comment by AlexandreCA** [comment]
thanks
