### ISSUE TITLE
Single items returned from AH by search are returned in stack form

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2110]
Expired single items from the AH are returned in stacks instead of singles.

**Comment by TeoTwawki** [comment]
Sure you didn't miss an AH change? 99% sure I saw a commit fixed exactly this..

**Comment by bendangelo** [comment]
Need someone to confirm this.

**Comment by RunAwayDSP** [comment]
https://github.com/DarkstarProject/darkstar/commit/bc70f99480b7d89dfd29dc41a5f744b4407456db

jun 8th might want to verify your code Nasomi

**Comment by nasomi** [comment]
Found it, came through while I was out of the country. Thanks!
