### ISSUE TITLE
Mob Skills with conditions being used whenever.

### ISSUE THREAD

**Issue by Leelink1** [DarkstarProject/darkstar#2113]
Noticed that Khimera should be using Fulimation when below 35%. Instead it seems to be doing it whenever he feels like it. Not 100% sure its just Khimera or if its all moves with a return condition.

**Comment by Hozu** [comment]
That check got re-added in this commit: https://github.com/DarkstarProject/darkstar/commit/0912ce98a021e6a04c381345fb9111ccd9100bda

**Comment by wrenffxi** [comment]
This can close.  It's Khimaira only uses fulmination at low HP.
