### ISSUE TITLE
Dancer job: Izhiikoh high damage occasionally hits.

### ISSUE THREAD

**Issue by Dimmabr** [DarkstarProject/darkstar#2115]
Hello everybody, I grabbed the dagger izhiikoh the last week and I was very happy but when I went to use my Dancer job it does not work the high critical hit damage , please could see how this will work? thank you.

**Comment by TeoTwawki** [comment]
Wtf are you even talking about "the high critical damage" ?

> [Main] All Races
> DPS: 3240 DMG:108 Delay:200 DEX+15 Accuracy+10 Attack+8 Evasion+22 Dagger skill +242 Parrying skill +242 Magic Accuracy skill +188 "Triple Attack"+2%
> LV 99 THF BRD DNC

Those are the stats according to ffxiah.com
I have no idea if the item is even implemented in DarkStar yet. if it isn't, to bad. This place will be a real mess real fast if everybody opened an issue report for every single missing item. If the server you play on tells you nothing is wrong with it on their server and you disagree, maybe you should try and better explain wtf you are talking about. I see on Legions Tracker R3P0FFXI told you:

> Enhances "Triple Attack" Effect 2
> 
> This has the correct mod on it you are just unlucky please stop opening Dancer job related tickets Dimma we have no intention of working on dancer any time soon

THF has native triple attack for that to stack onto. DNC does not. There is nothing to do with crit damage on that item that I can tell. Your "bug" doesn't look like there is any bug.

**Comment by xdemolish** [comment]
feature request, not a bug

**Comment by Dimmabr** [comment]
Nah Teo , Izhiikoh contains un hide effect when you are hitting the monster he occasionally does high damage when hitting , like Twashtar and Mandau but in smaller proportions of damage .

**Comment by teschnei** [comment]
No, it does not. Yes, I have one on retail.

**Comment by TeoTwawki** [comment]
@Dimmabr Nothing about it on any wiki, and you said it was working for THF but there is no code at all to support doing that on a per job basis.

**Comment by Dimmabr** [comment]
Serbebus doing high damage 700-800 dmg by hitting beats while Izhiikoh doing 300-350 always by dmg hits

**Comment by Dimmabr** [comment]
Retail it do...
