### ISSUE TITLE
Something is causing the despawn time parameter of SpawnMob() to be ignored?

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2116]
Force pop mob loses interest in player, was set to 180 second despawn
`
SpawnMob(mobidhere,180):updateClaim(player);
`
mob instantly depops instead.   `\_(o.o)_/`

Quickest way to reproduce is give something force popped a charm skill, let it charm you. Watch it instant depop.

**Comment by bendangelo** [comment]
Can you give me a good example mob I can reproduce this with?

**Comment by TeoTwawki** [comment]
I dunno.

Someone I was helping mistakenly gave a wrong ID to a mob they were building, and it wound up using frog chorus instead of what they were expecting (and that charms). And it instantly depopped after charming, every time.

Since charm doesn't do anything special *to the mob that used it* I would think you could spawn some random force popped (any of the ZNM maybe after GM'ing yourself the pop item) thing and `@goto <me>` to see it depop.

**Comment by Hozu** [comment]
All ZNMs seem to be like that. If you lose all aggro due to a wipe or whatever, they instantly depop. Ix'Aern MNK sticks around though.

**Comment by TeoTwawki** [comment]
Its supposed to be the latter, starting the moment the mob goes idle.

**Comment by TeoTwawki** [comment]
hmm.. Ix'Mnk is using
`SpawnMob(16916815, 300):updateEnmity(player);`
Instead of updateClaim()..Maybe thats whats causing it to behave differently.

**Comment by bendangelo** [comment]
Right I think `updateEnmity` is the correct way. This will seed hate and start the countdown.

**Comment by TeoTwawki** [comment]
updateClaim() should be made to work as well though, or we'd need to call both of them in a ton of places.

**Comment by bendangelo** [comment]
So those methods both do different things. `updateEnmity` adds a small amount of hate to the mob. `updateClaim` will claim the mob, this will only update it's name color. We basically need one method which does both of these things.

**Comment by TeoTwawki** [comment]
We need `updateClaim` to do both things, `updateEnmity` still has its own purpose for mobs that should spawn agro, but not spawn claimed (there are a few).

**Comment by bendangelo** [comment]
Sorry, I just dug deeper, `updateClaim` does do both, it will add a bit of enmity. So we should be only be using that method. Not sure why it isn't working though.

**Comment by TeoTwawki** [comment]
That sorta debunks the theory of the depop being caused by using `updateClaim`, unless the code is broken there.

**Comment by bendangelo** [comment]
Someone just has to look into it now.

**Comment by TeoTwawki** [comment]
Finally had time to try switching it in the scripts and 
`updateClaim()` or `updateEmnity()`
have zilch to do with this instant depop thing.

As a matter of fact I declaimed and degaroed mobs players were telling me instantly depopped using the `@goto <me>` method, an dthey didn't instantly depop for me..The only instant depop I could replicate at all happened *only* when I got charmed. I've been getting told lots of other mobs that do not have a charm move "depop instantly" but I haven't been able to see it myself. Something is fishy.

**Comment by Hozu** [comment]
Try messing around with the time in it - I think if you've been fighting for longer than the amount of time, it will instantly depop at that point. As in, it's counting from when it's spawned rather than when it kills everyone.

**Comment by TeoTwawki** [comment]
Will try that tomorrow to see.

**Comment by teschnei** [comment]
Is that not what is expected?

**Comment by TeoTwawki** [comment]
@teschnei that time value is how long mob can be unclaimed before it depops, its expected to start when the mob goes idle not the moment it spawns.

**Comment by teschnei** [comment]
where do you see it claim that is it the "time unclaimed"?  it explicitly
calls SetDespawnTimer when you call SpawnMob, which just sets the despawn
time to current time + duration

**Comment by TeoTwawki** [comment]
So what WAS this supposed to be, that people have obviously not been using it as, a max time the battle can last? If so thats broken because they don't depop during the fight, and peopel have been scripting their force pop NMs wrong for a long long time.

**Comment by teschnei** [comment]
Takeaway from mine and TeoTwawki's IRC conversation: the despawn timer in SpawnMob is only used to despawn the mob from the time it was spawned, but not while it is fighting.  Example: undead mobs despawning when daytime comes.  If you want a NM to despawn after some idle time, use MOBMOD_IDLE_DESPAWN
