### ISSUE TITLE
Helices vs. elemental absorb mod

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2121]
Since the damage from absorbed elements is recovered, this causes the helix DoT to be a huge amount because it's unsigned, and basically just kills anything that can absorb the element. Unfortunately I don't have a retail account to see if the helix DoT should be "absorbed" (ie. regen the enemy) or just be nullified. Easiest way to test is Puks in ToAU areas, they absorb wind element.

**Comment by teschnei** [comment]
i confirmed that the dot does no damage when the original nuke is absorbed
