### ISSUE TITLE
Build Failing due to status_effect_container.cpp

### ISSUE THREAD

**Issue by ElectronJunkie** [DarkstarProject/darkstar#2123]
Hopefully this is just some weird snafu on my end (apologies in advance if it is) but am getting the below while building a fresh pull using MSVS 2015

1>  status_effect_container.cpp
1>c:\ffxi\server\src\map\status_effect_container.cpp(99): error C2079: 'EffectsParams' uses undefined class 'std::array<effects::EffectParams_t,802>'
1>c:\ffxi\server\src\map\status_effect_container.cpp(111): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(111): error C2228: left of '.Flag' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(122): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(122): error C2228: left of '.Name' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(123): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(123): error C2228: left of '.Flag' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(124): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(124): error C2228: left of '.Type' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(125): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(125): error C2228: left of '.NegativeId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(126): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(126): error C2228: left of '.Overwrite' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(127): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(127): error C2228: left of '.BlockId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(128): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(128): error C2228: left of '.RemoveId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(130): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(130): error C2228: left of '.Element' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(132): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(132): error C2228: left of '.MinDuration' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(140): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(140): error C2228: left of '.Element' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(241): error C2677: binary '[': no global operator found which takes type 'EFFECT' (or there is no acceptable conversion)
1>c:\ffxi\server\src\map\status_effect_container.cpp(241): error C2228: left of '.BlockId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(247): error C2677: binary '[': no global operator found which takes type 'EFFECT' (or there is no acceptable conversion)
1>c:\ffxi\server\src\map\status_effect_container.cpp(247): error C2228: left of '.NegativeId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(269): error C2677: binary '[': no global operator found which takes type 'EFFECT' (or there is no acceptable conversion)
1>c:\ffxi\server\src\map\status_effect_container.cpp(269): error C2228: left of '.Overwrite' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(300): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(300): error C2228: left of '.Overwrite' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(306): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(306): error C2228: left of '.RemoveId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(312): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(312): error C2228: left of '.NegativeId' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(343): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(343): error C2228: left of '.MinDuration' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(344): error C2109: subscript requires array or pointer type
1>c:\ffxi\server\src\map\status_effect_container.cpp(344): error C2228: left of '.MinDuration' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(1117): error C2677: binary '[': no global operator found which takes type 'EFFECT' (or there is no acceptable conversion)
1>c:\ffxi\server\src\map\status_effect_container.cpp(1117): error C2228: left of '.Name' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(1117): error C2664: 'std::_String_iterator<std::_String_val<std::_Simple_types<char>>> std::basic_string<char,std::char_traits<char>,std::allocator<char>>::insert(std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>)': cannot convert argument 1 from 'unsigned int' to 'std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>'
1>  c:\ffxi\server\src\map\status_effect_container.cpp(1117): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\ffxi\server\src\map\status_effect_container.cpp(1127): error C2677: binary '[': no global operator found which takes type 'EFFECT' (or there is no acceptable conversion)
1>c:\ffxi\server\src\map\status_effect_container.cpp(1127): error C2228: left of '.Flag' must have class/struct/union
1>c:\ffxi\server\src\map\status_effect_container.cpp(1128): error C2677: binary '[': no global operator found which takes type 'EFFECT' (or there is no acceptable conversion)
1>c:\ffxi\server\src\map\status_effect_container.cpp(1128): error C2228: left of '.Type' must have class/struct/union

**Comment by teschnei** [comment]
#include <array>
