### ISSUE TITLE
Players are able to do certain actions under sleep status.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2127]
I tested this on a stock test server, spawned Diabolos from the CoP fight so it would inflict Sleep I status, and I was able to cast spells while slept (yay for waking self with cure!). I was not able to reproduce the ability to move or attack while slept on my test server, however, so either that's fixed or is an issue with custom content.

Edit: I *think* players may also be able to cast during stun as well, since I've had spells continue through stun from Thunderbolt a few times.

**Comment by Sacshop** [comment]
Tested this as well Hozu and yes you can indeed continue to cast during stun if caught midcast - but I was not able to start casting while under the stun effect.

**Comment by bendangelo** [comment]
I'll test this out myself.
