### ISSUE TITLE
Ninja beastmen mobs crash server when attacked.

### ISSUE THREAD

**Issue by Gundar25** [DarkstarProject/darkstar#2128]
not sure if this is just me or if anyone else is running into this. but tried it out on 
tonberries and yagudo nin job mobs all the others seem to be fine just ninja mobs 
giving  problem. sorta new to this. so sorry if this isnt kosher.

**Comment by Hozu** [comment]
Well that explains why I got a strange crash as soon as attacked a certain statue in dynamis - one that spawned NIN mobs.
