### ISSUE TITLE
The NM Tarasque in Ifrit's Cauldron does not spawn

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2129]
Seems to be listed in mob_spawn_points.sql but has 0 0 0 for xyz posistion.

Important as it prevents the obtaining of Kikoku.

**Comment by Fiocitrine** [comment]
Does the mob have typical mob AI? You could either go to retail and look to see where it spawns or put in a really good guess for it's spawn position!

**Comment by dphillips2014** [comment]
He should be in now, my pull request (#2180) was merged. I pull requested my Habetrot code as well.

**Comment by Deadwing888** [comment]
He works, this can be closed.
