### ISSUE TITLE
Issues with SQL mob_droplist

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2132]
I fixed it on my end, and some SQL programs may just ignore this, but mine errored. The two lines:
INSERT INTO `mob_droplist` VALUES (4539,0,6014,89);;
INSERT INTO `mob_droplist` VALUES (4555,0,5563,93);;

Have the extra ; which navicat full version found as a problem. I removed it on my SQL and it imported fine after. Just wanted to let someone know.

**Comment by bendangelo** [comment]
Can you open a PR?
