### ISSUE TITLE
Sneak and Invisible do not last long enough

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2135]
At high enhancing skill sneak and invisible will often last 5 minutes on retail. On darkstar sneak and invisible seem to come off much quicker and it is a source of widespread frustration.

If you need me to collect some specific data let me know; but perhaps this is one of those times where we pave over guesswork with slightly more educated guesswork.

**Comment by bendangelo** [comment]
It says on wiki sneak lasts around 10 minutes. Not sure if it is based on enhancing skill though, don't think it is.

**Comment by Deadwing888** [comment]
I have some memory of it lasting shorter when you first them. I always assumed that was tied into lower enhancing magic skill, possible it's level related or just my faulty memory.

**Comment by bendangelo** [comment]
I'll test it out later.

**Comment by teschnei** [comment]
I've never seen sneak/invis last less than 10 minutes (with capped
enhancing skill).  Not including spectral jig (which is ~2 minutes)

**Comment by teschnei** [comment]
you can also check the source code for the windower addon timers, it's
usually pretty exact for those

**Comment by Hozu** [comment]
If you're testing on retail don't you get exact duration with SE's new timers for status icons?

**Comment by teschnei** [comment]
actually, it does seem a bit variable - always 7 to 9 minutes

**Comment by bendangelo** [comment]
Could test with a subjob 75 thf/ whm, to confirm enhancing skill affects duration. From the wiki it says sneak has a longer duration than invisible, so we need to confirm that as well.

**Comment by teschnei** [comment]
Don't know about that, I casted them both a few times and sometimes sneak
was longer, sometimes invisible.  both went 7 to 9 minute duration

**Comment by Hozu** [comment]
While you guys are at it, how does Skulker's Cape modify sneak/invis? Currently it's coded to give +50% duration.

**Comment by Deadwing888** [comment]
I can testify that is what it does

**Comment by Hozu** [comment]
Ah neat, guess I made good use of it on retail so many years ago.. How about sneak/invis via oils/powders, and spectral jig? How is the duration on those compared to retail?

**Comment by teschnei** [comment]
Spectral Jig is always 3 minutes (barring enhancing gear or whatever)

**Comment by Deadwing888** [comment]
Oilpowders feel about right to me.

**Comment by bendangelo** [comment]
As soon as someone confirms enhancing magic affects duration I can make a quick fix.

**Comment by teschnei** [comment]
still get 9min with 155 enhancing skill

**Comment by bendangelo** [comment]
Ok I'll make sneak / invisible last around 7-9 minutes, but I do remember invisible / sneak occasionally lasting only a minute.

**Comment by teschnei** [comment]
Yes, it doesn't do that anymore (at least not since the sneak/invis on jig
change)
