### ISSUE TITLE
Player position not saved on crash or disconnect

### ISSUE THREAD

**Issue by waytim** [DarkstarProject/darkstar#2136]
This started happening about 5 months ago. If you leave the game any other way than logging out, it sends you back to wherever you last zoned in.  This is a huge pain for things like prommies where POL crashes or disconnects happen.

**Comment by bendangelo** [comment]
Maybe a background job can be setup to save the player position every 10 or so minutes?

**Comment by waytim** [comment]
I'm curious as to what it used before? Whatever it was worked fine before an update.

**Comment by bendangelo** [comment]
I think it only saves player position on logouts and zoning.

**Comment by waytim** [comment]
Yes, that is what it does currently, but it was working before;  I was just asking if anyone knew what method it was prior to. Something was set up and broke. I'm not sure it needs a whole new feature, maybe just the old method looked into.

**Comment by Novah1** [comment]
I don't think it was working before, it always worked this way.

**Comment by TeoTwawki** [comment]
This has been driving me batty for over 2 years, while devs insisted to me I was wrong and it only happens if the server crashes and I argued no, my server did NOT crash, I merely DC'd...

**Comment by TeoTwawki** [comment]
If you interact with an NPC at all, you will usually land back at that NPC instead of the last zoneline you crossed. Has to be an onTrigger interaction, the regions triggering for promy teleports don't count.

**Comment by teschnei** [comment]
I don't remember this argument. You will never be able to save position
properly on a server crash obviously, but a client disconnecting not saving
position is a bug (that should be trivial, unless there was a reason and I
forgot by now what it was)

**Comment by bendangelo** [comment]
@teschnei Would you agree to setting up a background job to save player positions every 10 mins?

**Comment by teschnei** [comment]
of course not, there is absolutely no need for that

**Comment by teschnei** [comment]
just have to save the position when the character entity is deleted

**Comment by bendangelo** [comment]
I'm not talking about logging out. I'm talking about in cases of crashes / disconnects. I just checked the code base and positions are only saved on login and zoning.

**Comment by TeoTwawki** [comment]
When char times out, its last known position the server actually got from client should be saved just like a logout would have, which only leaves a server crash benefiting(I know that word here is arguable Kj) from a timed job. The crash people were noticing this with was a client crash, in case anybody was confused about that (players keep using crash and dc interchangeably when talking about client crashes).

**Comment by teschnei** [comment]
the position when the server crashes does not matter.  I'm talking about
when your client crashes, or you close your game without using logout,
which is what the reporter is talking about

**Comment by waytim** [comment]
^ Exactly. Being on 3rd floor of prommy and 1 out of 6 d/c you all have to go back to the beginning to accommodate the player who is now at the beginning of zone. If you could have it savecharposition when the char entity is deleted that would be perfect.
