### ISSUE TITLE
Beastmaster's Sic job ability and the claiming system

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2137]
If a beastmaster uses sic on a white mob and his pet starts running toward the mob, if the mob is claimed before his pet gets there, his pet will proceed to attack the claimed monster and change claim over to the beastmaster.

Therefore it essentially acts as a provoke, but one that would bypass the claim shield (if darkstar had a claim shield).

**Comment by bendangelo** [comment]
Good catch, I would say this is a high priority bug.
