### ISSUE TITLE
Crash when attacking some monsters

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2142]
I noticed a few random crashes with my server, not sure if its something I've done (Just reverted everything to core except settings..), or something else. But I did get a crash dump.

https://drive.google.com/file/d/0B5bAzpYtD2lzN0VvOFNOb1hTUTA/view?usp=sharing

**Comment by tagban** [comment]
I saw a crash from 2 days ago that was closed supposedly linked to nin mobs.. But I am fully updated on this crash dump so not sure if its the same issue or not.

**Comment by Hozu** [comment]
I don't think the issue was fixed, and it may extend to more than just NIN mobs. I believe DRG mobs may also cause this, but it's best to check all jobs ofc.

**Comment by tagban** [comment]
Yea I was testing it with a mob in Dyna real fast, but its happened 4 times in a day when people were attacking beastmen.

**Comment by Novah1** [comment]
I had to roll my server back to an earlier commit, because the bug gets triggered every few moments

**Comment by bendangelo** [comment]
Just fixed this by conquicidence in a7de70f3183becd99e5417e00a1f86be09f7ccf9

**Comment by tagban** [comment]
Thanks!!!!!!
