### ISSUE TITLE
Dezoning (warp, etc.) sometimes warps to same zone

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2150]
For example, I paid Ibwam 300 gil and got sent to the zone line where I entered Windurst Woods. I've had a similar issue using a warp scroll.

Revision: 2cb95ef
Server: Classic

**Comment by takhlaq** [comment]
does this still happen?
wasn't able to get it to happen with !homepoint

**Comment by zynjec** [comment]
Unable to repro, open another issue if you're still having an issue.
