### ISSUE TITLE
Odin crashes when using Dismiss

### ISSUE THREAD

**Issue by PikaFox** [DarkstarProject/darkstar#2151]
Steps taken to reproduce:

Used Astral Flow
Summoned Odin on mob
Odin used Zantetsuken on mob
I derped and used dismiss forgetting he will auto dismiss after he finishes
Dismiss was allowed to go through, however it caused a server crash

**Comment by zynjec** [comment]
Unable to repro on master, if anyone else has this issue feel free to open a new issue.
