### ISSUE TITLE
Items that proc curse effect are overpowered

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2152]
I'm mainly talking about the igqira gear here, but possibly others as well. 

Firstly the proc rate is much too high.
Secondly it should not proc vs hnm (shaving off 15% of their health right off the bat).

We regularly start hnm fights by having the black mage stun it and curse the mob off their gear. It's funny and effective, but not retail.

**Comment by Hozu** [comment]
This is part of the already existing issue with spikes.

**Comment by bendangelo** [comment]
I will reduce the proc rate of igqira spikes, right now it's stupidly high but of course spikes need to take resistance into account.

**Comment by Hozu** [comment]
IIRC the Gothic Sabatons/Gauntlets have a fairly low proc rate (below 10% or something) yet they proc 100% so there's an issue somewhere else.

**Comment by TeoTwawki** [comment]
> Secondly it should not proc vs hnm (shaving off 15% of their health right off the bat).

Never ever, or just insanely rare like most things of this sort vs HNM?

**Comment by Deadwing888** [comment]
That's a good question.

My money is on never ever (as I never ever saw it) but I honestly don't know for sure.
