### ISSUE TITLE
/yell seems to happen two times

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2153]
It seems to show that I send it once, and then after it goes to everyone within yell range, it gets displayed to me again. After reviewing code, it appears maybe its not going thru the message server properly. 

I do have SQL modified to allow all users on server to see the Yell messages, but thats the only modification for that.

**Comment by teschnei** [comment]
It should exclude the yeller when pushing messages to everyone, but that
might not be implemented or working correctly

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/b2738c44940853a4976551e80fd0ab4186a4870b
