### ISSUE TITLE
Woodworking crafting - level 16 (North Sandoria)

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#2154]
I ve decided to continue to ride my craft . However, the NPC to Sandoria refuses to take me his item. I no problem crafting a Maple table but when I trade him . Nothing is happening.

Unless its an error on my part .. If anyone can tell me .

http://ffxiclopedia.wikia.com/wiki/Woodworking_Guide_by_Godofgods

TEST ITEM: Maple Table (16)--Earth Crystal, Maple Lumber x4— Now it's time to use those Maple Lumbers you've made. These are supposedly great for gardeners, so if you know any be sure to ask if they'd like to buy them.

**Comment by towbes** [comment]
You have to turn in the item between woodworking skill level 18-20

**Comment by AlexandreCA** [comment]
Ok, yet the wiki talks about having the level 16. My level refuses to raise even making maple loop tables. I'm at the max for this part . In addition, the NPC reclame me the object to show me new techniques .

**Comment by AlexandreCA** [comment]
You have right! That at working in level 19. Thanks!
