### ISSUE TITLE
Alliance not properly displayed at party overview

### ISSUE THREAD

**Issue by Thexder** [DarkstarProject/darkstar#2163]
FFXI Client: 30150629_4, DarkStar - Git Revision Hash: 34092a4488559a2925487b877a5ce345029bd972.  Both not the latest, but not old either.

Form an alliance of two parties.

On retail you see on lower right corner two parties stacked upon each other with their members at each ffxi instance. 
In DSP the other party is not displayed at all. The white dot though points to the alliance leader and indicates an alliance.
![alliance-not-displayed-at-party-setting](https://cloud.githubusercontent.com/assets/1940761/10232572/c848e954-6889-11e5-8f8a-5bc6ec33bf25.png)

**Comment by xdemolish** [comment]
update your server and reopen if it's still an issue
