### ISSUE TITLE
Jungle Boogeyman

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#2169]
Tonberry in this BCNM seem to deaggro, depop and trigger the win.

EDIT: not sure if this is indicative of the overall deaggro system or just this BCNM

UPDATE | EDIT: Depopped Divine Might as well, for the win

**Comment by bendangelo** [comment]
This is because the navmeshes are broken in those zones. @gedads is going to be redoing them.

**Comment by bendangelo** [comment]
Fixed, repull navmeshes
