### ISSUE TITLE
Items with charges get recharged

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2175]
When using an item with a charge, such as warp crudgle, if you change gear while it's activating, it will be fully charge when you zone.

**Comment by Hozu** [comment]
I could not reproduce this - I had a Protect Earring equipped, used it, and during the activation time I hit my macro that called an equipset to change gear (including both earring slots). The Protect Earring activated, and granted the effect. When I zoned, it was still down a charge.

However, I tested this on a slightly older build so it may be a thing. Or maybe I did it wrong?

**Comment by bendangelo** [comment]
I think this is a multi-server issue.

**Comment by nasomi** [comment]
It's been happening for quite some time, it's only recently that I've been able to reliably reproduce it. Can you try with warp crudgle? That's how i was able to reliably reproduce it.

**Comment by BRFord88** [comment]
I attempted to reproduce this with the warp cudgel and was unsuccessful after several attempts.

**Comment by xdemolish** [comment]
closing cause cant reproduce, reopen if it's still an issue (only if you've updated to latest rev at time of bug)
