### ISSUE TITLE
Sleepwalking

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2176]
When mobs sleep players, players can still move around, though not cast spells or do actions.

**Comment by bendangelo** [comment]
Is this reproduce-able with any kind of sleep? Sleep? Item? I couldn't reproduce this with sleeping potions.

**Comment by OtianNgocnion** [comment]
I have noticed this in dynamis with both horde lullabies and sleepgas originating from dynamis mobs.
