### ISSUE TITLE
Dyna Timer reset

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2177]
If you crash out of dynamis, when you return your timer will be reset to 1 hour.

**Comment by bendangelo** [comment]
What timer? What do you mean?

**Comment by nasomi** [comment]
The dynamis timer for being in dynamis.

**Comment by wrenffxi** [comment]
This issue can be closed.  Players who log into Dynamis zones after their run ends (by server crash, or everyone else leaving zone) will now be kicked out of the zone.  (If it's a GM, they'll instead be registered for a new Dynamis run.)
