### ISSUE TITLE
Parties and Alliances causing server lag

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#2179]
Seeing an issue where parties and alliances seem to be causing a 5 second server lag.

**Comment by bendangelo** [comment]
Do you have steps to reproduce? Need a little more info. A half full alliance is enough to produce this problem? Laggy in what way?

**Comment by R3P0FFXI** [comment]
@bendangelo a half or full alliance can produce this lag easy. The lag is simple you hit a macro or perform an action and it takes at least 5+ seconds for the server to see it. We've also had instances where characters are hit 3-4x server side but only seen being hit 1x client side and players just drop dead. It is not the hardware we are running on or the connection being used as our server is not even bypassing 12% CPU usage or 40% RAM usage, the only thing i can deduce is there is an issue with party packets on DSP end something is not right.

**Comment by TeoTwawki** [comment]
And I can confirm that when I log into his server, I experience zero lag while solo..

**Comment by TeoTwawki** [comment]
Beyond that I dunno anything about this, other than some guy in the global LS complaining about is and blaming navmesh. I don't do any of the alliance stuff but so far as I know that has *always* been kinda laggy on dsp so shouldn't be anything new.

**Comment by teschnei** [comment]
The client tends to do that when it is receiving packets faster than it can
handle. (For the record, it's probably not server lag, as you can see from
the resource usage, but it might be worth investigating how much time is
spent on packet handlers and ticking). If it's constrained to just parties
and alliances, navmesh is out of the question (as it varies by players
nearby, which do not touch navmesh stuff). Check the receiving packets
value in the top right of the client, maybe?

**Comment by TeoTwawki** [comment]
The loud complainer about it says his R value jumps up and down 80-1600 "just while idle"..I followed him around for a few hrs and while my R value jumped a bit form mob models loading onto my screen, all my abilities and spells etc were able to go off without any delays. I was solo, and he was in alliance HNM hunting, so it *might* be from that. I bet if we bring him into this discussion he'll claim his net is perfect and it happens to him everywhere all the time etc. etc..

**Comment by teschnei** [comment]
Could be party update packets, but I myself am not inclined to 18 box on my
own server. Will wait for confirmation from a more reputable source than a
random player

**Comment by TeoTwawki** [comment]
I'll see if I can get 17 other people to do..I dunno something I don't usually do, and see if its super bad compared to my normal lag free time. I rarely even log in anymore but did yesterday just to look for this lag.

**Comment by R3P0FFXI** [comment]
@teschnei It is multiple people not just 1 complaining about this, 1 of them is @Loki79 he is the source I am using in regards to submitting this report.

**Comment by TeoTwawki** [comment]
@R3P0FFXI I'm still gonna go see if I can make my character lag hard just by being in an alliance.

**Comment by TeoTwawki** [comment]
@teschnei things seemed ok even in alliance until I used `@goto` mid fight to jump to where R3's character was. Then suddenly all action on my screen became stop motion animation, and R3's character struggled for more than half a minute to get off a ws. It got worse over the next several min from there until on my screen nothing was moving and players were invisible but I could see mob health falling. This was with a 14 man alliance and 6 or 8 mobs agroed, and a few mobs idle. The group also did some NMs and each time I was able to trigger my lag the same way, and if i repeated it multiple times I could near lock my client. Even running across the zone way away from the alliance didn't return me to normal - had to re log to straighten myself out.

**Comment by nasomi** [comment]
Instruct everyone to disable mob drawdistance. Have had that create issues like this before.

**Comment by TeoTwawki** [comment]
drawdistance has nothing at all to do with it.

**Comment by R3P0FFXI** [comment]
First off as Teo said this has nothing to do with Drawdistance. We have verified it is not a hardware issue as our current setup can handle 30k concurrent connections with ease. most likely this is due to DSP incorrectly handling the 0x0D packet as its sent as a full update to the client which appears to not be correct.

**Comment by teschnei** [comment]
0x0D hasn't sent full updates every tick since april 2014

**Comment by TeoTwawki** [comment]
https://forums.dspt.info/viewtopic.php?f=15&t=2923

I've asked some people to try and log what packets they are getting during their "super lag" to see if its for sure a packet problem.
