### ISSUE TITLE
Prowess seems to break times showing subsequent status icons

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2182]
When using the built-in status timers, prowess shows at 99h. New icons to the right show up without a time at all.

Revision: f4d33ae
Server: Classic
Client: 30150910_3

**Comment by teschnei** [comment]
There's already a bug report for this (and I was just thinking about
getting to it tonight)

**Comment by xipies** [comment]
I had even read that one a few days ago. I should have searched for "prowess" first. :)
