### ISSUE TITLE
Some problems with the Magic Accuracy tweaks

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2183]
The changes to the magic accuracy formula have made spells too hard to land at low levels (even with the best gear) and too easy to land at high levels. 

I'm not sure what was changed, but It's actually a pretty serious problem for daily play.

**Comment by bendangelo** [comment]
I been looking into this. I need more data points from retail.

**Comment by teschnei** [comment]
Repeating the same mistakes I did when I implemented the previous formula :p

**Comment by Deadwing888** [comment]
Feel free to use retail wing's gil to gear yourself a blm to play with.

If you're too busy let me know and I can get to it within a couple of days.

**Comment by bendangelo** [comment]
Fixed https://github.com/DarkstarProject/darkstar/commit/0fe4d0a40f2f5e1b3aa78741c6303043e4cde502
