### ISSUE TITLE
Issues with the Enmity system

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2186]
Major issues:

1) Healing magic produces no CE
2) Taking damage from a mob's melee attacks does not reduce CE
3) Hate is not wiped upon death
4) Large amounts of damage cause enmity to overflow and reset to 0

Minor Issues:
5) Absorbing an attack with a shadow does not cause 25 CE to be lost.
6) In 2010 SE nerfed the VE/CE values for the spells that allowed rdm/nin, nin/drk, and pld/rdm to tank in the level 75 era. I know DSP follows retail, but it uses the old Kings Spawn system and old dynamis so I thought it may want to use the old enmity values too. Even if not it might be cool to have a level era 75 branch with un-needed content removed and certain values set to their ~2006 levels.
7) Hate is wiped upon logout or zone change. Retail would only reset your hate if the mob tried to target you and could not. If you logged out and logged back in while never on top of the hate list, your CE would be preserved.

**Comment by teschnei** [comment]
1-4 i'll take a look at, 5 is part of AI so i won't touch that (pointless atm) and 6 is probably not going to happen with 2 core developers

**Comment by teschnei** [comment]
1 and 2: fixed
3: working as it should (full reset if you are the primary target when you die, removal from hate list when you are not, as per kanico's blog)
4: maybe fixed, hopefully

**Comment by m241dan** [comment]
In terms of 6, if anyone has the old data on what those CE numbers were. I'd love to implement on my server. I know dispel was 320/320 VE/CE from kanican's blog but that's it.

**Comment by Deadwing888** [comment]
Dispel= 320VE, 320CE
Sleep= 320VE, 320CE
Sleep II= 480VE, 480CE
Blind= 600VE, 1CE
Blind II= 600VE, 1CE
Bind= 600VE, 1CE

All else the same. (Unless you're going for a 2005 feel in which case mazurka needs boosted hate for nin/brd tanking)

**Comment by m241dan** [comment]
What about Flash? Has it always only been 180 CE?

**Comment by Deadwing888** [comment]
Yes
