### ISSUE TITLE
fishing problem..

### ISSUE THREAD

**Issue by ghost** [DarkstarProject/darkstar#2187]
I encounter a problem when I want to fish . My character throws the stick and when finished fish takes the bait , we just do anything. There is no cursor or anything . One can just rotate the camera around. A bug that did not exist before .

**Comment by waytim** [comment]
Known bug, no ones looked into it yet I think.  I couldn't figure it out but would love this to be addressed.

**Comment by AlexandreCA** [comment]
Thank you for your answer. I would also like !

**Comment by waytim** [comment]
The main issue for me is that there are some missions and an awful lot of quests that need fished up items. Had to put fish on custom vendors but really takes away from experience. But I was in C++ and the entire system needs to be redone I think, and changed over to the new Arrow dance dance revolution minigame.

**Comment by nasomi** [comment]
The fishing packet changed and no one bothered to adjust the packet system for hte new packet, so when you catch a fish it just stops.

**Comment by nesstea** [comment]
it used to be an actionpacket right?

**Comment by teschnei** [comment]
no, it was a fishing packet, now its a different fishing packet

**Comment by AlexandreCA** [comment]
In this case , it will be time to put the person designated to date

**Comment by TeoTwawki** [comment]
#484
#1307

**Comment by maxtherabbit** [comment]
9cdf53d
