### ISSUE TITLE
New linkshells don't work until server restart, and changing lsmes does't update cross server

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2190]
When creating a new linkshell it only is effective on the server it was created.

When changing LSMES it is only changed in the server in which it was changed.

**Comment by TeoTwawki** [comment]
That explains so much weirdness I haven't been able to reproduce to report. I was changing lsmes then I'd relog 3 days later and it was the old lsmes again. I don't have a bunch of zones on diff map server like you (just a few, like my GM only idle zone) so it never occurred to me that was the cause
