### ISSUE TITLE
First tier cure/dia/haste have more hate than provoke

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2197]
https://github.com/DarkstarProject/darkstar/commit/80d6c3746b906242f430359736c690b0512ccd08

Whm casts one cure and steals hate from tank after multiple vokes/weaponskills.

**Comment by teschnei** [comment]
Adding on to this: dia and haste are probably correct. Dia for sure. The
difference is they generate CE while provoke does not. If the tank takes
enough damage and doesn't deal enough to generate CE, this is expected.
However, it's not out of the realm of possibility that the CE decay is
wrong, or that cure is generating too much CE. It's also possible that
these players are used to cures generating no CE (as that was the case
always before a few days ago) and are not gearing/playing their tanks
properly.

**Comment by Deadwing888** [comment]
I'll update my server and take a look at the prints

**Comment by Deadwing888** [comment]
Enmity appears genuinely broken at the moment. Cures give no hate, damage gives no hate, spells give hate but it's reset to 0VE 1CE if you do damage.

**Comment by teschnei** [comment]
Have you updated since this issue was closed?

**Comment by Deadwing888** [comment]
Yes, I've tried both yours and nas's enmity_container it seems broken for both

**Comment by Deadwing888** [comment]
Looking at more prints, damage does generate some enmity, but it keeps getting reset to 0VE 1 CE

**Comment by xdemolish** [comment]
did you rebuild?

**Comment by Deadwing888** [comment]
Yeah, I'm 95% sure I'm using the correct enmity_container and there appear to be these problems on Nasomi server as well

**Comment by bendangelo** [comment]
What's the easiest way to reproduce?

**Comment by Deadwing888** [comment]
Casting spells seems to be resetting enmity in some fashion. Also cures produce no VE and 1 CE all the time.
