### ISSUE TITLE
Client Crash - Quest Black Market 

### ISSUE THREAD

**Issue by RunAwayDSP** [DarkstarProject/darkstar#2204]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Norg/npcs/Muzaffar.lua

Client will crash after completing Black Market Quest, but not every time maybe 25%-50% of the time.

**Comment by TeoTwawki** [comment]
Incoming fix.

**Comment by TeoTwawki** [comment]
#2207
