### ISSUE TITLE
Party is pulling hate from linked unclaimed mobs.

### ISSUE THREAD

**Issue by rpetit3** [DarkstarProject/darkstar#2209]
Server Commit: https://github.com/DarkstarProject/darkstar/commit/5fddd6149aa4a6f2da4a33cae59af7bd91c428e0
Client Version: 30150910_3

---
Expected Behavior: Unclaimed mobs which are linked or aggroed should only attack the puller (or one with aggro) until the mob is claimed and put in the hate pool of the party.

Observed Behavior: Hate is being pulled from unclaimed mobs by party members which have not interacted with the unclaimed mob.

**Comment by bendangelo** [comment]
Do you have steps to reproduce?

**Comment by rpetit3** [comment]
Sure.

In Crawler's Nest at (K-8) there are 3 Death Jackets. Pull one, and link the other two.

Have puller just stand there. Have a party member cast Cure III, and the unclaimed mobs should now begin attacking the healer. This should not be the case, hate should only be pulled from the claimed mob.
