### ISSUE TITLE
Characters changing race on local client.

### ISSUE THREAD

**Issue by rpetit3** [DarkstarProject/darkstar#2210]
Server Commit: https://github.com/DarkstarProject/darkstar/commit/5fddd6149aa4a6f2da4a33cae59af7bd91c428e0
Client Version: 30150910_3

---

Characters are randomly changing into other races locally. Other members of the server see the original race. I haven't quite figured out what triggers the change. I have observed the following:

Gallka --> Hume
Taru --> Hume
Elvaan --> Mithra

**Comment by teschnei** [comment]
disable your plugins

**Comment by rpetit3** [comment]
Will give it a go!

**Comment by rpetit3** [comment]
Looks like blinkmenot may be the culprit!

http://forums.windower.net/index.php?/topic/933-chars-random-race-choocobo-change/

Will test it out tomorrow to verify. I will close for now and reopen if it appears to not be a plugin. 

Thanks @teschnei!
