### ISSUE TITLE
GoV not repeating

### ISSUE THREAD

**Issue by rpetit3** [DarkstarProject/darkstar#2211]
Server Commit: https://github.com/DarkstarProject/darkstar/commit/5fddd6149aa4a6f2da4a33cae59af7bd91c428e0
Client Version: 30150910_3

---

If I choose to repeat a GoV, it does not register.

Looking at groundsofvalor.lua

```
GOV_MENU_REPEAT_REGIME1  = -2147483630; -- 2147483666;
GOV_MENU_REPEAT_REGIME2  = -2147483614; -- 2147483682;
GOV_MENU_REPEAT_REGIME3  = -2147483598; -- 2147483698;
GOV_MENU_REPEAT_REGIME4  = -2147483582; -- 2147483714;
GOV_MENU_REPEAT_REGIME5  = -2147483566; -- 2147483730;
GOV_MENU_REPEAT_REGIME6  = -2147483550; -- 2147483746;
GOV_MENU_REPEAT_REGIME7  = -2147483534; -- 2147483762;
GOV_MENU_REPEAT_REGIME8  = -2147483518; -- 2147483778;
GOV_MENU_REPEAT_REGIME9  = -2147483502; -- 2147483794;
GOV_MENU_REPEAT_REGIME10 = -2147483486; -- 2147483810;
```

If i change it to:

```
GOV_MENU_REPEAT_REGIME1  = 2147483666;
GOV_MENU_REPEAT_REGIME2  = 2147483682;
GOV_MENU_REPEAT_REGIME3  = 2147483698;
GOV_MENU_REPEAT_REGIME4  = 2147483714;
GOV_MENU_REPEAT_REGIME5  = 2147483730;
GOV_MENU_REPEAT_REGIME6  = 2147483746;
GOV_MENU_REPEAT_REGIME7  = 2147483762;
GOV_MENU_REPEAT_REGIME8  = 2147483778;
GOV_MENU_REPEAT_REGIME9  = 2147483794;
GOV_MENU_REPEAT_REGIME10 = 2147483810;
```

All is well.

I can submit a PR, but I'm not sure if there is a reason for the negative numbers in the current version of groundsofvalor.lua

**Comment by teschnei** [comment]
platform dependent code says hello

you'd have to test it on both windows and linux, 32 and 64 bit

**Comment by rpetit3** [comment]
A month later, but are Windows builds not experiencing this behavior?

I cannot test on Windows unfortunately.

**Comment by teschnei** [comment]
Probably not. I know for sure that the maximum boundaries behaves
differently between architectures and platforms in the lua implementations.
However, the bit functions from the bit library will work as the proper fix

**Comment by zilloryatf** [comment]
Can confirm this is still happening. Tried it in Lower Delkfutt's Tower and Kuftal Tunnel, selecting Yes on regime to repeat does nothing. Selecting No works. Tried it in on Windows server and Ubuntu. 

Also tried rpetit3 fix on both but nothing changes, Yes does not work and No works.

**Comment by wrenffxi** [comment]
Can someone retest this with latest regimes.lua on linux and x64 windows.

**Comment by zynjec** [comment]
Seems fine on master now.
