### ISSUE TITLE
Party of 6? Zone crash

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#2219]
6 people in hte same party in the same zone causes the server to crash. Or the same party on the same server, I can't really test that. 6 people in the same party in different server/zone = pol crash. You're fine until you hit 6 people, then something crashes.

**Comment by nasomi** [comment]
just had a confirmed crash with 5 in the same zone.

**Comment by bendangelo** [comment]
Need a dump

**Comment by nasomi** [comment]
https://www.dropbox.com/s/ysncnrducjl5cvp/Hydra.7z?dl=0

**Comment by nasomi** [comment]
It's usually a POL crash first, but if you can get 6, and cast, zone will crash.

**Comment by csundman** [comment]
This is happening on my server as well.

**Comment by csundman** [comment]
I was able to stop this crash from happening on my server by reverting f99c8a8e241286d97bdc608e8f76ec67a86b2a50

I don't know why this fixes it.

**Comment by xdemolish** [comment]
some shit about heap corruption so idek
also: it shouldn't be writing the effects of the player it's being pushed to, and should be using a query to get the info for players not in the same zone (assuming party object was used instead of querying cause isn't supposed to display for members not in zone, but zone should be checked before pushing the packet in that case)

**Comment by teschnei** [comment]
I think it will leave blanks for players not in zone, so ya the database
will be needed to get the right order

**Comment by bendangelo** [comment]
Can we just revert the commit until it gets fixed?

**Comment by teschnei** [comment]
please try 66f6442b17058e9d67aab31520bfa4f04e1d5f90 - I cannot test 6 player parties

**Comment by nasomi** [comment]
Reverting that solves the party issues.

**Comment by coreyms** [comment]
Still have issues with 6 person parties or alliances after 66f6442, under 5 players in a party works fine

**Comment by teschnei** [comment]
Need a dump after 16aec7465c6e286ced2e30d605ad9784043a07f0 (should trigger the debug break)

I am assuming that @coreyms "crash" means server crash and not client

**Comment by coreyms** [comment]
Yes server crash, I will try to get a dump tonight if no one else does
before me.

**Comment by coreyms** [comment]
Here is dump, note: crash didn't happen until there were 8 people (one full party and two in alliance) https://www.dropbox.com/s/jgc0jqba86oji73/1DSGame-server.dmp?dl=0

**Comment by teschnei** [comment]
need pdb and exe too

**Comment by coreyms** [comment]
Sorry, here are all 3 together
https://www.dropbox.com/s/rfa0gu6htr8itg9/DSGame-ServerDMP.7z?dl=0

**Comment by teschnei** [comment]
are you building the server in release mode?  I can't really do anything
with a dump if that's the case (and you won't hit the breakpoint I added)

**Comment by coreyms** [comment]
Oops, I'm sorry, rebuilding, will have it back to you shortly

**Comment by coreyms** [comment]
https://www.dropbox.com/s/ui8v80dawnf7qp9/DMP2.7z?dl=0

**Comment by teschnei** [comment]
I still can't actually see any variables in the dump, so it will be some
time before I can muster the courage to 6 box myself
