### ISSUE TITLE
Empty Welcome Messages Causes Crash

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#2220]
I performed the last update . The compilation is done very well . However, when I raise the server. DSGame shows me an error .

![capture-1](https://cloud.githubusercontent.com/assets/12043587/10384609/f362a6b6-6e0b-11e5-9b4e-4aa0997dd982.png)

**Comment by AlexandreCA** [comment]
![capture](https://cloud.githubusercontent.com/assets/12043587/10384582/7c8b0dd0-6e0b-11e5-8273-b25c89bdf7d0.png)

**Comment by teschnei** [comment]
going to need a core dump

**Comment by bendangelo** [comment]
this could be something in your conf file is too long.

I recommend you run dsgame in gdb. It'll show you stacktraces on crashes

```
./configure --enable-debug=gdb
make
gdb ./dsgame
run
```

**Comment by AlexandreCA** [comment]
server@betsy ~/darkstar $ ./configure --enable-debug=gdb
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LUA... yes
checking for ZMQ... yes
checking for mysql_config... /usr/bin/mysql_config
checking whether to enable assertions... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether g++ supports -Wno-unused-parameter... yes
checking whether g++ supports -Wno-pointer-sign... yes
checking whether g++ supports -Wno-switch... yes
checking for setrlimit... yes
checking for sqrt in -lm... yes
checking for clock_gettime in -lrt... yes
Building Linux targets
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/common/config.h
config.status: src/common/config.h is unchanged
config.status: executing depfiles commands
server@betsy ~/darkstar $ make
make: Nothing to be done for 'all'.
server@betsy ~/darkstar $ gdb ./dsgame
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./dsgame...done.
(gdb) run
Starting program: /home/server/darkstar/dsgame 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[Status] Memory manager initialised: log/DSP.leaks
[Info] DarkStar - Git Revision Hash: bc05914a6f656c8f1bab95f04a96ad0bce5ab136.
[Status] do_init: begin server initialization...
[08/Oct] [22:35:10][Info] Console Silent Setting: 0terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 4294967295) >= this->size() (which is 0)

Program received signal SIGABRT, Aborted.
0xb78daddc in raise () from /lib/i386-linux-gnu/libc.so.6
(gdb)

**Comment by AlexandreCA** [comment]
It's fixed! Thanks a lot!

**Comment by bendangelo** [comment]
What do you mean it's fixed? After it crashes type bt and paste that.

**Comment by AlexandreCA** [comment]
The problem was that I had to delete the welcome message in the conf folder.

**Comment by bendangelo** [comment]
Well this still shouldn't crash the game server. I think it's still a bug.

**Comment by AlexandreCA** [comment]
I do not know what to say. I added a welcome message in the file conf folder and everything works fine since.

**Comment by TeoTwawki** [comment]
see second comment in #1510 An empty server message will cause this.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/issues/1510
