### ISSUE TITLE
Request: Lua Binding for onMobWeaponSkill and onMobUseAbility

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#2233]
There are some Sea gods and ToAU NMs that will greatly benefit from this. This is a reminder for @teschnei. We have two Sea gods ready for it.

**Comment by teschnei** [comment]
AI rewrite branch, not sooner

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/documentation/AI_Events.txt
