### ISSUE TITLE
Ballad sometimes crashing clients

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2238]
Was Ballad II each time. Could be coincidental. Is crashing caster and two (but not all) receiving party members.

Maybe related to client status timers or party icons? Happened with both disabled in client.

Revision: 5f4ffab
Server: Classic

**Comment by csundman** [comment]
This is likely the same issue as #2219

**Comment by teschnei** [comment]
please try on 66f6442b17058e9d67aab31520bfa4f04e1d5f90

**Comment by xipies** [comment]
Seems to be fixed now.
