### ISSUE TITLE
Something is up with Evasion

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2243]
It might be related to the bird family. 

I have no difficulty landing hits with my staff on rdm (0 staff skill) against colibri (of all types) and Suzaku.

**Comment by bendangelo** [comment]
This could be a pretty big issue. I'll look into it.

**Comment by Hozu** [comment]
Imps seemingly have 0 evasion as well.

**Comment by bendangelo** [comment]
I found the issue, I'm making a fix for it.
