### ISSUE TITLE
Feedback on the magic accuracy tweaks.

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2259]
Low level casting feels spot on now.

For High levels the macc formula is still too forgiving. I'm able to consistently land sleep on Tiamat in my enmity set. I don't think it's a Tiamat problem either because it used to resist heavily with the old formula.

**Comment by Hozu** [comment]
Odd, I'm being told that the resist rate is too high at high level. Though that's probably on the certain spells that should have extra magic accuracy (stun/flash, and to a lesser extent, dispel).

**Comment by Deadwing888** [comment]
Double check on that. I'm going to see if I can get some datapoints from retail this week.

**Comment by bendangelo** [comment]
I'll do more testing. I do think MACC is too weak for HNMs but for regular mobs I made it quite accurate to retail.

**Comment by Deadwing888** [comment]
If we're reasonably sure the macc formula is done changing, I can start my big magic/enfeeble resistance balancing pass on HNM lua files. I've got data for almost everything up through 2010.

**Comment by bendangelo** [comment]
I'm done changing the formula. Now we're just balancing the magic evasion rank of mobs.
