### ISSUE TITLE
Fire resistance calculation on faf/nidhogg

### ISSUE THREAD

**Issue by Kubisnaxx** [DarkstarProject/darkstar#2265]
An aegis paladin with a fire resistance set takes as much damage from their breath move as a ninja with no special gear or anything to reduce the fire damage

**Comment by teschnei** [comment]
Don't think aegis affects breath damage

**Comment by bendangelo** [comment]
I found the problem. Legacy code in monstertpmoves.lua gives a generous accuracy bonus to breath moves. I'll make a fix for it.

**Comment by Deadwing888** [comment]
Dragon Breath needs an additional slight rework. It needs to do about 25% less to it's target if they're not directly in front, and about 25% more to anyone who is standing directly in front (including it's target if that's where they're standing).

Also a similar WS called Fiery Breath is missing entirely from Tiamat. It'll hit for about 400 to it's direct target (if they're on the paws) and around 2.2k to anyone standing directly in front.

**Comment by bendangelo** [comment]
I think that's already implemented

**Comment by Deadwing888** [comment]
I'll check how it feels with the latest build. As of a week ago, the basics were correct but the numbers were somewhat off, making Dragon Breath hit too hard vs someone on paws.
