### ISSUE TITLE
Pets seem to be disconnected from master in Dynamis - Xarcabard

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2280]
I can only get avatars to spawn as Carbuncle, when they'd be random of 7 if they had a proper master. In most cases, avatars and SMN mobs spawn from different eyes even. If they spawn from the same eye, defeating the master does not dismiss the avatar either.

Actually, eyes that spawned SMN or BST mob with pets don't even seem to do that anymore.

Dynamis - Tavnazia demons seem to act properly, spawning pets with master.

**Comment by Hozu** [comment]
Hell even the SMN NM doesn't spawn his pet. Not much of a SMN is he...

**Comment by bendangelo** [comment]
The tables in dynamis.lua for xarac are messed up. Someone has to go through the ids.
