### ISSUE TITLE
Missing NPCs in The Colosseum

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2286]
I checked https://wiki.dspt.info/index.php/Zone_IDs and I did not see one for the Pankration area The Pit. There is one for The Colosseum but I am fairly certain this is a different area. 

I need this to fix the Gate in order to enter and script the NPC to give soul plates/ cameras.

**Comment by teschnei** [comment]
pretty sure its the colosseum

**Comment by Fiocitrine** [comment]
hmmm well there are no npcs in the colosseum when I'm transported there from the gate.
Suppose they will have to be fully scripted in ; ;.

**Comment by Fiocitrine** [comment]
Ok so a bunch of missing NPCs in the Colosseum need scripted. Zandjarl seems to be the most useful one here as he gives Soul Plates/ Trappers.
