### ISSUE TITLE
Party of 6 with Level Sync

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#2289]
This seems to cause random clients to crash. Party of 5 and Level Sync, no problem. Add a 6 person, or try to start a fresh sync with 6 and you'll get a bunch of random client crashes, oddly enough, not everyone in the party though.

**Comment by bendangelo** [comment]
You reproduced this with the latest code?

**Comment by m241dan** [comment]
Yah, reliably and with the latest stuff from yesterday. Nothing from today but todays stuff wasn't relevant.

**Comment by Scavenge** [comment]
i can confirm that this did not begin until i updated to the latest code yesterday after having been running off code from oct 21st just fine.

**Comment by Scavenge** [comment]
my only intuition is whether or not the people that do and do not crash ahve anything in common, like ffxi version

**Comment by m241dan** [comment]
I believe it will be fixed when parties of 6 are back.

**Comment by Scavenge** [comment]
I didn't realize they were seperate
