### ISSUE TITLE
Alliance EXP gain

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2290]
I made this issue before but was told it got solved... but it seemingly hasn't though I can't verify on a server with absolutely no custom things, I'm 99% sure we don't have code that affects this.

EXP is only granted to the party that has the killer - anyone else in other parties are not getting any EXP at all.

**Comment by nesstea** [comment]
I confirm this. Killer's party gets exp.

**Comment by jwonesh** [comment]
I have a fix for this issue, going to try to make a pull request.

**Comment by xdemolish** [comment]
@jwonesh https://help.github.com/articles/creating-a-pull-request/
