### ISSUE TITLE
Can't make alliances at all

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#2291]
Here's the rub: If two parties create an alliance, the would-be leader of the Alliance's party goes "solo" but they are still pseudo in the alliance. The search server still shows you as party leader, but you can no longer invite anyone and the UI goes wonky.

Needless to say, once this happens, you can't add a third party to the Alliance because technically you aren't the alliance leader you in a "solo" party.

Zoning had no affect either.

The second party that was invited to the alliance maintains as a party, and can try to send invite third party but it never arrives.

**Comment by nesstea** [comment]
Menu commands stop working as well. the /pcmd commands work though.

**Comment by m241dan** [comment]
anyone have a rollback for this? My server really struggling with the alliance situation xD
