### ISSUE TITLE
Blue Mage Overhaul

### ISSUE THREAD

**Issue by Xine0hp** [DarkstarProject/darkstar#230]
I've been leveling Blue Mage heavily over the past few months and have found some pretty important issues.

-Blue Magic skill doesn't seem to matter for physical blue magic and all seem to be based on strength and attack power rather than the stats they should. My Drk/Blu does more damage to exp mobs with blue magic than my blu main.

-Souleater and Sneak Attack and Trick Attack should stack with physical Blue Magic spells but do not.

-Some blue magic spells are unobtainable because the mobs arent using TP moves. Rafflesia, Qiqrin, and gnoles are examples. 

-Physical Blue Magic Spells should have a chance to critical hit (sneak attack for example) but dont ever seem to do so.

-And lastly some spells are giving the wrong stats when equipped i.e. Feather Storm

Thank You!

**Comment by helixhamin** [comment]
Level 1-54 spells have the correct stats value assigned to them now.

**Comment by whasf** [comment]
Old ticket, please re-look at BLU and see if there are still issues as there has been a lot of changes.
