### ISSUE TITLE
AOE moves crashing clients with full PT

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2303]
Ballad still, also Fafnir Hurricane Wing crashed clients. We were in alliance (with the bug in #2291 active), attempting Fafnir.

See also #2238. May be related to #2291.

Edit: Still happening in vanilla PT, too, at least with ballad.

Revision: 14430e6
Server: Classic

**Comment by xipies** [comment]
Can also cause char in party to crash even if in different zone.

**Comment by Hozu** [comment]
Probably the party status effect packet again... How does it work on retail, wasn't it supposed to only show for whoever you're focus targeting instead of just whoever you're targeting?

**Comment by teschnei** [comment]
No. Has nothing to do with focus target

**Comment by xipies** [comment]
One player on classic is reporting even completing GoV is causing client crashes. He's 6-boxing.

This is now on revision: 26b5e7f

**Comment by Hozu** [comment]
This seems to happen only in a party of 6.

Also I'm wondering about the "custom" statuses (beyond 607 or w/e the number was), or statuses with no icon.

**Comment by teschnei** [comment]
The party effects packet uses the same functions as the char packet (since
the data is the same), so it will get the same icons as you see on your own
character

**Comment by nesstea** [comment]
I just rebuilt last night and I verify that it's still doing it. Protectra, Shellra, anything... crashes people.

**Comment by OtianNgocnion** [comment]
Tested this morning with party of 6. Five in Cape Ter. One in Onzozo. Tried various combat and single target buffs. No crashes. Then tried an aoe buff (bard song) in Cape, which immediately crashed the guy in Onzozo. 

I think this is redundant to what has been noted before, but thought I'd share the test in case it sheds any light.

**Comment by Hozu** [comment]
I have a feeling it's not supposed to be sending the packet to party members that are in a different zone, heh.

**Comment by teschnei** [comment]
With one in a different zone... I can see that being a problem, the effect
packet doesn't skip people outside zone unless they're on another server,
but the party define packets will. I was seeing clients crash even with 6
in the same zone and just casting protectra, though, which I've not yet
found the cause. I'll fix people in other zones getting the info they
shouldn't and see what happens

**Comment by teschnei** [comment]
Yes, that's what I was saying

**Comment by teschnei** [comment]
Okay, made a commit for that, let me know how it works

**Comment by Hozu** [comment]
Tried with 6 people in the party, one member in another zone, 2/6 crashed. Was multiboxing on my own test server but I'm sure it will happen to non-multiboxers too.

I can't tell if the packet was still sent to the 6th person though, but for what it's worth the person in the other zone did not crash.

**Comment by OtianNgocnion** [comment]
This bug is reproducible with all 6 in the same zone. It's really puzzling to me why it would occur with 6 but not 1-5...

**Comment by xipies** [comment]
We attempted Fafnir two nights ago for ~20 minutes with a 5 person PT with ballad being played the entire duration with no crashes.

One of the players on the server who had been getting constant 6 person PT crashes (multiboxing) was able to solidly play with 5 person PT (xp'd several levels that way).

Seems to only be an issue with full PT.

This is still on revision 26b5e7f on classic server.

**Comment by teschnei** [comment]
i need to capture the packet in a party of 6, so most likely it's going to
stay broken until then. if someone can capture the packet (0x76) on a DSP
server in a 6 person party just as the client crashes though, that would
help

**Comment by nesstea** [comment]
@teschnei Can we do this sometime today? I have players that are willing to assist with the test. Any server that built recently can't do anything end-game right now.

**Comment by m241dan** [comment]
Anything? 3 parties of 5 doesn't work for you?

**Comment by teschnei** [comment]
@nesstea you dont need me to capture the packet on a dsp server

**Comment by nesstea** [comment]
@teschnei i dont know how to capture the packets. O.o
