### ISSUE TITLE
hasCompletedMission returning true when it shouldn't.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2339]
Seems to be for CoP missions only, a quick test with a Windurst mission didn't return true when it shouldn't have.

**Comment by teschnei** [comment]
If you have a test case, please let me know what it is so I don't have to
spend time reproducing it

**Comment by Hozu** [comment]
Go to the marble bridge door with a char that doesn't meet the requirements, you'll get the CS for the CoP ring. There are some other things as well, think the Swirling Vortex warps to Lufaise/Misareaux.

**Comment by nesstea** [comment]
Verified. New character can touch that door and get dat ring yo.

**Comment by m241dan** [comment]
had someone on my server as well
