### ISSUE TITLE
All spells from merits don't work

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#2345]
As the title says:
5/5 burst II, can't use Burst II.
5/5 Slow II, can't use slow II.

This occurred after pulling from  most recent DSP, but I'm not seeing any relevant changes?

Hmmph.

**Comment by Hozu** [comment]
You have the spells actually learned yes? There was a thing not too long ago that moved spells from a blob in chars.sql to a table.

**Comment by m241dan** [comment]
Yes, all spells are. Even my gm lost them. I have ToAU enabled so that shouldn't be an issue and I ran the spell python script a while back. But this most recent update that changed spell enabling seems to have borked all merit spells.

**Comment by Hozu** [comment]
Do you get them back via the addspell command if you do like... addspell 207 (that's freeze II).

**Comment by Hozu** [comment]
Ok confirmed that you can re-learn the spells and they'll cast, but, you know, you lost all the expansion spells, which probably includes Carbuncle, which can't be re-learned ever.

**Comment by m241dan** [comment]
Just tested, it did not remain through relog. Q_Q

**Comment by Hozu** [comment]
The spells are still in the char_spells table so they're not lost... just not loading properly.

**Comment by m241dan** [comment]
Yah. Which was a recent change, on how they were loaded.

**Comment by bendangelo** [comment]
Kinda a major bug. I'll look at it.

**Comment by Altreer** [comment]
I can corroborate this. Certain spells appear in char_spells.sql but do not appear in game.

**Comment by Fr0zt** [comment]
This also seems to affect blue magic. All of my blue magic spells are still in the db but will not load in game.
