### ISSUE TITLE
Screen black out for Bastok Mission 8-2 "Enter the Talekeeper"

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2346]
http://ffxiclopedia.wikia.com/wiki/Enter_the_Talekeeper

After killing NMs, heading back to Drake Fang in Zeruhn Mines, and clicking on him causes screen to black out. I had to "blindly" (with the help of mappy) zone myself out into Bastok Mines when the CS started. Received rank up and gil.

**Comment by nesstea** [comment]
TextID shift right?

**Comment by xdemolish** [comment]
assuming something related to the event packet has changed, or we're missing a packet which the client is expecting after event release
