### ISSUE TITLE
Yagudo Abbot in Oztroja uses Benediction

### ISSUE THREAD

**Issue by OtianNgocnion** [DarkstarProject/darkstar#2347]
On repeated kills, the Yagudo Abbots in Oztroja use Benediction. I think this is not retail accurate, but unsure.

**Comment by nesstea** [comment]
This mob indeed has a mobmod main 2hour with the familyID of 360.

The wiki doesn't cover if it has one or not, but here is some ghetto lore about the abbots:
"High-ranking priests in the Yagudo Theomilitary, the Yagudo Abbots are revered as miracle workers."

```
SELECT DISTINCT b.mobname as "Spawn_Mobname", c.`name` as "Pool_Name",a.groupid,a.poolid,c.familyid, d.`modid` as "MOD", d.`value` as "MOD VALUE", d.is_mob_mod as "MOBMOD"
FROM `mob_groups` a 
inner join mob_spawn_points b on b.groupid=a.groupid 
inner join mob_pools c on a.poolid=c.poolid 
right join mob_family_mods d on c.familyid=d.familyid
where a.zoneid=99 and mobname like "%abbot%" order by mobname
```

**Comment by nesstea** [comment]
On another note, don't submit an issue unless you know it is an issue; "unsure" is not helping anyone.

**Comment by OtianNgocnion** [comment]
I couldn't find any evidence that they used Benediction in retail, either on the wiki, or by searching the web for "Yagudo Abbot", Benediction. Given that most (all?) other mobs that use 2hrs are tagged as such, my thought was that it was a bug or mistake. But, my memory of retail Castle Oz isn't exactly fresh. That having been said, I see your point. Thanks for the snippet, btw!

Maybe someone with better retail memories of Oz wants to chime in?

**Comment by teschnei** [comment]
Aren't they NMs in shadowreign oztroja?

**Comment by OtianNgocnion** [comment]
Yeah teschnei, they are. And Sauromuge (S), Garlaige (S) as well. Perhaps the mob_mod Bene from thre Shadowreign mobs of the same name is incorrectly added to the regular Yagudo Abbots?

**Comment by nesstea** [comment]
If that's the case, they would just need a family change to normal Yagudo. I don't know...

**Comment by bendangelo** [comment]
The mob has the NM flag in the db. So we'll have to create a new pool for the regular mob.

**Comment by ZirkSupernova** [comment]
Retail Oztroja Yagudo Abbot don't use benediction.

**Comment by wrenffxi** [comment]
this can be closed 
https://github.com/DarkstarProject/darkstar/commit/1a86ac599931d6e6265ffe44a351701853999f23
