### ISSUE TITLE
Bastok 9-1 "The Salt of the Earth" Plasm NMs do not despawn or head back to spawn point.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2348]
What the title says. I've died 3-70 time on these NMs. I left for 6 hours and came back and they are still in the same place when I deaggro'd them: Immobile, silent, and plotting...

**Comment by nesstea** [comment]
I am guessing the flags aren't set correctly.

**Comment by TeoTwawki** [comment]
Fixed by #5786
