### ISSUE TITLE
Windurst 9-1 Goobbue do not have Item on droplist.

### ISSUE THREAD

**Issue by Djcocha** [DarkstarProject/darkstar#2349]
When trying to do mission 9-1 according to http://ffxiclopedia.wikia.com/wiki/Doll_of_the_Dead after talking to a few NPC you must go to Zi'Tah and collect Goobbue Humus from Goobbue Gardeners but according to https://dspt.info/moblist.php?l=G&mobid=17272927 it is impossible. Not sure if moblist is out of date but I tried killing Goobs for about an hour before deciding to check moblist to no success.

Also, I've heard through the grapevine that Windurst 9-2 is not scripted. If anyone could do anything about that it would be just lovely. ^.^

**Comment by nesstea** [comment]
https://github.com/DarkstarProject/darkstar/pull/2363
