### ISSUE TITLE
Spells going away after Zone

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2359]
I've had several players reach out to me and let me know after using specific spells they learn them, and then the spell goes away on zone. Specifically Tier V, -ja spells, Odin, Alexander (Which I manaully added to people) Stay until zone.  Same with most BLU Spells going away as well.

It might just be a setting I'm missing, I have my server set to ignore limitations for expansions but everything is on Except for ASA, and the other micro expansions.

**Comment by Hozu** [comment]
Probably is the same issue as https://github.com/DarkstarProject/darkstar/issues/2345
