### ISSUE TITLE
Wyvern initial name is incorrect

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2361]
Example: Unlock Dragoon and choose the wyvern name "Max" and end up with "Rover" instead.

The name selection in Norg works properly, and can be used to fix your wyverns name.

**Comment by TeoTwawki** [comment]
The name selection in norg works properly, and can be used to fix you wyverns name.

**Comment by GiggleCait** [comment]
This can be prevented by selecting the name above the current name you want in game.
