### ISSUE TITLE
Involuntary healing

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2367]
Issue 1) When logging out (as a non GM character) with /logout one will log back in in the /heal position, sometimes with the logout counter going at a slower rate. This isn't a terribly serious problem in and of itself but coupled with issue 2 it can be annoying.

Issue 2) whenever healing, if one moves too quickly after standing up they will automatically re-heal, sometimes several times.

The first issue wasn't always a problem, it started on nas server in about march I want to say. The second issue has always been a problem as far as I know. 

I was also reminded about something the other day that I think retail got really wrong and darkstar gets really right: on retail after running you have to "plant your feet" for a moment or the cast will be interrupted, but darkstar seems to handle casting after movement imo the way it should be, and I love it.

**Comment by TeoTwawki** [comment]
> I was also reminded about something the other day that I think retail got really wrong and darkstar gets really right: on retail after running you have to "plant your feet" for a moment or the cast will be interrupted, but darkstar seems to handle casting after movement imo the way it should be, and I love it.

Thats just the joy of not sending our packets clear to japan and back :smile:

**Comment by teschnei** [comment]
Could always add artificial ping for "that retail feel"

**Comment by TeoTwawki** [comment]
:no_entry_sign: nothx Kj

**Comment by Deadwing888** [comment]
I was told by someone who may or may not have known what they were talking about that SE read movement before action in the packet even if it happened slightly after, which is why you get that interrupt even when you know you took your finger off the w to hit the macro in the first place.

**Comment by TeoTwawki** [comment]
SHHH! YOU'LL RUIN IT!

Er, I mean. Nothing to see here Kj!

..In seriousness, I dunno if that's a possibility or not, but it would not surprise me.

**Comment by xipies** [comment]
Issue 1 also #1899.

**Comment by zynjec** [comment]
Unable to repro 1, and 2 is now fixed, so closing.
