### ISSUE TITLE
Jug pets higher level than the master reduces EXP gain

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2369]
Beast Affinity merits are supposed to be able to boost pets to be above the level of the master (news to me), but they're not supposed to reduce EXP gain - only charmed pets above the level of the player are to.

**Comment by bendangelo** [comment]
Pretty easy fix, check out the code in charutils.

**Comment by Hozu** [comment]
Ok I'm pretty sure I know what to do with this, but I have a question - is it only charmed mobs that can reduce EXP gain?

**Comment by Hozu** [comment]
Actually, do charmed mobs that are the highest level entity in the party reduce EXP gain anymore? If they don't, then the change I'd do would be different (ie. remove the pet check entirely vs. applying only if charmed mob).

**Comment by teschnei** [comment]
probably - but nobody actually uses charm anymore so its hard to say

**Comment by teschnei** [comment]
all you have to do is check objtype is TYPE_MOB vs TYPE_PET, though
