### ISSUE TITLE
Enchanted items without full charges can be placed on the AH

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2372]
If you put an item with 0 charges onto the AH (which shouldn't be possible by the way), if you buy it the item will have full charges.

**Comment by teschnei** [comment]
"recharging" is actually what the retail behaviour would be if you could put them up (its stored in the same place as signatures, which as you probably know is reset)

**Comment by Hozu** [comment]
You're right, that's the real issue here. Also, enchanted items with full charges can't be put on the AH (you get the partially charged message).

**Comment by TeoTwawki** [comment]
This is extremely amusing since I'm unable to place fully charged items on the AH when that should be allowed. Someone get the flag check **backwards**?

**Comment by zynjec** [comment]
This was fixed with https://github.com/DarkstarProject/darkstar/pull/4929
