### ISSUE TITLE
"Darkened" synth materials cannot be used (see screenshot)

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2373]
Kind of hard to explain: Trying to synth hemp gorget with grass thread. I can only use the stack of three and not the full stacks. 

Here: http://prntscr.com/8zct77

**Comment by Hozu** [comment]
Did this happen on a success or a break? I know that if you break a Blessed Briault synth, this happens with Galateia every time.

**Comment by teschnei** [comment]
Probably good idea to let the developers know if you found a way to
reproduce it every time

**Comment by Hozu** [comment]
I forgot this issue existed until now, but yeah, break a Blessed Briault synth to see this bug in action - I'm not the only one on the server I play on who ran into this.

**Comment by Fiocitrine** [comment]
I haven't found a way/tested. But it was most likely due to a break as I was skilling up Clothcraft.

**Comment by nesstea** [comment]
It happens when you break and the stack exists after the synth. I am not certain if it happens when you crystal break and/or lose items break.

**Comment by TeoTwawki** [comment]
#463
