### ISSUE TITLE
Dynamis Statues don't have true sight / sound

### ISSUE THREAD

**Issue by bendangelo** [DarkstarProject/darkstar#2388]
Dynamis statues and eyes are not true sight nor true sound. I liked a few of the mobs down below. The stats and eyes are not true sight or sound everything else is.

http://ffxiclopedia.wikia.com/wiki/Avatar_Icon
http://ffxiclopedia.wikia.com/wiki/Vanguard_Eye
http://ffxiclopedia.wikia.com/wiki/Warchief_Tombstone
http://ffxiclopedia.wikia.com/wiki/Adamantking_Image

**Comment by Deadwing888** [comment]
Are you sure? All the ones that I've ever encountered are. Make sure you're not level 99, they will not aggro high level characters.

**Comment by Hozu** [comment]
I thought you did something before that made things true sight/sound? I never noticed this on DSP because the server I play on changed the aggro type in the database directly because we though them being not true aggro before was intentional.

**Comment by bendangelo** [comment]
Someone else posted this, I copied this from an other comment.

**Comment by Deadwing888** [comment]
I suspect this has already been fixed. A spot check on my test server certainly had them aggroing through sneak/invis

**Comment by bendangelo** [comment]
No the issue is they are not supposed to aggro through sneak/invis. I think this still has to be confirmed.

**Comment by teschnei** [comment]
You can't confirm this anymore because nothing is true sight nor sound in
dynamis now

**Comment by Deadwing888** [comment]
In classic dynamis they're supposed to be true sight true sound. Eyes, statues, TE, everything.

It's currently working properly, can someone close the issue?
