### ISSUE TITLE
Possibility to have crafting difficulty fall between crafting tier difficulty ranges

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2391]
In darkstar/src/map/utils/synthutils.cpp (synthutils.calcSynthResult), it looks like difficulties of -10.5, -30.5, and -50.5 can fall between the ranges. Difficulties of +/- .5 could get returned from getSynthDifficulty if craft_direction_matters is enabled.

```
if((synthDiff <= 0) && (synthDiff >= -10))
{
    success -= (double)(PChar->CraftContainer->getType() == ELEMENT_LIGHTNING) * 0.2;
    hqtier = 1;
}
else if((synthDiff <= -11) && (synthDiff >= -30))
    hqtier = 2;
else if((synthDiff <= -31) && (synthDiff >= -50))
    hqtier = 3;
else if(synthDiff <= -51)
    hqtier = 4;
```

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/issues/1357 This was brought up earlier, didn't know it was still a thing.

**Comment by Deadwing888** [comment]
This is still a problem with moon or direction matters enabled, but the server owner has to go out of their way to break it in the config so it can possibly be closed now.
