### ISSUE TITLE
status effects on mobs persisting after death into next respawn

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2402]
I'm dead certain this was fixed before, and now I notice its happening again. You debuff a mob and it dies with the debuff on. Later mob repops and it has that status effect on it already and some time later you see the log message saying "`<mobname>'s <effect> wears off`".

Does retail do this? I do not recall.

**Comment by TeoTwawki** [comment]
Does retail do this? I do not recall.

**Comment by bendangelo** [comment]
Should be an easy fix. I'll look into it.

**Comment by Hozu** [comment]
I believe TP persists through respawns as well. I know for a fact that mobs retain TP when they're in the respawn action state, and I've seen people get hit with instant mobskills... I don't think TP depletes while mobs are idle either, but I can't remember if that should or not.

**Comment by teschnei** [comment]
Status effects: should be wiped on death except for permanent durations I
think. Tp should be reset on spawn. Don't think it depletes while roaming
(example: mobs with regain usually use a skill on engage in bcnms, etc)

**Comment by TeoTwawki** [comment]
>  Don't think it depletes while roaming (example: mobs with regain usually use a skill on engage in bcnms, etc)

Definitely correct. Mobs never lose TP unless they either died or tried to use said TP.
