### ISSUE TITLE
Party Effects don't display sixth party member

### ISSUE THREAD

**Issue by teschnei** [DarkstarProject/darkstar#2415]
Part of the temporary fix to clients crashing with 6 members.

**Comment by m241dan** [comment]
good enough.... just wanted to say thanks for getting 6 member parties back!

**Comment by xdemolish** [comment]
did you fix this in https://github.com/DarkstarProject/darkstar/commit/99aac9343a2751915792b14694ea084aa59b4a58

**Comment by teschnei** [comment]
yes
