### ISSUE TITLE
Killing mobs doing weird things to currencies

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2418]
Think it might be only mobs eligible for G/FoV, but whenever you kill something some of your currencies change drastically. Seems to disappear on zoning. Wonder if it's just a client bug since I don't think some of these are implemented yet.

**Comment by teschnei** [comment]
it's because the currency packet has changed a million times since I
implemented it - everything server side is still okay

**Comment by TeoTwawki** [comment]
Retails currencies menu seems to have settled down now. Somewhere along the lien it became *two* packets and *two* menu entries.

I dumped them both last free period and forgot to share/do anything with it
https://yadi.sk/d/UEcEzBZF3NDmqX
