### ISSUE TITLE
Clothcraft Guild NPC in Windurst menus screwy.

### ISSUE THREAD

**Issue by Djcocha** [DarkstarProject/darkstar#242]
Meririr does not actually buy anything from you when you try to sell (I tried wool thread.), and Kuzah Hpirohpn next to her has nothing in her 'Buy' menu.

**Comment by xdemolish** [comment]
weird, https://github.com/DarkstarProject/darkstar/blob/master/sql/guild_shops.sql#L414 looks fine

time to dump this on... @gedads

**Comment by whasf** [comment]
Old, please re-visit NPC in game. If this still is an issue please re-open.
