### ISSUE TITLE
Issues with ranged weaponskill damage

### ISSUE THREAD

**Issue by whb07** [DarkstarProject/darkstar#2420]
There's an issue with ranged weaponskill damage, its doing too little damage in relation to the mob and then to other weaponskills. For instance, playing around with culverin+1 with its highest base damage and limited ammo barely does any damage above a nq hellfire. Or damage of annihilator both slug shot and coronach on a lvl 62 NM does roughly 540 (coronach) or 650ish (slug shot). NM is a pugil. Every other job does 800+ dmg, and done more than 1.5k dmg on it with a warrior's vorpal or extentator on thf. Last point, on a roc Abraxas, every other DD was doing more damage than my Rng's slug or coronach. Where rng should have the clear advantage here on a bird type mob.

please address the clear watering down of what is supposed to be a heavy hitting DD job.

**Comment by m241dan** [comment]
Well, I'm curious, have you run the math to prove this? Also, what does your WS set look like for this weapon skills? My samurai easily hitting 1.3k sidewinder's in cape terrigan and 1k on birds when it hits. That's with mid-level gear. Seems accurate given my lack of access to ranged attack equipment. Ranged attack and pdif is going to go a lot farther on high ftp WS than str, or WSC.

**Comment by RwNigma** [comment]
Ranged Accuracy isn't calculated correctly according to wiki. Not sure how much of an effect that would be on Ranged Weapon Skills, but I will look into it a little more. Would like to have a more experienced person on this though.

Ranged Accuracy within Battleentity.cpp lines 579 to 585 needs to be looked at. 
WIKI:
Ranged Accuracy = ( 200+ ((Combat Skill-200)*0.9) + 3AGI/4 + (+Ranged accuracy from gear) + (+Ranged accuracy from trait/ability) ) * (1+ (percentage from food effect/100))

Battleentity.cpp:
if (skill_level > 200)
    {
        acc = 200 + (skill_level - 200)*0.9;
    }
    acc += getMod(MOD_RACC);
    acc += battleutils::GetRangedAccuracyBonuses(this);
    acc += AGI() / 2; --This is the blatant difference.

**Comment by m241dan** [comment]
100% of WS accuracy and Dmg is handled Lua side, as far as I know, so I don't know if it matters per se.

**Comment by RwNigma** [comment]
Ranged Attack is also being calculated incorrectly.
WIKI: Ranged Attack = {( 8 + Combat Skill + 3STR/4 + (+ Ranged Attack from gear) + (+attack trait/ability/minuet)) * (1 + (berserk effect + warcry + velocity shot effect + chaos roll effect))} * (1+ percentage increase from food ) 

Battleentity.cpp:
int32 ATT = 8 + GetSkill(skill) + bonusSkill + m_modStat[MOD_RATT] + battleutils::GetRangedAttackBonuses(this) + STR() / 2; --This is blatantly different as well.

**Comment by m241dan** [comment]
Ranged attack being improperly calculated would have a significant impact depedning on how far off it is.

**Comment by m241dan** [comment]
Looking over the code, it would seem th eonly thing that is actually wrong is the STR() / 2 section. Easilly changed to ( 3 * STR() ) / 4.

This will likely go a long way towards making the ranged ws more accurate since they benefit a ton from attack.

**Comment by teschnei** [comment]
It's about 20 attack missing, barely noticeable (though should be fixed, of
course)

**Comment by m241dan** [comment]
20 Attack could easilly put you into the next tier of pdif which would essentially increase damage by 33%

**Comment by teschnei** [comment]
Pretty sure pdif is a piecewise linear function. 30 attack is never going
to increase damage by 30% except in silly extreme conditions (ie. attack
down debuff against a level 10 mob)

**Comment by m241dan** [comment]
I thought it was floored at x1, x2, x3 for ranged attack? I could be wrong.

**Comment by teschnei** [comment]
No, it's a piecewise linear function so attack increases are (mostly) smooth

**Comment by m241dan** [comment]
Ah, well, my mistake then, guess it won't make that huge of a difference! xD

**Comment by whb07** [comment]
just to be clear, i have top tier gear, i have better gear than most. im comparing this to myself and others on my same level. something is clearly wrong with rnged attack when culverin +1 is doing garbage damage. THe whole point of the culverin to have only 12 bullets, stupid high delay, etc was to make up for its obscene damage which isnt there. Or the gun which is meant to deal high damage which wasnt there. like i said other weaponskills do more on nm pugil than coranach. thats not right....

**Comment by teschnei** [comment]
It's pretty hard to quantify anything without knowing what "top tier gear"
is (2005 top tier? 2007? 2015?) or even what level you are (especially
since you mentioned exenterator, a level 96 ws)

**Comment by m241dan** [comment]
There's lots of top tier gear, doesnt mean its the best for each ws. I've already relayed my own experiences and the one annihilator on my server does seemingly appropriate damage weapon skills.

**Comment by Hozu** [comment]
"Coronach used to a real nice WS. it would be a shame if they watered down another relic WS...how dmg are u doing with it on EP stuff yuuna?"

Well yes, it used to be better when it mistakenly had double ranged attack on WS.

I don't know what's going on with your numbers, but I've always got around 1400-1500 Sidewinder on the higher level worms in Zeruhn Mines w/ relic bow and the best available gear on DSP servers at 75 (ie. either AH stuff or obtainable from existing mobs), while eating attack food as /NIN.

**Comment by TeoTwawki** [comment]
ITT: clear watering down not so clear after all.

**Comment by m241dan** [comment]
Well, there is still certainly the issue of getting racc and ratt calculating properly in the main project. But otherwise, certainly not so clear.

**Comment by teschnei** [comment]
One handed weapons have the same problem. And anyways, it avtuslly was 0.5
acc/atk per stat back in that era anyways.

**Comment by m241dan** [comment]
75 cap was .5 for one handers and .75 for two  handers.

**Comment by teschnei** [comment]
Indeed, and 0.5 for ranged weapons too.

**Comment by m241dan** [comment]
Ah, was it .5 for ranged? I never played any ranged classes in retail.

**Comment by teschnei** [comment]
Bg-wiki edit history

**Comment by m241dan** [comment]
Fair enough.

**Comment by whb07** [comment]
why then is my pld doing 500-700 dmg with vorpal, and my ranger the same damage on same mob. again both are equipped fairly the same with best gear possible for slots - heca +1 for pld, kirin osode wyvern helm+1 etc including eating rabbit pies

**Comment by teschnei** [comment]
depending on the mob and your buffs, that sounds about right (assuming we're talking about coronach here)
the only situation where coronach would beat vorpal blade of course is if the RNG has a lot more attack than the PLD
at any rate, without knowing your actual stats and what mob you're hitting it's not really possible to determine anything

**Comment by whb07** [comment]
mob was a bird. also isnt the point of the relic gun to do crazy damage? and what about the culverin+1 ?

**Comment by teschnei** [comment]
No, the point of the relic gun is to do damage from range with low enmity.
Coronach has garbage ftp and is a single hit.  Slug shot does about 66%
more damage than coronach though, which may or may not outperform a
multihit ws depending on other factors

**Comment by whb07** [comment]
-enmity for coronach isnt working yet right?
and what about the damage differences for culverin+1 over nq hellfire,  which is negligible

**Comment by Fr0zt** [comment]
I know the aftermath effect works (-20 enmity) but I am not sure if the 80 CE / 240 VE part works yet.

**Comment by m241dan** [comment]
It's setup in the database with the proper value, whether it actually draws from that on a weaponskill, I'd have to check.

**Comment by Fr0zt** [comment]
I thought enmity was handled in core, in enmity_container. Where are you seeing these values in sql? Unless coronach is handled elsewhere, from looking through enmity_container, I couldn't find anything relating to coronach and it's flat CE/VE values.

**Comment by m241dan** [comment]
Well I'm either making shit up or seeing things because I can't find it now tbo the app for github on the phone jsnt great for searching.

**Comment by Fr0zt** [comment]
Perhaps @teschnei would be able to shed some light on this?

**Comment by teschnei** [comment]
It wouldn't be in the enmity container. I don't know without looking
whether it's implemented or not, though. The enmity is probably calculated
in the ws finish action in the ai

**Comment by whb07** [comment]
Did this ever get looked at as far as the coronach's main draw of having - enmity? 

What about damage of slug/side winder in relation to other jobs ws?
 Here's setup on rng/nin:
Vulcan or francisca/archers
Head- wyvern helm +1
Body -osode
Legs- scouts +1
Feet - Rutter / scouts +1
Rings- triumph  ear: triumph
Hands: seiryu kote
Bow : yoichi arrows: demon/kabura
Back: amemet +1
Waist: scouts 

Warrior: 
Full heca +1, same rings, same earring, hands: alky, back : cerb +1 use jugg/man or jugg/ ridill. Waist: warwolf

Thf:
Same as war, no alky. Mandau

Point being thf and war, rampage/vorpal and dancing edge will outdo sidewinder/slug on sea hog nm pushing past 1.5k dmg. While rng is weak little girl. Again on roc mobs rabbit pies for rng I can't break 1.1k dmg like I hit the ceiling dmg on them even after playing around with the gear and food . But can't do better id imagine on gear.

**Comment by Hozu** [comment]
Gear: http://i.imgur.com/7plrkG7.png
Damage: http://i.imgur.com/1MMPNNP.png
Notes: I gave myself regain and perfect dodge for the purposes of testing.

Can we please close this issue because it's flat out wrong?

**Comment by xdemolish** [comment]
enmity issues can go in a new issue
