### ISSUE TITLE
Cannot synthesize Oil-Soaked Cloth 

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2424]
http://ffxiclopedia.wikia.com/wiki/Square_of_Oil-soaked_Cloth

Could be a Nasomi specific problem, but I doubt it. My test server is fubar at the mo, so I can't find out for sure myself.

Edit: Looked through sql and could not find it there.

**Comment by Fiocitrine** [comment]
Yeah, this recipe is not in the database. I remember this was an issue last year as well ( to finish Gobbiebag quest).

**Comment by RwNigma** [comment]
Ive added a bunch of recipies that weren't within the database. (Including this one.) I will try and figure out github to commit to the database.
