### ISSUE TITLE
synth recipe sql file errors on execution

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#2428]
deleted synth recipe table and executed the synth_recipes.sql file while updating Era, and the sql hit a syntax error during the section that checks the 'order of operations' of the ingredients.  multiple times this happened, starting fresh each time, even going back to older versions.  we hadn't updated our table in a while and had been manually inserting the newest commits.  hopefully this is an error on my part but I was not able to fire the sql off without manually selecting the rest of the file after that section and choosing 'run selected'.  now bracing for the issues it might cause

**Comment by teschnei** [comment]
Can't help you unless you post the error message

**Comment by Hozu** [comment]
I just pulled and ran the synth_recipes.sql file and had no errors. Must be something custom that you have or something.

That error happens when the ingredients is out of order - it's expecting the ingredients to be in ascending order of itemid.

**Comment by Scavenge** [comment]
confusing since i had deleted the table entire, and the error was just a basic "there is an error in your syntax on line 5".  i'll try to get it to happen again on a test server, would the triggers.sql file somehow affect that section of the file?

**Comment by Scavenge** [comment]
im sure that this issue's title is now misleading since it's likely due to something else but here is the error, produced on a seperate db but on the same machine.  

          END IF;

          IF NEW.Ingredient6 > 0 AND NEW.Ingredient5 > NEW.Ingredient6
          THEN
            SIGNAL SQLSTATE VALUE '45000'
            SET MESSAGE_TEXT = '[table:synth_recipes] - `Ingredient5` is larger than Ingredient6';
          END IF;

          IF NEW.Ingredient7 > 0 AND NEW.Ingredient6 > NEW.Ingredient7
          THEN
            SIGNAL SQLSTATE VALUE '45000'
            SET MESSAGE_TEXT = '[table:synth_recipes] - `Ingredient6` is larger than Ingredient7';
          END IF;

          IF NEW.Ingredient8 > 0 AND NEW.Ingredient7 > NEW.Ingredient8
          THEN
            SIGNAL SQLSTATE VALUE '45000'
            SET MESSAGE_TEXT = '[table:synth_recipes] - `Ingredient7` is larger than Ingredient8';
          END IF;
END;
[Msg] Finished - Unsuccessfully
--------------------------------------------------

**Comment by Scavenge** [comment]
im not sure what is going on with the formatting here but hopefully that is still coherent

**Comment by bendangelo** [comment]
Could be the mysql version you're running. What is it?

**Comment by Scavenge** [comment]
ah that could be, looks like we have 5.0.10 i'll look into updating it

**Comment by bendangelo** [comment]
You should update it to latest or at least 5.5

**Comment by Scavenge** [comment]
sorry closing this, it was resolved by updating mysql
