### ISSUE TITLE
Alliance EXP gain only gives 2 EXP per kill

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2429]
This has actually been a bug forever, everywhere when you're in an alliance (except for dynamis zones, weird), anytime you're in an alliance and you gain EXP, you only get 2 points.

**Comment by Fiocitrine** [comment]
Yeah, confirmed on our sever, as well. Although, we only get 1 exp. Maybe dependent on mob level?

**Comment by teschnei** [comment]
is this still a thing after I redid the EXP gain for alliances? I know for sure that a 3 member alliance was working as it should have, but I never tested more than 6.  I don't remember how long ago it was now, but I'd like confirmation.

**Comment by Hozu** [comment]
I'm 99% sure it's still a thing but I'm going to ask around to make sure.

**Comment by Hozu** [comment]
Confirmed still exists. Weird that it doesn't happen inside dynamis.

**Comment by ZirkSupernova** [comment]
From retail experience, I suspect dynamis zones have special flags related to alliance behavior, such that on retail you don't need to actually be in the party/alliance to be able to see/lot things in the treasury, don't need to be in the party/alliance to attack the same mob as someone in a different alliance, etc.

**Comment by ZirkPrime** [comment]
I just did Tenzen's Path in Pso'Xja with 7 member alliance (6+1). Regular mobs in the zone were all giving 2 exp, but the Gargoyle's which spawn upon clicking the doors as part of the quest were giving full exp. So looks like mobs which spawn via an event are immune to this issue.

In Dynamis are stones giving 2 exp per kill whereas the beastmen which spawn upon pulling a stone give full exp?

**Comment by bendangelo** [comment]
This would be easy to write a test for if I can get the test suite finished.

**Comment by Hozu** [comment]
In Dynamis ALL mobs give full EXP. Even though the vast majority of them are not NMs.

**Comment by ZirkPrime** [comment]
Still sorta makes sense, since Dynamis is sort of an instanced zone, mobs don't appear in the zone via conventional methods i.e. repop after death, they have to be scripted to pop on an event such as when the first person enters a new instance of the zone or something along those lines.

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/b438e44f0bb4e0e4b565302b94ae7f0f6b584515/src/map/utils/charutils.cpp#L3308 found the place this happens, but I don't quite know what's being checked there. If you're in an alliance and fighting a normal mob, in certain zones, add calculated exp. Otherwise, add 1 exp. ...why is it doing that? The alliance exp split was done a long time ago, shouldn't that be removed?
