### ISSUE TITLE
Server crashes when dynamis boss is defeated

### ISSUE THREAD

**Issue by Fr0zt** [DarkstarProject/darkstar#2432]
The server will crash immediately following the dynamis boss's defeat. I tested with san d'oria and bastok and both crashed the server once the final boss was defeated. I have nothing custom on my server that pertains to dynamis.

Revision: 8df5ae2
Dump: https://drive.google.com/folderview?id=0Bwo-QJxEqo87TnpSREpxbm44bW8&usp=sharing

**Comment by wrenffxi** [comment]
According to #1370, this issue can be closed.

**Comment by Fr0zt** [comment]
Thanks, I'll close.
