### ISSUE TITLE
Very minor CoP flaw: can get next cs at shattered telepoint of crag you just cleared

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2433]
Title. The CS with Ayama and Cid. That cs should not play until you go to a different shattered tele point.

Probably means yet another player var being set and then cleared, or else changing the PromathiaStatus values, either of which means characters mid mission will get borked again if you want it retail perfect.

(and server ops that forget `@setplayervar` exists will complain)

**Comment by gedads** [comment]
Any idea?
checked the script, you should only be able to get the cs if you beat first promy and have cspromy2 enabled and if one you arrive in mea dem or holla with having in possession one of those which isn't the one of the promyvion

**Comment by TeoTwawki** [comment]
I cleared holla with someone who was having trouble and clicked the shattered telepoint at holla afterward, and got the next cs right there. So if the existing code was intended to restrict that the logic is just plain faulty. Its not a game breaker in any case, just strange.

**Comment by TeoTwawki** [comment]
Closing, someone else can trip it and report it after they figure out how the F it happens. I don't have the time for tracking it down.
