### ISSUE TITLE
Magic Pot mobs are taking 0 magic damage all of the time.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2439]
Nuked a pot that was idle since boot so no magic shield effect, took 0 damage, not no effect. I wonder if a change somewhere made other mobs that are resistant to magic have stronger resists too.

**Comment by teschnei** [comment]
check the console for errors (0 damage is the fallback on errors)

**Comment by Hozu** [comment]
Nothing gets printed to the console despite high level spells doing 0 damage. Strange...

**Comment by Scavenge** [comment]
fprint their stats?

**Comment by Cloudef** [comment]
https://github.com/Cloudef/darkstar/blob/personal/scripts/commands/scan.lua You can also use this (You need to be engaged to enemy).

**Comment by Hozu** [comment]
The problem is that when xdt was refactored to be out of 100 instead of 256, various things were forgotten, like mob mdt% mods. So how should xdt%s be done? I was under the impression that being out of 256 was the way to go because it's more accurate, but it was changed to be out of 100 recently.

**Comment by Hozu** [comment]
This was resolved long ago.
