### ISSUE TITLE
Darkness Named Calls Wrong NPC ID

### ISSUE THREAD

**Issue by Altreer** [DarkstarProject/darkstar#2444]
It seems there is a mislabeling of the npc id for Diabolos in the opening cutscene for Darkness Named. This means either the npc id in npc.sql is incorrect for Diabolos under The Shrouded Maw, or the event is calling the wrong npc for the cutscene. Either way it causes the client to crash.

**Comment by gedads** [comment]
Hi, which area please?
the cs in jeuno?

**Comment by Altreer** [comment]
The opening cut scene to Darkness Named in The Shrouded Maw at the start of the BCNM

**Comment by Hozu** [comment]
Probably related to this one: https://github.com/DarkstarProject/darkstar/issues/2436

**Comment by Altreer** [comment]
I was able to prevent the crash by reverting the npc ids in npc.sql to the previous ones for Diabolos in The Shrouded Maw.
