### ISSUE TITLE
update to version 30151103_3 client crash~

### ISSUE THREAD

**Issue by githubigssan** [DarkstarProject/darkstar#2448]
VS 2015 break point 

FFXiMain.dll

055AA4DD  rep stos    dword ptr es:[edi]  

EAX	00000000	
ECX	3FFFFFFA	
EDX	FFFFFFE8	
EDI	00000000	
ES	002B	

help ...

**Comment by nesstea** [comment]
Nothing to do with us. Reinstall your game. I have the latest version of the game.
What you see there are the contents of registers.

**Comment by githubigssan** [comment]
have use bat fast install

install.reg

[HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS]
[HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\InstallFolder]
[HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\Interface]
[HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\Product]
[HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\SquareEnix]
[HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\SquareEnix\FinalFantasyXI]

=========================================================

install.bat

@Echo off

regedit /s install.reg
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\InstallFolder" /v 1000 /t reg_sz /f /d "%~dp0\"
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\InstallFolder" /v 0001 /t reg_sz /f /d "%~dp0\"
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\InstallFolder" /v 0002 /t reg_sz /f /d "%~dp0\"
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\PlayOnlineUS\InstallFolder" /v 1000 /t reg_sz /f /d "%~dp0\"
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\PlayOnlineUS\InstallFolder" /v 0001 /t reg_sz /f /d "%~dp0\"
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\PlayOnlineUS\InstallFolder" /v 0002 /t reg_sz /f /d "%~dp0\"
regsvr32 /s "FFXi.dll" 
regsvr32 /s "FFXiMain.dll"
regsvr32 /s "FFXiVersions.dll" 
regsvr32 /s "polcore.dll"

**Comment by nesstea** [comment]
Still, not DSP. Just install the game normally.

**Comment by xdemolish** [comment]
create a topic on the forums and discuss there
