### ISSUE TITLE
Mobs spawned in BCNM after it begins do nothing

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2449]
They can't even be interacted with in any way. I guess they're considered outside of the fight. This includes the mystic avatars spawned from chests in Temenos, the mobs spawned by trees in Apollyon SW(?), etc.

**Comment by teschnei** [comment]
You have to add the battlefield effect.  I thought that it should take care of it automatically, but it could be something specific to Limbus (which I will probably not look at, myself)

**Comment by Hozu** [comment]
I think it might be all BCNMs because I know the Fission mobskill wasn't added for whatever reason when the promy boss mobskills were done. If @bendangelo remembers why he didn't add it that'd clear things up.

**Comment by Brierre** [comment]
If you add these mobs to bcnm_battlefield.sql they appear to work fine. I have a crap ton of limbus fixes like this in both Temenos and Apollyon, just need to find some time to put them into my DSP code and push them.

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
