### ISSUE TITLE
Ultima's Equalizer is... something else

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2450]
In the mobskill table and in the monster tp moves doc, Equalizer is listed as 1005. However, when the mob uses it, it calls upon #749 instead.

**Comment by teschnei** [comment]
1005 - 749 = 256

does that help?

**Comment by Hozu** [comment]
I vaguely remember reading something about a 256 offset for CoP era and beyond mobskills... I'll have to look into it and see why specifically Equalizer is messed up.
