### ISSUE TITLE
Casting Utsusemi: Ichi after Ni should require canceling of utsusemi images buff

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2458]
Currently this functions correctly for ninja mains with the 4 shadow Ni.

When subbing Nin the 3 shadow Ni does not require cancellation for the 3 shadow ichi to go off.

Not a huge issue, but it does take a bit of skill out of tanking and lets tanks squeeze about an extra third of a second out of their shadow casts/recasts.

**Comment by R3P0FFXI** [comment]
Ni always overwrote ichi regardless of nin being sub or not. Ichi will not overwrite Ni under any circumstances and should be cancelled

**Comment by Hozu** [comment]
You can cast Ichi with Ni active when /NIN and it'd overwrite. When NIN main, it works properly.

**Comment by Scavenge** [comment]
recently i did notice that nothing seemed to be prevented from overwriting even though i was casting both randomly

**Comment by GiggleCait** [comment]
@R3P0FFXI How did this not make any sense? 

When subbing Nin the 3 shadow Ni does not require cancellation for the 3 shadow ichi to go off.

Lol...

**Comment by wrenffxi** [comment]
Can be closed.  Was fixed by #4792 .
