### ISSUE TITLE
Bst jug pets kill exp

### ISSUE THREAD

**Issue by whb07** [DarkstarProject/darkstar#2461]
I've been away for 3-4 months but now back for about a month, to find that my jug pets kill all exp for myself and party members. Any word on when this will be getting fixed? This seems like an important fix as it's essentially killing a job.

When I say there's an exp penalty it's like 90% or more exp is eaten up by the pet.

**Comment by Hozu** [comment]
Already fixed - please update your server to get that change. https://github.com/DarkstarProject/darkstar/pull/2406

**Comment by teschnei** [comment]
closing as it's been addressed in #2406
