### ISSUE TITLE
Greater Pugils in Qufim affected by Acid Bolt Defense Down take less damage.

### ISSUE THREAD

**Issue by BRFord88** [DarkstarProject/darkstar#2464]
After a Greater Pugil in Qufim Island is effected by an Acid Bolt's Defense Down effect they take about 10% of the normal expected damage.

**Comment by Hozu** [comment]
Is this the case with other mobs as well?

**Comment by BRFord88** [comment]
Other mobs were responding normally to the defense down effect, however it could be with the pugil mobs. I will test further when I get off of work if nobody else has.

**Comment by teschnei** [comment]
requesting an update on this, if possible

**Comment by BRFord88** [comment]
After about 10 trials, it appears to be resolved.
