### ISSUE TITLE
Hunter's Prelude/Archer's Prelude

### ISSUE THREAD

**Issue by RwNigma** [DarkstarProject/darkstar#2484]
I was attempting to code the resist BRD spells and ran into scripts\globals\effects\prelude and noticed that it doesn't have any text other than function calls that don't actually call anything. here is the file for reference:
````
-----------------------------------
--
--
--
-----------------------------------

-----------------------------------
-- onEffectGain Action
-----------------------------------

function onEffectGain(target,effect)
end;

-----------------------------------
-- onEffectTick Action
-----------------------------------

function onEffectTick(target,effect)
end;

-----------------------------------
-- onEffectLose Action
-----------------------------------

function onEffectLose(target,effect)
end;
````

I will also post Madrigal since it's the closest comparitive to Prelude.

````
-----------------------------------
--
--	EFFECT_MADRIGAL
-- getPower returns the TIER (e.g. 1,2,3,4)
-----------------------------------
require("scripts/globals/status");
-----------------------------------
-- onEffectGain Action
-----------------------------------

function onEffectGain(target,effect)
	target:addMod(MOD_ACC, effect:getPower());
end;

-----------------------------------
-- onEffectTick Action
-----------------------------------

function onEffectTick(target,effect)
end;

-----------------------------------
-- onEffectLose Action
-----------------------------------

function onEffectLose(target,effect)
	target:delMod(MOD_ACC, effect:getPower());
end;
````

**Comment by teschnei** [comment]
this isn't really an issue, can you post it on the forums instead?

**Comment by RwNigma** [comment]
If anything its noted that the above spells aren't coded and that Prelude may need to be looked into. Ill post it within Scripting.

**Comment by teschnei** [comment]
I suggest either closing this and opening a new one for Prelude (after verifying that it actually doesn't give ranged accuracy) or just renaming this one to reflect that.

we don't typically keep issues for stuff that isn't implemented yet since we'd just have a million issues hanging around always

**Comment by RwNigma** [comment]
Fair enough. I will check out Prelude here in a minute.

**Comment by Hozu** [comment]
Yeah I tested it and the song did literally nothing so... there's the pull to implement it.

**Comment by RwNigma** [comment]
Thanks Hozu. :)
