### ISSUE TITLE
Windurst 9-2 "Moon Reading" cannot get 1st Heaven's Tower cutscene.

### ISSUE THREAD

**Issue by koverlet** [DarkstarProject/darkstar#2486]
After accepting Windurst mission 9-2 "Moon Reading", the first cutscene is supposed to be found after clicking the Door:Vestal Chamber at the top of Heaven's Tower. Instead of a cutscene, I only receive the message "The door to the Vestal Chambers is locked shut."
This stops the mission from continuing, none of the 3 key items needed are able to be obtained.

**Comment by gedads** [comment]
Moon reading isn't scripted yet because of ajido-marujido is troublesome behavior during the fight

**Comment by zynjec** [comment]
Added with https://github.com/DarkstarProject/darkstar/pull/5158
