### ISSUE TITLE
Changeing jobs in Al Zahbi MH (From DRG)

### ISSUE THREAD

**Issue by Leelink1** [DarkstarProject/darkstar#2492]
If you enter Al Zahbi mog house with your Wyvern out as a DRG he appears inside your Mog House.

If you change job and exit the mog house the server crashes. When you log back in it continues to crash.

**Comment by Hozu** [comment]
On retail, when you change main or sub job, does it always despawn your pet? I think that would be the best way to go about fixing this.

**Comment by Leelink1** [comment]
It does for every other zone. Normally you don't even see your Pet in the moghouse. I guess since Al Zahbi is a Battle zone (due to Besieged) it allows them to appear.

**Comment by teschnei** [comment]
I don't think pets spawn in your mog house either way

**Comment by teschnei** [comment]
at any rate, I think it should be possible to extend the "is pet allowed in this zone" check to check the zoneflag and the moghouse instead of just the zoneflag

**Comment by TeoTwawki** [comment]
Fixed by https://github.com/DarkstarProject/darkstar/commit/55fab7ae1a23207623c07b1a0bfb45130c522197 and we forgot to close
