### ISSUE TITLE
Blaze spikes, the new 60kEXP/HR

### ISSUE THREAD

**Issue by GiggleCait** [DarkstarProject/darkstar#2499]
So the issue here is, lets say I pull a zone on my 75 RDM and want to level my alt, I find a sync around level 10 (with my alt) and pull (with my RDM) a linking type mob (lizards, bats, bunnies, gobs, etc, whatever it may be). I then cast blaze spikes on myself (RDM) and claim on said alternate account, once the mobs die, the alt account receives full exp to include chains etc.

Another issue, if I do die the mobs stay claimed to me even through death, I have tested this on multiple DSP servers and the issue is the same.

**Comment by bendangelo** [comment]
What's the retail behaviour? If a claimed mob hits an other player with spikes mobs give no exp?

**Comment by GiggleCait** [comment]
Correct

**Comment by teschnei** [comment]
More likely just the max attacker level is updated, I think

**Comment by GiggleCait** [comment]
Regardless, if the mobs hit the person with spikes they should then become claimed.

**Comment by Deadwing888** [comment]
Duplicate of issue #2095 I reported several months back

**Comment by GiggleCait** [comment]
Claimed as in the attacker level shouldn't be updated again during fight.

**Comment by Deadwing888** [comment]
I believe it calculates EXP based on the level of the person with blaze spikes it hit. Not 100% on it, but I think if a level 20 mob hit a level 30 who had blaze spikes it would still give a bit of exp to a party of level 15s

**Comment by Novah1** [comment]
If I recall retail behavior correctly, the exp calculation would calculate as if the outside partymember were part of the party for that mob.
