### ISSUE TITLE
Tinnin ZNM all fuqd up: Mixed up TP moves and also too weak

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2502]
Tinnin is supposed to be much harder than he is now. Curse from Nerve Gas should be much stronger. I remember it dropping a PLD to around 50-60% of his max HP. Also, when he uses Nerve Gas he then immediately follows with either Pyric or Polar Bulwark. 

Also Pyric and Polar Bulwark are mixed up. Pyric is supposed to be a Physical shield and Polar is supposed to be a magical shield, These are reversed.

**Comment by Hozu** [comment]
Er, the two shields aren't reversed when I look at the script here...

**Comment by Hozu** [comment]
Also BGwiki as it so it uses Nerve Gas after the bulwark, rather than the bulwark after Nerve Gas...

**Comment by Fiocitrine** [comment]
Yeah, well I knew it was either one or the other after the other. It's been awhile, I just new he used in tandem.
