### ISSUE TITLE
Limbus Black Screens

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#2516]
Tried doing SW Ap. and multiple people with the latest client version get stuck on black screens when trying to climb the floors.

**Comment by Fiocitrine** [comment]
I think it's safe to say: Limbus is fucked. Anyway you look at it.

**Comment by TeoTwawki** [comment]
several other limbus area's have this or other problems rendering them completely unplayable, been that way for over 6 months. I'm looking at rewriting the entire thing to make it easier to maintain white cleaning the utterly useless garbage out of it.

**Comment by nesstea** [comment]
Thank you @TeoTwawki

**Comment by Hozu** [comment]
Probably the same as https://github.com/DarkstarProject/darkstar/issues/2327

**Comment by Fiocitrine** [comment]
I think this can be closed as limbus is being rewritten.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/issues/2327
