### ISSUE TITLE
Ancient Vows Mammets open up with TP moves and are too good at their job.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2518]
I'm posting for an LS member.

Apparently after several attempts at this fight, both kiting and trying to sleep nuke, we've come to the conclusion that this fight is too hard. 

A THF with trotter boots can't outrun the mammets. As far as I know, these guys don't have enhanced movement speed. Also the mammets seem to tear through him rather quickly. 

Another thing, after casting sleepga on the mammets for the first time, they apparently wake up and use Gravity Wheel. These mobs shouldn't have a regain and definitely shouldn't gain 100TP with only one casting of Sleepga. 

If someone could take a look at this and do some tweaking to make this fight more "retail" that would be fantastic. 

Thanks,
Fio

**Comment by whasf** [comment]
What server does your friend play on?

**Comment by Hozu** [comment]
Yeah these definitely have regain when they shouldn't, and tremorous tread is always inflicting stun. As for the movement speed, I don't know what they're supposed to have.

**Comment by Hozu** [comment]
On the other hand, I don't think you were able to sleep nuke these in a 40 cap environment...

**Comment by Hozu** [comment]
Also I noticed the Mammets in 6-4 don't change form, but I'm hesitant to do anything with that because the form changing script specifically sets the dmg value - I have no idea what should be set for the fight that was originally capped at level 60.

**Comment by Fiocitrine** [comment]
Whasf: your server, silly!

Hozu: Thanks for taking a look and fixing it. I think it might have to do with mob pathing that allows the mammets to "follow" the player in a smaller circle instead of directly behind. But, removing regain should definitely fix the TP issue. As far as sleeping them, I figured you could sleep them with decent enough gear. They seem to either half-resist or not resist at all. Either way, kiting them and nuking them down should work. And right now, it's not. Thanks again!

**Comment by Fiocitrine** [comment]
Also, my LS mates told me that the mammets were able to TP them from a decent distance away. Might want to check the speed at which they ready a TP move and also if the TP moves they are using are flagged as ranged. Just a guess.

**Comment by Hozu** [comment]
They don't have fast cast trait in the script, but they're set to cast spells often when in mage form. As for using mobskills from range, if they're within the AoE range of the mobskill, the mob will be eligible to use it. So yeah. But with the regain removed that shouldn't happen quite rarely while being kited due to not gaining tp.

**Comment by Fiocitrine** [comment]
cool thanks a billion

**Comment by Hozu** [comment]
We'd need a retail packet capture to get their proper movespeed btw. I'm pretty sure they're supposed to be default (ie. old player speed) but not sure.
