### ISSUE TITLE
table.getn has been deprecated for a really long time..

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2521]
..[but people kept using it anyway](https://github.com/DarkstarProject/darkstar/search?utf8=%E2%9C%93&q=table.getn). This may to lead to future broken scripts.

This issue is to make it known so people stop using it in new scripts, and to remind myself to swap those out to what we're actually supposed to use in our current lua implementation (unless someone else wants to do it first - have at it).

**Comment by teschnei** [comment]
IIRC its gone in 5.2, but we probably won't be switching to 5.2. Still, not
gonna complain

**Comment by bendangelo** [comment]
What's the new way of doing it?

**Comment by xdemolish** [comment]
#sweg

**Comment by TeoTwawki** [comment]
from 5.0 onward of mainstream lua and the build of luajit we use `#` was introduced as a length operator to replace `table.getn`.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/3a0b9a656648550593d8bb326bb124eae2a7fd04
