### ISSUE TITLE
No way to distinguish between light and dark-based sleeps.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2531]
Repose, Yawn, and Sheep Song are using the same resistance check as Sleep(ga)/2 (MOD_SLEEPRES). Lullaby is using its own calc, MOD_LULLABY. I'm pretty sure that it should be something like MOD_DARKSLEEPRES and MOD_LIGHTSLEEPRES (IIRC there's no sleep that's neither light or dark) and the spells should use the proper resistance value. Or just make light-based sleeps all use MOD_LULLABYRES.

**Comment by Hozu** [comment]
Yeah if there's no sleep that's an element other than light or dark, using light/dark sleep res is the way to go. Things that are vulnerable to lullaby are vulnerable to the light-based sleep spells.

**Comment by teschnei** [comment]
I was under the impression that things that were not vulnerable to dark
based sleep were so because they had high dark res

**Comment by Hozu** [comment]
That's probably the case. I wanted to increase the base dark res of certain mob families (basically the ones in the pull that I gave sleep res to) but the values that are currently set are taken from either wiki.

**Comment by Fiocitrine** [comment]
or dark elementals being resistant to  dark sleep but not to light sleep i.e repose and lullaby

**Comment by TeoTwawki** [comment]
> I was under the impression that things that were not vulnerable to dark based sleep were so because they had high dark res

There are a few mobs that are outright immune (in retail you can tell if it was just super resist or immunity form the message text). But I do not know of any mob that has true immunity to one sleep type and not the other, the only difference in immunity I am aware of is repose - the rest are the super resist variety, where you just are not overcoming that resistance ever.

**Comment by TeoTwawki** [comment]
>  but the values that are currently set are taken from either wiki

I highly suspect we *still* ain't doinitright for resistance checking.

**Comment by Lightningcount** [comment]
Imps in the mire used to be incredibly difficult to sleep with "sleep" spells. (75 cap content) In fact until repose came out only a blu or brd had any reliable chance of sleeping them. Outside of a random lucky sleep from a blm/rdm, ele seal was the only reliable method for sleeping them with the "sleep" family of spells.

**Comment by nesstea** [comment]
Correct. You had bards doing sleeps on imps. You'd only be able to sleep with decent gear at 75 cap like 1/10 times.

**Comment by Hozu** [comment]
I said this wasn't entirely resolved in that commit - Repose/Yawn/Sheep Song are light-based spells but they check the same resistance as dark-based sleeps, meaning that mobs that have increased sleepres are also more resistant to those light-based ones.

**Comment by xdemolish** [comment]
didnt even realise it closed the issue lol
