### ISSUE TITLE
How to build PVP system

### ISSUE THREAD

**Issue by woqunima123** [DarkstarProject/darkstar#2538]
I want to build a so that all the players in each map to PVP, but setpvp in command, but cannot make between players to attack each other, I would like to ask the how to set?

**Comment by mspyerzuka** [comment]
Swim said pvp breaks on combat.

**Comment by woqunima123** [comment]
Please guide me in detail

**Comment by woqunima123** [comment]
I have a other people made all map PVP combat service, I need to send to the mailbox. Help me to study and guide me, thank you

**Comment by whasf** [comment]
This is an area to report bugs for the DarkStar project, not to request help with server modifications. Please post this on the forums or some other location.
