### ISSUE TITLE
Command @setpvp can't Pvp combat

### ISSUE THREAD

**Issue by woqunima123** [DarkstarProject/darkstar#2539]
Order entry into force player can't attack trag

**Comment by woqunima123** [comment]
---------------------------------------------------------------------------------------------------
-- func: setpvp
-- auth: Lautan
-- desc: Sets a players pvp flag.
---------------------------------------------------------------------------------------------------

cmdprops =
{
    permission = 1,
    parameters = "s"
};

function onTrigger(player, target)
	local value = 1;
    if (target == nil) then
        player:PrintToPlayer("You must enter a valid target name.");
        return;
    end
    
    local targ = GetPlayerByName( target );
    if (targ ~= nil) then
        targ:setFlag( value );
		player:setFlag( value );
    else
        player:PrintToPlayer( string.format( "Player named '%s' not found!", target ) );
    end

**Comment by teschnei** [comment]
setpvp was removed years ago because it was deprecated.

Please don't open issues for out of date issues
