### ISSUE TITLE
mercenary task cannot be completed BUG

### ISSUE THREAD

**Issue by woqunima123** [DarkstarProject/darkstar#2540]
mercenary task cannot be completed BUG。

**Comment by Fiocitrine** [comment]
This seems rather vague in description. What is this bug doing and what may or may not be causing this bug?

**Comment by woqunima123** [comment]
Mercenary task, can not be completed, so that I can not get NPC to help me fight

**Comment by armouredking** [comment]
Are you referring to the Adventuring Fellow / Trust questlines? Pretty sure none of that has been coded.

**Comment by woqunima123** [comment]
yes!  Signal Pearl can’t use!

**Comment by teschnei** [comment]
Maybe it'll be done in a year or two..

**Comment by Fiocitrine** [comment]
Yeah, I think this issue can be closed for now.
