### ISSUE TITLE
Seeing Spots quest rewards is incorrect. 

### ISSUE THREAD

**Issue by Lightningcount** [DarkstarProject/darkstar#2541]
The seeing spots quest reward seems to be incorrectly coded to return a larger amount of gil for the first turn in and a smaller amount of subsequential turn ins. 

https://github.com/DarkstarProject/darkstar/blob/28a96bcd126a3a45adef3a0291e37c651357a9cf/scripts/zones/Southern_San_dOria_%5BS%5D/npcs/Wyatt.lua

There is no greater and lesser rewards for this quest in retail. 

http://ffxiclopedia.wikia.com/wiki/Seeing_Spots    The current wiki page for seeing spots. 

http://ffxiclopedia.wikia.com/wiki/Seeing_Spots?oldid=380426    And an old id for the seeing posts page for reference. It does not appear that at any point in time that this quest would give differing amounts of gil.

**Comment by Fiocitrine** [comment]
I'm guessing on line 67 the 1500 needs to be changed to 3000. I don't have a server to test this out.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/pull/2542
