### ISSUE TITLE
Client Crashes > COP Mission 6-4 "One to Be Feared"

### ISSUE THREAD

**Issue by Arthurdales** [DarkstarProject/darkstar#2544]
Hello -

I'm Foxmulder and play on classic Darkstar server. My client is crashing after entering the COP 6-4 mission "One to Be Feared" armada airship fight against the 5 mammets, ultima, and omega.  On my first attempt I was able to beat the mammets, but when i clicked on the airship door to advance to the next armada ship to face Ultima, thats when i crashed. One my second attempt i crashed immediately upon transporting to the mammets airship. Any ideas what is causing these client crashes to occur?

**Comment by Fiocitrine** [comment]
I can confirm this. A LS mate and I multi-boxed this fight and one of his DC'd and one of mine DC'd leaving us with 4 characters at the end. It tends to happen when you click on the door to zone into the next fight. It happened after the Mammet fight going into omega and after Omega going into Ultima. ALSO the bug where Ultima and Omega immediately begin attacking on zone in is still present. Sort your shit out Airship!

**Comment by zynjec** [comment]
Unable to repro on master, open another issue if you're still having this issue.
