### ISSUE TITLE
Jeuno Area Questions

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2548]
So leveling a new character up and noticing the odd behaviours. Not sure if it's just because things are unimplemented / automatically implemented or what.

Gobbiebags and extra packs / bags: For starters, as a new character I already have a mob sack. Which should be something one purchases, IIRC. Second, it upgrades the sack with the gobbiebag quest, I don't have to talk to an Artisan Moogle separately to get the sack to upgrade slots which isn't retail behaviour.

NPC walking: I noticed the NPCs walking 'weird' and went looking, noted the paths are... complex. Especially Navisse. Her's looks like some odd form of stutterstep currently. Red Ghost seems more 'natural' but still has odd pauses. I don't think it matters, but just in case it does I _do not_ have walking speed mods. Is this because of navmesh, old code that hasn't been looked at in a while, or something else?

**Comment by TeoTwawki** [comment]
Sorry nobody ever answered, but closing because all of these are either already described more detailed in other issues or are just settings related
