### ISSUE TITLE
Guddal non-responsive for Kazham Airship Pass quest.

### ISSUE THREAD

**Issue by Djcocha** [DarkstarProject/darkstar#2550]
Just collected keys with a friend on Oldschool server, Guddal did not respond when attempted to do quest, and now cannot get airship pass.

**Comment by whasf** [comment]
The NPC doesn't accept the trade? Let me know when you're online so we can troubleshoot.

**Comment by Djcocha** [comment]
Sorry I am relaying all of this via Willam(artist formerly known as Anthem), he just recently updated to start playing again like within the past few days so his /ver should be new, and after I saw your response to this i asked him:
 "yo when you were tryina talk to guddal he didnt respond at all when talking before tryina trade right?"
"yeah he did nothing with both talk and trade, hes fckd, actually everyone in that room didnt respond at all."

**Comment by zynjec** [comment]
Seems to be working fine on master.
