### ISSUE TITLE
AOE WS no longer apply damage to multiple mobs

### ISSUE THREAD

**Issue by lichtl** [DarkstarProject/darkstar#2551]
Hi,

just compiled the latest merge and noticed that AOE WS no longer seems to be able to kill multiple mobs the same time (using @godmode in Aery). It seem the damage is applied to all mobs but after the WS they still have 100%
![ffxi_2016 01 04_00 58 56](https://cloud.githubusercontent.com/assets/1228155/12081601/9bdab458-b27e-11e5-920c-0c656c3531f7.jpg)

**Comment by teschnei** [comment]
f949d2a6418f7ad57a2e9ff696bdc7ba2715fa7c
