### ISSUE TITLE
Mobs casting benefitial spells on player

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#2559]
E.g. In palborough mines the Amethyst Quadav cast protect on the player while engaged.

Also when mage-type of mobs aggro/link they start to cast a spell just to interrupt their spellcasting by running torwards player.

**Comment by Fiocitrine** [comment]
I'm not saying this isn't a legitimate issue but, I've never seen this behaviour. Is this with a fresh server build or a custom one?

**Comment by teschnei** [comment]
it's probably on master, which you do not have yet on old school

**Comment by teschnei** [comment]
32a578ebb419f695b97d3b018ff575a228df7ece

(commit message is wrong, but it should have fixed this)
