### ISSUE TITLE
Monster Spawn Times

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2570]
So I've upgraded to build 6f2ed4 and weird stuff is going on in Qufim. I've been playing for 3 ingame days now and there are light and lightning elementals up at the same time, it's 12noon and there are banshees and wights up... I saw some commit changes about elementals but regular mobs seem to be not following spawn times either.

**Comment by teschnei** [comment]
e380e9a54f0c00ccf1f3c1c150ec25663a7f4771

**Comment by teschnei** [comment]
Should have fixed elementals for sure.  Reopen if you still see undead up

**Comment by Bizzle-Dapp** [comment]
Wight spotted in Rolanberry Fields - reopening for this reason.

**Comment by TeoTwawki** [comment]
@Bizzle-Dapp actually..we should move it to a new issue so its not 60 pages back.

**Comment by Bizzle-Dapp** [comment]
I'll submit a new issue if you wish to close this again @TeoTwawki
