### ISSUE TITLE
Weapon skill chain timers

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2574]
It has been a loooooong time since Retail for me so I don't know if this changed and I'm just way outdated.

IIRC, in FFXI, you can't weaponskill unless you're engaged to a target. I can however use a weaponskill without being engaged. If I attempt to do it from the command menu, I cannot - the weapon skills are grayed out ( as would be expected ). However, if I instead do something like

```
/ws "Fast Blade" <t>
```

I am able to use my weaponskill without being engaged. Since I usually use macros for weaponskills, I didn't notice until I thought about it that the weaponskills should only be able to be used when engaged.

As for limit breaks, I'm able to self skillchain. I really shouldn't be able to self skillchain as a lvl 25. I use an ability at 122711 ( by ingame time stamp ) and waited a reeeeeaaaaalllly long time letting myself get hit upon and not engaging ( since I can use ws without engage ) and at 122819 I use my next ws and... get a combo. I don't know what the time limit is supposed to be but this seems way too long.

**Comment by teschnei** [comment]
If you're using gearswap or ashitacast or any addon that turns your commands into packets circumventing the game command handler, that is exactly how it works on retail.

**Comment by armouredking** [comment]
I guess it's GearSwap doing it then. I didn't expect it to work on the FFXI command. AFAIK /ws was from retail, where /command is the GS way of doing things faster in a macro ( because like //cure doesn't work but you could use /command cure from a macro ).

**Comment by teschnei** [comment]
GearSwap will intercept your commands in order to do its stuff properly (ie. it must change your equipment before you start your action, and change your equipment again immediately after - and the only way to do this is by stealing your command and inserting it into the packet buffer itself)
