### ISSUE TITLE
Items Cannot be Triggered

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2575]
Tried to use my Emperor Band and my Homing Ring but received the unhelpful "Unable to use item." message. Nothing in server logs. Both have charges.

When I used the Homing Ring, even though I got "Unable to use item." message in display log I saw the "Casting Time" popup window appear and go from 0->100%. Of course, nothing happened when it hit 100, but it shouldn't have done that at all, right? I mean if I was unable to use it?

Also, unsure if this is retail or not: I can't use the items at all ( appear greyed out ) from my Mog Wardrobe, they have to be in inventory. Tried to lookup on wikia but didn't see any warnings about not being able to use items in wardrobe instead of inventory.

**Comment by teschnei** [comment]
Pretty sure you have to use a /item macro (or /use, I forget the syntax) to
use a wardrobe item in retail. Don't know if it works here or not

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/ed8b44a493436fec42b1c1848f9414d697c1bb09
