### ISSUE TITLE
Switching targets on death results in being unable to attack again without zone or logout

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2576]
I've been able to make this happen a few times now so I feel comfortable noting it. Attack two or more mobs. Use a weaponskill or just hit and while the mob you just killed is in the process of falling to the ground ( hp zero but still targetted checks not yet complete to recognise mob is dead ), use switch target and select the next mob nearest you ( but not necessarily in front of you, the game will keep you in attack mode automatically usually if it is negating the need to do so ).

What should happen: you select the next mob and stay in attack mode provided it is in range.
What happens: the mob is selected, but you leave attack mode. And you can't go back into it unless you zone or logout. No error messages, no warnings about you have to wait longer... just nothing. Clicking the attack button does nothing but beep.

I can at least kill the mobs using weaponskills off of tp gained from getting hit, but I can't attack so I usually zone out / logout to fix it. Going to just stop using switch target for now.

**Comment by teschnei** [comment]
I can't reproduce this.  Can you tell me if it still happens after 88dad24?

**Comment by armouredking** [comment]
It does not appear to be happening any more after 88dad24.

**Comment by armouredking** [comment]
Hm, seems I spoke too soon on this. It's still happening but it's a lot rarer. The behaviour is usually proceeded by oddball stuff happening but not always.

So. Normally, you bring up a query to select a target. That's a golden arrow. The arrows stay gold for the most part, but a blue arrow appears on top when you select target while already fighting another mob. On the rare occasion, this arrow is red for me. If the arrow is red, it's guaranteed that the OP actions will occur. However, I still occasionally get this on a blue arrow.

Seems to be really random ( I can't narrow it down more than *right around mob death* as a time frame, and it's not perfect ), like the port-after-you're-dead issue that still remains. I've unloaded every Windower mod I can ( luacore won't unload ) to make sure it's not related to that as best I can.

**Comment by teschnei** [comment]
The color of the arrow is the range indicator. You're switching to targets
that are far away then?

**Comment by armouredking** [comment]
I suppose. Usually it's when I'm linking them to get a chain going. I'll have to see if I can make it happen with mobs far away.

**Comment by armouredking** [comment]
Yeah. Definitely on red arrow, tried in Crawler's Nest with Death Jackets on opposite sides of an entry room. I got the "You must wait longer to perform that action." as one DJ died and the other DJ was coming towards me. After that I'm unable to do anything with attacks. Hit attack and it beeps with command menu interaction but I don't pull out weapon. Blue arrow is kinda spotty, can't make it happen every time.
