### ISSUE TITLE
Additional Effect Ammo is Broken

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2578]
As stated. Ammo of any sort with an additional affect _does not_ decrement on use, _nor_ apply it's additional affect. It _does_ still do damage.

**Comment by teschnei** [comment]
Additional effects should be working now.  Ammo isn't being consumed because of ed8b44a493436fec42b1c1848f9414d697c1bb09 (item is locked), so I'll let demolish fix that one :)

**Comment by armouredking** [comment]
They aren't working still. On latest build as of post.

**Comment by teschnei** [comment]
Which ammo? The majority aren't scripted I think

**Comment by armouredking** [comment]
Blood bolts, like stated. They are definitely scripted ( or at least they have it in the items container ). My modified ones aren't working either. I see scripts in /scripts/global/items for acid bolt, bloody bolt, and kabura arrows... But they're not procing.

**Comment by teschnei** [comment]
Okay, I'll take a look tonight. Can you reopen this issue if you did not
already?

**Comment by armouredking** [comment]
Unfortunately it won't let me. All I can appear to do is edit the title and comment, there is no button to reopen it like there was for #2576 when I reopened it.

**Comment by armouredking** [comment]
Just out of curiosity this doesn't fix weapons right? Like for example Acid Claws and Acid Dagger have scripts that should occasionally proc on hit but don't appear to do so. Your comment only says ranged / weaponskills so I'm wondering if that's limited only to that and not weapons too?

**Comment by teschnei** [comment]
they should have been fixed the first time i closed it

**Comment by armouredking** [comment]
K. Was just checking.
