### ISSUE TITLE
Items are not Used on Use

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2579]
In testing of #2578 I bought a Bloody Bolt Quiver (1) from the AH. I only needed to do a dozen or so shots to confirm it after all.

Later I noticed I still had the quiver. Now I'm sitting here filling up my inventory with stacks of bloody bolts from a single quiver. It never runs out... Bluffnix must have gotten ahold of the code. Not sure if related to fix from #2577 or not.

**Comment by armouredking** [comment]
On the plus side, in #2577 the Outpost Ring I used _did_ use a charge. It's currently counting down and at 29/30, so maybe it's just 1 use stuff? I know some 1 use items are infinite ( like teleport staves ) but maybe that got overlapped into all items?

**Comment by teschnei** [comment]
I'm sure this is fixed in #2580, but you (or me) can reopen it if it isn't (I'll try to remember to test it when I get home from work if you don't before I do)

**Comment by armouredking** [comment]
No this is good now. I bought another quiver and it went away after usage. Same thing with #2573 - it's working ( AFAICT ). No need to reopen.
