### ISSUE TITLE
Time Limits on Spells

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2582]
![timers](https://cloud.githubusercontent.com/assets/16038428/12211353/885a9784-b61d-11e5-883e-18405d1cb1f2.JPG)

So yeah. Picture kinda says it all. The spells don't wear off. This might be related to #2494 Signet, but I'm pretty sure I've seen Signet wear off at least once. _I think_. What I do know that _will_ wear off is the custom effects I've coded in myself ( I added some aftermath and magic shield to special weaponskills you can't normally obtain like uriel blade and attached them to the judge's weapons; they last a minute ish and 10secs ish varying up with TP ).

They _do_ wearoff when I change jobs in mog house.

**Comment by teschnei** [comment]
is this before or after 6db3a727c6be408ade8f498d8efc9faf61b5dab5? it appears fixed on my end

**Comment by armouredking** [comment]
Stuff appears fixed after latest commit.
