### ISSUE TITLE
Aftermath is Invincible

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2585]
So, this was working previously. Now aftermath never goes away. Even on job change. I've not made any changes to the scripts regarding it; it should die after 60ish seconds ( depending on TP ). It's been on since I logged in.

**Comment by teschnei** [comment]
before or after 4f36e9451fc54788156a2cd3a76ecb7297911f15?

**Comment by armouredking** [comment]
After. Regen and Refresh are working and dying in time. Blaze Spikes also died at the set interval. My magic shield effect tied to the weaponskill also died. But aftermath will not die.

**Comment by armouredking** [comment]
So I rebuilt the server to get to d0a76aefbcad0e7e07c598a5e908875fc080d24b and after a server unload / rebuild / load aftermath is still present.  So far for 3 minutes.

**Comment by teschnei** [comment]
which weapon? you said duration varies on TP so I assume a relic weapon?

**Comment by armouredking** [comment]
Since it's for testing it's the judges weapon. I've altered the script to use the relic weapon stuff. It looks like this:
```
    if (damage > 0) then
        local amDuration = 60 * math.floor(player:getTP()/100);
        player:addStatusEffect(EFFECT_AFTERMATH, 50, 0, amDuration, 0, 12);
    end	
```

They were working before - aftermath was one of the only ones that would go away. Now it is the only one staying forever heh.

**Comment by teschnei** [comment]
hmm, I tested with yoichi and namas and it wore off after 60s (3000 tp)
can you print your tp?

**Comment by armouredking** [comment]
Print it how?

**Comment by teschnei** [comment]
```
    if (damage > 0) then
        local amDuration = 60 * math.floor(player:getTP()/100);
        print(player:getTP())
        player:addStatusEffect(EFFECT_AFTERMATH, 50, 0, amDuration, 0, 12);
    end 
```

**Comment by armouredking** [comment]
Just out of curiosity was that code supposed to have a semicolon on it? It's not printing anything to the log or to the chat.

**Comment by teschnei** [comment]
nah, semicolons don't matter in lua

did you restart the server? depending on what file its in

**Comment by armouredking** [comment]
It seems to matter. Added the semicolon and now they're showing up. So logs:

[08/Jan] [22:12:11][LUA Script] 115.09999847412
[08/Jan] [22:12:49][LUA Script] 113.59999847412

For TP. Thing is... all of a sudden this isn't happening anymore. Aftermath is dying at 60 secs like it should. It went forever and couldn't get it to quit, even with cancel.

I haven't restarted server or changed anything except from adding the printTP line which I doubt had any affect. I know from testing that you can change any of these particular lua files ( weapon skills, item files ) without reseting the server - they get called every time so like if I goon up a weapon skill because of a bad character I change it and perform another WS and it'll work. Good for figuring out how to balance custom changes on the fly without using a GM account.

Maybe it was just bad SQL leftover from before? Is that possible? Like a ghost from when the timers weren't working? I dunno, I've done another couple WS and they're all printing TP to server logs and aftermath is _now_ wearing off properly. Dunno why it didn't want to die before. I'll close this for now.

**Comment by teschnei** [comment]
could have had a super long duration aftermath left in your saved effects from the db, that's the only thing I can think of
