### ISSUE TITLE
some char flags not updating normally

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#2591]
Noticed it before airewrite became master so likely exists on both master and stable branches right now. wallhack flag will take effect after zoning instead of immediately. `@wallhack` and `/mentor` are busted, I dunno what else. I think mentor has something else broken just in master because it isn't taking effect after zoning either.

I noticed wallhack misbehaving shortly after this change https://github.com/DarkstarProject/darkstar/commit/d54ba36afe9e3195f97b8096e3f06115130390ca

**Comment by teschnei** [comment]
I can't seem to reproduce this. wallhack takes effect immediately on master

**Comment by TeoTwawki** [comment]
Odd, I was just on last night and had to zone before it would notice.

**Comment by TeoTwawki** [comment]
I'm not far behind latest commit either.

**Comment by teschnei** [comment]
Do you have "isGMHidden" toggled on?

**Comment by TeoTwawki** [comment]
yes and didn't realize it. I just tested and that is the circumstance that was missing. Toggle `@hide` back off and everything goes back to normal.

**Comment by teschnei** [comment]
I happened to be looking at that code last night and realised that gm
hidden would suppress updates to yourself. Should fix it tonight when I
finish up the player charm AI :)

**Comment by nesstea** [comment]
yay for kj

**Comment by teschnei** [comment]
fixed in fe3c3e6
