### ISSUE TITLE
Guard skill increases from lower level mobs

### ISSUE THREAD

**Issue by Biogreg82** [DarkstarProject/darkstar#2593]
I am a lvl 45 mnk with  guard skill and I am still getting guard skill from lvl 20 mobs.

**Comment by bendangelo** [comment]
Thought skilling up was based on your current guard skill not your level? If you're guard skill is zero you could skill up on a level 1 mob.

**Comment by Biogreg82** [comment]
My mistake my guard skill is at 130

**Comment by FrankWHansen** [comment]
Parrying is the same way. I capped parrying skill as THF 75 on farming lower level mobs (carpenter's landing level mobs).
