### ISSUE TITLE
Abilities that consume ammo do not

### ISSUE THREAD

**Issue by teschnei** [DarkstarProject/darkstar#2600]
Call beast, repair, etc.

**Comment by teschnei** [comment]
there's a commented out block in CCharEntity::OnAbility that used to handle that, which should be moved to scripts (and it'd be a simple binding.. consume item in some slot)

**Comment by teschnei** [comment]
Call Beast, Angon, Reward and Repair consume ammo now.

Corsair shots don't consume the cards, still

**Comment by zynjec** [comment]
All of these seem to consume their appropriate items now, closing.
