### ISSUE TITLE
Low Level Regime not working

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2604]
The settings.lua setting doesn't appear to track kills when turned on to ignore exp gain/mob level and still give credit for death.

**Comment by Fiocitrine** [comment]
We are having an issue with this as well on Old school.

**Comment by tagban** [comment]
The default setting would be that you have to be able to get EXP to use field manuals, so I'd imagine Old School is set to that normally, however the setting that I adjusted didn't appear to actually allow anyone to get credit if they don't get exp for the kills. And they should be in my case.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/b2cf6e6cad6b61fde89f894eab570d380a6c2265#diff-936b9acec1fdfe8a36c42f87bedfcf93 changed how some of this worked, give us a new issue if its still broken
