### ISSUE TITLE
Player Charm has no AI

### ISSUE THREAD

**Issue by teschnei** [DarkstarProject/darkstar#2610]
CPlayerCharmController exists, but doesn't have any functionality yet (everything needed probably goes under Tick, just to follow master and engage when master does, and move into attack range while engaged)

**Comment by Deadwing888** [comment]
Additionally (unless it's been recently fixed) a player who dies while charmed will crash the server.

**Comment by teschnei** [comment]
If that's older than a week, it's probably been fixed
