### ISSUE TITLE
Desynthesis

### ISSUE THREAD

**Issue by GiggleCait** [DarkstarProject/darkstar#2614]
I've noticed there are quite a few items that cannot be desynthed on DS servers, where would we start with listing everything that is not desynthable? Or shall we just make =/= issues threads- per synth?

**Comment by xdemolish** [comment]
create a forum post and leave a comment on this issue every week or so if there's been any changes to the list on the forums

**Comment by TeoTwawki** [comment]
Desynths are just a recipe table entry like regular synths. To fix it they just need added. If you make a list on the forum and update it when the recipes get added, someone is bound to make it happen. In fact I think I have just the minion for that...

**Comment by teschnei** [comment]
We should fix the differentiation between normal and desynths first, if we
haven't already

**Comment by TeoTwawki** [comment]
True..
The flag is already in the sql table, I think we just haven't been doing anything with it. Shouldn't be that hard to hammer out the rules just hasn't been anybodies priority. If nothing else we can put the rows in commented out so servers can decide to enable those by commenting them.

**Comment by teschnei** [comment]
Just want to have it there before we start adding a million desynths..
Would make fixing it later more annoying

**Comment by TeoTwawki** [comment]
How so, am I missing something? There wouldn't be any schema change needed afaik and I can't think of what else would be an issue so I was thinking that at worst some server operator uncomments the lines and then complains that desynthing is "to easy".

**Comment by teschnei** [comment]
If we didn't do anything now, I mean

**Comment by GiggleCait** [comment]
Cool, Bug forum page I assume.
