### ISSUE TITLE
Jump and High Jump Deal No Damage

### ISSUE THREAD

**Issue by Altreer** [DarkstarProject/darkstar#2616]
Not sure what could possibly be the cause, but Jump and High Jump do no damage, do not claim a mob when used, and in the message box it states '<character> uses Arcane Circle' and '<character uses Last Resort' respectively. When using Arcane Circle no message appears.

![ivaubiont_2016 01 13_081710](https://cloud.githubusercontent.com/assets/11806075/12295338/8469e4d6-b9ce-11e5-84fe-e73104ac0ab3.png)

**Comment by GiggleCait** [comment]
Works properly on my end, this may be a an issue on your specific server.

**Comment by teschnei** [comment]
https://github.com/DarkstarProject/darkstar/issues/2590
