### ISSUE TITLE
UI / Chat Notices

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#2617]
So, question: I seem to remember in retail that status effects in your bar had priorities about where they were placed. Like, signet / sanction would always be far right, protect / shell would always be far left. If they got knocked off / wore off and you recast, they would pop up where they were before. On Darkstar they just get tacked on to the right. Am I not remembering that right?

Not questions:
- [ ] Shield Bash calls itself "Astral Flow" in chat log.
- [ ] Sentinel does not display in chat log. The animation goes off and the effect is applied, but the chat log does not say "[player] used Sentinel."
- [ ] Notorious Monsters should not have "The" in front of their names. Fought Simurgh earlier and it was "the Simurgh" this and that.

Not sure what other things might exist. Feel free to tack on more; I've only unlocked PLD / BST and have played on the original 6 jobs as well so I'm probably missing a few that also are wrong.

**Comment by Hozu** [comment]
Latter is a nameflag thing set in mob_pools.sql (flag 0x20 removes the leading "The").

Status effect icons do have a specific hierarchy that DSP does not have implemented - it's actually important for Empathy, which currently does not transfer buffs over.

**Comment by tagban** [comment]
In chat log NMs do have ' the' infront of them in retail. Or at least did a few years ago.

**Comment by teschnei** [comment]
it depends on the NM

**Comment by armouredking** [comment]
I'm not sure how many have 'the' in front of them in that case. A quick Google search for videos of various NMs ( Simurgh included ) show quite a few not to have 'the' in front of it. I'm definitely more used to not seeing 'the', but I won't claim to having fought every NM in the game either.

**Comment by Fiocitrine** [comment]
Another ability that doesn't show in chat log is Apogee.

**Comment by teschnei** [comment]
First one's fixed, but I'm going to close this because it's 3 completely unrelated issues and they should really be in their own issues
