### ISSUE TITLE
All Raise spells (magic and instant scrolls) cause instant Home Point

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2626]
When the player has Raise cast on them in anyway, on selecting to be raised, it causes them to be instantly home pointed. This has been tested with both spells and the instant scrolls.

**Comment by Arthurdales** [comment]
To add to what Fio is saying, when raise is cast it prompts the player (not 100% of the time) to raise up. When player selects yes the player will lose experience points as if dieing all over again AND will stay dead.

**Comment by teschnei** [comment]
09b40baa283f5ecac164fd3e3fcc239a6bc901c8
