### ISSUE TITLE
Phuabo, Hpemde, Yovra issues

### ISSUE THREAD

**Issue by teschnei** [DarkstarProject/darkstar#2631]
They should have onMobDisengage to set their name back to hidden, untargetable and in their hidden animation.  Also, whenever they change animation, they should wait for ~2 seconds before continuing what they were doing (ie. mob:wait(2000))

**Comment by xdemolish** [comment]
mob:wait(2000) adds another state so the stack never empties on disengage (prolly despawning too)

**Comment by xdemolish** [comment]
``` 
while (!m_stateStack.empty() && (top = m_stateStack.top().get())->DoUpdate(_tick))
    {
        if (top == GetCurrentState())
        {
            // cleanup calls onMobDisengage/onMobDeath 
            m_stateStack.top()->Cleanup(_tick);
            // mob:wait(2000) adds interrupt state to stack which is now at top of stack
            m_stateStack.pop(); // wait state is now top of stack and gets pop'd, resulting in infinite loop as disengage/death state is now back at top of stack
            // repeat 5evar
        }
    }
```

**Comment by xdemolish** [comment]
possible solution would be to check after cleanup whether the current state is still top of stack before removing (not that ive bothered to think of what could happen as a result of that)

**Comment by teschnei** [comment]
I see I see. Might have to pop it before cleanup (which means taking a
copy, but there are worse things that can happen)
