### ISSUE TITLE
Attack of the Goldfish!!!

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2636]
Apparently, goldfish are on the prowl. Target: Tarutaru Objective: Attack when we are not supposed to.

**Comment by TeoTwawki** [comment]
Those fish are suicidal and want to be eaten see, so they are just trying to get some tartar sauce.
http://bilingualgamer.net/blog/2009/01/17/ffxi-in-real-life-part-6-tarutaru-salad/

**Comment by TeoTwawki** [comment]
Alternate joke: taru so tasty, even the fish eat you.
