### ISSUE TITLE
WS missing all the time

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2642]
Several players after updating server informed me that ws are now missing. I'm guessing after this commit. https://github.com/DarkstarProject/darkstar/commit/daa1d4c6eeda59b634baf40c66d66ca6c75098dc

**Comment by teschnei** [comment]
read your game server log

**Comment by coreyms** [comment]
![capture1](https://cloud.githubusercontent.com/assets/13152047/12427265/4468de22-beac-11e5-83e0-9b3b311a6bac.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13152047/12427268/4b0e41b8-beac-11e5-821b-a5fb3940bb56.PNG)

Just causes Weaponskills to miss

**Comment by teschnei** [comment]
I don't know if what you fixed was correct, so I will ask you to try again with the latest commit

**Comment by tagban** [comment]
Im going to update real fast and will let you know results. :)

**Comment by tagban** [comment]
Fixed: https://github.com/DarkstarProject/darkstar/commit/bca289d86f1b87d42835b760432fdee6ada9ecde
