### ISSUE TITLE
CoP: Dawn Black screening

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2644]
I was trying to fight Promathia for one of my alts. Four of my other characters have the mission finished. I entered with my character trying to get the clear and she black screened and got the "Another event was called" while my other characters went right into the CS when you defeat Promathia. 

I've attempted this twice so far and both times it has done the same thing. I've even attempted to just enter with just Fio logged in and I still get the black screen and "Another event was called."

http://prntscr.com/9sdt4n

**Comment by xdemolish** [comment]
prolly an issue with incorrect npc ids, likely wont be fixed til they're updated

**Comment by starlightknight** [comment]
I started working on updating npc ids, then i got sick, and then new january client patches come out.... will sort out the differences soon

**Comment by zynjec** [comment]
Unable to repro on master, open another issue if you're still having this issue.
