### ISSUE TITLE
server crash on residential zone level 2

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2647]
I was told this is where things are crashing. I've found chars showing as zone_pos is well over maxzoneid. It seems to crash and every time I've found a crash its another random person in some weirdly high zone Id. I have @zone open but have it block access for zones above 285 and some instance zones. Will try to get a crash dump asap.

**Comment by teschnei** [comment]
It's known already, don't need a dump

**Comment by tagban** [comment]
Is it possible to just turn off the access for the second level?

**Comment by teschnei** [comment]
Were it that easy, it would be done already

**Comment by teschnei** [comment]
i'll have to get at it tomorrow, but it might be possible to prevent them from zoning, but I don't know enough about the packet to get the second floor option out of the menu

**Comment by tagban** [comment]
Yea I was playing around with it. Does the door work just like any other
'npc'? Maybe just have it trigger on click to exit immediately.

**Comment by tagban** [comment]
I basically just tweaked settings to only direct people to Rabao instead of MH's when entering MH using zonelines for now... Obv not longterm fix, but it avoids the server crashing for that reason.. Nomad Moogles ftw.

**Comment by whasf** [comment]
You're too nice. I would drop them in the middle of the jungle and remove their map key item.

**Comment by teschnei** [comment]
Real FFXI players have that map memorized! Try yorcia weald instead. You
can even give them the map because it doesn't help

**Comment by tagban** [comment]
lol.. I was putting them in Rabao so they can still use moogles for the time being til its fixed.
