### ISSUE TITLE
DRG Server Crash (dump included)

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2653]
As far as I can tell, this person was summoning their pet and crashed, something about pet allegience...

http://hltracker.com/DRGCRASH.7z

**Comment by xdemolish** [comment]
dumping on @teschnei cause how even does a dnc/thf get a pet in the first place without even having drg leveled

also lolreturn instead of proper error handling or at least a debug break (in petutils::loadpet)

**Comment by tagban** [comment]
I have no clue how this even happened, Its a n00b on my server, not sure if it was accidental or intentional to crash.. lol

**Comment by tagban** [comment]
Thanks!!!!
