### ISSUE TITLE
Cerberus not spawning quickly enough on zone load.

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2655]
GetMobByID(17027458):setRespawnTime( ( math.random((12),(36)) \* 3600 ) + 43200 );

He should wait 12-36 hours after server boot. The +43200 is redundant and makes his window 24-48.

**Comment by Fiocitrine** [comment]
change dat shit then! wouldn't you just delete the + 43200?

**Comment by Deadwing888** [comment]
Yes, but I'm sure if I tried I'd mess it up somehow

**Comment by Fiocitrine** [comment]
Try it on a test server. Delete the  + 43200 and set a timer for 12 hrs and once every 30 minutes or so

**Comment by zynjec** [comment]
It seems his spawn timer has been made to match what was suggested/tested here now.

https://github.com/DarkstarProject/darkstar/blob/f9e55601e3e112b9cca9788d21573a1f15866f7c/scripts/zones/Mount_Zhayolm/Zone.lua#L14

Closing.
