### ISSUE TITLE
Aggro issues with mobs (obvious).

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2657]
Mobs are not deaggroing after running across an entire zone.

**Comment by teschnei** [comment]
Are they within sight/sound range the whole time? Did you have deodorize up or walk through any water? There is a lot of information missing, here

**Comment by Fiocitrine** [comment]
So far, fomor and big birds. But they followed all the way across the zone in Lufaise Meadows. Some point they SHOULD deaggro, one would think.

**Comment by teschnei** [comment]
Why would you think that? if you never leave their detection range, they will of course not stop chasing you

**Comment by Fiocitrine** [comment]
I get further than targeting distance. I'll stop for about 15-20 seconds and they eventually catch up.

**Comment by teschnei** [comment]
This is expected if you did not run through water or cast deodorize

**Comment by Fiocitrine** [comment]
http://ffxiclopedia.wikia.com/wiki/Category:Fomors I don't think fomor detect by smell

**Comment by teschnei** [comment]
Everything pursues by smell

**Comment by Fiocitrine** [comment]
I didn't know this.

**Comment by Fiocitrine** [comment]
I thought only some mobs pursue by smell like Orcs, Tigers, etc.

**Comment by helixhamin** [comment]
That is the only reason for deodorize, because it helps drop tracking mobs if you can leave their view.

**Comment by Fiocitrine** [comment]
http://ffxiclopedia.wikia.com/wiki/Abraxas  http://ffxiclopedia.wikia.com/wiki/Category:Rocs http://ffxiclopedia.wikia.com/wiki/Category%3AFomors

These are what aggro'd me and didn't despawn until I zoned from all the way across a zone. Neither of them track/pursue by scent.

**Comment by teschnei** [comment]
As I said before, everything pursues by scent.  Going to close this now, since it's working correctly
