### ISSUE TITLE
CoP Storms of Fate not flagging quest but receiving the CSs

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2658]
In my Missions log it still says Dawn. I still get the CSs to eventually enter Riverne and fight Bahamut.

**Comment by teschnei** [comment]
Storms of Fate isn't a mission.  It's a quest, under Jeuno. Same for Apocalypse Nigh.

**Comment by Fiocitrine** [comment]
My bad closing this.
