### ISSUE TITLE
Heap Corruption?

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2664]
This happened to me when running from Visual Studio, it wouldn't let me submit a crash dump so I'm guessing its NOT a coding issue, but wanted to be sure.

"HEAP CORRUPTION DETECTED: after Normal block (#30302110) at 0x3AE0CE68.
CRT detected that the application wrote to memory after end of heap buffer."

**Comment by teschnei** [comment]
It's most certainly a coding issue

**Comment by tagban** [comment]
Is there any way for me to help track down what caused it for you? Wouldn't
let me save a dump.

**Comment by teschnei** [comment]
Whasf has sent me heap corruption dumps before, if you want to ask him

**Comment by teschnei** [comment]
FYI: this was probably the same crash as the other one you reported

**Comment by tagban** [comment]
Closing since can't really verify
