### ISSUE TITLE
SetDropRate doesn't seem to be able to change the base rate

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2667]
Someone said something that made me remember this, way back when I was messing around with Ix'Aern DRK, I would get both drops on occasion, despite setting one of the drops to 1000 and the other to 0. I believe it's possible to get both drops from the two Ix'Aerns that work at the moment.

Edit: Received confirmation that both Pixie Earring and D ring dropped at the same time from a recent KB. Unless this was fixed on AI rewrite, the issue remains.

**Comment by Scavenge** [comment]
in october or november of 2014, when I coded jailer of prudence I had to use this setting to set the drop rate to act correctly based on whether there was still one alive or not, and it worked at the time. so it hasn't always been broken.

**Comment by Hozu** [comment]
Did you use the mobmod that sets no drops? That one works, and is how I would have done it to prevent seals and stuff from dropping.

**Comment by TeoTwawki** [comment]
I always wondered at the logic of trying to set droprates in onMobDeath() when the mobs death both triggers the loot drops and then calls that function, effectively adjusting the drop rates after they are in the middle of being dropped. Seriously, look at the code. https://github.com/DarkstarProject/darkstar/blob/c8345aa5259513a7fa73989f9c0a9767aaa740b5/src/map/entities/mobentity.cpp#L882 onMobDeath happens right *after* teh droplist stuff https://github.com/DarkstarProject/darkstar/blob/c8345aa5259513a7fa73989f9c0a9767aaa740b5/src/map/entities/mobentity.cpp#L769

**Comment by Hozu** [comment]
I figured that wouldn't work, but when I was testing a while back I would set it in the onMobSpawn action. Hm...

**Comment by TeoTwawki** [comment]
Awhile back I fixed the core dropping items for zero rate items, dunno if that combined with moving all the logic to onMobSpawn fixed this or not (and I forget who moved it all to onMobSpawn, it was awhile ago).

Someone let me know if this still happens.

**Comment by dwn134** [comment]
Setting drop rate via onmobspawn does work as long as you do have a drop
table in database made. It just adjusts the % drop

**Comment by TeoTwawki** [comment]
@dwn134  there was the additional problem of zero percent drop rates still somehow dropping. Which I believe I fixed but I haven't gone and killed hundreds of zero percent droppers to find out for sure.

**Comment by TeoTwawki** [comment]
meh, if this still happens, gimme a new issue to look into it on
