### ISSUE TITLE
Apogee stealin' all my mpeez!

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2668]
Apogee is not doing it's job! I see it now in log but when I use it then use a BP it doesn't reset the BP recast so I can use another BP right after.

Also also, it's using the extra 50% mp on the first BP.

**Comment by Hozu** [comment]
FYI during my testing my re-implementation of the ability, I found out that it's not increasing MP consumed right now. It's just doing nothing but giving the effect.
