### ISSUE TITLE
Goldfish, Sharks, and  UFOs Oh My! 

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2669]
Goldfish do their "aggro" but don't follow. Also, when you attack them they don't attack back 

Sharks aggro but don't follow, as if in a bound state. If you get close enough they will attack you after aggroing. They also ignore pet hate while in this state. 

UFOs are doing the same as the sharks.

**Comment by tagban** [comment]
Did you update to latest build? Around 2 days ago they fixed mobs not following

**Comment by Fiocitrine** [comment]
It's not my server. But, I'm certain that our GM updated in the past two days.

**Comment by tagban** [comment]
They might want to re pull and check again. Assuming they are on the Master
branch
