### ISSUE TITLE
Server crash on getZoneIPP

### ISSUE THREAD

**Issue by m241dan** [DarkstarProject/darkstar#2670]
I don't have a dump, but I have a backtrace... sorry, not really sure what the issue is here.
#0  malloc_consolidate (av=av@entry=0x7ffff62f8760 <main_arena>)

```
at malloc.c:4149
```
#1  0x00007ffff5fb9df8 in _int_malloc (av=0x7ffff62f8760 <main_arena>,

```
bytes=8160) at malloc.c:3423
```
#2  0x00007ffff5fbc7b0 in __GI___libc_malloc (bytes=8160) at malloc.c:2891
#3  0x00007ffff76855d4 in my_malloc ()

   from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
#4  0x00007ffff76811be in alloc_root ()

   from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
#5  0x00007ffff766612c in cli_read_rows ()

   from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
#6  0x00007ffff7666ff5 in ?? ()

   from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
#7  0x00007ffff7667c3e in mysql_real_query ()

   from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18
#8  0x00000000004185d1 in Sql_QueryV (self=0x7ffff5ad7064,

```
query=<optimized out>, args=args@entry=0x7fffffffdfc8)
at src/common/sql.cpp:295
```
#9  0x00000000004186c7 in Sql_Query (self=<optimized out>,

```
query=query@entry=0x516748 "SELECT zoneip, zoneport FROM zone_settings WHERE zoneid = %u;") at src/common/sql.cpp:275
```
#10 0x00000000004f091a in zoneutils::GetZoneIPP (zoneID=245)

```
at src/map/utils/zoneutils.cpp:1024
```

---Type <return> to continue, or q <return> to quit---
#11 0x000000000049d6d1 in SmallPacket0x05E (session=<optimized out>,

```
PChar=0x31b77520, data=...) at src/map/packet_system.cpp:2781
```
#12 0x000000000048655f in parse (buff=0x7ffff5ac1d2c "\026\001\025\001\b\002",

```
buffsize=buffsize@entry=0x7fffffffe1b8, from=from@entry=0x7fffffffe1d0,
map_session_data=map_session_data@entry=0x31f2ac80) at src/map/map.cpp:606
```
#13 0x0000000000488e1e in do_sockets (rfd=rfd@entry=0x7fffffffe220,

```
next=<optimized out>) at src/map/map.cpp:382
```
#14 0x0000000000406b80 in main (argc=1, argv=0x7fffffffe398)

```
at src/common/kernel.cpp:252
```

**Comment by teschnei** [comment]
master or stable?

**Comment by m241dan** [comment]
ah, sorry. Stable.

**Comment by zynjec** [comment]
Stale, if you're still having this issue feel free to open another issue.
