### ISSUE TITLE
WS miss all the time

### ISSUE THREAD

**Issue by Jahana** [DarkstarProject/darkstar#2674]
Every attempt to use a weaponskill results in a miss and a server error message similar to 

`[24/Jan] [10:13:04][Error] luautils::onUseWeaponSkill: ./scripts/globals/weaponskills.lua:440: attempt to compare nil with number`

**Comment by Scavenge** [comment]
is this on stable or master? it looks like it's this line:  elseif (tp>=200 and tp<=300) then

which implies that tp is nil i guess.

**Comment by Jahana** [comment]
It's on master.  Stable works just fine.

**Comment by Scavenge** [comment]
it looks like on master tp must be added to onuseweaponskill as an argument, any chance you're using a custom or old script for the weapon skill?

on stable it looked like 
function onUseWeaponSkill(player, target, wsID)

but now on master it has to look like

function onUseWeaponSkill(player, target, wsID, tp, primary)

https://github.com/DarkstarProject/darkstar/commit/7e69a04bd849753a267fa4cb6908fb31c62b7fa0

**Comment by Jahana** [comment]
No custom here -- did a git pull this morning, started server, and weaponskills were no longer working.

**Comment by teschnei** [comment]
hello,
It sounds like you didn't recompile your server - so your scripts are
updated but your game server is not

**Comment by tagban** [comment]
Last night it was reported some weapon skills were causing server crashes, so I'm guessing something there did it?

**Comment by Jahana** [comment]
Ah, yes, that fixed it!  Thanks!
