### ISSUE TITLE
BCNM and Dyna Timers are not working

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2675]
When it updates you for the amount of time left it gives you random numbers like 17:05:00 and then 28:45:02 and 9:23:43. It doesn't give you actual time left. Unsure if timer if still "counting down" or not.

**Comment by Hozu** [comment]
Just want to update this, the underlying timer still works properly - I sent a BCNM to 2 mins and I got booted out after 2 mins. It's just displaying the time to the client improperly.

**Comment by teschnei** [comment]
Thanks, I've been wanting to fix it but I was too lazy to check if it was
just display or not
