### ISSUE TITLE
Quick Draw recast merits not working

### ISSUE THREAD

**Issue by Kubisnaxx** [DarkstarProject/darkstar#2678]
Three CORs on Nasomi have merits into this group1 slot and have all concluded that no recast time is deducted for merits in it. I am not 100% sure on the quick draw accuracy either, but i would like both of them to be check if anyone could.

**Comment by Hozu** [comment]
Accuracy works, it's the recast that doesn't. It has to do with the fact that it uses charges.

**Comment by Kubisnaxx** [comment]
Would it be possible to reduce each charge by one second then? Mathematically speaking, it would reduce Quick Draw by 2 seconds still.

**Comment by teschnei** [comment]
er.. the quick draw recast merit is supposed to reduce each charge by 2 seconds.  the issue isn't really that it's not known what to do, just that nobody has got around to doing it yet

**Comment by Hozu** [comment]
I tried but it confused the hell out of me.

**Comment by Kubisnaxx** [comment]
dang :( i doubt anyone will get around to working on it anytime soon either

**Comment by teschnei** [comment]
Should just be applying merit to chargeTime at charentity:1202

**Comment by Kubisnaxx** [comment]
any way for it to be fixed soon? :D

**Comment by teschnei** [comment]
It'll get fixed when someone has time to fix it
