### ISSUE TITLE
Worms aggroing underground stay untargetable

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#2680]
If a player gets aggroed by an underground worm (worm while moving, eg land worm's in qufim), the name doesn't appear and they stay untargetable.

also, if this happens and the player puts on sneak+deo (and runs off), it's not possible to lose aggro 
and finally, after returning to check for aggro state, player got hit by rasp but didn't lose sneak+deo

happend on today's master 2d460d7 

sorry for 3 in 1 bug report, but i guess it might be somehow related

**Comment by armouredking** [comment]
Worm issues have been for a while https://github.com/DarkstarProject/darkstar/issues/2138

Didn't personally test it with spell use though.
