### ISSUE TITLE
Job Abilities missing

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2688]
I updated the server and sql today and players are no longer seeing job abilities. I might have missed something but so far my investigation says I didn't.

**Comment by teschnei** [comment]
search your map server log for "error"

**Comment by tagban** [comment]
No errors related to abilities, there are flat out no abilities in the list to try to use..

**Comment by teschnei** [comment]
it would be during start up, not when trying to use them

I added another column to the abilities table, if you did not rerun it then it's not going to work

**Comment by tagban** [comment]
Im re-pulling and rebuilding will let you know.

**Comment by tagban** [comment]
Just re pulled, and re-did SQL for abilities.sql and whatnot, and its still showing no abilities availible.

**Comment by xdemolish** [comment]
works for me

**Comment by ymkc** [comment]
Stopped working for me aswell.

Newly unlocked (quested) nin is lacking 2hr ability.

Nothing in the log, happens on current master. Ability.sql imported before restarting

**Comment by starlightknight** [comment]
my guess would be, 10c9d3225407edd24d214072eaf6432aed56fe25 added a new column called castTime in the middle of the table - there are probably query(s) in the code that are looking at the wrong row offset now. If the query offsets are off, the wrong value would be used for expansion info, which could lead to disappearing job abilities

**Comment by teschnei** [comment]
grr, I always miss that one

**Comment by tagban** [comment]
I'm not crazy, my mother had me tested ;)
