### ISSUE TITLE
Qutrubs Blinking 

### ISSUE THREAD

**Issue by hookstar** [DarkstarProject/darkstar#2689]
Qutrubs in Arr{tabkey} reef are blinking. Unable to effectively fight mobs. It is on my server as well as a fresh pull (master and stable) with no table or script modifications. MobID #16998467 POS 167 -3 140

Oddly, the Lamia Idolators (mobid 16998818 (presume same model and same zone)) do not have this issue.

**Comment by Scavenge** [comment]
i've seen this as well, but also they all died in one hit every time as if they had 1 hp.

**Comment by TeoTwawki** [comment]
blinky model ID: 0x0000EE0600000000000000000000000000000000
non blinky ID: 0x0600C50600000000000000000000000000000000
non blinky ID: 0x0600C60600000000000000000000000000000000
as a temp fix till the blinky ones are fixed in darkstar, can just swap the model ID in mob_pools table.

**Comment by hookstar** [comment]
Thanks

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5345
