### ISSUE TITLE
Red Pondweed not spawning Aspidochelone

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2691]
Trading the red pondweed to the ??? at H-8, dropped by Adamantois, doesn't spawn Aspidochelone.

**Comment by armouredking** [comment]
I thought this was because the system had been changed in https://github.com/DarkstarProject/darkstar/commit/9e683fe410bc589213abdb934f9f782a77d3d34a due to all the bugs it had? Like right now doesn't that setting not work?

**Comment by Fiocitrine** [comment]
Apparently, Aspi is a timed pop. So, I'll close this for now.
