### ISSUE TITLE
Relic currency too easy to obtain

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2693]
The current dynamis system mirrors what was seen during the 75 cap and is remarkably well coded despite having no reference in retail. There are however a few things making relic weapons too easy to obtain.

First of all: the drop rates in dynamis jeuno are off by an order of magnitude. In retail your average city dynamis run could expect round about 350 pieces of currency. A good run might push 700-800 with lucky hq drops or something. This is contrasted against an average darkstar dynamis jeuno run which will yield ~7,000 pieces of currency. The other three city dynamis zones are also more generous than retail, but if one were to remove darkstar's overpowered TH they would be sort-of kind-of in the ballpark.

The reason for dynamis jeuno's higher yield stems from the fact that every goblin has a chance to drop each of the hq currency pieces at 1% each whereas the normal mobs in the other city dynamis zones only have a chance to drop singles. When this code is implemented on an actual server the farming runs completely revolve around dynamis jeuno where a small static of members can churn out a relic a week. This is totally non retail.

The second thing making relic currency too easy to obtain is the mob difficulty in dynamis. The mobs con ~T to a level 75 and can be plowed through by individuals at roughly the same speed it would take an alliance to plow through them on retail. @nasomi has boosted the level of dynamis mobs by something like 6 or 8 levels and the results have been great (though they are still a smidge squishy). 

The third thing making relic currency too easy to obtain is the entry conditions for dynamis. Retail only let a player enter dynamis every 72 hours whereas darkstar is every 24. Also, retail required purchase of a 1M hourglass to enter dynamis whereas darkstar's is free. 

To go off on a tangent for a moment: When free dynamis goes into play on an actual server, one starts to see is the "gil is useless effect" whereby high level characters have no use for the tens of millions that have piled up. Meanwhile relic currency is scarcely sold for gil even though it is ten times easier to obtain. The 1M hourglass on retail closed the loop by tying gil into the creation of the other three major currencies-- bringing better balance to the overall economy.

**Comment by teschnei** [comment]
Just letting you know I will not ever spend time on changing anything related to the way dynamis currently works, and would just redo the entire thing for how it is currently on retail

**Comment by Deadwing888** [comment]
Well I hope someone else spots this then

**Comment by jamiehavok** [comment]
Doesn't Nasomi have a 50k per person per entry to dynamis fee? This would be nearly 1 million gil per alliance which would offset the hourglass requirement especially with the main dynamis zones often having more than 1 alliance entering. Retail now it's just a 1 time entrance fee to forever enter dynamis. so yeah if servers like nasomi want to make it harder and more classic it's easily moddable!

**Comment by Hozu** [comment]
Replace the 100s on the beastmen with singles, in their drop pool. Also there's a setting where you can make it true 72 hour entry in settings.lua.

**Comment by LionelGrimm** [comment]
"I almost got my relic now I want it harder for others to get theirs." is what that first post translates to.

**Comment by teschnei** [comment]
I would appreciate it if comments not relevant to the description or fixing of the bug were left unposted, thanks.

**Comment by whasf** [comment]
Right now, dynamis tweaks are up to the server owner as the system will be re-written to match current retail in the near future.
Thanks for your report!
