### ISSUE TITLE
Non retail behavior of dynamis statues

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2694]
Darkstar dynamis statues currency have 1k hp (too little). 

Coupled with the fact that when one-shotted they will not spawn their mobs: a black mage can cruise around a (freely entered) dynamis zone blowing up stones left and right for HQ currency pieces and exp.

Now in retail it was possible for a group of black mages to time nuke statues and take them straight from 100 to 0, but when they did this the mobs would still spawn (not aggro'd the black mages if the stone was killed quickly enough).

@nasomi has raised the HP on the stones to 2k and this has moved things closer to retail conditions, but it is still possible with two black mages (close enough in sync) to kill the statue before it spawns its mobs. Such a strategy can bypass over half of the normal amount of fighting required for a city win for instance.

PS: Dynamis statues in the 75 cap dynamis are true detection (currently coded correctly in darkstar), issue #2388 can be closed.

**Comment by R3P0FFXI** [comment]
Dynamis itself is non retail the entire thing needs to be rewritten for whats out there now.

**Comment by zynjec** [comment]
Neo-dynamis is being added with bcnm rewrite, and not bothering fixing 1.0 dynamis.
