### ISSUE TITLE
Certain battlefield mobs should not render exp

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2695]
Most notably the mobs in the dynamis that darkstar is replicating did not used to yield EXP. The only exp came from EXP pages that mobs would sometimes drop (they granted only a couple of hundred exp a piece).

Certain BCNM monsters need the no exp flag as well. Under Observation and Like the Wind come to mind, probably others as well. (by extension these mobs should not drop beastman seals or crystals)

**Comment by Topace1** [comment]
On retail dynamis mobs do give exp now. That is how people upgrade their armor before reforging.

**Comment by TeoTwawki** [comment]
There is a mobMod that can be applied to fix this on any mobs this is still an issue with.

As this is 3 years old now and BCNMs have been overhauled, i am closing. A new issue can be made if needed.
