### ISSUE TITLE
QM3 in Xarcarbard not appearing the LB 2 quest

### ISSUE THREAD

**Issue by Biogreg82** [DarkstarProject/darkstar#2696]
2 people needed the quest, 1 person picked it up at the beginning of the fight and recieved it.  Killed the Courel and the ??? was not there.  Zoned came back it was still not there.

Not sure what to do...

O and this is on Oldschool server

**Comment by zynjec** [comment]
Not seeing this issue on master any more.

If anyone else has this issue, feel free to open another issue.
