### ISSUE TITLE
Certain Ammo not doing Damage

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2703]
This was from someone on my server testing. I had them test multiple methods for using ammo:

> For the scorpion arrows, with a stack of 99 I was able to do positive damage.
> Equipping a single arrow would get 0 damage on hits.
> 
> It seems to happen on other single items as well.
> The Animikii bullet will equip but does 0 damage.
> 
> All equipped items DO deal damage in weapon skills. Just not regular attacks.
> 
> Some other higher level ranged ammo doesnt equip as well. Dark Adaman bolts, Achiyal. bolts and Titanium bolts wont equip on RNG99. The first two are higher item level maybe thats the cause? Dark adaman bolts are RNG89. 

I did verify I had the same issues on my RNG. But not entirely sure if its item issues, or something else.

**Comment by teschnei** [comment]
anything over 75 isn't officially supported, FYI

**Comment by tagban** [comment]
Scorpion Arrows are I believe 75

**Comment by teschnei** [comment]
Yep, I'll look into the single ammo not doing any damage.  But for ammo over 75 that won't equip, that's the situation

**Comment by tagban** [comment]
Gotcha. It might be something simple in the data base that I can play with.
