### ISSUE TITLE
Throwing Bullets

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2704]
Equipping a bullet in the ammo slot and then equipping a boomerang in the ranged slot causes the boomerang to add the bullet damage to each ranged attack. Bullets are not consumed.

**Comment by tagban** [comment]
That's awesome

**Comment by teschnei** [comment]
Can't reproduce. Iron bullet -> Wingedge unequips the bullets.

**Comment by Deadwing888** [comment]
Throw the wingedge, you'll notice a substantial damage increase
