### ISSUE TITLE
Incorrect dialogue while using "Scavenge" during "Fire and Brimstone" RNG AF Quest

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2718]
![afq](https://cloud.githubusercontent.com/assets/7009763/12762793/e266f400-c9e8-11e5-9b5b-25a007018d19.png)

The correct item is obtained, but the dialogue doesn't match to indicate that the item was obtained.

**Comment by xdemolish** [comment]
textids prolly need updating (that or they've already been updated and you didn't update your client)

**Comment by Hozu** [comment]
Scavenge isn't requiring the textid file for Castle Oztroja, though it's a bit silly to have to include it every time the ability is used.

**Comment by teschnei** [comment]
you can include it after checking the zone

**Comment by wrenffxi** [comment]
this can be closed. scavenge is getting text IDs from the zones table.
