### ISSUE TITLE
San d'Oria mission 5-2 can't enter Throne Room Shadowlord Fight

### ISSUE THREAD

**Issue by kfwebdev** [DarkstarProject/darkstar#2719]
Playing RDM99 on BNet.cc and attempting to play San d'Oria Mission 5-2, The Shadowlord Fight in the Throne Room results in this notice and black screen. Selected the Throne Room door, choose The Shadowlord Battle from the list and the resulting text says "Another event was called while current event was running."

![img_20160202_161418](https://cloud.githubusercontent.com/assets/2660589/12769942/e11f4eac-c9d0-11e5-99e6-a398161d1ee9.png)

**Comment by teschnei** [comment]
#2717

**Comment by tagban** [comment]
Thanks.

**Comment by kfwebdev** [comment]
Thank you!
