### ISSUE TITLE
Player's casting not interrupted by mob hits

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#2725]
Player's can cast successfully even though getting hit while casting.

Only Mob WS seems to interrupt the casting, but the mobs i tested on used knock-back ws moves.

**Comment by Swiss-y** [comment]
skill? spell interupt gear? part of casting hit during? and from what i recall, mob ws never interupt on retail unless has knockback/stun. been working fine from what i seen

**Comment by ymkc** [comment]
Any rdm/nin lvl40 spell, no intr reduction gear

Getting hit multiple times while casting between 0% and 80%

Long time i player retail, but as far as i remember one hit landed while casting utsusemi and you might have had a taste of the floor (bad timing on utsu:ni -> ichi)

Now i can cast stoneskin or whatever while being hit nonstop (from eg a mnk type mob, although ep for testing)

**Comment by teschnei** [comment]
EP aren't going to have a very high chance of interrupting you

**Comment by dickeyf** [comment]
I can test this tonight

I also experienced this, I never get interupted ever, long spells like
stoneskin never gets interrupted.  I'll give it a try against EMs, which
for sure should interrupt every time I get hit.  On retail, I remember that
interuption rates where 100% for nin spells.  But almost 100% for most
magics.  For EPs, interuption rate with no mods (If my memory is good
enough) would be more like 25% to 50%

**Comment by ymkc** [comment]
Oh i see. Thought a hit is a hit and EPs just miss more often. Will give DCs/EMs a try aswell

**Comment by Deadwing888** [comment]
Darkstar is definitely more forgiving about spell interrupts from mob hits. Especially when using /nin

Spell interrupt gear does appear to function correctly. Aquaveil is pre-2010 correct  where 77%+aquaveil = spell always goes off.

**Comment by helixhamin** [comment]
Not sure if it is correct, but aquaveil, according to the settings.lua, isn't quite that high.
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/settings.lua#L133

**Comment by Deadwing888** [comment]
I'm not saying aquaveil is 77%, I'm saying 77% in gear + aquaveil = spells always go off

Darkstar may allow as little as 75% in gear+aquaveil but retail required 77%.

**Comment by teschnei** [comment]
Just a little nitpick, but the percent a spell is at when it goes off is
entirely client side and has no resolution higher than 400ms, so it doesn't
really make sense to say anything about the percent you were at.  In fact,
most likely the reason is just latency being smaller to darkstar servers
than it is to retail's servers in Japan.

**Comment by whasf** [comment]
Darkstar spell cast times are way off what is in retail by at least 3-4 years.

**Comment by teschnei** [comment]
Nah I think we fixed that a while ago

**Comment by Hozu** [comment]
To me it feels like it's comparing your current skill vs. your cap for the skill, and when you're getting a skill from a subjob, it's checking against the cap you'd have from the sub, despite it being much lower than it would be if it was mained. That's why I find that if you have capped Ninjutsu skill as /NIN you don't get interrupted very often.

**Comment by Deadwing888** [comment]
I wasn't talking about % I was at when spell goes off, I was talking about % in Spell Interruption down gear you had to be wearing. 

That's a really interesting comment Hozu, someone should look into that. I'm not sure what causes it but even a hit for 1 damage from a high level mob and your /nin shadows were probably not going off. DSP they'll go off about half the time it feels like even on big hits.

**Comment by teschnei** [comment]
whoops, my mistake

**Comment by ymkc** [comment]
Just wanted to add, that i tested as rdm36/nin18 with ninjitsu lvl9 and still got of utsu against EM mobs without interrupts 

So might not be tied to main job skill/spell lvl

**Comment by Hozu** [comment]
Didn't https://github.com/DarkstarProject/darkstar/commit/9cb7f1fbbf485eb5ce806f4672302f38a20bfea8 fix this?

**Comment by bendangelo** [comment]
This is fixed.
