### ISSUE TITLE
Shield block should not be possible under Terror status effect

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2731]
It currently is. Most easily recreated at Fafnir or Nidhogg.

**Comment by Deadwing888** [comment]
Furthermore I noticed I got a parry check while asleep a moment ago. As I recall this is also non retail? But I'm not 100% sure, could anyone weigh in?

**Comment by Topace1** [comment]
I think parrying can be done while under the effects of sleep. All you need is to be facing the mob,

**Comment by aizenmyou** [comment]
Parry definitely is available in retail while asleep. We used to make jokes about it years ago. (That and how characters sleep standing up)

**Comment by Scavenge** [comment]
you also need to have your weapon drawn in order to parry, not just be facing the mob.

**Comment by Deadwing888** [comment]
Yeah, that's coded correctly scavenge

**Comment by TeoTwawki** [comment]
Was the damage reduced, shield skillup obtained, or both?

**Comment by Deadwing888** [comment]
Damage reduced. Unknown if skillup was obtained.

**Comment by TeoTwawki** [comment]
186cb73ace59a58d7269426e3b43f1523b1142e8
