### ISSUE TITLE
Avatars not attacking mob if player has hate.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2735]
If mob kills avatar and comes after you. Then you resummon avatar, the avatar will not auto-attack the mob.

**Comment by tagban** [comment]
Same as mine? https://github.com/DarkstarProject/darkstar/issues/2729

**Comment by Fiocitrine** [comment]
They might be related. I also posted a bug about BPs not going off unless you are extremely close to the mob.

**Comment by KnowOne134** [comment]
this is not an issue anymore, can close
