### ISSUE TITLE
tom tit tat does not exist

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#2739]
no sql entries for his existence, but the onMobDeath for the mandragora placeholders is there as well as a lua for the NM itself

**Comment by xipies** [comment]
Mob is in mob_pools.sql:

INSERT INTO `mob_pools` VALUES (3947,'Tom_Tit_Tat',178,0x00002C0100000000000000000000000000000000,2,2,7,360,100,0,0,1,2,0,0,0,3,0,0,0,1,0,178);

**Comment by Scavenge** [comment]
oh i guess i did a search within the github repo for tom_tit_tat and it only came up with 3 luas and nothing else

**Comment by teschnei** [comment]
The github search is not very reliable. Use git grep on your repository
