### ISSUE TITLE
Lotto pop NMs seem to pop faster when PH is killed with a full pt

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2740]
Someone mentioned this has something to do with each person near the mob getting a dice roll to pop the NM?

**Comment by TeoTwawki** [comment]
code that doesn't involve any players only runs once.

Using rock lizard / leaping lizzy as an example:
```lua
    -- Get Rock Lizard ID and check if it is a PH of LL
    mob = mob:getID();

    -- Check if Rock Lizard is within the Leaping_Lizzy_PH table
    if (Leaping_Lizzy_PH[mob] ~= nil) then
        -- printf("%u is a PH",mob);
        -- Get LL's previous ToD
        LL_ToD = GetServerVariable("[POP]Leaping_Lizzy");

        -- Check if LL window is open, and there is not an LL popped already(ACTION_NONE = 0)
        if (LL_ToD <= os.time(t) and GetMobAction(Leaping_Lizzy) == 0) then

            -- printf("LL window open");
            -- Give Rock_Lizard 5 percent chance to pop LL
            if (math.random(1,20) == 5) then
                -- printf("LL will pop");
                UpdateNMSpawnPoint(Leaping_Lizzy);
                GetMobByID(Leaping_Lizzy):setRespawnTime(GetMobRespawnTime(mob));
                SetServerVariable("[PH]Leaping_Lizzy", mob);
                DeterMob(mob, true);
            end
        end
    end
```
should only run one time. at one point in the past there were..issues about that. but right now should only be running once. could print to console log to verify it easy enough. 

Also of note: months ago I did something to some mobs under the mistaken impression it would run per party member..luckily said mobs function fine after my derpage, so I haven't had to rush to undo it.

**Comment by Deadwing888** [comment]
In that case I'm going to go out on a limb and assume it works now, and recent manifestations of this issue were just coincidences.

Closing the issue.
