### ISSUE TITLE
Mission 2-3 (all Nations) CS Not working

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2743]
Players are stuck on a black screen and cannot use release command even to get out of it. Seems to be happening on a lot of missions right now, but thats the one I'm hearing most about. Tested it myself and sure enough only way out was using zone to move myself or my players were using homepoint command.

**Comment by teschnei** [comment]
try it after the most recent commit

**Comment by tagban** [comment]
Hrm okay sorry, will re-sync real fast and make them try it.

**Comment by tagban** [comment]
Thanks!!
