### ISSUE TITLE
Shadowlord Fight 5-2 CS Not working

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2744]
Seems to be the same issue as 2-3 not working, but making a separate report just incase its different. Seems to hang after the fights and just black screen forever.

**Comment by dickeyf** [comment]
Yeah, same issue.  All BCNMs that does not spawn a coffer at the end (So
missions fights) will suffer from this problem.

I have a pull request up that fixes this issue:
https://github.com/DarkstarProject/darkstar/pull/2741

**Comment by teschnei** [comment]
closing since it's a duplicate
