### ISSUE TITLE
King Arthro spawn method is incorrect

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#2749]
As it currently works, the server variable gets reset any time a knight crab spawns, but in retail it worked so that if you didn't kill all of the crabs within 5 minutes of the first crab's death, they all respawned at the same time.  if you did manage it, KA would pop and once he died, the knight crabs would return 21-24 hours later and presumably spawn all at the same time.  spawning at the same time is key because if they don't (and this is how we discovered the issue) the first one to spawn can be killed and then the others spawn, resetting the progress of kills back to 0.  the unknowing player kills all of them one by one as they spawn and is left with only a servervar of 1 for his last kill.

**Comment by TeoTwawki** [comment]
good catch, explains the occasional missing KA pop people have previously complained of

**Comment by Deadwing888** [comment]
On retail the knight crabs will respawn all at once 21-24 hours on 30 minute windows which are offset slightly earlier than KA's TOD. I don't remember if the offset is 5, 10, or 15 minutes but I'm pretty sure it's one of those.

**Comment by eraffxi** [comment]
what is the 30 minute window? after 30 minutes they depop?

**Comment by metalfiiish** [comment]
These issues should be resolved in the merged code from #4292 . Could probably close this ticket.
