### ISSUE TITLE
CoP Antlion At top of Mountain

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2753]
This mob pops but is invisible but can still attack you. Pretty funny to watch people try to fight with /attack for each hit. But I'm guessing this might just be an SQL trigger?

**Comment by Murdoc14** [comment]
Invisible, untargetable, cannot be hit by AoE.
/attack <bt> spam will keep you in combat and auto attacking.

**Comment by gedads** [comment]
is it lioumere climbing the mountain? there's no mob at the top in retail (except in abyssea)

**Comment by tagban** [comment]
God I forget. Murdoc should be able to answer that, he had been the one
that reported it for me.

**Comment by Murdoc14** [comment]
It is spawned at the "Loose Sand"  @ K-8 its ground level, not on the mountain, although it is nice that after you kill and check the loose sand for the key item you get instantly ported to the top of the mountain, nice script :+1:

**Comment by Hozu** [comment]
This issue is resolved btw.
