### ISSUE TITLE
Search Server Breakpoint/crash.

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2755]
https://www.dropbox.com/s/cqzwr6k9hni1qf1/searchcrash.7z?dl=0

Finally sick of restarting it every so often, so opted to run in debug and grabbed a crashdump.

**Comment by whasf** [comment]
Visual Studio says I don't have the correct search.cpp file (you're running a modified server). Can you email it to me whasf[.at{.}...]dspt.info ?

**Comment by tagban** [comment]
my server is slightly modified but not for search... either way here is the whole folder.. (its running vanilla master was pulled like yesterday morning. https://www.dropbox.com/s/27m6k6yz3zok3x0/search.7z?dl=0

**Comment by xdemolish** [comment]
links are dead, reopen with a new dump
