### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by mrnecromancer** [DarkstarProject/darkstar#2768]
Had no trouble playing the game for the last 2 weeks then today while in a party, there was bad serer lag so everyone decided to exit and re-log.

I exited the game and tried to use auto login but now it says invalid username/password.

Server status shows up on wiki.

**Comment by helixhamin** [comment]
What server?
Github isn't really the right place.
If old school you may want to post in the forums.

**Comment by mrnecromancer** [comment]
supernova

New to server, can you direct me to the right place?

**Comment by helixhamin** [comment]
Again unsure what server. If old school report here: https://forums.dspt.info/index.php

**Comment by xdemolish** [comment]
not our bug, report bugs to your server admins who can then report them to us after confirming its an issue with DSP and not their setup

**Comment by aizenmyou** [comment]
mrnecromancer: Post here - http://supernovaffxi.proboards.com
