### ISSUE TITLE
Server Crash on food use (dump)

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2769]
Honestly, I checked to see if we had any modified SQL and re-set it real fast and re-loaded the SQL, still crashed within a few minutes of loading.

https://www.dropbox.com/s/oy8n1iy5466xaea/crash2.17.7z?dl=0

Its still possible its somthing custom or out of scope, but I wasn't sure so wanted to share the dump.

**Comment by tagban** [comment]
This was after https://github.com/DarkstarProject/darkstar/commit/59a6dad78f16ed34fa6602c711b0e5324935fab3

**Comment by teschnei** [comment]
I purposefully left in a bunch of those mods in food scripts because I don't have time to fix them - so a bunch of food scripts will trigger debug breaks (I did not check the dump yet to see if that was the case).  I think after grepping those mods, food was the only thing left, though.

**Comment by tagban** [comment]
Oh gotcha, so just disable food. :)

**Comment by teschnei** [comment]
Or complain loud enough that a scripter fixes them

**Comment by tagban** [comment]
If I have time I'll see what I can do at some point but just clocked out and need to go finally take a break from the screeens after 11 hrs of work. lolz
