### ISSUE TITLE
5-1 CS causing client crash

### ISSUE THREAD

**Issue by hookstar** [DarkstarProject/darkstar#2770]
Upon entering FeiYin from Beaucidine to trigger cs 0x0001 (5-1 CS) causes black screen / crashing of client. Server log didnt show any errors.. Thanks

**Comment by TonySpahgetti** [comment]
Player on my server was getting the same issue, though, when attempting to log in (after attempting to @homepoint <playername> while he was logged off)  his POL client kept crashing, thanks to the guys in the IRC, we managed to fix it, though the cutscene is still broken.

His nameflag was set to 131072, and resetting it to 0 in the database allowed him to log in again (Char_stats is the table where the nameflag is found)
