### ISSUE TITLE
Player spawning Mimics from coffer chests with coffer key in Boyada Tree.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2773]
A player told me that they spawned three mimics with MNK AF quest activated in The Boyada Tree. Also, they attempted to open a fourth ( the coffer around E-6 ) and it spawned the Detonator WS NM Beet Leafhopper.

**Comment by Hozu** [comment]
They weren't weakened when they opened it, were they?

**Comment by Fiocitrine** [comment]
I'm not sure. Let me ask.

**Comment by Scavenge** [comment]
I have seen this happen on era as well

**Comment by Hozu** [comment]
Yeah if you're weakened it spawns a mimic. That's expected behaviour.

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5324
