### ISSUE TITLE
BCNM/KSNM non working/working list

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#2782]
BCNMs

Name - Zone - Status

Level 20 Cloudy Orb
(20 Beastmen's Seals)
- [x] Charming Trio - Balga's Dais - Works
- [ ] Crustacean Conundrum - Waughroon Shrine - Trade not accepted
- [ ] Shooting Fish - Horlais Peak - Trade not accepted
- [x] Wings of Fury - Ghelsba Outpost- Works

Level 30 Sky Orb
(30 Beastmen's Seals)
- [ ] Birds of a Feather - Waughroon Shrine - Mo mobs just chest; doesn't exit upon opening chest
- [ ] Carapace Combatants - Horlais Peak- No option given
- [ ] Creeping Doom - Balga's Dais-Trade not accepted
- [ ] Die by the Sword - Qu'Bia Arena-Trade not accepted
- [x] Petrifying Pair - Ghelsba Outpost-works
- [x] Dropping Like Flies - Horlais Peak - works
- [ ] Grove Guardians - Waughroon Shrine - No option given
- [ ] Harem Scarem - Balga's Dais-Trade not accepted
- [ ] Let Sleeping Dogs Die - Qu'Bia Arena-Trade not accepted
- [ ] Toadal Recall - Ghelsba Outpost -No option given

Level 40 Star Orb
(40 Beastmen's Seals)
- [ ] Under Observation - Horlais Peak-Trade not accepted
- [ ] Undying Promise - Qu'Bia Arena-Trade not accepted
- [ ] Royal Jelly - Waughroon Shrine-Trade not accepted
- [ ] Royal Succession - Balga's Dais-Trade not accepted
- [ ] Factory Rejects - Qu'Bia Arena-Trade not accepted
- [ ] Steamed Sprouts - Balga's Dais-Trade not accepted
- [ ] Tails of Woe - Horlais Peak-Trade not accepted
- [ ] The Worm's Turn - Waughroon Shrine-Trade not accepted

Level 50 Comet Orb
(50 Beastmen's Seals)
- [ ] The Final Bout - Waughroon Shrine-Trade not accepted
- [ ] An Awful Autopsy - Qu'Bia Arena-Trade not accepted
- [ ] Eye of the Tiger - Horlais Peak-No option given
- [ ] Rapid Raptors - Balga's Dais-Trade not accepted
- [x] Hostile Herbivores - Horlais Peak- Works
- [ ] 3, 2, 1... - Waughroon Shrine-Trade not accepted
- [ ] Idol Thoughts - Qu'Bia Arena-Trade not accepted
- [ ] Treasure and Tribulations - Balga's Dais-Trade not accepted

Level 60 Moon Orb
(60 Beastmen's Seals)
- [ ] Celery - Qu'Bia Arena-Trade not accepted
- [ ] Shots in the Dark - Horlais Peak-Trade not accepted
- [x] Up in Arms - Waughroon Shrine-Works
- [ ] Wild Wild Whiskers - Balga's Dais-Trade not accepted
- [ ] Amphibian Assault - Sacrificial Chamber-No option given
- [ ] Brothers D'Aurphe - Qu'Bia Arena-Trade not accepted
- [ ] Demolition Squad - Qu'Bia Arena-Trade not accepted
- [ ] Dismemberment Brigade- Horlais Peak-Trade not accepted
- [ ] Divine Punishers - Balga's Dais-Trade not accepted
- [ ] Grimshell Shocktroopers - Waughroon Shrine-No option given
- [x] Jungle Boogymen - Sacrificial Chamber-Works
- [ ] Kindred Spirits - Throne Room-Trade not accepted
- [ ] Legion XI Comitatensis - Chamber of Oracles-Trade not accepted

Atropos Orb
(30 Kindred's Seals)
- [x] Contaminated Colosseum - Horlais Peak-Works
- [ ] Infernal Swarm - Qu'Bia Arena-Trade not accepted
- [ ] Moa Constrictors - Balga's Dais-Trade not accepted
- [x] Prehistoric Pigeons - Waughroon Shrine- Works
- [ ] The Scarlet King - Chamber of Oracles-Trade not accepted

Clotho Orb
(30 Kindred's Seals)
- [ ] Cactuar Suave - Chamber of Oracles-Trade not accepted
- [ ] Come Into My Parlor - Qu'Bia Arena-Trade not accepted
- [ ] Copycat - Waughroon Shrine-Trade not accepted
- [x] Double Dragonian - Horlais Peak-Works
- [ ] Seasons Greetings - Balga's Dais- Trade not accepted

Lachesis Orb
(30 Kindred's Seals)
- [ ] E-vase-ive Action - Qu'Bia Arena-Trade not accepted
- [ ] Eye of the Storm - Chamber of Oracles-Trade not accepted
- [x] Operation Desert Swarm - Waughroon Shrine-Works
- [ ] Royale Ramble - Balga's Dais-Trade not accepted
- [ ] Today's Horoscope - Horlais Peak-Trade not accepted

Themis Orb
(99 Kindred's Seals)
- [x] Early Bird Catches the Wyrm - Balga's Dais-Works
- [x] Horns of War - Horlais Peak-Works
- [x] The Hills Are Alive - Waughroon Shrine-Works

**Comment by Fiocitrine** [comment]
Yeah, a lot doesn't work. Yet.

**Comment by R3P0FFXI** [comment]
@Fiocitrine I know this was a working list for @xdemolish

**Comment by jamiehavok** [comment]
So is someome actively trying to get these working? Would be pretty epic for nasomi server!

**Comment by TeoTwawki** [comment]
> Would be pretty epic for ~~nasomi~~ every server! 

:smile:

**Comment by nyczducky** [comment]
Well I tried my hand at coding BLU AF BCNMs and it went well. That will be coming but I can look into coding these when I'm done.

**Comment by TeoTwawki** [comment]
Since BCNM has been overhauled, this list is no longer valid.

I believe wrenffxi has doen a pretty good job commented what works/doesn't in the new global script, but if need be we can start a new issue.
