### ISSUE TITLE
San D'oria 1-3 black screen hang at cs.

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2783]
Basically same issue is assume as other cs based problems right now.

**Comment by teschnei** [comment]
You're on master? some of the other CS issues were because of npcid shifts that weren't in master (they are now)

**Comment by tagban** [comment]
Yea I'm on master, updated 5 hrs ago.

**Comment by teschnei** [comment]
so.. which CS is it? there's certainly more than one CS in that mission

**Comment by tagban** [comment]
He said right after fight it just goes black and doesn't come back. I'll
re-update and have them try it again.

**Comment by wojojojo** [comment]
Black screen is still occurring right after the fight, hangs and goes nowhere.

**Comment by nightydog27** [comment]
After 1.3 Sandy fight there is an endless black screen unable to finish mission.

**Comment by teschnei** [comment]
37640fcf2e9368040b3c0d6dc44db454ad82e6e5
