### ISSUE TITLE
Seemingly every BCNM is hanging on a black screen at the end.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2791]
I didn't see anything strange in the console. Happens when you win any fight. Multi-part BCNMs do have each part working though.

**Comment by teschnei** [comment]
maybe @dickeyf will know something about it

**Comment by dazusu** [comment]
Getting reports of this consistently happening on my server too. Also seems to be issues with entering BCNMs (tested on San d'oria 2-1 and Shadowlord so far).

**Comment by Hozu** [comment]
Shouldn't this issue be higher priority since it blocks all kinds of progress? A new character can't get through any kind of mission progress, and can't get past level 70.

**Comment by teschnei** [comment]
there is no priority in an unpaid open source project

**Comment by Hozu** [comment]
I mean, the high priority label, heh.

**Comment by dickeyf** [comment]
I didnt see this issue since my PR from 2weeks ago.   Was it happening on a load past that commit?  I currently don't see it on my private server.  If you tell me from what commit your load is based, I'll test against it and work on it.

**Comment by teschnei** [comment]
what I mean is that the high priority label doesn't mean anything

**Comment by Hozu** [comment]
I know for sure it's broken on https://github.com/DarkstarProject/darkstar/commit/5cfcf1062f118cb365c1df3475210614ff32202a but I will test the latest commit shortly.

**Comment by Hozu** [comment]
Still broken on https://github.com/DarkstarProject/darkstar/commit/4b5fe131ca077a809382a2c3f9f5869a1d8024bf @dickeyf

**Comment by teschnei** [comment]
try after 37640fc

**Comment by Hozu** [comment]
I tested out Trial of Ice (standard fight), Shadow Lord Battle (multi-stage), and When Angels Fall (psuedo-BCNM?) and they all worked.
