### ISSUE TITLE
Mobs with pets don't summon them

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2798]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/0dd5c6adad397727e67641e27105480883d22b8f

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Not including the mobs in Dynamis, BST mobs aren't summoning their pets.

**Comment by bendangelo** [comment]
Holy crap. Who broke this again?

**Comment by teschnei** [comment]
<---

**Comment by bendangelo** [comment]
I'll take a quick look tonight
