### ISSUE TITLE
Spell range is not enforced by the server

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2800]
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
5cfcf10

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
The client can't be trusted to enforce it because it allows spells with a range shorter than 21.4 yalms to be casted from that far (ie. pretty much every physical BLU spell). Retail checks the distance from target at both the start and end of the casting time.

**Comment by teschnei** [comment]
we can't (and haven't ever) enforced this because nobody knows how polutils stores the range

**Comment by Hozu** [comment]
Is it even stored client side? If I were SE I would do that server side so people couldn't modify it somehow, but then again, SE has made some pretty dumb decisions.

**Comment by teschnei** [comment]
of course, that's how it determines the color of the arrow (and it is of
course checked on the server side as well, we just don't yet have a way to
translate the client side ranges into something usable in the server)

**Comment by Hozu** [comment]
I don't think the client itself is enforcing the range anymore - I tried with both Windower and Ashita, even ffxi-boot and all bypass the range.

**Comment by teschnei** [comment]
someone already had the spell ranges in the db! I never noticed it before (and I'm sure we weren't using before either)
