### ISSUE TITLE
Casting of spells does not terminate properly if stopped for reasons other than interruption

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2801]
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
5cfcf10

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
Example, if the target runs out of range, or dies, it returns the spell interrupted message (should be out of range, and nothing respectively). Also, if you're casting on a player who dies before the cast is complete, it client crashes the caster when the spell would have completed.

**Comment by teschnei** [comment]
hmm.. there are a lot of cases that aren't covered in here (which messages are displayed and whether nearby players see them), so i'm just going to leave the messages until I feel like figuring out how it's supposed to work

**Comment by teschnei** [comment]
I am going to close this issue because you put two into one, though.
