### ISSUE TITLE
Monsters link through walls

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2808]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
latest as of today (@revision says "unknown", I run a release build on a remote server)

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Engage a Goblin in KRT, Goblins from behind walls will link.

Monsters should only link if they can see either you, or the monster they are linking with. If there is line of sight between the two, a link should not occur.

**Comment by Cloudef** [comment]
The goblins are probably shouting to each other. It's pretty unfair that only players get to use party chat.

**Comment by bendangelo** [comment]
Where is this happening? You have the KRT navmesh in `navmeshes/`?

**Comment by dazusu** [comment]
Hey Ben.

Yes the Navmesh is loaded. Monsters are roaming.  In this zone, bats are aggroing from under-ground on top of the linking through walls issue.

**Comment by bendangelo** [comment]
You got an idea which point on the map it is?

**Comment by dazusu** [comment]
Goblin problem:   -4, 0, -122
Bat aggroing through the floor problem:  -84, 0, -123

**Comment by helixhamin** [comment]
The bat problem has been around for a while. I have learned there is a spot in KRT that if you step on, you will get agg from a high level bat from below. Sorry, I cannot check the spot exactly, but I have found this happened every time there.

**Comment by ZariusCane** [comment]
Had this happen in Crawlers Nest @ level 49BST. There is a Labyrinth Lizard in a dead in tunnel next to a tunnel where a Soul Stinger bee is. Bee Aggro'ed through the wall and also, Lizards AoE fireball can hit the bee as well in opposite tunnel if its close enough. I also noticed the AoE sprout spin from Witch Hazel can hit through walls as well.

In the basement of Garliage Citadel(where warden beetles and fortalice bats are) My fungar familar could hit Siege Bats upstairs with Silence Gas. The same thing happened in Fei-Yin down stairs where you first run into "Underworld Bats" Silence Gas could hit bats from the floor above.

In Kuftal Tunnel by the Yowie spawn where the raptors are, I had a foul breath go through the wall and hit an Air Elemental on the other side.

**Comment by dazusu** [comment]
![img_20160225_132547](https://cloud.githubusercontent.com/assets/7009763/13320865/a338fb42-dbc3-11e5-9f32-8e3a1b24885f.png)

**Comment by ZariusCane** [comment]
While we're on the topic, there are also places in Beadeaux where mobs aggro from the huts below while running above them. There is an area just past the rank 5 headhunter NM(in the Emerald Quadav) area where a few coffer mobs can aggro thru the floor w/o sneak.

I forget the groupings but a Sapphire Quadav is among them. Seen a few people die there who were on the way to farm coffer keys.
