### ISSUE TITLE
Mobs keep trying to use ranged attacks while idle/shoot too fast.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2810]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/9253c0320284505060b55f24601e81d8e2a5e5d6

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
They shouldn't be doing that, of course. When in battle with a NIN Aern it was using ranged attacks every 3 seconds, which is way too fast.

As an aside, Aerns have a special animation for ranged attacks - 1015 for normal (used by both NIN and RNG, btw), and 1016 for EES. I mention that because @bendangelo did both the ranged attacks for mobs and the correct animations for different mob families.

**Comment by teschnei** [comment]
every family has its own animation for ranged attacks

**Comment by RwNigma** [comment]
It's not a big deal. Is there any reason why when a monster will use a ranged attack on you sometimes you will not be allowed to move? It acts like it binds you for 2 seconds. Then shows you the animation of being hit. 

This happens frequently when engaging a ranged enemy that's ranged attacking you. The speed/animations may be effecting this?

**Comment by teschnei** [comment]
That is entirely client side. You always get locked when changing animation
until all animations on you are done playing

**Comment by bendangelo** [comment]
Wait whats the issue here? Which mob is shooting too fast? Mobs are shooting while idle? The animation is wrong for which mob? Every mob has it's own animation.

**Comment by RwNigma** [comment]
Hozu was stating that monsters are using ranged attacks too soon during combat. "Shoot" (3 seconds) "shoot". I was thinking that short delay was causing hiccups in movement animations. I was asking if this was correlated to mobs using ranged attacks quickly. 
Previously discussed delays may be effecting all types of attacking.

**Comment by Hozu** [comment]
Couple of issues:
1) Mobs are attempting to use ranged attacks on themselves while idle, as it's spitting out that error in the console.
2) The NIN Aern I was fighting was using ranged attacks every 3 seconds or so, while not moving aroung.
3) Not so important, but if you feel like doing the animation for Aern ranged attacks, 1015 for normal, 1016 for EES.

**Comment by Hozu** [comment]
I think it's not setting when the special ability was last used, so it keeps spamming the special ability. https://github.com/DarkstarProject/darkstar/blob/264d40ba0c79680581cce4359195d4b40b4270c8/src/map/ai/controllers/mob_controller.cpp#L347

**Comment by helixhamin** [comment]
Actually, I found an interesting effect yesterday in Delfutt's.
I was near a Giant Lobber, and one threw a rock at me.
There was no aggro, the Giant did not turn aggressive, and was just doing its idle movement (It was right before its idle movement phase, so throw rock -> idle pathing). The rock that hit my toon did no damage, but it did cause my toon to target the giant. Not sure if these are linked, but thought I would mention my observation around this. I think I have had gob archer classes also do this to me, but I would need to retest to see if I am remembering correctly.
