### ISSUE TITLE
Wyvern not attacking

### ISSUE THREAD

**Issue by helixhamin** [DarkstarProject/darkstar#2813]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
64f86e1a93b0eb706ed3b913f234fa4677cbfa

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Summon wyvern, attack monster while main job is DRG, wyvern does nothing.
Tried at level 1 DRG in West Ron.

**Comment by teschnei** [comment]
Working fine for me. 64f86e1a93b0eb706ed3b913f234fa4677cbfa doesn't appear to be a valid hash on our trees, so check your modifications

**Comment by helixhamin** [comment]
Hmm, I have changed a couple things.
Changed blu spell learn from 7 level gap to 9 level gap, and removed the doom and death luas (renamed them to doom.lua.bak and death.lua.bak), but other than that, I have made no other changes outside settings.lua and the various config files. And the pull was updated to the latest build before reporting (So 2/24/2016's build). Not sure why I would have this result.
I am multi-boxing, could this make a difference?
I can recheck the revision hash once I get home (In about 8 hours).

**Comment by helixhamin** [comment]
@teschnei  https://github.com/DarkstarProject/darkstar/commit/64f86e1a93b0e0eb706ed3b913f234fa4677cbfa

Hmm, it is this pull, and they match.

**Comment by teschnei** [comment]
oh, you typo'd it in the original message :)

server on Windows?

**Comment by helixhamin** [comment]
Correct (On windows 10). Hmm, I might have typoed. Long string to type while reading between windows xD

**Comment by helixhamin** [comment]
After further checking, the wyvern is attacking. It is just not animating. Seems like it is just idle, but the mob is taking damage.

**Comment by aizenmyou** [comment]
Make sure you don't have the PetFix plugin loaded in Windower as I noticed my pets were attacking w/o animation on BST a while back. (If you're using Windower)

**Comment by helixhamin** [comment]
Okay. I will try once I get home.

**Comment by takhlaq** [comment]
iirc there was a similar issue recently due to a pet plugin too (worked fine once the plugin was disabled)
if this is still an issue, drop a comment and we can reopen
