### ISSUE TITLE
Mobs not interrupting player's spell cast, ever

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2814]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/d6473f68ac5382985113ef09f6bedc0b722c008d

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Had someone with basically 0 Ninjutsu skill get hit during a cast, by a 78+ mob. Never failed to cast. Used to be basically 100% chance to do that.

**Comment by bendangelo** [comment]
Was the player a pld? Anyone with shield mastery will never get interrupted according to the code.
