### ISSUE TITLE
Players can enter Dynamis at any time despite restriction being set

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2815]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/d7b0b64e526d9e4ff247d6bdb976a2906e05f68f

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
I can't figure out why it's broken.

**Comment by Hozu** [comment]
I tried adding in a check to make sure that if the server var holding the unique ID is 0, to not let the player in (that's what is bypassing the time atm), but for whatever reason, the variable remains 0 upon entering, it seems. The following line is what sets the var on entering:
`SetServerVariable("[DynaBastok]UniqueID",player:getDynamisUniqueID(1280));`
And this gets set to 0 when the BCNM clears. But when I entered with two people and left with one person, that person couldn't get back in because the server variable was 0.

**Comment by Mizzguy** [comment]
I have also come across this issue as well. I remember before the "rewrite" that the "midnight reset" in the settings being true, would allow players to enter dynamis and leave, then they could enter another dynamis without restriction. The same seems to be happening again but in the settings "midnight reset" is false with 1 day in-between enter. My current Server Version 30160329_1

**Comment by Hozu** [comment]
Whenever a player enters dynamis (and limbus) there's a nil error printed to the console, something about battlefield. I can't remember what it is.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/issues/3513#issuecomment-282068501

**Comment by wrenffxi** [comment]
We've been running the latest Dyamis entry code in master for months now and have never seen this issue.  Can anyone confirm that it's still a thing?

**Comment by TeoTwawki** [comment]
system got overhauled, open new issues for any new current Dynamis problems that don't amount to "this zone isn't implemented yet"
