### ISSUE TITLE
Wipe at end of 5-1, HP button disappears after wipe timeout, instance never ends

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2816]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
64f86e1

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
On Classic server. We took a full PT to 5-1 fight. Wiped with archlich @ 18%. No one had RR up. After "wipe" timeout, HP buttons disappeared for everyone, no one got kicked out. After full instance time passed, still no one got kicked out.

**Comment by teschnei** [comment]
I think this is the same issue as https://github.com/DarkstarProject/darkstar/issues/2791, so I'll close it in favor of that one
