### ISSUE TITLE
Players are able to cast spells through obstacles, like trees.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2822]
**_Client Version_** (type `/ver` in game) **:**
latest

**_Server Version_** (type `@revision` in game) **:**
latest

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
An extension to the previous issue of monsters linking through walls @bendangelo - players can also cast spells through obstacles such as big trees in West/East Ronfaure.

**Comment by bendangelo** [comment]
Isn't this a client thing? Thought you could always do this

**Comment by dazusu** [comment]
I'll confirm on retail at the same location....

**Comment by TeoTwawki** [comment]
lol...This is entirely client handled, and its done poorly too. I've often on retail adjusted my camera and abused clipping to cast through walls and obstacles I otherwise could not. SE's server does no checking.

**Comment by dazusu** [comment]
Point taken!

**Comment by Deadwing888** [comment]
Are you all sure about this? Retail won't let you shoot arrows or cast through solid walls, and darkstar always will. If it's client side then why is it broken?

**Comment by TeoTwawki** [comment]
Yes retail will, I've done it. No cheat tools involved you tilt camera just right and obstacles cease to matter.

**Comment by Deadwing888** [comment]
There's no need to do any camera tilting on a darkstar server, it'll just shoot or cast no matter what if you're in range.

**Comment by TeoTwawki** [comment]
In general if you can see yoru character and the target, you'v e pretty good chance of being able to hit it with dia or a ranged attack even if teh map shows a brick wall between you.

Depends on the obstacle you are shooting through, but its still the server trusting the client on it in retail.

It was still the same last time I logged into retail, during that last free login period they had. I am telling you I am 120% percent beyond any shadow of doubt that it isn't handled in the client.

**Comment by TeoTwawki** [comment]
edited for effing typos, so anyone reading via email will have to look on github

**Comment by teschnei** [comment]
Just to end this conversation, the server should be checking line of sight.
http://i.imgur.com/eYJ0zbK.jpg

**Comment by TeoTwawki** [comment]
For reference: he checked the packets too.

I'm now annoyed because I'm trying to see how the F that doesn't work for him when I know I've done it with no 3rd party tools involved. Meanwhile, enjoy the sweet taste of vindication.

**Comment by TeoTwawki** [comment]
Oh curse you and your ninja edit. What an off day, thats normally MY thing.
