### ISSUE TITLE
Elemental magic can be cast at a range of 29.8yalms

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2823]
**_Client Version_** (type `/ver` in game) **:**
latest

**_Server Version_** (type `@revision` in game) **:**
latest

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Elemental Magic spells can be cast on targets at a range of upto 29.8 yalms. This is way too far. It should be closer to 21.4 at an extreme maximum.

**Comment by teschnei** [comment]
closing for duplicate (#2800)

**Comment by teschnei** [comment]
and please never put "latest" as the version types, that is completely useless
