### ISSUE TITLE
Deletion of Charactor Causes issues

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#2827]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
c77e3fe9cb0f10df8018dc885b28813aab903d47

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When you delete a charactor, it can cause issues with that account from there on out. I had a few tests done on my test server. Basically, after deleting a char, it still stays connected to lobby (Select Char, Create Char, etc. screen). When trying to create a new char it gives FFXI 3101, we exit the screen, and game, and re-attempt and get japanese lettering error. With a different name, so its treating it as if its a duplicate entry. What I think is happening is that its trying to re-use the charid of the deleted char, when it should be creating a new one. But thats a guess. 

Only reference I could find was this, but I don't think its the same issue:
https://github.com/DarkstarProject/darkstar/issues/497

**Comment by teschnei** [comment]
Why wouldn't it reuse the charid of the deleted char?

**Comment by tagban** [comment]
I dunno but game server won't let it stating there is already one used or
duplicate ID error. So something isn't being cleaned out when its deleted.

**Comment by teschnei** [comment]
so you are going to check your database for the row that wasn't cleaned out, right? :)

**Comment by tagban** [comment]
Yea although I lost the char ID because I already wiped out the
chars/accounts DB so will do it again in a few.

**Comment by tagban** [comment]
Created Char: ID: 21840 Name:Questria
DELETED
Tried creating new char Name: Quest
Error on DSConnect: "DB error - Duplicate entry '21840' for key 'PRIMARY'
Query: INSERT INTO char_look(charid,face,race,size) VALUES(21840,2,1,1);
lobby_cLook: char(Quest), charid: 21840"

Error on client" Error code: FFXI-3101
Transmission error with lobby server."

**Comment by tagban** [comment]
So I'm guessing its char_look

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/5a22b4cef2d74b503e05e4fc9e5ab05674b6e247
