### ISSUE TITLE
Blood Pact:Ward doesn't appear under commands

### ISSUE THREAD

**Issue by Topace1** [DarkstarProject/darkstar#2828]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
c77e3fe9cb0f10df8018dc885b22813aab903d47

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When summoning any avatar Blood Pact:Ward does not appear.

**Comment by teschnei** [comment]
c77e3fe9 is 3 days ago, and I changed how that works entirely, can you update first?

**Comment by tagban** [comment]
Still having same issue. (Topace is from my server, just updated 5 mins ago)

**Comment by teschnei** [comment]
select addtype from abilities where name = "blood_pact_ward"

if it's not 256, you didn't update properly

**Comment by tagban** [comment]
Got 256 on both servers. Is it possible that it didn't readd because of
releveling? Does it handle the same way rage does where you just get it
based on your chars level?

**Comment by Hozu** [comment]
Server I play on just rebuilt today to https://github.com/DarkstarProject/darkstar/commit/14a1e3d2f81547767a4157fb8d9762a9ff3b99e6 and while the wards show up in the list, the defensive ones (ie. ones that aren't used on mobs like Slowga) do nothing.

**Comment by teschnei** [comment]
the 2 rows are the exact same except for name, id, recast ID and required
expansion. can you recompile your servers?

**Comment by tagban** [comment]
Will do with the test one shortly no problem.

**Comment by Hozu** [comment]
This issue has been resolved for a while now.
