### ISSUE TITLE
DNC flourishes have a weird animation that tends to get people stuck

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2836]
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
14a1e3d

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
Hard to describe what happens, the character moves in a strange manner that doesn't look like how it should. Only way to get out of it is to use another ability.

**Comment by teschnei** [comment]
I'm guessing you mean the offensive flourishes (violent) and not the
defensive ones (reverse)?
