### ISSUE TITLE
Players appear with a black linkshell silhouette; nameflag is 0 for affected players.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2838]
**_Client Version_** (type `/ver` in game) **:**
30160203_2

**_Server Version_** (type `@revision` in game) **:**
48e2db6146073d8131dbf508607879699c284884

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Created a new database, and rebuilt the code. New characters, after they are no longer classified as a "new player" now appear with a black linkshell silhouette. NameFlag is set to 0 for such players.

https://dl.dropboxusercontent.com/u/149192/img_20160229_210255.png

**Comment by teschnei** [comment]
Working fine for me - created a new character, removed new adventurer icon, looks normal

**Comment by helixhamin** [comment]
My toons still have this, and are not flagged as new adventurers anymore. But only my other two. The toon I am on doesn't, just the others.

**Comment by dazusu** [comment]
It's interesting this isn't happening for Kj, but is for me and helix. This doesn't affect the character you're currently on, only characters around you

**Comment by teschnei** [comment]
oh.. that changes everything then

**Comment by tagban** [comment]
Happens for me to. I just stopped using linkshells. Lol

**Comment by helixhamin** [comment]
But, my toons do not have a linkshell, since it is a solo server...
Just the effect.
