### ISSUE TITLE
Using Hide makes the mob completely deaggro even if others have hate on it

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2841]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/14a1e3d2f81547767a4157fb8d9762a9ff3b99e6

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Supposed to remove the THF from the mob's hate list (and remove all enmity? I don't know the mechanics of it), and if the THF is the only one on the list, then it's supposed to deaggro the mob. Assuming the mob doesn't have scent tracking of course.

**Comment by Deadwing888** [comment]
Hide is currently OP in a number of ways.

It should fail in circumstances where the mobs track by scent, sound, or true anything. Currently it works almost everywhere.

The HNM should certainly not be going white when thief uses hide.
