### ISSUE TITLE
Enmity should not accumulate on linked mobs until they are acted upon offensively.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2842]
**_Client Version_** (type `/ver` in game) **:**
30160203_2

**_Server Version_** (type `@revision` in game) **:**
48e2db6

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
"Player 1" is fighting "Goblin A",  "Goblin B" links to "Goblin A".

"Player 2" performs healing action on "Player 1"

Currently, "Player 2" enmity increases on "Goblin B", and "Goblin B" changes target to "Player 2".

Enmity should not accumulate on linked mobs until they are acted upon offensively, or the /heal command is performed near them.

**Comment by bendangelo** [comment]
Thought I fixed this. Let me look into it.
