### ISSUE TITLE
Crash with alliance vs. a mob that has a pet

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2843]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/14a1e3d2f81547767a4157fb8d9762a9ff3b99e6

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Seems to cause a crash when an alliance defeats a mob that has a pet, but I can't get a crash dump of this since it's not my server. The pet does not necessarily have to be alive, as defeating Kirin with an alliance, which summons a pet for a short period of time, also crashes.

Edit: Crash happens immediately on death, no items get dropped, no EXP.

Edit 2: Crash dump: https://dl.dropboxusercontent.com/u/57303795/Alliance%20vs.%20mob%20with%20pet%20crash.7z Triggered a debug break for having too many states in the stack... uh what. Why does being in an alliance trigger that?

**Comment by Hozu** [comment]
May or may not be SMN mobs only, still unsure.

**Comment by ZirkSupernova** [comment]
Are dynamis summoner mobs causing crashes as well, or is this Kirin specific since it sort of summons mulitple pets (Byakko, Suzaku, etc + a traditional avatar, sometimes with

**Comment by Hozu** [comment]
Dynamis SMNs - Kirin's adds aren't considered pets, only the avatar is.

**Comment by Hozu** [comment]
Updated with crash dump in OP.

**Comment by ZirkSupernova** [comment]
I think you didn't finish your sentence, did Dynamis SMNs reproduce? I was going to suggest Vrtra as a data point if Dynamis SMNs did not reproduce (assuming Vrtra summons properly, the other day I fought Bomb Queen which is supposed to summon adds but didn't).
