### ISSUE TITLE
BCNMs unable to be finished

### ISSUE THREAD

**Issue by Ex0r** [DarkstarProject/darkstar#2844]
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
14a1e3d

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
Enter any BCNM and then finish it. The cutscene will start, but go to a black screen causing the player to force close the client.;

**Comment by teschnei** [comment]
https://github.com/DarkstarProject/darkstar/issues/2791

Use the search before posting, please

**Comment by Ex0r** [comment]
I just noticed this was a duplicate and was on my way to delete it
