### ISSUE TITLE
All nations missions (2-3)

### ISSUE THREAD

**Issue by MNKgod** [DarkstarProject/darkstar#2845]
**_Client Version_** (type `/ver` in game) **:**
latest

**_Server Version_** (type `@revision` in game) **:**

latest
**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

After defeating the Searcher and Dark Dragon the game seems to glitch and continue to loop without showing the cutscene or recieving the key item. It just hangs. tested this with all 3 nations

**Comment by teschnei** [comment]
https://github.com/DarkstarProject/darkstar/issues/2791

Please search before opening an issue

**Comment by teschnei** [comment]
And please don't put "latest" as the version and revision, I need the actual versions.
