### ISSUE TITLE
error emssages on active servers after long uptime

### ISSUE THREAD

**Issue by egzen** [DarkstarProject/darkstar#2850]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
b6f32ce365350f9159fc09769e3e26669b50ebc0

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
By long uptime I don't just mean a servers uptime I mean if a zone stays empty this issue basically won't happen. Its like zones don't exist when people aren't in them. Anyway, in a zone seeing a lot of player traffic for many hours, the console log will begin to fill with navmesh related error messages where previously we were not having issues. 

`CNavMesh::findRandomPath startRef is invalid (-574.346985, -0.593000, -473.778015) (132)`

`CNavMesh::findPath Couldn't find path (-254.328995, 32.438999, -433.661011)->(-250.373337, 2.877833, -414.505402) (254)`

**Comment by Hozu** [comment]
I noticed that if someone aggros and trains a mob somewhere, it has trouble returning to the spawn point and throws errors in the console. Though that's only really an issue for mobs that don't despawn.

**Comment by dazusu** [comment]
I think eventually @bendangelo will address this, making monsters auto-reset to their spawn point if someone zones a bunch of monsters and there's no one else in the zone to allow the navigations/mob ticks to continue. Perhaps this failover could also be used if a monster cannot find a path back to it's spawn point. It would be helpful (and resource saving) to not continue trying to path a monster that cannot path for whatever reason though.

**Comment by bendangelo** [comment]
It's been brought up a few times, mobs need to reset back to spawn point when the zone becomes empty.
