### ISSUE TITLE
Players who get BCNM status but don't actually enter can still get win credit

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2853]
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/180c791aca26bbfd07ca8d7cac1dfdc08cd69f02

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
They should not be getting the credit.

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
