### ISSUE TITLE
Pets seem to be too attached to master while aggroed/claimed

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2856]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/e99fb5ca2f25167e851a64cd4570fde2a39919f0

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Whenever the master moves, the pet attempts to move along with it. It's not obvious except when the pet is dead/despawning. Also I've had reports of people client crashing when a BST pet was pulled to a party (may or may not require level sync status).

**Comment by bendangelo** [comment]
What do you mean? Can you elaborate. What is expected and what is happening?

**Comment by Hozu** [comment]
When a BST pet dies, the corpse can move around when the master moves. It's really weird.

**Comment by bendangelo** [comment]
Oh ok that makes sense.

**Comment by teschnei** [comment]
I don't remember how the pet/master movement currently works - if the master is telling the pet to move, then that's wrong, and it should be the other way around.  If that is already the case, then I dun goofed in how roamtick is called

**Comment by lenonk** [comment]
The calling of DoRoamTick() looks reasonable, and I don't see how DoRoamTick() would be called if the pet is dead, assuming the isAlive() member works.  I do however see how the pet could follow if it was asleep.  To prevent that, HasPreventActionEffect() should probably be checked, as below.

void CMobController::Tick(time_point tick)
{
    m_Tick = tick;

    if (PMob->isAlive()) <- should probably add && !PMob->StatusEffectContainer->HasPreventActionEffect()
    {
        if (PMob->PAI->IsEngaged())
        {
            DoCombatTick(tick);
        }
        else if (PMob->PAI->IsSpawned())
        {
            DoRoamTick(tick);
        }
    }
}
