### ISSUE TITLE
Conquest items all seem to be treated as (rare)

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2859]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
180c791

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Obtain a non-rare conquest item from conquest NPC. Try to obtain another. Get "cannot obtain" message. Must get rid of item (trade, dbox, AH, etc.) to get another.

**Comment by Hozu** [comment]
I didn't check the item flags, but maybe it's trying to apply the EXP band check to everything?

**Comment by xipies** [comment]
All my chars on Classic/Old School have probably had exp ring each time I tried. It always prevented me from getting more than one of the same weapon or armor. I have not checked on my local machine yet.

**Comment by Hozu** [comment]
I mean like, it's checking if you have the item you're asking for, rather than if you have the EXP band. Otherwise it wouldn't let you get any CP item until you toss the band.

**Comment by xipies** [comment]
Oh, like the logic got copied and/or same method getting called for all items as the exp band.

**Comment by xipies** [comment]
This appears fixed now. I was able to buy multiples of conquest items without trading them away first.
