### ISSUE TITLE
Death Jackets in Crawlers Nest aggroing

### ISSUE THREAD

**Issue by helixhamin** [DarkstarProject/darkstar#2865]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/accc6b819e00c6172943bd58d7ddfdec9168ab50

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Go to CN, find a Death Jacket, watch it aggro you.

I checked https://github.com/DarkstarProject/darkstar/commit/e0135e0886bd5d5cac65735d5c22dff706bd280f since this seems to be the last time mob_pools.sql was changed. The aggro column was set to 1 from what I see at this point.
The strange part is, I tried changing it back in the sql database, and it didn't seem to stick. Maybe I did something wrong myself?
http://ffxiclopedia.wikia.com/wiki/Crawlers%27_Nest#Regular_Monsters_Found_Here

Death Jacket
40-42	Beehive Chip
Insect Wing
Giant Stinger
Royal Jelly	Honey	Bees	12
Respawn: 14 min	L

https://www.bg-wiki.com/bg/Death_Jacket

**Comment by Hozu** [comment]
Hm? I thought the column in mob pools would be aggro, and the new one in mob families would be detection type, as not all mobs in the same family aggro (ie. some crabs do and others don't).

**Comment by Hozu** [comment]
Is that not the case, @bendangelo ?

**Comment by helixhamin** [comment]
CREATE TABLE `mob_pools` (
  `poolid` int(10) unsigned NOT NULL,
  `name` varchar(24) DEFAULT NULL,
  `familyid` smallint(4) unsigned NOT NULL DEFAULT '0',
  `modelid` binary(20) NOT NULL,
  `mJob` tinyint(2) unsigned NOT NULL DEFAULT '1',
  `sJob` tinyint(2) unsigned NOT NULL DEFAULT '1',
  `cmbSkill` tinyint(2) unsigned NOT NULL DEFAULT '1',
  `cmbDelay` smallint(3) unsigned NOT NULL DEFAULT '240',
  `cmbDmgMult` smallint(4) unsigned NOT NULL DEFAULT '100',
  `behavior` smallint(5) unsigned NOT NULL DEFAULT '0',
  `aggro` tinyint(1) unsigned NOT NULL DEFAULT '0', _**<-----------**_ This?
  `true_detection` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `links` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `mobType` smallint(5) unsigned NOT NULL DEFAULT '0',
  `immunity` int(10) NOT NULL DEFAULT '0',
  `name_prefix` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `flag` int(11) unsigned NOT NULL DEFAULT '0',
  `flags` int(11) unsigned NOT NULL DEFAULT '0',
  `animationsub` tinyint(1) NOT NULL DEFAULT '0',
  `hasSpellScript` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `spellList` smallint(4) NOT NULL DEFAULT '0',
  `namevis` tinyint(4) NOT NULL DEFAULT '1',
  `roamflag` smallint(3) unsigned NOT NULL DEFAULT '0',
  `skill_list_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`poolid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by xdemolish** [comment]
closing in favour of https://github.com/DarkstarProject/darkstar/issues/2866 (both bugs have the same cause)

**Comment by bendangelo** [comment]
The aggro column is for aggro. There is an other death jacket that does aggro, I guess the migration messed it up.

**Comment by helixhamin** [comment]
Checking BG-Wiki, the Death Jacket spawns in:
Yuhtunga Jungle 
Misareaux Coast 
Fort Karugo-Narugo (S) 
Lufaise Meadows 
Rolanberry Fields (S) 
Crawlers' Nest 

Only the Fort Karugo-Narugo (S) one aggros.
