### ISSUE TITLE
Mobs will not stay claimed

### ISSUE THREAD

**Issue by helixhamin** [DarkstarProject/darkstar#2866]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/accc6b819e00c6172943bd58d7ddfdec9168ab50

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
1. Go to CN
2. Engage with Worker Crawler
3. Watch it move around, going red then yellow, red then yellow

So, attacking the worker crawler causes it to move, but not to stay red. Each time I hit it, it will move, but it will not engage. It also will not link other crawlers. I have to DOT or the idle regen makes it so I cannot kill it, and I have to chase it all over the place as it continually moves.

**Comment by dazusu** [comment]
This applies to all monsters in the game as of this server version. Monsters will aggro; then immediately return to idle/roaming state.

If you hit a monster, it will immediately idle, unclaim and roam away.

**Comment by bendangelo** [comment]
I'm fixing it now, a lot of mobs don't have the right detection type
