### ISSUE TITLE
AbsorbTP and Reverse Flourish report the wrong amount of TP drained

### ISSUE THREAD

**Issue by lenonk** [DarkstarProject/darkstar#2867]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
e99fb5c

**_Source Branch_** (master/stable) **:**
All

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
These two skills, and probably anything else that drains TP, report the actual amount drained divided by 10 in the resulting message.  It's because the addTP() method in lua_baseentity.cpp multiplies all tp gains by 10.  

I'll be happy to fix it, but before I do, I'd like to know if there is a reason why addTP() multiplies it's parameter by 10.  If there's not a good reason for it, then probably the best thing to do is to remove that feature and modify all lua scripts that call addTP() to drain 10x more.

**Comment by lenonk** [comment]
nvm, I understand why it's the way it is.  On retail TP goes from 0-300, and is considered to be in terms of %,  Here, damage is 0-3000.  So technically the message is correct I guess.

**Comment by helixhamin** [comment]
Because retail does that now.
http://ffxiclopedia.wikia.com/wiki/Tactical_Points
	
Abbreviation: TP

Note: TP displayed on a scale of 0 to 300% prior to June 2014. It now displays on a scale of 0 to 3000 (no % sign) to allow more precise display of TP values. 1000 TP is required to initiate a weapon skill.

**Comment by lenonk** [comment]
Ah, nice, so the functions that multiply * 10 should probably be changed then.

**Comment by Hozu** [comment]
You could probably just have the returned value be multiplied by 10, at the very end. Assuming it's supposed to always give you an amount that's a multiple of 10. Can it give like, 1234 TP return on retail?

**Comment by lenonk** [comment]
Yeah, you could.  I tested that and it works, but it seems unnecessarily hackish.  The current behavior is highly non-intuitive for those writing scripts.

**Comment by Hozu** [comment]
It can't take more TP than the mob has, as it specifically checks for that.

https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/spells/absorb-tp.lua#L43

**Comment by lenonk** [comment]
Yes, but it multiplies that value by MOD_AUGMENTS_ABSORB after the check.  Maybe I'm not understanding that part, but from what I can gather, that's checking for gear that improves the effect of AbsorbTP, in which case it could drain more than the mob has.  Maybe I'm wrong though.

**Comment by Hozu** [comment]
Oh you're right, that can happen.

**Comment by TeoTwawki** [comment]
> I'd like to know if there is a reason why addTP() multiplies it's parameter by 10

Happened because nobody wanted to find every instance of it to adjust it the right way, DSP easy out'd by multiplying. I doubt anybody would complain if you changed it so long as you caught every spot and made them all consistent.

**Comment by lenonk** [comment]
I’m working on it.  Currently I’m on bluemagic.lua, which is providing a bit of a challenge since I don’t know exactly what it’s doing.  I’m about halfway done atm

**Comment by TeoTwawki** [comment]
This got 100% resolved didn't it, we just forgot to close the issue?

**Comment by takhlaq** [comment]
i see pr merged i close issue
