### ISSUE TITLE
Occasionally when crafting, the resulting item doesn't appear immediately in inventory

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2876]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
1da5803

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Perform several of the same synth, occasionally, the resulting items do not appear in your inventory.
To get around this issue, you can 'sort' your inventory, and the items will then appear.

**Comment by helixhamin** [comment]
Related to the other sort bugs possibly?
https://github.com/DarkstarProject/darkstar/issues/1174
https://github.com/DarkstarProject/darkstar/issues/607

**Comment by takhlaq** [comment]
#607
