### ISSUE TITLE
Crash upon exiting a Limbus instance

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2879]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/2643851f28ef33e4ab1c5d1fdcaf0e98ba268bb4

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Once the last person warps out of the instance (since that's the only way to exit, time running out doesn't even end it...), the server crashes. Edit: Only happens if you warp out early, opening the final chest/time running out.

**Comment by Hozu** [comment]
Seems that the issue is probably being caused by someone outside of the zone/party being added to the BCNM somehow. When everyone else leaves, the BCNM still exists, and when it finally times out, server goes down.

**Comment by Mizzguy** [comment]
I have encountered this same issue. The report I'm getting seems that it's only tied with temenos, but as hozu mentioned above this seems to happen with different bcnm as well. I know there is other pr for them but thought I would chime in as it seems to be an issue with other servers as well.

**Comment by Hozu** [comment]
I've encountered it with both.

**Comment by Scavenge** [comment]
definitely getting this with limbus regularly.  always seems to be a lose condition.

**Comment by Mizzguy** [comment]
I've been doing some testing on my server. If you win you need to exit the proper way, instead I know like my server and others im sure, we allow commands to warp back to hp or a town. And this could have been the issue. Since ppl started exiting the correct way, there have been no crashes even when time runs out.

**Comment by Hozu** [comment]
It's hard to do that when someone who isn't even in the zone is put into the instance somehow, you know?

**Comment by Mizzguy** [comment]
That's true. Was just trying to add more to this as it came up.  I missed that  you had mentioned that in your other coment.

**Comment by nyczducky** [comment]
Another issue with the timeout in Apollyon is that once you go through the last teleporter, there is nothing that stops the BCNM. You actually end up in the lobby with the battlefield effect. Upon the timer running out on Limbus, you get "warped" to the exit which is in the lobby over and over again.

Not sure how to properly add in a BCNM win condition upon using the last teleporter where it will clean up the BCNM and reset all variables. When I tried, I ended up in a black screen. I think that's because there is no set exit and you need to treat it like Horlais peak and designate a set POS in the core?

**Comment by Kushdr** [comment]
Pretty sure I fixed this locally. Should also fix #2459

Just one small addition in each of the start NPCs and moving a function call around in battlefield.cpp

I can put the commit in later. at work now

**Comment by nyczducky** [comment]
@Kushdr Not sure if this was committed. Could you confirm?

**Comment by Kushdr** [comment]
It wasn't and I'm not near my computer. I can submit as soon as I can

**Comment by nyczducky** [comment]
@Kushdr Thx. Much appreciated.

**Comment by takhlaq** [comment]
i think we just need to remove player from battlefield in ccharentity destructor since when debugging the pointer's usually 0xdddddddd (freed memory in visual studio)

**Comment by teschnei** [comment]
It already removes them in DecreaseZoneCounter

**Comment by Hozu** [comment]
The basic problem is people other than the first person are not added to the battlefield. That's what is leading to the issues. From what @Kushdr told me elsewhere, that's what his fix did - ensured everyone was entered. This caused the others to lose their soap/card properly as well.

**Comment by nyczducky** [comment]
Solo queue still leads to BCNM not completing upon use of last teleporter in Apollyon. Also upon time out, the server crashes.

**Comment by Hozu** [comment]
I don't think any submission towards fixing it was made to DSP yet.

**Comment by takhlaq** [comment]
> It already removes them in DecreaseZoneCounter

ya but not in map_close_session or when d/c
https://github.com/DarkstarProject/darkstar/blob/824fbbd7c79eea6d43524c0d96131abffac56881/src/map/map.cpp#L732
https://github.com/DarkstarProject/darkstar/blob/824fbbd7c79eea6d43524c0d96131abffac56881/src/map/map.cpp#L837

**Comment by Brierre** [comment]
This is still an issue.  Additional party members after the first to click are not having their KI removed from their list, and at the end of the Limbus, it's not cleaning things up.  Solo, I have not encountered a problem, but as soon as I put my girl in a party, it creates a mess.  

It's almost like the leave codes are not defined.  There's no definitive way of "winning" a Limbus set up or something.  I'm not very good at the code yet, so forgive me if I'm pointing out the obvious to some of you.

**Comment by TeoTwawki** [comment]
open new issue if this is still happening in our post bcnm rework world.
