### ISSUE TITLE
[at]givexp command gives double the amount of exp

### ISSUE THREAD

**Issue by helixhamin** [DarkstarProject/darkstar#2887]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
All
(But last tested with 30160203_0)

**_Server Version_** (type `@revision` in game) **:**
All
(but last tested with https://github.com/DarkstarProject/darkstar/commit/cc1521dbc9bf056f63db216619dc20fa2cf25d5b)

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
To test, use the command [at]givexp number name, like [at]givexp 1000 Delaide
The message will say "Gave 1000 exp to player Delaide", but then the actual exp increase will show 2x the amount, and if you check the toons exp, it will also show the recorded 2x amount.

**Comment by Altalus** [comment]
Stupid question but are you sure your server configuration file does not implement EXP multiplicator?

 

______________________________

Guillaume Gingras

**Comment by Scavenge** [comment]
on our server we have x4 xp so if i want to give someone 10,000 xp for a merit i give them 2500

**Comment by helixhamin** [comment]
@Altalus @Scavenge Meh, yeah, I am an idiot...this is probably exactly what it is...

**Comment by Altalus** [comment]
Forgetting a detail does not make you an idiot :P

______________________________

Guillaume Gingras
