### ISSUE TITLE
Xiloader wont start the game

### ISSUE THREAD

**Issue by AycanS** [DarkstarProject/darkstar#2889]
**_I have:_**

The game worked last night.
Now when Im at the login screen, where I chose 1 or 2, I chose 1 and then enter the login info, nothing happens for 30 sec, then I get the option t
![939389_10156740928595128_525392921_o](https://cloud.githubusercontent.com/assets/17771885/13684618/db5fbdb8-e70c-11e5-8593-fe0fbfd049cd.jpg)
o chose 1 or 2 again.

And and the text "Autologin activated" also apared before "Connection to server"

- [ ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by xdemolish** [comment]
wrong repository
also didn't bother to fill out template

**Comment by AycanS** [comment]
Thanks you so much for helping me out

Date: Thu, 10 Mar 2016 13:18:18 -0800

**Comment by TeoTwawki** [comment]
@AycanS you are so welcome.

**Comment by AycanS** [comment]
Go fuck yourself 

Sendt fra min iPhone

**Comment by TeoTwawki** [comment]
@AycanS Stop being a moron, and then abusing people who contribute to this project. Your error is: posted in the wrong place, ignored the rules for reporting errors to THIS project, and isn't even a real error: invalid input = loop back to start. So no, you go F _yourself_

**Comment by teschnei** [comment]
One of the more common causes for this is when xiloader can't find the FFXI DLL, which should have the path to it stored in the registry.  Depending on how you installed it, you might have to reinstall it.  Also make sure it's actually up to date (you can check that in playonline viewer).

And please be a little more civil, next time.
