### ISSUE TITLE
Quested weaponskills are automatically awarded at the appropriate level.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2890]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
020be7a

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Quested Weaponskills are available as soon as you reach the appropriate skill level.

It would be nice to be able to toggle Weaponskills as unavailable/available via either scripts, database, or both. I believe the quests for these Weaponskills are already scripted; so it would be nice to add this to the list of implemented content! :+1:

**Comment by darvisgalka** [comment]
Settings.lua has a setting specifically regarding quested ws's like, Steel Cyclone, Asuran Fists etc. Can toggle for automatic learning and the skill for it.

**Comment by dazusu** [comment]
It is already set correctly. Skills are still awarded automatically.

**Comment by nyczducky** [comment]
I believe you receive the W/S but once you zone it is removed. I saw this happen on a few private servers. Happened to me on skill level 251 on Samurai. Saw Tachi: Kasha appear and then get removed once I zoned.

**Comment by a351must2** [comment]
I'm running into this same issue with client version 30161206_3.  Characters gain the Quested weaponskill when they pass the required level for the skill, but lose it as soon as they zone.  Server version is returning "unknown", but the build was pulled December 26, 2016.

**Comment by shawndrake2** [comment]
Also seeing this issue. Was awarded Asuran Fists automatically but lost it upon zoning.

**Comment by davismj** [comment]
I'm going to work on getting the work @ababyduck [put into the WSNM quests](https://github.com/ababyduck/darkstar-ahiru/tree/WSquests) integrated into core.

**Comment by davismj** [comment]
closed by https://github.com/DarkstarProject/darkstar/pull/4851
