### ISSUE TITLE
Level sync doesn't wear off when the syncee zones (again)

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2891]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/2643851f28ef33e4ab1c5d1fdcaf0e98ba268bb4

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Red dot doesn't appear next to syncee either. If the syncee zones, you can get the party synced to whatever level forever.

**Comment by metalfiiish** [comment]
Unable to reproduce since the code changes:
https://github.com/DarkstarProject/darkstar/issues/3949
https://github.com/DarkstarProject/darkstar/commit/e4145183db306202488a89bca5bf64c5fad44ff2

**Comment by Hozu** [comment]
I'll take your word for it. If someone runs into a sync problem, open a new issue.
