### ISSUE TITLE
Scripted type NM's not spawning.

### ISSUE THREAD

**Issue by Leelink1** [DarkstarProject/darkstar#2896]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160203_0

**_Server Version_** (type `@revision` in game) **:** (Says Unknown. but i got it from here like a hour ago)

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Mobs that spawn from a ???, or any HNM such as Behemoth, Aspid, Fafnir are not spawning. I believe these are spawntype 128 in the database. 

If you do a command to spawn them. they will spawn. And they then allow you to make trades to ??? to spawn them like normal. until the server restart again.

Known effected mobs.
Behemoth
Aspid
Fafnir
Leeches in Korroka tunnel for Nin Quest
Relic Shield NM Amaltheia
(Probley many others)

**Comment by hookstar** [comment]
I am having similar issues, I was able to get them to spawn if I comment out this for Genbu

 if **_(--GetMobAction(17309980) == 0 and _**
    trade:hasItemQty(1424,1) and trade:hasItemQty(1425,1) and trade:getItemCount() == 2) then
        player:tradeComplete();
        SpawnMob(17309980,300):updateClaim(player); -- Spawn Genbu
        player:showText(npc,SKY_GOD_OFFSET + 5);
        npc:setStatus(STATUS_DISAPPEAR);
    end
end;

**Comment by dazusu** [comment]
See #2897
