### ISSUE TITLE
GetMobAction() returning 16 when it should be returning 0

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2897]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
b47243c

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

A lot of scripted lottery NMs use "GetMobAction()" to check if an NM can be popped when a placeholder is killed. Usually, this _should_ return "0" if the mob is not popped; however - it is now returning "16" (Which I believe is 'roaming'). If the monster is not popped, should it be returning 16 for its action?

Expected: GetMobAction() should return 0 if the monster is not popped.

This has broken all scripted lottery NMs, and perhaps has other consequences where GetMobAction() is used in a condition.

**Comment by dazusu** [comment]
Related #2896

**Comment by hookstar** [comment]
Forced popped mobs are also in the same boat. For science, I commented out the getmobaction ==0 and the mobs were able to spawn correctly.

I don't return any errors in my logs, but the lua doesn't execute anything past the getmobaction.

Hope that helps...

**Comment by dazusu** [comment]
The problem is the wrong action ID is being returned. It expects 0, but gets 16.

**Comment by teschnei** [comment]
GetMobAction is deprecated, so it should be removed where possible.

That said, I'll still fix it.  Either scripted NMs dont get the despawn state (I suppose that's possible, not sure whether they should or should not yet), or GetMobAction should check IsSpawned instead of the state stack.

**Comment by xdemolish** [comment]
psh you updated it for the rewrite and made a poopy
also, i cant seem to find the laughing cry face to add my reaction to your comment so i thought i'd add a mix of everything
