### ISSUE TITLE
Mobs not using 2 hour abilities

### ISSUE THREAD

**Issue by Turylon** [DarkstarProject/darkstar#2901]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
5d489db1dd88bbeda78ec9954e707c483d658d

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Tested on all dynamis mobs on live and fresh test server.  Mobs are not using 2 hour abilities and in some cases pets ie scorpions are just standing at spawn and taking no action at all.

Sky Gods are not using 2 hour abilities.

**Comment by nesstea** [comment]
No mobs use 2 hours because it's not in the AI rewrite yet.

**Comment by Hozu** [comment]
Whenever it's to be reimplemented this check has to be modified:
https://github.com/DarkstarProject/darkstar/blob/d727dd77d55cc3a166869d8ba1c92dbe4a9df768/src/map/ai/controllers/mob_controller.cpp#L299

**Comment by takhlaq** [comment]
@teschnei

**Comment by TeoTwawki** [comment]
Note: Teo will volunteer to script all the 2hrs if y'all will throw agree out that core stuff + flag +mobmods (more than one) when its finished.

**Comment by davismj** [comment]
think this can be closed
