### ISSUE TITLE
Salvage - Instance Bug #2 (more Qutrub blinking)

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2917]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
ff4a4e4

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

There's still an issue with Qutrub in Salvage. As soon as they aggro (or you engage them), they start blinking like hell.

Note: This is **only** happening with Qutrub, not with Lamia.

The target fix is working; my monsters follow me - and people in other monsters can move their mobs around too without it affecting mine.

Video: https://youtu.be/kiKXH5w03zk

**Comment by teschnei** [comment]
Qutrub blinking has nothing to do with instances. Is that all this issue is?

**Comment by dazusu** [comment]
Yes, that's why I changed my comment/report (initially I thought it was an instance issue), but realised quickly that it wasn't. Qutrubs are just blinking rapidly and are untargetable as a result.

Forgot to change the title of the bug I guess :)

**Comment by teschnei** [comment]
We already have an issue for that. (And I don't see the bug title on my
phone)

**Comment by dazusu** [comment]
Closed issue.
