### ISSUE TITLE
Players can use items/cast spells when jailed.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2926]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/2643851f28ef33e4ab1c5d1fdcaf0e98ba268bb4

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Players are supposed to be able to do no actions whatsoever. Right now they can escape, though they will get put back in every time they zone.

**Comment by Hozu** [comment]
Also anyone who somehow escapes from jail is no longer put back into it whenever they zone... http://i.imgur.com/GDf1oyG.png

**Comment by Hozu** [comment]
In case I don't get around to it soon...
[01:45:24]	kjLotus	anyways, someone can PR @jail calling jailutils::Add and @pardon calling jailutils::Del

**Comment by tagban** [comment]
Set status effect to Terror.. :-D Worked for me!

**Comment by tagban** [comment]
Then I just remove it on Pardon. Set it for 99999 (10hrs)

**Comment by teschnei** [comment]
Taking fear mongering to the next level

**Comment by Hozu** [comment]
Finally remembered to take a look at this and um... https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/jailutils.cpp#L61 there's nothing there.

**Comment by teschnei** [comment]
It removes the controller, that's all you need.

**Comment by Hozu** [comment]
Erm, I called jailutils::Add in the lua binding and the char added to jail could still cast spells. Also zoning didn't send them back to jail.

**Comment by teschnei** [comment]
I don't think there's anything in place to prevent zoning in jail

**Comment by Hozu** [comment]
Before anyone who would zone while they were supposed to be in jail would be put back into it. It was pretty neat, actually.

**Comment by tagban** [comment]
I still say my solution works. :)

**Comment by TeoTwawki** [comment]
I think this got fixed and we forgot to close? Open new issue (and be loud about it) if I am wrong 😉 so we make sure its def gets/is fixed for good
