### ISSUE TITLE
mini fork avatar fight

### ISSUE THREAD

**Issue by Haightred** [DarkstarProject/darkstar#294]
I realize it's probably not of high concern, but I wanted to bring up that the level 20 mini fork avatar fights the mob is running on the level 60 encounter script, allowing the mob to use merit moves and multiple astral flow moves, I.e. diamond dust. this makes the fight unbearable.

**Comment by whasf** [comment]
There has been a lot of changes in the last 2 years, please revisit and re-open if it is still an issue.
