### ISSUE TITLE
Mob deaggro timer doesn't reset back to 25s when acted on by a player

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2941]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/8f2765e5f9a29ac5f9bd75cb2da6de36a610a8bc

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Makes sleep/bind nuking stupid hard because the mob will deaggro and regen HP. Also if you sleep a mob, it will deaggro when it wakes from a long enough sleep, even if it was woken by damage.

**Comment by dazusu** [comment]
I've never in all my time playing seen a monster deaggro while it's asleep, if the mob is still in render range.

**Comment by Hozu** [comment]
It will deaggro the instant it wakes. Even if it's woken up by being hit.

**Comment by dazusu** [comment]
On retail? I've never experienced this behavior... ever.. If this is on retail, it must be new (within the past 18 months)?

**Comment by Hozu** [comment]
On DSP that's what it's doing. It's not supposed to.

**Comment by Hozu** [comment]
Hm further testing suggests if the last action on a mob was a melee attack, it will never deaggro (I hit a worm, stood at range 20 and I never lost it). But someone else casting on a worm from range, even after a melee attack, it will deaggro.

**Comment by bendangelo** [comment]
Right sleep should reset the timer. I'm pretty sure bind already does that. A mob getting attacked does not reset the timer, but the worm should not deaggro if it can still see you.

**Comment by teschnei** [comment]
This is a quick fix when I get back to my computer

**Comment by Hozu** [comment]
I assume the 25s timer resets when sleep/bind actually wears off, @bendangelo ?

**Comment by teschnei** [comment]
Bind resets every tick. Pretty sure sleep doesn't reset anything, just
pauses

**Comment by teschnei** [comment]
No, bind pauses... Whatever, I'll have to double check later

**Comment by bendangelo** [comment]
Yeah so they should both reset on wear off. I think I had bind reset every tick just because it was easiest to implement.

**Comment by Hozu** [comment]
To add on to my comment about worms deaggroing players while they're in casting range despite players casting on them, it also happens with ranged attacks. So to summarize, if you melee a worm then back out of melee range, it won't deaggro (provided you're in casting range). But if you cast on it/shoot it when out of melee range, it will deaggro.

**Comment by Hozu** [comment]
Pretty sure mobs in BCNMs don't deaggro ever, as a general rule either. Just saw one deaggro.

**Comment by Hozu** [comment]
Mobs also have no neutral time after deaggroing, they instantly despawn/move if able.

**Comment by bendangelo** [comment]
These are big issues, someone will have to look at them.

**Comment by Hozu** [comment]
Also got a report that a NM despawned after it deaggroed, hm... Leaping Lizzy to be exact.

**Comment by helixhamin** [comment]
I actually had this happen, BCNM mod deaggroed (But did not depop) during the antican ZM battle. After it woke, its name went yellow again, although its two friends were still on me.
