### ISSUE TITLE
charmed pets pettp not working

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#2942]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
8f2765e5

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Using <pettp> on charmed pets always returns 0, but sic seems to work correctly. 
Also works fine on jug pets.

**Comment by ymkc** [comment]
Using pettp on charmed pets...

**Comment by Hozu** [comment]
I noticed with summons, whenever I used exec to set the tp to an amount, pettp was reporting a different value than what I set. Like, I set it to 800 and it would have 1400.
