### ISSUE TITLE
BST can charm uncharmable mobs

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#2943]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0 

**_Server Version_** (type `@revision` in game) **:**
8f2765e5

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
As a BST it's possible to charm morbols, wyverns, goobbues, manticores, hippogryphs

Afaik this was not possible on retail

**Comment by helixhamin** [comment]
I want to charm Fafnirs xD

**Comment by ymkc** [comment]
NM's aren't charmable, but Storms of Fate Bahamut is checked as TW and is charmable :D 

Unfortunately not mobs around to have fun with a bahamut pet ...

**Comment by ymkc** [comment]
btw, you can "zone" bahamut, but you can't make him fight
