### ISSUE TITLE
Dyna Xarcabard > Animated NM's Drop Tables Empty

### ISSUE THREAD

**Issue by Arthurdales** [DarkstarProject/darkstar#2947]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

  Dynamis Xarcabard Animated weapons drop tables appear to be empty (e.g. Animated Scythe) and nothing drops.

**_Client Version_** (type `/ver` in game) **:**
30151223_0

**_Server Version_** (type `@revision` in game) **:**
8f2765e5f9a29ac5f9bd75cb2da6de36a610a8bc

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Kill animated scythe. Nothing drops.

**Comment by Hozu** [comment]
Uh, you're supposed to kill the 15 demon NMs first. Yeah Dynamis is mostly old-school.

**Comment by Deadwing888** [comment]
When the chamber of souls sets free its captive spirits there is an animationsub change on the weapons that enables their fragment drops.

**Comment by Fiocitrine** [comment]
Some of the Animated weapons have drop tables with items and some don't. Not sure if this is old school retail or not, as I never did Dyna Xarcabard.

**Comment by Hozu** [comment]
I've never seen an animated weapon *not* drop a fragment after the 15 NMs are defeated.

**Comment by Arthurdales** [comment]
I havent been able to test this conclusively in game because of DynaXarca issues with lag.  Currently the animated weapons auto spawn upon entry (which i dont remember from retail) but they dont drop anything when killed. So you could be and are probably right.

**Comment by Arthurdales** [comment]
The lag issue with dyna xarca was fixed. Last night i took an alliance to kill NMs;  Unfortunately, not all NMs spawn. Plus only one time extension mob appears.  Until that is corrected i cannot test/validate that animated weapons drop their respective relic upgrade item.

**Comment by Hozu** [comment]
I've noticed that sometimes not all mobs spawn. It's weird.
