### ISSUE TITLE
Astral Flow

### ISSUE THREAD

**Issue by Haightred** [DarkstarProject/darkstar#295]
One other summoner issue is that Astral Flow moves from the summoners avatars hit for 0 damage against mobs. If this were fixed, the importance of getting the proper  for the fights would fall drastically.

**Comment by xdemolish** [comment]
is this still an issue?

**Comment by Haightred** [comment]
I believe so. I just recently began playing again and haven't tried out smn
yet. I'll be logging in shortly and will email you again. My in game name
is Haight.

**Comment by nesstea** [comment]
Yeah still a prob.

**Comment by teschnei** [comment]
Yes, still have no script

**Comment by teschnei** [comment]
0a46c30b03e511be3695d1ea76f4756c070eab97
