### ISSUE TITLE
Summoned Elementals do no cast spells.

### ISSUE THREAD

**Issue by Topace1** [DarkstarProject/darkstar#2954]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0
**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/ba2702c6eb381315bab59961a6187a95b5529cd8
**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The summoned elementals do no cast any spells no matter how long I have them out and fighting.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/pull/3409
