### ISSUE TITLE
Lagfest in DynaXarcabard When Engaging Kindred Mobs  (OLDSCHOOL)

### ISSUE THREAD

**Issue by Arthurdales** [DarkstarProject/darkstar#2956]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30151223_0

**_Server Version_** (type `@revision` in game) **:**
8f2765e

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Attack an eye > Kindred mobs spawn > Attack kindred > Lagfest ensues

**Comment by Hozu** [comment]
Are you in an alliance when this happens? I think there are two things going on - being in an alliance causes lag, and mobs that can't find a path cause lag. The Kindred NMs end up being both.

Also, for what it's worth, the server I play on reversed the tick rate change, and it alleviated some of the general "lag" (ie. game server slowdown), but not the spikes.

**Comment by Arthurdales** [comment]
Yes we've raided DynaXarc as an alliance. Is there a known "fix" to correct mob pathing?  Or is that something that is unsolvable to date?

**Comment by teschnei** [comment]
If there was a known fix, this probably wouldn't be an issue?

I will try to reproduce it later, but I'm not making an alliance for it (and I'm only testing in release mode)
