### ISSUE TITLE
2-3 bug

### ISSUE THREAD

**Issue by oztralian** [DarkstarProject/darkstar#2961]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Doing bastok 2-3. Windy then sandy. The bastokian npc helaku will not talk so i cant proceed.

**Comment by Hozu** [comment]
I believe the issue was that while the missionStatus var was set properly, the actual mission isn't uh... whatever part 2 was.

**Comment by TeoTwawki** [comment]
Helaku suffers from _Halver's Disease_
If only we had quarantined patient zero before it was too late.

**Comment by oztralian** [comment]
Anyway to fix it? I dont remember can i abbondon and redo the other way?

**Comment by TeoTwawki** [comment]
`@setplayervar NameHere MissionStatus 11` I think..

**Comment by Hozu** [comment]
If you finished up with the Windy leg, try setting the MissionStatus var to 7.

https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Northern_San_dOria/npcs/Helaku.lua#L40

If that works, then that check should check for w/e it was set to instead (so check the var first before setting it, I believe it gets set to 8).

**Comment by oztralian** [comment]
Let me make sure this is correct. 
@setplayervar Hotcarl MissionStatus ==8
Should allowme to talk to helaku?
Or should i go to the bcnm step?
Sorry for the hassel just want to make sure i do ot right the first time.

**Comment by Hozu** [comment]
First do @checkvar playername MissionStatus, see what it's currently set to. I believe it will be set to 8. If it is, try @setplayervar playername MissionStatus 7, and let us know if that worked.

**Comment by oztralian** [comment]
Ok thank you

**Comment by TeoTwawki** [comment]
At some point someone is going to have to sift through all the 2-3 NPCs and make sure they all use correct conditional checks for their mission steps and never mistakenly change variables for players from the wrong nation/mission (I had ages ago visiting wrong consulate would screw you, dunno if it was ever really fixed)..

Even when they are all correct we'll still occasional have var problems. Players who are multi boxing randomly (less constant than even the auto-homepoint thing) have one of their characters not receive a variable change or keyitem change.

**Comment by oztralian** [comment]
Gm cmd on server. They reset it to 7. Trying now

**Comment by oztralian** [comment]
Worked perfectly tyvm

**Comment by TeoTwawki** [comment]
#2971 well, one down..
