### ISSUE TITLE
Unused Lachesis Orbs disappeared from remaining participants during run.

### ISSUE THREAD

**Issue by FrankWHansen** [DarkstarProject/darkstar#2967]
Group of 4 characters, 2 people dual boxing.
All four characters grabbed an orb from Shami to do Operation Desert Storm.

When we were getting ready for the third run, the two remaining players (one char belonging to each person) were unable to locate their lachesis orbs in inventory.

The character that used orb on second run still had her used orb in inventory. Unable to reuse this, of course.

I'm thinking either the two orbs went missing some time during the second run, since no one noticed any missing orbs between first and second run... or there's some hoopla with dualboxing on computer and when player1's first character went first, it screwed up his alt character's orb, and the same happened to me when I as player2 went second, that my alt lost his orb during that second entry.

**Comment by helixhamin** [comment]
Please use the form provided when reporting issues

**Comment by R3P0FFXI** [comment]
@FrankWHansen There are issues with dualboxing

**Comment by xdemolish** [comment]
server revision? client version? reopen following the issue template
