### ISSUE TITLE
Telling zoning apart from log out/in

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#297]
There are some things on retail where you can log out and not lose progress or an effect, but will lose them on zone. Example include the the sheep's meat places in the campfire in South Gustaberg and the recently added Prowess effect.

The script in South Gustaberg makes use of needToZone() and EFFECT_PROWESS uses a flag in its database entry. When I asked about it on IRC Kj said he thinks needToZone() does it wrong then. I do not know how to change this behavior to be more retail, so currently prowess buffs wear off on logout/connection loss and will cause you to lose your progress on that galkan sausage quest if you were doing that. 

This likely effects or will effect other things these are just two examples that come to mind.

**Comment by maxtherabbit** [comment]
is this still a thing?

**Comment by TeoTwawki** [comment]
Yes. needToZone() stipp has its state changed on relogging into same zone and shoudl not. Along with my failure to work aroudn this issue for buffs that need to be removed *only* on zoning, but are stripped by logout.

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/203a30332312803e4b9fb8f7504a88b81bf3a50d

**Comment by xdemolish** [comment]
0 duration effects is another issue, which i will probably fix later (once i come up with a non-ugly way to do it)

**Comment by TeoTwawki** [comment]
Thanks demo.
