### ISSUE TITLE
Not all NMs and TimeExt Mobs Spawn Within Dyna Xarcabard

### ISSUE THREAD

**Issue by Arthurdales** [DarkstarProject/darkstar#2973]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30151223_0

**_Server Version_** (type `@revision` in game) **:**
8f2765e

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Engaged each set of 3 NMS within Dyna Xarca.  Some sets only spawned 2 NMs and not 3; therefore, cannot kill all 15 NMs needed to kill animated weapons and obtain their respective drops. Also, only 1 time ext mob near the beginning of the zone is spawning.  There should be 4 more.

**Comment by Hozu** [comment]
Seems to be an issue with dynamis in general, sometimes not all of the mobs spawn.

**Comment by R3P0FFXI** [comment]
Dont walk in at level 99 and 1 shot AOE everything. If you aggro the mobs normally as you would a 75 they all pop as they are supposed to.

**Comment by wrenffxi** [comment]
This can be closed.  All mobs now completely despawn during cleanup, and will spawn when eyes are aggroed.
