### ISSUE TITLE
Pouch of Weighted Stones

### ISSUE THREAD

**Issue by XephyrDragonos** [DarkstarProject/darkstar#298]
I believe it was mentioned that these were implemented at some point. I went to Garliage Citadel the other night and was unable to collect the stones from the ???. I believe an update must have broken them =(

**Comment by nesstea** [comment]
@maxtherabbit  they are in the wrong location. they are in the ceiling right now.

**Comment by maxtherabbit** [comment]
alright then

**Comment by teschnei** [comment]
They are supposed to be in the ceiling

**Comment by nesstea** [comment]
@teschnei http://wiki.ffxiclopedia.org/wiki/Pouch_of_weighted_stones

**Comment by nesstea** [comment]
https://github.com/DarkstarProject/darkstar/pull/970

What should I do about the old one?
