### ISSUE TITLE
Auction House concerns

### ISSUE THREAD

**Issue by Annihilus343** [DarkstarProject/darkstar#299]
one of my toons made a large number of Artificial Lens skilling up and saved them for Prism Powders later, I posted them on AH for free space in inventories for 1500 each. I'm now trying to buy them back and can't for 1500, not a single one that I put up. I tried for more and still couldn't buy them. I cleared my sales status and reposted what I had to after relogging and none of the lens showed up though the AH still has 54 posted. I wouldn't make the connection to a bug but Djinn is also having trouble buying griffon hides for absurd amounts of gil. Maybe a bug, maybe something else Idk, figured I'd mention it.

**Comment by whasf** [comment]
AH should be somewhat OK now. Please revisit and re-open if the issue is still occurring.
