### ISSUE TITLE
PW Using Brainjack Crashes Zone

### ISSUE THREAD

**Issue by Arximiro** [DarkstarProject/darkstar#2999]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
Shows as Unknown (Nasomi Server)

**_Source Branch_** (master/stable) **:**
Not sure

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
If PW uses Brainjack while in chariot form and connects it crashes the entire zone. If it is caught by a shadow or stunned it is fine.

**Comment by whasf** [comment]
Thanks for the report, but Nasomi is usually pretty behind on versions. I'd like him to chime in this with a version and if possible, update to latest.

**Comment by Hozu** [comment]
Pretty sure anything to do with PW has been untouched for almost a year now.

**Comment by Fiocitrine** [comment]
When I fought PW on a recent version test server, he was doing Dvergr TP moves in his various forms. Of course they went all wonky when executed, but he wasn't using his other form's TP moves.

**Comment by Arximiro** [comment]
He changes forms correctly and uses TP moves on Nasomi. Brainjack will just crash the zone if it lands on the target.

**Comment by Fiocitrine** [comment]
Well to be fair, Nasomi has stuff on his server that we don't have on ours. Ours is extremely close to what DSP is at now. Like whasf said, Nasomi is possibly behind on versions.

**Comment by Raycian** [comment]
Are you using gearswap?

**Comment by Arximiro** [comment]
No one is using Gear Swap. PW used Brainjack on an Avatar last night and it crashed the zone. It did it on a BST pet not long ago and crashed the zone also. As long as it hits a shadow it causes no issues. It's probably just a Nasomi thing. Thought I'd post just incase it isn't.

**Comment by Hozu** [comment]
It doesn't even seem to be charming players correctly, see other charm moves. Though I'm not sure what to do about it being a physical move that applies the status...

@Raycian That's a more problematic bug... I imagine changing gear while charmed is what does it, since you're not able to via the client.

**Comment by tagban** [comment]
I was having issues with PW crashing my server last week so I disabled him entirely. That was on bnet.cc
We update server around once a week, so as far as I know now still crashes server.

**Comment by TeoTwawki** [comment]
Pandemonium warden went all bugged to hell after both the mobskill refactor and then AI refactor. He's crashy in multiple ways right now, and some of the code he had was sort of buggy anyway (like for anyone that enabled his ability to self depop, there was a chance he'd get "stuck" in the action trying to despawn). We even had his dverger model wrong, he got the lamps and the lamps got his. You shoulda seen it before I made commits cleaning it up..

I really recommend disabling him till he's rewritten (again).

p.s.
Like half the mobskills, not just PW, have completely incorrect animation IDs. I have a large pile of corrections I need to PR, haven't had time yet.
