### ISSUE TITLE
No EXP gain when high level player outside party assists with healing.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#3002]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
5ca0bfd

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
If a player is fighting a monster, then a player outside the PT (who is higher level) heals that player, that player will **not** receive EXP from the monster, even though the outside player did not attack the monster.

**Comment by Hozu** [comment]
I've only noticed it happening if the mob was to take a swing at the high level player (or at least the high level player reaches the top of the hate list). You sure it happens regardless?

**Comment by dazusu** [comment]
Even if the mob takes a swing at the high level player (or the player reaches the top of the hate list), it still should **not** affect the EXP of the player offensively attacking the mob.

In my testing, it's happening regardless, though :+1:

**Comment by Hozu** [comment]
Well it's not supposed to, but knowing how it's being applied helps pinpoint the issue.

Though I do have to say I like it this way.

**Comment by dazusu** [comment]
Open to abuse; that's probably why it's not that way in retail.

It seems the issue is in the DistributeExperience method.

**Comment by helixhamin** [comment]
Correct me if I am wrong, but didn't SE implement something similar? I remember everyone used to let the high level mage take hate, then the dunes parties could slowly kill the mob with little worries. But, I also remember something about the mage using spikes, so was that the only way the exp was killed in retail? Sorry, it has been a while.

**Comment by dazusu** [comment]
Like we have discussed here, if the high level player acts offensively, they will then be registered as the highest level player to attack the monster; and EXP will be based on that players level.

So yes, if a Mage is using a 'spikes' spell, that counts as acting offensively on the monster; so EXP would be ruined.

However if the Mage "tanks" the monster, but doesn't deal damage - then EXP is still awarded.

**Comment by maxtherabbit** [comment]
is this still a problem?

**Comment by Hozu** [comment]
There wasn't a commit specifically to fix this, so I'd say most likely.

**Comment by Lagosaurus** [comment]
This is still an issue.

**Comment by eraffxi** [comment]
i am also told that not only do you get no exp, but no drops either. almost like it's been called for help on

**Comment by Scavenge** [comment]
but yes it's still an issue

**Comment by dazusu** [comment]
This is still an issue.

**Comment by Manticmage** [comment]
It is still behaving this way. Really hoping this is given priority soon as it kills Power Leveling which was always very common thing in Retail FFXI.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/9dfcfe81110648161481af1d29ded3d736c77301
