### ISSUE TITLE
Monsters no longer turn to face players who are engaged.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#3003]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
5ca0bfd

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Monsters no longer turn to face players, if you run behind the monster for example - it will continue to face the way it was facing when it engaged you.

If you run out of range and the monster has to follow you, it will then turn to face you again until you are in range - then direction checking seems to stop completely.

![img_20160406_135622](https://cloud.githubusercontent.com/assets/7009763/14317330/aa3a466a-fbff-11e5-8fd5-5026cac8b55a.png)

**Comment by teschnei** [comment]
you're 100% sure this was after 1abd581c2a2c7c439ba646735731360aede55c58?

**Comment by ElectronJunkie** [comment]
I ran into the same problem yesterday but was holding off on reporting to see if it was an error on my part updating yesterday. The problem occurs only as long as the mob does not have to change location, if you back up a bit it will turn as it moves.

Ver 30160203_0
Rev 1224572a

**Comment by teschnei** [comment]
Yes, it would have been broken until 1abd581c2a2c7c439ba646735731360aede55c58 (last night)

**Comment by ElectronJunkie** [comment]
The change was pushed earlier today fixed this... ("moved engaged status further down than movement" ...stuck at work can't look up changes)

**Comment by dazusu** [comment]
Gonna pull latest code and try it

**Comment by teschnei** [comment]
Your report says you're already on a later revision. Did you forget to
rebuild?

**Comment by Altalus** [comment]
I tested that commit and it did fix it on my server FYI.

 

______________________________ 
Guillaume Gingras

**Comment by dazusu** [comment]
I'm thinknig I didn't upload the latest exe to my server. I never run 
dsp locally (I only build it on my machine in release config); - so 
yeah, I think I screwed up deployment. Gah.

**Comment by Altalus** [comment]
I do think this is a fixed issue. I have a server updated to the latest commit and do not experience this.

**Comment by dazusu** [comment]
It is fixed
