### ISSUE TITLE
Settings file in windower4 keeps resetting after its been saved when launching windower 4

### ISSUE THREAD

**Issue by AycanS** [DarkstarProject/darkstar#3006]
**Settings file in windower4 keeps resetting after its been saved when launching windower 4. I tried to install the windower4 folder in 3 different Places now, desktop, download folder and in programfiles. All results in the settings file beeing resat back to the way it was before i made the changes in it. 
**

- [*] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **Not able to log on**

**_Server Version_** (type `@revision` in game) **not able to log on**

**_Source Branch_** (master/stable) **Sorry. Not sure about this.**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by xdemolish** [comment]
post on the forums, bug tracker is for issues related to the server not windower

**Comment by tagban** [comment]
Just a heads up this is likely a computer permission issue. But demo is right post this on windowers forums
