### ISSUE TITLE
Broken page in Ifrit's Cauldron

### ISSUE THREAD

**Issue by Samikana** [DarkstarProject/darkstar#3007]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160203_0

**_Server Version_** (type `@revision` in game) **:** b104bbb028c00fe7b3ea88fe0c89f37a4f67f0e8

**_Source Branch_** (master/stable) **:** stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Page 1 in Ifrit's Cauldron lists as 0 Volcano Wasps/0 Volcano Gases, as well as target level 0..  The result is consistent whether you close out of the book, relog.  

It should be 4 volcano wasps, 1 volcanic gas.  Target level 61~68.

**Comment by Hozu** [comment]
Hm? That should have been fixed in my commit a month ago... https://github.com/DarkstarProject/darkstar/pull/2873

**Comment by Samikana** [comment]
@Hozu I saw that commit, but being it was so long ago and our server is up-to-date since then, I figured maybe it wasn't working besides the fact.  :/

**Comment by Hozu** [comment]
I just checked on the server I play on and the book displays properly for page 1.

**Comment by Samikana** [comment]
Not sure then.  :< 

![halsey_2016 04 09_134136](https://cloud.githubusercontent.com/assets/18128996/14405257/cfa54f70-fe58-11e5-8184-a3bf176c32bc.png)
