### ISSUE TITLE
Self casting magic and job ability problem.

### ISSUE THREAD

**Issue by Genesis-Legion** [DarkstarProject/darkstar#3009]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160203_0

**_Server Version_** (type `@revision` in game) **:** b104bbb028c00fe7b3ea88fe0c89f37a4f67f0e8

**_Source Branch_** (master/stable) **:** Stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Talk to an NPC (tested on bastok mines NPC to the right of MH entrance, Also worked with the homepoint)
Attempt to use an ability or spell on yourself (ex: /ja Hasso Genesis) and it'll fail throwing an error as if you mistyped it. But if you were to replace your name with < me > it'll work fine.
The first command works with no problems until you talk to an NPC, after which is breaks then continues to work after you zone.

**Comment by teschnei** [comment]
That's interesting. Have you tried unloading all your ashita/windower
plugins?

**Comment by Genesis-Legion** [comment]
Yeah, I missed the copy/paste, tried with no plugins on ashita and windower.

**Comment by teschnei** [comment]
I wonder if that happens on retail. The name to targid replacement is
client side, but maybe something on our side is messing it up

**Comment by Genesis-Legion** [comment]
I just recently not to long ago updated my client (before latest update) so I'd like to hope my files aren't corrupted.

**Comment by xdemolish** [comment]
works fine for me
