### ISSUE TITLE
character values not being erased when deleting a character

### ISSUE THREAD

**Issue by Xaver-Entropia** [DarkstarProject/darkstar#3011]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_0 (updated one hour before this)

**_Server Version_** (type `@revision` in game) **:**
unknown, my own private server updated just an hour before this issue

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
when deleting a character through "Delete Character" option in main game menu is not erasing values from the following sql tables...

char_recast
char_spells
char_style

havent tried it with a character with merits, but i have a feeling thoose wouldn´t be erased either from char_merits

**Comment by Hozu** [comment]
If you erase a character, then create a new one, it should use the next lowest charid, which would be the one from the deleted char. I wonder if it would clear out all those values.

**Comment by tagban** [comment]
It doesn't Hozu
