### ISSUE TITLE
Can't make respawn times longer than a mob is currently set to respawn for

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3012]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/ec30b55f7457dbfbbe190ed181c4b83e7e07871d

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
If a mob is set to respawn in say, 2 minutes, you can't set the respawn time to be 5 minutes, for example. Used to be able to do that. Affects mobs with various spawn times, including scripted.

**Comment by Deadwing888** [comment]
That could explain why I've been having such problems trying to get aery spawns working correctly...

**Comment by teschnei** [comment]
what are you using to set the respawn time?

**Comment by Hozu** [comment]
mob:setRespawnTime

**Comment by teschnei** [comment]
What's stopping you from setting it?

**Comment by Hozu** [comment]
If the mob has a shorter current respawn time than what I set it to, it uses that instead.

**Comment by xdemolish** [comment]
can't reproduce this, used setRespawnTime to set respawn time to 3s then 180 and it worked fine

**Comment by Hozu** [comment]
I assume you tested this on a mob which has a base respawn time longer than what you specified? I'm beginning to wonder if this only applies to mobs with a normal spawntype, which this shouldn't be used on anyway...

**Comment by Hozu** [comment]
I guess I misinterpreted a change what happens during server boot (mobs are spawned before onZoneInitialize happens). Setting the respawn time works just fine.
