### ISSUE TITLE
Game Server Crash - Status Effect?

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#3016]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30160203_0

**_Server Version_** (type `@revision` in game) **:** cf2882998d6a2d8147e679195985ea8abd69ca53

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Not entirely sure, providing crash dump. We've been having weird crashes. This appears to be trying to get status effect information on a null target?

Dump: https://www.dropbox.com/s/8szatbxuig4z6ni/Crash4.9.7z?dl=0

**Comment by tagban** [comment]
This all being said, I know I'm on a 2 day old version so am rebuilding from today as of right now and will continue to run in debug to see if I can catch anything else.

**Comment by Hozu** [comment]
Good thing you got the dump, there are over 1300 instances of hasStatusEffect in scripts...

**Comment by tagban** [comment]
:)
