### ISSUE TITLE
Players client crash if target mob becomes untargetable before the spell completes

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3023]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/ec30b55f7457dbfbbe190ed181c4b83e7e07871d

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Spell should stop to prevent said crash.

**Comment by teschnei** [comment]
Untargetable? Are you sure you don't mean something else?

**Comment by Hozu** [comment]
Oh right, worms use HideName. But I wouldn't be surprised if it also happened with HideModel and Untargetable.

**Comment by teschnei** [comment]
What is this happening with? Worms? Antlions?

There are a lot of cases where stuff cast while being untargetable (all of
those scripted Abyssea NPCs, for example)

**Comment by Hozu** [comment]
Worms, when they go underground while you're casting a spell on them, the spell still attempts to cast on it, which causes a client crash. Same issue as before when curing a player that would die mid cast would cause a client crash. I assume there will be a similar thing with Antlions but I never really tried that out.

**Comment by Mizzguy** [comment]
I'm having the same issue with worms but they also loose hate half way through the fight.
