### ISSUE TITLE
Hidden mobs can cast spells.

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3024]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/ec30b55f7457dbfbbe190ed181c4b83e7e07871d

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
While testing out antlion stuff, I noticed that when I deaggroed Alastor Antlion it was attempting to cast Stoneskin repeatedly while hidden, though it could never complete the spell.

**Comment by Hozu** [comment]
Worms too, but when they cast on players they don't unhide their name so you can't even fight back.

**Comment by xdemolish** [comment]
are worms supposed to be able to cast while hidden (and then unhide)?

**Comment by Hozu** [comment]
Worms don't cast spells when hidden, it's only like alastor antlion after it deaggros.
