### ISSUE TITLE
Enmity caps are too low.

### ISSUE THREAD

**Issue by Raycian** [DarkstarProject/darkstar#3030]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The VE and CE enmity caps are too low at 10,000. Retail is 30,000 each.
https://www.bg-wiki.com/bg/Enmity
![enmity](https://cloud.githubusercontent.com/assets/17800871/14438901/35107710-ffdd-11e5-8f95-ccd55c44920d.png)

**Comment by teschnei** [comment]
They are 30,000 now of course, but only for about a year now ;)

**Comment by Raycian** [comment]
You're right. They tripled them on 3/26/15. I apologize. Can this be deleted?

**Comment by teschnei** [comment]
You can close it if you wish (technically it is still wrong, but I wouldn't
want to implement it unless we do all the other recent enmity changes at
the same time).
