### ISSUE TITLE
Certain Notorious Monsters are not checking as "Imposible to gauge"

### ISSUE THREAD

**Issue by Xaver-Entropia** [DarkstarProject/darkstar#3045]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
Unknown, clean server clone done yesterday from master branch

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The monsters i have found so far are...
- Highlander Lizard
- Ghillie Dhu.

Both located at Konchtat Highlands.
I guess they are just missing the NM flag... wich I THINK is located in the mob-pools table, 13th value
If someone could confirm this, i can correct the values and chek for other mobs which might be missing it

**Comment by TeoTwawki** [comment]
Huh. Thought I already fixed those once before (was my fault they were originally missing them, on the 2 you listed). You are correct about the cause and how to fix it. Some have the wrong name flagging too ("_The Namehere_ readies" vs "_Namehere_ readies").

**Comment by TeoTwawki** [comment]
..Did these get fixed? I don't recall.

**Comment by wrenffxi** [comment]
Just tested.

Highlander lizard is "Impossible to Gauge!" and referred to as "The Highlander Lizard."
Ghillie Dhu is "Impossible to Gauge!" and referred to as "Ghillie Dhu."

**Comment by TeoTwawki** [comment]
thanks. those 2 sound right then. any other NM with same problem someone just let us know,
