### ISSUE TITLE
Unable to advance Aht Urhgan mission "President Salaheem" 

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3048]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
a7898bb

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
After talking to Salaheem, then talking to Assault NPC then going back to Salaheem, she keeps saying the same line, "God girrrl, keep getting those jobs done!" 
I had taken a look at the script

https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Aht_Urhgan_Whitegate/npcs/Naja_Salaheem.lua

 and it seems one has to wait 1 full real day and zone before she'll give you the quest. I'm unsure if this is where the issue is or not. 

Update: so I tried to force the CSID in line 35 and it just freezes my player until I release them. I'm guessing it's not the right CSID.

**Comment by teschnei** [comment]
Did you wait a full day yet?

**Comment by Fiocitrine** [comment]
It's been well over a day, I started the last CS around 1pm EST yesterday

**Comment by TeoTwawki** [comment]
Did you zone? You have to zone, the mog house doesn't count, and even if you waited a day if you never left whitegate this won't go forward.

**Comment by TeoTwawki** [comment]
p.s. the cs ID is correct. it won't work without all the params forced to zero.

**Comment by Fiocitrine** [comment]
TeoTwawki, I zoned and wait a full day in Bastok. I keep getting the "standard" dialog from Naja.

**Comment by TeoTwawki** [comment]
Checked with Whasf, you had the old var and not the new one, he fixed that so your mission should work now

**Comment by Fiocitrine** [comment]
yay thanks Teo

**Comment by TeoTwawki** [comment]
anytime vars change that happens, GM commands or db edit is required.

**Comment by Fiocitrine** [comment]
This I say, fix eet!
