### ISSUE TITLE
Zanshin Issues

### ISSUE THREAD

**Issue by TheMuffinPirate** [DarkstarProject/darkstar#3052]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_0

**_Server Version_** (type `@revision` in game) **:**
Unknown

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **
Zanshin attacks can trigger on a multi attack or another zanshin attack (should not be possible)
This often leads to a Samurai attacking a huge numbers of times per round till they hit successfully. 
With the 100% Zanshin GKat the sam continues attacking until they hit succesfully or reach 8 attacks per round.

**Comment by Hozu** [comment]
For WSs, Zanshin also forces the hit to land if rand(100) < zanshin mod value on the player (barring PD). It should be checking accuracy.

Thankfully, if DA/TA/QA procs on your melee swing, Zanshin does not.
