### ISSUE TITLE
Random number generator not seeding properly.

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#3056]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** issue not related to client

**_Server Version_** (type `@revision` in game) **2 weeks old**

**_Source Branch_** (master/stable) **master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

![Dilbert](http://assets.amuniversal.com/321a39e06d6401301d80001dd8b71c47)

When the server is initially booting the random numbers it chooses will always always be the same. This includes math.random in onmobinitialize as well as initial spawntimes for mobs set in zone.lua

One way of checking this is by printing a random number on server boot.

In game it can be most easily noticed at behemoth which is theoretically set to initially spawn 15mins-3hours after boot but in actuality will always choose 2 hours 26 minutes.

**Comment by teschnei** [comment]
Which random number generator? The core's, or the lua engines?

**Comment by Deadwing888** [comment]
It seems to me that random number generation within lua will produce the same numbers after server boot up until the point that the random number generation is called in a different order (or different time I'm not sure which).

I don't know enough about core to know if there is a problem or even how to identify it.

**Comment by teschnei** [comment]
I doubt there's a problem with the core's generator, I know exactly how
it's seeded.  Would like to move Lua's to the core's, but haven't done so
yet.

**Comment by Deadwing888** [comment]
If core handles things like synthing, then that seems pretty solid to me. I have noticed no patterns in synthesis after server boot.

**Comment by TeoTwawki** [comment]
We're technically supposed to be calling the function to change the seed before every instance of lua's RNG. It would be trivial to wrap it then find+replace all the instances of `math.random(` but if we're going to move to calling the core's RNG then we may as well wait and do that.

Keep in mind streaks are expected sometimes anyway, but its been known for awhile that the way we've been doing lua RNG is non optimal. Most ppl just haven't noticed.

**Comment by Deadwing888** [comment]
math.randomseed you say. That's incredibly useful, let me give that a shot in the three places I'm calling it in onmobinitalize. Thank you very much.

**Comment by Cloudef** [comment]
Couldn't the core call lua's math.randomseed() with the same seed core is using during initialization? No need to do own wrappers over core's rng then.

**Comment by teschnei** [comment]
Yes, but then it's still using rand().  In fact, I thought we were already
calling randomseed on boot for Lua, so I never realised this was a thing.

**Comment by TeoTwawki** [comment]
> In fact, I thought we were already calling randomseed on boot for Lua

I forget who it was that told me we weren't. I don't even know where that would be to see for myself. Even then depending on who you ask some ppl even advise to call it again later, due to [certain platforms](http://lua-users.org/lists/lua-l/2007-03/msg00553.html) being wonky (Platforms we don't support, so it shouldn't matter, but I could be wrong).

**Comment by teschnei** [comment]
You can just grep for it :)

**Comment by TeoTwawki** [comment]
Has never shown on any search I have done :)

**Comment by teschnei** [comment]
Guess we really don't seed it anywhere. Was kind of hoping someone thought
of it once and it just wasn't being run anymore.. At any rate, I can look
into overriding math.random tonight if I remember
