### ISSUE TITLE
mutliple battlefields magic damage is abnormal while skilled/geared apropriate for it's level

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3072]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
last commit hash isn't a dsp hash, however these battlefields haven't been customized and server is definitely updated past the last time resistances were touched

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
In many battlefields nuke damage will always be 0 - BCNM40 under Observation, RDM Maat, etc. Doesn't appear to be an MDT related problem. So much for resistances being fixed?

**Comment by bendangelo** [comment]
That means a lua script threw an error. Was there anything in the log?

**Comment by TeoTwawki** [comment]
Nothing at all in log. If you change the cap and go in at levels higher with skill capped for that level or using the next tier you normally would not have access to because of level restrictions. your previously full resisted nukes then do damage, leading em to believe either the mobs were stronger than they should be, or the resistance check is still wrong. **So I started printing the resistance values. And I discovered its hitting the zero damage return before it ever reaches the resist check.**
```lua
        if (DMG <= 0) then
            return 0;
        end
```

So seems like rdm Maat, Compound eyes, and Sobbing eyes, and bunch other mobs, just have way to much int or something..I start printing the base damage and its negative numbers. I guess the mob stats are way off from retail because I would think we'd have seen this reported much sooner had exp mobs been always hit by zero dmg nukes. But at least its not the resistance again

**Comment by Hozu** [comment]
Checked in-game, Maat has 75 INT. Not unreasonable.

**Comment by TeoTwawki** [comment]
Hmm. wonder wtf the deal is. I did all my printing on BCNM 40 under Observation, but ppl complaining are most often on rdm Maat.

**Comment by TeoTwawki** [comment]
@Hozu prinst say Maat's int is 158 as a rdm. `target:getStat(MOD_INT)` which is teh same check magic.lua is using to get mob int so I know I'm not doing it wrong.

**Comment by TeoTwawki** [comment]
He just checked the UO mobs for me (the hecteyes): 146 INT on both hecteyes.

**Comment by TeoTwawki** [comment]
Notice of million and 1 edits for you email readers..

**Comment by TeoTwawki** [comment]
... I just realized something I need to check on this server

gd effing conf settings

**Comment by Hozu** [comment]
146? I checked on the server I play on and they have "only" 91 INT.

**Comment by TeoTwawki** [comment]
nm_stat_multiplier:     1.6
mob_stat_multiplier:    1.2
player_stat_multiplier: 1.2

Gonna be really angry with some ppl if this problem goes away after resetting those to 1.0

**Comment by teschnei** [comment]
isn't that expected? the BCNM mobs are NMs

**Comment by TeoTwawki** [comment]
Hence my anger at having been convinced to look at this and bringing it here when I didn't see a reason.

**Comment by TeoTwawki** [comment]
ok.. with default settings now its not zero. Abysmally low single digit, which isn't normal, but not zero.

**Comment by TeoTwawki** [comment]
I'm slightly less po'd with this server now. But only slightly because they had me posting totally wrong numbers and created confusion. -\_-

**Comment by teschnei** [comment]
oh duh, I don't know what I was thinking

**Comment by TeoTwawki** [comment]
Going to close this out and after the bcnm rewrite hits look into BCNM mobs one by one instead. 

Mob stats aren't perfectly retail (and unlikely we're ever have them perfect) but that's not a BCNM specific thing anyway, and this problem was greatly exaggerated by one server's mistakes.

**Comment by Wiggo32** [comment]
>  look into BCNM mobs one by one instead.

Thats actually how I do it now. I've come across this issue and I've pretty much had to tweak every bcnm fight in *some* way or another to get it to act more like retail. 
p.s. I keel all my config setting modifiers at 1.0

**Comment by zforninja** [comment]
In mobutils.cpp, the 1.5x stat multiplier is not needed.  I've not seen it documented anywhere as being in the game.  It skews NM stats to the point where for low tier spells you'll never overcome the int gap.

`    if(isNM)
    {
        PMob->stats.STR *= (1.5 * map_config.nm_stat_multiplier);
        PMob->stats.DEX *= (1.5 * map_config.nm_stat_multiplier);
        PMob->stats.VIT *= (1.5 * map_config.nm_stat_multiplier);
        PMob->stats.AGI *= (1.5 * map_config.nm_stat_multiplier);
        PMob->stats.INT *= (1.5 * map_config.nm_stat_multiplier);
        PMob->stats.MND *= (1.5 * map_config.nm_stat_multiplier);
        PMob->stats.CHR *= (1.5 * map_config.nm_stat_multiplier);
    }`

Example:  5-1 Archlich should have 66 INT but this is making it have 99 INT.

At level 50, an Elvaan Male BLM/RDM with no gear has 50 INT.  A cast of Fire with no gear will net the following:

DMG = math.floor( 0 + 0 + 55 + ((50-99) * 1.4)
Which is -13.6.

With standard level appropriate gear it's impossible to overcome that INT deficit.

Removing that 1.5x modifier yields results inline with what would be expected.

**Comment by TeoTwawki** [comment]
it is widely believed NMs have better stats lv per lv than regular mobs. It would be great if someone could confirm what if anything retail does differently for "notorious" monster stats level for lwvel compared to a regular monster of the same type. I bet its just a ranking boost (e.g. reg mob rank b, nm get rank a) plus a few extra lv (e.g. reg mob lv5, nm lv7) instead of a 1.5x multiplier.

**Comment by zforninja** [comment]
The only piece of information I can find is related to Bahamut V2. 

> Anyway, to the OP, I remembered one thing. Studio Gobli lists Bahamut V2 has having 115 INT. I haven't verified it myself using any of the above techniques, but if you use their calculations for flare damage assuming his INT and MAB (1.12) they work out to exactly the observed damage.

115 INT would be on par with no stat increase.

**Comment by TeoTwawki** [comment]
that would fit my rank/lv theory since there is no "non nm" version of bahamut to compare with

**Comment by zforninja** [comment]
Just doing the standard calculation for INT using:

INT = fINT + mINT + sINT

115 is dead on.

More likely NM's get some MDB etc added rather than raw stats?

**Comment by TeoTwawki** [comment]
you understand whay i mean when i say rank right?

**Comment by TeoTwawki** [comment]
My apologies I was on mobile so it was difficult to talk.

It sounds like you've a good grasp of what stats he has but now how we assemble them in darkstar (which may be horribly wrong, btw)

Every stat has a "grade" (or rank) to determine how much they get per level. I was trying to say that rather than multiplying them, if they don't math retail at the same level, we probably used teh wrong rank (the entire way we even build them could be wrong, but I would hope that would've been found out sooner).
