### ISSUE TITLE
"Run away" option in BCNM lead to black screen and being stuck.

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3075]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
Not actually certain since last commit hash wasn't for a DSP commit, but server has pulled updates from stable fairly recently

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
while testing unrelated crap in BCNM 40 "Under Observation" in Horloise Peak, I ran away from the BCNM. The screen went dark, and then I was frozen. I had to zone myself by GM command to regain visibility.

**Comment by Hozu** [comment]
IIRC this has been an issue forever.

**Comment by TeoTwawki** [comment]
Some of them work, some don't. I dunno why it hasn't been fixed assumed it needed a per-bcnm report

**Comment by Scavenge** [comment]
this seems related to oneventfinish which has had issues forever, which may be more the source of the 'this has been an issue forever'

**Comment by TeoTwawki** [comment]
pretty sure thats a different issue, and this is caused by the run away option not even being handled at all so the battle ends with the loss condition but doesn't actually transport the character out

**Comment by starlightknight** [comment]
2e6fb0e will fix, but its dependent on my TOAU branch since I'm not going to cause myself merge conflicts.

**Comment by TeoTwawki** [comment]
I'll make a new issue if I find this is still happening now that BCNM system got reworked
