### ISSUE TITLE
Mission 5-1: Darkness Rising BCNM

### ISSUE THREAD

**Issue by Arthurdales** [DarkstarProject/darkstar#3082]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
494588d35f4954f058d4fe0806e522e0f8309385

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Unable to complete BCNM battlefield. After killing skeleton NM players don't receive burnt seal as the summoned skeletons keep attacking and BCNM doesnt end.  Players are unable to activate the cutscene which grants the burnt seal KI

**Comment by TeoTwawki** [comment]
Can you do us a favor and verify that all the Ancient Sorcerer and Ancient Warrior mobs exist in your bcnm_battlefield table? This was working for a long time and nobody has touched it, if its really bugged then it is likely other battlefields are affected by the bug as well.

**Comment by nekolepsy** [comment]
I ran into this bug yesterday as well. The BCNM faded to black when the Archlich died, but the remaining Ancient Warriors kept attacking us while the screen was black. My blaze spikes eventually killed the Ancient Warriors, but the cutscene did not continue at that point and the bcnm timer continued to count down. I successfully completed this mission on another server, but I can't remember if all the Ancient Warrior adds were dead when the Archlich died. Here's the relevant database info:

`MariaDB [dspdb]> select bi.name, msp.mobname, bb.battlefieldNumber, bb.conditions FROM bcnm_info as bi, mob_spawn_points as msp, bcnm_battlefield as bb WHERE bb.bcnmID = bi.bcnmId AND bb.monsterId = msp.mobid AND bi.name = 'rank_5_mission';`

name  | mobname  | battlefieldNumber | conditions
---- | ------- | ----------------- | ----------
rank_5_mission | Archlich_Taber_quoan | 1 | 3
rank_5_mission | Ancient_Sorcerer | 1 | 1
rank_5_mission | Ancient_Sorcerer | 1 | 1
rank_5_mission | Ancient_Warrior | 1 | 0
rank_5_mission | Ancient_Warrior | 1 | 0 
rank_5_mission | Ancient_Warrior | 1 | 0
rank_5_mission | Ancient_Warrior | 1 | 0
rank_5_mission | Archlich_Taber_quoan | 2 | 3 
rank_5_mission | Ancient_Sorcerer | 2 | 1
rank_5_mission | Ancient_Sorcerer | 2 | 1
rank_5_mission | Ancient_Warrior | 2 | 0
rank_5_mission | Ancient_Warrior | 2 | 0
rank_5_mission | Ancient_Warrior | 2 | 0
rank_5_mission | Ancient_Warrior | 2 | 0
rank_5_mission | Archlich_Taber_quoan | 3 | 3
rank_5_mission | Ancient_Sorcerer | 3 | 1
rank_5_mission | Ancient_Sorcerer | 3 | 1
rank_5_mission | Ancient_Warrior | 3 | 0 |
rank_5_mission | Ancient_Warrior | 3 | 0
rank_5_mission | Ancient_Warrior | 3 | 0
rank_5_mission | Ancient_Warrior | 3 | 0

21 rows in set (0.00 sec)

**Comment by TeoTwawki** [comment]
1 = spawned at start
2 = required to be defeated for victory
3 = both
So those are correct. And the screen went black so it was triggering the event..BCNM cleanup should have removed the monsters right then. :confused:

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
