### ISSUE TITLE
Possible issue with speedsub and/or movement animation passed from sql's "speed"

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#3104]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30160329_0**

**_Server Version_** (type `@revision` in game) **91b4275**

**_Source Branch_** (master/stable) **Master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

This may absolutely be my own ignorance and if so close the issue, but what I am noticing is this:

If a mob such as Cerberus is set to speed 80 in mob_family_system then he will run faster but will move using a slower animation (legs moving slowly) and then warp to catch up with you in a glitchy fashion.

On the other hand if his movement speed is lowered to 40 and then given a (MOD_MOVE, 100); in cerberus.lua onmobinitialize he will run at the same speed but this time with the correct animation. It makes me wonder if something about speedsub or animation is not being read from sql properly for mobs moving faster than 4.0 yalms/sec.

**Comment by Hozu** [comment]
This currently happens with Phuabo and Kindred as well, from what I've seen.

**Comment by teschnei** [comment]
Do you have speed mod changes in the map config?

**Comment by Deadwing888** [comment]
Map config reads:

mob_speed_mod: 0

**Comment by Hozu** [comment]
My server probably does so I'll back out of this one.

**Comment by xdemolish** [comment]
> Server Version (type @revision in game) 1 week old
commit hash please (even if your local branch is ahead use the hash of the latest remote commit)

**Comment by Deadwing888** [comment]
Okay I think I did it correctly @xdemolish

**Comment by xdemolish** [comment]
looks good, thanks :D

**Comment by xdemolish** [comment]
also the tickbox in the issue template should look like this `` - [x] `` to tick it automatically (ive been ninja editing your issues so far i dont think anyone noticed) :p

**Comment by TeoTwawki** [comment]
@xdemolish @Deadwing888 
you can also check the boxes with the mouse after submitting as well, and github will update the source comment with the `[x]`.
