### ISSUE TITLE
Issues with Clear Chips, the Goblins that sell them, and Teleportation to Tu'Lia (not in that order)

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3114]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
237d8c

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Firstly, the "randomness" of the clear chips breaking seems to be quite high. If I remember correctly on retail, it wasn't as often as they break on DSP. I could use the same chip many times over without it breaking.

Second, the goblins selling the chips are broken. I cannot purchase chips from them. The shop opens up, I can scroll over the item, but cannot purchase it.

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Hall_of_Transference/Zone.lua#L89 seems to be 5% break chance.

**Comment by Deadwing888** [comment]
In retail the chip would not break if you didn't use sky warp more than once in a day.

At least it never happened to me in over 100 sky warps.

**Comment by Fiocitrine** [comment]
Hozu, I use five characters on the same server. I used the teleporter on the same day, one character after another, and apparently three broke their chips. This seems a bit much. Sorry not trying to sound like I'm attacking anyone/anything here. 

Deadwing888, I agree. I warped to sky a ton of times on retail and I never broke a chip. The only time I ever heard of anyone breaking a chip is if they use it more than once in a Vana'diel day.

**Comment by TeoTwawki** [comment]
Guys, is that per crag too as well as per day? I don't really recall.

@Fiocitrine do you know if the server was caught up at the time? There was an improvement to the RNG being used not long ago. _As coded_, it should be 5% which I know isn't currently how retail behaves.

Even at 5% that leaves a chance for the unlucky to break multiple times in a row. Which was why retail gives you that freebie no-break every earth day.

**Comment by Fiocitrine** [comment]
No, the server was fine. As far as I can remember. I believe it's per crag/per day.

**Comment by TeoTwawki** [comment]
so who wants to test for me?
https://github.com/TeoTwawki/darkstar/commit/34eae02cae57ba315492f585f99c096e5d08c379?w=1#diff-10a5840be6c7060c6a77208b596cd322L113

**Comment by TeoTwawki** [comment]
the downside of referencing the issue in the commit: github rats me out on all my amends! :cry:

**Comment by xdemolish** [comment]
https://github.com/TeoTwawki/darkstar/commit/999717e56dcfc68ee6c82ea28a15cf98a4876e16
