### ISSUE TITLE
Limit dsconnect to IP

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#3117]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
not related

**_Server Version_** (type `@revision` in game) **:**
ffc3a95

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
It's not possible to limit dsconnect to only listen to a specific ip address.

this would be of great help to test a modified version versus a vanilla version or to have different branches running or even to have a dev and a live game server on the same box at the same time

**Comment by tagban** [comment]
If you're talking about a modified version of the game you could modify version.info

**Comment by tagban** [comment]
Otherwise you can also edit the firewall port setting when opening them to only allow traffic to the connect port from a specified address.

**Comment by ymkc** [comment]
I was thinking about a modified binary or different db.

And you cannot launch the binary twice since it's listening on all ips.

It's parrly in the code already and search/map already support this.

**Comment by teschnei** [comment]
super easy fix if you just want to expose the six config options to the
config file (data/view/auth ip/port)
so easy that I'll let someone else do it

**Comment by R3P0FFXI** [comment]
@ykmc Xiloader currently lets you specify ports but the DSP lobby will not @teschnei would need to modify the lobby code to allow us to specify incoming ports to be able to have more then 1 instance of DSP running on the same IP address for test servers and such.

**Comment by teschnei** [comment]
well I'm not gonna modify it because it's so easy anyone can do it
