### ISSUE TITLE
Lorena Guild Points (Server Crash)

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#3121]
**_I have:_**
- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160329_1 

**_Server Version_** (type `@revision` in game) **:** 43756f7c3dd3f6b61c0e423c5b92d5d2e1726bc8 (Might be off since we update our server from our own version)

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When attempting to purchase guild point items from NPC it crashes the server. Specifically tested with Smithy's Mitts (Item ID 14831)

**Comment by xdemolish** [comment]
got a dump? not managing to crash my server (though im running in release mode)

**Comment by tagban** [comment]
I don't have a dump and disabled her. But I can turn her back on to try to
get one.
