### ISSUE TITLE
Synthesis recipes stop giving skillups at Cap-1

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#3138]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
f2389c2

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When crafting, synthesis recipes stop giving skillups when you become 1 level within the cap of the item.

If you are synthing an item that 'caps' at level 23, once your skill is level 22 - the item will no longer give a skillup.

The item should continue to give skillups until your level is equal to the cap of the synth.

**Comment by Hozu** [comment]
Hm? There were a couple of crafts where I hit 100 by synthing a 100 cap recipe...

**Comment by dazusu** [comment]
Could be possible that some recipes have incorrect cap assigned to them, I'll do more investigating and re-open the bug later if necessary.

**Comment by Deadwing888** [comment]
If your server has day/moon/direction matters turned on it can give the effect of extra levels. This can stop skillups one or even two levels before you cap.
