### ISSUE TITLE
Game Server Crash - Status Icon (Dump Included)

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#3149]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** Latest (game is down cannot check)

**_Server Version_** (type `@revision` in game) **:** a74aebe55f4a3d8e8464c847b8666f02c51c8713

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Nullptr error seems to be related to status icons. 

Dump: https://www.dropbox.com/s/csi9xs1bfrn6115/nullptr_crash.7z?dl=0

**Comment by tagban** [comment]
One of my users mentioned they were cancelling Utsusemi when it crashed to cast Utsusemi:Ni...

"cancelling utusuemi: ni while casting utsuemi: ichi "

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/5d2fa107ccecc10f91825d1e2befbd84667895c7

**Comment by tagban** [comment]
<3
