### ISSUE TITLE
MNK invigorate

### ISSUE THREAD

**Issue by personaone** [DarkstarProject/darkstar#3153]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
b53c5c636f3cd892cb5037b95cad9c5fb73ced31

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Hey Guys, is it me or I don't see any regen kicking in after I use mantra as a level 75 MNK? Has this simply not be implemented?

**Comment by Hozu** [comment]
Erm, you did merit Invigoration, yes? I know it shows up in the list of traits once you hit 75, but you need to actually merit it to gain regen effect. I just tested it.

**Comment by personaone** [comment]
Actually I haven't, I'm surprised it shows up in the trait list and doesn't work until a merit is there, but if that's how retail works then I'll bugger off, sorry for the false positive.
