### ISSUE TITLE
onEventFinish() not working consistently

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#3155]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

even though it is known by many i don't see an issue about it, and wanted to make one because it seems to be getting worse.  commands meant to go off after an event are very often not firing and getting tons of support tickets regarding a quest not working and it is ending up being due to oneventfinish not firing consistently across the board.  it's something that can be 'fixed' by having the player continue to trigger the event until it finally works, when possible/practical, but many times it is not and i am forced to put the commands into the ontrigger alongside the cs being called. i know that this issue has existed for a very long time but recently it seems to have become far more common

Client Version (type /ver in game) :
30160329_1

Server Version (type @revision in game) :
914ce5203730fdca17614150936640d083a20431

Source Branch (master/stable) :
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
set something in oneventfinish to be easily repeatable and then attempt to fire it off over and over and it should eventually happen.  a long time ago when i first reported this (2014) kj mentioned it could be latency from players who are far from the server.  the bcnm issue where people get stuck in a win seems to be related somehow.

**Comment by eraffxi** [comment]
as this continues, we've noticed that of the things we see deal with being possibly broken due to this, defeating maat and then exiting the battlefield will get characters stuck in a black screen and will not get credit for the fight, but not 100% of the time, yet as high as 90%.  

not sure if related, but when players exit limbus the server will often crash due to their timer running out, even when it shouldn't have.

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
