### ISSUE TITLE
Phalanx II cap incorrect

### ISSUE THREAD

**Issue by Darkstorm87** [DarkstarProject/darkstar#3162]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160329_1

**_Server Version_** (type `@revision` in game) **:** 914ce5203730fdca17614150936640d083a20431

**_Source Branch_** (master/stable) **:** stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
The following page seems to indicate that Phalanx II should not have a hard cap at 35, as it shows a table with Enhancing skill between 500 and 524 hitting 36 damage absorbed.

http://ffxiclopedia.wikia.com/wiki/Phalanx_II

Within phalanx_ii.lua there is a hard cap of 35 dmg absorbed.

```
    final = (enhskill / 25) + merits + 1;

    if (final>35) then
        final = 35;
    end
```

I believe that cap should be removed.  I think it should scale entirely off Enhancing Magic Skill.

**Comment by teschnei** [comment]
likely there was no way to get over 500 at the point it was written so it
was put in as a failsafe

make a pull request and someone will merge it

**Comment by Darkstorm87** [comment]
I believe I made the pull request.  Not sure if I did it correctly though.  Thanks

**Comment by Hozu** [comment]
Same with this issue too, should be resolved no?
