### ISSUE TITLE
NORMAL_MOB_MAX_LEVEL_RANGE Lua Settings not functioning properly

### ISSUE THREAD

**Issue by Darkstorm87** [DarkstarProject/darkstar#3163]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160329_1

**_Server Version_** (type `@revision` in game) **:** 914ce5203730fdca17614150936640d083a20431

**_Source Branch_** (master/stable) **:** stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The following Lua settings do not seem to be applied accurately:
NORMAL_MOB_MAX_LEVEL_RANGE_MIN
NORMAL_MOB_MAX_LEVEL_RANGE_MAX

Within zoneutlis.cpp the following function doesn't properly check an NM flag

```
void LoadMOBList()
{
    uint8 normalLevelRangeMin = luautils::GetSettingsVariable("NORMAL_MOB_MAX_LEVEL_RANGE_MIN");
    uint8 normalLevelRangeMax = luautils::GetSettingsVariable("NORMAL_MOB_MAX_LEVEL_RANGE_MAX");

.
.
.

// Cap Level if Necessary (Don't Cap NMs)
if (normalLevelRangeMin > 0 && PMob->m_Type != MOBTYPE_NOTORIOUS && PMob->m_minLevel > normalLevelRangeMin)
{
     PMob->m_minLevel = normalLevelRangeMin;
}

if (normalLevelRangeMax > 0 && PMob->m_Type != MOBTYPE_NOTORIOUS && PMob->m_maxLevel > normalLevelRangeMax)
{
    PMob->m_maxLevel = normalLevelRangeMax;
}
```

The PMob->m_Type field should be doing a bitwise AND check instead of an equality check.  I believe the line should appear as

```
if (normalLevelRangeMin > 0 && !(PMob->m_Type & MOBTYPE_NOTORIOUS) && PMob->m_minLevel > normalLevelRangeMin)
```

This matters for Arena fights and may be applicable elsewhere to other NM types.  As an example of an Arena fight.

```
INSERT INTO `mob_pools` VALUES (5186,'Diabolos',378,0x0000790400000000000000000000000000000000,4,5,12,240,100,0,1,1,0,18,0,32,191,155,0,0,149,1,0,378);

INSERT INTO `mob_groups` VALUES (300,5186,10,0,128,0,11000,0,80,82,0);
```

You'll notice that Diabolos has a mobType of 18.  18 represents the combination of the following MOBTYPE

```
MOBTYPE_NOTORIOUS   = 0x02
MOBTYPE_BATTLEFIELD = 0x10
```

On the private server I am currently playing on they are having issues after adjusting the NORMAL_MOB_MAX_LEVEL_RANGE Lua settings.  NMs are being artificially capped lower than their values in the database.

**Comment by teschnei** [comment]
That looks right - can you pull request it?

**Comment by Darkstorm87** [comment]
I'm super unfamiliar with how github works.  I've mostly just been reading the code and haven't made my own branch :/

I'll try to figure it out.  Thanks :)

**Comment by Darkstorm87** [comment]
I believe I made a pull request.  Not sure if I did it correctly.  Thanks

**Comment by Hozu** [comment]
Isn't this issue resolved now?
