### ISSUE TITLE
Setting a mob's respawn time changes it relative to when it died instead of when it was set

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3166]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160427_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/910078c1efd9eba631a005b6225efe468aeb5da2

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Kill a mob, wait 60s, then set the respawn time for it to 30s. It will spawn instantly because it has been more than 30s since death. It should be setting it to respawn 30s from when it was set.

**Comment by Hozu** [comment]
This affects NQ -> HQ kings and vice versa.

**Comment by Deadwing888** [comment]
A lot of other NMs are written expecting setrespawn it to work like that. 

Land king hq days are wrong, windows are missing, HQs pop instantly, the whole shabang just needs  needs to be rewritten.

It's easy enough to have an option for free spawn and for force spawn kings in the server config, but there is really not an obvious way to make it function for both in my eyes. I've written perfectly retail lua to govern the re-spawns and HQ pops but cannot submit to DSP as it doesn't play nicely with the force pop system. If the "both" option were eliminated I could submit it easily and this problem would go away.

**Comment by Deadwing888** [comment]
If someone else wants to take a stab at writing lua I can outline what I worked out using fafhogg as an example. Much trial and error lead me to:

Fafnir.lua: http://pastebin.com/vyZ17kmd

Nidhogg.lua: http://pastebin.com/WzEnJP5H

Yes HQ day could go that high on retail but it was rare (as reflected in slanting of elseif statements)
Fully window based, tested and fully functional.

**Comment by Deadwing888** [comment]
Thought about this a little more in the shower, and I think where it actually might want to be involves having the "both" option get changed to meaning NQ on a timer (which never pops HQ) and HQ only as a force pop. 

That would be a piece of cake to script, and would be a happy medium for server owners who wanted to be era but also not quite as cut-throat about the land kings botting.

**Comment by teschnei** [comment]
Is that how setRespawnTime used to work or is it just the way it should
have always done so?

**Comment by Deadwing888** [comment]
I think I was mistaken about other mobs expecting setrespawn time to always reference time of mob death.
