### ISSUE TITLE
Unable to trade linkpearls after latest update

### ISSUE THREAD

**Issue by fallen45078** [DarkstarProject/darkstar#3178]
I have:

  searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
  checked the commit log to see if my issue has been resolved since my server was last updated

Client Version (type /ver in game) :30160427_0

Server Version (type @revision in game) : 30160427_0

Source Branch (master/stable) : Master

Additional Information (Steps to reproduce/Expected behavior) :

Create a new pearl and attempt to trade to a player.
Existing linkshells still communicating properly, but am unable to trade linkpearl to new players. 
Can create pearl but will not go into trade window.
This was working properly prior to last update.
 Entire source pulled on 5/15/16 and compiled.

**Comment by Hozu** [comment]
I bet it has to do with linkpearls being flagged as EX so people without a pearlsack/linkshell can't trade them to others... Maybe there will have to be a check for that in the trade check?

**Comment by fallen45078** [comment]
So I am the holder of the master LS on this server and the other player who tried to trade it is a sack holder. Neither of us could trade the pearl to the new player.

**Comment by eraffxi** [comment]
for now my only option is to inject a linkpearl into an inventory using sql,  the extra column is a blob but copying it from another player might be the only option until this is fixed

**Comment by maxtherabbit** [comment]
I've seen this problem on whasf's server. certain sack holders will be able to trade to player X while other sack holders will not ba able to trade to that *same* player X

very odd, I was also not able to reproduce this on my testing server

**Comment by maxtherabbit** [comment]
also to anyone experiencing this: make certain your item_basic table is up to date, we had a couple days where linkpearl was flagged incorrectly
