### ISSUE TITLE
killing dynamis-jeuno boss crashes server

### ISSUE THREAD

**Issue by eraffxi** [DarkstarProject/darkstar#3183]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
dd31b5fc1da371803c8f5cb57cfc63374c8091a5

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
kill boss of dynamis-jeuno

dump:

edit: new link
https://www.dropbox.com/s/1erco13nd4frgvb/dynamis%20jeuno%20boss%20crash.rar?dl=0

**Comment by eraffxi** [comment]
according to demo launchDynamisSecondPart is the culprit

**Comment by xdemolish** [comment]
i didnt even check the dump just echoed https://github.com/DarkstarProject/darkstar/issues/1554#issuecomment-110360279 so w/e

**Comment by eraffxi** [comment]
well confirmed, commenting it out in the scripts stopped the crash.

**Comment by wrenffxi** [comment]
According to https://github.com/DarkstarProject/darkstar/issues/1370, this issue can be closed.
