### ISSUE TITLE
mob:actionQueueEmpty() appears to be failing

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3186]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160427_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/7cf6d1e129f9966b394a41a8fa16a4dec50d24b0

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Was messing around with Tiamat and it took flight while it was in the middle of casting a spell. None of the form changes are supposed to happen while it has a queued/currently active action.

**Comment by teschnei** [comment]
Tiamat doesn't queue anything... why wouldn't it return false?

**Comment by Hozu** [comment]
It used to not be changing forms in the middle of a spell. I suppose it should be a different kind of check then, huh.

**Comment by teschnei** [comment]
I think onMobFight didn't run when they were doing actions.  That's not the case now, and I'm not sure if it should be returned to that behaviour

**Comment by eraffxi** [comment]
not sure if this is relevant really but i have noticed on a high number of crash dumps that mob:actionQueueEmpty() is one of the last 3-5 things in the call stack
