### ISSUE TITLE
Kreutzet spams Stormwind

### ISSUE THREAD

**Issue by DanteMccloud** [DarkstarProject/darkstar#3196]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160427_0

**_Server Version_** (type `@revision` in game) **:**
value returned was "Revision is: Unknown"

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
NM Kreutzet in Cape Teriggan spams Stormwind. Fights start out fine until he uses stormwind for the first time and then he just keeps spamming it and nothing else. I can't tell if he is stuck at a loop or just not loosing TP after he uses the move. I think the problem is within the Stormwind.lua itself but I'm unsure.

**Comment by dazusu** [comment]
Uh, he's meant to spam it.... and he needs to land 3 before it will stop.

What we do need to fix is AOE abilities that don't require a target stopping when the player runs out of range. I believe @teschnei  said the fix is to change the ability to target the mob instead of a player.

**Comment by DanteMccloud** [comment]
He is suppose to use it consecutively 3 times and stop regardless of if his attack hits or not. Currently you can test him with Godmode and after he starts his first stormwind he just loops it with no auto attacks inbetween not 3 times and stop but infinite looping. Unless retail updated how this mechanic works since I last fought him which is 100% possible I suppose.

"Stormwind will always be used 3 times in succession with no other actions inbetween"

**Comment by dazusu** [comment]
On retail, if the player runs out of range - Stormwind still goes off/animates.
On DSP, if the player runs out of range - Stormwind does not complete.

I'll look at the spam issue, though.

**Comment by DanteMccloud** [comment]
Just re-tested it in fear of maybe it "missing" causing it to not count 1 2 3 and be over. I attacked him until he got to about 90% hp and used his first Stormwind. I turned off godmode and put my weapon away (no TP being fed) he used stormwind about 37 times in a row after that each of them landing and dealing a nice lump of damage. (had to toggle godmode on and off a few times to not die while testing it, but it's looping for sure not just 3 in a row. If there is anything else I can do to help please let me know.

**Comment by nyczducky** [comment]
Confirmed. He spammed way more than 3 in a row. Got hit with all of them. He pretty much bugged out from 90% - 20% and did nothing but spam Stormwind.

I had to run from him and noticed he didn't chase and instead stood there trying to hit me from out of range over and over. No damage was taken since I was out of range. Killed him with ranged attacks from a distance.

**Comment by TeoTwawki** [comment]
"fixed" by #4363 but now broken a diff way
