### ISSUE TITLE
15 Character name makes DSP broken

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3204]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

30160427_0

**_Server Version_** (type `@revision` in game) **:**

9624926bac121c75464925b9c309ebae28f659d5

**_Source Branch_** (master/stable) **:**

Master and Stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

15 character name breaks DSP, client allows up to 15 characters DSP however does not. Cannot send tells to the character name was sucidaldeathtar. Everything started working fine no character recreation after renaming the character in the database to sucidaldeath

**Comment by aizenmyou** [comment]
Just quickly looking through, it may have something to do with the data[5] value being passed in SmallPacket0x0B6. Everywhere else the charname is 15.

**Comment by TeoTwawki** [comment]
I don't think data[5] has anything to do with it. I think this is just the [packet size](https://github.com/DarkstarProject/darkstar/blob/a0396e2e4cbbe93bd4949c9277f4e4b847b919d1/src/map/packets/basic.h#L62) and doesn't effect the packets contents.
