### ISSUE TITLE
typing @revision gives error

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3205]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

30160427_0

**_Server Version_** (type `@revision` in game) **:**

9624926bac121c75464925b9c309ebae28f659d5

**_Source Branch_** (master/stable) **:**

Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

typing @revision givers lobby error

 [31/May 16:13][Error] lobbyview_parse: Incorrect client version: got 301604xx_x, expected 301604xx_x

**Comment by xdemolish** [comment]
that has nothing to do with the revision command
