### ISSUE TITLE
Avatar and BST pets generating 0 enmity on miss

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3210]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

30160329_1
**_Server Version_** (type `@revision` in game) **:**
9624926

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
This issue has happened in the past and I thought it was addressed? On initiating aggro, a summoned avatar that misses will generate 0 enmity. This causes the mob to directly attack/target the player.

**Comment by ymkc** [comment]
Same with bst pets
