### ISSUE TITLE
Unable to launch game

### ISSUE THREAD

**Issue by Swisskat** [DarkstarProject/darkstar#3211]
Hello ;

I have tried to install FFXI/Supernova through the automatic installer but don't succeed in launching the game. Windower says this : 

Found Unknown Command Argument : /game
Found Unknown Command Argument : eAZcFcB

Any idea how to solve this ?

Sorry for the inconvenience and thank you very much for your answer.

Daniel

**_I have:_**

- [X ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by teschnei** [comment]
Hi,
Unfortunately we don't have anything to do with Supernova, installers or anything outside of the server.  The only suggestion I can give to you is to buy the game legitimately or ask on Supernova's support for help.
