### ISSUE TITLE
zone GM command error

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#322]
(at) zone {Behemoth's Dominion}
lands me in Meriphataud Mountains instead of Behemoth's Dominion.

**Comment by whasf** [comment]
This is still broken. Behemoth's Dominion and Meriphataud Mountains both give groupId 20 and messageId 32

**Comment by helixhamin** [comment]
Yep, still broken. Anyone know if this will be fixed going forward?

**Comment by Heepster03** [comment]
Middle Delkfutt's Tower also lands you in Meriphataud Mountains
