### ISSUE TITLE
SetRespawnTime called from onInitialze(zone) not working as expected

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#3220]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**
27d980c

**_Source Branch_** (master/stable) **:**
30160427_0

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
On server start, when the SetRespawnTime's are called from onInitialize in the zone.lua, mobs should get a time set when to pop. Although the function is being called, the timers only start once a character zone's in.

E.g Duke Decapod. Make sure there is no character in East Sarutabaruta, restart the server, wait 1:15h+, zone into East Sarutabaruta and check for Duke Decapod being up.
His respawntime starts with the first character to zoning in, so DD will be up 1h-1:15 after the first char zoned to East Sarutabaruta.

This seems to be true for any "delayed timed spawn NM" that is called SetRespawnTime on in a zone.lua

**Comment by ymkc** [comment]
I think I found the problem, but it needs someone more skilled to fix than I am.

It seems, if there is no PC in a zone, the zone timers are stopped:
https://github.com/DarkstarProject/darkstar/blob/master/src/map/zone.cpp#L583-L586

I added a zone timer to every zone on it's creation and it fixed the problem.
The downside was a nice little cpu benchmark-like increase in load and the server logs flying by (nav mesh errors from all the roaming mobs).

So probably a better solution might be having a second type of zone timer running for the "inactive"/PC-less zones just for the (re)spawn timers?

**Comment by teschnei** [comment]
I don't think you need a timer for this.  It's just setting the respawn time

**Comment by ymkc** [comment]
But the respawn times are not ticking/running/counting down on inactive zones. 

After a few days uptime, alot of special NMs should be up, but they are not (on an idle server) :|

**Comment by teschnei** [comment]
respawn times don't tick, they are just a duration from when they despawned

the problem is simply that calling SetRespawnTime resets the death time, and the respawn time is not applied outside of ticks (so the death time is reset to the time of the first tick)

**Comment by ymkc** [comment]
i see, but that would make it very hard to time pop many nm's incl the land kings
a PC would need to stay in the zone for hours to days for them to pop

apart from that, as there is no mob roaming in empty zones, if a NM (or any mob if mob_no_despawn is set) is pulled to a zoneline and the pt/last PC zones the NM/mob will wait right at the zoneline :|

so maybe it might sound stupid, but how about adding an option (default off of course) for beefy hardware/real servers to have a zonetimer running even on empty zones?

probably only on zones accessable by the enabled expansions?

**Comment by teschnei** [comment]
Sorry, it's really not as complicated as you think - a PC only needs to enter the zone for a single tick after SetRespawnTime is called.  The easiest way to fix that is to move the ResetEntryTime out of the state and into all the functions that modify the respawn time (only if the state is CDespawnState).

As for running zone timers on empty zones, it's useful but not important to this particular bug (maybe discuss it in another issue)

**Comment by ymkc** [comment]
okay, thanks for all the hints I will try to take a look at it in a few days
