### ISSUE TITLE
Valkurm Dunes - Missing Snippers

### ISSUE THREAD

**Issue by heakinakai** [DarkstarProject/darkstar#3225]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160602_0

**_Server Version_** (type `@revision` in game) **:**
Revison is: UNKNOWN (I can get version from server directly if you tell me how.)

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Snippers are missing from Valkurm Dunes, On our server we don't appear to have any spawning. When we run a command to spawn one we get an error saying "Mob with ID '17199147' not found!". I've looked in the DB and the Mob is in there in the Spawn Locations Table, I've looked in the /scripts/zones/Valkurm_Dunes/mobs and there is a Snipper file in there... 

Can any one tell me where to look when analysing problems like this? or what I can do to debug this.

I'm running a Linux Ubuntu Server.

Many thanks in advance,

Drkdragon

**Comment by abriasffxi** [comment]
Is this still an issue?

**Comment by TeoTwawki** [comment]
Open new issue if this is still a thing
