### ISSUE TITLE
Trick Attack enmity transfer does not work with Skillchain damage

### ISSUE THREAD

**Issue by neosatus** [DarkstarProject/darkstar#3228]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** N/A

**_Server Version_** (type `@revision` in game) **:** N/A

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The enmity generated by skillchain damage is not being applied to the Trick partner as it did on retail. We noticed this issue while opening Like The Wind encounters with Konzen > Gekko > SATA Mercy Stroke where the Mercy Stroke hit for 3k+ and the Darkness 2 chain for 4k+ which always lead to the THF having aggro as he generated more enmity than he put on the tank. I checked the DSP github code to verify this was true and found that there was no condition to apply the enmity generated by a skillchain to the taChar. So I set to understanding the methods involved and came up with this (albeit lengthy) fix. Copy/pasting from my comment on the Era github:

Stack trace of the WS to SC method flow:

The taChar is discovered in doPhysicalWeaponskill on line 56 and needs to be passed down the line somehow:

OnWeaponSkillFinished (charentity.cpp:801) calls onUseWeaponskill (luautils.cpp:3086) which calls onUseWeaponskill (mercy_stroke.lua:19) which calls doPhysicalWeaponskill (weaponskills.lua:18) which calls takeWeaponskillDamage (weaponskills.lua:884) then values get returned all the way back up to OnWeaponSkillFinished which a handful of lines later calls TakeSkillchainDamage (battleutils.cpp:3176).

I think I figured it out! However, the way taChar is defined and passed around is unclear to me so some tweaking is possibly needed but in general this path should work:

weaponskills.lua:228
`return finaldmg, criticalHit, tpHitsLanded, extraHitsLanded, taChar;`

mercy_stroke.lua:35
`local damage, criticalHit, tpHits, extraHits, taChar = doPhysicalWeaponskill(player, target, wsID, params, tp, primary);`

mercy_stroke.lua:42
`return taChar, tpHits, extraHits, criticalHit, damage;`

luautils.cpp:3121 (new line here) (this is probably wrong)
`CBattleEntity* taChar = lua_touserdata(LuaHandle, -5);`

luautils.cpp:3138 (was 3137)
`return std::make_tuple(dmg, tpHitsLanded, extraHitsLanded, taChar);`

charentity.cpp:732
`std::tie(damage, tpHitsLanded, extraHitsLanded, taChar) = luautils::OnUseWeaponSkill(this, PTarget, PWeaponSkill, tp, primary, action);`

charentity.cpp:801
`actionTarget.addEffectParam = battleutils::TakeSkillchainDamage(this, PBattleTarget, damage, taChar);`

battleutils:3176
`int32 TakeSkillchainDamage(CBattleEntity* PAttacker, CBattleEntity* PDefender, int32 lastSkillDamage, CBattleEntity* taChar)`

battleutils:3244-3251
`if (taChar != nullptr)`
`{`
`((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(taChar, (uint16)damage);`
`}`
`else`
`{`
`((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(PAttacker, (uint16)damage);`
`}`

I haven't setup a test environment yet, just browsed the codebase. Should I do that and submit a merge request or is this comment enough?

**Comment by takhlaq** [comment]
test and pull request

**Comment by neosatus** [comment]
I tested this on the personal server of one of the GM's of the server I play on. Neither of us know how to push the code back to you. Here's my comment from our github:

Here's an easy way to fix the problem, however, the function getAvailableTrickAttackChar is now called twice per weaponskill. The work around for this would be to pass it down the chain of methods which would include modifying every single weaponskill script. I don't imagine anyone is interested in doing that. This fix will take 5 minutes to implement and it works. If it causes issues, you could revert it or do it the hard way, either one. I don't think it'll cause any issues and it helps enmity in coordinated groups a lot. We just tested it on a fully up to date version of the code base and it worked. Here's the fix:

**/src/map/entities/mobentity.cpp:748**
```
if (effect != SUBEFFECT_NONE)
{
    int32 skillChainDamage = battleutils::TakeSkillchainDamage(this, PTarget, target.param, NULL);
```

**/src/map/entities/charentity.cpp:631**
```
if (effect != SUBEFFECT_NONE)
{
    uint16 skillChainDamage = battleutils::TakeSkillchainDamage(static_cast<CBattleEntity*>(this), PTarget, actionTarget.param, NULL);
```
**/src/map/entities/charentity.cpp:724**
```
uint16 tpHitsLanded;
uint16 extraHitsLanded;
int32 damage;
CBattleEntity* taChar = battleutils::getAvailableTrickAttackChar(this, PTarget);
```
**/src/map/entities/charentity.cpp:~800**
```
if (effect != SUBEFFECT_NONE)
{
    actionTarget.addEffectParam = battleutils::TakeSkillchainDamage(this, PBattleTarget, damage, taChar);
```
**/src/map/utils/battleutils.h:153**
```
int32				TakeSkillchainDamage(CBattleEntity* PAttacker, CBattleEntity* PDefender, int32 lastSkillDamage, CBattleEntity* taChar);
```
**/src/map/utils/battleutils.cpp:3176**
```
int32 TakeSkillchainDamage(CBattleEntity* PAttacker, CBattleEntity* PDefender, int32 lastSkillDamage, CBattleEntity* taChar)
```
**/src/map/utils/battleutils.cpp:3242**
```
case TYPE_MOB:
{
    if (taChar == nullptr)
    {
        ((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(PAttacker, (uint16)damage);
    }
    else
    {
        ((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(taChar, (uint16)damage);
    }
}
break;
```

**Comment by teschnei** [comment]
sorry, despite the good intentions I cannot do anything if you do not make
a pull request.  There are tons of guides everywhere to teach how to do it

**Comment by neosatus** [comment]
We'll see about getting our devs to add it to our server and do some more testing with the full playerbase then have them push it up to you.
