### ISSUE TITLE
Olla Pequena crashes server on death

### ISSUE THREAD

**Issue by fallen45078** [DarkstarProject/darkstar#3233]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** 30160427_0

**_Server Version_** Unknown

**_Source Branch_** master

**_Additional Information_** Killing Olla will result in an immediate server crash. I pulled a raw copy of the most recent (6/17/16) build and compiled it with no customizations, it crashes there also.  He spawns but on death, server closes.

**Comment by teschnei** [comment]
if you pulled a "most recent build", please fill out the server version

**Comment by TeoTwawki** [comment]
missing require. may be more like this if you want to look for them real quick. I just pr'd it because I was there.
