### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by woqunima123** [DarkstarProject/darkstar#3245]
I use the latest Ashita when registering

DS show
The DB ERROR Column 'timelastmodify' always be null

Why is this?

**Comment by woqunima123** [comment]
When do_close CTRL + shift + b Often appear error
I carefully check found a lot of position errors. Hope to solve the problem when the next update

**Comment by woqunima123** [comment]
Do_close errors of position in the darkstar - master \ SRC \ map \ socket.CPP

**Comment by Fiocitrine** [comment]
I think this would be an Ashita issue, not DSP?

**Comment by woqunima123** [comment]
Look, what I use is the latest Ashita. Has nothing to do with Ashita, I can go to other private server

**Comment by takhlaq** [comment]
please use the issue template
