### ISSUE TITLE
Potential issue with cMeleeRatio function

### ISSUE THREAD

**Issue by neosatus** [DarkstarProject/darkstar#3247]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** N/A

**_Server Version_** (type `@revision` in game) **:** N/A

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

I was browsing the weaponskill calculations today and creating a spreadsheet for my Tachi: Gekko damage to compare items against one another when I noticed the following block of code. Note that there are two conditions in a row for cratio < 1.5.

```
if (cratio < 0.5) then
        pdifmax = cratio + 0.5;
    elseif (cratio < 0.7) then
        pdifmax = 1;
    elseif (cratio < 1.2) then
        pdifmax = cratio + 0.3;
    elseif (cratio < 1.5) then
        pdifmax = (cratio * 0.25) + cratio;
    elseif (cratio < 1.5) then
        pdifmax = cratio + 0.375;
    else
        pdifmax = 3;
end
```

**Comment by eraffxi** [comment]
that means that the second one will never go off.  perhaps it meant to be another value like 1.75 or 2.0
