### ISSUE TITLE
@addmission not working for SOA and ROV logIDs

### ISSUE THREAD

**Issue by ibm2431** [DarkstarProject/darkstar#3249]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30160602_0

**_Server Version_** (type `@revision` in game) **:** 6d4312439caaca3605e24e90fe9d6d52cb78e0f9

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Maybe I'm just an idiot, but I can not for the life of me get @addmission to add mission logs for Adoulin (12) or Rhapsodies (13). I believe I have them enabled: login_darkstar.conf (expansions: 4094), and scripts/globals/settings.lua (both ENABLE_SOA and ENABLE_ROV are 1). I'm refreshing the mission log after each attempt.

@addmission for all other expansion missions works just fine.

@completemission seems to suffer from similar problems. A @completemission 13 0 won't complete the first/default ROV mission.

Screenshots:
@addmission 12 1 (Adoulin, Geomagnetron), @addmission 13 1 (RoV, Resonace)
![img_20160627_174704](https://cloud.githubusercontent.com/assets/13112942/16400446/5502daa0-3c90-11e6-8ab6-3ed180f0628c.png)

Nothing in Adoulin:
![img_20160627_174717](https://cloud.githubusercontent.com/assets/13112942/16400449/5dfa5e94-3c90-11e6-8131-4f38bb8b8fd6.png)

RoV not changed from default:
![img_20160627_174724](https://cloud.githubusercontent.com/assets/13112942/16400474/a57680b8-3c90-11e6-8646-72ccb473367f.png)

I've looked at ::addmission in lua_baseentity.cpp, and while there is a check to see the expansion ID (LogID) is less than the defined MAX_MISSIONAREA, the max is defined as 15 in charentity.h. So I have no guess as to why it wouldn't working other than maybe the packets for those two logs being different somehow.

**Comment by teschnei** [comment]
I don't think we ever added them to the packet (or even the database).  Not likely going to happen anytime soon, though

**Comment by ibm2431** [comment]
Looking over the history for [quest_mission_log.cpp](https://github.com/DarkstarProject/darkstar/blob/master/src/map/packets/quest_mission_log.cpp) (which appears to have logic for SOA and ROV in it), I think Adoulin was added to the packet in commit aa61e583, and RoV added to it in commit 72e7bd3e. I'm not going to pretend I understand XI's packet structure enough to evaluate why they don't seem to be working now (assuming that they used to, that is).

I'll freely admit I'm too unfamiliar with Darkstar to figure out if they're in the database. But I can tell that the server is building and sending some kind of update packet to the client:
![img_20160627_214002](https://cloud.githubusercontent.com/assets/13112942/16404063/462cda88-3cb0-11e6-98af-712b1ba45b91.png)
(//packetviewer log chatlog incoming not 0x017 ; 0x017 is the chat packet)
Even if the progress wasn't stored in the character database, wouldn't the packet cause the client's mission log to change?

I have a mule on retail I can complete a couple SOA/ROV missions for (to lock down what the packet "should be") and then look into this some more. I've been working on scripting Adoulin NPCs, but many have changing dialogue depending on mission progress, so I'll have to eventually solve it if no one beats me to it.

**Comment by helixhamin** [comment]
Those are more placeholders rather than completed code. You still need to script the entire thing in the proper lua files. For example, everyone's least favorite, https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Chateau_dOraguille/npcs/Halver.lua
You can see how it assigned cses, how it adds the appropriate items, etc. So, even if the packets are correct, and no guarantee of that, you still need to build up everything else around the missions.

**Comment by ibm2431** [comment]
Yeah, that's what I intended to do. It's just that I noticed that the [global constants for missions](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/missions.lua) weren't completed, so I was going to add those first (like [I did for quests](https://github.com/DarkstarProject/darkstar/pull/3246)). But upon testing my expected IDs with @addmission to verify they were accurate, nothing happened. So here we are!

**Comment by takhlaq** [comment]
did you enable soa in lobby config? i dont think the client displays missions unless the flag for the expansion is set

**Comment by ibm2431** [comment]
Do you mean in https://github.com/DarkstarProject/darkstar/blob/master/conf/login_darkstar.conf?

My expansions value is set to 4094 (0000 1111 1111 1110).

I discovered previously that without it being set, the client won't even let you click or view the mission log for the expansion - it'll just be grayed out. It also skips over the expansion if you try clicking another type of log and then using the red left/right arrows. I think it also does the same for that area's quests.

But my Adoulin bit is set and I can access the mission log on the client. And my Adoulin area quest log is working just fine.

I did do some SOA and ROV missions on retail and took screenshots of the incoming packets. Here's screenshot compilations of the packets I got for the first few missions of SOA and ROV. Some sample data to work with for myself, or anyone else who's interested. The images are kind of large, so I threw them on imgur instead of pasting them into this comment:
[Seekers of Adoulin](https://imgur.com/zAfdOCV)
[Rhapsodies of Vana'diel](https://imgur.com/pEuqxOk)

**Comment by ibm2431** [comment]
This will be fixed by a376abb.
