### ISSUE TITLE
charybdis does not multi attack, because CheckMobMultiHits never gets called, ever

### ISSUE THREAD

**Issue by eraffxi** [DarkstarProject/darkstar#3269]
**_I have:_**

- [ x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160427_0

**_Server Version_** (type `@revision` in game) **:**
dd31b5fc1da371803c8f5cb57cfc63374c8091a5

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

charybdis does not multhit like normal, put a breakpoint on the CheckMobMultiHits exception for 'unique mobs' where charybdis ID is highlighted, never got set off. set breakpoint on the function itself, nothing.

**Comment by HeavensSword** [comment]
I found that CheckMobMultiHits is not actually called anywhere. I went ahead and split it into a new method that check multi-hits for special mobs like charby. Tested and works correctly; creating a pull request now.

**Comment by HeavensSword** [comment]
We should be able to close this issue now after change #3278
