### ISSUE TITLE
Found a couple of bugs in quickstep.lua

### ISSUE THREAD

**Issue by neosatus** [DarkstarProject/darkstar#3270]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** N/A

**_Server Version_** (type `@revision` in game) **:** N/A

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Was just browsing the code some more for spreadsheet purposes and noticed a few bugs in quickstep.lua.

It appears to work correctly for /DNC but for DNC mains when there are 4 stacks of Quickstep on the mob it puts 2 stacks up instead of 5.

Also, for the timing, you get the Duration from the status effect, which is in milliseconds, but then pass it into the constructor for a new Status Effect like it's a second without doing any converting. The end result is, assuming the variable type could hold the number, the duration of a 5 stack Quickstep would be 1.9 million years.

In seconds: 60 > 60,030 > 60,030,030 > 60,030,030,030 > 60,030,030,030,030

Whoops.

Presumably, this same bugged interaction exists in other step scripts.

**Comment by teschnei** [comment]
actually, there's like 30 scripts that assume getDuration and the constructor take the same timescale (a totally reasonable assumption) and (i think) zero scripts that know they are different.

so I guess i'll change getDuration to return seconds and it'll fix all the steps, corsair shots, modus veritas, sacrifice, mobskills that steal buffs, etc...

**Comment by neosatus** [comment]
I think there is one spot I saw where it does getDuration and then divides by 1000. I'll try to find it again and edit.

**Comment by neosatus** [comment]
This is interesting, should this be divide by 1000, not subtract?

https://github.com/DarkstarProject/darkstar/blob/04c91f4c645f22b1520150f2c6341699d661a2e6/src/map/utils/battleutils.cpp#L2956

And here it does convert it:

https://github.com/DarkstarProject/darkstar/blob/acfc336de71d683188c36b5fb6a0b465f9d25eab/src/map/status_effect_container.cpp#L1053

**Comment by teschnei** [comment]
I should have mentioned that I'm talking about scripts only (I'd change only the lua binding for GetDuration, not the C++ method)

and yes, that skillchain code is correct the way it is (both getduration and setduration use milliseconds, and that is removing one second from the duration)

**Comment by neosatus** [comment]
Alright, sounds good then.
