### ISSUE TITLE
Redefinition of mission constant in missions.lua

### ISSUE THREAD

**Issue by neosatus** [DarkstarProject/darkstar#3281]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** N/A

**_Server Version_** (type `@revision` in game) **:** N/A

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The Last Verse is both a CoP and ZM mission but they're defined as the same constant, THE_LAST_VERSE, to two different values. Perhaps it should be THE_LAST_VERSE_COP and THE_LAST_VERSE_ZM?

https://github.com/DarkstarProject/darkstar/blob/a9976388c29bf6f65088f783c5bb656cd090db48/scripts/globals/missions.lua#L128

https://github.com/DarkstarProject/darkstar/blob/a9976388c29bf6f65088f783c5bb656cd090db48/scripts/globals/missions.lua#L197

**Comment by takhlaq** [comment]
ideally they'd be in a table under the nation name

**Comment by ibm2431** [comment]
In my (unsolicited) opinion, simply appending _COP and _ZM might be best (for now, anyway). With the exception of one time in ROV (which in its case, a table wouldn't help with), I believe this is the only case where two different mission IDs share a name. Table-fying all the mission/quest names is ideal, but I don't know when someone will want to deal with that mess.

**Comment by TeoTwawki** [comment]
Tabling the IDs or renaming the variable are the only 2 options for handling conflicting variable IDs.
