### ISSUE TITLE
Cure V giving non-retail hate

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#3294]
**_I have:_**
- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **NA**

**_Server Version_** (type `@revision` in game) **Recent**

**_Source Branch_** (master/stable) **Master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **
Cure V is supposed to generate static CE and VE, and those values are indeed correctly set in sql.
It is not supposed to generate further hate based on HP cured the way the other cure spells do. If you turn on enmity prints you will find that it currently does.

I believe the source of the problem is cure_V.lua line 103

Credit goes to Llowyn of Nasomi server for spotting the increased hate and pinpointing the issue based on test server enmity prints.

**

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/f28b05bb85b73a612ebe7e12c4f8f926b66f63f4/src/map/enmity_container.cpp#L202

Uh, I believe that it's adding enmity even when out of range... But that's the values that should be added, regardless of enmity mods.

**Comment by Deadwing888** [comment]
I don't know what to tell you other than to turn on the enmity prints and actually look at it. On my test server it was giving hate from HP cured until I removed the line of cure_v.lua that I mentioned in initial issue.

**Comment by Hozu** [comment]
Try replacing final with 65535 in line 103 there. It looks like if that value is passed in, it's counted as a cure 5 spell. Should probably do the same for cure 6 IIRC?

And the thing I mentioned earlier is still a problem.

**Comment by Deadwing888** [comment]
I've never seen a cure 6 casted, so I'm not a good source of information for that.

I don't know if removing the update enmity line from the lua is the best way to proceed for dsp. You all are far more code savy than I am. It seemed to do the trick though so it may be what we stick with where I play.

**Comment by Hozu** [comment]
What you did completely removes all hate gain. What I suggested should make it do the fixed gain thing. But I can't test anymore so yeah.

**Comment by Deadwing888** [comment]
Are you sure about that? It seemed to be passing static hate values in from sql (or somewhere) onto the enmity prints.

**Comment by Hozu** [comment]
I'm pretty sure, but that's what testing is for. It should generate 400 CE and 700 VE regardless of enmity mods and amount healed, according to this:
https://github.com/DarkstarProject/darkstar/blob/f28b05bb85b73a612ebe7e12c4f8f926b66f63f4/src/map/enmity_container.cpp#L202

**Comment by Deadwing888** [comment]
Yes those were in the ballpark of the enmity passed from the console prints after I removed that line from the lua. (After factoring enmity- traits).

Again, you all are the experts and I'm sure will know the best fix, be it on the core core level or addition of the 65535 number to the lua.

**Comment by teschnei** [comment]
the core checks if enmity is 65535 and uses that for determining enmity

it's kind of silly but i guess if you just want it fixed for now..

**Comment by zynjec** [comment]
Fairly sure this was fixed with enmity rewrite.
