### ISSUE TITLE
Monk Attack Speed

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3296]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** 30160629_1 **:**

**_Server Version_** Unknown **:**

**_Source Branch_** stable **:**   (downloaded ~7/15

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Hi all -  we started a new server fresh around 7/15 without changing anything.  First thing we noticed is that monk attack speeds were insane - about the same as daggers.  On further testing we found r.arc cesti to be ~210 delay against a 196 dagger  with only ma1.

So, I dug around and found that the sql table for item_weapon h2h has horrendously low delay.  All of them are 240+ weapon delay in game when they should be 480+.  I verified in the state code that the delay is just (delay/60-MOD_Martial_arts)*1000 so this is definitely incorrect.  I fixed them on my server by going in and adjusting each group listing of weapons to account for a base of 480 instead of 240.  I didn't look for every record, but they generally seem to be accurately (grouped), so an UPDATE database.item_weapon SET delay = 'xxx' WHERE (skill = '1' AND delay = 'xxx') was easy enough to change all of them over in ~30 minutes.

Not familiar with how to branch or anything on github so if anyone wants to take this over in testing and incorporating and teaching me the branch (on irc) that would be great.

**Comment by Hozu** [comment]
I would have thought the core should have
`((delay+w/e natural h2h delay is)/60-MOD_Martial_arts)*1000`
because POLutils stores h2h weapon delay as without the natural h2h delay. I bet that would also fix the issue with mobs that attack with h2h "weapons".

**Comment by teschnei** [comment]
mobs just use whatever delay is set in cmbDelay in the mobs tables.. what
do some monks have?

**Comment by Hozu** [comment]
I honestly don't know what they have, but the problem was referenced in this issue: https://github.com/DarkstarProject/darkstar/issues/3148

Surprised it wasn't made its own issue, but you can see it if you were to go fight any high level MNK mob (or any mob where the cmbSkill is set to 1 for h2h I suppose), they'll swing really, really fast.

**Comment by teschnei** [comment]
looks like mostly 240-360, so 4-6 sec minus martial arts

**Comment by abriasffxi** [comment]
Relevant section of battleentity:

int16 CBattleEntity::GetWeaponDelay(bool tp)
{
    if (StatusEffectContainer->HasStatusEffect(EFFECT_HUNDRED_FISTS) && !tp)
    {
        return 1700;
    }
    uint16 MinimumDelay = m_Weapons[SLOT_MAIN]->getDelay(); // Track base delay.  We will need this later.  MOD_DELAY is ignored for now.
    uint16 WeaponDelay = m_Weapons[SLOT_MAIN]->getDelay() - getMod(MOD_DELAY);
    if (m_Weapons[SLOT_MAIN]->getSkillType() == SKILL_H2H)
    {
        if (!StatusEffectContainer->HasStatusEffect(EFFECT_FOOTWORK))
        {
            WeaponDelay -= getMod(MOD_MARTIAL_ARTS) * 1000 / 60;
        }
    }
    else if (m_Weapons[SLOT_SUB]->getDmgType() > 0 &&
             m_Weapons[SLOT_SUB]->getDmgType() < 4)
    {
        MinimumDelay += m_Weapons[SLOT_SUB]->getDelay();
        WeaponDelay += m_Weapons[SLOT_SUB]->getDelay();
        //apply dual wield delay reduction
        WeaponDelay = WeaponDelay * ((100.0f - (float)getMod(MOD_DUAL_WIELD)) / 100.0f);
    }

Not really sure which way would be cleaner (fix sql or fix .cpp),as I'm only 2 days in in checking out the projects code, but it's definitely a fix that needs to be in.

**Comment by Hozu** [comment]
240-360??? About that... Fruit Punches are set to 520, and they're the fastest h2h weapon at +0 delay. Every other h2h weapon is slower. That explains that.

**Comment by teschnei** [comment]
also interesting.. the unarmed items don't actually set the delay to anything.. I wonder what they end up being?

**Comment by abriasffxi** [comment]
240-360 lines up exactly with the current stable SQL numbers for player
weapons.

520 lines up with what people thought the base delay was 3-4 years ago, but
I think it's know to be 480 now without ma.

**Comment by nyczducky** [comment]
This is a huge issue for new players who are in the process of fighting Maat. Getting various reports from players dying in a few seconds of:

Maat hits player for 200.
Maat hits player for 200.
Maat hits player for 200.
Maat hits player for 200.
Maat uses Asuran Fists.

Only option is to level WHM and kite for 5 minutes sadly.

**Comment by helixhamin** [comment]
Guess that is one way to get more healers on your server >.>

**Comment by nyczducky** [comment]
Only issue is for servers that are retail exp... finding that out after you leveled something like BRD is a kick in the nuts if you have to level something again to just finish Genkai 5 lol.

**Comment by abriasffxi** [comment]
Ninjixtix commited a change that fixed this.  Closing the issue.  Sorry for your commentary about Maat- suggest opening a separate issue as it's not related to player attack speed.

**Comment by Snugglesffxi** [comment]
@abriasffxi I can't seem to find any user named Ninjixtix or any commits relating to the issue, would you be able to point me in the right direction to that PR? thanks!

**Comment by abriasffxi** [comment]
Sorry, it was Ninjistix.

https://github.com/DarkstarProject/darkstar/pull/3170

**Comment by nyczducky** [comment]
This isn't fixed and pretty much breaks a lot of content. 

Maat, BCNMs, NMs. Missions. 

This isn't limited to just MNK mobs. Alky is an example. Sometime he will have 0 delay and then other pops he will be like retail.

With servers that have Genkai enabled, it pretty much limits you to doing Maat on SAM, RDM, WHM, THF.

I know because I leveled BRD first on one of these servers and tried 7 times to kill Maat with everything capped and always died in 3 seconds because of 0 delay.
