### ISSUE TITLE
Dancers roll bugged on corsair

### ISSUE THREAD

**Issue by sisternERA** [DarkstarProject/darkstar#330]
Dancers roll animation always displays numeral one and the bust will actually take down hp instead of taking away regen

**Comment by MalRD** [comment]
- [x] Verified that Dancer's roll shows the correct number during animation for self
- [x] Verified that Dancer's roll shows the correct number during animation for others
- [x] Verified that busting gives a -4HP/tick regen effect!

Appears to have been resolved sometime in the last four years, if I've understood the posted issue.
