### ISSUE TITLE
nothing happens after CS when leavecode == 2 for bcnms

### ISSUE THREAD

**Issue by eraffxi** [DarkstarProject/darkstar#3300]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
'/ver' in game

**_Server Version_** (type `@revision` in game) **:**
@ revision in game

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
sorry that i'm lazy about ^ but it's 5 am and i want to sleep

admin on my server submitted a fix for bcnms by calling player:bcnmleave(1) in the oneventfinish after CS.  considering that cs gets triggered during leavecode 2, it seems wrong to me that you would need to call leavecode 1 to make leavecode 2 work.

in his words, his fix( putting bcnmleave(1) after the CS ends) fixes the following:

"What this fixes:
Continuing to get your ass beat by mobs when you win a BCNM.
Having the battlefield buff removed from all players when the finishing CS is done.
Unregistering players from the BCNM when the finishing CS is done.
Battlefield closing/clearing/wiping after all players are out of the BCNM.
Warping players out of the BCNM and closing the BCNM when all players lose.
Spamming of CS when the BCNM is won/lost."

**Comment by TeoTwawki** [comment]
> Server Version (type `@revision` in game) :
@ revision in game

I see what you did there

> admin on my server submitted a fix for bcnms by calling player:bcnmleave(1) in the oneventfinish after CS. considering that cs gets triggered during leavecode 2, it seems wrong to me that you would need to call leavecode 1 to make leavecode 2 work.

```lua
-- Leaving the BCNM by every mean possible, given by the LeaveCode
-- 1=Select Exit on circle
-- 2=Winning the BC
-- 3=Disconnected or warped out
-- 4=Losing the BC
-- via bcnmLeave(1) or bcnmLeave(2). LeaveCodes 3 and 4 are called
-- from the core when a player disconnects or the time limit is up, etc
```

I don't understand why leavecode 1 would work..

**Comment by cowrevenge** [comment]
I fixed this issue, waiting on review of changes.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/e3ffb1ed5a9e79d105e47b897614ba229aa682cb
