### ISSUE TITLE
Game Server Crashing On Ranged Weapon Equip

### ISSUE THREAD

**Issue by BasiclySean** [DarkstarProject/darkstar#3310]
**_I have:_**

- [ x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160728_0

**_Server Version_** (type `@revision` in game) **:**
bfe8b06dd7c4de32c6d0b694636d292d93708f81

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
The thread 0x7694 has exited with code 0 (0x0).
Exception thrown at 0x74E5DAE8 in DSGame-server.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0057E5F8.
Exception thrown at 0x74E5DAE8 in DSGame-server.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0057E5F8.
Exception thrown at 0x74E5DAE8 in DSGame-server.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0057E5F8.
Exception thrown at 0x74E5DAE8 in DSGame-server.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0057E5E0.
Unhandled exception at 0x6B18468B (ucrtbase.dll) in DSGame-server.exe: Fatal program exit requested.

Steps to reproduce:
1. Set your job to COR or RNG
2. Go to equipment and equip a ranged weapon
3. Game server crashes

When debugging on my own, I found that this is happening during the code that determines the weaponskills the character should have with the newly equipped weapon. In particular, I believe it's crashing when it gets to Wildfire. Line 603 in map.cpp is throwing the exception above.

`PacketParser[SmallPD_Type](map_session_data, PChar, CBasicPacket(reinterpret_cast<uint8*>(SmallPD_ptr)));`

**Comment by csundman** [comment]
This was happening on my server as well.  I temp-fixed it by checking wsid against the count of the array object holding your learned weaponskills in the "hasLearnedWeaponskill" function, and returning false if it would go out of bounds.  I'm sure there's a much more complete fix but that's letting things work my server for now.

Sorry I can't give you the actual code... I'm not at my home PC at the moment.

**Comment by teschnei** [comment]
Eh.. silly off by one error in the bitset size..
