### ISSUE TITLE
Ranger delay on client longer than retail

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3313]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160629_1

**_Server Version_** (type `@revision` in game) **:**
c004e9fd12e78f9a90d628a1c8cd65af97165efb

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

As is, the current ranger delay POST ATTACK is incorrect vs retail.  The delay of the weapon was corrected in the last build.

After the animation sheating animation finishes, there is right now ~2-3sec delay before an arrow is allowed to be shot again.  In retail, this delay is more like ~.5sec depending on packet timing.

This is a pretty significant DPS reduction in ranger and also breaks the addon auto ra.

In rangestate.cpp, there is a +2 sec delay included in the wrapup code.  I assume this was to emulate the 1.7 sec delay noted above, but in reality it is simply adding an additional fake delay.

**Comment by teschnei** [comment]
It's supposed to be 1s + ammo delay (charentity::onranged...), where the ammo delay is the offset value.  Unfortunately, a pull request removed the offsets so that everything got increased by 2sec...

It might be possible to move that out of the controller and into ranged state, replacing the 2s you mentioned.  I don't actually remember what it was there for (but it's not the cause of this problem)

**Comment by abriasffxi** [comment]
Sorry, I don't follow.  All of that code looks botched to me.

static_cast<CPlayerController*>(PAI->GetController())->setNextRangedTime(server_clock::now() + 1s + std::chrono::milliseconds(this->GetAmmoDelay()))

GetAmmoDelay pulls delay as a value to be converted to seconds by dividing by 60, which isn't done here.  So this reads 1s+60ms for a typical 120 delay arrow.  Still, I don't even think that's how retail works, but I don't have an active sub to test.  It's certainly not causing 3+ seconds of delay.

**Comment by teschnei** [comment]
A 120 delay arrow is 1 second.  So 1s + 1s would fall within your 2~3 sec observation, taking into account tick rate and packet rate.

**Comment by abriasffxi** [comment]
Right, but this simply isn't how it's done in retail anymore.  Maybe in 2004.

See extensive testing in BG that shows ammo delay doesn't factor in anymore, at all, except for TP.  To be fair, they then use /106 as the divisor.

https://www.bluegartr.com/threads/116145-Ranged-Delay-Snapshot-and-Stuff 

This huge delay just does not exist in retail after the shot, no matter what the cause in the code.  Autora works perfectly fine in retail with any ammunition but does not work in dsp due to additional delay after the animation is over.

**Comment by teschnei** [comment]
I literally did all the testing for this myself less than a year ago, I am pretty sure that is how it works.  As I was saying before, the delay of all ammo is offset by 240 in the database (2 seconds), which is probably your problem.

**Comment by teschnei** [comment]
Sorry, they USED to be offset by 240 (ie, a 120 delay arrow would be -120), and the code is most likely expecting that.

**Comment by abriasffxi** [comment]
I don't see anywhere that expects any offset, unless that's what the +2sec in aimtime was for.  Regardless, I'm just pretty sure that ammo delay is not a factor anymore.

FWIW, I found the update that reduced the delay, linked below.  It seems silly not to have this change in considering the reduced mana cost and cast time, and increased WS damage and TP gain is in for melee.  This was the buff that kept RNG together with those.
*Adjustments to ranged attack delay
-Up to 50% reduction between ranged attacks 
http://iyouboushi.com/forum/index.php?/topic/806-final-fantasy-xi-thread-4-now-with-more-balance/page-6 

Also, here's a vid of what a ranger looks like after the update.
https://www.youtube.com/watch?v=PEPLYoguK68 

I'll change it on my server, you guys can do whatever you want.

**Comment by teschnei** [comment]
I don't know why you are bringing up an update from 2012?  What makes you think that we don't want the ranged delay to be the same as current retail?
