### ISSUE TITLE
Regular (weekly) conquest update not applying to some things

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3319]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160629

**_Server Version_** (type `@revision` in game) **:**
c004e9fd12e78f9a90d628a1c8cd65af97165efb

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
A normal weekly conquest update is not resetting item timers (chariot band etc) recharge timers, and it looks like the regional vendors are spotty.  I had it work a few times, and then not work this last Sunday.

After forcing a @updateconquest this morning, both items above were solved.

**Comment by Hozu** [comment]
I find that bands, for whatever reason, update the next day at server midnight.

**Comment by teschnei** [comment]
Bands were scripted long before conquest update was

**Comment by abriasffxi** [comment]
Alright that's fair - I think the vendors were just me being an idiot.
