### ISSUE TITLE
CN and Boyahda Tree Coffer (maybe others?) not showing on widescan 

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3320]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160728_0

**_Server Version_** (type `@revision` in game) **:**
bfe8b06dd7c4de32c6d0b694636d292d93708f81

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
After updating today, I went to do ranger AF in CN and help a friend with ninja AF in TBT.  We found the coffers but neither showed up on widescan, even when right next to it.  Didn't notice any blank spots or anything so might be related to a flag.

**Comment by ibm2431** [comment]
It would appear that treasures were deliberately excluded from widescan in #3265 and #3271, which as far as I'm aware is the same behavior as retail.

**Comment by abriasffxi** [comment]
Oh snap, didn't remember that right at all.  Thanks!
