### ISSUE TITLE
Mobs Spell / RA range not interrupted by distance

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3321]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160728_0

**_Server Version_** (type `@revision` in game) **:**
bfe8b06dd7c4de32c6d0b694636d292d93708f81

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Thanks to @bendangelo , spell/ra casting mobs have much better pathing after I updated.  However, they now do not have spell/ra interrupted by distance.  I haven't been able to test abilities yet, but I'll try over the next day or so if it helps.

Thanks!

**Comment by abriasffxi** [comment]
Also; The mobs path correctly but they do not turn and face the character.  Should I create a separate issue or?

**Comment by neosatus** [comment]
Spells not being interrupted by distance was an intentional change done recently though I'm not sure of the reasoning.

**Comment by abriasffxi** [comment]
Uh... well I'm not sure how that could possibly be the case in the quest to mimic live.  We're eating huge AOE's pulling....

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/7b99d3cf40a9ac55ad5bebe4d6fae2d011ec9915

which was originally part of this pull request https://github.com/DarkstarProject/darkstar/pull/3276

Obviously there has to be a casting range limit for mobs somewhere somehow, so if that change is correct something else needs done.

**Comment by teschnei** [comment]
I don't remember what the mobs spellcasting range is.  30? 40?

**Comment by TeoTwawki** [comment]
It might vary by mob? regular exp mobs I'm out of range by 30 for sure, if not any sooner.

**Comment by TeoTwawki** [comment]
edit: meant to say by 40

**Comment by abriasffxi** [comment]
Can't find it on BG, but ffxiwiki says 26.8 yalms to start casting, 28.5 yalms to cancel.  I think as long as its more than 25 (so rangers can't cheese worms) and less than ~30 it will at least not be that noticeable.

http://ffxiclopedia.wikia.com/wiki/Distance

**Comment by 7cipherx7** [comment]
in "CMagicState::CanCastSpell" this check is the 40Y if "(distance(m_PEntity->loc.p, PTarget->loc.p) > 40)" but this needs to take to account speed_mod: X so if speed_mod: is just 25 the value of 40 is very close to what the check needs to be since speed_mod: of 25 would check up to 39.47Y to be accurate with speed vs distance check on retail, 99% of private server go way pass the 25 speed increase so 28.5 check is a joke, if we make this dynamic with speed_mod 28.5 would work fine

**Comment by abriasffxi** [comment]
To be fair, I don't think 99% of DSP servers exceed 25 nor should the base code be marginalized because it's not flexible to account for non-retail behavior.

This change makes it very difficult to pull correctly at the moment.

**Comment by TeoTwawki** [comment]
What matters is the behavior at retail settings..Your speed has no bearing on the distance, if speed is non retail obviously its going to be easier to get out of range before the spell finishes. If its a problem for a server they can modify the distance but we need to work "like retail does" by default.

**Comment by abriasffxi** [comment]
Anybody know how to fix this?  We're trying to get King B down..
