### ISSUE TITLE
Chocobo Digging produces pretty much no results

### ISSUE THREAD

**Issue by AeriusOhara** [DarkstarProject/darkstar#3323]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160728_0

**_Server Version_** (type `@revision` in game) **:**
Unknown (zip downloaded it yesterday night (~10 hours ago), sorry!)

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Related to: /scripts/globals/chocobo_digging.lua
Most of the time when digging with a chocobo you get no message whatsoever. As far as I can remember it should always say "You dig and you dig, but find nothing" when an item was not dug up. This makes certain items unobtainable that are needed for some crafts (Lizard Molt->Seer's Crown)

I tried to look into it myself but I know very little of chocobo digging to fix it, But as far as I can see on line 150 the Chance variable (which was multiplied by 1000 on line 142 and has a chance of being halved on line 147) is compared to (and has to be lower than) RItemAbundance + DIG_ABUNDANCE+BONUS combined. The Chance value is very (very!) rarely lower than the above and also gives no feedback to the player on what happened. The chocobo digging animation plays and the Gysahl Green is consumed but the player is left to guess whether it succeeded or not as they get no message indicating whether something happened or not. I don't believe this is the correct behavior and I couldn't find anything else in the issues relating to this.

Steps to reproduce would be to simply pick a chocobo, a stack of gysahl greens and digging in South Gustaberg or anywhere where it is allowed. Most of the time nothing will happen when you execute dig (the digging animation will play, and the gysahl green will be consumed)

My apologies if I reported this wrong, it's my first issue ever and I pretty much referenced other issues as a base.

**Comment by R3P0FFXI** [comment]
@AeriusOhara What is your digging skill level? Even on retail if your skill was 0 you pretty much got no results. It was a bit better after you managed to level up the hidden digging skill to 5 or even 10.

**Comment by AeriusOhara** [comment]
@R3P0FFXI When you say "no result" even on retail, do you mean literally no feed back? I'm used to FFXI always telling you that you can't do something, or whether or not your action has resulted in success or failure.

This is a screenshot of my digging attempts
[http://i.imgur.com/kE3rKOP.jpg](url)
I bought 84 Gysahl Greens and was able to dig 57 times before (I believe) fatigue set in and it started telling me I "must wait longer to perform that action." As you can see in that screenshot out of the 57 times I dug I was only told 10 times "You dig and you dig, but find nothing." So what happened the other 47 times? I'm not sure if that is normal behavior, my bad if it is.

My skill in chocobo digging was beginner, I had just picked up my chocobo licence. I can't verify on retail since I would really rather not resubscribe just to check for that. However I came across chocobo digging videos on youtube and every time the person digs, whether it be successful or unsuccessful they got feedback in the chat log telling them at least something happened instead. On Darkstar the Gysahl Green gets consumed and nothing happens most of the time, and very few of the digging attempts results in you finally getting some feedback by seeing "You dig and you dig, but find nothing." appear

**Comment by wrenffxi** [comment]
I believe this can be closed.  Resolved by #4157 and #5320.

**Comment by TeoTwawki** [comment]
If there are still digging problems, open new ticket
