### ISSUE TITLE
Can't go in-game when the server CPU is ARM architecture

### ISSUE THREAD

**Issue by thedax** [DarkstarProject/darkstar#3338]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
August 2016 client

**_Server Version_** (type `@revision` in game) **:**
f8175463415d4964d3deb2492d73a1bd03b548c6

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
This has been posted on the forums in the past ( https://forums.dspt.info/viewtopic.php?f=5&t=2056 ), but I figured it's worth bringing up here. Basically, when you try to go in-game on a darkstar server running on ARM (more specifically, a Raspberry Pi 3, though it looks like this problem has persisted since before this model came out, so I'd guess they're all affected), the dsgame server acts as if the client isn't there (or somehow the encryption is bad) and eventually the client gives up, saying there was no response.

[29/Aug] [04:54:45][Debug] Player <Testchar> logging in to zone <230>
[29/Aug] [04:54:45][Info] parse: 00A | 0001 0000 2E from user: Testchar
[29/Aug] [04:54:45][Debug] CZone:: Southern_San_dOria IncreaseZoneCounter <1> Testchar
[29/Aug] [04:54:47][Info] parse: 00A | 0002 0000 2E from user: Testchar
[29/Aug] [04:54:47][Warning] Client cannot receive packet or key is invalid: Testchar

Specs of the Pi 3:
pi@raspberrypi:~/darkstar $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

pi@raspberrypi:~/darkstar $ uname -a
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

pi@raspberrypi:~/darkstar $ gcc-6 -v
Using built-in specs.
COLLECT_GCC=gcc-6
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 6.1.1-11+rpi1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 6.1.1 20160802 (Raspbian 6.1.1-11+rpi1)

I don't have any other ARM boards, so I dunno if this is Pi specific or ARM specific.

**Comment by teschnei** [comment]
it's probably the zlib decompression.  I don't know anything about ARM (or
have any way to test that).

**Comment by thedax** [comment]
Have any ideas we could try to test if it's zlib (I can hop on IRC if you like)?

**Comment by teschnei** [comment]
debug it with gdb... it's not exactly something easy to look into - I had
to mess with it when making 64 bit work and it was a total pain in the ass.

**Comment by Cloudef** [comment]
The zlib.cpp reads 32bit pointer table from file, and this was problematic with 64bit in past because it treated them as machine width pointers in code. The code nowadays should use explicit width types (uint32_t, uintptr and such), but I guess there is still something with ARM that fails. I have ARM device too (armv7) so I can probably look at it. @teschnei Do you know if this is some custom zlib compression? Can we just change it to use libz instead?

**Comment by teschnei** [comment]
no idea

**Comment by Cloudef** [comment]
Yup, it might be worth checking if libz can decompress x86/x86_64 compressed data, if so, good change we can replace the pointer table compressor with libz. If that doesn't work, just need to check where the difference with ARM happens obviously.

**Comment by Cloudef** [comment]
I did look into it, it's not really DEFLATE algorithm at all, but something custom perhaps (as I could not find anything resembling what XI does from wikipedia).

Anyhow, while I was learning that zlib.cpp, I did tool for encoding/decoding and cleaned the code quite a bit. This seems to work on the armhf I have here, but I doubt it works on big endian which I will also fix before submitting patches to darkstar.

I'm attaching the tool here for you to test and confirm as well:
[xic.zip](https://github.com/DarkstarProject/darkstar/files/454135/xic.zip)

Unzip it into your darkstar source and run:
```sh
tcc -std=c99 xic.c -o xic
./xic enc ../compress.dat < map.dec > map.xic.enc
./xic dec ../decompress.dat < map.enc > map.xic.dec
diff map.enc map.xic.enc &>/dev/null && printf -- "encoding: ok\n" || printf -- "encoding: failed\n"
diff map.dec map.xic.dec &>/dev/null && printf -- "decoding: ok\n" || printf -- "decoding: failed\n"
```

**Comment by thedax** [comment]
I found this on the forum: https://forums.dspt.info/viewtopic.php?f=22&t=2386&hilit=zlib

So I guess the current zlib.cpp is an implementation of that reverse-engineered code.

Anyway, your code works for both encoding and decoding, so I think we're good.

**Comment by Cloudef** [comment]
Thanks for the url, those seems to be original code decompiled and converted to C++. I noticed even the current implementation has some cases which are probably not handled correctly. E.g. map.cpp uses fixed packet buffer size which may be wrong. I'm pretty sure it has nothing to do with zlib though :)

**Comment by Cloudef** [comment]
@thedax I've pushed the code here https://github.com/Cloudef/darkstar/tree/zlib, can you give it a spin for me. I don't have whole ecosystem on my arm machine, so I can't run whole server there. From quick testing I did not notice any regressions on x86_64. 

The standalone c99 tool code can be found here now: https://gist.github.com/Cloudef/0d22235b87b8f53d65f8828cb7b66db7

**Comment by thedax** [comment]
I'll test ASAP once I get a few other things done. Shouldn't be more than an hour-ish.

**Comment by thedax** [comment]
@Cloudef we're getting closer, but we have a problem:


[05/Sep] [23:01:47][Warning] Client cannot receive packet or key is invalid: Testchar
[05/Sep] [23:01:47][Warning] zlib_compress: ran out of space

**Comment by thedax** [comment]
It's showing "ran out of space" on line 171 in zlib.cpp.

**Comment by Cloudef** [comment]
Hmm the arm specific bug may be before the zlib compression then. Just in case can you dump the input here https://github.com/Cloudef/darkstar/blob/zlib/src/common/zlib.cpp#L171 like:
```
FILE *f = fopen("/tmp/map.dec", "wb");
fwrite(in, 1, in_sz, f);
fclose(f);
abort();
```

And post it here.

**Comment by thedax** [comment]
```
dax@raspberrypi:/tmp $ hexdump map.dec
0000000 044f 0001 0000 0000 820a 0001 5544 0000
0000010 0400 bf00 0000 0000 0000 0000 0000 c130
0000020 0000 0000 2828 0064 8100 0000 0000 0000
0000030 0000 0000 0000 0000 00e7 0000 0000 0000
0000040 8f95 57ce 1225 1b9e 0000 00e7 0100 1000
0000050 2008 3008 4008 5008 6015 7000 8000 006b
0000060 006b 006b 006b 00d4 0000 0000 0000 0000
0000070 0002 11f8 1b9e 0000 0000 0000 0000 0000
0000080 0000 0000 0000 0000 0002 0000 6554 7473
0000090 6863 7261 0000 0000 0000 0000 0000 0000
00000a0 0000 0000 0000 0000 000b 0000 0000 0000
00000b0 0000 01ff 0000 0000 0000 0000 0001 0000
00000c0 0000 0000 0000 0000 0000 0000 0000 0000
00000d0 0000 0000 0008 0007 0006 0007 0005 0005
00000e0 0006 0000 0000 0000 0000 0000 0000 0000
00000f0 001f 0000 0000 0000 0000 0000 0000 0000
0000100 0000 0000 0000 0000 0001 0000 1a08 0001
0000110 0000 0000 0000 0000 0000 0000 0000 0000
0000120 0000 0000 0000 0000 0000 0000 0080 0000
0000130 0000 0000 0000 0000 0000 0000 0000 0000
0000140
```


[map.zip](https://github.com/DarkstarProject/darkstar/files/456402/map.zip)

**Comment by Cloudef** [comment]
I force pushed over and tested this on my arm https://github.com/Cloudef/darkstar/tree/zlib
The problem is that darkstar relies on chars (and thus int8) to be signed. Fortunately on gcc we have -fsigned-char, but in future we should get rid of cbasetypes.h (it's plain wrong)

**Comment by thedax** [comment]
It's working now, just needs any cleanup and a pull request, nice work @Cloudef.

![Image of in-game w/raspi 3 server](http://i.imgur.com/GP8oprZ.jpg)

**Comment by Cloudef** [comment]
Sent PR https://github.com/DarkstarProject/darkstar/pull/3355

**Comment by thedax** [comment]
Closing since #3355 fixed this.
