### ISSUE TITLE
BCNM Cleanup doesn't run after maat fight (win/loss)

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3339]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160728

**_Server Version_** (type `@revision` in game) **:**
8f5c1b2aff

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

(Linux server)  After fighting maat, win/loss/timeout, I get a cutscene loop of respawning and cleanup doesn't run until I GM zone.  Console is spammed with You have exceeded your time limit! and Losing conditions met. exiting the battlefield.

I noticed when I GM Zone, I finally get the message All players have fallen.  Cleanup runs after that, so perhaps the problem is that cleanup is only called in this instance when all players have fallen.  Dunno.  I don't have a log of when I won, but could do so if it would help.

**Comment by LocoFFEra** [comment]
This has been basically going on for months now, quite the annoying issue. When the fight stops @ 10%, it's not recognizing it as a "win" and the player gets stuck in a cutscene loop and either needs to log out or manually get GM homepointed.

**Comment by abriasffxi** [comment]
Alright, went ahead and did a win and 

BCNM 195 battlefield 1 : Winning conditions met. 

is getting spammed in the console.

**Comment by teschnei** [comment]
I fixed this for ouryu, but disabled Maat's alternate win condition.  So once someone readds Maats special win condition to his script (not the cpp file...), this can be closed
