### ISSUE TITLE
Missing ??? near Boreal Coeurl for G2 limit break

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3341]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160728_0

**_Server Version_** (type `@revision` in game) **:**
Unknown (that's what it says when I type @revision)

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
The ??? is missing near the Coeurl for G2. My test server isn't up and running so I can't check this to be sure but I believe that the ??? was previously up before engaging the Boreal Coeurl.

**Comment by abriasffxi** [comment]
Mine is present on my very up to date server.  Are you saying it disappears after engaging the coeurl?

**Comment by abriasffxi** [comment]
Well, I killed it and its still there.

**Comment by Fiocitrine** [comment]
hmmm I'm not sure then. I know it's not present anywhere near the coeurl.

**Comment by Fiocitrine** [comment]
Maybe whasf needs to update?

**Comment by thedax** [comment]
Do you have the OldSchoolG2 option turned on?

**Comment by TeoTwawki** [comment]
5da858075a229d270e02013f6ae5fad7b5116cb2
