### ISSUE TITLE
Superjump crash on debug break

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3345]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Server Version_** (type `@revision` in game) **:**
8/30 version

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
DRG ability has player:stun(5000) in script. That triggers a debug break on luabaseentity.cpp:10104

inline int32 CLuaBaseEntity::stun(lua_State* L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
  --here!!--  DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_MOB);
    DSP_DEBUG_BREAK_IF(lua_isnil(L, 1) || !lua_isnumber(L, 1));

    m_PBaseEntity->PAI->Inactive(std::chrono::milliseconds(lua_tointeger(L, 1)), false);

    return 0;
}

**Comment by whasf** [comment]
ability is Super Jump, sorry i didn't put that in original post.

**Comment by takhlaq** [comment]
dat code quoting tho

**Comment by takhlaq** [comment]
if the player is supposed to be unable to do anything for a while after super jump just remove the line with the objtype check

**Comment by whasf** [comment]
Sorry, the version of windows that oldschool is running on hasn't been updated yet (I haven't had time due to travel for work).
Why wouldn't we allow players to be stunned? Doesn't King Behemoth do that? It should have been crashing on his ability too.

**Comment by Hozu** [comment]
That stun function does something different from the stun effect, IIRC. But yes using Super Jump is supposed to make the player unable to do anything/be targeted/be hit by AoE for a couple of seconds (while they're in the air).
