### ISSUE TITLE
tier 2 merits rdm debuffs

### ISSUE THREAD

**Issue by whb07** [DarkstarProject/darkstar#3364]
Tier 2 debuffs- para2, slow2, etc don't appear to be overwriting para1 and slow2.

-after a lvl 75 sch lands debuffs and my rdm 75 fully merited+ properly geared throws paralyze 2, chat logs say (paralyze 2 has no effect) implying it's not overwriting and does not have a stronger effect/different one than paralyze 1. Can anyone look into this

**Comment by whb07** [comment]
I'll try and get a screenshot submitted soon enough

**Comment by teschnei** [comment]
Please create a new issue using the issue template.  Thanks.
