### ISSUE TITLE
PM 8-4: Final CS shows distorted characters.

### ISSUE THREAD

**Issue by nyczducky** [DarkstarProject/darkstar#3375]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30160831_1

**_Server Version_** (type `@revision` in game) 7a7a317c1a1e2052cf952379599cc6eafce2268f

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior):

Completion CS for CoP 8-4 in Empyreal Paradox shows distorted character models.

Steps to reproduce:
@zone36
@cs 0x0006

**Comment by gedads** [comment]
Thanks,at least promatia is missing, going to correct this tonight

**Comment by ibm2431** [comment]
I remember that Empyreal Paradox was one of the zones the batch tool picked up shifted IDs on when I ran it last. It seemed pretty certain about them, but there's at least four Promathias, Selh'teuses, and Prishes in the zone.

**Comment by nyczducky** [comment]
This issue was resolved with commit #1c7ddc85e09c89e299e19f6b9d8c5bd284f1bdc3
