### ISSUE TITLE
Self target ws's are broken.

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3387]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831-1

**_Server Version_** (type `@revision` in game) **:**
a4f0d0f980901666d3dd2ce6f10b538fb78f5086

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Self target weaponskills such as starlight produce an error stating you cannot see your target.

**Comment by phlare** [comment]
+1  was literally going to post an issue for this myself.   Not sure where to begin looking to fix it though.

**Comment by teschnei** [comment]
almost certainly in src/ai/states/weaponskill_state if anyone is interested enough to look into it before i do
