### ISSUE TITLE
Weapon skills hit for 0 if multiple are used within a short time

### ISSUE THREAD

**Issue by Fr0zt** [DarkstarProject/darkstar#3391]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831_1

**_Server Version_** (type `@revision` in game) **:**
4f9e62d6d4138b7b2b9db3e2bc88a381f6e1bcaa

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
(Most of this info comes from Teo, see discussion below)
This can be done solo or with others.

If solo:
Either use godmode or give yourself very high regain so that you can spam weaponskills.
Start using them as fast as the client will let you and you will start seeing 0's.

If with others:
Just have two or more people use weaponskills either at the same time or within a short time of each other and you will start seeing 0's.

**Comment by TeoTwawki** [comment]
I don't think thats the cause. I've seen it on other ws.

**Comment by TeoTwawki** [comment]
Also tested the miss theory, put my own acc bottomed out and went against a buffed mob, got normal miss messages and took more than 50 tries to get a zero dmg message.

**Comment by TeoTwawki** [comment]
Seems I can get it everytime if I give myself high enough regain to spam ws so fast that I am in the menu selecting again before the animation even finishes (which really should not be possible anyway, but somehow client let me overlap!)

**Comment by Fr0zt** [comment]
I could very well be completely wrong regarding my initial theory, that is just what it seemed since I would never land 0's on mobs that checked Tough or lower. I find it interesting that you have seen 0's on skills that don't use this param, as I have never once encountered that. It would either be a miss or just very low dmg, but never 0. However, once I had this param, it will start hitting 0's.

However, wouldn't bottoming out make you miss _every_ hit instead of just the first hit? That would make it give you the normal miss message, instead of 0. I was thinking:

Miss first hit - land next 4 hits - skill does 0

On a potentially unrelated note, I have seen blue magic do 0 pretty often (usually the lower level spells against high level mobs). I don't remember how blue magic worked on retail, or if it is supposed to be hitting 0's. It has been several years since I have played on the live servers.

But if you are getting 0's consistently when spamming, then maybe it is unrelated to any of the things we are discussing here?

**Comment by TeoTwawki** [comment]
Well Rudra's is a single hit WS, so it can't be related to multihit. So I tried to find some cause for it, printing every param and trying diff ws to see what was in common. To me hours to stumble on the fact it was only happening when multiple back to back ws's were being fired off rapidly. Till then I was doubting the resident thf telling me rudra's was randomly broken, and saw your issue right after he managed to show it to me (I hadn't realized there was already a report here).

**Comment by TeoTwawki** [comment]
edit: only happening for me during spammage. other tell me that in party it is "just random" we just that bugs hide when I show up so that everyone can look crazy when I can't find anything.

**Comment by Fr0zt** [comment]
Alright, then I am completely wrong thinking that it is related to multi hit. It sounds like it isn't even related to this param at all, in fact. I will edit the original post to reflect your input.

**Comment by Fr0zt** [comment]
After some additional testing, this seems to occur often, if not 100% of the time, when you use a weapon skill during or shortly after a mob uses a mobskill.

**Comment by TeoTwawki** [comment]
Makes this sort of an ah-ha moment for me hearing that. state related issue number 1223456....

**Comment by teschnei** [comment]
Seems to be working fine - using Combo unarmed on aerns while they WS

requesting detailed reproduction steps

**Comment by Fr0zt** [comment]
May have been a coincidence. This SEEMS random, but it isn't. My party and I were farming some mobs in sky and we got several 0's while weapon skilling at the same time as mobs use mobskills.

I went back to test my original theory again, with this being tied to params.multihitfTP and I am ONLY able to get this to happen with weaponskills that have this param added to. Although Teo claims to have seen it on other skills, I personally have not, and think that is why combo is working fine for you.

I added params.multiHitfTP to Vorpal Blade just to test and I have been getting 0's while spamming with 1500 regain. I have not been able to produce 0 dmg while this was not enabled on this skill. I have also seen it while not spamming, so I am not 100% sold on the idea that it only happens while multiple skill are going off.

Try this:

Add params.multiHitfTP = true to Vorpal Blade and start going to town on some mobs with it. You will start seeing them hit for 0. Myself and my party have confirmed and reconfirmed this several times.

**Comment by TeoTwawki** [comment]
I found it happening even without that param when I was testing with 2 other people. 
Paging @Heepster03 and @PikaFox, I know you two were there that day when I spammed ws to make it happen continuously and saw my chars animation go borked.

I've seen it with Dancing edge (multihit), Evisceration (multihit), Rudra's Storm (single hit ws), Resolution (multihit), Rampage (multihit), also been told happens with Last Stand, and one of the single hit KG ws's (I forget which one, not fudo..)

**Comment by Fr0zt** [comment]
So I guess my initial theory was correct regarding the first hit missing?

Teo, perhaps you are experiencing an entirely different bug regarding the animations? Would you be able to test and confirm after pulling this latest commit since I am not able to reproduce what you are describing?

**Comment by TeoTwawki** [comment]
No, I've seen it on single hit ws. I am 100% certain

**Comment by TeoTwawki** [comment]
sorry trying to type 6 places at once

**Comment by TeoTwawki** [comment]
I just said on irc a second ago there may be more than one single cause.

I -KNOW- I've seen it on single hit ws.

**Comment by Mizzguy** [comment]
Ive also notices some if not all of the ws torques from sea will cause ws to do 0 damage, although this could be a seperate issue i figured it was worth mentioning incase you were testing with one. I believe EES is the one i can 100% confir does it.

**Comment by Fr0zt** [comment]
Perhaps someone should write up a separate issue if you are still hitting 0's after pulling this latest fix? Like Teo said, there could be multiple causes to this bug and this may have only been one of them. I personally have not seen 0's for anything other than what I have reported and what was just fixed, so I would not be the best source for reporting additional causes for this bug.

**Comment by TeoTwawki** [comment]
same thing got said in irc a bit ago, but wasn't going to open it till I got a fresh post update screencap
