### ISSUE TITLE
Linux Server Crashes (max cpu?) with zlib_compress error/sea al

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3394]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831

**_Server Version_** (type `@revision` in game) **:**
6475f7ebaef

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
As discussed in IRC, I was seeing intermittent crashes that started happening when the server (Ubuntu Server 16.04 running on xeon 1270v5) reached moderately high cpu loads.

Found a way to replicate by maxing cpu with stress-ng and then aoeing about 30 mobs in Giddeus.  Consistently crashed 3 times in 4 pulls.  Ran with gdb and here is the backtrace.

```

[26/Sep] [07:09:50][Warning] zlib_compress: ran out of space (3854 : 11 : 3864 : 101)

Thread 1 "dsgame" received signal SIGSEGV, Segmentation fault.
send_parse (buff=<optimized out>, buffsize=buffsize@entry=0x7fffffffe808, from=from@entry=0x7fffffffe820, 
    map_session_data=map_session_data@entry=0x1d47a930) at src/map/map.cpp:682
682         WBUFL(PTempBuff, zlib_compressed_size(PacketSize)) = PacketSize;
(gdb) bt
#0  send_parse (buff=<optimized out>, buffsize=buffsize@entry=0x7fffffffe808, from=from@entry=0x7fffffffe820, 
    map_session_data=map_session_data@entry=0x1d47a930) at src/map/map.cpp:682
#1  0x000000000049551f in do_sockets (rfd=rfd@entry=0x7fffffffe880, next=...) at src/map/map.cpp:382
#2  0x00000000004073f7 in main (argc=1, argv=0x7fffffffea18) at src/common/kernel.cpp:303

```

After consultation with @Cloudef , reverted 47b3a5f, remade, and tried again.  We've done about 15 pulls now with no crash or any other random stuff in gdb.

**Comment by Cloudef** [comment]
You can blame me for breaking this. If you can get me dump for the data that causes the compression to fail by adding following lines after this line: https://github.com/Cloudef/darkstar/blob/zlib/src/common/zlib.cpp#L187
```
FILE *f = fopen("/tmp/map.dec", "wb");
fwrite(in, 1, in_sz, f);
fclose(f);
abort();
```

Other than that I see at least one problem that existed even before 47b3a5f commit, that is not checking the return value of zlib_compress and zlib_decompress functions, which is where unexpected -1 eventually leads to the crash, but this should confirm that before 47b3a4f the compression never failed.

**Comment by Cloudef** [comment]
For troubleshooting your CPU usage, see https://en.wikipedia.org/wiki/Perf_(Linux) which can show realtime disassembly of hot codepaths even. If perf points to darkstar code it may be worth posting.

**Comment by abriasffxi** [comment]
Sorry for the delay.  I added the dump code, reverted the revert, and remade this morning.  When it crashes I'll attach the dump.

**Comment by Cloudef** [comment]
Noted.

**Comment by eraffxi** [comment]
https://drive.google.com/open?id=0B25qGfQmrUa5SFJKXzE0dWYxbnM
cant tell exactly what caused this crash, didn't seem like this one was from dynamis.

**Comment by Cloudef** [comment]
I debugged this while ago with someone in IRC and IIRC we managed to reproduce the crash even with the code reverted. In short it seems like the preallocated buffer we use for compression is not big enough for some messages. The crash happens because the -1 return value from zlib_compress was never handled. This should be simple to fix at least, but I'm not sure what happens if we just drop the packet after failure. Other solutions is to dynamically allocate output buffer, or preallocate more. This may break client if it assumes some maximum packet size.

Anyhow, I think I should be able to reproduce this crash always by reducing the output buffer size.

**Comment by teschnei** [comment]
There's a maximum packet size for client, but only when compressed afaict
(which should be already implemented server side)

**Comment by helixhamin** [comment]
Any update on this? I have been able to complete Dynamis Sandy, but not Dynamis Windy or Bastok, because that is where this issue hits me.

**Comment by Cloudef** [comment]
It seems like dynamis windy / bastok can be used to reproduce this.

**Comment by Cloudef** [comment]
Please test #3772
