### ISSUE TITLE
Valor Coronet is not increasing Rampart duration

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#3404]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831_0

**_Server Version_** (type `@revision` in game) **:**
894def0

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
On Classic (Old School) server.

Equip Valor Coronet.
Use Rampart.

Expected duration to be 45 seconds.

Actually lasted 30 seconds (normal, non-enhanced duration).

**Comment by wrenffxi** [comment]
Fixed in PR #3414
