### ISSUE TITLE
Afflatus Skills available to /whm subjob 

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3429]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
301601831_1

**_Server Version_** (type `@revision` in game) **:**
50868e308882da87ca59798352f348186b000f2f

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
RDM 99 / WHM 49 Afflatus solace & misery skills available to /whm job even tho they should not be according to wiki

https://www.bg-wiki.com/bg/Afflatus_Solace

https://www.bg-wiki.com/bg/Afflatus_Misery

**Comment by zynjec** [comment]
This can be closed, resolved with https://github.com/DarkstarProject/darkstar/pull/4829
