### ISSUE TITLE
Trying to enter Promy's after completing the last mission crashes client and cannot re-enter

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#344]
Player has completed cop missions. On zonein from hall of transference, player crashes to desktop. Player cannot log in again until their zone is changed.

**Comment by helixhamin** [comment]
Is this still a thing? I thought this was fixed.

**Comment by takhlaq** [comment]
can someone other than nasomi test this? i don't exactly trust selectively manually copying in commits

**Comment by zynjec** [comment]
Unable to repro on master, closing for now.
