### ISSUE TITLE
Using Spirits within crashes server

### ISSUE THREAD

**Issue by Fr0zt** [DarkstarProject/darkstar#3440]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831_1

**_Server Version_** (type `@revision` in game) **:**
2564db15e5951d8623dd1d327607a2be889206c9

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Use Spirits Within on any mob, causes game server to crash.

**Comment by TeoTwawki** [comment]
Not crashing when I use it. You sure it was something else? Can you look use the debugger and see what it died on? (or just link us a dump)

**Comment by Fr0zt** [comment]
I will run the debugger when I get home from work, about 9 hours from the time I post this.

**Comment by whasf** [comment]
I am seeing it on the Oldschool server too. It is hitting a debug break point. I have temporarily disabled the weaponskill.
Here is the dump: https://www.dropbox.com/s/nezewx4fnlog9js/Spirits_within_debug_hit.7z?dl=0

**Comment by TeoTwawki** [comment]
lookin now

**Comment by TeoTwawki** [comment]
@whasf 
`int32 CLuaBaseEntity::takeWeaponskillDamage(lua_State* L)`
`{`
`    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);`
`    DSP_DEBUG_BREAK_IF(lua_isnil(L, 1) || !lua_isuserdata(L, 1));`
`    DSP_DEBUG_BREAK_IF(lua_isnil(L, 2) || !lua_isnumber(L, 2));`
`    DSP_DEBUG_BREAK_IF(lua_isnil(L, 3) || !lua_isnumber(L, 3));`
    **`DSP_DEBUG_BREAK_IF(lua_isnil(L, 4) || !lua_isboolean(L, 4));`**  <- you sploded here

Which means you are missing something that happened in https://github.com/DarkstarProject/darkstar/commit/c7aed5228dd812437a5b629897de083549fe4786

It works for me so I'm betting your global does not match trunk.

@Fr0zt check and see if yours is the same prob.

**Comment by Fr0zt** [comment]
Will do. I'll report back once I run the debugger this afternoon.

**Comment by TeoTwawki** [comment]
Actually now I see something..and am wondering instead of why yours crashes...why mine *doesn't*...

**Comment by TeoTwawki** [comment]
Yeah..Pull requesting fix. That'll learn me.

**Comment by TeoTwawki** [comment]
So. in addition to spirits calling `takeWeaponskillDamage` directly which no other ws does (because its not physical or magical or ranged, so this makes sense) and not getting that param added when takeWeaponskillDamage got changed, we also have 2 versions of takeWeaponskillDamage..One is a lua binding for a C++ function that takes a baseentity, and the other is a lua function..which calls the binding. Spirits uses the lua function one. 

[I've added the param and a comment for now.](https://github.com/DarkstarProject/darkstar/pull/3454) If someone else wants to make the naming less prone to future confusion, great (I'm not touching that for now, I'm obviously not the first person to see this and its stayed this long).

**Comment by teschnei** [comment]
They all use the lua function, yes?

**Comment by TeoTwawki** [comment]
@teschnei I stared confused momentarily at why 2 distances of the same function had differing syntax before realizing what it was doing and taking a minute to be sure which one the script should have. All the ` doWtfEver` functions in the global use the lua function, and the lua function calls that lua binding. But if you -only- looked at spirits_within.lua and already knew of the battelutils call thats a head scratching moment.

**Comment by TeoTwawki** [comment]
And I just realized I said the opposite of what I meant in my comment. Yay amend.

**Comment by TeoTwawki** [comment]
Er no. See. GDI, I'm re-confused just explaining it to you!
Spirits calls the binding directly. All the other scripts call a script to call the binding. good god. No amend need. And demo just merged so I'd be flipping out at my luck if I was wrong now.

**Comment by teschnei** [comment]
why not just have spirits within call the lua function? it doesn't really make any difference, but its more consistent, i suppose

**Comment by TeoTwawki** [comment]
A failed attempt at not doing the explaining. Because the diff would have shown entirely different syntax instead of slipping in one new param. But I just wound up explaining anyway. m(_ _)m my logic isn't the greatest when I am over 8hrs past where I should have fallen asleep.
