### ISSUE TITLE
DsGame crashes after a char zone to Tahrongin Canyon

### ISSUE THREAD

**Issue by icxb** [DarkstarProject/darkstar#3459]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game)  :30160831_1

**_Server Version_** (type `@revision` in game) **:  4f9e62d6d41

**_Source Branch_** (master/stable) **: master

**_Additional Information_** (Steps to reproduce/Expected behavior) **: I noticed that everytime one of my char zoning to an area, it will crash my server, zoning or using command  @zone 

i attached the dump file:

https://drive.google.com/file/d/0B5Eho6o--MjpNGo0blE5NGZKVGs/view?usp=sharing

Thank you

**Comment by teschnei** [comment]
"checked the commit log to see if my issue has been resolved since my server was last updated"

**Comment by TeoTwawki** [comment]
Tip: github sees mentions not GM commands. So all members of the public repo for Zone Ltd got notified of this issue. If you have to put a GM command into a gihub post, wrap it in back-tics: `@zone`

**Comment by icxb** [comment]
thank you teschnei & teo 👍 👍

**Comment by takhlaq** [comment]
> Please commit your changes or stash them before you merge.

**Comment by icxb** [comment]
I did commit, and merge.  After merge it says already updated, that is all right?

Though I saw my config reset back to default, I just have to update them right?

thank you demolish
