### ISSUE TITLE
Headstone Pilgrimage Opo Opos reappear if you click the stone too early.

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#3477]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831_1

**_Server Version_** (type `@revision` in game) **:**
7a7a317c1a1e2052cf95237959cc6eafce2268f

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Be on Zilart mission HEADSTONE_PILGRIMAGE.
Spawn the two Opo Opos at the Cermet Headstone in Yuhtunga Jungle.
After they die, but before they fade out, click on the headstone to attempt to get Fire Fragment.
Instead of receiving the KI, the Opo Opos reappear.

**Comment by phlare** [comment]
I thought I had the same thing happen with dark spark the other day, but I also may have been clicking the wrong torch after the fight. Will try to confirm.

**Comment by TeoTwawki** [comment]
@teschnei sounds related to what I was telling you last night about the death/fadout/repop

**Comment by teschnei** [comment]
i think you're right there - after death but before despawn they are
considered unpopped, and perhaps the complete var is not set until
onmobdespawn - so the check if theyre still spawned returns false before
they fade out, and it shows you having not killed them yet

i might be able to test the changes I made last night tonight

**Comment by TeoTwawki** [comment]
WHT...Why is this even a server var..
```lua

    if (csid == 0x00C8 and option == 1) then
        SpawnMob(17281031):updateClaim(player); -- Carthi
        SpawnMob(17281030):updateClaim(player); -- Tipha
        SetServerVariable("[ZM4]Fire_Headstone_Active",0);
```
```lua
    if (GetServerVariable("[ZM4]Fire_Headstone_Active") == 0) then
        SetServerVariable("[ZM4]Fire_Headstone_Active",1);
    elseif (GetServerVariable("[ZM4]Fire_Headstone_Active") == 1) then
        SetServerVariable("[ZM4]Fire_Headstone_Active",os.time()+ 900);
    end
```

**Comment by Kushdr** [comment]
It is most certainly that the variable is set in onMobDespawn.
Without changing anything, the easy answer is just wait until they depop.
Alternatively, could move that logic to onMobDeath to avoid waiting, although that would break the condition where you only have to kill one (if that's a thing for these two)

**Comment by TeoTwawki** [comment]
@Kushdr 
```lua
function onMobDeath(mob, player, isKiller)
    if (isKiller) then -- runs once per kill sicne 2 killers cannot land killing blow
        if (GetServerVariable("[ZM4]Fire_Headstone_Active") == 0) then -- this is zero at every spawn
            SetServerVariable("[ZM4]Fire_Headstone_Active",1); -- whichever NM dies first will set this
        elseif (GetServerVariable("[ZM4]Fire_Headstone_Active") == 1) then
            SetServerVariable("[ZM4]Fire_Headstone_Active",os.time()+ 900); -- whichever NM dies second sets this, the headstone looks for this.
        end
    end
end;
```

That oughta do it.

**Comment by teschnei** [comment]
This should be retested on latest, as I changed some of the despawn state
logic to accommodate it

**Comment by wrenffxi** [comment]
Tested and working on latest.
