### ISSUE TITLE
Current jail system poorly thought out

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3480]
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
irrelevant

**_Server Version_** (type `@revision` in game) **:**
a5cf446cb9e68c6dde1c1bc77d90eed84c67ea28

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Apologies if the issue title comes off insulting in any way. I dunno what else to call it.

Whatever the intent of `jailutils::Add()` and `jailutils::Del()` they appear to do absolutely nothing when given a binding to use them.  `jailutils::InPrison()` is literally nothing but a check to see the player is not a GM and their current zone is Mordion. This may as well not exist you could simply check those directly. This was not an improvement over using that crappy variable that used to be checked instead. 

If we went back to using the variable (which let me point out, I just called that method crappy _also_) it would _at least_ be trivial to block warping/teleporting/deathporting out by using one simple check (_and I could put the retail message there as well_).

``` c++
if (jailutils::InPrison((CCharEntity*)m_PBaseEntity))
{
    uint16 messageID = luautils::GetTextIDVariable(131, "NO_ESCAPE");
    ((CCharEntity*)m_PBaseEntity)->pushPacket(new CMessageSpecialPacket(m_PBaseEntity,messageID,0,0,0,0,0));
    return 0;
}
```

I can't do this when being non GM and in zone = being jailed, because then the GM can't release them. I honestly can't think of a non retarded way to do this, unless Add/Del in jailutils are intended to prevent player actions somehow that and state is stored somewhere between sessions and are just broken but fixable. Currently neither function is called anywhere at all in the trunk.

On a default build of darkstar if you have to jail a character, they can just ignore it and exit by a variety of means. Scroll of instant warp, whm teleport, blm warp spells, retrace, dying and homepointing (elshimo pachira or poison pots)..Even worse for server that give their players free transportation commands. Multiple servers I know have worked around this by editing every lua script that moves a player and checking for the old variable `isJailed`. 

Ideally I'd rather jailing not use `char_vars`, but still be stored to the db in some way - it would be nice to include that "reason" string the `@jail` command uses to give servers some basic record keeping too.

I'm willing to do the edits, but not without some consensus on what we want to actually happen here first.

**Comment by teschnei** [comment]
I thought you can't use items or spells while in jail? The ai controller
you get has them all disabled. Did that stop working?

**Comment by TeoTwawki** [comment]
blm spell works, scroll of instant works, nothing seems to be disabled at all.

**Comment by nyczducky** [comment]
Correct. Spells and all item based teleports will get you out. 

I had to code a block based on Zone ID to each spell, item, etc. Which is a crappy way of handling it to prevent people from escaping.

**Comment by teschnei** [comment]
I need to be reminded to look into this when I am home (terrible memory)
