### ISSUE TITLE
Server randomly loses track of NPC 16982042

### ISSUE THREAD

**Issue by starlightknight** [DarkstarProject/darkstar#3490]
**_I have:_**
- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
v_30161004_1

**_Server Version_** (type `@revision` in game) **:**
#3488

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

NPC 16982042 has the name ''

This name appears to be required as client crashes occur if it is changed to any of the other generic cutscene npc names like "blank". The server randomly loses track of this npc after it has been accessed a few times. Once the server loses track of the npc, it will begin logging **Server Need NPC <16982042>** warning, and any client viewing a cutscene where this npc is involved will get a client crash. The only way to fix it is to restart the server.

**Easy reproducing steps:**
- Use cutscenes a the Imperial Whitegate. TOAU-46 Imperial Coronation is particularly effectively at causing this to happen fast - sometimes as soon as the second time.

**Comment by starlightknight** [comment]
@teschnei This also appears to be happening to 16998981, which also has this character as the name. In this case, the npc is labeled ship in POLUtils so I'm assuming its the Cutter's ship model. Calling GetNPCByID on it will return nil despite it being in the DB. This might block me from implementing the arrival/departure of the cutter's model depending on what's necessary (in the early stages of looking at that).

**Comment by gedads** [comment]
those are the boats npcs. i think that if those anmes are changed they stop working like doors (departures / arrivals anims were once working in dsp https://www.youtube.com/watch?v=cy9dqQfjWks)
