### ISSUE TITLE
Combat and Magic Skills no longer show as capped when they are capped

### ISSUE THREAD

**Issue by Fr0zt** [DarkstarProject/darkstar#3497]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
11e24ac0e006b769b313f626cbc37b5d1d4a375c

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
~~Skill ups no longer work. Fight a mob that normally would give you a skill up for any combat or magic skill and you will not receive any skill ups.~~

~~My current example is being lvl 75 SAM with merited Great Katana skill cap, currently not capped at 286. Farming Groundskeepers in sky would not give myself or anyone in my party skill ups.~~

~~This also seems to affect magic skills. We have a WHM that is not receiving any Healing Magic skill ups from curing the party.~~

After re-testing skill ups do work, the skills just no longer show as being capped (not showing blue text).

**Comment by nyczducky** [comment]
Unequip and re-equip your great katana.

It's a bug that caps your weapon based combat skills early.

**Comment by Fr0zt** [comment]
I will try that when I get home this afternoon, however this is also affecting magic skill ups. We could not raise Healing Magic, Enhancing Magic, etc. either. Will re-equipping fix that as well?

I believe I have seen the bug you are talking about before, but I am not sure this is the same thing, as this is not showing that the skills are capped (blue text).

**Comment by Hozu** [comment]
If it's not showing the stats capped in your status, it's a different bug. The other bug is where a skill shows capped in your status because you just hit the skill cap vs. the mob you're fighting - even if that mob is a lower level. Which will prevent you from getting more skillups for that skill until you change your weapon.

**Comment by Fr0zt** [comment]
That is what I figured, which is why I reported this as a separate bug and tried to make it clear that the skills are not showing that they are capped. In fact, we even tested a WHM with 0 healing skill casting cure several times and no skill ups were had.

I am thinking this is related to ef35fcd882f62ca0422e391d7554aa5535792480 but I am not 100% sure. This has never happened until I updated the server last night.

**Comment by nyczducky** [comment]
That was my fault. Selective reading on NYC subways. 

I'll see if I can duplicate.

**Comment by Fr0zt** [comment]
So after re-testing we discovered that our skills were actually capped, they were just showing that they were uncapped. Reverting the changes made in ef35fcd882f62ca0422e391d7554aa5535792480 my skills now correctly show that they are capped.

Turns out skill ups are not actually broken, they are just don't show as capped. We must have just gotten unlucky with skill ups in our original test.
