### ISSUE TITLE
Several errors in game server log while booting

### ISSUE THREAD

**Issue by Fr0zt** [DarkstarProject/darkstar#3502]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
N/A

**_Server Version_** (type `@revision` in game) **:**
fcf28b0645f95609659419238b24a30b3b27c74c

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Upon updating and restarting the server, several errors occurred while booting the game server. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/10720170/19826450/db2ff332-9d58-11e6-9bee-67c8d51bbccb.png)

**Comment by TeoTwawki** [comment]
#3503

**Comment by Fr0zt** [comment]
Just updated again and got a few more:

![image](https://cloud.githubusercontent.com/assets/10720170/19826635/9dd2387e-9d5d-11e6-90b5-7c084d88322d.png)

**Comment by Fr0zt** [comment]
Alright, is this issue good to be closed then?

**Comment by TeoTwawki** [comment]
Yeah and I'll go see about those jobs in a min or two. I hate extra junk in log :)
