### ISSUE TITLE
No-wait Dynamis

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3513]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
latest

**_Server Version_** (type `@revision` in game) **:**
latest

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
It was reported to me that you can freely enter dynamis, even though the settings.lua are 'stock' (wait time is set to 1 real day)

**Comment by Mizzguy** [comment]
What i did and im not sure it was correct but , i changed the "or" to "and" in the trail markings. And it functions correctly.

elseif ((dynaWaitxDay + (BETWEEN_2DYNA_WAIT_TIME * 24 * 60 * 60)) < realDay or player:getVar("DynamisID") == GetServerVariable("[DynaBastok]UniqueID")) then

**Comment by Hozu** [comment]
IIRC the issue has to do with the entry into the "battlefield" not being done properly.

**Comment by Hozu** [comment]
@Mizzguy because the "battlefield" entry is not being done properly, the server variable doesn't get set - just left at 0. Which is what is causing the problem.

**Comment by TeoTwawki** [comment]
Someone do me a favor, make a single issue summering everything screwed in dynamis right now, and I'll close out all these olds one. All the recent ones boil down to the thing Hozu pointed out. Annoyingly someone saw fit to leave a print in the core even though its never anything but zero. 

```cpp
CBattlefield::CBattlefield(CBattlefieldHandler* hand, uint16 id, BATTLEFIELDTYPE type) {
    m_Type = type;
    m_BcnmID = id;
    m_Handler = hand;
    locked = false;
    m_FastestTime = 3600;
    m_DynaUniqueID = 0;
    treasureChestSpawned = false;
    m_entrance = 0;
    m_lost = false;
    m_won = false;
}

//Create dynamis unique ID for player can't cheat by leaving a dynamis before the end and enter the next
void CBattlefield::setDynaUniqueID() {
    //#TODO maybe, or just get rid of the entire dynamis functions section
    //m_DynaUniqueID = m_BcnmID + m_StartTime;
    printf("uniqueid core: %u", m_DynaUniqueID);
}

uint16 CBattlefield::getDynaUniqueID() {
    return m_DynaUniqueID;
}
```

Not even the kind that we can filter in the conf, its the kind you have to comment out and recompile to be rid of.

**Comment by teschnei** [comment]
I think it was me that commented out the "unique ID" - it doesn't really make a lot of sense (it doesn't even guarantee uniqueness...).  I think the start time got changed into a chrono datatype and I had zero motivation to even look at anything related to dynamis.  Maybe it'll work if you just change back into seconds... but it still doesn't guarantee uniqueness.

**Comment by TeoTwawki** [comment]
@teschnei I'm of the opinion that 99% of the dynamis code in core is dogdoo and should be obliterated. Including this. We should use status effect to determine who can enter. Unfortunately current dynamis scripts are all looking for that stupid servervar+player var combination. Lamebus too.

**Comment by teschnei** [comment]
Yes of course :) I thought you were just looking to do minimum maintenance.
But that's better

**Comment by whasf** [comment]
@TeoTwawki there is a bcnmrewrite branch already that is supposed to fix all the problems with the current implementation, but it seems to have stalled.

**Comment by takhlaq** [comment]
im not going to touch it until ive figured out how retail tells apart entry into multiple choice bcnms on trade/talk and conditions for party members to enter

**Comment by TeoTwawki** [comment]
Not as fixed as we thought @wrenffxi some people other than the initiating player are still able to reenter before the wait time is up. @Raelious tells me his group cleared boss then everyone left the zone, and we was able to start the same dynamis again right away.

> We killed every single mob in the zone, killed the boss, then I killed all of the 100 coin statues after the boss died. I was the only one in the zone after the boss died. When I left there was no one in the zone and I waited about 2-3 minutes before attempting to re-enter Dynamis-Windurst, and it gave me the option to go inside, proceeded to and it re-spawned all of the mobs again, I killed the first 2 statues and mobs, exited and was able to reenter a third time with the mobs all back up again.

**Comment by wrenffxi** [comment]
Hm.  I'm unable to replicate this.  When I leave the zone then try to reenter, I get the "You cannot enter Dynamis - Windurst for {n} days (Vana'diel time)" message.  @Raelious do you have BETWEEN_2DYNA_WAIT_TIME set to 1 day or greater in settings.lua?  Can you verify that player var dynaWaitxDay is being set when you enter Dynamis zone?

**Comment by TeoTwawki** [comment]
@wrenffxi he's a legion player and I have remote access to their machine. They had it with the default of 1. I also verified they actually are up to date and hand;e changed any of the dynamis code. Some ppl were getting hit with the wait and others were not. Like its only applying for the 1st person to activate the the battlefield or something. Didn't spend more time on it, Legion decided to disable the timer after that since it'd already been busted for months prior to your commit.

**Comment by whasf** [comment]
I don't think this is an issue anymore.
