### ISSUE TITLE
Namas Arrow - Set Enmity Params Not Coded

### ISSUE THREAD

**Issue by nyczducky** [DarkstarProject/darkstar#3519]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30161004_1

**_Server Version_** (type `@revision` in game) ed0d506

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Namas Arrow is generating default hate instead of reduced hate. Upon looking in the namas_arrow.lua, I noticed:

    params.overrideCE = 160;
    params.overrideVE = 480;

I went through to the weaponskill.lua and didn't see these params being used within doRangedWeaponskill() or in battleutils.cpp in TakeWeaponskillDamage().

Following it further down the rabbit hole:

GetEnmityModDamage in enmitycontainer.cpp doesn't make use of the param.

**Comment by teschnei** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills.lua#L885

???

**Comment by teschnei** [comment]
Can you actually confirm in-game whether it is working or not?  Printing your CE/VE values before/after the WS or something?

**Comment by nyczducky** [comment]
Yeah I saw that. Sorry about that. I'll do some prints and confirm once I'm home.

**Comment by Hozu** [comment]
@nyczducky I wrote some lua bindings for getting VE and CE when I redid Atonement a while back to do damage based off of enmity, so it should be fairly simple to check.

**Comment by nyczducky** [comment]
Confirmed working as intended. People are dumb and so am I for not checking. Sorry for calling wolf.
