### ISSUE TITLE
Taurus in Dynamis - Tavnazia spawning in odd spots

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#3526]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
ed0d506

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Fight an eye on third floor that spawns a Taurus. Taurus does not appear with main group. Walks up about 30s-1m later. Depending on which eye, and thus the path the Taurus takes, the Taurus can link with mobs along the way (mobs on second floor?) if you did not clear those out.

**Comment by Hozu** [comment]
Oh I forgot to report this one a while back. It's only a problem if you take the further path into the area, ie. going right past the door that doesn't cause the problem. I made a passive-aggressive "helpful" image detailing it. http://i.imgur.com/OTxUcTv.png

**Comment by gedads** [comment]
hi, i uploaded updated mobspawnpoints mob groups and pools files in neodynamis branch if you want to correct positions
