### ISSUE TITLE
Shattering Stars White Mage unwinnable via lasting 5 minutes

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3530]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

30161004_1
**_Server Version_** (type `@revision` in game) **:**

d72a22f
**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

A server mate tried to beat WHM Maat by lasting 5 mins when engaged.  He says he kept Maat slept, paralyzed,  and slowed during the 10 min fight and ran out of time. He didn't win the fight. If more info is needed let me know.

**Comment by teschnei** [comment]
related:
#3339

**Comment by Fiocitrine** [comment]
should I close this then?

**Comment by teschnei** [comment]
Nah, its easier to see this one via search, I just wanted to point to that
explanation in case anyone wants to try fixing it

**Comment by nyczducky** [comment]
Corrected with #3555
