### ISSUE TITLE
Homepoint teleporting mismatch

### ISSUE THREAD

**Issue by ffxijuggalo** [DarkstarProject/darkstar#3542]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game):
30161103_1

**_Server Version_** (type `@revision` in game):
0cf2fcf66569f11217e49d6dd9a99e7aa50

**_Source Branch_** (master/stable):
master

**_Additional Information_** (Steps to reproduce/Expected behavior):
- Added `Home Point 5` to **Windurst Woods** next to the **Clothcraft guild** as it appears in retail. It registers as a new homepoint properly but registers in the teleport menu as `Home Point 1` in **Misareaux Coast**. If selected from a different homepoint, you're teleported to `Home Point 5` in **Windurst Woods**. 
- Zoning to **Misareaux Coast** and using the homepoint will register as a new homepoint properly but upon examining the teleport menu from a different homepoint, it's registered as `Home Point 1` in **Qufim Island**. If selected, you're teleported to `Home Point 1` in **Misareaux Coast**.
- Zoning to **Qufim Island** and using the homepoint will register as a new homepoint properly but upon examining the teleport menu from a different homepoint, it's registered as `Home Point 1` in **Toraimarai Canal**. If selected, you're teleported to `Home Point 1` in **Qufim Island**.

From what I've gathered from `homepoint.lua` and `npc_list.sql`, there isn't a homepoint yet for **Toraimarai Canal**, which is positioned near the **Full Moon Mountain** zoneline in retail. Coordinates in retail would be `X:-257 Y:23 Z:81` for this homepoint.
So in short, after these homepoints are registered, `Home Point 5` in **Windurst Woods** is actually `Home Point 1` in **Misareaux Coast**. `Home Point 1` in **Misareaux Coast** is actually `Home Point 1` in **Qufim Island**. And `Home Point 1` in **Qufim Island** is actually `Home Point 1` in **Toraimarai Canal** that doesn't exist.

Here's data I have from `npc_list.sql`

**Windurst Woods**:
```
INSERT INTO `npc_list` VALUES (17764540,'HomePoint#5','Home Point #5',128,-43,0,-142,1,40,40,0,0,0,0,3,0x0000330000000000000000000000000000000000,0,null,1);
```

**Misareaux Coast**:
```
INSERT INTO `npc_list` VALUES (16880006,'HomePoint#1','Home Point #1',224,-65,-17.5,563,1,50,50,0,0,0,0,3,0x0000330000000000000000000000000000000000,0,'COP',1);
```

**Qufim Island**:
```
INSERT INTO `npc_list` VALUES (17293821,'HomePoint#1','Home Point #1',64,-212,-21,93,1,50,50,0,0,0,0,3,0x0000330000000000000000000000000000000000,0,null,1);
```

**Toraimarai Canal**:
```
No HomePoint data listed.
```

Here's data I have from `homepoint.lua`
```
homepoints[114] = { 4, 19,       -65,     -17.5, 563,   224, 25, 1000}; -- Misareaux Coast #1  <--- this was already implemented, didn't touch.
homepoints[115] = { 4, 20,       -212,     -21,  93,    64, 126, 500}; -- Qufim Island #1 <---this was already implemented, didn't touch.
-- homepoints[116]  = { 4,  21,       0,      0,       0,   0,  276,  1000}; -- Inner Ra'Kaznar #1    // next to the Sinister Reign NPC and Ra'Kaznar Turris
homepoints[117] = { 4, 22,     -43,      0,    -142, 128, 241,  500}; -- Windurst Woods #5 // next to clothcraft guild  <--- had to manually add this line as it didn't exist.

freeHpTeleGroups[3] = { 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 ,27 ,28, 103, 117}; -- Windurst
```
Also had to create `HomePoint#5.lua` in the `scripts/zones/Windurst_Woods/npcs` folder. Used a copy of `HomePoint#4.lua` as a reference and made these changes to `lines 26 and 46` then saved as `HomePoint#5.lua`:

```
homepointMenu( player, 0x2200, 117);
if (csid == 0x2200) then
```

**Comment by takhlaq** [comment]
you can use three backticks before and after code in markdown to help make your comments more readable (fyi)

**Comment by takhlaq** [comment]
prettified your comment :)
though really this should be a pull request

**Comment by teschnei** [comment]
pull request? isn't he asking for help because they are not lining up?

didn't @Hozu do it originally?

**Comment by takhlaq** [comment]
o ya.. oops
was too busy formatting to even understand what the issue was

**Comment by Hozu** [comment]
I may or may not have made an issue about home points after SE implemented favourites a while back, because that messed up what DSP has - players could teleport to home points that they don't have registered. But I forget. I did not do any code for home points though.

**Comment by ffxijuggalo** [comment]
Closed as this was fixed and implemented.
