### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3547]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
n/a

**_Server Version_** (type `@revision` in game) **:**
0586046fe63eae5e47c5ddeeedc4a17241d0c4d7

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
I don't know where this is from or what the value should be otherwise i'd add it.
luautils::onEventFinish scripts/zones/Uleguerand_Range/npcs/Zebada.lua:65: attempt to perform arithmetic on global 'ZEPHYR_FAN_COOLDOWN' (a nil value)

**Comment by takhlaq** [comment]
@Fiocitrine

**Comment by Djcocha** [comment]
I let Fio know about this in game, the text display from the NPC is all screwy too gives different message everytime, not sure if thats an ID issue or part of the script problem..

**Comment by Fiocitrine** [comment]
It's weird. It displays normally on some of my characters and all weird on others. I can't explain this. Maybe, someone else with more expertise can?

**Comment by takhlaq** [comment]
probably conflicting global var
make sure you reload the zones textids

**Comment by TeoTwawki** [comment]
it was never defined at all, actually.
