### ISSUE TITLE
Orb BCNM failure to check for more than on with same orb

### ISSUE THREAD

**Issue by ffxiphoenix** [DarkstarProject/darkstar#3548]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game):
30161004_1 (also 301611xx_x)

**_Server Version_** (type `@revision` in game):
Unknown

**_Source Branch_** (master/stable):
stable

**_Additional Information_** (Steps to reproduce/Expected behavior):
Set 2 x BCNMs using same orb, only the 1st one is chosen

**Comment by takhlaq** [comment]
known issue, i still need to figure out how retail handles the entry cutscene (best not to expect a fix anytime soon)

**Comment by wrenffxi** [comment]
just a note to tie this issue to the commit in bcnmcrap branch that will fix it https://github.com/DarkstarProject/darkstar/commit/08393c110fb536c28f6ed0891d1bd4c62e28d884

**Comment by TeoTwawki** [comment]
IT MERGE WHEN? WHEN TEAM DSP? /nag

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
