### ISSUE TITLE
DSConnect and DSGame failing to build on Windows (bad encoding)

### ISSUE THREAD

**Issue by la0wai** [DarkstarProject/darkstar#3552]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
n/a

**_Server Version_** (type `@revision` in game) **:**
7a08dadf649f51b98b59adc0388322f5d3f7c684

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Windows 10 Pro x64, VC2015.3. Debug, release, Win32 and x64 all fail building.

I simply followed the instructions on the wiki. Opened the .sln and hit build, no editing of anything.

DSConnect error list:
```
Error	C3861	'do_close': identifier not found	DSConnect-server	C:\dsp\src\common\socket.cpp	203	
Error	C2447	'{': missing function header (old-style formal list?)	DSConnect-server	C:\dsp\src\common\socket.cpp	219	
Error	C3861	'do_close': identifier not found	DSConnect-server	C:\dsp\src\common\socket.cpp	785	
Error	C3861	'do_close': identifier not found	DSConnect-server	C:\dsp\src\common\socket.cpp	961	
```

DSGame error list:
```
Error	C3861	'do_close': identifier not found	DSGame-server	C:\dsp\src\common\socket.cpp	203	
Error	C2447	'{': missing function header (old-style formal list?)	DSGame-server	C:\dsp\src\common\socket.cpp	219	
Error	C3861	'do_close': identifier not found	DSGame-server	C:\dsp\src\common\socket.cpp	1226	
Error	C1075	the left brace '{' was unmatched at the end of the file	DSGame-server	C:\dsp\src\map\packets\inventory_item.cpp	36	
```

**Comment by teschnei** [comment]
it's building locally for me and on appveyor - can you try getting the source again?  did you use git bash or tortoise git or something else to get the source?

**Comment by la0wai** [comment]
The first time round I downloaded the zip right from the github repo. I just tried again using the windows desktop Github program and got the same errors. My VS2015 isn't set up in any special way or anything so I'm stumped.

**Comment by teschnei** [comment]
some kind of encoding issue? do_close should have a declaration in socket.h (line 159), is it there?
you did install visual c++ when you installed visual studio, right?

**Comment by la0wai** [comment]
Yeah VC++ is all set up.
I didn't think it was related but when building I get lots and lots of errors that talk about encoding, yes.
Warning	C4819	The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss	DSConnect-server	y:\github projects\darkstar\src\common\socket.cpp	1	

When I open socket.h I get an error box come up:
http://i.imgur.com/EH4cSpo.png

Line 158 says //渼, 鈞・鏆・ ・・void do_close(int32 fd); and then 159 is blank

**Comment by teschnei** [comment]
oh, yeah there is supposed to be a line break after that comment, so it's definitely encoding!

I don't think there's too many badly encoded comments, so you might be able to just remove them all if you have time, I am not sure what the best way to fix it on your end is, to be honest.

Something we should probably fix in the future too

**Comment by la0wai** [comment]
Right, I deleted all the comments and re-saved the offending files as Unicode. Now the server compiles without any problems. Thanks a lot for your help. 

The files that had the problem were:
- src\common\socket.cpp
- src\common\socket.h
- src\map\items\item_fish.h
- src\map\packets\inventory_item.cpp

I'll leave this open in case you want to refer back to this list some time in the future, and if not you can close it. :)
