### ISSUE TITLE
Black Bread GP numbers are off. Also won't take right amount.

### ISSUE THREAD

**Issue by FrankWHansen** [DarkstarProject/darkstar#3554]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
7a08dadf649f51b98b59adc0388322f5d3f7c684

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Guild points, cooking guild, specific recipe:

According to wiki, you're supposed to be able to trade 139 black breads for a total of 6240 GP.
I traded 8 stacks (96 singles) and got 2080 GP. Couldn't trade again. Also, reward numbers seem off.

**Comment by FrankWHansen** [comment]
Seems there's a discrepancy between wiki and server for more than this GP item. Today, I can do ram mantles for 13440 GP according to wiki, while server says 4480 GP is the limit.

I assume retail version has recently lifted the amount of GP you can get per day. I'll leave this issue open since it's not up to me how to resolve it (or whether to ignore it).

**Comment by zynjec** [comment]
Fixed to best known values in https://github.com/DarkstarProject/darkstar/pull/5586
