### ISSUE TITLE
Current exp formula emulates neither modern nor era retail

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#3558]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **not a client issue**

**_Server Version_** (type `@revision` in game) **f8175463415d4964d3deb2492d73a1bd03b548c6**

**_Source Branch_** (master/stable) **master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

I'd like to draw attention to line 3213 in charutils.cpp:

                    permonstercap = ((PMember->PParty != nullptr && pcinzone > 1) ? 1.35f : 1.15f);

It then proceeds to multiply the era-correct hard caps for each level range by 1.35 or 1.15 based on conditions that I have not been able to pinpoint. What is this permonstercap and why is it interfering with otherwise perfectly functional exp hard caps?

**Comment by Hozu** [comment]
I think the condition is if the player is in a party or not, and the other party members are in the zone - 1.35 if they are, 1.15 if not.

**Comment by Deadwing888** [comment]
That does appear to be what that line is doing yes.

Why it is doing it is another question entirely.
