### ISSUE TITLE
Alastor Antlion "burrows" when going unclaimed

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#3562]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
abb184b

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Per this youtube video, Alastor Antlion should not be burrowing when going unclaimed:
https://youtu.be/-hAyx56fVnE?t=2m6s

Related to #3181, but instead of burrowing > despawning, mob should at least be roaming back to its spawn point instead of burrowing.

Mixin used by Alastor script:
scripts/mixins/families/antlion_ambush.lua

This has a disengage handler which "burrows" the mob, which is my guess is the culprit.

**Comment by Hozu** [comment]
I wasn't aware that it doesn't go underground when it goes unclaimed when I fixed the antlions via the mixin. Sorry about that.

**Comment by xipies** [comment]
Hey, np, Hozu.

I am currently exploring splitting out a separate "antlion nm ambush" mixin that does not have the disengage handler. Will try to get that tested and committed, if it looks like it is closer to retail behavior, in the next few days.

**Comment by xipies** [comment]
It looks like roamflag for Alastor also needs to be changed. Currently set to ROAMFLAG_AMBUSH.

**Comment by Hozu** [comment]
On spawn it ambushes the player, so it does need to have that roamflag. I think. Unless you can reproduce the behaviours that are dictated by that roamflag by script.

**Comment by xipies** [comment]
The roamflag I think should not be changed after all.

I successfully got the mob to not go "untargetable" on unclaim by not having a disengaged handler in antlion_ambush.lua. However, I kept triggering the mob either burrowing (visibly) or going invisible, but still targetable. I could trigger this by running sufficiently far enough away (with @runspeed). It would happen both when claimed and also unclaimed.

I am currently stuck on how to fix this (burrow/invisible). I do not know what could be causing it, since I even tried commenting out all the handlers in antlion_ambush.lua. Could it even be something that is part of the model information? Animationsub? I do not know.

**Comment by Hozu** [comment]
Looks like this is causing the issues: https://github.com/DarkstarProject/darkstar/blob/6927d516e5cc48c58513e45950668a293870d0e4/src/map/ai/controllers/mob_controller.cpp#L778

I think I forgot to remove that when I redid their ambush behaviour? You may be able to remove that entire check and the regular ambushing antlions should continue to function properly.

**Comment by xipies** [comment]
Awesome. I will look into it as soon as I get some more time.
