### ISSUE TITLE
Bad Treasure Coffers in VeLugannon Palace

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3566]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
eaeff3a81e309499a24e4b728b65cc58afbdd594

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

[04/Dec] [11:09:33][Error] luautils::onTrade: scripts/zones/VeLugannon_Palace/npcs/Treasure_Coffer.lua:68: attempt to concatenate global 'zone' (a nil value)

**Comment by Brierre** [comment]
Does this have to do with the #3611 commit made 12/30?  421 chest/coffer npcIDs were fixed, including those in Ve'Lugannon.

**Comment by ibm2431** [comment]
That server version is from before the November and December updates, so assuming they're running a corresponding client version (which it appears so), it shouldn't be related.

**Comment by Brierre** [comment]
Oh darn.  Well thought it was worth a try :)

**Comment by R3P0FFXI** [comment]
@ibm2431 at the time this was the October version and it was the latest DSP version. Someone will have  to goto Ve'Lugannon and see if the issue still occurs
