### ISSUE TITLE
Ghettofield crash

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3567]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
N/A

**_Server Version_** (type `@revision` in game) **:**
N/A

**_Source Branch_** (master/stable) **:**
master + ghettofield mod

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
https://1drv.ms/u/s!AvyTIXTmkiRwlwgjmuDRkZDxSx0z

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/17a17ff38c5d8791889e383121f843b3b72bf541
