### ISSUE TITLE
great axe weaponskills have incorrect stat modifier

### ISSUE THREAD

**Issue by wadski** [DarkstarProject/darkstar#3568]
in the settings/globals/weaponskills .lua files both raging axe and metatron torment have the incorrect str modifiers. 

raging rush is supposed to be 50%  the param is .35

params.str_wsc = 0.35; params.dex_wsc = 0.0; params.vit_wsc = 0.0; params.agi_wsc = 0.0; params.int_wsc = 0.0; params.mnd_wsc = 0.0; params.chr_wsc = 0.0;

metatron is supposed to be 80% the param is only .6 

str_wsc = 0.6; params.dex_wsc = 0.0; params.vit_wsc = 0.0; params.agi_wsc = 0.0; params.int_wsc = 0.0; params.mnd_wsc = 0.0; params.chr_wsc = 0.0;

**Comment by teschnei** [comment]
They are both correct for their era.  You are comparing the old modifiers with the post-seekers values.  If you want the post-seekers modifiers, then you can turn on USE_ADOULIN_WEAPON_SKILL_CHANGES in settings.lua
