### ISSUE TITLE
Need a server update for the newest Client

### ISSUE THREAD

**Issue by haywoodspartan** [DarkstarProject/darkstar#3570]
**_I have: Tried to login but the client has version later than the server. If there was some code I could change that would be greatful.**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:301611xx_x**

**_Server Version_** (type `@revision` in game) **:301610xx_x**

**_Source Branch_** (master/stable) **: Master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by helixhamin** [comment]
Please check this topic in the forums: https://forums.dspt.info/viewtopic.php?f=14&t=3132
