### ISSUE TITLE
Ghettofield crash

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3571]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
N/A

**_Server Version_** (type `@revision` in game) **:**
N/A

**_Source Branch_** (master/stable) **:**
Stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Crash when someone was leaving Limbus via teleport/warp
https://1drv.ms/u/s!AvyTIXTmkiRwlw0uZ1V_mxGbqfZg

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/9632090cb30ab26b7bd88a1aece2cc6b61348427
