### ISSUE TITLE
Dynamis crash - ghettofield

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3577]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
n/a

**_Server Version_** (type `@revision` in game) **:**
eaeff3a81e309499a24e4b728b65cc58afbdd594 with ghettofield mod

**_Source Branch_** (master/stable) **:**
stable + ghettofield

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Dump: https://1drv.ms/u/s!AvyTIXTmkiRwlxSXQRnCcNGWrmXV
Explanation:
We were in dynamis xarc, time ran out, all seemed fine then it just went down.
I shouldnt say "all" seemed fine I guess... there is stones that pop in there after you kill other certain stones, when time ran out and mobs depsawned it triggered those stones to spawn so we tried attacking one... but im not sure if the crash started when we killed it my computer was disconnecting from internet at the time...

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/3e219405b3d22773fcb4cef50156417177aac0e6
