### ISSUE TITLE
Oldschool crash in metalworks

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3581]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Crash in Metalworks, debug hit. I don't know how to look up what LUA file it is.
https://1drv.ms/u/s!AvyTIXTmkiRwlxs_94ZNUqdMA95G

**Comment by takhlaq** [comment]
closing cause old, reopen if still happens
