### ISSUE TITLE
Various Emotes are Crashing Clients

### ISSUE THREAD

**Issue by nyczducky** [DarkstarProject/darkstar#3589]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30161103_1

**_Server Version_** (type `@revision` in game) 7186236

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior)
Some emotes are crashing clients. Sometimes it's just the targeted player. Othertimes, it's to everyone.

/wave and /laugh are the usual culprits.

**Comment by wrenffxi** [comment]
Anyone with retail access able to capture the incoming packet when you ...

/bow {to someone / to nobody} {with no weapons / with a one-handed weapon / while dual wielding}

Would like to compare this to the one created by DSP.

Load [PacketViewer](https://github.com/z16/Addons/tree/master/PacketViewer) and do: **//pv l chatlog i 0x05A**  Then when you emote it'll show the packet in your chatlog.

**Comment by nyczducky** [comment]
Logged some packets but I couldn't reproduce the crashes reliably. The crashes did happen but after like... 100 emotes.

Players have noticed that doing emotes in towns are safe while doing this in areas outside of town causes more crashes. I don't know how that makes sense but just putting that observation here.

**Comment by wrenffxi** [comment]
You logged incoming 0x05A packets from retail?  If so can you post a few?  Want to either confirm or eliminate outdated packet fields as a source for this bug.  Thanks!

**Comment by nyczducky** [comment]
I just resubbed. I'll have it shortly.

**Comment by nyczducky** [comment]
`Packet
        |  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F      | 0123456789ABCDEF
    -----------------------------------------------------  ----------------------
      0 | 5A 1C 96 05 24 0C 02 00 B8 CF 00 00 56 05 89 04    0 | Z...$.......V...
      1 | 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    1 | ................
      2 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2 | ................
      3 | 00 00 00 00 00 00 00 00 -- -- -- -- -- -- -- --    3 | ........--------

Packet
        |  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F      | 0123456789ABCDEF
    -----------------------------------------------------  ----------------------
      0 | 5A 1C A9 05 24 0C 02 00 00 00 00 00 56 05 00 00    0 | Z...$.......V...
      1 | 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    1 | ................
      2 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2 | ................
      3 | 00 00 00 00 00 00 00 00 -- -- -- -- -- -- -- --    3 | ........--------

Packet
        |  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F      | 0123456789ABCDEF
    -----------------------------------------------------  ----------------------
      0 | 5A 1C C7 05 24 0C 02 00 B8 CF 00 00 56 05 89 04    0 | Z...$.......V...
      1 | 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    1 | ................
      2 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2 | ................
      3 | 00 00 00 00 00 00 00 00 -- -- -- -- -- -- -- --    3 | ........--------

Packet
        |  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F      | 0123456789ABCDEF
    -----------------------------------------------------  ----------------------
      0 | 5A 1C CE 05 24 0C 02 00 00 00 00 00 56 05 00 00    0 | Z...$.......V...
      1 | 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    1 | ................
      2 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2 | ................
      3 | 00 00 00 00 00 00 00 00 -- -- -- -- -- -- -- --    3 | ........--------

`

**Comment by nyczducky** [comment]
http://pastebin.com/x8J6zqx2

**Comment by wrenffxi** [comment]
Super helpful!  Do you remember which weapon you had equipped?

**Comment by nyczducky** [comment]
Onion Knife.

**Comment by wrenffxi** [comment]
Thanks again.  One more request: can you capture a retail 0x05A for ...

doing /hurray with a weapon equipped
doing /jobemote {some job}  (not sure if this is available to new players on retail)

No rush on this at all.  About to crash for the night.  Thanks very much for the help.

**Comment by nyczducky** [comment]
1) Hurray with onion knife
2) Hurray with no weapon
3) THF Job Emote

http://pastebin.com/pbVdi16p

**Comment by wrenffxi** [comment]
Perfect!  Had it right.  PR incoming.  Thanks for all your help. <3

**Comment by nyczducky** [comment]
No. Thank you. Been driving me nuts and would have taken me longer to implement lol.
