### ISSUE TITLE
Doom Effect not working

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3599]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**
718623696ae4431bdbb9613bedf2d3c75c56a7de

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Effect_Doom is not working, when a mob uses a move that gives the effect_doom effect the timer will count down to 2 then stop every time it will never count down to 0 and kill the player or give the message "[Player] narrowly escapes impending doom" will be displayed in the chat log.

**Comment by TeoTwawki** [comment]
Just as he posted this, I noticed the tick rate seems off . `@addeffect 15 10 30` which should be your standard 10 ticks of doom. only does 8 ticks.  `@addeffect 15 10 35` will result in a death. 5 whole seconds off.

**Comment by TeoTwawki** [comment]
Def not specific to just doom
![21 tick regen should be 25](https://cloud.githubusercontent.com/assets/6871475/21469396/33ecd918-ca18-11e6-82c4-a01efb5aa294.png)

**Comment by teschnei** [comment]
Looks like it's skipping a server tick every effect tick, maybe (3400ms
instead of 3000). Shouldn't be too hard to investigate after Christmas

**Comment by TeoTwawki** [comment]
> Shouldn't be too hard to investigate after Christmas

Just posting to remind.

**Comment by TeoTwawki** [comment]
I suspect the timing thing is causing some of the other recent bugs too
