### ISSUE TITLE
Delivery box errors

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3603]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161206_3

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/c31bd6b31708695f77d04eb089fa0a1dfe24ae93

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

[27/Dec] [15:38:32][Error] Failed to return item id 4868 stack 0 to char...
[27/Dec] [15:40:21][Error] Failed to return item id 15271 stack 0 to char...
[27/Dec] [15:42:29][Error] Could not finalize receive transaction. PlayerID: 28330 Action: 0x0A[27/Dec]

I think people overloaded their delivery boxes from abusing the infinite AH slot bug

**Comment by Djcocha** [comment]
#3350 and #3425 not sure if related. Also, on oldschool when players who are not around anymore have sold a ton of items (no idea what the limit is) Whasf needs to manually clear their deliv box or something for any more items to be buyable from them on AH... (This has not happened in a long time that I am aware of so he might have some sort of fix in place...)

**Comment by whasf** [comment]
for oldschool this may be due to a missing SQL trigger

**Comment by maxtherabbit** [comment]
R3P0 is this only an issue when using the AH auto return?

**Comment by maxtherabbit** [comment]
"Could not finalize receive transaction." can be triggered by a player simply trying to remove an item from his inbox with a full inventory

I'm looking into the ah return errors (these are canceled not expired sales btw)
