### ISSUE TITLE
Lakeside Minuet Quest Issue...

### ISSUE THREAD

**Issue by ffxijuggalo** [DarkstarProject/darkstar#3615]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30161206_3

**_Server Version_** (type `@revision` in game) **:** 1362c28b17a9fbe39a66b30c22e34df7565934c7

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Completed Lakeside Minuet (DNC unlock) quest from start to finish without any issues. Was told in irc chat to submit a bug report because of this anomaly. Thanks for your time and humor.

**Comment by TeoTwawki** [comment]
How did this occur? Halver's sleeping on the job!

**Comment by ffxijuggalo** [comment]
Maybe it's the secret crush I have for Laila.
