### ISSUE TITLE
Nokkhi Jinjahl has wrong textids in Bastok.

### ISSUE THREAD

**Issue by Heepster03** [DarkstarProject/darkstar#3629]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161206_3

**_Server Version_** (type `@revision` in game) **:**
[c31bd6b](https://github.com/DarkstarProject/darkstar/commit/c31bd6b31708695f77d04eb089fa0a1dfe24ae93)

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Nokkhi Jinjahl has a jumble of textids going on while trading items for quivering in Bastok. In a screenshot that I'm including, each of the red arrows is a trade and where it should says that I obtained a quiver, it didn't. However, I did actually receive a quiver where each red arrow is indicated.

![halkuras_2017 01 05_193508_ink_li](https://cloud.githubusercontent.com/assets/8421725/21705079/3a0c7faa-d383-11e6-8351-d151e183f229.jpg)

**Comment by ibm2431** [comment]
To save people some time: [Port_Bastok/Nokkhi_Jinjahl](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Port_Bastok/npcs/Nokkhi_Jinjahl.lua)

Everything is using ITEM_OBTAINED, which judging by the provided screenshot, seems to be correct... sometimes. Whatever is going on doesn't appear to be a simple text ID issue, but something wonky with messageSpecial (or an underlying function).

**Comment by teschnei** [comment]
the script doesn't require bastoks text IDs... how is it supposed to use
them if it doesn't know them?

**Comment by TeoTwawki** [comment]
Missing require means text id is nil (because textIDs are just global variables sitting in the required file).
And nil var being passed into messageSpecial means you wind up with the client spitting out the default/first string in the zone.

c1b5919305bd8dd3b359e3c6ceea26ba23eb60c1

**Comment by TeoTwawki** [comment]
~~default/first string in the zone~~ or whatever the crap is at the number of whatever previous pile of textIDs it had loaded were

**Comment by teschnei** [comment]
It's not that it's nil here, but that ITEM_OBTAINED is going to be the
value of whatever zone last loaded it's text IDs. Which is why you get
different things randomly

**Comment by TeoTwawki** [comment]
You replied right as I editted lol
