### ISSUE TITLE
Maat Broken Again

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3633]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161206_3

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/62fa64137b353ad46f7b80cea3a8541759313448

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

I dunno what this fatal error is but seems kinda serious

[08/Jan] [16:44:54][LUA Script] UPDATE csid 32000 option 255
[08/Jan] [16:44:54][Error] Mobutils::CalculateStats Mob (Maat, 17367077, 335) ha no detection methods!
[08/Jan] [16:44:54][Fatal Error] Sql_NextRow: SQL_ERROR

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/sql/mob_family_system.sql#L403

Give the Maat family a detection method, otherwise it won't be able to engage because it doesn't have a way to track the target.

**Comment by wrenffxi** [comment]
Paging @Brierre . Could add this to open PR #3618.

**Comment by TeoTwawki** [comment]
The fatal error is unrelated to the detection: tons of mobs were missing detection, none of them generated a fatal error message. So multiple bugs one report basically. Probably related to that BCNM entry.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/pull/3618

**Comment by TeoTwawki** [comment]
Also Kj fixed the nextrow thing, which I forgot about
