### ISSUE TITLE
Build error LNK1117: Syntax error in option 'LTCG:incremental' when building on Release Win32 in VS2015 Community

### ISSUE THREAD

**Issue by la0wai** [DarkstarProject/darkstar#3647]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
n/a

**_Server Version_** (type `@revision` in game) **:**
f00420430f39fcb6b21224070882738b62454e6c

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Unable to build DSSearch, DSGame or DSConnect servers on VS2015 Community from a fresh clone, completely untouched.
Results in error LNK1117: Syntax error in option 'LTCG:incremental'.

**Comment by la0wai** [comment]
To fix: 

- Right click DSConnect-server in VS Solution Explorer, go to Properties. 
- Set Configuration to 'Release' and Platform to Win32
- In the left sidebar open Linker, then All Options
- Search for the option "Link Time Code Generation"
- Change it from "Use Fast Link Time Code Generation (/LTCG:incremental)" to "Use Link Time Code Generation (/LTCG)"
- Click OK
-Do the same for DSGame-server and DSSearch-server

Not sure what caused this specific error but it seemed to be specific to me. My Windows 10 is set to use Japanese (Japan) locale for non-unicode programs, so I speculate it's probably something to do with this.

demo made me post this issue. he threatened me with kpop

**Comment by teschnei** [comment]
It's already on LTCG by default, and there isn't an option for "fast link time code generation" (and I can't even find anything on msdn about it).  I don't think there's anything we can do about it, since it seems to be specific to your installation.

**Comment by takhlaq** [comment]
https://msdn.microsoft.com/en-us/library/xbf3tbeh.aspx?f=255&MSPPError=-2147217396
first thing listed is INCREMENTAL

**Comment by teschnei** [comment]
msdn defaulted to VS2010, durr

**Comment by teschnei** [comment]
our vcxproj already specifies LCTG, actually (WholeProgramOptimization tag).  I don't think we can do anything about this, and it's something VS is doing

**Comment by takhlaq** [comment]
yeah, had him make the issue in case anyone else gets it in future (not that anyone ever searches before asking)

**Comment by la0wai** [comment]
https://www.diffchecker.com/FyDTQTDh
DSSearch-server.vcxproj before and after the setting is changed in VS2015 (before is taken from yet another fresh clone)
Can one of you guys confirm the difference? If I submit a PR with the option changed by default it'll mean the issue won't exist if anyone else happens to be running with the same setup I'm on (though I literally haven't changed a thing in my VS2015 settings, I even reset the settings midway through trying to figure out the problem lol)

**Comment by takhlaq** [comment]
yeah sure @teschnei will look at it

**Comment by teschnei** [comment]
do a pull request, i'll switch to it and see what my VS does
