### ISSUE TITLE
MAAT fight very difficult to win with BLM, possibly other jobs, 75 cap server

### ISSUE THREAD

**Issue by LegacyFFXI** [DarkstarProject/darkstar#3648]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30161206_3

**_Server Version_** (type `@revision` in game) 7de3ae2

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior) 
Seems MAAT has too much HP? not sure if this is across the board but when fighting him on BLM at level 70 this is easily apparent as in retail the win was to do 2 x AM1 and then a ga3.
Flare - 886
Freeze - 902
Waterga III - 895
Took him to < 30% but not quite enough for the win and this is over 2600 damage, as far as i can see from the tables he should be getting initialised with a base value of 2300 and a modifier of 0.9?
Could this be related to the var in map_darkstar.conf:
nm_hp_multiplier:     1.5
If so, is this intended behavior for the maat mob to be effected by this multiplier?

**Comment by takhlaq** [comment]
does he check as impossible to gauge? if so then remove from nm spawn points table

**Comment by TeoTwawki** [comment]
whether something count as an NM is determined by a  flag, not nm spawn point table. If its flagged /check will report impossible to gauge, and then yes being effected by things that effect NMs is intended.

Ran into a a similar report awhile back where a server had beefed up all NM's base stats not realizing that BCNM monsters count too. Settings like that are for people who want to make the entire game harder.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/blob/0889d2359c897166a37f81234ae5aa6ef03d833e/src/map/entities/mobentity.h#L74

**Comment by LegacyFFXI** [comment]
got it, been wracking my brains on this one for a while, thanks!
