### ISSUE TITLE
Unequipping armor with a 'cannot equip' attribute causes the removed slot to be invisible

### ISSUE THREAD

**Issue by ThisIsPatrick** [DarkstarProject/darkstar#3652]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30161227_1

**_Server Version_** (type `@revision` in game) **:** 369d6e8

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Equip a piece of armor with a 'cannot equip handgear' attribute then unequip it.
After unequipping the character's hand model will be missing. The model will reappear once hand armor is changed again.

This happens with all armor that has 'cannot equip' on it.

The issue is due to this line of code in charutils.cpp UnequipItem :

> switch (((CItemArmor*)PItem)->getRemoveSlotId())
            {
                case SLOT_HEAD:  PChar->look.head = 0; break;
                case SLOT_HANDS: PChar->look.hands = 0; break;
                case SLOT_FEET:  PChar->look.feet = 0; break;
            }

Since the RemoveSlotId is a bit as of 0922498, the case switches are never hit.

**Comment by wrenffxi** [comment]
Possibly related: all the pants that should prevent feet from being equipped (for example novennial boots or Hume Shorts, do not remove footgear, and will clip through the naked foot model if equipped while naked.

**Comment by GMYasiinEra** [comment]
tested cosy bottom.  removes ammo slot as well

**Comment by maxtherabbit** [comment]
just tested this on current rev, could not duplicate with vermillion cloak

kj didn't change remove slot to be a bit, it's still a 16bit unsigned int, he just made it so individual items could have multiple remove slots by using bitwise logic

I don't think the problem is with the core code, guessing certain items have incorrect rslot values in the database

**Comment by maxtherabbit** [comment]
I'm fixing this - @GMYasiinEra if there are items that are removing ammo slot incorrectly, they are flagged wrong in the database, not related to this issue
