### ISSUE TITLE
Levels of aftermath "appear" to stack, no overwrites

### ISSUE THREAD

**Issue by ffxijuggalo** [DarkstarProject/darkstar#3665]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30161227_1

**_Server Version_** (type `@revision` in game) **:** 7b4b683f8c429c1595f28e3d95566b7bce3b2b0f

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** After using mandalic stab to check and see if the aftermath effect would activate, I noticed that the levels don't overwrite each other as the level increases. Screenshot included showing all 3 levels of aftermath active:
![shaggy_2017 01 24_083529](https://cloud.githubusercontent.com/assets/22580624/22251659/396b25a0-e211-11e6-99da-9048661c7b4b.png)

Another screenshot from the chatlog showing them wearing off individually:
![shaggy_2017 01 24_084458](https://cloud.githubusercontent.com/assets/22580624/22251721/6e20e7ee-e211-11e6-96e4-aeefa4568f2f.png)

**Comment by zynjec** [comment]
This was fixed, closing.
