### ISSUE TITLE
Pup - Automation will not skillup

### ISSUE THREAD

**Issue by dwn134** [DarkstarProject/darkstar#3668]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
Unknown

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Leveled to 20 so far and only can get Auto to melee attack but does not skillup
also when in battle if you check the equip screen the auto elements are changing from 0 to 11 randomly

**Comment by helixhamin** [comment]
Automation is still broke. One reason most servers disable the job.

**Comment by dwn134** [comment]
ok i was looking at alot of the code and thought i could be working since there was so much of it. And saw on the forum a few servers had a somewhat functioning. Maybe they added the skill in manually?
