### ISSUE TITLE
FUBAR'd NPCs are still a thing after last updates, unfortunately.

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3669]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
848453a4f8b5bddd6b9b937225002b50a841ea48

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

I delayed reporting till after I had finished my recent totally unrelated to this bug work in that sql table (it wasn't me!) since I am not fixing these, I'm making it known so anyone else who wants to can. There may possibly be cookie related bribery.\*

**Comment by GMYasiinEra** [comment]
I noticed this myself after we updated our server last week, Did a complete pull 2 days ago on my testserver only leaving out char tables  and its fine.
http://imgur.com/a/BKo9K

**Comment by nyczducky** [comment]
Assuming that it's all zones (some more than others)?  I'll spend some time with IBM's plugin running around once I get myself some movement speed boots.

**Comment by nyczducky** [comment]
I can run around gathering the information but it would be nice if someone could do the queries lol.

**Comment by TeoTwawki** [comment]
I haven't looked thoroughly but I am betting its a handful of spots where some data from 2 diff rows got mangled together from moogle movings. Notice the Artisan Moogle is an NPC we already had at the correct spot, but his pos is now on top the other npc. The magian moogle targeted is a csnpc, as the other magian moogles are already up and in their correct pos so its not one of them.

**Comment by ffxijuggalo** [comment]
Adding this in here for anyone wanting to know what DSGame-server thinks about the latest commits.
[Serverlog.txt](https://github.com/DarkstarProject/darkstar/files/731780/Serverlog.txt)

**Comment by ibm2431** [comment]
Do you have IDs for those two Magian/Artisan Moogles? I don't have access to my DSP computer at the moment (so can't just launch server), but looking at the raw SQL list, I'm having a hard time finding NPCs with coordinates which overlap Fabien or Vincent.

**Comment by TeoTwawki** [comment]
Pardon me one moment..

@LegionDark -_WHACK_- 
Hey, wtf is this
```sql

REPLACE INTO `npc_list` VALUES (17772784,'Fabien','Fabien',191,2.282,0.001,-65.316,29,40,40,0,0,0,0,3,0x0100070100100421c930b9400251006000700000,0,NULL,0);
REPLACE INTO `npc_list` VALUES (17772785,'Vincent','Vincent',190,4.043,0.001,-65.351,22,40,40,0,0,0,0,3,0x01000b0100100421c930b9400251006000700000,32,NULL,0);
```
stop that stuff, you don't even have a working script on those dudes :rage2: 💢 

Ahem, now that that is out of the way...

I chose poor examples for the screenshot. Some **is** still off around them though.
```sql
INSERT INTO `npc_list` VALUES (17772786,'unk','     ',0,0.000,0.000,0.000,0,40,40,0,0,0,2,2051,0x0000340000000000000000000000000000000000,0,NULL,1);
INSERT INTO `npc_list` VALUES (17772787,'csnpc','     ',0,0.000,0.000,0.000,0,40,40,0,0,0,6,27,0x0100000005100520053005400050006000700000,32,NULL,1);
INSERT INTO `npc_list` VALUES (17772788,'npc','Fabien',191,2.282,0.001,-65.316,29,40,40,0,0,0,0,3,0x0100070100100421C930B9400251006000700000,0,NULL,1);
INSERT INTO `npc_list` VALUES (17772789,'npc','Vincent',190,4.043,0.001,-65.351,22,40,40,0,0,0,0,3,0x01000B0100100421C930B9400251006000700000,32,'ABYSSEA',1);
INSERT INTO `npc_list` VALUES (17772790,'npc','Voidwatch Purveyor',192,9.000,0.001,-80.500,16,40,40,0,0,0,0,3,0x01000C01141019200C3002400250006000700000,0,'ABYSSEA',1);
INSERT INTO `npc_list` VALUES (17772791,'unk','     ',241,0.000,0.000,0.000,0,40,40,0,0,0,2,2051,0x0000340000000000000000000000000000000000,0,NULL,1);
INSERT INTO `npc_list` VALUES (17772792,'unk','     ',0,0.000,0.000,0.000,0,40,40,0,0,0,2,2051,0x0000340000000000000000000000000000000000,0,NULL,1);
INSERT INTO `npc_list` VALUES (17772793,'unk','     ',0,0.000,0.000,0.000,0,40,40,0,0,0,2,2051,0x0000340000000000000000000000000000000000,0,NULL,1);
INSERT INTO `npc_list` VALUES (17772794,'unk','???',0,0.000,0.000,0.000,0,40,40,0,0,0,2,2051,0x0000340000000000000000000000000000000000,0,NULL,1);
INSERT INTO `npc_list` VALUES (17772795,'npc','Anastase',34,-36.977,0.001,-38.532,1,40,40,0,0,0,0,27,0x01000E039510262002303A403A50116200700000,0,NULL,1);
```
The name columns don't match. They should.
And a few other places. Side note: I accidently cause Ryftworn Pyxis to start popped when I moved things to using the sql column, I can fix that soon. They are supposed to be despawned till a script tell's to pop and I forgot to make sure they all has status set to 2.

**Comment by ibm2431** [comment]
Checked the file history, [they've apparently been like that for at least two years](https://github.com/DarkstarProject/darkstar/blob/53408535871907166cea61e95c19b1649301f4e0/sql/npc_list.sql). So it wasn't me! I'm innocent! :sweat_smile:

My guess is they've always been like that and were never given scripts. They could probably be given proper name values without a second thought (ie: not indicative of problems more sinister).

**Comment by TeoTwawki** [comment]
I'm now sifting through *somebodies* custom *mess* and then making them *recheck* **all the things.** before I post any new examples. Sorry about that :grimacing:

###### its was legion, prolly loki
#####  whoa didja see that bus? came outa *nowhere!*

**Comment by nyczducky** [comment]
I'll run through the zone for retail confirmation. Just let me know which.

**Comment by TeoTwawki** [comment]
I made some corrections a few days ago  and I'm working on the last corrections now so closing this. It's at least 99% entirely stuff thats been screwed up for 6 months+ and less of it than I originally thought I would find. If anyone does the client version update stuff (SE is on 301702014_1 now) before I'm done it'll be ok and won't trip me up much, so am closing this issue.

**Comment by ibm2431** [comment]
Just to state, the 301702014_1 is another update from hell. SE removed a blank NPC from almost every zone, and the batch tool is doing its usual cascading "screw-up-all-later-IDs-with-the-same-name" thing. I'm not going through all zones by hand again, so there's a zero percent chance I'm doing this client update unless I rework the tool first.

**Comment by TeoTwawki** [comment]
Maybe if we wind up skipping an update, the next one will put a new blank back in again. 

Coz watch we do the work and get updated and then its all wrekt in next update again anyway.

**Comment by ibm2431** [comment]
Yeah, but they'd probably screw it up by adding another Moogle and shifting all the real NPCs by one; we'd have to actually fix that one. 😉 

But the tool needs retooling. This is going to be a problem any time SE adds/removes a blank or a Moogle. In cases of removal, it pushes the (now removed) blank/Moogle to the next available spot, and starts shoving all later Bloogles back by that amount. In cases of addition, Bloogles which occur later in the zone will be moved up to the newly available ID (which is in POL, but we don't have in the NPC list), and all Bloogles after that will cascading-leapfrog up slots.

I'm still thinking about how this can be resolved without falling into traps. "Locking" Bloogles with no information to the contrary was my first thought. This would prevent the random single Bloogles among the named NPCs from leaving their station, but it might pose a problem with Bloogles happening in succession if one gets removed and the others in the block actually did shift back.

**Comment by nyczducky** [comment]
@ibm2431 I'll run through the zones one at a time. I'll hop on IRC later and message you. Least I could do to speed this up if it helps.

**Comment by TeoTwawki** [comment]
![mog of war](https://cloud.githubusercontent.com/assets/6871475/22854309/893b773e-f039-11e6-9089-f664df983e57.jpg)
