### ISSUE TITLE
Latest commits messed up some stuff

### ISSUE THREAD

**Issue by ffxijuggalo** [DarkstarProject/darkstar#3671]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30161227_1

**_Server Version_** (type `@revision` in game) **:** 9135fbaa8c120a616c629e1013a8f0fa9a4b9dfa

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Too many different errors to list after pulling the latest commits so i copied/pasted into a text file. Had to hard reset my playable branch because of it.
[Serverlog.txt](https://github.com/DarkstarProject/darkstar/files/731808/Serverlog.txt)

**Comment by TeoTwawki** [comment]
```[00:51:42][1;35m[SQL][0m DB error - Unknown column 'spell_list.content_tag' in 'field list'```
update your database.

**Comment by ffxijuggalo** [comment]
brain not functioning properly at 3am lol
was my error, all good now and closing this
