### ISSUE TITLE
Level gap not modifiying exp correctly when low lv parties with high level

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3672]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/9135fbaa8c120a616c629e1013a8f0fa9a4b9dfa

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Retail does not allow for this type of powerleveling with a 60+ level gap in the same party.  

https://www.bg-wiki.com/bg/Experience_Points#Calculating_Experience_Points_earned
> The effect of the modifier is to penalize grossly underlevelled players which join a party.
level_modifier is dependent on the player's level (plvl) and the player or pet level used to calculate base above (blvl). If blvl > plvl + 7 or blvl > 50, then level_modifier = plvl / blvl. Otherwise, level_modifier = TNL(plvl) / TNL(blvl), where TNL(x) is the experience points needed to obtain the next level at level x. For example, if the highest party member is 20 and the player is 18, level_modifier = 4200 / 4600

**Comment by TeoTwawki** [comment]
I tested in game, and there ***is*** a penalty being applied, its just not cutting off to zero exp where retail would.

**Comment by ibm2431** [comment]
Chiming in that if the monster's level is sufficiently high, you'll still get exp at low levels even if there's a level 99 in the party doing the killing. Example: Power/page leveling in Zeruhn Mines. It's a pathetically small amount, but it doesn't zero out.

From a log years ago (2014/03/11):
```
[06:42:58]Hanatori defeats the Burrower Worm.
[06:42:58]EXP chain #3!
[06:42:58]Nedaltic gains 28 experience points.
[06:42:58]Nedaltic attains level 26!
```
I was burning up one of my main's jobs to 30 in Zeruhn. Mule doing the killing was 99.

I want to say that you'll get exp even as low as level 10, but I don't feel like digging through all my logs at the moment.

**Comment by TeoTwawki** [comment]
>``` [03:12:11]Records of Eminence: Gain Experience.
[03:12:11]Progress: 1704/5000.
[03:12:11]You defeated a designated target. (Progress: 1/5)
[03:12:11]Records of Eminence: Vanquish Multiple Enemies I.
[03:12:11]Progress: 1/200.
[03:12:13]Nedaltic defeats the Colliery Bat.
[03:12:13]Hanatori gains 4 experience points.
[03:12:13]Hanatori attains level 11!
[03:12:13]You find a bat wing on the Colliery Bat.
```

^ this is inline with my own memories.

@R3P0FFXI Legion is running with a 3.25 conf setting for the exp, so that example would be 13 exp there. Can you try it with a  lv 10 ?

**Comment by TeoTwawki** [comment]
wtf github, get your act together on markdown format

**Comment by TeoTwawki** [comment]
> [03:12:11]Records of Eminence: Gain Experience.
[03:12:11]Progress: 1704/5000.
[03:12:11]You defeated a designated target. (Progress: 1/5)
[03:12:11]Records of Eminence: Vanquish Multiple Enemies I.
[03:12:11]Progress: 1/200.
[03:12:13]Nedaltic defeats the Colliery Bat.
[03:12:13]Hanatori gains 4 experience points.
[03:12:13]Hanatori attains level 11!
[03:12:13]You find a bat wing on the Colliery Bat.

This is inline with my own memories.

@R3P0FFXI Legion is running with a 3.25 conf setting for the exp, so that example would be 13 exp there. Can you try it with a  lv 10 ?

**Comment by ibm2431** [comment]
I checked that particular log again; I had a level 18 friend/leech in the party as well. The other three slots were either trusts or non-existent. According to bgwiki, [those bats](https://www.bg-wiki.com/bg/Colliery_Bat) are level 75~78.

**Comment by mcmsweet** [comment]
I believe you could fix this issue by modifying charutils.cpp to add a check for the player level vs the maxlevel calculated by the DistributeExperiencePoints function.

if (maxlevel - PChar->GetMLevel() > 20) { baseexp = 0; }

correct me if I'm wrong? I'm new to the project.

**Comment by TeoTwawki** [comment]
I gave him a non retail solution that looked similar, but still dunno if this is a legit inconsistency with retail's exp gains in hi gap situations since I don't have an active retail account and exp rates have changed since my time. *In my day we went to the dunes for our exp! And it was uphill and snowing the entire trip. Both ways!*

**Comment by TeoTwawki** [comment]
If someone could run a few test kills with a very large lv gap on dsp and retail (same level diff and same /check value, pls) I'd appreciate the comparison so we can confirm or close this

**Comment by TeoTwawki** [comment]
if anyone experiences this, please open a new issue. its been over a year and not a peep so far, and legion closed up shop
