### ISSUE TITLE
Homepoint @pos set to 0s acros the board in Rivern B-01

### ISSUE THREAD

**Issue by GMYasiinEra** [DarkstarProject/darkstar#3676]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30161227_1**

**_Server Version_** (type `@revision` in game) **Unknown**

**_Source Branch_** (master/stable) **Master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **Confirmed in the globals, Aplied the fix**

Heya guys just here with another bug/fix.. Most recet glabals lua for homepoints doesnt have the proper co-ordinates for rivernesite B01. Ive done the leg work for the fix. 

`homepoints[73]  = { 3, 10,    -520,    -18,     505, 127,  29, 1000}; -- Riverne - Site #B01 #1 `

change the lua save it and @reloadglobal homepoint, bobs your uncle!

**Comment by GMYasiinEra** [comment]
Make sure your commas after each X,Y,Z,ROT align with the rest too or it'll put ya in the sky lol

**Comment by TeoTwawki** [comment]
You need to learn how to use git and fork, branch, clone, edit, commit, push, then pull request.

Issue reports are not for fix submissions. 

Here have some links. Google as often as you need to. 
https://git-for-windows.github.io/
https://tortoisegit.org/download/
https://www.youtube.com/watch?v=mSMGq3fTF-U
https://try.github.io/levels/1/challenges/1
