### ISSUE TITLE
typing /pcmd leave while being an alliance leader causes server crash

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3696]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/79a4e08a4d0198c6611ef3c90e60fa5c611e949f

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
typing /pcmd leave while being an alliance leader causes server crash

Form alliance, as leader type /pcmd leave, crash server see dump below

https://www.dropbox.com/s/w5z1dn9fp8bva2l/pcmd%20leave%20delete%20party%20alliance.cpp.7z?dl=0

**Comment by nyczducky** [comment]
#3229

**Comment by TeoTwawki** [comment]
I thought `/pcmd` commands didn't work till alliance dissolves, and that you had to use `/acmd` if you wanted anything done by command lien while in alliance. /shrug

**Comment by ibm2431** [comment]
In an alliance situation, if you `/pcmd leave` while being leader of the alliance, you drop from party/alliance while your yellow (party) and white (alliance) dots go to a random person in your party. For non-leaders, you simply drop from party/alliance.

`/acmd leave`, as leader, causes your entire party to leave the alliance, while keeping your party intact. For non-leaders, `/acmd` commands won't do anything.

**Comment by maxtherabbit** [comment]
think this is resolved
