### ISSUE TITLE
Level Sync Bug

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3708]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/79a4e08a4d0198c6611ef3c90e60fa5c611e949f

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Find good EXP Spot
Sync to level
Have level sync either run out of range or zone and come back, even happens sometimes when sync leaves party
Sync will be permanently stuck/broken at sync level IE level 10 Dunes
This apparently can be easily reproduced but does not happen every time

**Comment by TeoTwawki** [comment]
>  First of you need more then 3 Partymember. Then when you in Party you need to Sync. After this 1 member of the Party has to leave (but not the Sync member) by Zoneing or Warp or Tele. After this your PT is stuck in LvL Sync and if the Sync leaves then it is still stuck.

According to @cleanermc over in LegionDarks tracker..

**Comment by metalfiiish** [comment]
I was unable to reproduce the bug and I see that there was a code change to stop similar behavior here:
https://github.com/DarkstarProject/darkstar/issues/3949
https://github.com/DarkstarProject/darkstar/commit/e4145183db306202488a89bca5bf64c5fad44ff2
