### ISSUE TITLE
Garud BP Ward: Aerial Armor

### ISSUE THREAD

**Issue by Vaneticorum** [DarkstarProject/darkstar#3709]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor **
- [x] checked the commit log to see if my issue has been resolved since my server was last updated **

**_Client Version_** (type `/ver` in game) **:** 30161227_1

**_Server Version_** (type `@revision` in game) **:** 0582b915bb249e05e0fb99c992bace631fb2c9d4ba8

**_Source Branch_** (master/stable) **:** Stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Attempting to use Garuda's BP Ward: "Aerial Armor". There is no animation and the ability does not apply to the party. Tried this in multiple zones.

**Comment by R3P0FFXI** [comment]
Server Version is actually 79a4e08

**Comment by TeoTwawki** [comment]
@Vaneticorum yer supposed to check the little boxes in the post :)

@R3P0FFXI he sees diff hash when following the instructions because legion has custom commits

**Comment by Vaneticorum** [comment]
@TeoTwawki Figured it out after I posted and looked at my own post. >,>
@R3P0FFXI Thanks. I was confused how you were getting something different from me.

**Comment by R3P0FFXI** [comment]
@TeoTwawki I am aware was just adding the correct info into the ticket so whoever looks at this does not go WTF lol

Should also advise others this extends further then Ariel Armor, I would have to check but I cant remember if its Aero IV or Blizzard IV which does not work either, should probably rename the ticket to multiple blood pact abilities do not work.

**Comment by TeoTwawki** [comment]
it was aero 4, because nobody ever made aero 4 for garuda work. aerial armor has a script and was working fine last I knew - no idea what happened since.

**Comment by TeoTwawki** [comment]
I stand corrected they have an aero 4 script. I dunno wtf then.

**Comment by metalfiiish** [comment]
This can probably be closed as per that other issue ticket number, the problems have been resolved. I tested Aero IV and BP: Aerial Armor and they worked fine, animations and effects.
