### ISSUE TITLE
Oldschool crash in party stuff

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#3710]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Server Version_** (type `@revision` in game) **:**
dd43ffdaa371890500235699a8fd25697c1adb71

**_Source Branch_** (master/stable) **:**
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Dump: https://1drv.ms/u/s!AvyTIXTmkiRwmB-R1FClzMklu2Cm

**Comment by maxtherabbit** [comment]
looks like an attempt to run the ForAlliance lambda on a player with a party pointer to garbage memory after the use of /acmd breakup as shown in the log - probably related to #3696

**Comment by maxtherabbit** [comment]
@teschnei helped me come up with a potential fix, its still needs testing then I will push

**Comment by maxtherabbit** [comment]
think this is resolved
