### ISSUE TITLE
Jeuno Community Service Quest Bugged - cService logic

### ISSUE THREAD

**Issue by miex0r** [DarkstarProject/darkstar#3714]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Source Branch_** (master) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The jeuno community service quest logic is incorrect. Currently you have to select light posts in order. ie: If cService == 1, cService = 2.

The quest should not care what order the lights are selected.

http://ffxiclopedia.wikia.com/wiki/Community_Service

**Comment by wrenffxi** [comment]
I'll fix this soon.

**Comment by TeoTwawki** [comment]
sounds like a job for `setMaskBit()`/`setMaskBit()` and `isMaskFull()`

**Comment by takhlaq** [comment]
i apologise for committing that monstrosity (pretty sure i did anyways)

**Comment by TeoTwawki** [comment]
Git blames whasf, but we know it was you! [Coz it was the SVN patch days and whasf thanked you](https://github.com/DarkstarProject/darkstar/commit/5d7538cc1c012cc42e7c155f70619bcb64c0a5af) 😆

**Comment by takhlaq** [comment]
o god the xbl style name
brb force push overwriting any commit messages involving that

and yeah git's on my side, i blame whasf
