### ISSUE TITLE
element/magic absorb modifiers are broken

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3718]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
edb534fc2f1a02e97b0acf3498fbd6658aee649b

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When *Gurfurlur the Menacing* does his Arcane stomp, you can one shot him with any magic dmg weaponskill. Also any other mob using magic shield to absorb dmg. Here is why that happens:

Put magic shield effect with power of 3 or more. If power is 3,
```lua
        target:addMod(MOD_FIRE_ABSORB, 100);
        target:addMod(MOD_EARTH_ABSORB, 100);
        target:addMod(MOD_WATER_ABSORB, 100);
        target:addMod(MOD_WIND_ABSORB, 100);
        target:addMod(MOD_ICE_ABSORB, 100);
        target:addMod(MOD_LTNG_ABSORB, 100);
        target:addMod(MOD_LIGHT_ABSORB, 100);
        target:addMod(MOD_DARK_ABSORB, 100);
```
is set. if power if greater than 3, the default "else" happens setting
```lua
        target:addMod(MOD_MAGIC_ABSORB, 100);
```
In either case, the value of 100 is the proc chance. On proc,instead of healing the target you will do extremely high damage.

![batman_2017 02 14_063228](https://cloud.githubusercontent.com/assets/6871475/22927859/7513062e-f281-11e6-8f37-1db065815b2f.png)

**Comment by teschnei** [comment]
somewhere in the core is still using a uint16 instead of an int32, I'd guess

**Comment by Brierre** [comment]
When I was playing around with this, Gurfurlur was recovering health fine with magic -aga spells when he did the move, but it was telling me that his guards were recovering health when it was actually killing them.  I tried putting their magic absorb in their own .luas when he had the effect.  It seemed to work, but the messages were a whole lot of spam.
