### ISSUE TITLE
Smithing Guild Recruit Error

### ISSUE THREAD

**Issue by Vaneticorum** [DarkstarProject/darkstar#3731]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170204_1

**_Server Version_** (type `@revision` in game) **:** https://github.com/DarkstarProject/darkstar/commit/edb534fc2f1a02e97b0acf3498fbd6658aee649b

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Joining the Smithing Guild in San d'Oria results in a message saying, _"You must free at least 4096 spaces before trading those items"_ after NPC Mevreauche gestures as though he is handing you something.

**Comment by TeoTwawki** [comment]
Sounds like a TextID issue.

**Comment by ibm2431** [comment]
Is. All the text IDs in North Sandy's Text IDs are one before the POLUtils dump for 30170204_1.

**Comment by TeoTwawki** [comment]
@Vaneticorum since the current master branch is still on client ver 30161227_1 this is fairly normal to get wrong dialogs like that.

**Comment by Vaneticorum** [comment]
@TeoTwawki @ibm2431 Makes sense. I might copy files from my laptop just to stop getting version mismatch issues. Thank you both for clarifying.
