### ISSUE TITLE
Om'aern MNK hundred fists like speed entire fight

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#3733]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161206_3

**_Server Version_** (type `@revision` in game) **:**
528aab2

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Old school server. Sea. Mob id 16912564.

Took out PLD faster than KB. War Om'aern seemed normal.

Server has also been lagging heavily, so not sure if that could be a factor.

**Comment by TeoTwawki** [comment]
934515a6103f79faead3bc847c7bdb28b77073d0 its combat delay was set to low for a h2h mob.

**Comment by xipies** [comment]
Thanks! Looks like Ul'aern has same (too low) delay, too.
