### ISSUE TITLE
Dynamis bastok zlib_compress ran out of space

### ISSUE THREAD

**Issue by helixhamin** [DarkstarProject/darkstar#3750]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/6dec1aa5fd14f17393633be053b1cbcac204822b

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Not sure. I was doing dynamis bastok, and kept getting client crash.

Here is the log that happened before the crash:
https://gist.github.com/helixhamin/f960da5b7d5644f9fb02a596d2c36bd6

Also checked the CPU and memory use. Memory use never exceeded 50%, and CPU use never exceeded 40%.

**Comment by helixhamin** [comment]
Could this be similar to this: https://github.com/DarkstarProject/darkstar/issues/3394

I know I was mass killing approximately 5 dynamis stones worth of pops or more. So, probably close to the same numbers as this other (Although mine is a windows 10 server, not linux).

**Comment by Cloudef** [comment]
This is indeed same issue as #3394 can be closed as dupe. I'll post more information to #3394, how you can help me to fix this.
