### ISSUE TITLE
Aura Steal - Not working

### ISSUE THREAD

**Issue by nyczducky** [DarkstarProject/darkstar#3755]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30170204_1

**_Server Version_** (type `@revision` in game) 8b8a839

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior) Aura Steal evasion or effect steal not working.

**Comment by TeoTwawki** [comment]
Not working because it doesn't exist yet. Mentioned with some discussion in #411 which may be useful to anyone trying to implement.

**Comment by nyczducky** [comment]
The line you referenced is blank. Old ticket so not sure what changed.

**Comment by Hozu** [comment]
Back when I tried this I was looking at the mobskills that Thinkers have that steal buffs, but those aren't doing it right. You're supposed to copy the entire effect, not just parts of it, but I couldn't figure out how to do that.

**Comment by TeoTwawki** [comment]
> The line you referenced is blank. Old issue so not sure what changed.

Sources changes moved the line. 

Here this one uses a specific revision: https://github.com/DarkstarProject/darkstar/blob/ca49d6169089d40dee318e8007c1a40790161180/src/map/lua/lua_baseentity.cpp#L5342

**Comment by TeoTwawki** [comment]
@Hozu should be able to just effect:getWhatever() any thing thats missing. Which parts couldn't be copied? If something is missing I'll make it happen, but I thought we had bindings for every status parameter already. power/tic/duration/subpower/tier...it looks like its all there.

```cpp
    int32 getType(lua_State*);
    int32 getSubType(lua_State*);
    int32 getPower(lua_State*);
    int32 getSubPower(lua_State*);
    int32 getTier(lua_State*);
    int32 getDuration(lua_State*);
    int32 getStartTime(lua_State*);
    int32 getLastTick(lua_State*);
    int32 getTimeRemaining(lua_State*);
    int32 getTickCount(lua_State*);
    int32 getTick(lua_State*);
```

should be able to use the stealEffect command for getting the effect, similar to the dispel function. If that doesn't already work it'll need to change.

**Comment by teschnei** [comment]
Maybe we should make a function to do all that automatically...

**Comment by TeoTwawki** [comment]
Probably should just modify the existing function to have an argument to do that instead of its current behavior. Whether we make the script or core end do it is another matter, either way the functionality *should* already be here is all I am saying.

**Comment by zynjec** [comment]
Can be closed, was added in https://github.com/DarkstarProject/darkstar/pull/4657
