### ISSUE TITLE
Utsusemi wiped on normal single target spells

### ISSUE THREAD

**Issue by cszark** [DarkstarProject/darkstar#3760]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170204_1

**_Server Version_** (type `@revision` in game) **:**
Unknown

**_Source Branch_** (master/stable) **:**
https://github.com/cszark/darkstar (a copy of darkstar/master as of 2/20/2017)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Sub or main ninja, cast utsusemi ichi or ni.  Level 99 with godmode makes it easy to test.  Attack and wait for Tonberry Maledictor to cast spells.  Notice how the "some" single target spells overwrite all shadows.

I host my own private server and keep it updated with the latest code from darkstar with some very minor adjustments to settings and configuration.  No custom code.

The issue: It seems some single target spells, when cast, remove shadows.  It is consistently the same spells.  I have narrowed down the cause of why shadows are removed.  Somehow the `PSpell->getFlag()` has a value of `SPELLFLAG_WIPE_SHADOWS (0x02)` on some of these spells.

Here is a list of spells the mob cast that wipe all shadows and have a flag value of 0x02 and shouldn't.
Aero3 /Debug Output: 0 2
Bind /Debug Output: 0 2
Burst /Debug Output: 0 2
Flare /Debug Output: 0 2
Drain /Debug Output: 0 2
Drown /Debug Output: 0 2
Quake /Debug Output: 0 2
Tornado /Debug Output: 0 2

File:
darkstar/src/map/entities/battleentity.cpp
Line: 1217

I injected some debugging code to display the variable values to confirm these findings.
```
//debug
if (PSpell->canTargetEnemy())
{
    ShowDebug(CL_CYAN"aoeType: %u spellflag: %u %\n" CL_RESET, aoeType, PSpell->getFlag() &
    SPELLFLAG_WIPE_SHADOWS);
}
```

**Comment by TeoTwawki** [comment]
I'm not seeing this bug at all on current master 50 casts into the same tonberry (assuming Temple of Uggalepih). Been hit by all of the listed spells, haven't seen on single instance of shadows being stripped or the flag value as anything but zero.

```cpp
        // Take all shadows
        if (PSpell->canTargetEnemy() && (aoeType > 0 || (PSpell->getFlag() & SPELLFLAG_WIPE_SHADOWS)))
        {
            ShowDebug(CL_CYAN"spell flags: %u AoE: %u \n" CL_RESET, PSpell->getFlag(), aoeType);
            PTarget->StatusEffectContainer->DelStatusEffect(EFFECT_BLINK);
            PTarget->StatusEffectContainer->DelStatusEffect(EFFECT_COPY_IMAGE);
        }
```

Is the debug print I used.

**Comment by TeoTwawki** [comment]
Edit: I fail at copy past

**Comment by cszark** [comment]
I just downloaded a fresh copy of darkstar/master compiled it, setup a brand new database, created a character, and still can replicate the issue.  Could this be environmental, something to do with my OS?

See screenshots.
![img_20170228_183254](https://cloud.githubusercontent.com/assets/6811415/23443641/048e6686-fde5-11e6-863f-28d62b4a8a07.png)
![img_20170228_183454](https://cloud.githubusercontent.com/assets/6811415/23443642/049137c6-fde5-11e6-9798-93de9926ff2f.png)

Also some background. I this issue has existed ever since I started working on this project in October 2016, so its not a new issue to me.

**Comment by TeoTwawki** [comment]
What OS you run server on?

**Comment by cszark** [comment]
Ubuntu 16.04 LTS

**Comment by TeoTwawki** [comment]
K hopefully mystery can be solved with some bit of platform specific silliness accidently left someplace..I'm on windblows 10 atm.

**Comment by TeoTwawki** [comment]
```
[1:05 AM] Lotus: i accidentally fixed it about a week ago
[1:05 AM] Lotus: m_flag was never initialized to 0
```

**Comment by TeoTwawki** [comment]
Sorry that took so long!
