### ISSUE TITLE
Quest "Empty Memories" has no code for completion

### ISSUE THREAD

**Issue by Whitechaser** [DarkstarProject/darkstar#3761]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30161227_1

**_Server Version_** (type `@revision` in game) **:** Unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/RuLude_Gardens/npcs/Harith.lua

Simply have to add a player:completeQuest(JEUNO, EMPTY_MEMORIES)  after line 102.
I'm not sure how much fame is supposed to be added though.

**Comment by helixhamin** [comment]
> Requirements	Jeuno Reputation 1

So, no worries about that.

**Comment by Whitechaser** [comment]
Oh, I wasn't talking about the required reputation. I was talking about how much you gain for completing the quest.
