### ISSUE TITLE
Mamool Ja mobskill "Warm-up" giving too high evasion? And possibly too much acc bonus. 

### ISSUE THREAD

**Issue by soupcans** [DarkstarProject/darkstar#3767]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
version 30161227_1

**_Server Version_** (type `@revision` in game) **:**
n/a

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

The code under in mobskills/Warm-Up.lua has this thingy:

```lua
local base = mob:getMainLvl() + 0.05*mob:getMaxHP()*(skill:getTP()/1000); --base is around 5~150 level depending
```

If my math is right... that would give a lvl 73~ mamool ja almost 300 bonus to evasion. I could not hit a Decent Challenge Mamool Ja Mimicker at 75, eating sushi, full accuracy gear, 508 total accuracy, when it did warm-up.

The evasion bonus does not match the comment by next to the code saying "5~150" evasion bonus "level depending".

**Comment by TeoTwawki** [comment]
I wrapped yer copse snippet in 
```
```code tags```
```
 for you

**Comment by Hozu** [comment]
Why in the hell is it using a percentage of mob HP!?

**Comment by TeoTwawki** [comment]
my guess is copy pasta:
https://github.com/DarkstarProject/darkstar/search?utf8=%E2%9C%93&q=level+depending

**Comment by GMYasiinEra** [comment]
dispel ftw

**Comment by TeoTwawki** [comment]
**Mob** versions of :
*Diamondhide
Metallic Body
spring water
whispering wind*
All exhibit the same garbage code. I just spent an hour trying to find some reliable info that wasn't specific to the blue magic version or blatantly bulls\*\*t with no luck. If all crabs metal body was always only 25hp, I'd have been taking that off in a single hit on those high level crabs we always wanted dispel for..

**Comment by Hozu** [comment]
I didn't think that retail crabs Stoneskin really scaled, but everyone wanted Dispel for Scissor Guard and Bubble Curtain.

**Comment by TeoTwawki** [comment]
@Hozu I suspect diff crabs on retail (particularly the NM ones) use diff copies of the skill. The global skill list has multiple (ID's 448, 1593, 3475, and 3865). Next time I can get on retail I'll go sample some and capture the skill ID, as well as try and get a grasp of how much "hp" their effect had.

**Comment by TeoTwawki** [comment]
Only info I can find for Warm-Up says +10 acc and eva, but that could be just the player version. Still, better than the mess we have now so I guess I'll make that change later.

**Comment by TeoTwawki** [comment]
So after getting on someones retail account to look, Mamools Warm-Up doesn't even do what the blue magic version does let alone base doff mobs HP and TP. the 1st mamool got evasion boost. the second mamool got accuracy boost. Same mamool different respawns of it. never managed to get any mamool to use it twice before dying. I'm making a few assumptions about how it works in my script changes.

**Comment by TeoTwawki** [comment]
And *Metallic Body* really is a static 25 every time on every non NM crab I could check..The multiple IDs in the skill list are for different visual models of crab (diff sized bones in the model)

**Comment by TeoTwawki** [comment]
Warm-up and Metallic body will no longer give crazy values to their effects, Warm-up was what opened this issue so closing this. Feel free to open new issues for other jacke dup skills (there's no shortage of copy pasta failures..)
