### ISSUE TITLE
BST ability Tame bugged, also pets 20% slower while the player 20% faster

### ISSUE THREAD

**Issue by Umbasa** [DarkstarProject/darkstar#3775]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (30170204_1) **:**

**_Server Version_** (UNKNOWN) **:**

**_Source Branch_** (STABLE) **:**

**_Additional Information_**

about a year ago, the issue with Tame had been hotfixed by turning it into a bind.  not sure if this could be done again, but could be worth a shot.   Also if there is any way to increase the movement speed of pets, that would help a lot.   Mainly Tame is the biggest issue...because 9 times out of 10 it will lead to death if i cannot successfully get away.  the -20% movement speed and +20% player speed helps a little but it is not practical as a means of escape as a beastmaster who is soloing.   I honestly wouldnt even file a ticket for the issue but it leads to my death a lot of times when i am soloing and i mischarm.  I know BST may not be the most popular job but i love it and its one of the only jobs i really enjoy in FFXI

**Comment by GMYasiinEra** [comment]
the movement speed issue is specific to ERA only umbasa since we have added rate custom movement rates.. as for tame itself.. Confirm bugged on current master

**Comment by teschnei** [comment]
While the original issue was lacking on the details, I'm assuming it was saying that tame wasn't implemented (because it wasn't)

Resolving this now due to 62c2b5de1a9d28b695ee3db7b191d6be174acab5 implementing Tame

**Comment by Umbasa** [comment]
Thank you for fixing it
