### ISSUE TITLE
Repeating EXP Loss while character left dead overnight

### ISSUE THREAD

**Issue by whateversclever1215** [DarkstarProject/darkstar#3782]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161227_1

**_Server Version_** (type `@revision` in game) **:**
"Revision is: Unknown" (DSP Server: ERA FFXI)

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
I was told to report this here, as this is a DSP/core code issue.

I multibox, although that is not relevant to this issue.
I was exping solo with my characters.

It was late and my wife distracted me / pulled me away from the game.
I just decided to let my THF (The only one fighting the mob, a non-aggro lizard at Cape Teriggan outpost) melee the last 40%~ hp of the enemy, and I just went afk. Wouldn't matter if I died one time. My character did die, but I just left it for the morning and went to sleep.

When I woke up, my character was still dead and had not home pointed, first question mark.
Someone had given me a raise while I was asleep.
I didn't accept or deny it because I was afk.
When I came back in the morning I accepted the raise.

Then I learned that I had lost over 2 full levels. I went from a pre-death 40,000/44,000exp at 75, to a post-death 28911/40,000 at Lv73.

I am told that this bug is known somewhat, but I didn't find it when searching your repository.
I think the Raise accept/deny dialog kept me from either homepointing or anything else. I think the timer kept running all night, and I think after every hour it took another death worth of experience.
I don't care about the exp loss, easy to earn back, but you should be aware of this bug.
Hopefully the extra detail that happened to me helps narrow down the cause of the issue.

**Comment by GMYasiinEra** [comment]
I can confirm this as well. We spoke about it and I have tested on the master since then. IF you let the timer run out you lose the exp for a second time upon being homepointed.. Since he didnt get homepointed(pending raise) everytime the hour went by he lost exp.. since he was away for so long, the timer kept rolling back his exp every hour until he finally awoke the next morning. Leaving him nearly 3 levels delvled lol. Now I was pretty harshe in explaining a simple work around but never the less its still a bug.

**Comment by R3P0FFXI** [comment]
@GMYasiinEra I would say this is a more Era specific bug then a DSP issue. I have never seen this happen at all on our server and we are fully upto date with DSP

**Comment by whateversclever1215** [comment]
This happened to another player on Era today.
I heard someone will be doing era specific testing of this later tonight.

**Comment by GMYasiinEra** [comment]
nah imma do a Master test tonight no need to test on era its hands down happening.. ill pull a clone tonight and test

**Comment by xipies** [comment]
This happens on oldschool, too.

**Comment by GMYasiinEra** [comment]
Tested on DSP UnkownX7 did as well i think he has the fix.

**Comment by maxtherabbit** [comment]
I don't think that pull request fixed this, it did fix not homepointing when the timer runs out however

**Comment by teschnei** [comment]
When there are reports of the bug persisting, we will reopen it.

**Comment by UnknownX7** [comment]
The bug was occurring because the character wasn't being revived and was staying dead upon the end of the dead state and it was detecting the player at 0 hp, killing them again. Now, the player is revived the tick before the dead state ends, so it should be fixed now (it was when I tested it at least).

**Comment by whateversclever1215** [comment]
If the death timer always sends a player to their homepoint upon reaching 0 now, then there will be no way to even potentially access this bug anymore, if I am not mistaken.

**Comment by GMYasiinEra** [comment]
does this account for a pending raise?

**Comment by UnknownX7** [comment]
Pending raises shouldn't have any effect on the death timer AFAIK, they only set a variable that lets the server know that the player is allowed to revive without changing the death state timer.

**Comment by whateversclever1215** [comment]
What UnknownX7 has said fits with how someone else on ERA had the same issue but as far as we know without ever receiving a raise. This was before anything was done here.

**Comment by maxtherabbit** [comment]
I'm absolutely certain I have experienced the "repeating xp loss" while being dead for *much* less than 1 hour

**Comment by whateversclever1215** [comment]
What maxtherabbit just said fits with how I was dead for ~12h real time, but I lost 2.5 levels, if it's 10% exp loss per death that's ~25 deaths not 12.

**Comment by teschnei** [comment]
If you can reproduce that now with this fix, then we can open a new issue on it.

The death timeout doing nothing and the state repeating are two separate issues, and we already fixed one of them in here - so we'll assign the other one a new issue if it's still happening.
