### ISSUE TITLE
unexpected party behaviour when using multiple zone servers

### ISSUE THREAD

**Issue by maxtherabbit** [DarkstarProject/darkstar#3789]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

still trying to document the extent of this issue...

so far I have the "phantom party" thing where the server(s) recognise the existence of party/alliance elements that are not displayed to the players
i.e. 
1) player shows up as solo on their HUD when actually in party (seen on other members' HUDs)
2) you invite a player who search shows as solo and they are added on as allianced pt of 1

additionally observed that when a player is in a party/alliance and they zone that will not be reflected in the party HUD if they are zoning to a different server

some of these problems have been resolvable by party leader zoning or changing leader, indicating that at least in part they are caused by failure to send party update packets 

other observations I've received from other players:
"when player leaves pt, pt list doesn't update nor does search" - conditions to reproduce unknown
"if you don't fully disband after being in an alliance you randomly get put in main pt or look like you're in a second pt"
"player zone/hp/mp all vanish across alliance when people are added. dropping a person and re-adding fixes that"

**Comment by teschnei** [comment]
Do you have consistent reproduction steps yet?

**Comment by maxtherabbit** [comment]
unfortunately not

**Comment by maxtherabbit** [comment]
updated OP with related observations, I also have can reproduce one of these:
 if you zone into a different server the other party members will still see your hp bar as if you never left
<maxtherabbit> repeatable
<maxtherabbit> zoning into same server works 100% as expected
<maxtherabbit> like im in bastok mines, a party member zoned from mines into markets i saw that, she then zoned into gustaberg i still see markets
<maxtherabbit> then she zoned into palborough i see markets still
<maxtherabbit> but our third party member in boyahda saw the update when she hit palborough
<maxtherabbit> since they're both dungeon types on same server
