### ISSUE TITLE
King Arthro No longer pops after Knight Crabs are killed

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3794]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170204_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/4f2ca3d08e77b162ebdbf18d4461c27025509186

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Kill 10 Knight Crabs KA does not spawn

Script and DB both look ok from what I can tell

```sql
INSERT INTO `mob_spawn_points` VALUES (17203216,'King_Arthro','King Arthro',5783,-144,5,474,93);
```

```sql
INSERT INTO `mob_pools` VALUES (2254,'King_Arthro','King_Arthro',77,0x0000650100000000000000000000000000000000,4,5,12,240,100,0,1,0,0,2,20,32,514,157,0,1,79,1,0,77);
```

```sql
INSERT INTO `mob_groups` VALUES (5783,2254,104,86400,128,1935,35000,0,55,55,0);
```

From the Knight Crab Script in Jugner Forest
```lua
-----------------------------------
-- onMobDespawn
-----------------------------------

function onMobDespawn(mob)
    SetServerVariable("[POP]King_Arthro",GetServerVariable("[POP]King_Arthro") + 1);

    if (GetServerVariable("[POP]King_Arthro") == 10) then
        SetServerVariable("[POP]King_Arthro",0);
        SpawnMob(17203216); -- Pop King Arthro !
    end
end;
```

**Comment by TeoTwawki** [comment]
Wrap code in code tags. 3 backtics, a language type (lua, c++, whatever) and end with newlien and 3 closing backtics.
` ```lang`
`code here`
` ``` `

**Comment by metalfiiish** [comment]
This ticket should be closed. He spawns just fine since the changes in https://github.com/LegionDark/Issues/issues/1407. I tested it on current branch an no problem getting him to spawn.

**Comment by R3P0FFXI** [comment]
@metalfiiish this is intermittent if you just start up or restart the server it fixes it no matter the DSP version (yes our server runs pretty current code from DSP on the master branch). You would need to run your server for a good long while before it happens at random and the crabs are not synced properly.
