### ISSUE TITLE
Synth not working: Al zahbi sash

### ISSUE THREAD

**Issue by FrankWHansen** [DarkstarProject/darkstar#3796]
Al Zahbi Sash synth works, but the desynth does not.
Lightning crystal => al zahbi sash
NQ: 1 karakul thread
HQ1: 1 gold thread
HQ2: 1 wamoura silk
HQ3: not listed on the main page, but one person on talk page states he got 1 rainbow thread as result

**Comment by TeoTwawki** [comment]
`<!-- Issues will be closed without being looked into if the following information is missing (unless its not applicable). -->`

Template exists for a reason. If you are on mobile and no template loaded into the input box, complain to github that they have a broken feature when on mobile.

This is what you should see when in the input box when you open an issue:

```md
<!-- remove space and mark with 'x' between [] -->

**_I have:_**

- [ ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated


<!-- Issues will be closed without being looked into if the following information is missing (unless its not applicable). -->

**_Client Version_** (type `/ver` in game) **:**


**_Server Version_** (type `@revision` in game) **:**


**_Source Branch_** (master/stable) **:**


**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

```
