### ISSUE TITLE
CoP ring selection glitch

### ISSUE THREAD

**Issue by Heepster03** [DarkstarProject/darkstar#3801]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170204_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/4f2ca3d08e77b162ebdbf18d4461c27025509186

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
While choosing the Chains of Promathia reward (Rajas, Sattva, or Tamas Ring), if you choose either Sattva Ring or Tamas Ring and say "I've changed my mind."; it will replace the top option (Rajas Ring) with the other options depending which one you choose. For you to be able to select Rajas again after this, you must fully back out and reclick the door.

I have included a video showing said bug.

https://vimeo.com/208201590

or 

[CoP ring glitch.zip](https://github.com/DarkstarProject/darkstar/files/839548/CoP.ring.glitch.zip)

**Comment by Hozu** [comment]
This happens with the Divine Might earrings selection as well, IIRC.

**Comment by TeoTwawki** [comment]
is this fixed now?

**Comment by wrenffxi** [comment]
Yes, can be closed.
