### ISSUE TITLE
Southern San dOria chat manual lua file different from npc_list table entry

### ISSUE THREAD

**Issue by Trystanosaurus** [DarkstarProject/darkstar#3808]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
db80cb1d

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
If you try to use the Chat Manual in Southern San dOria (G-10) nothing happens and the game server returns a message saying ChatManual.lua can not be found. There is however a file in scripts/zones/Southern_San_dOria/npcs/ called Chat_Manual.lua
Renaming that to ChatManual.lua makes it work as expected.

Edit: Looking at the SQL file all other copies of it are called Chat_Manual in the npc_list table, so it's more likely that the lua file is correct and the databas entry is wrong.

**Comment by TeoTwawki** [comment]
> Edit: Looking at the SQL file all other copies of it are called Chat_Manual in the npc_list table, so it's more likely that the lua file is correct and the databas entry is wrong.

Convention is to replace spaces with underscores so yep :)
