### ISSUE TITLE
Gallant's Roll is reducing Magic damage when it shouldn't

### ISSUE THREAD

**Issue by soupcans** [DarkstarProject/darkstar#3829]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
version 30170304_1

**_Server Version_** (type `@revision` in game) **:**
Unknown

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

http://ffxiclopedia.wikia.com/wiki/Gallant%27s_Roll

Reduces Physical damage taken

Think it's because Gallant's roll is using MOD_DMG instead of MOD_DMGPHYS lol
![img_20170328_174323](https://cloud.githubusercontent.com/assets/25946262/24433560/6f126638-13de-11e7-8c8c-72c7f367fdec.png)

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/pull/2993 check the source in the pull that changed it.

**Comment by soupcans** [comment]
Ah nvm
