### ISSUE TITLE
BLU Magic Spell Seedspray not available

### ISSUE THREAD

**Issue by KalinaERA** [DarkstarProject/darkstar#3832]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
0346a07690ef52ed3e473215129fe7ceed65d80f

**_Source Branch_** (master/stable) **:**
Neither

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
BLU Magic Skill Seedspray is not learnable. The spell (mobskill) is not available within the database.

**Comment by whasf** [comment]
Hi, thanks for the report but a missing spell isn't a bug. It just plain isn't implemented yet.
