### ISSUE TITLE
Lure of the Wildcat (Bastok)

### ISSUE THREAD

**Issue by FrankWHansen** [DarkstarProject/darkstar#3833]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
155308e1370596ad4071ad1421fac1398f0fc0ec

**_Source Branch_** (master/stable) **:**
I do not know how to get this information.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Talk to NPC: Alib-Mufalib - Port Bastok (K-7) to start the quest.
Talk to NPCs Paujean and Tilian. Notice Tilian will say the exact same thing as Paujean, and each sentence will be preceded by Paujean: just as when Paujean said it.
Then talk to Tilian again, and the response that you were supposed to get the first time will be given.

**Comment by TeoTwawki** [comment]
wrong csid, I'm on it.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/d279ef17bfa96fe39f78430f2e591a45826c0e07
