### ISSUE TITLE
WotG Mission "Purple, The New Black" BCNM Fight Bugged

### ISSUE THREAD

**Issue by Arrytha** [DarkstarProject/darkstar#3836]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
Current

**_Server Version_** (type `@revision` in game) **:**
Current, LegionDark

**_Source Branch_** (master/stable) **:**
Not sure what this is stable i guess?

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
The Reinforced Gateway for the CS & BCNM fight Galarhigg is bugged. Upon clicking on the door, it simply opens. It should activate a Cutscene and then clicking again should enter you into the BCNM fight. The door just opens. X:-110 Y:0 Z:-180 (117), La Vaule (S) See my LD post on this: https://github.com/LegionDark/Issues/issues/1429

**Comment by TeoTwawki** [comment]
to my knowledge this was never implemented and is where the missions currently stop (I have been away for awhile)
