### ISSUE TITLE
Total loss of all Key Items

### ISSUE THREAD

**Issue by stevomatic** [DarkstarProject/darkstar#3844]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
No idea what is relevant, I was doing ToAU mobs for mythic trials, finished mine and when we zoned for others going from Gulool to Khimaira I checked map and noticed that I had no map, further I noticed
 my key item slate was a total wipe, nothing remarkable happened other than i got my trial done and zoned. Key item wise I've farmed various mobs in Abyssea lately that are, I guess, force pop, but they're up and respawn almost immediately after kill? Also missing ??? in Abyssea. Been effectively neutered without KI and unable to request

**Comment by TeoTwawki** [comment]
>  I was doing ToAU mobs for mythic trials,

sounds like  you wanted your servers tracker (legion player?) since no such thing currently exists in darkstar.

**Comment by Brierre** [comment]
I've seen this happen on other servers in the last 1-2 months.  Haven't noticed any kind of pattern to when it occurs.  Sometimes triggering an NPC, other times after a mission completion CS where a KI should have been received.  BLAM, all gone.

**Comment by TeoTwawki** [comment]
@Brierre Happens when something attempts to write invalid things to the blob. Lots of ways that can happen even though the lua binding checks for null.

+1 for "lets stop doing that as a blob". :sulk:

**Comment by Brierre** [comment]
haaaate the blob

**Comment by TeoTwawki** [comment]
Used to happen to spell lists too, till we un-blob'd those.

**Comment by helixhamin** [comment]
I have asked about unblobing things, like missions...got a response that was basically "No"...

**Comment by Altalus** [comment]
+1 for "lets stop doing that as a blob".

 

Never understood why it was a blob anyway :P

 

______________________________

Guillaume Gingras

**Comment by TeoTwawki** [comment]
because normally its more convenient and *should* cause problems, but unblobing things is a lot simpler than figuring out what/how blob handling for this particular one got fouled up on top just plain being easier for laypersons to deal with.
