### ISSUE TITLE
Some synths not in database

### ISSUE THREAD

**Issue by FrankWHansen** [DarkstarProject/darkstar#3846]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
0cbd46

**_Source Branch_** (master/stable) **:**
I don't know how to answer this question (if it's explained in this thread, I'll be happy to do it in future issue reports.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Cannot synth: Bookstack: http://ffxiclopedia.wikia.com/wiki/Bookstack
Cannot desynth: Al Zabhi Sash: http://ffxiclopedia.wikia.com/wiki/Al_Zahbi_Sash

**Comment by whasf** [comment]
Thanks for the report, but missing database items aren't considered a bug. They just haven't been contributed to the project by someone yet.
