### ISSUE TITLE
Bug in castSpell function in lua_baseentity.cpp

### ISSUE THREAD

**Issue by neosatus** [DarkstarProject/darkstar#3848]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** n/a

**_Server Version_** (type `@revision` in game) **:** n/a

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

castSpell was coded with functionality to allow passing in a target but has a bug.

Lines 8889-8893 are currently:

```
if (!lua_isnil(L, 1) && lua_isuserdata(L, 1))
{
    CLuaBaseEntity* PLuaBaseEntity = Lunar<CLuaBaseEntity>::check(L, 1);
    PTarget = (CBattleEntity*)PLuaBaseEntity->m_PBaseEntity;
}
```

When it looks like it was intended to be this:

```
if (!lua_isnil(L, 2) && lua_isuserdata(L, 2))
{
    CLuaBaseEntity* PLuaBaseEntity = Lunar<CLuaBaseEntity>::check(L, 2);
    PTarget = (CBattleEntity*)PLuaBaseEntity->m_PBaseEntity;
}
```

**Comment by teschnei** [comment]
Pull request

**Comment by TeoTwawki** [comment]
I was bored.. https://github.com/DarkstarProject/darkstar/commit/92fcff4ff0a288e4aea5c2af7b6f2b4ecacdc5b8
