### ISSUE TITLE
Various enfeebling formula do not match retail

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3851]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
current

**_Server Version_** (type `@revision` in game) **:**
current

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

- [x] Looking over the scripts for various enfeebles, their formula are not matching the ones posted by the devs:

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6503005&viewfull=1#post6503005

- [X] Note: Blind and Blind II are wrong in that post - this post has the correct formula: https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6504743&viewfull=1#post6504743 Note that for potency, it's comparing caster's MND to target's INT - I wonder if that's a typo on the dev's part?

Shouldn't be difficult to fix at all, but I can't do it myself as I'm unable to test.

- [ ] Edit: The effect of Saboteur is 1/4th of its normal potency vs. NMs: https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6473762&viewfull=1#post6473762

Edit 2: Sleep and Bind are not affected by stats - merely enfeebling skill and magic accuracy. And enfeebling duration is not random, being determined solely by resist level. Presumably Repose is in the same boat.

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6373540&viewfull=1#post6373540

- [x] Edit 3: Duration of Paralyze/Paralyze II/Silence is 120s, Poison/Poison II is 90s. Blind/Blind II is 180s. Nothing about Slow/Slow II though...

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6365216&viewfull=1#post6365216

- [ ] Edit 4: Distract/Frazzle changes in Feb 2017 update: https://www.bluegartr.com/threads/129738-Distract-Frazzle-Values-Post-Feb-2017-Update-QD-Testing?p=6857849&viewfull=1#post6857849

**Comment by TeoTwawki** [comment]
I think the only spells we're doing correctly right now are elemental nukes  😢

**Comment by Hozu** [comment]
Also, I'm assuming that Blind II formula is also missing the potency boost from merits... whoops.

I'll see if there's anything else I can dig up. I'll probably make another issue for those.

**Comment by TeoTwawki** [comment]
The int/mnd thing on blind shouldn't be to difficult to check on retail for anyone that has an account.if it actually compares player mnd to mob int, thats different from all the other spells and breaks the pattern the rest follow.

**Comment by Hozu** [comment]
"A monster with high darkness resistance may be able to be hit with Blind if it has little Resist Blind, but may still resist Frazzle. This is intended by design."

Looks like those traits need to be taken more heavily into account as well. And various mobs/NMs should be adjusted with those traits (ie. giving Suzaku a high Resist Silence trait value).

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6839575&viewfull=1#post6839575

**Comment by TeoTwawki** [comment]
We'd adjust their level of the modifier, rater than changing "traits". Element resistance is inherited by family, and right now the only status specific resistance would be granted by job and that's miniscule. 

Also have to be careful not to confuse resistance with immunity, the wiki's will sometimes conflate them (A lot of people thought this or that NM was "immune" till the level cap went up and people could pile on another +200 skill). It can be determined in game by the message text.

**Comment by TeoTwawki** [comment]
Additional resistance mods that aren't part of the family entry can either go in the whatever_mods.sql tables or in `onMobInitialize()` via `addMod()`/`setMod()`. Full on immunity is currently handled in mob_pools.sql

**Comment by Hozu** [comment]
Blind/Blind II got a third post - it uses caster's INT vs. target's MND for potency. That's... strange, but at least it still works by INT for the caster.

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6517315&viewfull=1#post6517315

**Comment by TeoTwawki** [comment]
I must now dat mod blind/blind2's graphical effects into *a special unique snowflake* on my client.

**Comment by Hozu** [comment]
Saboteur effect is 1/4th of what it normally is vs. NMs. Haven't seen anything posted later on regarding that. I'll edit the main post accordingly.

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6473762&viewfull=1#post6473762

**Comment by Hozu** [comment]
Sleep and Bind are not affected by stats - merely enfeebling skill and magic accuracy. And enfeebling duration is not random, being determined solely by resist level.

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6373540&viewfull=1#post6373540

I imagine Repose is in the same boat here?

**Comment by Hozu** [comment]
Wait... I'm not sure this will actually require any change here? Since dINT/dMND affects accuracy in the scripts already.

**Comment by TeoTwawki** [comment]
> I imagine Repose is in the same boat here?

I think it'd be divine skill instead of enfeebling, even if (I dunno) MND were not involved.

**Comment by TeoTwawki** [comment]
I gotta go out, good luck sifting through the global  and the *multiple* resist functions that chain into each other to see what stat gets used how!

**Comment by Hozu** [comment]
Duration of Paralyze/Paralyze II/Silence is 180s, Poison/Poison II is 90s. Nothing about Slow/Slow II though...

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6365216&viewfull=1#post6365216

**Comment by Hozu** [comment]
I'm thinking magic accuracy still includes dINT for black magic/dMND for white magic. Wasn't that the consensus from testing long ago? The main things here being dINT/dMND affecting potency, and correcting the variable potency for each enfeeble.

**Comment by Hozu** [comment]
Edited the first post to reflect what has been done so far. Not sure what should be done with the info about Sleep/Bind though. Probably should leave it as-is unless someone can confirm that stacking INT doesn't affect the accuracy of those spells.

**Comment by Hozu** [comment]
Found a thread about changes to Distract/Frazzle in the Feb 2017 update. Looks like those scripts that were just added will need to be updated.

https://www.bluegartr.com/threads/129738-Distract-Frazzle-Values-Post-Feb-2017-Update-QD-Testing?p=6857849&viewfull=1#post6857849

**Comment by TeoTwawki** [comment]
I think I mentioned on one of my commits right after the merge that the formula was up on bg

**Comment by zynjec** [comment]
This is largely fixed with Autkast's rewrites, going to close this.

Any future problems can open a new issue.
