### ISSUE TITLE
blockaid does not block alliance requests

### ISSUE THREAD

**Issue by Jessland86** [DarkstarProject/darkstar#3878]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
581b5e7da03d7e1f088057abccf4e5af4334a1c5

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Make a party, have the leader turn blockaid on, have someone send an alliance request, blockaid will not block the request.

**Comment by whasf** [comment]
Should be fixed in 9d4b3e30ffb556f228f2ebfa63462a92bf69a567
Thanks for the report!
