### ISSUE TITLE
missing item_mods Pup relic

### ISSUE THREAD

**Issue by dwn134** [DarkstarProject/darkstar#3883]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30170304_1

**_Server Version_** (type `@revision` in game) b010e4eb8ce001c35667706a8fd452f851b92aff

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

sorry im new to this and not sure where im supose to put fixes I find
but this adds pet mods of magic acc and MAB to pup relic pants and feet NQ and +1

INSERT INTO `item_mods` VALUES (16352,30,5);
INSERT INTO `item_mods` VALUES (16353,30,7);
INSERT INTO `item_mods` VALUES (11388,28,5);		
INSERT INTO `item_mods` VALUES (11389,28,5);

**Comment by TeoTwawki** [comment]
https://help.github.com/articles/fork-a-repo/

https://help.github.com/articles/creating-a-pull-request/

protip:  
after you fork, create a new branch before making any changes. do all your changes and pull requests in branches, that way your master branch stays "clean" and updating it is as simple as pulling darkstar's master onto it.

**Comment by TeoTwawki** [comment]
p.s.

> item_mods

Pet mods happen in item_mods_pet normally

**Comment by dwn134** [comment]
Ah i found it now. Its in there thanos
