### ISSUE TITLE
Ranged Attack - Sometimes cannot see mob

### ISSUE THREAD

**Issue by Hokuten85** [DarkstarProject/darkstar#3891]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When attempting to do a ranged attack, occasionally you will receive a message saying that you cannot see the mob.  On my own private server I've narrowed down one scenario that was causing this issue, but I'm not positive that I've identified all scenarios.

in common\utils.cpp I made the following changes:

```
uint8 getangle(const position_t& A, const position_t& B)
{
    return (uint8)(atan2f(B.z - A.z, B.x - A.x) * -(128.0f / M_PI));
}

bool isFaceing(const position_t& A, const position_t& B, uint8 coneAngle)
{
	int32 angle = getangle(A,B);
    coneAngle = coneAngle >> 1;
    
    //need to check to see if the angle and rotation are within the coneAngle
    //special scenario when the rotation is near 256, need to see if the angle is near to zero in quadrant 1
    //special scenario when the angle is near 256, need to see if the rotation is near to zero in quadrant 1
	return abs(angle - A.rotation) <= coneAngle || 256 - A.rotation + angle < coneAngle || A.rotation + 256 - angle < coneAngle;
}
```
I modified getangle, though that probably doesn't really need to change.

isFaceing appeared to have a bug in it.
The game uses 0 through 255 to represent angles.  There were scenarios where you'd have and angle near zero and a rotation near 255 that would be within the coneAngle, but the previous logic didn't account for rotations around 255 actually being close to angle zero.  And the reverse was also true where rotation was near zero and angle was near 255.

This was my solution, but I couldn't figure out how to do a pull request but not include all of the other customizations I've made on my fork.  I also didn't know if there was a more elegant way of achieving the same thing or maybe I'm full of crap and this isn't a bug at all.

**Comment by teschnei** [comment]
Also explains Sneak Attack rarely failing.  Thanks for the bug report.

**Comment by Hokuten85** [comment]
Glad I could help.
