### ISSUE TITLE
Mobskills considering players out of range when they are not

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3894]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/a157563af2005c7a777439586726dada159b60d4

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Flail tank Nidhogg from behind, while having other people in the pit, at the time they were 20 yalms away from Nid they did not get hit by the spike flail, it appeared to either be single target or affected by elevation change. Does not appear to hit people outside the alliance either. It's supposed to literally wreck anyone in the pit period. Hurricane wing appears to not hit anyone outside alliance either, and can also be out ranged.

Uses the same TP moves as Fafnir, but be warned, as they are not limited to the alliance who has claim. AoE attacks will hit everyone in range.
AoE range is ~40 yalms.

Is it possible that this is a line of sight issue?

**Comment by Deadwing888** [comment]
You have to add an identical spike flail and hurricane wing into sql with the hit all skillflag, then move them over into Nidhogg's WS list.

**Comment by TeoTwawki** [comment]
62ca175782c4333641d973f64f53ec69d4fa922f takes care of the alliance/not alliance part of it

**Comment by TeoTwawki** [comment]
(assuming that skillflag even works - I could swear I've been aeo'd outside of alliance/hatelist by things that did not have that set..)

**Comment by teschnei** [comment]
isn't that just spike flail? what about hurricane wing and dragon breath?

**Comment by TeoTwawki** [comment]
woops

**Comment by TeoTwawki** [comment]
Should *all* his moves his outside alliance?

**Comment by TeoTwawki** [comment]
7708a74ec61d39a8ef7483f31851c71f7faf6ea5

**Comment by TeoTwawki** [comment]
Now someone can figure out what causes it to exclude ppl even in alliance and in range. GL with that *not it* _-runs off-_

**Comment by Deadwing888** [comment]
I know nidhogg's hurricane wing and spike flail hit all. The only other aoe he has is dragon breath, not sure on this one but I believe it will hit all as well.

**Comment by TeoTwawki** [comment]
> Raelious commented 10 hours ago • edited
>
> Just to mention it here as well, there are several "spots' where you can fight Nidhogg and he cant see you and none of his move or attacks will be able to hit you. You could theoretically just put a DoT on him and nuke him down without ever getting hit.
>
> It has to be the navmesh in the area that is causing it, you could replicate it with the darters as well.
>

**Comment by teschnei** [comment]
We turned off navmesh in canSee a few months ago

**Comment by TeoTwawki** [comment]
I think this got fixed if I'm wrong open new issue.
