### ISSUE TITLE
DSP Using Extreme Bandwidth 

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3900]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170304_1

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/a157563af2005c7a777439586726dada159b60d4

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

After switching over to more up to date hardware with better monitoring on May24th

50 Unique concurrently connected clients for the last week have used the following bandwidth

28.28 GB (↓9.26 GB, ↑19.02 GB)

This game was designed for 56k modems. So I am not sure if DSP is not handling some packets correctly or there are some behavioral issues with the project that might need cleaning up.

I have spoken to Whasf and he confirmed he also has High Bandwidth usage roughly 53GB /month

Nasomi confirmed he has modified his code to cap at 2.5k thus reducing his Bandwidth usage I am not sure how relevant that will be in this.

I am not sure where to begin investigating to capture real time logs of what exactly is doing what to see if there is a way to narrow down where this is coming from.

**Comment by ibm2431** [comment]
28.28 GB / 50 clients = .56 GB / connection
573 MB / 7 days = 81 MB /connection/day

56k = ~0.0067 MB / second
0.0067 MB * 60 seconds * 60 minutes * 24 hours = 578.88 MB / connection / day.

Not saying that there might not be an issue with high bandwidth, just that the numbers aren't entirely impossible for 56k modems. Would need measurements over smaller time intervals; 50 connections over a week is a bit too broad.

**Comment by R3P0FFXI** [comment]
I can break down by 24 hour and hourly intervals if you would like

**Comment by teschnei** [comment]
Bear in mind that although the game was originally designed with 56k modem in mind, we are not emulating (or using the client of) the original game.

The information presented here is hard to come to any reasonable conclusions, though.  We'd need like.. average bandwidth while connected, if anything.

**Comment by R3P0FFXI** [comment]
Previous 24 Hours 

3.93 GB (↓1.22 GB, ↑2.71 GB)

Previous 2 hours 

405.8 MB (↓111.4 MB, ↑294.4 MB)

I see about 36 individual IP clients on currently 83 Characters, avg BW about 400k

**Comment by teschnei** [comment]
Correct me if I'm wrong.. isn't that like 500 bytes/s per character?

**Comment by TeoTwawki** [comment]
Whasf has maybe 10 people maybe multi boxing up to 20 connected characters. I can't see his server using that much so I am shocked he hasn't brought this up before himself.

**Comment by teschnei** [comment]
If whasf wants to comment on his character count and load over a time, we can consider it, but all we have is legion to go off of right now

**Comment by whasf** [comment]
As I was talking to R3 about this the other day, the bandwidth information I gave him for my connection includes my email traffic (and DSPT website too, now that I think about it). I would have to look into monitoring traffic just for the oldschool server to really get good numbers, but with my numbers being roughly half of his (with far fewer people online, but counting more types of traffic), I didn't think it was much of an issue.

I know it's been discussed in the past and I think we even made a change or two regarding packets being sent, especially entity/character update packets. I'm still glad he posted this for the discussion.

**Comment by xipies** [comment]
This line spams 0x37 packets when chars are moving around in zones:
https://github.com/DarkstarProject/darkstar/blob/master/src/map/entities/charentity.cpp#L488

When chars are standing still, this packet is not sent nearly as much.

From what I can tell, no other packet is sent as much as 0x37. The next most that I saw during testing was 0xDF (health update), probably because I was subbing whm a lot.

**Comment by teschnei** [comment]
Yes, that is the packet that moves characters around.  This is expected.

**Comment by xipies** [comment]
Oh, gotcha. I should have expected that. :)
