### ISSUE TITLE
SE Version Update 6/7/2017

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#3904]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
NA

**_Server Version_** (type `@revision` in game) **:**
NA

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

@ibm2431  Our guy wont be able to do this update @TeoTwawki has asked me to tag you in hopes you have time to do version update for DSP.

**Comment by TeoTwawki** [comment]
I meant just ask him if he was, on the other pr where we were talking.. >.> oh well

**Comment by ibm2431** [comment]
I won't have access to my dev machine for another two weeks~! If it's still not-done by then, I'll look into it.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/e9eacbce1159c963caa8850f6a0966d0789c53d6
