### ISSUE TITLE
Lotting on Items from any zone..

### ISSUE THREAD

**Issue by Neil-Mitchell** [DarkstarProject/darkstar#3907]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30170601_0**

**_Server Version_** (type `@revision` in game) **b010e4eb8ce001c35667706a8fd452f821b92aff**

**_Source Branch_** (master/stable) **master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **Reproduced with the alliance leader being 80/80 while farming in a zone.. breaks the alliance and reforms from that point on anything that person acquires in their loot chest will go into a pool no matter what zone you're in.. you can farm sky and sea for alts without them even leaving the starting city.. farm quest trade in items and lot with an alt in front the NPC that takes the item etc etc**

**Comment by KnowOne134** [comment]
unable to reproduce even after zoning in to same zone and get treasure pool and then zoning back out then its gone again

**Comment by TeoTwawki** [comment]
Open new issues if can be reproduced again. The alliance break step should be clearing the pool if I'm not mistaken.
