### ISSUE TITLE
Homepoint favorites bugged.

### ISSUE THREAD

**Issue by GMYasiinEra** [DarkstarProject/darkstar#3912]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30170601_0**

**_Server Version_** (type `@revision` in game) **b010e4eb8ce001c35667706a8fd452f821b92aff**

**_Source Branch_** (master/stable) **master**

**_Additional Information_** (Steps to reproduce/Expected behavior) **New accounts have access to various homepoints from within the favorites menu to zones they normally shouldn't have access to.. sea sky adoulin whitegate etc etc**

**Comment by TeoTwawki** [comment]
More like *"was never implemented at all"* and as previously reported the values intended for the non favorites menu options get passed into it causing it to give people options they shouldn't have there.

**Comment by TeoTwawki** [comment]
Sidenote: the default value when you should have zero homepoints also has homepoints available..somebody didn't verify their bit values survived lua's number storage type when they decided on -1 vs 0..

**Comment by RunAwayDSP** [comment]
also as a note the function hpTeleport should verify you have the teleport.

**Comment by ShelbyZ** [comment]
I looked at this briefly and came up with a check to see if they player has the HP they are intending to use, but the problem exists what to do if they don't.  The player is already in a cutscene animation that turns the screen black expecting to navigate away.

```lua
function hpTeleport( player, option)
    if ( option == 2 or option > 0x10000 and option < 0x7F0003) then
        local hpIndex = bit.rshift( option, 16); -- Calculate hpIndex based on option selected
        
        -- do normal free teleport logic...

        if (hasHP(player, hpIndex)) then
            -- send player on their way...
        else
            -- we are already in a teleport animation and no idea how to navigate away from the black void
            -- this skipped a cutscene but screen was still black
            -- player:release();
        end
    end
end;

-- borrowed logic from determining if the player needs to add this teleport to their bitmask
function hasHP (player, hpIndex)
    local HpTeleportMask1 = bit.bor( bit.lshift( player:getVar("HpTeleportMask1a"), 16), player:getVar("HpTeleportMask1b"));
    local HpTeleportMask2 = bit.bor( bit.lshift( player:getVar("HpTeleportMask2a"), 16), player:getVar("HpTeleportMask2b"));
    local HpTeleportMask3 = bit.bor( bit.lshift( player:getVar("HpTeleportMask3a"), 16), player:getVar("HpTeleportMask3b"));
    local HpTeleportMask4 = bit.bor( bit.lshift( player:getVar("HpTeleportMask4a"), 16), player:getVar("HpTeleportMask4b"));
    
    if ( homepoints[hpIndex][1] == 1) then
        if ( bit.rshift( bit.lshift( HpTeleportMask1, 32 - homepoints[hpIndex][2]), 31) ~= 0) then
            return true;
        end
    elseif (  homepoints[hpIndex][1] == 2) then
        if ( bit.rshift( bit.lshift( HpTeleportMask2, 32 - homepoints[hpIndex][2]), 31) ~= 0) then
            return true;
        end
    elseif (  homepoints[hpIndex][1] == 3) then
        if ( bit.rshift( bit.lshift( HpTeleportMask3, 32 - homepoints[hpIndex][2]), 31) ~= 0) then
            return true;
        end
    elseif (  homepoints[hpIndex][1] == 4) then
        if ( bit.rshift( bit.lshift( HpTeleportMask4, 32 - homepoints[hpIndex][2]), 31) ~= 0) then
            return true;
        end
    end

    return false;
end;
```

Feel free to work with the above as I don't know what should be done to avoid a black screen for the player.

**Comment by teschnei** [comment]
Mostly stems from the issue that they're not verified server-side on retail
either, but you could just zone them back to where they are currently
standing
