### ISSUE TITLE
"Foreigners" not charged increased price when buying Conquest Point items

### ISSUE THREAD

**Issue by Alice5150** [DarkstarProject/darkstar#3913]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30170601_0**

**_Server Version_** (type `@revision` in game) **c40a5e115b8a0e0679301def5074fbdb80d1bd1**

**_Source Branch_** (master/stable) **master**

**_Additional Information_** (Steps to reproduce/Expected behavior): http://ffxiclopedia.wikia.com/wiki/Conquest_Overseer When you belong to another nation besides the one you are buying Conquest Point items from, you should be charged double the price for items 8k CP or under, or 8k MORE for items over 8k in price. Neither seems to be working. Tested with two NPCs on two servers. A 16k item costs 16k, and a 2k item costs 2k. Tried with a Windurst character buying from Bastok, and a Windurst character buying from Sandy.
 https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Windurst_Woods/npcs/Panoquieur_TK.lua#L117

**Comment by TeoTwawki** [comment]
related: #3486

**Comment by Alice5150** [comment]
Thanks, I wasn't sure if that was related or not. Someone on the IRC didn't think it was.

**Comment by TeoTwawki** [comment]
prolly meant 2 diff bugs and he's right about that. both come from same crappy scripts though and one makes the other worse.

**Comment by wrenffxi** [comment]
fixed by conquest rewrite.
