### ISSUE TITLE
Yet another alliance server crash bug. 

### ISSUE THREAD

**Issue by Jessland86** [DarkstarProject/darkstar#3920]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170427_0

**_Server Version_** (type `@revision` in game) **:**
4ca87a3dd8b29dda4f8b2a11443d917eff30ed48

**_Source Branch_** (master/stable) **:**
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
How to crash your server in a few easy steps!

Step One) Make 3 parties.
Step Two) Have Party leader A send an alliance request to party leader B. Do not accept alliance request on party leader B,
Step Three) Have party leader C send an alliance request to party leader A, and have party leader A accept the alliance.
Sterp Four) have Party leader B accept the alliance invite that Party leader A sent. This will cause Party leader A to go from being a party leader in an existing alliance to being an alliance leader. While leaving Party leader C also an alliance leader. 
Step Five) Have Party leader C dissolve the alliance through the menu. 
Step Six) Crack open a beer, you just crashed the server!

**Comment by GMYasiinEra** [comment]
mmm beer
