### ISSUE TITLE
Cleric's Briault/+1's Enhanced Regen effect.

### ISSUE THREAD

**Issue by Chuchu90** [DarkstarProject/darkstar#3925]
**_I have:_**

[x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
[x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game)**:
30170304_1

**_Server Version_** (type `@revision` in game)**:
 b010e4eb8ce001c35667706a8fv452f821b92aff

**_Source Branch_** (master/stable)**:

**_Additional Information_** (Steps to reproduce/Expected behavior)**:
http://ffxiclopedia.wikia.com/wiki/Cleric's_Briault

The "Enhances potency of 'Regen'" effect on Cleric's Briault/+1 currently do not work.

"Adds 1 HP per tick to Regen, 2 HP per tick to Regen II, 3 HP per tick to Regen III, , and 4 HP per tick to Regen IV."

**Comment by wrenffxi** [comment]
As far as I can tell, it's working for me.  Can you clarify the problem?  Thanks.

**Comment by dwn134** [comment]
the added bonus from the relic doesnt apply but I think i got the fix.works on my test let me know if im on the right track and i can commit

-----------------------------------------
-- Spell: Regen
-- Gradually restores target's HP.
-----------------------------------------
-- Scale down duration based on level
-- Composure increases duration 3x
-----------------------------------------

require("scripts/globals/status");
require("scripts/globals/magic");

-----------------------------------------
-- OnSpellCast
-----------------------------------------

function onMagicCastingCheck(caster,target,spell)
    return 0;
end;

function onSpellCast(caster,target,spell)
    
    local hp = math.ceil(5 * (1 + 0.01 * caster:getMod(MOD_REGEN_MULTIPLIER))); -- spell base times gear multipliers
    hp = hp + caster:getMerit(MERIT_REGEN_EFFECT); -- bonus hp from merits
    hp = hp + caster:getMod(MOD_LIGHT_ARTS_REGEN); -- bonus hp from light arts
    
    local duration = 75 + caster:getMod(MOD_REGEN_DURATION);
	
    if (caster:getEquipID(SLOT_BODY) == 14502 or 15089) then
        target:addStatusEffect(EFFECT_REGEN,6,0,75);
    end	

    if (caster:hasStatusEffect(EFFECT_COMPOSURE) == true and caster:getID() == target:getID()) then
        duration = duration * 3;
    end

    duration = calculateDurationForLvl(duration, 21, target:getMainLvl());

    if (target:hasStatusEffect(EFFECT_REGEN) and target:getStatusEffect(EFFECT_REGEN):getTier() == 1) then
        target:delStatusEffect(EFFECT_REGEN);
    end

    if (target:addStatusEffect(EFFECT_REGEN,hp,3,duration,0,0,0)) then
        spell:setMsg(230);
    else
        spell:setMsg(75); -- no effect
    end

    return EFFECT_REGEN;
end;

**Comment by wrenffxi** [comment]
I'm not following.  The code that's current in DSP works fine from what I can see.  I think you've got an older version of the code base.

**Comment by takhlaq** [comment]
edited your comment with code tags to help make it more readable

**Comment by dwn134** [comment]
you are correct @wrenffxi  seems like we are using an older version that doesnt have this implemented yet. just tested on newest version

**Comment by TeoTwawki** [comment]
this is why updating should be done via `git pull` and mixing files from different revisions is a no-no.

leads to bugs that don't exist in the project
