### ISSUE TITLE
Moving to Discord

### ISSUE THREAD

**Issue by takhlaq** [DarkstarProject/darkstar#3942]
switching from irc to discord

get the client here https://discordapp.com/download
our discord server https://discord.gg/4dgAzfC

created an issue for those who don't frequent the forums or missed the readme update

**Comment by Ninjistix** [comment]
shouldn't the irc info be removed from the README.md (to avoid the confusion of people going there)

**Comment by TeoTwawki** [comment]
It will be when irc is turned off. for now both are present while we get everyone moved.

**Comment by tagban** [comment]
Sad that we didn't go to Slack instead. But glad to be out of IRC. Why are the forums/wiki down?

**Comment by teschnei** [comment]
Whasf having issues currently, they should be back up eventually

**Comment by TeoTwawki** [comment]
slack sux


-_ducks and covers_-

**Comment by tagban** [comment]
I guess it sucks if you like website integration, or tons of other service integration. Discord is a copy of slack but with gamers in mind. Slack is mostly for development teams, Discord also has the child porn thing going on right now so been avoiding it for that reason.

**Comment by TeoTwawki** [comment]
slack was slow as hell when I tried it. discord gave me no probs other than (until recently) non adjustable font

**Comment by Cloudef** [comment]
There doesn't seem to be working discord plugin for weechat atm.

**Comment by TeoTwawki** [comment]
Reminder: We still need to kill the github notifications for irc before we shut down the IRC channel completely..still like 8 or 12 ppl or so idling in it.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/9598c7bba8063920317d712fe99bc4426f3d16b7
