### ISSUE TITLE
Ancient magic elemental resist debuff missing

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#3945]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170707_0

**_Server Version_** (type `@revision` in game) **:**
8dd70aa

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Cast ancient magic, tier I or tier II.

Expect elemental resist debuff to be applied. Does not appear to do so. Looking at ancient magic spell lua files, does not appear to have code to apply status effect. Only appears to have a call to apply the direct nuke damage. Compared with ninjutsu elemental nuke spell lua files, which do have a call to apply status effect.

**Comment by Hozu** [comment]
I imagine they weren't included because the resist debuff values aren't known. Or are they?

**Comment by Hozu** [comment]
A quick look at BG wiki states that AM I is -30 resist for 10s, though it doesn't list if it's affected by the spell being resisted or not. It doesn't have a resist amount or duration for AM IIs unfortunately.

**Comment by xipies** [comment]
A few pages below listing -30 for 15s and being identical to ninjutsu. Although, this could just be one big echo chamber (the repeated info).

http://ffxiclopedia.wikia.com/wiki/Resistance
http://ffxi.allakhazam.com/forum.html?forum=263&mid=1142911918147289979&h=50
http://ffxi.allakhazam.com/forum.html?forum=259&mid=11503938669557970
http://www.ffxionline.com/forum/ffxi-game-related/race-job-type-q-a/blue-mage/68200-haste-vs-refueling/page2

**Comment by Hozu** [comment]
I wouldn't be surprised if it was the exact same as for Ninjutsu nuke debufs. Shouldn't be too difficult to verify on retail if needed.

**Comment by TeoTwawki** [comment]
> I wouldn't be surprised if it was the exact same as for Ninjutsu nuke debufs. Shouldn't be too difficult to verify on retail if needed.

My foggy retail day memories say this is the most likely situation

**Comment by TeoTwawki** [comment]
I also tend to trust BG over other sources for hard numbers

**Comment by zynjec** [comment]
Seems this was added with https://github.com/DarkstarProject/darkstar/pull/4061

If there is any issues/errors with it, open another issue.
