### ISSUE TITLE
Unable to trigger Moogles

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#3956]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170707_0

**_Server Version_** (type `@revision` in game) **:**
 c4e8298

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
since 03af4c3 it's no more possible to interact with moogles, probably related to this:
https://github.com/DarkstarProject/darkstar/blob/master/src/map/zone_entities.cpp#L592

**Comment by teschnei** [comment]
that is the stupidest workaround...

**Comment by teschnei** [comment]
Fixed this a while ago, forgot to close

**Comment by teschnei** [comment]
a97eff6467ad9c29904f11a4faa55acd2e09f0b6
