### ISSUE TITLE
Sandoria Mission 6-1 unable to progress, Halver won't talk

### ISSUE THREAD

**Issue by kairoffxi** [DarkstarProject/darkstar#3973]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170707_0

**_Server Version_** (type `@revision` in game) **:**
[d428456](https://github.com/DarkstarProject/darkstar/commit/d428456385e41c5120155badf126d8c8c1981d88)

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Started Mission 6-1 with Sandoria gate guard.
Current Sandoria Mission is Leaute's Last Wishes (6-1).
When selected, Gate guard says finish current mission first.
Go to Chateau d'Oraguille and Halver does not respond at all leaving no way to continue the mission.
Dreamrose in West Altepa does not spawn Cactaur.
Verified I do not have Dreamrose key item.
Chalvatot does not respond or complete the mission.

My MissionStatus value somehow was set to 9 according to the issue I opened at LegionDark.
https://github.com/LegionDark/Issues/issues/1559#issuecomment-318881366

**Comment by KnowOne134** [comment]
can close, i found no issues doing the mission
![image](https://user-images.githubusercontent.com/35616771/61003494-b3615d80-a329-11e9-8bc5-21ea9de56688.png)

**Comment by KnowOne134** [comment]
finished rest of mission just to be sure, all works

**Comment by TeoTwawki** [comment]
_HALLLLLVERRRRRR!!!!!_

@KnowOne134 are they playing on your server? for all I know there is a random npc out there for some other mission mistakenly overwriting their variable. [Coz that does happen sometimes.](https://github.com/DarkstarProject/darkstar/commit/202c612f35752439cf3c0d173335f9e2aac0ee9c#diff-72074758686508312607ea885f718f33L28)

**Comment by TeoTwawki** [comment]
OH. lol Legion...

**Comment by TeoTwawki** [comment]
Here Iw as mistaking this for a recent issue! nvm

**Comment by KnowOne134** [comment]
Just reading issues and doing what I can. Testing

**Comment by TeoTwawki** [comment]
appreciated, I was derping.
