### ISSUE TITLE
Bibiki Bay to Purongo Isle Boat Double Ticket Ride

### ISSUE THREAD

**Issue by Raelious** [DarkstarProject/darkstar#3980]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170707_1

**_Server Version_** (type `@revision` in game) **:** Revision: d428456385e41c5120155badf126d8c8c1981d88

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

This has happened a couple times where if you have 1 ticket left when boarding the boat, it will often times charge the player twice for the ride. If will allow you passage onto the Manaclipper but when the boat reaches this destination it will kick you off at the start of Bibiki Bay/Buburimu. Often seems to happen more often when the boat is claiming to take you to a different isle, and since all rides always take you to Puronogro Isle may be causing this issue? Has happened a total of about 3 times in the last couple months. Also if you only have 1 ticket, there is no way to cancel you tickets and re-buy 10 tickets, so if you board with 1 ticket and it charges double you're kinda SOL.

[/LegionDark/Issues/issues/1558](https://github.com/LegionDark/Issues/issues/1558)

**Comment by wrenffxi** [comment]
assume this was fixed in manaclipper rewrite. cannot replicate.
