### ISSUE TITLE
Altiret - Port San d'Oria - Quest: "The Pickpocket" syntax error

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#3982]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170707_0

**_Server Version_** (type `@revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**When completing the quest "The Pickpocket" in Port San d'Oria and obtaining the item it says, "Access Granted" instead of "Item obtained".

It's trivial but I fixed it on my server already by changing line:
97         player:messageSpecial(6403, 16667);
to:
97         player:messageSpecial(ITEM_OBTAINED, 16667);
which properly references the TextID file and works as expected.

Line 38 also bypasses the referenced TextID file but I'm not sure which message to reference so I just changed to:
38         player:messageSpecial(ITEM_CANNOT_BE_OBTAINED_3, 579); -- CANNOT_OBTAIN_ITEM

These changes are why my server version is unknown.

**Comment by TeoTwawki** [comment]
`_3` 

...

**Comment by TeoTwawki** [comment]
Testing which textID behaves which way, will them nuke 2 of 'em out of existance when I am done.

**Comment by TeoTwawki** [comment]
..so turns out there are ***five*** of that message.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/85a1df78ca22d5db87e81e4915d10d7dcdbd9d31
