### ISSUE TITLE
Fotia Gorget and Belt have no bonus and 1% TP not loss

### ISSUE THREAD

**Issue by dwn134** [DarkstarProject/darkstar#3983]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30170707_0

**_Server Version_** (type `@revision` in game) d8cf54a5be0bfe5d0cba223b0195d5feb4636f

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior) doesnt seem to be coded at all to work

**Comment by teschnei** [comment]
I don't think either of them are obtainable (definitely not the belt, as
that's synergy), so this is not very surprising

**Comment by dwn134** [comment]
i had found where to add the id to to weaponskills.lua
function handleWSGorgetBelt(attacker)
    local ftpBonus = 0;
    local accBonus = 0;
    if (attacker:getObjType() == TYPE_PC) then
        -- TODO: Get these out of itemid checks when possible.
        local elementalGorget = { 15495, 15498, 15500, 15497, 15496, 15499, 15501, 15502, 27510 };
        local elementalBelt =   { 11755, 11758, 11760, 11757, 11756, 11759, 11761, 11762, 28420 };
but i dont know where the next step is to check for ws properties for that id

**Comment by dwn134** [comment]
Actually i dont think weaponskill.lua is even being used. I tried adding this gorget to na avil and then i adjusted the number of the working one and had no change so i deleted the entire script and the ws still work the same even the bonuses from the other gorgets

**Comment by teschnei** [comment]
Global scripts are only loaded once and then stay in memory until the
server is restarted or you manually unload it using require

**Comment by TeoTwawki** [comment]
Use the `reloadglobal` GM command to attempt reloading a global on the fly, when needed.

**Comment by dwn134** [comment]
Tha ks i got the acc and damage coded for it and works. Just dont have the 1% no tp use now. Didnt know about not being able to change this file while in game. I know npcs and effects and spells could

**Comment by dwn134** [comment]
its coded now, and closing
