### ISSUE TITLE
Summoner - I can hear a rainbow - Crash

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#3984]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170707_0

**_Server Version_** (type `@revision` in game) **:**unknown dl 8-15-17

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**When doing the SMN job quest "I can hear a rainbow" server crashes when getting light cutscenes.

I've been looking at this pretty much all day and so far I've been able to get all the cutscenes working perfectly unmounted IF i comment out all of the code regarding the 'fixChocoboBug' in the icanheararainbow.lua. Doing this however, does make the server hang when attempting to get a cutscene while riding a chocobo. I've noticed that part of the 'fixChocoboBug' function references a status effect called "EFFECT_CHOCOBO" which does not exist in the require file "scripts/globals/status" I don't know if this is why that function isn't working but there is an "EFFECT_MOUNTED" which exists in the status file. I tried to change the 'fixChocoboBug' function to include "EFFECT_MOUNTED" but I didn't get it working that way either.  My programming skills are still limited for the time being.

**Comment by TeoTwawki** [comment]
that function has never really worked right. I caused the wrong effect name thing tho.

**Comment by Wiggo32** [comment]
I see you changed the EFFECT in the icanheararainbow.lua file but that doesn't fix the issue. I had previously stated I already tried that and it didn't work.

**Comment by TeoTwawki** [comment]
issue auto closed from me referencing it in commit. but the chocobo thing has never worked right leads to stuck cs when on choco works fine for me when not

anyway issue titles said crash. crash is fixed. i can reopen this or we can make a new one for stupid choco stick thing still not working. I'll be back soon.

**Comment by TeoTwawki** [comment]
#3986

**Comment by Wiggo32** [comment]
nope, I don't crash anymore... that part is fixed indeed. just hangs now. I am continuing to work on it.
