### ISSUE TITLE
Magic Evasion "default ranking" minor (major?) conflict between scripts/globals/magic.lua and src/map/utils/mobutils.cpp

### ISSUE THREAD

**Issue by Whitechaser** [DarkstarProject/darkstar#3985]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** **:** 30170707_0

**_Server Version_** **:** Unknown

**_Source Branch_** **:** master

**_Additional Information_** **:**
Previous discussion I found: https://github.com/DarkstarProject/darkstar/pull/2080
Wherein the magic evasion equation for mobs was changed from its old, impossible-to-land-past-level-83-ness to a function that scales a "default rank" by level. The current code is a little cleaner compared to the original commit but is logically the same.

https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/magic.lua
At the very bottom there is an old function used to print out magic evasion info for all levels 1 through 75.
line 1238: The documentation states that this the default monster magic evasion rank is D.

The following can be ignored and the issue closed if the documentation was just a typo and really meant that the default should be C.

line 1239: magicEvaRank is assigned a value of 3
Now this particular variable doesn't exist outside of magic.lua, but it is passed to /scripts/globals/utils.lua in what I presume was a preliminary testing of the code before it was ready for official use in /src/map/utils/mobutils.cpp. The functions getMobSkillLvl() in utils.lua and getBase() in mobutils.cpp are the same, more or less.

In magic.lua the function responsible for calculating magic hit rate, getMagicHitRate() extracts MOD_MEVA from the target (line 402), added to the mob in mobutils.cpp (line 502) and calculated by the function getMagicEvasion() (line 86) by passing it to getBase() as I mentioned above. In here the "default rank" mEvaRank is again assigned a value of 3.

If you scroll down to getBase() (line 160) you will find that a value of 3 corresponds to a rank of C. The conflict is either critical or insignificant now.

What was the intended default rank? D (a value of 4) or C (a value of 3)? Since the actual value that's in there is 3, it's much easier to imagine that the documentation simply had a typo. However, the logic used in calculating magic evasion in that old print function at the bottom of magic.lua is the precursor to the logic in mobutils.cpp. If it was really supposed to be 4 and the hypothetically incorrect value of 3 was propagated when it got copied into mobutils.cpp, then all mobs are likely more resistant to nukes and other spells than intended.

Gameplay-wise, the difference isn't noticeable for me. 
**HOWEVER**, I play a ridiculously well-geared BLM on a 75 cap server. (Our Claustrum has a server-specific Elemental/Divine/Enhancing/Enfeebling/Dark/Summoning magic skills+10 along with elemental magic accuracy +30, and a bunch of other OP effects like Iridiscence and all stats +7.)
I cannot say whether the D to C accidental increase, if it is one, impacts resist rates for other jobs.

THEN AGAIN, the documentation could have just been a typo.

**Comment by teschnei** [comment]
It's supposed to be C

**Comment by Whitechaser** [comment]
Right then. Sorry it got this long.
