### ISSUE TITLE
fixChocoboBug() in \scripts\globals\icanheararainbow.lua appears to be useless

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#3986]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30170707_0

**_Server Version_** (type `@revision` in game) **:**
8bb517f3fb554079394940701e38ebf481414d95

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
This function
https://github.com/DarkstarProject/darkstar/blob/8bb517f3fb554079394940701e38ebf481414d95/scripts/globals/icanheararainbow.lua#L146
does not seem to work as intened. CS usually just hangs forever.

***Work around*** **: Dismount chocobo and re-zone**

***Additional note*** **: mounts don't exist yet but in the future we made need to take animation 85 into account as well**

**Comment by Wiggo32** [comment]
I have been testing various aspects of this code to see if I can figure anything out about it. So far I haven't been able to get ANY cutscenes to work while mounted (using the !cs command) but work just fine unmounted. I'm thinking that means any fixes need to be applied before the cs triggers. I've been trying to remove the mounted status effect entirely before playing the cs but so far haven't been able to figure out where that happens. I was looking in the various zone.lua files, if there is someplace else I might look I would appreciate just a slight 'nudge'. My thought process was to remove the effect, play the cs, then put the effect back on. If there's anything anyone else thinks I should try (even if it's tedious) I will do it. For now, I'll keep trying things.

**Comment by teschnei** [comment]
most likely what you can try is forcing the animation to 0 if a cs has been
decided upon in zone_in.cpp, but that's basically exactly what the
icanheararainbow.lua fix was doing.

Possible that a further entity update is breaking it... not sure

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5209
