### ISSUE TITLE
Can learn warp II before lvl 40

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#3987]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170707_0

**_Server Version_** (type `@revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Tested on 2 different server installs on 2 different machines with the latest git pull. BLM lvl 36 was able to learn Warp II which is a lvl 40 spell. The spell was greyed out and unusuable but I shouldn't have been able to learn it until lvl 40 in the first place. Haven't checked on where to look to fix this yet. If anyone wants to point me in the right direction I will gladly do the work.

**Comment by Hozu** [comment]
You were able to use the scroll to learn the spell? What does the client say the level for the scroll is? I can't remember if the client prevents you from using a scroll that you're too low of a level to learn, but it would prevent a player from casting the spell regardless of what level the spell is set in the database.

**Comment by Hozu** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/sql/spell_list.sql#L319

Oh, I see. In the blob there, each job uses two digits (in hex) in order of jobs. Since it's only BLM, this one is easy to see. It's set to 0x24, or level 36 BLM. Change the 24 to 28 and that should fix it.

**Comment by Wiggo32** [comment]
Thank you for finding that hex code value and pretty much solving this issue for me altogether. 

Yes, I was able to use the scroll to learn the spell at level 36.  The client says the level for the spell is 40 as it has always been as far back as I remember playing. FFXIclopedia also has it listed correctly as 40. In retail play, one is not supposed to be able to learn spells until they have attained the level requirements of said spell.

**Comment by TeoTwawki** [comment]
no pull request?

sniffle hozu dont lurve us no more guys :sob:

**Comment by Hozu** [comment]
No testing environment, sorry.

I wonder if you can just send the relevant packet(s) for casting the spell and be able to cast it at a lower level than the client specifies if the DB has the spell set to a lower level than the client.

**Comment by TeoTwawki** [comment]
yeah client stops it at menu only
