### ISSUE TITLE
Quest Warding Vampires required item missing from mob drop pool

### ISSUE THREAD

**Issue by Whitechaser** [DarkstarProject/darkstar#3988]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** **:** 30170707_0

**_Server Version_** **:** Unknown

**_Source Branch_** **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Here's the quest info: ffxiclopedia.wikia.com/wiki/Warding_Vampires

Orcish Cursemaker dropIDs for Fort Ghelsba, Yughott Grotto, and Davoi (in order):
2586, 2587, 2588

bulb of shaman garlic itemID:
1018

Drop rates from http://ffxiclopedia.wikia.com/wiki/Orcish_Cursemaker:
Fort Ghelsba: ???, but probably similar to the other two
Yughott Grotto: 14.1%
Davoi: 13.4%

Could someone add them please? The rest of the quest seems to be fully implemented.

**Comment by Hozu** [comment]
http://ffxidb.com/items/1018 IIRC the rates from ffxidb are more accurate

**Comment by Whitechaser** [comment]
Oh! Thanks! I'll look there from now on.

**Comment by Wiggo32** [comment]
I've updated the mob_droplist.sql to include the item 1018 in the three dropId's corresponding to the specific zones the Garlic is supposed to drop in. Please forgive me but I am kinda new here and I am not sure how to do a Pull Request. Or how to submit the new updated file for review.

**Comment by Whitechaser** [comment]
Only recently learned how to submit stuff. Redoing this as it seems you didn't get back to it. Cheers for newcomers!
