### ISSUE TITLE
OP teleporter NPC 'Lobho Ukipturi' -buburimu -doesn't spawn

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#3994]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170707_0

**_Server Version_** (type `@revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**Go look at the outpost in Buburimu when either windurst or bastok has control. (i'm not sure what sandy control looks like) but the NPC isn't there and there is a permanent beastflag sitting on top of the signet guy.

**Comment by Wiggo32** [comment]
Any chance you could tell me what file to look for this in and I'll make the fix and submit PR?

**Comment by TeoTwawki** [comment]
id in lua global not matching id in nps list table because they ate client veraion dependant just wait till project catches up to latest retail version and well fix it then

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/f17316a18da25af0adddf6e1d51ec36309cb1c90?w=1
