### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by o0Persefone0o** [DarkstarProject/darkstar#4003]
**_I have: **

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** 30170728_2**

**_Server Version_**have no answer trying to get it on game **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
![21081389_10213454391656331_2137875012_o](https://user-images.githubusercontent.com/30010790/29583836-600482a2-8747-11e7-9108-ad9dd90758f6.png)
I
![21035075_10213454308294247_2063871947_o](https://user-images.githubusercontent.com/30010790/29583832-5ab8ddf2-8747-11e7-9c0c-b3d8175da83a.png)
 have to sorry because english its not my main languaje, i try to explain, i log first time today and pol told me a mistake POL 3303 and i think im gonna have to actualize... i try to log with other char and it get into the select menu, but have no vanadiel pictures passing or my char selection, but i can select, so i select my char and get into legion, but i get a grey screen, but i have access to everything, i can select ppl, follow ppl, i do zone, but i keep a grey screen. i actualize FFXI (doing chek files) but dsnt fix it, a friend told me maybe my video card get damage... but i run other games without problems_**

**Comment by zynjec** [comment]
Are you using an Intel GPU?

I had this happen on a laptop running Win10 after updating to Creators Edition, only fix I found was uninstalling the update.

**Comment by takhlaq** [comment]
you can try rolling back to another driver, though as this is not a server issue i will be closing this issue
feel free to hop in discord for support or post on forums
