### ISSUE TITLE
Auction House not returning Gil for sold items

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4004]
**_I have:_**

- [x ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `@revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**Listed 2 stacks of Giant sheep meat for 1 gil each. Bought one back for 1 gil, received the items. Bought other stack with different character for 2,196 gil, received the items. Both sales show up in item history. No gil was delivered to seller.

**Comment by teschnei** [comment]
No errors in either the game server or search server log?

**Comment by TeoTwawki** [comment]
if you have no error messages, try rerunning your triggers.sql

..have seen this happen before with missing/damaged triggers so the delibery never went off.

**Comment by Wiggo32** [comment]
so strange. the trigger was missing. though the other triggers were there (account_delete, char_delete). I reran the sql and now there is a trigger for auction_house_buy...

**Comment by TeoTwawki** [comment]
I make a habit of rerunning my triggers anytime I reimport any tables just in case

**Comment by Wiggo32** [comment]
well, i feel silly. tested and it works fine now.

**Comment by teschnei** [comment]
Did it work and then randomly stop working? Or that was the first time you tried?

**Comment by Wiggo32** [comment]
No, it actually never worked for me but I didn't create an issue until after I rebuilt and updated client. I've never actually checked the triggers though until it was mentioned to me. I only ever checked for the two triggers that were mentioned in the darkstar building the server tutorial. so, pretty much my bad...
