### ISSUE TITLE
Bastok Flag in Valkurm Dunes when Windurst has control. L-11

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4005]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `@revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Just run to Tebubu, W.W. at L-11 when windurst has control of the region and you'll see him standing next to the flag for Bastok. might be related to:
https://github.com/DarkstarProject/darkstar/issues/3994

**Comment by TeoTwawki** [comment]
its the same thing. Also of note your client is newer than the current darkstar is set up for. So its normal for you to see this happen. Also you *may* see wrong text strings, cs event hangs ir crashes..And its not a darkstar code bug, just mismatched client revisions.

**Comment by Wiggo32** [comment]
i've seen these outpost issues since i first installed with the older client last month. the outposts haven't been right from when I first started my server.

**Comment by TeoTwawki** [comment]
yeah not surprised. Thats why your other issue you linked here is still open - its the same answer. We have a tool we run that gets *most* of them. Sometimes things get missed, and usually just like now by the time we get a report about it its already time for the next client update anyway so may as well fix them at the same time.

**Comment by Wiggo32** [comment]
ahhh, i thought maybe it was just some painstaking manual entry of id's that no one wants to do because its so mundane and boring. which i would have volunteered for because i guess i like to torture myself.  =)
