### ISSUE TITLE
Zi'Ghi Boneeater is simple pop.

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4009]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30161227_1

**_Server Version_** (type `!revision` in game) **:**

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Zi'Ghi Boneeater should be a lottery pop among Veteran Quadav with a 1 hour minimum respawn time. See here: http://ffxiclopedia.wikia.com/wiki/Zi%27Ghi_Boneeater

**Comment by TeoTwawki** [comment]
in 400 kills or so, I only veer saw him in one pos so I'm going to place him there. Thought I adjusted his pop forever ago must have forgot him.

**Comment by davismj** [comment]
He pops, but he's not doing the lottery pop behavior. Same with all the other NMs in Palborough Mines.

**Comment by TeoTwawki** [comment]
yeah. Its just I have this branch I worked on like 50 NMs in to make them retail..and I never remembered to finish and send them all in. 😊

**Comment by TeoTwawki** [comment]
Can you try update and tell me if I missed anything? made 2 commits.

**Comment by TeoTwawki** [comment]
ba948fcaa77b53c044ed87a1f8be12a625162ce0
