### ISSUE TITLE
Too much Platinum Ore in Palborough Mines

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4013]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**When mining in Palborough Mines, Platinum Ore is the MOST abundant material to come out of there. Checking the mining.lua it is also the most heavily weighted of all the drops. I'm pretty sure we need to move that '0' on the end to the front but I don't know what exact number will make everyone happy otherwise I would have submitted a PR.   

Gusgen Mines also appears to have unreasonably high drop rates for Gold and Mythril ore as well.

**Comment by TeoTwawki** [comment]
lmao

**Comment by TeoTwawki** [comment]
review? what reviews?
plat ore is 8/823 on the old wiki, no data on bg no data on ffxidb

xD

**Comment by TeoTwawki** [comment]
Checking the gold and mythril real quick before I coma for the evening

**Comment by TeoTwawki** [comment]
aaand fix'd

**Comment by TeoTwawki** [comment]
Ifrit's Cauldron was handing out fire ore too.

**Comment by TeoTwawki** [comment]
```lua
-- Note: All drops are weights, these are /not/ percentages.
```
Yet all the item comments have a % to confuse editors. I just stuffed them at the percent instea dof doing math, so they are likely less than stated.
