### ISSUE TITLE
Rank 2 mission BCNM no cutscene when dead & funky magic menu

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4020]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** When fighting the BCNM for "Rank 2 Final Mission" (Windurst Mission 2-3) at Waughroon Shrine the battle is capped at level 25, though all of the players learned spells appear in the magic window. Only the spells available at lvl 25 should be visible. Upon completion of the fight, if a player happens to be dead they will not progress/get cutscene even after raising.

**Comment by TeoTwawki** [comment]
Just a note for anyone that wants to deal with bcnm shiz: proper behavior should be get cs anyway then player does the dead-fall animation *again* after spawning at the BCNM exit.

**not it!** *runs and hides*

**Comment by Jessland86** [comment]
This is an issue with **every** BCNM fight when a person dies and the battlefield is finished with them dead. 5-1 is notorious for killing people and people people not getting credit for the win because they are dead.

**Comment by KnowOne134** [comment]
can close this issue all is resolved now, magic/abilities lists scale, and dead people get credit now
