### ISSUE TITLE
Ice spikes doesn't paralyze

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4021]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**Been fighting Ice elementals, Ghosts, and Skeletons- Too Weak through Very Tough. Have not recieved the status affliction "paralyze" at all after continuously receiving damage from mobs Ice Spikes effect.

**Comment by TeoTwawki** [comment]
Fixed. The line calling the function got lost in the AI refactor I think.

**Comment by dwn134** [comment]
what was the fix btw? i cant seem to find it

**Comment by TeoTwawki** [comment]
b1cfe9a6a3477e810da36f006f00c23bbdc8ab6a
and
da3fc081276af9e4009f4600ddd393cd59185953
