### ISSUE TITLE
Lumbering Lambert Respawn Window

### ISSUE THREAD

**Issue by Delkathus** [DarkstarProject/darkstar#4030]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170728_2

**_Server Version_** (type `!revision` in game) **:** Unknown

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Lumbering Lambert's window is currently set to opening anywhere between 1-8 hours. The window is to open after 1 hour of tod and should be available for lotto. It has a 5% spawn chance which why it can take up to 12 hours to spawn.

But the window shouldn't start on average 4-6 hours after last kill when it's to open 1 hour after. There shouldn't be a window range.

Sauce: http://ffxiclopedia.wikia.com/wiki/Lumbering_Lambert
»» [Minimum respawn time is 1 Hour from last Time of Death.]

**Comment by wrenffxi** [comment]
Can be closed.  Was fixed by #4747.
