### ISSUE TITLE
Manaclipper... the boat to nowhere.

### ISSUE THREAD

**Issue by Yatsumoto** [DarkstarProject/darkstar#4033]
Date of occurance: 9/1-3/2017
Version: 30170707_0
Revision: f559cc9dc94c68fd8b64b75f8afbfef8be92f3eb
I don't know what stable or master refers to, but I'm playing on OldSchool Server, if that helps.

Reason why this issue is important: CoP cannot be completed without much frustration. It's doable, but a royal pain in the butt just for a couple of short required cutscenes on Purgonorgo Isle. 

There are other quirks with the boat, so I'll start with the most important. When you try to go to Purgonorgo Isle, the boat keeps spitting you back out at the Bibiki Bay zone entrance from Buburimu. I'm told this worked correctly at one point. I've only been playing for a few months so I can't say. All I know is I only made it Purgonorgo on 1 out of 5 tries. GM had to drag me to Purgonorgo after 4 failed attempts on the first cutscene. By some miracle, it worked two days later on the first try for the final cutscene.

Other issues.

Boat leaves without you. Depending on where you're standing on the manaclipper when it departs, it will leave right out from under you, allowing you to walk around over the water and be unable to get back on the dock. This happened when I was standing on the bow.
![yatsumoto_2017 09 01_192124](https://user-images.githubusercontent.com/31595118/30005189-71973f96-90a2-11e7-86af-79905de760f0.png)

If you are standing on the side where the elevation is lower when it departs, you'll be under the boat during the trip. If you are standing in the middle with the raised elevation when it departs, you'll be standing on the boat correctly. This seems to be the only are you can stand without issue.
![yatsumoto_2017 09 01_194856](https://user-images.githubusercontent.com/31595118/30005194-928ab778-90a2-11e7-8bf3-e29b392b2abb.png)
![yatsumoto_2017 09 01_195026](https://user-images.githubusercontent.com/31595118/30005200-a07afb18-90a2-11e7-90dd-91d9d1eb574b.png)

When the boat is docked at Purgonorgo, it looks like this. Fortunately, it doesn't require you to walk off the boat to the dock. I didn't try to board from this side. I just warped after the cutscene.
![yatsumoto_2017 09 03_121610](https://user-images.githubusercontent.com/31595118/30005224-3f020f4c-90a3-11e7-96c1-d6d013f5ba77.png)

**Comment by wrenffxi** [comment]
fixed by manaclipper rewrite
