### ISSUE TITLE
Nexus Cape to Mog House Crash

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4034]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Crash happened when nexus cape resolved while party leader was in mog house or in transition to exiting mog house. 
![nexus crash](https://user-images.githubusercontent.com/30469395/30005773-7ad7d216-90af-11e7-95ab-a49ed5a69d7c.jpg)

**Comment by teschnei** [comment]
5d390127d3f4043e4ebae3af9cc2a6e2fed44eb8
