### ISSUE TITLE
Drk dread spike don't work 

### ISSUE THREAD

**Issue by lion85xx** [DarkstarProject/darkstar#4040]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `!revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by teschnei** [comment]
Issue template not filled in
