### ISSUE TITLE
!delquest / !addquest don't like 4 as a logID

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4041]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
!delquest and !addquest both give an "invalid logID" error when attempting to use '4' (the ID for OTHER_AREAS) as a logID.

**Comment by DFPercush** [comment]
See also [PR #4150](https://github.com/DarkstarProject/darkstar/pull/4150) - completequest was overlooked here

**Comment by metalfiiish** [comment]
Issue can be closed as it was resolved in PR #4150
