### ISSUE TITLE
Fully charged Water Tank won't list on AH

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4044]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When attempting to list the fully charged Water Tank (item 13683) you get the error:
"Partially depleted items cannot be put up for auction"

**Comment by teschnei** [comment]
"searched existing issues" :thinking: 

https://github.com/DarkstarProject/darkstar/issues/534
