### ISSUE TITLE
Aquaveil can come off from basic attacks

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4049]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Aquaveil randomly comes off during battle before it is supposed to. This will usually happen after a basic attack from a mob, but sometimes happens after a mob weaponskill also.

**Comment by teschnei** [comment]
that's how it's supposed to work, yes

**Comment by TeoTwawki** [comment]
https://www.bg-wiki.com/bg/Aquaveil
