### ISSUE TITLE
MNK AF temple gloves

### ISSUE THREAD

**Issue by genesius149** [DarkstarProject/darkstar#4062]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

30170728_2
**_Server Version_** (type `!revision` in game) **:**

b010e4eb8ce01c35667706a8fd452f821b92aff
**_Source Branch_** (master/stable) **:**

i don't understand what this is master/stable?
**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Hey there, Temple Gloves do not give the +5.5% attack bonus to boost as they should, if anyone could look it up please^^? 
(also temple gaiters and crown do not give the +10 bonus to evasion and accuracy but that's less of an issue for endgame)

here are screenshot of me using boost with only weapon equiped and one with gloves, other without, attack is same on both minus the str bonus from temple gloves.

http://i.imgur.com/VLHbs9O.jpg
http://i.imgur.com/jPudzjC.jpg

**Comment by zynjec** [comment]
Seems to be applying bonuses fine on master.

Base Attack: 251
Boost without AF: 281
Boost with AF: 298 (296 without STR bonus), a 5.5% bonus.

Do you have them equipped before boosting?

**Comment by genesius149** [comment]
yes have them equiped before

**Comment by genesius149** [comment]
master is like main server? so means if i'm like on era, code is there but not scripted only?

**Comment by zynjec** [comment]
Master/Stable refers to the branch of Darkstar you're using.

If you're playing on Era, contact them they've done something to break this.

**Comment by genesius149** [comment]
oki^^ can close this ticket here I guess then. tyvm
