### ISSUE TITLE
Taisaijin doesn't spawn

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4065]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
looks like it's coded to perform a check onmobRoam to spawn the NM from one of the Taisai but I've been watching it for 5 days and it hasn't done anything. No new server variables, no mobaction, no nothing.

**Comment by Hozu** [comment]
Does onMobRoam run for mobs that are in zones that have no players? I know that mobs don't move around at all when there are no players in the zone.

**Comment by TeoTwawki** [comment]
@hozu It *should* update the 1st tick that happens after the zone "resumes".

**Comment by Hozu** [comment]
Hm, you're probably right.

I wonder what the mob action of Taisaijin is when it's waiting to spawn. Is it really ACTION_NONE?
