### ISSUE TITLE
Gallijaux and Joulet missing carp item IDs in quest dialogue

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4066]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Need to put 4401 and 4289 after the cs that starts the quests for both npcs. This should be in the function onTrigger block so it would be something like:

player:startEvent(304,4401,4289);

and the same thing for the other one.

**Comment by metalfiiish** [comment]
This was resolved in the #4297 PR. Along with other missing features from those NPC's.
