### ISSUE TITLE
Lamps in lower jeuno have wrong message ID when lighting them

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4067]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When lighting the lamps in Lower Jeuno the message ID for every lamp is wrong. It should be 7244 which indicates how many lamps you have remaining thus the need for the 'lampsremaining' variable in the code. There should also be an additional if in there to tell us when all the lamps have been lit like it does in retail and has a unique message for. So it should look something like:

```
function onEventFinish(player,csid,option)
    if csid == cs and option == 1 then
        -- lamp is now lit
        GetNPCByID(lampId):setAnimation(ANIMATION_OPEN_DOOR);

        -- tell player how many remain
        local lampsRemaining = 12;
        for i=0,11 do
            local lamp = GetNPCByID(lampIdOffset + i);
            if lamp:getAnimation() == ANIMATION_OPEN_DOOR then
                lampsRemaining = lampsRemaining - 1;
            end
        end
        if lampsremaining == 0 then
            player:messageSpecial(7243);  -- All lamps lit
        else
            player:messageSpecial(7244,lampsRemaining);
        end
    end
end;
```

**Comment by TeoTwawki** [comment]
rememberme telling you about client version being potentially the cause of another issue just like this?

**Comment by TeoTwawki** [comment]
and yeah it does need moved to textids.lua

**Comment by Wiggo32** [comment]
its been doing this since i installed with last months client version

**Comment by TeoTwawki** [comment]
i hate having to try and github from mobile

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/d26b455a839e359b5140d0ec2665bbf991bb3380?w=1#diff-5373d79b4d850d6246dea896af772f4fR17
