### ISSUE TITLE
Chests/Coffers don't share gil/loot with party

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4079]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Per retail, Treasure Chests and Coffers are supposed to share gil and loot with party members within the same zone as the player who opened it.

**Comment by Hozu** [comment]
There's a lua binding to add an item to a treasure pool seen in the addtreasure command here: https://github.com/DarkstarProject/darkstar/blob/master/scripts/commands/addtreasure.lua#L49

Dunno if there's anything like that for gil.

**Comment by Wiggo32** [comment]
I have chests all sharing gil on my personal server but not loot. (haven't figured that out yet) Not sure if it's done the way in which it would be acceptable for dsp (or i would have submitted a PR) but I basically had to alter the Treasure_Chest.lua for every zone that has chests/coffers.

**Comment by TeoTwawki** [comment]
I'll write a lua (or binding, havent looked yet to see which i need) function that does the same split the core one does for mob dropped gil, then all chest/coffer can call that from global allong with addtreasure

**Comment by TeoTwawki** [comment]
now that I think about it retail doesn't have an out of range for gil drops, as long as same zone, yeah? should be able to correct that and then use same thing

**Comment by Wiggo32** [comment]
as long as party members are in zone, they all receive gil (unless it's been changed recently). And I have an lua function that distributes the gil to the party if you want that?

**Comment by TeoTwawki** [comment]
was referring to when someone in dsp changed the mob gil drop to exclude ppl oyt of exp range which I think is incorrect

**Comment by Hozu** [comment]
re: the message for obtaining item/gil, is it displayed to the whole party on retail? Or just whoever opened the chest/coffer? I forget.

In any case, one would have to modify every chest/coffer script in each zone that has them - example, https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Davoi/npcs/Treasure_Chest.lua#L58 has `player:addItem(loot[2]);` - replace that with `player:addTreasure(loot[2], npc);` ...I think.

**Comment by Hozu** [comment]
Actually, doesn't the addTreasure binding display a message to the entire party anyway? If so, you can just remove the message from each chest/coffer script.

**Comment by TeoTwawki** [comment]
yeah it does :)
coz everyone gets normal lootpool msg and it just does that

**Comment by hilts-vaughan** [comment]
I'll take care of this.

**Comment by wrenffxi** [comment]
This can be closed per #5546
