### ISSUE TITLE
Various Weapon Skills are broken.

### ISSUE THREAD

**Issue by Yatsumoto** [DarkstarProject/darkstar#4080]
Client Version: 30170707_0
Server Version: c79a3f2a9b66c9ea5e34e4cb8f1c8cca6a87f268
Oldschool Server

Some weapon skill are 100% miss and return 0 TP even when stacked with Sneak Attack. There seems to be nothing common to the ones I've tested so far. I only have THF PLD SAM for testing. Another player tested some on WAR. I will update the list as I discover more.

**Ones that are broken:**
Dancing Edge
Shark Bite
Vorpal Blade
Swift Blade
Spirits Within

**Ones that work:**
Aoelian Edge
Tachi: Gekko
Tachi: Yukikaze
Raging Rush
Metatron Torment

**Comment by teschnei** [comment]
Seems to be working fine on latest.  Closing (whasf can look into his own server)
