### ISSUE TITLE
Banish(ga) spells crash server

### ISSUE THREAD

**Issue by CTOON50** [DarkstarProject/darkstar#4081]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170905_1

**_Server Version_** (type `!revision` in game) **:**588d7bf14df091ea7b42bd81860a09f8f58b0cfa

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
When any type of Banish spell (I, II, III, IV, or ga I-III) are cast, the server crashes. I notice that if the files that were recently updated are reverted to the old version the spells cast with out crashing the server but only cause 0 damage. I've tested on a fresh clone of the repository as well with the same issue.

**Comment by takhlaq** [comment]
i do remember them being a shit with my regex, looking into it now

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/cc0ac4492d2c067a6d700893f914171c48d81a20
