### ISSUE TITLE
Synthing Flint Stones Buggy

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4082]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**30170728_2

**_Server Version_** (type `!revision` in game) **:**unknown

**_Source Branch_** (master/stable) **:**master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

Alchemy lvl 50 status 'Journeyman' 
While synthing 8 flint stones from a stack of 12 to make glass fiber which caps at 61,
if the synth breaks, you will get notification that you have lost flint stones, however the stack will remain greyed out and indicate all 12 remaining. upon zoning, you have full use of the 12 flint stones to attempt synth again.

If the stones are broken up into individual stones (no stack) and placed each in its own slot for the synth, upon synth failure message and notification of losing items the stones that were reported lost are actually lost.

**Comment by TeoTwawki** [comment]
#463
#2373

**Comment by metalfiiish** [comment]
This can be closed. Fixed in patch #4286.
