### ISSUE TITLE
Can't call automation

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#4084]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
current supported

**_Server Version_** (type `!revision` in game) **:**
a2dd561b0f8540efe34fc7e328f2526cce4fadfd

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Unable to summon automation. Looks like a problem with the petType from activate.lua..?
[19/Sep] [18:57:18][1;37m[Info][0m parse: 01A | 000B 000A 0E from user: Queenvicky
[19/Sep] [18:57:18][1;36m[Debug][0m [1;36mCLIENT Queenvicky PERFORMING ACTION 09
[0m[19/Sep] [18:57:18][1;31m[Error][0m [1;31mCLuaBaseEntity::spawnPet : PetID is NULL

**Comment by teschnei** [comment]
you're gonna need to provide a dump, I cannot reproduce it

**Comment by whasf** [comment]
Was problem with (we think) character got automation between critical updates and didn't actually have one in the db, but had command unlocked.
Thanks kj!
