### ISSUE TITLE
BST jug pets respawn on zone after death

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4089]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170728_2

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Summon a jug pet
2. Fight mobs until pet dies
3. Zone
4. Grats! New pet without spending another jug.

**Comment by TeoTwawki** [comment]
BSTs everywhere crying out in despair as wiggo keeps reporting their free ride bugs 👍

**Comment by Wiggo32** [comment]
This has been fixed.
