### ISSUE TITLE
How does trust open?

### ISSUE THREAD

**Issue by woqunima123** [DarkstarProject/darkstar#4092]
I have:

 searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
 checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30170707_0

**_Server Version_** (type `!revision` in game) unknown

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior):

How to customize the signal pearl, the server is missing this, I hope to get help

**Comment by takhlaq** [comment]
please use discord for questions/discussions, github issues are for filing bug reports
you can find our discord server invite in our README
