### ISSUE TITLE
sandy mission 2-1 glitched freezes client

### ISSUE THREAD

**Issue by thenoobers** [DarkstarProject/darkstar#4101]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30170905_1** 

**_Server Version_** (type `!revision` in game) **0c16d47cd63dbba1a3db80c7c12df57144769e81** 

**_Source Branch_** (master/stable) **sandorian mission 2-1 "the rescue drill" i talked to the npc at the top road up by the wall if you came from west ronferau to la thein.  he started the quest initiating that a rescue operation was active and to go ask his colleagues about helping.  than i went into monastic cavern and talked to the npc along the left wall.  went back outside and talked to the 2 npcs on the hill path, and than to the npc right before the entrance of the cave leading to monastic cavern.  every time no matter which order i talk to all the other npcs i do not get the bronze sword.  i have even tried after talking to the npc inside monastic cavern, talking to the 2 npcs on the hill than going all the way back up to the npc by the wall and talking to him than talking to every other npc on the way back down the path. 2 people give me a response along the lines of did you find anything, nope nothing!  but the 3rd one the npc near monastic cavern says did you find anything.  next line Hey!   and than thats where it freezes from there i can still type in chat but i cannot do ANYTHING else literally.  i cant open menus i cant select other npcs or targets i cant /heal i am stuck in a dialogue screen that will not play.  i have even walked away for 20+ mins with the dialogue lock in place just to see if it was a lag or delay issue.  I am Noobers in game and in discord please reach out and help me solve this bug/glitch/ whatever the heck is going on** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **N/a**

**Comment by thenoobers** [comment]
to clarify i was very tired when i wrote this after trying to debug it myself.  im not zoning the wrong area for clarification i went to ordelles caves as needed.  was there the whole time.  currently have a friend testing from his end to see if it freezes him up as well.  please help!

**Comment by EpicTaru** [comment]
Noobers, you opened this ticket on the wrong tracker entirely.  Please close the above ticket and then re-open it under LegionDark's own specific tracker for server issues: https://github.com/LegionDark/Issues/issues
