### ISSUE TITLE
dsconnect on linux spamming log

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#4103]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Server Version_** (type `!revision` in game) **:** 
e261e52

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
dsconnect process is spamming the log and eating 100% cpu, running on linux:
```Sep 30 12:52:16 dsconnect[5207]: [Info] DarkStar - Git Revision Hash: Unknown.
Sep 30 12:52:16 dsconnect[5207]: [Info] Console Silent Setting: 0
Sep 30 12:52:16 dsconnect[5207]: [Status] The login-server-auth is ready (Server is listening on the port 54231).
Sep 30 12:52:16 dsconnect[5207]: [Status] The login-server-lobbydata is ready (Server is listening on the port 54230).
Sep 30 12:52:16 dsconnect[5207]: [Status] The login-server-lobbyview is ready (Server is listening on the port 54001).
Sep 30 12:52:17 dsconnect[5207]: [Status] The login-server is ready to work...
Sep 30 12:52:17 dsconnect[5207]: [Status] Console input thread is ready..
Sep 30 12:52:18 dsconnect[5207]: [Status] Unknown console input command
Sep 30 12:52:19 dsconnect[5207]: [Status] Unknown console input command
Sep 30 12:52:20 dsconnect[5207]: [Status] Unknown console input command
Sep 30 12:52:21 dsconnect[5207]: [Status] Unknown console input command
Sep 30 12:52:22 dsconnect[5207]: [Status] Unknown console input command
Sep 30 12:52:23 dsconnect[5207]: [Status] Unknown console input command
Sep 30 12:52:24 dsconnect[5207]: [Status] Unknown console input command
```
strace just states endless polling:
```
[pid  5989] poll([{fd=13, events=POLLIN}], 1, 500) = 0 (Timeout)
[pid  5989] getpid()                    = 5988
[pid  5989] poll([{fd=13, events=POLLIN}], 1, 500) = 0 (Timeout)
[pid  5989] getpid()                    = 5988
[pid  5989] poll([{fd=13, events=POLLIN}], 1, 500) = 0 (Timeout)
[pid  5989] getpid()                    = 5988
[pid  5989] poll([{fd=13, events=POLLIN}], 1, 500) = 0 (Timeout)
[pid  5989] getpid()                    = 5988
[pid  5989] poll([{fd=13, events=POLLIN}], 1, 500) = 0 (Timeout)
[pid  5989] getpid()                    = 5988
```

**Comment by takhlaq** [comment]
odd, on windows std::cin blocks

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/src/login/login.cpp#L136
try sticking a after that line
```cpp
std::this_thread::sleep_for(std::chrono::seconds(1));
```

**Comment by ymkc** [comment]
cpu load gone when adding the line, spamming still there

**Comment by Cloudef** [comment]
cin should block on unix as well, either stdin was set to O_NONBLOCK by some process, or stdin is connected to something weird, or something is outputting constantly on your stdin.
>[Status] Unknown console input command

**Comment by ymkc** [comment]
will take a look, but there is not much else running on the vm

**Comment by Cloudef** [comment]
do you run the server in background, from service? This code assumes that it's attached to terminal.

**Comment by ymkc** [comment]
running it through systemd, but systemd keeps it attached/in the foreground

**Comment by ymkc** [comment]
guess this is related to a systemd special behaviour, from its man page:

```... standard input will be connected to /dev/null, i.e. all read attempts by the process will result in immediate EOF```

just add an eof check?

**Comment by takhlaq** [comment]
i dont have a linux box to test but if either of you could pr that and test it works, sure

**Comment by Cloudef** [comment]
Yeah it should check EOF or isatty. Systemd IIRC also has option to attach pseudo tty, if you don't want to send patch.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/pull/4106
