### ISSUE TITLE
disable_gear_scaling half broken

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#4104]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30170905_5

**_Server Version_** (type `!revision` in game) **:** 
e261e5284

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
- set disable_gear_scaling to 1
- equip lvl 40+ gear and make sure /stylelock is off
- zone from tav safehold to phomiuna aqueducts (or any level restricted area)
- check gear getting removed but char look staying the same
- zone out again to have gear reequipped

char look seems to be messed up after first zone
another minor thing: out of level equipment is shown as equipable (white)

**Comment by teschnei** [comment]
We can't fix it showing as equippable because that's a client side thing,
ever since they implemented gear scaling

**Comment by TeoTwawki** [comment]
I knew about the appearance not updating but hadn't had free time to deal with cosmetic issue yet.
