### ISSUE TITLE
THF Merit Issue

### ISSUE THREAD

**Issue by kimballharoldf** [DarkstarProject/darkstar#411]
Looks like the recast time of Feint is not being improved when adding merits to Feint. This is a bit out of my level of coding on this project at the moment otherwise I would submit a fix. 

Aura Steal isn't implemented. If there's no changes in the core, I can give an attempt to give it a go.

**Comment by nesstea** [comment]
@teschnei can you get an effect and it's duration, power, etc. from a mob?

**Comment by teschnei** [comment]
yes, mobs and players use the same container for all effects

**Comment by nfaletra** [comment]
This is all addressed in: https://github.com/DarkstarProject/darkstar/pull/4657
