### ISSUE TITLE
Blue Magic Spells doing 0 Damage (physical spells are fine)

### ISSUE THREAD

**Issue by vrtra** [DarkstarProject/darkstar#4110]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:30170905_5** 

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Blue magic doing 0 dmg on all levels of mobs (physical magic is working)

Noticed it on my live server, made a clean pull of dsp on my test server to verify no custom content was causing the problem.

**Comment by maxtherabbit** [comment]
7c51397
