### ISSUE TITLE
geomancer spells crashing server

### ISSUE THREAD

**Issue by NeoSpace29** [DarkstarProject/darkstar#4118]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 
30170905_5

**_Server Version_** (type `!revision` in game) 
53771f2

**_Source Branch_** (master/stable) 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://1drv.ms/u/s!AnY9mhvx6w8G2Q2Y2z61ST1uIEDR

the steps i took are:
#1: i made my character change to Geomancer 
#2: i  did !addallspells command
#3: i tried to use the spells in town(it crashed )
#4: i got back on and tried them outside town (it crashed again)

after the second time that it was the same problem i saw in the debug window 
i went and got help and they told me to put this info up here

**Comment by takhlaq** [comment]
we currently do not support geomancer/rune fencer (both are unimplemented)
though if someone does wish to add support they are free to make a pull request (preferably after joining discord and discussing with @teschnei)

**Comment by TeoTwawki** [comment]
The crash is from the spelltype not being valid for the current enum. Buuut the spells were commented out I thought, shouldn't be able to cast any without modding things yourself.

**Comment by TeoTwawki** [comment]
e75149de64ba8b0a4b5b3eb7437c40f27ea6a28d

@takhlaq pls don't let anybody try and add the trust to spell_list.sql, those have so little in common I'll probably be giving them their own table. If they do go in same table, it'll be the same generic info repeated anyway..
