### ISSUE TITLE
Puppet WS Magic Mortar & Skillchain Attempt Causes Server Crash

### ISSUE THREAD

**Issue by Delkathus** [DarkstarProject/darkstar#4119]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **: ** 
30170905_5

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When you attempt a skillchain after your puppet on Stormwaker/Harlequin frame uses Magic Mortar it will crash the server. Only this puppet weaponskill will cause the server crash.

Tested it with Sharpshot ws' and Valoredge ws' and no crashes will occur.

How to Recreate Crash:
When your puppet uses the weaponskill Magic Mortar and you use any weapon skill after your puppet uses Magic Mortar it will cause a crash.

Looking into the code i'm theorizing it has to do with:
>>> bool attemptChain = (PAutomaton->getMod(Mod::AUTO_TP_EFFICIENCY) != 0); 
and so on in https://github.com/DarkstarProject/darkstar/blob/5078b8b1b71c30af4a5fbcb9075787e5a9a3cd3f/src/map/ai/controllers/automaton_controller.cpp.

Still looking into it, just wanted to pass this along and get it noted.

Disabling magic mortar from being used is the only temp solution (Go Band-aid solution!).

**Comment by metalfiiish** [comment]
Hrm, wonder if its related to skillchain stuff.

**Comment by TeoTwawki** [comment]
If you click the line number on the left side, you can link directly to the line you intend on github, like this 😃 

https://github.com/DarkstarProject/darkstar/blob/5078b8b1b71c30af4a5fbcb9075787e5a9a3cd3f/src/map/ai/controllers/automaton_controller.cpp#L1275

Lets anybody looking jump directly to it. 😃

**Comment by Delkathus** [comment]
i tried but i apparently failed lol XD
