### ISSUE TITLE
Worms are broken

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4121]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Worms 'attempt' to disappear when moving but end up hijacking the cursor when targeted causing you to not be able to move past them and they sometimes do not disappear at all and end up sliding across the ground.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/issues/2138
