### ISSUE TITLE
Goblintrap working?

### ISSUE THREAD

**Issue by Akhawi** [DarkstarProject/darkstar#4128]
**_I have:Question about Goblintrap NM is wroking whit the dropp it is supose to dropp_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version 30170707_0_** (type `/ver` in game) **:** 

**_Server Version 0c16d47cd63dbba1a3db80c7c12df57144769e81_** (type `!revision` in game) **:** 

**_Source Branch Master_** (master/stable) **:** 

**_Additional Information have tried to pop Goblintrap, but it dose not pop, altho it is lottery pop, but this nm might not work. _** (Steps to reproduce/Expected behavior) **:**

**Comment by metalfiiish** [comment]
Currently not implemented. Looks like the spawn points are in the database but the  East Ronfaure (S)/mobs/Battrap.lua is not built to spawn him onMobDeath.

**Comment by metalfiiish** [comment]
Can be closed as this has now been implemented.
