### ISSUE TITLE
Game Server Crashes on mob using ability/spell

### ISSUE THREAD

**Issue by sargcj** [DarkstarProject/darkstar#4153]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** Unknown

**_Source Branch_** (master/stable) **:** Master (Pulled earlier today(10/23) to update)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Seemingly random, yet has happened several times so far. First 2 instances were in ady. subterrain when a mob would cast a spell.
Most recent is when fighting bloodpool vorax and it used TP Drainkiss. The gameserver instantly crashed.  I suspect some recent changes as this wasn't happening in my previous build (pulled around 10th of october.)

Debugging this instance pointed to line 69 in lua_mobskill.cpp 
--Bloodpool Vorax was using TP Drainkiss
Debugging the earlier instance (no dump file sorry) pointed to line 70 of Lua_spell.cpp
--Slime Eater in Aydeewa Subterrane cast stoneskin when it happened.

I have included files from the dump.
DumpLink: https://drive.google.com/open?id=0ByCCY-QyWxcmNWJZWE9qSlZzeTg

Note: Teo may have fixed the TP issue, but whasf requested I still post issue.

**Comment by TeoTwawki** [comment]
b1bbe07e12438da3193753bb5a6c583fcfbc70e9
and
c32d7c64f20941393fef58633ac1aed37ca076ae

**Comment by sargcj** [comment]
c32d7c6 seems to have fixed TP move crash, Will test b1bbe07 tomorrow.

**Comment by zynjec** [comment]
Issue seems to have been resolved.
