### ISSUE TITLE
Spells have 0-5 second recast time 

### ISSUE THREAD

**Issue by vrtra** [DarkstarProject/darkstar#4158]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:Enhancing, Healing, Ninjitsu and summoning magic all have a recast timer of 0-5 seconds. I have ran the server in debug mode but couldnt find any errors. Could be similar to the warning commit error with latent_effects from yesterday. **

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/6b4ffa1c3225476e99a52dafad32055a8aa13f35
