### ISSUE TITLE
Cannot Nexus to Pashhow Marshlands

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4166]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Put on Nexus cape
2. Have Party Leader in Pashhow
3. Fail at Nexus

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/594a4ddd4d91c9f5948b3eca4f2df03d04fcf3bf#diff-21321494afb203809553dc9b8bf80666R24
+
http://ffxiclopedia.wikia.com/wiki/Nexus_Cape
