### ISSUE TITLE
Player's can claim more than one mob simultaneously

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4167]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Go to any zone (Low Level for max effectiveness)
2. put up stoneskin/phalanx/shadows/whatever
3. Diaga every mob in the zone but don't kill them... just keep claim
4. Stand by entrance to a city and watch all the low level players sulk because they cannot get any mobs.

**Comment by TeoTwawki** [comment]
already brought up by issue #2109
