### ISSUE TITLE
Crash when trying to find a status effect script

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#4179]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
n/a

**_Server Version_** (type `!revision` in game) **:** 
9ded76ded32fff04d70ed7f22829289dff63cb33

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
dump: https://1drv.ms/u/s!AvyTIXTmkiRwnDZl8wb_xqoeq88v

**Comment by TeoTwawki** [comment]
huh. Khromasoul_Bhurborlor go bewm.

**Comment by whasf** [comment]
Happened today on player named "Oldstone" while in Dynamis-Windurst
Dump: https://1drv.ms/u/s!AvyTIXTmkiRwnD1okpKs1rhFy2Et

**Comment by teschnei** [comment]
closing in favor of #4324
