### ISSUE TITLE
Rare/EX items lost with treasure pool auto assign

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4187]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Rare/EX items can drop to players that already have the item instead of prioritizing players who do not have it resulting in a loss of said item. Workaround would be to make sure you always lot for items you need/want instead of waiting for the treasure pool to assign. This is not retail behavior so hence, the 'issue'.

**Comment by Jessland86** [comment]
Fun fact: You can still loose them even if you have cast a lot on them, but not everyone has passed.
