### ISSUE TITLE
petutils - not accounting for scaleOver75

### ISSUE THREAD

**Issue by ShelbyZ** [DarkstarProject/darkstar#4192]
**_Source Branch_** (master/stable) **:** 
master

In petutils.cpp (and charutils) there is Load***Stats(...) methods that builds out the stats of an entity based on level among other factors.  While cleaning unused variables out of map, I noticed that LoadAutomatonStats(...) appears not to take into account the scale factor for Over75, **scaleOver75** when trying to build up the jobStat nor sJobStat.

It looks like LoadAvatarStats(...) and CalculateStats(...) both take into account over 75, so automatons also need some similar adjustments.

**Comment by teschnei** [comment]
Automatons already have their stats calculated to match retail as closely as possible using the current formulas.
