### ISSUE TITLE
Promyvion mobs "strays" are dropping gil

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4201]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Promy strays drop gil by default and without enabling the "all mobs drop gil" setting. Having a hard time figuring out where to change this...

**Comment by wrenffxi** [comment]
Believe this was fixed in ab5dedd9d99dc850a105c7c218f108e808e0e3f9.
