### ISSUE TITLE
GMs and sending /tells to people with /away status.

### ISSUE THREAD

**Issue by Jessland86** [DarkstarProject/darkstar#4211]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30170707_0

**_Server Version_** (type `!revision` in game) **:** 
de8eab2e5da8bfad3f4e0ea98dca001a025dda9b

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
GM's can no longer send tells to people with /away flag. Last time I had to talk to someone doing inappropriate things attempting to hide behind /away (10ish months ago) if you had the GM flag you could still send /tells to them and could not be ignored. 

Also, if you have the /away flag up and you log out you also now have perma away flag no matter how much you zone etc.

**Comment by TeoTwawki** [comment]
Temporary work around: 
`!setflag 0x00004000 <t>`

**Comment by teschnei** [comment]
was your GM flag on? some of the GM checks only work if your GM flag is on
still

**Comment by Jessland86** [comment]
Yup, GM flag was on. I toggled it off and tried, got "the recipient is away," toggled it back on and got same result.
