### ISSUE TITLE
cant sign into my account

### ISSUE THREAD

**Issue by fuclarian** [DarkstarProject/darkstar#4221]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

okay so i tryed logging into my account which should have been jeffy52 but could not. tryed to see if it was deleted by creating a new account same name/password and it was created. i havnt played in awhile cause real life but was wondering if i could get that account back. really dont mind leveling a new char but i got alot of hard to get items and time into him. i would hate to lose my drk and thf gear. sry i dont know where to finds the info for the info listed above but its not the issue so i hope that doesnt get this post deleted.  Character name should be Fuclarian which is a elvaan 99 Drk,Thf,Blu

**Comment by whasf** [comment]
Hello!
1. This issue tracker is for the darkstar project itself
2. You need to contact the owner of the server you are trying to connect to
