### ISSUE TITLE
Job ability steal msg.lua problem

### ISSUE THREAD

**Issue by dwn134** [DarkstarProject/darkstar#4228]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171004_1

**_Server Version_** (type `!revision` in game) **:** interesting, new build from 11-12, but says unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
when using the ability it works but doesnt display what was stolen, as a result fighting maat and stealing from him doesnt count as a win
error in log says luautils::onUseAbility: .\scripts/globals/abilites/steal.lua:64: attempt to index global MsgBasic' (a nil value)

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/commit/ec9f888223033afe4443dbadefcfb138abba46a5
