### ISSUE TITLE
violent flourish, 0 damage and no stun procs

### ISSUE THREAD

**Issue by dwn134** [DarkstarProject/darkstar#4229]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171004_1

**_Server Version_** (type `!revision` in game) **:** interesting, new build from 11-12, but says unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
when using the ability it always displays 0 as damage and says stun but doesnt actually stun
error in log says luautils::onUseAbility: .\scripts/globals/magic.lua321: attempt to index local 'params' (a number value)

**Comment by Hozu** [comment]
Whoever changed applyResistanceEffect missed changing this script to work with the modified function. Surprised it took so long for someone to notice and make an issue.

I think Desperate Flourish suffers from the same issue.

**Comment by takhlaq** [comment]
yep, i ran a regex replace for applyResistance crap since there was no way i was going through them all manually so i left what it missed for people to report in issues

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/1486fbe953e49706b28ebada86e068bdfa464703
