### ISSUE TITLE
<stpc>, <stnpc>, <st> not working properly with actions

### ISSUE THREAD

**Issue by scorchedxi** [DarkstarProject/darkstar#4233]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30170905_5

**_Server Version_** (type `!revision` in game) **:** 
unknown

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Subtargetting in macros (eg. &lt;st&gt;, &lt;stnpc&gt;, &lt;stpc&gt;) doesn't work properly. Example /ma "Cure" &lt;stpc&gt; should target player characters, then when selecting the target to perform the action, the action should fire. Instead, the action is firing instantly on whatever the current main target is.

**Comment by teschnei** [comment]
Can you try it after disabling all of your windower/ashita add-ons and
plugins?  I think the subtarget macros are all client side (but I could be
wrong)

**Comment by scorchedxi** [comment]
Ah, I missed unloading shorthand. That was the culprit. Sorry!
