### ISSUE TITLE
Party creation crash

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#4234]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Server Version_** (type `!revision` in game) **:** 
65353942f02db6970b341ab48ffa41266a84e4ca

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://1drv.ms/u/s!AvyTIXTmkiRwnFbS2WVUWiC9WrsA

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/929538833edea69f096f6de1e61fe0b6c57b97cc
https://github.com/DarkstarProject/darkstar/commit/cc45b990bef07ff65614b0a5e0cbd3b37db59279
one of those fixed it!
