### ISSUE TITLE
Blighting Brand throws an error when trying to UpdateNMSpawnPoint

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4241]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Are we adding NMSpawnPoints or taking out the request to update? idk so, up to whoever.

**Comment by Wiggo32** [comment]
looks like he also spawns halfway inside the bone skeleton which puts him inside when he moves making it impossible for melee type characters to get to him. mages can still nuke him but he wont even come out of the bone with navmesh enabled so that's like cheating.

**Comment by Wiggo32** [comment]
actually, just tried to fix his spawn point to make him spawn on top of the spine like he's supposed to but he still falls inside when he moves... not sure how to fix that.

**Comment by teschnei** [comment]
it's usually the client that does y correction on mobs like that.

funnily enough, when I did Dynamis - Qufim on retail yesterday, the weapons
were spawning inside the spine and I couldn't engage them.  So that part is
probably okay for us

**Comment by Wiggo32** [comment]
https://github.com/DarkstarProject/darkstar/pull/5116 would resolve the issue of the mob not coming out of the spine. Even though, you sometimes cannot engage them on retail... if you do get claim from another source, they will pursue regardless of being "inside the spine".
