### ISSUE TITLE
Rottata wrong dialogue

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4243]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Rottata tells me that regions which are currently under my home country's control are NOT currently under my home country's control when asking for teleports to said regions. I don't know if this is a global problem with all outpost teleporters but Rottata for sure.

**Comment by TeoTwawki** [comment]
let us know if still happens after both client and server are on version 30171103_1 (just updated master branch)

**Comment by wrenffxi** [comment]
It's still a problem.  The prices are calculated correctly, so it's only a cosmetic issue.  The problem lies here

https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Port_Windurst/npcs/Rottata.lua#L46

The fifth argument is, correctly, the player's CP.  The third argument however, to which we're passing CP, is instead supposed to control Rottata's next spoken dialog.  This is confirmed in the dialog extract:
```
That region is ≺Multiple Choice (Parameter 2)≻[no longer under your home country's control./currently under your home country's control.] You will require ≺Numeric Parameter 1≻ gil or ≺Numeric Parameter 3≻ conquest ≺Singular/Plural Choice (Parameter 3)≻[point/points] to teleport.
```

Problem is, I cannot figure out what that third parameter needs to be set to in order to change Rottata's dialogue.  I tried all the obvious things.  Numbers around 0.  Powers-of-two.  Powers-of-two minus one.  The 1073741823-ish menu offset plus and minus obvious variables.

So we know why it's happening, just not yet how to fix it.

**Comment by TeoTwawki** [comment]
thanks for the update

**Comment by Wiggo32** [comment]
Parameter 3 controls the control- starting with 
32 for Ronfaure
64 -Zulkheim
128 - Norvallen
256- Gustaberg
512- Derfland
1024- Saratabaruta
2048- Kolshushu
4096- Aragoneau
8192- Faurengandi
16384- Valduana
32768- Qufim
65536- Lil Teilor
131072- Kuzotz
262144- Vollbow
524288- Elshimo Lowlands
1048576- Elshimo Uplands
2097152- ???
4194304- ???
8388608- Tavnazia

Some I couldn't figure out... they are probably all spelled wrong. But, in order to activate the region control portion Parameter 6 has to be set to 514. Maybe you can do something with that.

**Comment by wrenffxi** [comment]
Param6 may be what I'm missing.  Doing some more testing.

**Comment by Wiggo32** [comment]
i did this for rottata... not sure if they use different param values for different outpost warp npcs. 
do this EXACTLY:
1. go to port windurst.
2. type: !cs 0x028 0 0 64 0 0 514 99 1063256127
3. select zulkheim and note text saying it is under your control
4. repeat 2
5. select any other region and note text saying it is not under your control.

**Comment by wrenffxi** [comment]
Interesting.  You're setting the region on eventStart rather than eventUpdate.  Before the player has selected anything from the menu.  Which means that third param (64) is probably expecting a bitmask of nation-controlled regions.  Doing more testing.

**Comment by TeoTwawki** [comment]
was gonna say..bitpacked param. Was just getting onto retail to look at a packet (I have a char with all outposts I can look at)

**Comment by Wiggo32** [comment]
np, glad it worked out. and looking at your PR, looks like it was pretty much the same for the other two warp npcs as well... that's always a plus!
