### ISSUE TITLE
Creating alliance causes Game Server crash

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#4245]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** it says Unknown, but my fork is even with DSP master as of commit 522faa7eee75a0abaf794e6a77ecfd144a4e5a73.

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Build brand new database schema from current SQL files.
Create three new characters in Bastok: Wren, Finch, and Tern.
Tern /pcmd add Wren.
Wren /join.
Wren /pcmd leave.
Wren /pcmd add Finch.
Finch /join.
So currently Tern is solo party leader.  Wren and Finch are in a party, with Wren leader.
Wren /sea all and select Tern from the list > Form
Tern /join. Immediate DSGame-server.exe crash

JustInTime Debug with VS Community 2017 Preview
```

>	DSGame-server.exe!std::vector<CParty *,std::allocator<CParty *> >::_Has_unused_capacity() Line 1787	C++	Symbols loaded.
 	DSGame-server.exe!std::vector<CParty *,std::allocator<CParty *> >::emplace_back<CParty * const &>(CParty * const & <_Val_0>) Line 938	C++	Symbols loaded.
 	DSGame-server.exe!std::vector<CParty *,std::allocator<CParty *> >::push_back(CParty * const & _Val) Line 982	C++	Symbols loaded.
 	DSGame-server.exe!CAlliance::addParty(CParty * party) Line 216	C++	Symbols loaded.
 	DSGame-server.exe!SmallPacket0x074(map_session_data_t * session, CCharEntity * PChar, CBasicPacket data) Line 3348	C++	Symbols loaded.
 	DSGame-server.exe!parse(char * buff, unsigned int * buffsize, sockaddr_in * from, map_session_data_t * map_session_data) Line 595	C++	Symbols loaded.
 	DSGame-server.exe!do_sockets(fd_set * rfd, std::chrono::duration<__int64,std::ratio<1,1000000000> > next) Line 375	C++	Symbols loaded.
 	DSGame-server.exe!main(int argc, char * * argv) Line 316	C++	Symbols loaded.
 	[External Code]		Annotated Frame
```
[The exception thrown](https://i.imgur.com/nLigZOS.png)

[Console shows this before server crashes.](https://i.imgur.com/7pqaZoH.png)

~~I had one of our other devs test this, and he could not replicate the issue.~~

Suspect a VS update required.  Will test and report back.

Update: rebuilt on VS Community 2017 15.4.4.  Encounter same error when forming alliance.
Update: all three project builds fail on Community Preview 2017 15.5.0 Preview 4.0.

Am out of ideas.  Any suggestions?  Can anyone replicate this issue?

**Comment by ShelbyZ** [comment]
Check if #4251 addresses this issue

**Comment by wrenffxi** [comment]
Updating client, then I'll give it a whirl.
