### ISSUE TITLE
promy strays/receptacles recently 'fixed' incorrectly

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4257]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Recent PR: https://github.com/DarkstarProject/darkstar/pull/4194/files 'fixes' strays so that they respawn every 30 sec.

Just went to promy dem on retail killed all the strays and then started timing after i killed the last stray
stray 1 popped in about 6 min
stray 2 popped 6 min later
stray 3 popped 2 min later
killed them again and then engaged the receptacle
stray 1 popped in about 20 sec
stray 2 popped 18 sec later
stray 3 popped 18 sec later
went to 2nd floor - 5 strays - killed them all and started timing
stray 1 - about 6 min
stray 2 - 3 min later
stray 3 - 2 min later
stray 4 - 1 min later
stray 5 - 1 min later
killed them again and engaged
stray 1 - about 20 sec
stray 2 - 18 sec
stray 3 - 16 sec
stray 4 - 17 sec
stray 5 - 17 sec
that's about all i had patience for. theres a huge difference in stray pop time whether or not the receptacle is engaged. dont ask me what the exact formula is... i just know its not a flat 30 sec.

also, with the addition of this PR there is a knockback effect with every empty seed whether it connects or not. in retail, there is no knockback with empty seed when the receptacle misses or is absorbed by shadows. i did have knockback with even the slightest bit of damage though. not sure why this was removed with this PR because it used to work correctly.

**Comment by TeoTwawki** [comment]
let us know if still happens after both client and server are on version 30171103_1

**Comment by TeoTwawki** [comment]
misread disregard

**Comment by TeoTwawki** [comment]
Doesn't look like empty seed was touched in that PR.

**Comment by Wiggo32** [comment]
well... empty seed mysteriously started adding knockback upon missing sometime after this PR. included issue... it shouldnt

**Comment by Delkathus** [comment]
Seems like it's working as intended to retail accuracy to me. Don't know why it's a issue.  ̄\_(ツ)_/ ̄

**Comment by Delkathus** [comment]
I wasn't able to recreate this issue.

**Comment by Wiggo32** [comment]
another thing to keep in mind... in retail strays spawn at the receptacle and then move out to their 'wandering' points. dsp just has them spawn at random spawn points around the receptacle

**Comment by TeoTwawki** [comment]
Having done promy dem/holla/mea literally yesterday on retail: wrong
They spawned *around* it and move *in* not out. Had a few pop behind me even. *jerks*. Had to turn to target them.

**Comment by TeoTwawki** [comment]
when they spawn while receptacle is idle, they just plain wander around their pop points. Where darkstar has them are wherever they were captured at when the person capturing went through. Some are spawning closer to the receptacle than others, true on retail as well.

**Comment by Wiggo32** [comment]
i just sat there and watched them on retail all come from under the ball... ALL of them... give me your dropbox and you can watch the same thing... cause it's recorded... the ball moved up for every spawn... and out popped a stray from the ball... EVERY time. some spots do not have receptacles... this is probably what you're referring to as being they spawn anywhere. that's because there's no receptacle to come out of.

**Comment by TeoTwawki** [comment]
I watched them NOT do that exact thing.
It's randomness.

**Comment by TeoTwawki** [comment]
I saw them spawning in both before and during my fights. They don't always spawn in the ball.

**Comment by TeoTwawki** [comment]
You know, their precise spawn position isn't exactly a make or break here anyway. How fast they repop is the primary issue being reported yes? Followed by your noting that the receptacles mobskill appears to be incorrect. So lets shelve the spawn positioning for the time being and not add additional distractions to the already reported problem. I've done that in the past and let me tell you: it makes everyone forget what we're saying when we tack on more things.

**Comment by Delkathus** [comment]
As for the Empty Seed ability knocking back while missed, I have yet to recreate that in 50+ Empty Seed's that missed in the past hour of attempts. Unless i'm doing it wrong it seems to be fine.

**Comment by Wiggo32** [comment]
Well, me neither now... empty seed is working fine again. Will have to retrace my steps to see if I can recreate it, but like teo said, it's not the main issue. was just something else i noticed. So, if Teo saw randomness with the stray spawns... then that's what he saw. However there doesn't seem to be any randomness with dsp then.

**Comment by TeoTwawki** [comment]
The road to retail accuracy is paved with much /banghead

**Comment by wrenffxi** [comment]
I couldn't replicate either the empty seed knockback on miss, or the 6 minute delay between strays.  I moved the 30 sec interval to be consistent whether or not a stray is found to spawn in this new PR.  Previously, if it couldn't find a stray to spawn, it would keep trying every tick until it found one.  Every test I've tried before and after spawned strays ~30 seconds in between, give or take a couple seconds to account for despawn timers.

**Comment by Wiggo32** [comment]
The 6 minute delay between strays wasn't an issue that existed on dsp. It was an issue that it didn't. because on retail strays do NOT spawn every 30 sec. on retail, they spawn that quickly only when the receptacle is engaged in battle. just sitting idle, the stray respawn is much longer.

**Comment by wrenffxi** [comment]
Ah, I missed that your tests were done on retail, so misunderstood the issue entirely.  So more accurate retail behavior would be to have strays begin spawned, have a natural respawn timer of ~6 minutes, and to have the receptacle only attempt to respawn dead strays when engaged every ~20 seconds.

**Comment by Wiggo32** [comment]
that sounds about right... but for the 2 sets of strays i tested, the natural respawn timer seemed to decrease as more strays were out. so, either the natural respawn is "somewhere" between 1 - 6 min or it starts out at ~6 min and decreases as more are spawned. i dont really have enough data to make that determination. but i've timed them popping at 1 min, 2 min, 3 min, and 6 min. dont really know how random this is without tons of data. and even though i havent seen any pop at 4 or 5 min doesnt mean they dont. so... idk. i just know natural respawn is significantly more than 30 sec. and yes when engaged i got ~20 sec.

**Comment by Wiggo32** [comment]
if you tell me the EASIEST way to share a 1.5 Gb video (without me having to make a bunch of new accounts) I can just send you the vid and you can probably understand what I'm talking about a little better

**Comment by teschnei** [comment]
upload unlisted to youtube

**Comment by Wiggo32** [comment]
its not for the whole world... just wren. and i said i didnt want to create any new accounts.

**Comment by takhlaq** [comment]
> its not for the whole world... just wren. 

yes, that is why he said `unlisted`, meaning it wont appear in search results (can only view by directly going to that link) - meaning you can make it private or take it down after pm'ing wren on discord and confirming she's seen it
and you won't need to create a new account for youtube iirc if you already have a google account

**Comment by Wiggo32** [comment]
sorry, guess i misunderstood how youtube worked

**Comment by Wiggo32** [comment]
cant upload a video longer than 15 min   - its 58 min long

**Comment by teschnei** [comment]
ah.. just upload the part that matters

**Comment by Wiggo32** [comment]
how do i upload 'part' of a video? the whole thing matters... just waiting for 2 strays is already 12 min... might as well just not bother if you're only going to look at 6 min of dead space in between 2 stray pops

**Comment by TeoTwawki** [comment]
@Wiggo32 by editing in like virtualdub. but don;t worry I got you covered. went back in up holla and recorded its uploading now.

And I owe you an apology about the spawn pos stuff: You are right, I was wrong, I just wasn't getting them faded in all and they are in motion during or even before this. So they can spawn, move right through you, and attack from behind (or beside or anywhere else near).

**Comment by TeoTwawki** [comment]
Here's a video with timestamps everywhere for us (plus a few `/clock` commands):
https://vid.me/4EiGj
Note: there may be a delay before its available on the website as they encoded several resolutions. Potato res will likely be available first..  Also parts of it are me just standing around to check idle repops.

**Comment by TeoTwawki** [comment]
Corrected link: https://vid.me/jZeJK

**Comment by TeoTwawki** [comment]
#4263
