### ISSUE TITLE
Prism Powder / Silent Oil base times off

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4272]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
On retail, the base time for Silent Oils and Prism Powder ranges from 7 to 9 min (indicated by the icon timer which means it's most likely more than 7 to 9 because we do not get to see the seconds of time remaining)
I've used Powder/Oil on lvl 99 jobs, lvl 20, lvl 1 with no change in base time applied. It's always been 7 to 9 min. Also, rank didn't seem to make any difference as the base time remained 7 to 9 whether the character had rank 1 or rank 10.

dsp has base times set to 1 to 3 min for Prism Powder and Silent Oil.
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/items/pinch_of_prism_powder.lua
https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/items/pot_of_silent_oil.lua

**Comment by TeoTwawki** [comment]
got updated in retail awhile back and nobody updated the item scripts I guess

**Comment by Hozu** [comment]
If they changed the items, did they also change the spells?

**Comment by TeoTwawki** [comment]
> did they also change the spells?

yes

I also thought the randomness was removed entirely but maybe its just the base duration of all sneak/invis/deoderize effect sources was hugely bumped up.

**Comment by TeoTwawki** [comment]
bg just says "Duration is variable, but has a minimum of 5 minutes." for all 3. I've yet to see anything below 9 min but maybe that's just luck or related to lv99 with capped enhancing (nothing says the skill effects it, but maybe it does - I've no idea). Pure luck is very possible, I'm only on retail for free weeks and don't spend much time on a mage job in a location that would need it.

**Comment by zynjec** [comment]
Fixed in https://github.com/DarkstarProject/darkstar/pull/4645
