### ISSUE TITLE
New Pull / New Build Errors

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4274]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Just rebuilt server with new master from Github:
![errors](https://user-images.githubusercontent.com/30469395/33221228-977bed36-d113-11e7-924b-8d824518df84.jpg)
Everything is stock from dsp master except for the conf files pointing to my own database.

**Comment by teschnei** [comment]
Is.. your own database updated?

**Comment by zynjec** [comment]
Looks like you didn't import the new SQL added for the NMs.

**Comment by Wiggo32** [comment]
oh. didn't think of that

**Comment by takhlaq** [comment]
git log -2 --oneline
>1bb67292c (HEAD -> master, origin/master, origin/HEAD) Merge pull request #4256 from wrenffxi/attohwa-fixes
23257a899 Attohwa antlion, miasma, gasponia fixes

git grep -n 17555721 -- ./sql/
>sql/mob_spawn_points.sql:54270:INSERT INTO `mob_spawn_points` VALUES (17555721,'Barbastelle','Barbastelle',105,133,-0.5,220,114);
sql/nm_spawn_points.sql:6296:INSERT INTO `nm_spawn_points` VALUES (17555721,0,133,-0.5,220);

yep looks like those tables weren't reimported
though im not sure why server rev shows as unknown

**Comment by Wiggo32** [comment]
Reimported brand new database from stock sql's only changed zone ip settings. Now have:
![server](https://user-images.githubusercontent.com/30469395/33221835-58ba4eb2-d118-11e7-91b5-725a8b525410.jpg)
No errors, still have "unknown" for server rev. (I've actually never gotten anything other than "unknown" could my Visual Studio be set up incorrectly?)

**Comment by zynjec** [comment]
Are you actually using git to pull the repo, or are you downloading a zip of the repo?

**Comment by teschnei** [comment]
The server just checks the hash in your git repository. If you aren't
building from a repository, it won't know the revision

**Comment by takhlaq** [comment]
i made a poopy and didnt select all configurations/platforms, should be good now https://github.com/DarkstarProject/darkstar/commit/b17a3a7ea83922c1acbb63cbba404cfb3f0ce6cc
