### ISSUE TITLE
ID Shift Issue for Promy Mea?

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4276]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** b17a3a7

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
I think it's just ID shifting, not certain though:
![receptacle](https://user-images.githubusercontent.com/30469395/33232581-501824e4-d1ce-11e7-8036-ef923cb4c0dc.jpg)
I don't know if it's zone wide either, I only ran into these two guys so far. 
IDs: 16859271, 16859252

**Comment by TeoTwawki** [comment]
fixed by #4287
