### ISSUE TITLE
Promy strays don't pop one at a time

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4279]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** b17a3a7

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Strays were recently changed to spawntype '0' in mob_groups which causes an issue allowing them to pop all at the same time if they happen to be killed at the same time.  In retail, strays pop one at a time no matter how many were killed at the same time. So, they should remain spawntype '128' (scripted) and fixed to allow them to spawn one at a time (every 5.5 min if that's what is easiest though retail has a variable respawn for strays when the receptacle is Idle depending on how many are already popped).

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5418
