### ISSUE TITLE
'Tame' can't miss

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4280]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** b17a3a7

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Changed to lvl 35 bst and went to Rala Waterways, started 'taming' a Pewter Diremite (17834122)
It checks as IT++ (lvl 99-107)
after 50+ 'tame's I still haven't missed a single one naked. That's about a 65-70 level difference.

**Comment by teschnei** [comment]
There's no hit check for the case where the mob isn't aggroed (wasn't sure
if there is one on retail).  Is that what you're talking about here?

**Comment by Wiggo32** [comment]
I'm not sure what exactly that means. But, on retail you can tame a mob that isn't aggro'd you either get a miss if it misses, a "seems friendlier" if it hits, or "no effect" if it cannot be tamed. You get the same messages for mobs that are aggro'd. 
I sometimes would tame first in retail when faced with tough mobs in a dangerous spot becaue it didn't generate hate, didn't get me aggro, and didn't remove sneak or invisible. Then, if tame was successful, I would attempt the charm with the added charm bonus. Retail tame does have a pretty good success rate on Tough mobs but it 'should' miss at least 'some' of the time.
