### ISSUE TITLE
Lootblox (Davoi) wrong dialogue

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4283]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** 2fe3c089

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Lootblox is supposed to not want to talk to players who do not possess the "Vial of Shrouded Sand" key item like the other dynamis vendors in Castle Oztroja and Beadeaux. He is currently giving all players the option to use his services without having obtained said Key Item.

**Comment by wrenffxi** [comment]
This is an easy fix -- there's some code commented out that shouldn't be -- but I'm updating the code for these three goblins to use post-prismatic hourglass events.  Should be a more complete fix.
