### ISSUE TITLE
Promy receptacles 'could' provide no portal after killing all of them

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4294]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** 2fe3c08

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
with the recent changes to receptacles in dsp, there is now a chance that the receptacle doesn't spawn a portal. That is accurate retail behavior but, the way the formula is set up it randomizes that 'chance' at every receptacle. meaning, you could kill all 4 on the second level and still not see a portal if you haven't killed them fast enough due to them respawning. Killing them fast is not an easy thing to do when you use the ENABLE_COP_ZONE_CAP which caps you at lvl 30. So, unlike 'old' retail it is possible to have killed every receptacle on the floor at least once and still not receive a portal. There is currently no way to prove this as the level cap on retail has been removed permanently. Traversing the promys at lvl 30 is hard enough as it is, but in 'old' retail we never had to kill a receptacle more than once to advance to the next level.

**Comment by Hozu** [comment]
Could have it randomize with the old method (ie. pick a random MR only when the portal is revealed) if the level cap is enabled, no? That way the new retail method would still be there if not using the zone level cap.

**Comment by TeoTwawki** [comment]
i think it actually is possible on retail but super low - i think how many exist on floor factors into it and this is why that entrance area with only one teceptacle is never a "fake"/"dud" one

when i was up there to check the strays i was having bad luck with them, trip prior to that to unlock lufaise i killed 3 of 4 twice before getting a portal but its possible there was a portal closer to the lv 80 mobs i was missing (no map)

**Comment by Wiggo32** [comment]
Should probably close all of my issues as well seeing as how I am of no benefit to the community. Evidenced by my making a statement of opinion on a topic in general conversation and then being banned from the channel when I don't sit there quietly and let everyone attack me.

**Comment by TeoTwawki** [comment]
you aren't banned
just booted so youd stop crapping in the dev channel

**Comment by TeoTwawki** [comment]
and as demo just told me, discord doesn't work like irc - trying to move you out of a channel winds up moving you out of the server

hey don;t worry I'm sure everyone will remove all my privileges to make you feel better real soon,
even as you continue to disparage the entire project at every minor change "for the new guy"

hey if he can make snide remarks, why can't I?

**Comment by zynjec** [comment]
Resolved with https://github.com/DarkstarProject/darkstar/pull/5418
