### ISSUE TITLE
Re-Organize lua_baseentity.cpp

### ISSUE THREAD

**Issue by Cryptexx** [DarkstarProject/darkstar#4295]
I'm working on re-organizing the lua_baseentity.cpp file. I've been wanting to do this for a long time since it's become very jumbled over the years. I'm about 80% finished (no code changes, just re-organize). It's logically separated into the following categories:

// Globals, ID's, and Objects
// Variables
// Masks
// Messaging System
// NPC AI and Operations
// Player Operations
// Packets, Events, and Flags
// NPC Positioning
// Player Positioning
// Inventory and Item Management
// Containers and Trade
// Items
// Equipping
// Storing
// Pools
// Player Appearance
// Player Status
// Player Jobs and Levels
// Player Titles and Fame
// Quests and Missions
// Player Currencies and Points
// Player Health and Status
// Skills and Abilities
// Parties and Alliances
// Instances    
// Battlesfields
// BCNM
// Dynamis
// Battle Utils
// Enmity
// Status Effects
// Damage and Calculations
// Pets
// Mobs and AI

Is there any disagreement with this order?

All of the code has been sorted. The last thing I have to do is add comments for each function. I've added quite a few already in the following format:

```
/************************************************************************
*  Function: ChangeMusic()
*  Purpose : Select a new .bgw file to play on the client
*  Example : player:ChangeMusic(5,84)
*  Notes   : Mounting Chocobo and changing Jeuno music in Winter
************************************************************************/
```

I left off the asterisks at the end of each line. Quite frankly that got annoying trying to align them all perfectly over ~500 sections and 10,000 + lines. We can re-add them later if they're really missed. 

The intent of the format change is to document everything more thoroughly and provide real examples of each member function's use.  The Notes line can be used for 'To Do's' and whatever other relevant information the developer feels is important. 

I'll have this done tomorrow, but wanted to throw out my idea for the comment lines and organization beforehand. I'm open to suggestion, of course. If no one has any objection, I'd like to present it tomorrow for review. 

**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by Cryptexx** [comment]
Here's an example of the very top of the file:

`/************************************************************************
*  Function: SendRevision()
*  Purpose : Sends the current Git version to the client via message
*  Example : player:SendRevision()
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::SendRevision(lua_State* L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_PC);
    char version[100];
    strcpy(version, "Revision is: ");
    strcat(version, get_git_revision());
    ((CCharEntity*)m_PBaseEntity)->pushPacket(new CChatMessagePacket((CCharEntity*)m_PBaseEntity, MESSAGE_SYSTEM_1, version));

    return 0;
}

/************************************************************************
*  Function: getID()
*  Purpose : Get Entity's ID
*  Example : npc:getID(); target:getID()
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::getID(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushinteger(L, m_PBaseEntity->id);
    return 1;
}

/************************************************************************
*  Function: getShortID()
*  Purpose : _________ 
*  Example : mob:getShortID(); pet:getShortID()
*  Notes   : To Do: Should be renamed to getTargID
************************************************************************/

inline int32 CLuaBaseEntity::getShortID(lua_State *L) 
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushinteger(L, m_PBaseEntity->targid);
    return 1;
}

/************************************************************************
*  Function: getCursorTarget()
*  Purpose : GM command - gets the ID of selected Mob's, NPC's, Players 
*  Example : player:getCursorTarget()
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::getCursorTarget(lua_State* L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_PC);

    CCharEntity* PChar = (CCharEntity*)m_PBaseEntity;
    auto PTarget = PChar->GetEntity(PChar->m_TargID);

    if (PTarget == NULL)
    {
        lua_pushnil(L);
    }
    else
    {
        lua_getglobal(L, CLuaBaseEntity::className);
        lua_pushstring(L, "new");
        lua_gettable(L, -2);
        lua_insert(L, -2);
        lua_pushlightuserdata(L, PTarget);
        lua_pcall(L, 2, 1, 0);
    }

    return 1;
}

/************************************************************************
*  Function: getObjType()
*  Purpose : Returns the int value of an entity's object type (Mob,PC...)
*  Example : if (caster:getObjType() == TYPE_PC) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::getObjType(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushinteger(L, m_PBaseEntity->objtype);
    return 1;
}

/************************************************************************
*  Function: isPC()
*  Purpose : Returns true if entity is of the PC object type
*  Example : if (target:isPC()) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::isPC(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushboolean(L, m_PBaseEntity->objtype == TYPE_PC);
    return 1;
}

/************************************************************************
*  Function: isNPC()
*  Purpose : Returns true if entity is of the NPC object type
*  Example : if (target:isNPC()) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::isNPC(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushboolean(L, m_PBaseEntity->objtype == TYPE_NPC);
    return 1;
}

/************************************************************************
*  Function: isMob()
*  Purpose : Returns true if entity is of the Mob object type
*  Example : if (target:isMob()) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::isMob(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushboolean(L, m_PBaseEntity->objtype == TYPE_MOB);
    return 1;
}

/************************************************************************
*  Function: isPet()
*  Purpose : Returns true if entity is of the Pet object type
*  Example : if (caster:isPet()) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::isPet(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushboolean(L, m_PBaseEntity->objtype == TYPE_PET);
    return 1;
}

/************************************************************************
*  Function: isAlly()
*  Purpose : Returns true if entity is an ally
*  Example : if (mob:isAlly()) then table.insert(allies, mob) end
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::isAlly(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushboolean(L, m_PBaseEntity->objtype == TYPE_MOB && m_PBaseEntity->allegiance == ALLEGIANCE_PLAYER);
    return 1;
}

/************************************************************************
*  Function: getStatus()
*  Purpose : Returns the status (or 'state') of an entity 
*  Example : if (qm2:getStatus() ~= STATUS_DISAPPEAR) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::getStatus(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    lua_pushinteger(L, m_PBaseEntity->status);
    return 1;
}

/************************************************************************
*  Function: setStatus()
*  Purpose : Updates the status (or 'state') of an entity
*  Example : npc:setStatus(STATUS_NORMAL)
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::setStatus(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    DSP_DEBUG_BREAK_IF(lua_isnil(L, 1) || !lua_isnumber(L, 1));

    m_PBaseEntity->status = (STATUSTYPE)lua_tointeger(L, 1);
    m_PBaseEntity->updatemask |= UPDATE_HP;
    return 0;
}

/************************************************************************
*  Function: getVar()
*  Purpose : Returns a var value assigned to a PC (in char_vars.sql)
*  Example : local status = player:getVar("[ZM]Status")
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::getVar(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_PC);

    DSP_DEBUG_BREAK_IF(lua_isnil(L, 1) || !lua_isstring(L, 1));

    const int8* varname = lua_tostring(L, 1);

    lua_pushinteger(L, charutils::GetVar((CCharEntity*)m_PBaseEntity, varname));
    return 1;
}

/************************************************************************
*  Function: setVar()
*  Purpose : Updates PC's variable to an explicit value; use 0 to delete
*  Example : player:setVar("[ZM]Status", 4)
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::setVar(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_PC);

    DSP_DEBUG_BREAK_IF(lua_isnil(L, -1) || !lua_isnumber(L, -1));
    DSP_DEBUG_BREAK_IF(lua_isnil(L, -2) || !lua_isstring(L, -2));

    const int8* varname = lua_tostring(L, -2);
    int32 value = (int32)lua_tointeger(L, -1);

    if (value == 0)
    {
        Sql_Query(SqlHandle, "DELETE FROM char_vars WHERE charid = %u AND varname = '%s' LIMIT 1;", m_PBaseEntity->id, varname);
        return 0;
    }

    const int8* fmtQuery = "INSERT INTO char_vars SET charid = %u, varname = '%s', value = %i ON DUPLICATE KEY UPDATE value = %i;";

    Sql_Query(SqlHandle, fmtQuery, m_PBaseEntity->id, varname, value, value);

    lua_pushnil(L);
    return 1;
}

/************************************************************************
*  Function: addVar()
*  Purpose : Increments PC's variable by an explicit amount
*  Example : player:addVar("[ZM]Status", 1) -- if 4, becomes 5
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::addVar(lua_State *L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_PC);

    DSP_DEBUG_BREAK_IF(lua_isnil(L, -1) || !lua_isnumber(L, -1));
    DSP_DEBUG_BREAK_IF(lua_isnil(L, -2) || !lua_isstring(L, -2));

    const int8* varname = lua_tostring(L, -2);
    int32 value = (int32)lua_tointeger(L, -1);

    const int8* Query = "INSERT INTO char_vars SET charid = %u, varname = '%s', value = %i ON DUPLICATE KEY UPDATE value = value + %i;";

    Sql_Query(SqlHandle, Query,
        m_PBaseEntity->id,
        varname,
        value,
        value);

    return 0;
}

/************************************************************************
*  Function: getLocalVar()
*  Purpose : Returns a variable assigned locally to an entity
*  Example : if (KingArthro:getLocalVar("[POP]King_Arthro") > 0) then
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::getLocalVar(lua_State* L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(lua_isnil(L, 1) || !lua_isstring(L, 1));

    const char* var = lua_tostring(L, 1);

    lua_pushinteger(L, m_PBaseEntity->GetLocalVar(var));

    return 1;
}

/************************************************************************
*  Function: setLocalVar()
*  Purpose : Assigns a local variable to an entity
*  Example : mob:setLocalVar("pop", os.time() + math.random(1200,7200));
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::setLocalVar(lua_State* L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);
    DSP_DEBUG_BREAK_IF(lua_isnil(L, 1) || !lua_isstring(L, 1));
    DSP_DEBUG_BREAK_IF(lua_isnil(L, 2) || !lua_isnumber(L, 2));

    const char* var = lua_tostring(L, 1);
    auto val = (uint32)lua_tointeger(L, 2);

    m_PBaseEntity->SetLocalVar(var, val);

    return 0;
}

/************************************************************************
*  Function: resetLocalVars()
*  Purpose : Reset local variables back to default (ex: on Mob disengage)
*  Example : GetMobByID(Defender):resetLocalVars();
*  Notes   : 
************************************************************************/

inline int32 CLuaBaseEntity::resetLocalVars(lua_State* L)
{
    DSP_DEBUG_BREAK_IF(m_PBaseEntity == nullptr);

    m_PBaseEntity->ResetLocalVars();

    return 0;
}`

**Comment by teschnei** [comment]
Not really opposed to it.  Maybe we can format the documentation with something that can generate docs like doxygen or something? Anyone else have any opinions?

I have found that a lot of scripters don't really know how to find stuff in lua_baseentity (not surprising considering how giant it is and how hard it is to understand the functions arguments/return values), so automatically generating a doc might be pretty useful.

**Comment by Cryptexx** [comment]
I can work on a white sheet next. Agreed, that that will be helpful. I'm not familiar with Doxygen, but I can check it out in the morning.

**Comment by takhlaq** [comment]
doxygen would be nice since it doesn't require much effort on our part

**Comment by TeoTwawki** [comment]
Am for organize/cleanup, but I dislike permanent header bricks that we have allover right now. I'd rather we document elsewhere aside from small comments in the code body itself or the occasional more involved non permanent `// #TODO` Buuut if it serves a better purpose like automating something else, I can dig that though.

That's my 2 cents.


Note to custom peoples: this is why I tell you to make a block for your custom stuff far away from the DSP stuff 😉  makes your diff easy to read when a big cleanup change triggers the ol edit conflict.

**Comment by ShelbyZ** [comment]
My only thoughts would be to try and fragment that file into sub-objects responsible for each area.  This code be done by either having lua_baseentity contain these objects and just forward calls from existing methods to these sub-objects or it could mean changing the methods to find the intended entity that is invoking the method and having more classes.

**Comment by Cryptexx** [comment]
I'm almost done with it, about another three hours.

**Comment by Cryptexx** [comment]
Update: three hours was far too optimistic. It's midnight, will have tomorrow. This has turned out to be quite the project.
