### ISSUE TITLE
Imperial Whitegate should not check ammo/range

### ISSUE THREAD

**Issue by aizenmyou** [DarkstarProject/darkstar#4303]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
This blocks "Guests of the Empire" from triggering as Naja says only remove your weapons.
Also back in the day on retail I worn bibiki shell and got this C/S.

https://github.com/DarkstarProject/darkstar/blob/9c013be68b20282255c6af4453e3aa9847ccb59c/scripts/zones/Aht_Urhgan_Whitegate/npcs/Imperial_Whitegate.lua#L29

**Comment by TeoTwawki** [comment]
Are we sure its not a matter of just one of the slots needs checked instead of both?

Although checking neither is most likely, since we don't check either of those for the siren's tier quest in North Gustaberg. Unless someone knows for sure I'd guess we just check main and sub slots and leave out both as aizenmyou suggests.

**Comment by teschnei** [comment]
We can also check if the slots are actually weapons

But ranged weapons don't show up on your character model anyways so I don't
think it matters much

**Comment by TeoTwawki** [comment]
Adjusted in #4785, open new issue if further problems with that CS are discovered.
