### ISSUE TITLE
Outpost warping broken by recent change

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4304]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** a72563e

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
A lot of stuff was 'cleaned up' with this merge: https://github.com/DarkstarProject/darkstar/commit/826b9fc5610d837dbdc75fab9202300da874a2c4
A lot of stuff is wrong now.
Rottata (Port Windurst) says she can only teleport players who belong to the nation of Bastok if you speak to her and are not Windurstian. Rottata also says regions are NOT under your home countrys control when they are. And, upon teleporting, DSP Debug Break occurs:

![rotatta-zulkheim](https://user-images.githubusercontent.com/30469395/33392379-83bb99b2-d501-11e7-8f89-498628ca67f1.jpg)

I didn't test every aspect of this... just reporting the issues that I ran into. It probably should have been tested before being put out though ;-)

**Comment by metalfiiish** [comment]
It appears that commit was reverted. Are you seeing any of the same behavior now?

**Comment by Wiggo32** [comment]
this is no longer an issue...
