### ISSUE TITLE
Synthing issue - SmallPacket0x29 Warning

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4323]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** a72563e

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
After synthing an item where it takes ingredients from only part of a stack of ingredients, the remaining items in the stack cannot be moved out of inventory. (not greyed out but appear to be 'locked')? I synthed some echo drops and only used 3 Triturators and 3 Distilled water out of a stack of 9 and 11 respectively. When trying to move the remaining 6 triturators and/or the remaining 8 distilled water, the items won't move and this warning appears:
![synth](https://user-images.githubusercontent.com/30469395/33512403-69599d62-d6f5-11e7-90e4-e288ddd57e05.jpg)
I don't think this is a new issue, however I am remaking it because i searched and it appears all the synth related issues were recently closed citing a potential fix: https://github.com/DarkstarProject/darkstar/pull/4286
The workaround for this issue is to zone and the items become movable again.

**Comment by metalfiiish** [comment]
The bugs that patch fixed were all pertaining to failed synthesis. This sounds like succesful synthesis using stacks might need some looking at. Since I was reading synth stiff I can try to look into this on Monday when I get time.

**Comment by metalfiiish** [comment]
Unable to recreate. If I do the eye drop craft successfully using Triturator ( and without)  it removes everything correctly. Can you confirm exactly the craft ingredients/quantities for a single test that produces the result mentioned?

**Comment by Wiggo32** [comment]
this is no longer an issue
