### ISSUE TITLE
Server crashes when attempting to rest while sublimation charging

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4324]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** a72563e

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Changed Job to Scholar lvl 50
2. Activated Sublimation
3. Rested while HP draining
That got me a crash 3 times in a row. It said "DSGame-server.exe has stopped working" so I think that's actually a crash. Not a debug break or anything.

**Comment by teschnei** [comment]
Same crash as #4179

But keeping this one in favor of the other because it has repro steps
