### ISSUE TITLE
automaton zone and go bewm

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#4334]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
n/a

**_Server Version_** (type `!revision` in game) **:** 
90c6b9eafd04b1bcf4adddcd0c98555574893534

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
person who triggered it for me claims the crash is semi random and that all they did to trip it for me was log in, change to pup, go outside and call their auto, and then zone.

crashdump: 

https://yadi.sk/d/V56WBa2d3QHM4J

server has a few customization but noplace near where crash occurs, nevertheless vs will probably say something about source not matching.

**Comment by Jessland86** [comment]
You need to zone between two zones that allow the automaton to be out. ie west to east ronfaure.

**Comment by teschnei** [comment]
I didn't get anything good out of the dump (wasn't in debug).  I also can't
reproduce by zoning, so there must be something else to it

**Comment by zynjec** [comment]
I can't get it to crash in debug mode yet, but I can replicate it 100% of the time on Release.

Repro:
Made party with 2 members, WHM + PUP, teleported a PUP with an automaton deployed to another crystal (in this crash, going from La Theine Plateau to Konschtat Highlands via Teleport-Dem)

Not sure if it'll have any productive information being in release:
https://www.dropbox.com/s/gp4it69x6pxl4dx/pup-crash.7z

**Comment by TeoTwawki** [comment]
@teschnei I spent half the day trying to get it to happen in debug mode yesterday. Not even one. but in release mode its stupidly easy to make happen. Wtf?

**Comment by teschnei** [comment]
okay, that does give us some hints on the problem then, if it's release only

**Comment by nfaletra** [comment]
I would have to guess index out of range based on the line of code that is breaking. Or m_mobStat isn't being properly initialized for Automaton Entities.

**Comment by teschnei** [comment]
I'm thinking it's already been destroyed (this is the server they're zoning out from, right?) during Tick and PostTick doesn't know about that for some reason.  operator[] on a map can't throw out of range, and we'd likely see a bunch of other issues if the mod list wasn't initialized properly (before zoning out)
