### ISSUE TITLE
Doom tick still incorrect

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#4342]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Server Version_** (type `!revision` in game) **:** 
https://github.com/DarkstarProject/darkstar/commit/90c6b9eafd04b1bcf4adddcd0c98555574893534

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Doom counter should be 10 ticks or 30 seconds. The counter after previous fix is still incorrect. WHile players die in a most hilarious fashion many complain that 1 second is a bit unfair.

10:07:55 Bukhis readies Apocalyptic Ray
...
10:07:58 Uzi's doom counter hits 2
10:07:09 Bukhis uses Apocalyptic Ray
...
10:08:02 Uzi explodes into a pink shower of giblets
...
10:08:04 Tbone lulz

![tbone_2017 12 05_101127](https://user-images.githubusercontent.com/3310503/33620513-44087ba2-d9a5-11e7-9504-c5914f7cfc7c.png)

**Comment by teschnei** [comment]
We don't have Apocalyptic Ray scripted.

If this is an issue outside of Apocalyptic Ray, you can re-open this issue with a reproducible scenario that exists in the base repository

**Comment by R3P0FFXI** [comment]
@teschnei this is reproducible via ANY doom counter, this is the one I was given a picture for

**Comment by TeoTwawki** [comment]
i just woke up and was checking wtf they have in that cystome scriot.. its just copy paste of  minitause doom with an added damage line:

```lua
MobStatusEffectMove(mob,target,EFFECT_DOOM,10,3,30)```

 same as every doom in project

**Comment by zynjec** [comment]
I was unable to reproduce with Mortal Ray.

![image](https://user-images.githubusercontent.com/17911103/33624458-79ab6946-d9c2-11e7-9318-759ef94568cb.png)

**Comment by teschnei** [comment]
Okay, I have no way of knowing that from the original report though.

**Comment by TeoTwawki** [comment]
gimma a sec to check out r3

**Comment by TeoTwawki** [comment]
the answer is multiple scripts for one thing and to much copy pasta

@R3P0FFXI you should always check if it exists in darkstar first even if the skill and effect look the same. there is some custom global in legion (which i just hotfixed for you)
