### ISSUE TITLE
Character attributes not loading.

### ISSUE THREAD

**Issue by zynjec** [DarkstarProject/darkstar#4346]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171103_1

**_Server Version_** (type `!revision` in game) **:** 
6eacf1d4e61d2e872204495e3a0a430a17ea10cd

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Every attribute except STR is 0.

![image](https://user-images.githubusercontent.com/17911103/33642008-f64900e2-da05-11e7-82fa-96a56c9af269.png)

**Comment by teschnei** [comment]
new client update? or was this from a server update?

**Comment by zynjec** [comment]
From a server update, don't recall which revision I was on previously, but if I had to guess, it's something in this commit that broke it https://github.com/DarkstarProject/darkstar/commit/6a11cf4026102763f9aa296bcacebf71d6073b46
