### ISSUE TITLE
Server gooooooooo BEWMN

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#4356]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171103_1

**_Server Version_** (type `!revision` in game) **:** 
https://github.com/DarkstarProject/darkstar/commit/dd89310b30c21867f1ef47441db5cbb99b4275e6

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://www.dropbox.com/s/vaymv7t93uliya5/crashdump.7z?dl=0

"because teo told us to stop ~~fucking~~ guessing"
![img_0945](https://user-images.githubusercontent.com/6871475/33740538-0f8ff87a-db6f-11e7-997c-2c265aaadecf.PNG)

**Comment by TeoTwawki** [comment]
i took a short looks at call stack, saw effect flash wearing off fillowed by cbasicpacket being pushed to chars in range, died on memcopy

**Comment by teschnei** [comment]
Server ran out of memory.

![image](https://user-images.githubusercontent.com/1149183/33747098-37b04fa8-db7e-11e7-9a5b-d7883562c234.png)

Boy, must have been pretty laggy for the people with a million packets in their packet queue

**Comment by TeoTwawki** [comment]
iunno how that was even possible, but holy crap thats a lot
