### ISSUE TITLE
Zanshin Attacks triggering when not engaged

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#4357]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171103_1

**_Server Version_** (type `!revision` in game) **:** 
https://www.dropbox.com/s/vaymv7t93uliya5/crashdump.7z?dl=0

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Become a Samurai
KIll shit without even taking out your weapon
I only noticed it with Seigan/Third Eye up while running pulling mobs. Agro'd mobs would get claimed and saw a few GK skillups. Not sure if this is Seigan specific, not heavily tested.

Due to the nature of zanshin, it's possible it affects things like counter and parry too, although I haven't noticed it.

**Comment by dwn134** [comment]
It effects war retaliation also

**Comment by metalfiiish** [comment]
I think it's just a matter of adding PTarget->PAI->isEngaged()  or PTarget->PAI->isAutoAttackEnabled() in various spots of battleentity.cpp for OnAttack function. I will try to reproduce and test if this could fix it when I get some time.

**Comment by teschnei** [comment]
Retaliations check is in HandleSpikesEffect in battleutils and Seigans
counter is in CheckCounter in attack.cpp, you'd want to check engaged in
those places

**Comment by metalfiiish** [comment]
We should also look at IsParried from attackutils no? Shouldn't parry if weapon isn't drawn.

**Comment by teschnei** [comment]
Only if it is currently a problem

**Comment by teschnei** [comment]
GetParryRate checks weapon drawn, so it should be fine already

**Comment by metalfiiish** [comment]
ok cool. I'll test it as well but it sounds like it should be ok.

**Comment by metalfiiish** [comment]
This can be closed. Was able to test the fix resolved this issue.
