### ISSUE TITLE
Unusual Party/Alliance Lag

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#4372]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171103_1

**_Server Version_** (type `!revision` in game) **:** 
https://github.com/DarkstarProject/darkstar/commit/ed0fd30123d84c2db7f8298ef877d443a02c3b04

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

There seems to be unusual lag in parties and alliances since the latest update. Players exping or fighting high level NM solo do not report the issue. I do not know any other way on how to explain this other then since the last update multiple players all in parties and alliances are complaining of lag.

**Comment by nasomi** [comment]
Under zone_entities.cpp find :
case CHAR_INRANGE:

Then add:
if (((distance(PEntity->loc.p, PCurrentChar->loc.p) < 50 && (packet->id() == 13 || packet->id() == 14)) || distance(PEntity->loc.p, PCurrentChar->loc.p) < 30) && ((PEntity->objtype != TYPE_PC) || (((CCharEntity*)PEntity)->m_moghouseID == PCurrentChar->m_moghouseID)))

The result will be only movement data will be sent when distance is greater than 30m, so no spell effects/casting/etc.

**Comment by R3P0FFXI** [comment]
@nasomi if this is the fix would it not make more sense for you to PR it to DSP?

**Comment by nasomi** [comment]
I gave up on git because litterally everything i gave got rejected.
