### ISSUE TITLE
Desperate Flourish causing DSGame-Server to crash

### ISSUE THREAD

**Issue by pandorraffxi** [DarkstarProject/darkstar#4375]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
 Version 30171103_1

**_Server Version_** (type `!revision` in game) **:** 
Unknown

**_Source Branch_** (master/stable) **:**  
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Players were experiencing DSGame-Server crash when using Desperate Flourish on mobs. Was able to recreate the issue by using the JA on mobs and crashing my test server twice.

**Comment by Caladius** [comment]
Happens on my server too, it occurs when it tries to perform the math for resistance (local resist variable in the script)

**Comment by pandorraffxi** [comment]
@Caladius - Thanks for the input. I have to grab some sleep but will take another look in the morning.

**Comment by TeoTwawki** [comment]
Just tried it on latest master and had no prob.
check your desperate_flourish.lua script resist lines:
```
        local resist = applyResistance(player, target, spell, params)
```
should be line 61 of your script. and
```
            target:addStatusEffect(EFFECT_WEIGHT, 50, 0, 60 * resist);
```
at line 65

**Comment by TeoTwawki** [comment]
if those are legit, give us a crash dump

**Comment by Caladius** [comment]
ill have to grab a fresh script then:

line 61:
`if (math.random() <= hitrate or isSneakValid) then`

line 65:
`local resist = applyResistance(player,spell,target,0,player:getWeaponSkillType(SLOT_MAIN),bonus)`

**Comment by zynjec** [comment]
It's hitting a debug breakpoint on CLuaBaseEntity::getSkillLevel

**Comment by TeoTwawki** [comment]
probably had an edit conflict that was resolved incorrectly, or your out of date.

**Comment by Caladius** [comment]
grabbed a fresh script, mine must have been outdated.

ill test shortly, im on version 30171103_1

**Comment by TeoTwawki** [comment]
you want to make sure your whole repository fork is up to date, if you are on a revision prior to the resist function change you'll just have more problems

**Comment by Caladius** [comment]
yea, crashed still. I probably have a wonky build since there were other issues I have. Ill leave pandora to test.

**Comment by TeoTwawki** [comment]
catching up from chat:

![image](https://user-images.githubusercontent.com/6871475/33868214-ac219a78-decf-11e7-8729-2f163ce2d374.png)

![unknown 1](https://user-images.githubusercontent.com/6871475/33868233-c45d78aa-decf-11e7-9515-921901c6c568.png)

**Comment by TeoTwawki** [comment]
can ignore dump request. 
> [12:05 AM] Zynjec: local hitrate = getHitRate(player,target,true);
[12:05 AM] Zynjec: commenting it out entirely stops the breakpoint

till we fix it

**Comment by TeoTwawki** [comment]
#4376 should take care of this
