### ISSUE TITLE
Automation Server Crash we think...

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#4379]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171103_1

**_Server Version_** (type `!revision` in game) **:** 
https://github.com/DarkstarProject/darkstar/commit/ed0fd30123d84c2db7f8298ef877d443a02c3b04

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://www.dropbox.com/s/ppmduvxkoo57qbx/something%20about%20automatons%20and%20continents.7z?dl=0

we really don't know what triggered this, hope the dump is useful

**Comment by teschnei** [comment]
I have NO idea how TryTPMove could get into GetContinentID - the only things that call it are the resting status effect and the orcish counterstance script

I don't really know what to offer other than trying to figure out of the player (Minikay) knows how to reproduce it reliably

**Comment by R3P0FFXI** [comment]
@teschnei Minikay is Chinese the language barrier is not an easy thing to get around. I would take a fair stab at saying no he does not know how to reproduce this reliably as unless @TeoTwawki can offer anything this crash has not happened since.

**Comment by zynjec** [comment]
Stale, if anyone else experiences this, feel free to open another issue.
