### ISSUE TITLE
Master/Stable branch errors when attempting to compile

### ISSUE THREAD

**Issue by darkslayer72** [DarkstarProject/darkstar#4381]
I am trying to build the server and i get error during the compile phase.  This occurs for both the Master and Stable branches.  

In file included from src/common/kernel.cpp:27:0:
src/common/../common/taskmgr.h:32:15: fatal error: any: No such file or directory
compilation terminated.
Makefile:1905: recipe for target 'dsgame-kernel.o' failed
make: *** [dsgame-kernel.o] Error 1

I get the same error on both branches.  

sh autogen.sh (This steb works fine)
./configure --enable-debug=gdb (This step works fine)
make (This step has the error)

I do not have Client version numbers or server version numbers because i cannot get the server to compile.  Thank you.

**Comment by takhlaq** [comment]
looks like either a bad pull, or outdated gcc
could you paste the output of
`gcc --ver && g++ --ver`
`cd path/to/darkstar && git log -1 && git reset --hard && git pull`

**Comment by metalfiiish** [comment]
When I had those exact issues it was due to my gcc version being wrong as linux defaults to 5 or something.

**Comment by darkslayer72** [comment]
ffxi@ffxi-virtual-machine:~/darkstar$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ffxi@ffxi-virtual-machine:~/darkstar$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by takhlaq** [comment]
try
```
sudo su -
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install -y g++-7
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
```
and run `sh autogen.sh` again

**Comment by darkslayer72** [comment]
The server is compiling.  Thank you for the help.  

On another note 
apt-get install -y luajit-5.1-dev libzmq3-dev g++-7 mysql-client-core-5.6 mysql-server-5.6 mysql-client-5.6 (command fails)
It says that 5.6 is outdated. I did not notice this error.  When i entered the command again with mysql-client-core-5.7 ... etc it works fine and updates everything.  
I am not sure who updates the wiki for server setup but i believe thats where my problem stemmed from.

**Comment by takhlaq** [comment]
great!
yeah i think it was the symlink stuff below this block of code in the wiki which lead to this issue
for future issues could you hop into our discord and post in troubleshooting channel? we prefer to troubleshoot there instead of github to avoid sending out tons of emails for potentially lengthy discussions

**Comment by metalfiiish** [comment]
You are correct, i had that mysql issue as well. Will get the wiki updated to reflect that. Thanks for getting back to us.

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 14, 2017 at 11:31 AM, Tahir Akhlaq<notifications@github.com> wrote:   
try
sudo su -
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install -y g++-7
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

and run sh autogen.sh again
