### ISSUE TITLE
PUP TP Gain Insanity

### ISSUE THREAD

**Issue by tb1** [DarkstarProject/darkstar#4388]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171103_1

**_Server Version_** (type `!revision` in game) **:** 
unknown

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The TP gain automatons get per WS, per hit and per getting hit increases over time. The longer the pup is out, the higher it increases. I was able to get it up to 67% TP per hit after a fairly long XP session. This means the pup can WS, hit once and WS again, or WS, get hit once and WS again.

- This was test Valoredge frame and head.
- I was always level sync'd down. Unsure if this is important.
- Seems to increase with the number of hits or WSes, not purely based on time.
- Heavy use of fire maneuvers.
- Key attachments include
  - Inhibitor
  - Tension Spring
  - Tension Spring II
  - Strobe
  - Auto Repair
  - Auto Repair II
  - ... others

I think this might be related the Inhibitor's Store TP implementation, as I've seen other attachments with behaviors that are abnormal such as auto-regen and auto-refresh when no light/dark maneuvers present (Auto-Repair Kit and Manatank).

**Comment by tb1** [comment]
Server Version: f99e83d

**Comment by Hozu** [comment]
"as I've seen other attachments with behaviors that are abnormal such as auto-regen and auto-refresh when no light/dark maneuvers present (Auto-Repair Kit and Manatank)."

I wonder if the cause is effects not being deleted when maneuvers are lost. ie. the bonus keeps increasing over time whenever a maneuver is used.

**Comment by tb1** [comment]
I'm pretty sure its related to overload not erasing the effect.  I can only confirm the STP from inhibitor, as I was able to get it to over 100% during tests lasts night (leading to some fantastic WS spamming from the automation).

The evasion from Accelerator appears to have the same effect, but I don't have raw numbers to see the evasion from the puppet increase over time.

However for Auto-Repair and Manatank, you don't even need to overload for the effect to be always-on.

**Comment by aizenmyou** [comment]
@Hozu  when you see it.
https://github.com/DarkstarProject/darkstar/blob/53323c21090fc93330bd038355b8cce31ce1185f/scripts/globals/abilities/pets/attachments/tension_spring_ii.lua#L37

**Comment by Hozu** [comment]
That's certainly an error, but the other attachments @tb1 mentioned don't have that mistake in their scripts.

**Comment by aizenmyou** [comment]
Clearly, but this definitely exacerbates the underlying problem greatly. Ranger dolls should not be chunking 400 dmg normal range attacks on VT/ITs. Especially when the PUP in your party has under capped skills and  her pet is on the top of scoreboard. lol

**Comment by wrenffxi** [comment]
There's a problem with the way maneuvers are added and removed.  Consider the Auto Repair Kit.  If you do 3 light maneuvers in a row, onManeuverGain() is called thrice, with maneuvers == 1, then 2, then 3.

```
    if (maneuvers == 1) then
        pet:addMod(MOD_REGEN, 3 + bonus);
    elseif (maneuvers == 2) then
        pet:addMod(MOD_REGEN, 4); 
    elseif (maneuvers == 3) then
        pet:addMod(MOD_REGEN, 4 + bonus);
    end
```

 So your pet now has MOD_REGEN 11 + (2 * bonus).  Now let's say you overload, and all three light maneuvers are removed.  Now onManeuverLose() gets called thrice, with maneuvers == 0 all three times.  Result: your pet retains all the MOD_REGEN.

But it doesn't have to be overload.  Started with those same three light maneuvers, let's say you next use three fire maneuvers.  The first one removes a light maneuver, which calls onManeuverLose() with maneuvers == 2.  That is, it's not counting the maneuver we just removed, in the maneuvers argument.  By cycling maneuvers, you can consistently call onManeuverGain with maneuvers of 2, but onManeuverLose() with maneuvers of 1, which over time stacks your pet's buffs up to ridiculous values.

**Comment by teschnei** [comment]
OnManeuverLose is counting maneuvers after removing instead of before,
then.  Probably not too hard to fix

**Comment by Kushdr** [comment]
@teschnei you're probably talking about moving the block with this line down to after the effect is lost 
https://github.com/DarkstarProject/darkstar/blob/73aab99e1eca4f1016b7b0ec8cde497b39026dd9/src/map/status_effect_container.cpp#L442
Then to @wrenffxi point, are we properly handling the actual adding/removing for the amount? ie 3 light in a row, i'm guessing the regen overwrites itself (which is fine), but when you remove one (down to 2) you completely remove regen. Should you? Or should you remove level 3 and add level 2?

**Comment by teschnei** [comment]
Actually.. I think that's in the right spot already.  We want it to call onManeuverLose before deleting the effect, so the call gets 3 the first time, so that it removes the bonus from level 3 (and then 2 to remove level 2's and then 1 to remove level 1's).  I see the problem now, though.  Removing a status effect marks it as deleted, and then at the end of the tick it will actually remove them.  But CountStatusEffects excludes "deleted" effects, so by the time onManeuverLose is called (at the end of the tick), it thinks there are 0 maneuvers.  I think I will move all the effect removal logic to when we mark as deleted instead of the actual deletion (which should keep everything how it worked before I changed that).
