### ISSUE TITLE
December TextID's incorrect.

### ISSUE THREAD

**Issue by zynjec** [DarkstarProject/darkstar#4397]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171205_0

**_Server Version_** (type `!revision` in game) **:** 
1818f369a38061aaba295090c1bf7dd95caf80fd

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Most text ID's appear to be incorrect for the December update.

eg:
Lower Jeuno 
`Obtained: id` shows `Obtained id gil`.
Client: 6386
Darkstar: 6387

Paging @dragonarmor

**Comment by dragonarmor** [comment]
hmm  I see that now. I will address it. Thanks

**Comment by TeoTwawki** [comment]
got adjusted in master and we'll get in in stable soon, so closing
