### ISSUE TITLE
Merit EXP is lost when warping and homepoint from death

### ISSUE THREAD

**Issue by darkslayer72** [DarkstarProject/darkstar#4418]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**  
30171103_1

**_Server Version_** (type `!revision` in game) **:**  
5df79a750f1cf51c0c4c565bdb09cbe02ed7e29b

**_Source Branch_** (master/stable) **:**  
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When a player earns Merit Exp and warps out of a zone by either using a warp spell or using homepoint upon death they lose their Merit Exp that they had gained since entering the zone.  I have personally tested this and have lost my Merit Exp.  This occurs when using GM commands such as !homepoint, and !goto <player> also.  
When walking into another zone, characters do not lose merit Exp. After walking into another zone, warping and GM commands do not cause the Merit Exp loss.  On an interesting note this does not occur with normal class exp at all.

I have rebuilt the server file (preserving character data) and the problem persists.

edit by teo: fixed your markdown for you

**Comment by ShelbyZ** [comment]
That version is 10 days out and I put in a fix for an merit/limit points 5 days out - #4398
