### ISSUE TITLE
items with multiple latents are only proccing the first

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#4438]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171205_0

**_Server Version_** (type `!revision` in game) **:** 6e869c25ce874cc66dce77d586374c208239a44b

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Be a level 75 character.
Give yourself a Rajas ring.  ```!additem 15543```
Put it on.
The only latent that's being applied is the first one from item_latents.

```
INSERT INTO `item_latents` VALUES(15543, 8, 1, 51, 45); -- STR+1 above level 45
INSERT INTO `item_latents` VALUES(15543, 8, 1, 51, 60); -- STR+1 above level 60
INSERT INTO `item_latents` VALUES(15543, 8, 1, 51, 75); -- STR+1 above level 75
INSERT INTO `item_latents` VALUES(15543, 9, 1, 51, 45); -- DEX+1 above level 45
INSERT INTO `item_latents` VALUES(15543, 9, 1, 51, 60); -- DEX+1 above level 60
INSERT INTO `item_latents` VALUES(15543, 9, 1, 51, 75); -- DEX+1 above level 75
```

**Comment by TeoTwawki** [comment]
somebody dun broke it!

used to work :(
