### ISSUE TITLE
2017 contest winners

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#4443]
Since I don't know your discord/forum names, I am tagging you here so you can contact me.
@ymkc @dragonarmor

**Comment by dragonarmor** [comment]
Hello contacting you this is dragonarmorOn Dec 31, 2017 1:39 PM, whasf <notifications@github.com> wrote:Since I don't know your discord/forum names, I am tagging you here so you can contact me.
@ymkc @dragonarmor

**Comment by ymkc** [comment]
just sent you a mail @whasf

**Comment by whasf** [comment]
email me direct @dragonarmor , whasf@dspt.info
