### ISSUE TITLE
Invalid amount of ammo shown when dropped.

### ISSUE THREAD

**Issue by zynjec** [DarkstarProject/darkstar#4463]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171205_0

**_Server Version_** (type `!revision` in game) **:** 
d9bbf6591516214c068c8cf626f6bf07518bc95f

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
All ammunition seem to exhibit the same issue.

Tested: Wooden Arrow (17318), Crossbow Bolt (17336), Bronze Bullet (17343).

It shows the correct quantity in 0x028, but the resulting CMessageStandardPacket seems to truncate the quantity to 1 digit.

eg: Tossing 10 of wooden arrows results in the singular "You throw away a wooden arrow", tossing 20 of an ammo results in "You throw away 2 wooden arrows", etc.
 
![image](https://user-images.githubusercontent.com/17911103/34506982-def1173a-efff-11e7-8c1b-23d446b58143.png)

**Comment by teschnei** [comment]
Is it truncating or just dividing by 10?

**Comment by zynjec** [comment]
Looks like it's actually truncating on DSP. https://www.diffchecker.com/zbuIESP1

Crossbow Bolt (17336) being tossed on DSP vs Retail.
