### ISSUE TITLE
PuppetMaster: Cannot equip Animator and Repair Oil at same time

### ISSUE THREAD

**Issue by MoguSN** [DarkstarProject/darkstar#4495]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171205

**_Server Version_** (type `!revision` in game) **:** 86f9522

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1-75 Puppetmaster
Will not allow (any type) Animator and (any type) repair oil to be equip at same time.
equipping one just unequips the other.

**Comment by aizenmyou** [comment]
Tested and getting the same issue.
