### ISSUE TITLE
Xarcabard telepoint is missing

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#4498]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171205_0

**_Server Version_** (type `!revision` in game) **:** 
459685fa63386640ffaa8759f61b76dae3973d29

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Go to Xarcabard and position where the telepoint is supposed to be, it's not there. NPC looks ok to me in database

**Comment by zynjec** [comment]
Figured out the issue, out of date offset id in conquest.lua for Xarcabard, causing one of the supposed conquest overseers to be the telepoint.

I'll see about going through the entire file and making sure they're all up to date, but for a quick fix for anyone reading, 

`local Jeantelas = 17236290;` should be `local Jeantelas = 17236288;` for December 2017 patch.
