### ISSUE TITLE
My Name is messed up with a space ava zhella

### ISSUE THREAD

**Issue by caimartin** [DarkstarProject/darkstar#4502]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

30171205_0
**_Server Version_** (type `!revision` in game) **:** 
preventretardedgitvererror

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by zynjec** [comment]
Without any more information my suggestion to you is, don't have a space in your name.

**Comment by TeoTwawki** [comment]
Only way to get a space in your name is to manually edit the name in the database. The client doesn't allow space inputs. Not a darkstar bug.

**Comment by TeoTwawki** [comment]
@R3P0FFXI this player is from your server. Recommend rejecting space named characters in the future. pls fix the dudes name.

**Comment by TeoTwawki** [comment]
***update:***
Don't control+v into name field. The retail restriction on this is client side but an add-on/plugin is bypassing it..

**Comment by caimartin** [comment]
I was literally told to come here so you could remove it from my name. I've never played this game before and I don't use plugins. I literally typed it in like that because it's the same name I use in ff14.

**Comment by teschnei** [comment]
Hi,
Sorry, whoever told you that was wrong!  This is the issue tracker for the source code, not any particular server.  So.. we don't actually have any characters, or a database, or anything like that.  Since it's a character data issue, you should post on the forums or issue tracker for whichever server you play on.  Teo mentioned R3P0, so if you're playing on Legion, their issue tracker is at https://github.com/LegionDark/Issues.  If you post there, they should be able to help you.

**Comment by TeoTwawki** [comment]
> I was literally told to come here so you could remove it from my name. I've never played this game before and I don't use plugins. I literally typed it in like that because it's the same name I use in ff14.

@caimartin You were probably told to go to LegionDark's tracker. which is a completely different place, You can find the link on their webpage. See the guy I tagged above? he can fix it, All he has to do is open his database while you are logged out and delete the space out of your name. I'm so sorry you've had  your time wasted. I'll kick him in the caboose for you.

**Comment by TeoTwawki** [comment]
to slow teschnei beat me to it
