### ISSUE TITLE
Konzen Ittai not being tracked properly.

### ISSUE THREAD

**Issue by aizenmyou** [DarkstarProject/darkstar#4540]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171205_0

**_Server Version_** (type `!revision` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Samurai does Konzen Ittai followed by Tachi: Gekko to produce darkness. Right after I executed Blade: Metsu and created another darkness. The server isn't tracking that the first WS was already used with Konzen.

![image](https://user-images.githubusercontent.com/4256716/35836840-1e5d8648-0aa8-11e8-88eb-a6dfe9caf897.png)

**Comment by teschnei** [comment]
Konzen-Ittai (Gravitation) -> Tachi: Gekko (Distortion) = Darkness -> Blade: Metsu (Darkness) -> Darkness

That seems right to me.  Relics/Empyreans can do Dark->Dark and Light->Light

**Comment by aizenmyou** [comment]
Does retail allow you to double darkness or double light off someone's Konzen-ittai now? I have not been on since 2010 so I cannot test on retail.

**Comment by teschnei** [comment]
Yes, but only if you make the first light out of level 2 properties. Konzen
-> fudo -> fudo does not work, but konzen -> shoha -> fudo does

**Comment by aizenmyou** [comment]
Just so I understand this, does this mean that Konzen chainbound to **Gravitation** because Gekko has an L2 of **Distortion** which made Darkness, so my Metsu chained against that flat out with it's **Darkness** property?

**Comment by teschnei** [comment]
Yes, that's correct. Konzen ittai will pick the highest level skillchain it
can make with the next WS, which will then act like any other skillchain,
so your metsu can make "double darkness"

**Comment by aizenmyou** [comment]
Ah ok that's good to know. This can be closed then. Thanks Teschnei!
