### ISSUE TITLE
TARGET_PLAYER_PARTY targettype not defined properly

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4560]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171223_0

**_Server Version_** (type `!revision` in game) **:** fae4c89

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Change to pld and make sure you're not in a party
2. Use the job ability "Cover" on yourself and check error message (not retail message)
3. Form a party
4. Use the job ability "Cover" on yourself and check success message
--cover is a job ability that is only to be used on party members, not yourself
![cover](https://user-images.githubusercontent.com/30469395/36231548-0d87cb82-11a4-11e8-8547-7efeadf61a95.jpg)
This image is how the retail message is supposed to display when trying to use the ability on yourself

![cover2](https://user-images.githubusercontent.com/30469395/36231578-2d6218e0-11a4-11e8-84dc-34ef2821c710.jpg)
This image shows the dsp error message when solo "You cannot attack that target" and then the success message when in a party.
Seems like the valid target type flag is including the player as a valid target when checking for party members.

**Comment by ShelbyZ** [comment]
We actually have no implementation of Cover - missing Cover.lua

**Comment by Wiggo32** [comment]
This issue is regarding the targettype: "TARGET_PLAYER_PARTY" not being defined properly. Cover is just a job ability that you can use to see the issue in action. You can also test with Accomplice, Collaborator, Martyr, Devotion, or any Ability you choose that is supposed to target a player's party member but, NOT the player.
