### ISSUE TITLE
No Damage indication for ability "Jump" - LOLDRG

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4562]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171223_0

**_Server Version_** (type `!revision` in game) **:** fae4c89

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Change job to DRG
2. Go fight a mob
3. Use "Jump" on said mob
4. Check message, if you don't miss there should be an indication of damage dealt as in retail:
![jump](https://user-images.githubusercontent.com/30469395/36241712-87eaf460-11dd-11e8-8e91-af70a7b87ee3.jpg)

Instead, there isn't:
![jump_dsp](https://user-images.githubusercontent.com/30469395/36241726-9cae9e6a-11dd-11e8-9f9b-c652fe3bd5a8.jpg)

**Comment by TeoTwawki** [comment]
Couldv't sworn we had this happen awhile back and fixed it. Either it never made it in and got forgotten or we rebroke it :x

**Comment by TeoTwawki** [comment]
looking at history..we rebroke it somehow. the corrtec messages are in the jumpe script still.

**Comment by TeoTwawki** [comment]
I was wrong. not correct, ironically I changed the variable names to avoid confusion. what was originally "USES_JA" became "USES_JA_TAKE_DAMAGE" to distinguish the 2. SO my bad, I didn't make sure all JA's got the correct version.
