### ISSUE TITLE
@Zone crash

### ISSUE THREAD

**Issue by Crystan** [DarkstarProject/darkstar#4584]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** 30170304_1 **:** 

**_Server Version_** unknown **:** 

**_Source Branch_** master **:** 

**_Additional Information_** DMGame-Server crashes when using !send command, DMGame-server AND SQL crash when using !zone command. It worker before but doesnt work now... can't figure out why.

Additional; Since updating the commands/zone.lua script, SQL no longer crashes, just the DSGame-Server. 

ZIP FILE UPLOADED TO:

[https://ufile.io/2fqbt]

Also i have notice that alot of files in the server folder have changed icons to grey? Not sure if it is relevant...

**Comment by whasf** [comment]
I don't have the same SDK as you... it looks like you were trying to use a GM command?
Also, what version of darkstar, I don't have the same source files as you

**Comment by Crystan** [comment]
When I tried to find out the version in game it just said "unknown"... I may just try re-downloading all the files again, or perhaps just the scripts directory again.

It is very annoying because the thing used to work. ..

I was trying to use @zone command and aamslso @send command. Both crashes the server

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by TeoTwawki** [comment]
> I may just try re-downloading all the files again, or perhaps just the scripts directory again.

You really don't want part of your files being from one revisions and part of your files being from another. Fork the repository and then use git to clone your fork locally. (I suggest tortoisegit for windows users, add handy shell extensions)

Then if you add darkstar as a remote in addition to your for, you can simply use git pull to update. 

> `I was trying to use @zone command and aamslso @send command. Both crashes the server`

Github uses the `@` symbol for mentions. We stopped using it for GM commands quite some time ago now. The Public repo for Zone Ltd just got tagged, and so did Kazuaki. Github will now send them notifications for this issue in this project they have probably never heard (sorry guys! you'll have to unsubscribe) so please watch out for that in the future.

Do you already have mismatched code, and have been trying to download files to update it? It would explain a lot. Using githubs zip file option is not recommended.

**Comment by Crystan** [comment]
Thanks for the advise.  Ill be upgrading hardware as well as software this weekend anyway so I think I'll start from scratch.

The reason l for the version unknown and mismatches in the files is that I've been editing scripts since I got it running months ago and also adding my own files whilst I've been trying to develop an expansion I mentioned in old posts.

To be fair it's been running beautifully without problems and I don't have any other issues currently other than the zone command failing and airships still not 100% working...

Thanks for the advise, I'll let you know how I get on

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dwn134** [comment]
New version will be !zone instead of @zone

**Comment by takhlaq** [comment]
please don't use the `@` symbol without code tags, we changed the prefix specifically to stop spamming people
