### ISSUE TITLE
No "new player" icon after nnameflags change

### ISSUE THREAD

**Issue by zynjec** [DarkstarProject/darkstar#4585]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171223_0

**_Server Version_** (type `!revision` in game) **:** 
b72a90335be89ab6a00700c9a53794bb0e7019e4

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
- Make a new character.
- No new player icon.

**Comment by ShelbyZ** [comment]
nnnnnnnnnnnnnnnnnnameflags
