### ISSUE TITLE
Pandemonium Warden Nope

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#4587]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** current

**_Server Version_** (type `!revision` in game) **:** 8f93f76bc2cfb0fc586133ce342f40af5aadc0e1

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Paging @dwn134 

Code for Pandy Warden in #4404 is mostly in onMobEngaged(), which only is called when mob goes from white to red.  I think you meant to put most (if not all) of that in onMobFight(), which gets called over and over while the mob's fighting people.  As coded, PW never changes phases and when reduced to 1 HP remains unkillable.

**Comment by TeoTwawki** [comment]
Guessing happened when he had to rebase from my format changes, and it got right past me because github normally collapses parts of it in between the changed sections when it shows the diff so I didn't notice the function name being out of place.

paging @dwn134 !

**Comment by KnowOne134** [comment]
yes sorry looks like the rebase took 2 lines out
at line 75
end;

function onMobFight(mob,target)

ill have to download a new fork tonight and add it in as i deleted everything when i finished this pull to get caught back up to dsp
