### ISSUE TITLE
Sirius Axe causing DSP break

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4604]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171223_0

**_Source Branch_** (master/stable) **:** fae4c89

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Form a party with the Sirius Axe Equipped and check your MOD_DMG. If you are in a party of 2 and you Unequip/Re-equip the axe you can watch your MOD_DMG go down by -2 with every unequip. (I stopped at -30) Then, make sure you are party leader, have the axe equipped, and disband party. DSP should break. If not, make sure you are party leader and in a party of 3 while you unequip and then re-equip the axe before disbanding. I got the break while in a party of 2 as well as in a party of 3 while having the axe equipped and attempting to disband as party leader. I did, however, disband successfully with the axe equipped while I was party leader while in a party of 2 only one time for an unknown reason.

**Comment by zynjec** [comment]
Stale, and unable to reproduce on master, closing.
