### ISSUE TITLE
Pizza Slice causes Accuracy to go zero

### ISSUE THREAD

**Issue by Dynas13** [DarkstarProject/darkstar#4611]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
Version 30171205_0

**_Source Branch_** (master/stable) **:** 
not sure. on supernova server. 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Eat pizza slice
Use antacid
Acc is now zero

![image](https://user-images.githubusercontent.com/36946058/36828703-0f6f662e-1ce1-11e8-89d2-43ae841f6e8c.png)

**Comment by TeoTwawki** [comment]
checking

**Comment by TeoTwawki** [comment]
*Slice of Maranara Pizza*

**Comment by Dynas13** [comment]
Correct, i'm using the +1 version if it matters.

**Comment by zynjec** [comment]
![image](https://user-images.githubusercontent.com/17911103/36828798-fadb3504-1ce9-11e8-8a58-1635f810a048.png)
Seems to be working, might be an issue with the server?

**Comment by TeoTwawki** [comment]
target:delMod(MOD_FOOD_ACCP, 111); <- had a typo. was taking 111 instead of 11

**Comment by TeoTwawki** [comment]
Not a big deal but in the future helps to see the exact item name in text, at 1st I was looking at the NQ 3hr food instead of the HQ 60 min food. I just sent up the fix though. :+1:
