### ISSUE TITLE
Guild Vendors not buying all applicable items

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4617]
**_I have:_** Brass balls
![image](https://user-images.githubusercontent.com/3845823/36931629-690fa3b0-1efd-11e8-8f04-bff159dd0879.png)

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

- [ ] : Bastok Smithing Guild, Iron Cuisses

**Comment by zynjec** [comment]
Invalid issue format, closing.
