### ISSUE TITLE
[Clothcraft] Galateia not selectable after a failed synth (See screen)

### ISSUE THREAD

**Issue by lwrand** [DarkstarProject/darkstar#463]
![screen](https://cloud.githubusercontent.com/assets/8465871/4168384/bbd42ba4-351b-11e4-9581-6778267bf728.png)

If you relog, Galateias are selectable again.

/lwrand,

**Comment by JoeCT** [comment]
I just tried to reproduce this glitch and have been unable to do so.  After failed attempts at synthesizing items with galateia as an ingredient I am still able to select the item from my inventory without logging out.

**Comment by TeoTwawki** [comment]
From comments in #2373 : 

> I forgot this issue existed until now, but yeah, break a Blessed Briault synth to see this bug in action - I'm not the only one on the server I play on who ran into this.

> It happens when you break and the stack exists after the synth. I am not certain if it happens when you crystal break and/or lose items break.

Someone confirm the trigger so we can get this fixed so we don't have year+ old bugs sitting on the tracker.

**Comment by Deadwing888** [comment]
Can confirm this is still a bug. 

Additionally: if this synth is done with 2 galateia stacked and the synth critical breaks to lose one galateia two will still be grayed out and you will have two usable galateia after zoning.

**Comment by metalfiiish** [comment]
This can be closed. Fixed in patch #4286.
