### ISSUE TITLE
MOD_xxxxRES doesn't handle negative numbers properly

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4640]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30180203_1

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Equip a snow belt (or anything that produces a negative result)
2. Check mod value ("getMod")
3:
![mod_resist](https://user-images.githubusercontent.com/30469395/37182156-9fd5d3b4-22f5-11e8-8510-e4066e40901d.jpg)

**Comment by teschnei** [comment]
How are you displaying this?

**Comment by Wiggo32** [comment]
getMod(MOD_ICERES)  and print it to chatlog

**Comment by teschnei** [comment]
What are you using to print to chat log?

**Comment by Wiggo32** [comment]
https://pastebin.com/BUbFVt7C

**Comment by teschnei** [comment]
You are specifying unsigned integers in your format string, so they cannot
be negative

**Comment by Wiggo32** [comment]
well... crap... i prolly messed up

**Comment by TeoTwawki** [comment]
%d or %i for signed, I think

**Comment by teschnei** [comment]
Or just use Lua's concatenation. If you aren't doing things like fixed
width you don't really need to use a format specifier for some debugging
like this

**Comment by Wiggo32** [comment]
Yep, got it... producing proper results now... I didn't catch that. Sorry guys.

**Comment by TeoTwawki** [comment]
> concatenation
```lua
player:PrintToPlayer(targ:getName() .. "Fire Resistance is: " .., targ:getMod(MOD_FIRERES));
```
