### ISSUE TITLE
Error in Magic.lua

### ISSUE THREAD

**Issue by ReachServer** [DarkstarProject/darkstar#4641]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by ReachServer** [comment]
Line 749: Attempt to index local params (a nil value). Not sure which spell is being cast just yet.

**Comment by zynjec** [comment]
I believe this was fixed already in this commit https://github.com/DarkstarProject/darkstar/commit/d83a2e7f4d8026c5ffd6ace8038f02784191c672

Update and see if it persists.

**Comment by TeoTwawki** [comment]
if already up to date, its posisible that `params.bonusmab = params.bonusmab or 0` generates the same bs message I see in the weaponskill global where there is no "real" error but it generates the message anyway when going with the value of zero.

**Comment by ReachServer** [comment]
Teo, it's possible. Zynjec, I updated yesterday, so it's the current version.

**Comment by zynjec** [comment]
Is there a specific spell setting this off? Unable to reproduce on master.

**Comment by ReachServer** [comment]
ya trying to figure that out, one of my players was on RDM 30, so has to be a lower spell

**Comment by zynjec** [comment]
Looks like Bio is at least one spell causing the error.

**Comment by ReachServer** [comment]
Yep, I just got the same result

**Comment by warlord1352** [comment]
having the same exact issue. it seems to be so far dias,diagas,bios,drain,aspir,impact

**Comment by takhlaq** [comment]
@Whitechaser i think this was caused by AMII stuff
if you get time to, could you pr a fix?

**Comment by zynjec** [comment]
This was fixed with https://github.com/DarkstarProject/darkstar/pull/4663
