### ISSUE TITLE
unhandled game packet error

### ISSUE THREAD

**Issue by warlord1352** [DarkstarProject/darkstar#4643]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171223_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This just started coming into effect after one of the recent updates. I didn't have these errors maybe about a week ago. Not sure where they came from or what they are. I did seem to find that the 114 error seems to be connected to the map when I bring it up, and 118 seems to be connected to unity when I went into the menu. I have no clue what or where 11B is from or what "performing action 14 is." 
A couple more errors seem to be "smallpacket is not implemented 112" and "[warning] smallpacket0x03c"

![packet_errors](https://user-images.githubusercontent.com/15023912/37237820-05ad1b56-23ce-11e8-92bc-fa3358707f59.JPG)

**Comment by TeoTwawki** [comment]
its just stuff we don't have yet that would do things like populate menu's. You can optionally filter the warning out while leaving more important messages like error and debug using the console_silent filter in the map_darkstar.conf file.

**Comment by warlord1352** [comment]
Ok that's what I was thinking. I didn't think it was too important atm. Thanks again Teo!
