### ISSUE TITLE
Game Crash on Death Any Pet

### ISSUE THREAD

**Issue by Cryptexx** [DarkstarProject/darkstar#4651]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 

Master, current up to five days ago. Not seeing any commit lately that would fix this.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Reproduced the crash three times using this method:

Zone: South Gustaberg
Job: 11 Beastmaster

Charmed a bee and attacked a crab. As soon as the bee dies, the game crashes.

**Comment by Cryptexx** [comment]
Would like to add that any pet that dies will crash server with latest version.

**Comment by zynjec** [comment]
Unable to reproduce on master with charmed or jug pet, the pet dies as expected and the mobs then target the master.
