### ISSUE TITLE
drain and drain 2 abosord zero and do zero damage

### ISSUE THREAD

**Issue by lion85xx** [DarkstarProject/darkstar#4672]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by zynjec** [comment]
You didn't provide much information, but I'm guessing you're on an older build before the bandaid fix was implemented, it's seems to be functional on current master (both damaging the target, and healing the caster).

You need to be on at least this revision or more recent https://github.com/DarkstarProject/darkstar/commit/defc799049150378f4923c8b1dd1bd3d71473904

**Comment by lion85xx** [comment]
i have the last version of darkstar server donwloaded 1 week ago
