### ISSUE TITLE
Weapon skills do 0 damage and do not skillchain.

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4673]
**_I *definitely* have:_** breast cancer
![image](https://user-images.githubusercontent.com/3845823/37465465-86b8b5a0-289e-11e8-971e-534668ec5cee.png)

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30171205_0

**_Source Branch_** (master/stable) **:** 
All of the above.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Try Red Lotus Blade > Raging Fists. Neither weapon skill appears in the damage log at all. Probably related to #4672.

**Comment by zynjec** [comment]
It was actually caused by https://github.com/DarkstarProject/darkstar/pull/4657

`[Error] luautils::onUseWeaponSkill: error loading module 'scripts/globals/weaponskills' from file '.\scripts/globals/weaponskills.lua':
        .\scripts/globals/weaponskills.lua:893: ')' expected near '::'`

Looks like fixing the syntax error has restored damage.
