### ISSUE TITLE
Assiduity pants +1 not giving refresh 

### ISSUE THREAD

**Issue by Imalion1** [DarkstarProject/darkstar#4681]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (30180306_2) **:** 

**_Source Branch_** (master) **:** 

**_Additional Information_** (tied them on two seperate accounts, they worked on Legion Dark) **:**

**Comment by zynjec** [comment]
`they worked on Legion Dark`

It was custom code, unity/unity ranks don't work on darkstar so they must have just added it as a static refresh value.
