### ISSUE TITLE
Miser Murphy is a sissy

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4684]
**_I have:_** no mouth and I must scream

![image](https://user-images.githubusercontent.com/3845823/37568663-bdc17a76-2b1b-11e8-84c8-9a8503e1fa07.png)

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Miser Murphy is supposed to have a potent drain on hit effect. He doesn't. He just laid back and took it.

http://ffxiclopedia.wikia.com/wiki/Miser_Murphy

**Comment by TeoTwawki** [comment]
If someone gets me info on how his drain is actually calculated I can add that part. I'm guessing part of its % based, since a lv85 player was getting 500+ drains while a 75 player reported 100-150...I can't be THAT random, can it? btw you missed a checkbox.

**Comment by davismj** [comment]
There's like 700 commits a day, I'm not reading those.

**Comment by TeoTwawki** [comment]
lolwhat? 700 that's supper exaggerated. maybe 10 on a really busy day. 

I just skim the 1st page or 2 of commit titles on https://github.com/DarkstarProject/darkstar/commits/master nobody expects you to read the all the lines of changes in every last one of the commits. Its why we insist ppl write commit and PR titles that tell us wtf it is.

**Comment by takhlaq** [comment]
git log --grep="some string in a descriptive commit message"
git log ./path/to/file
git show <sha1>
