### ISSUE TITLE
Shields and Grips don't 'unequip' with gear scaling disabled

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4686]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30180203_1

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Disable gear scaling: https://github.com/DarkstarProject/darkstar/blob/5078b8b1b71c30af4a5fbcb9075787e5a9a3cd3f/conf/map_darkstar.conf#L90
2. Change to a high lvl Job and eqiup a high lvl shield or grip
3. Enter a 'level-capped' area (where the cap is lower than the gear equipped)
4. Check you are still wearing gear of level which is above cap.

**Comment by TeoTwawki** [comment]
guess I need a special case for those.
