### ISSUE TITLE
Magic burst does 0 damage

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4690]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I'm doing red lotus blade > raging fists (fusion) > fire II, but I've noticed that mb does 0 damage in general.

**Comment by Whitechaser** [comment]
Is it only for that particular combo of weaponskills and spells? Does Fire/Banish do 0 damage as well?

**Comment by davismj** [comment]
> Is it only for that particular combo of weaponskills and spells? Does Fire/Banish do 0 damage as well?

Tried with fire, same thing. Tried blizzard II on distortion, same thing. Tried water II on reverberation, same thing.

> And also are you on the latest version of DSP?

Yes. Teo's server.

**Comment by davismj** [comment]
I've done some more testing. Any magic burst candidate spell will hit for 0. So, a thunder cast on a fusion will also do 0 damage.

**Comment by TeoTwawki** [comment]
```lua
-- Returns a boolean if the spell's element matches the resonace given
function doesSpellElementMatchResonance(ele, resonance)
    isMatch = matches[ele + 1][resonance:getPower() + 1];
    return (isMatch ~= nil and isMatch > 0);
end
```
ele is nil
