### ISSUE TITLE
Blood weapon bug

### ISSUE THREAD

**Issue by lion85xx** [DarkstarProject/darkstar#4704]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** 30171205_0 donwloaded 20-03-18

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
no effect no hp drain no icon on desktop

**Comment by zynjec** [comment]
Closing for now, seems fine on master.
