### ISSUE TITLE
Helix spells non-functional

### ISSUE THREAD

**Issue by zynjec** [DarkstarProject/darkstar#4724]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
na

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
None of SCH's helix spells currently work due to magic changes for AMII.

`
luautils::onSpellCast: .\scripts/globals/magic.lua:751: attempt to index local 'params' (a number value)
`
Their addBonuses are using some old format to apply merit bonuses.
`
dmg = addBonuses(caster,spell,target,dmg,merit*2);
`

**Comment by zynjec** [comment]
Tagging @Whitechaser, if you get a chance.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/commit/2959a6829648d1646f5393506a98d8439105c89a
