### ISSUE TITLE
Cannot invite to party unless both players are on the same area

### ISSUE THREAD

**Issue by kaincenteno** [DarkstarProject/darkstar#4804]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180329_1

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1) Leader sends party invite when not in send area
2) Party invite is received, invitee accepts.
3) Invitee not showing in party.

This issue is resolved if both players are in the same area.

**Comment by zynjec** [comment]
Looks like an issue with multiple process servers.

Process 1 character can invite Process 1 character.
Process 1 character can't invite Process 2 character.
