### ISSUE TITLE
Orc casting poison Crashes Server

### ISSUE THREAD

**Issue by Tiger62651** [DarkstarProject/darkstar#4830]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180329_1

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Walking around to ensure things work, building server for wife and me since we miss it so much.  Worms works they cast stone fine, ran up to orc and it starts to cast poison and then server crashes.  Did it 2 times and both times it crashes.  Checking debug and it sticks at certain point in code which I couldn't figure.  Already had 1 issue where crashes loading the city Dynamis's but just deleted them from sql table, yes all events disabled.  Nothing adjusted in the lua files, just couple tweaks in settings to mainly gil starting, heal at home points and expansions enabled.  Didn't see reason to adjust more for now.  dump file 123mb big and this won't let me attach it.  Link to google drive.  Server is located in my house and only for LAN purposes.  I am new to git but not new to computers so git make it simple steps.  Searching had nothing on poison.

https://drive.google.com/file/d/1DqmZFg1Ge9NWYpCtbmVDzlKo_G5b3uz8/view?usp=sharing

Thanks for your effort and time.

**Comment by whasf** [comment]
Thanks for the dump! We need the .exe as well though
.dmp
.pdb
.exe
see https://wiki.dspt.info/index.php/How_to_Dump

**Comment by zynjec** [comment]
It crashed in getSkillLevel(), I'd be willing to bet your local version was before this fix https://github.com/DarkstarProject/darkstar/commit/30e664ded7b5c1f513b1522656fddc127e602749

**Comment by Tiger62651** [comment]
here is the exe.

zynjec, 

That would actually explain it, I just started doing this few days ago and that was just updated 3 days ago.  The spells on local doesn't match whats up there, so next question is how can I pull the updates?  Already went through all options that would seem to pull updates but just doesn't do anything.  Every time I pull it just errors and says to commit or stash so don't see options for that, so may be doing something wrong.

[DSGame-server.zip](https://github.com/DarkstarProject/darkstar/files/1977473/DSGame-server.zip)

**Comment by zynjec** [comment]
How to do it will vary with what you're using, if you're using a GUI for your git, look for a pull option, or if you're doing it from the commandline, `git pull origin master`
