### ISSUE TITLE
Evasion Down causing crashes

### ISSUE THREAD

**Issue by locojay4ff** [DarkstarProject/darkstar#4834]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180329_1

**_Source Branch_** (master/stable) **:** 
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
using ws Shield Break crashes server.
Rock lizard (South Gustaberg) and Blade Bat (Outer Horutoto Ruins) casts Inrasonics server crash.

Shield Break and any mob ability with evasion down effect crashing server.

link below is for my dmp files
https://1drv.ms/f/s!ArJRiMYozXI7gVTWXmqhaa6AaiEC

(this post maybe related https://github.com/DarkstarProject/darkstar/issues/2767)

**Comment by MalRD** [comment]
I wasn't able to reproduce this on the latest master / client. Used Shield Break and waited for the effect to wear without any crash.
