### ISSUE TITLE
Fishing doesn't work

### ISSUE THREAD

**Issue by Arthine** [DarkstarProject/darkstar#484]
When fishing if something catches you play the mini-game, if you win it says you reeled in, etc. then that you "caught a monster" but nothing is added in inventory.

**Comment by TeoTwawki** [comment]
https://github.com/DarkstarProject/darkstar/search?q=fishing&type=Commits&utf8=%E2%9C%93
mostly works now

can open new issues for any problems with it, so they can be fixed.
