### ISSUE TITLE
WeaponSkills are Broke

### ISSUE THREAD

**Issue by armouredking** [DarkstarProject/darkstar#4868]
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

30180427_2 | Master

Please fix weaponskills.lua at line 575

    if cratio < 0.38 then
        pdifmin = 0
    elseif cratio < 1.25 then
        pdifmin = cratio * 1176 / 1024 - 448 / 1024
    elseif cratio < 1.51 then
        pdifmin = 1
    elseif ratio < 2.44 then
        pdifmin = cratio * 1176 / 1024 - 775 / 1024
    else
        pdifmin = cratio - 0.375
    end

ratio is missing a C, no WS work without fixing.

**Comment by takhlaq** [comment]
https://github.com/DarkstarProject/darkstar/issues/4869
