### ISSUE TITLE
Enmity decay not functioning properly

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4893]
**This issue is ready to be pulled in**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Originally reported here: https://github.com/KupoServer/Issues/issues/3

I've confirmed that on master, fighting Roc as a MNK + RDM dual box, after about 7 minutes suddenly the mob will randomly switch aggro between either character. Prior to this, nothing will get aggro off the MNK. Seems that around the 7 minute mark both characters become threat capped.

While I would expect that as time increases the total enmity gap would close, I would not expect a meleeing RDM to outpace the 60 VE/s decay.

Sources:
- https://www.bg-wiki.com/bg/Enmity
- http://ffxiclopedia.wikia.com/wiki/Enmity
- https://www.ffxiah.com/forum/topic/47943/psa-enmity-and-you/
- http://forum.square-enix.com/ffxiv/threads/43949-Enmity-decay

**Comment by teschnei** [comment]
Why do you think you are VE capped? It sounds more like both get CE capped

**Comment by davismj** [comment]
They definitely both get CE capped. But the MNK has aggro the entire time until cap, because he is getting more threat than RDM. Once RDM and MNK get threat capped, VE should determine aggro. So the only way they would have equal threat would be if both CE and VE are capped. The only way that could happen is if VE is not properly decaying. Or do I not understand it correctly?

**Comment by teschnei** [comment]
Or VE are both bottomed out, or they are both close enough that it ping
pongs.

I would start by adding a GM command to print VE/CE (I am like 99% sure
there's an unused debug msgbasic or messagespecial or something that can be
used for that) and using that to determine what the actual issue is

**Comment by TeoTwawki** [comment]
I have a few related issues I've been testing fixes for on my server quietly...where we're not clamping values and the casting doesn't match up. This result sin some scenarios I believe cause the VE to "reset" when it should have been very high. I'm at work right now I'll point out the line on discord later.

**Comment by davismj** [comment]
> Or VE are both bottomed out, 

True.

> Or they are both close enough that it ping pongs.

Unlikely, otherwise they would be generating similar enmity and so they should be ping ponging all along.

**Comment by teschnei** [comment]
> Unlikely, otherwise they would be generating similar enmity and so they should be ping ponging all along.
not quite, their CE could be different enough (the MNK would most likely be generating most enmity from auto attacks and WS, which gives a good amount of both CE and VE, while the RDM could be generating most enmity from debuffs and other spells, which hardly give any CE.

**Comment by tectal831** [comment]
I can speak from experience our issue on Kupo is not VE bottoming out. There is something wrong with decay

**Comment by zynjec** [comment]
This issue was posted before the rewrite, open a new issue if you find new problems.
