### ISSUE TITLE
Can't see animation for other players (Digging, Mining, Harvesting, etc.)

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4959]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30180427_2

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Retail shows animations for other players:
https://youtu.be/0lQ5I8Ckv0I?t=801

**Comment by zynjec** [comment]
Just so this doesn't get lost/if I never get around to finishing my PR off, this was our discoveries on Discord:

This effect is achieved with an emote packet (0x05A) that targets the gathering node with 3 unique emote IDs and emote mode set to 2 (motion only).

```Emote 40 is Logging
Emote 41 is Mining
Emote 42 is Harvesting```

**Comment by MGramolini** [comment]
Is there one for Excavating also? Or is that considered Mining as well?

**Comment by TeoTwawki** [comment]
they are basically the same thing in the cllient
