### ISSUE TITLE
Game Server Crashes When Loading zones

### ISSUE THREAD

**Issue by RalemX** [DarkstarProject/darkstar#4982]
I updated my server this morning to the current master build.
When loading the Game Server, it crashes at "loading zones". The logs do not show any errors. 

**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**Ver30180604_0** (type `/ver` in game) **:** 

** Master ** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by RalemX** [comment]
Yesterday after posting the above, I downloaded darkstar to a new folder and rebuilt everything from scratch. I could log in and test everything up to the Mog House and logged out.
Today when I got home from work, the same issue happened. When I start the Game Server, it crashes at loading zones. No log except that it is loading zones.

**Comment by TeoTwawki** [comment]
check that your zone settings are up to date. I always forget to reset my IP after I update that table and it'll start loading zones then instantly die right there and close the window in that situation.

If that's not it, you can run it in debug and see where it is dying at so we have something to go on to help you with. https://wiki.dspt.info/index.php/How_to_Dump

**Comment by areckx** [comment]
did you load all of the sql files into the database?

**Comment by RalemX** [comment]
Those were the first two things that I checked.

**Comment by RalemX** [comment]
I am sharing a link for the dmp file per a request, hopefully it help.
https://drive.google.com/open?id=19xTOAzqPiBU9qC4oq4J6gjh8LCHqtI0R

I should mention that I did get the server running again, but am curious if there is a solution, should the issue happen to any one else.

**Comment by TeoTwawki** [comment]
> Those were the first two things that I checked.

should mention things you already tried.

> I should mention that I did get the server running again, but am curious if there is a solution, should the issue happen to any one else.

what did you do?

**Comment by helixhamin** [comment]
Fire 2, followed by thunder, then water to cool it off. Think he also used ice, but that was drink related, not server related.

**Comment by RalemX** [comment]
I downloaded the latest darkstar build to a new folder and rebuilt the Game
Server from that.
The old version is archived, but I can still run it to get the error and
dmp files if needed.
Restarted the Game Server several times and it did not crash at all.

@TeoTwawki You are right, I should have listed that I checked zone settings
and SQL files.

**Comment by TeoTwawki** [comment]
sounds like you most likely had parts of your server on different revisions. the core and sql or core and scripts not fully aligned to same revision. I've seen that happen a lot especially with people who use the zip file but it happens to folks using git as well.

And sorry but to actually use a crashdump, we also needed the matching exe and pdb files. A windows build's crashdump can't be viewed without them.

> Stick the dmp, exe, pdb, and log\map-server.log in a 7z archive and post a link to the dump in a new issue in the tracker on github. Including the log is optional, but it does help if if there's a log around the time of the crash. 

From the link I gave. Not complaining just explaining why I can't do anything helpful here.

**Comment by zynjec** [comment]
This was determined to be code/database out of sync, closing for now.

If the issue returns, just start another issue.
