### ISSUE TITLE
Rancor Flame does nothing

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4985]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [lol] checked the commit log to see if my issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Triggering the lanterns on Map 4 causes them to light up. Trading the  Rancor Flame does nothing. Triggering the door causes it to open.

**Comment by wrenffxi** [comment]
On it.
