### ISSUE TITLE
fort ghelsba elevator/lever broken

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#4998]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Guessing an ID shift killed it sinc eteh last tiem I've been out here.

**Comment by TeoTwawki** [comment]
oh no..we don't have a script for that on stock DSP..how did this not get added??

**Comment by zynjec** [comment]
This can be closed now.

https://github.com/DarkstarProject/darkstar/pull/5006

**Comment by TeoTwawki** [comment]
thansk I forgot to tag the issue in the commit that fixed
