### ISSUE TITLE
Lotting behavior does not revert after party members leave zone, but you haven't zoned

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#500]
When you're in a party and you're the first one in a zone, the lot pool automatically distributes all items to you, unless your inventory is full. When party members enter the zone, it goes to normal party lot rules. After all the party members except you zone, it still uses the party lot rules, and you have to lot all the items, or wait until the lotting timeout expires.

Classic server revision 8c29b7a
Client version 30140911_0

**Comment by maxtherabbit** [comment]
if you're in a party in retail and the only pt member in zone, does everything drop to you or sit in the pool? I can't remember

**Comment by teschnei** [comment]
Drops to you one at a time (every tick about)
