### ISSUE TITLE
Metalworks Elevators Broken

### ISSUE THREAD

**Issue by areckx** [DarkstarProject/darkstar#5002]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
1. Zone into Metalworks
2. Step onto either elevator
3. There is a chance it will start to go back down once it approaches the top or go back up when approaching the bottom.
4. Character isn't always able to exit once reaching the top or bottom.

See PR #4997

**Comment by zynjec** [comment]
I think this was also fixed with https://github.com/DarkstarProject/darkstar/pull/5006

**Comment by TeoTwawki** [comment]
Nope, they still go screwy every 5th or 7th trip or so. :-(

They'll be fine for awhile and then suddenly midway through moving they reverse direction (animation stat flips) after which the invisible doors are in the wrong state until the next cycle, trapping you on board till it moves again.

We also have a problem of the doors being open at one end of the shaft *during* movement, and we have no way to animate the moving parts the way I did with fort ghelseba yet.

**Comment by wrenffxi** [comment]
i just rode metalworks elevator 30 times in a row and nothing seemed to be out of sync. think this can close. i think #5611 may have resolved.

**Comment by TeoTwawki** [comment]
We can open a new issue if anyone spots it happening again
