### ISSUE TITLE
Ghatsad gives automaton upgrades after JP Midnight instead of Vana'diel midnight  (at lv10, lv20, & lv30)

### ISSUE THREAD

**Issue by Enzeru2018** [DarkstarProject/darkstar#5013]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Ghatsad gives automaton upgrades after JP Midnight instead of Vana'diel midnight (at lv10, lv20 & level30)

**Comment by helixhamin** [comment]
Hmm, from the documentation I see, it is "Vana'diel midnight", so is either correct?
Can you help point to the documentation that states it should be after CST midnight?

http://ffxiclopedia.wikia.com/wiki/Puppetmaster:_Upgrading_Your_Automaton
https://www.bg-wiki.com/bg/Ghatsad

> Completion Time
> The first three frames are completed after **one game day** has passed.
> The two puppet heads at levels 40 and 50 require an aforementioned wait of **2-5 in game days** based on the item traded.
> Once every in **game midnight** has passed trade Ghatsad an Imperial Coffee icon.png Imperial Coffee to encourage him to keep working for you.

**Comment by helixhamin** [comment]
Okay, you may want to change the title then so contributors know what to look into.

**Comment by waterlgndx** [comment]
Is this `vanadiel_time_offset` set properly in **map_darkstar.conf**? 
```
#Determine when "JP midnight" is.
vanadiel_time_offset: 0
```
and more importantly is `TIMEZONE_OFFSET` set properly in **settings.lua**?
```
TIMEZONE_OFFSET = 9.0; -- Offset from UTC used to determine when "JP Midnight" is for the server.  Default is JST (+9.0).
```

**Comment by zynjec** [comment]
Looks like this was fixed with https://github.com/DarkstarProject/darkstar/pull/5036
