### ISSUE TITLE
Banish II and Banish III casting time going over 100%

### ISSUE THREAD

**Issue by kaincenteno** [DarkstarProject/darkstar#5025]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Can be reproduced in dsp-oldschool

When casting Banish II, and Banish III, the casting percentage bar is already at 100% but it still takes between 1-2 seconds for the spell animation to start.

Expected behavior: When casting Banish II and Banish III, the casting percentage bar when at 100% is to start the spell casting animation.

I tried setting up the spell cast time to several values in the spell sql for banish ii and banish iii and the spell is still experiencing the same issue.

**Comment by helixhamin** [comment]
Unless it has changed from when I last saw this issue, from my understanding, spell cast lengths are still mostly older values, and have not adjusted to the newer values.

**Comment by TeoTwawki** [comment]
I think the elemental nuke ones got fixed, dunno about any others. Banish's prolly still on old values. Should be easy to check and correct comparing what we have with bg wiki.

**Comment by kaincenteno** [comment]
Are the values somewhere else than in the sql db? The issue is not that that it doesnt match current retail, the issue is that cast bar goes at 100% it is still casting-preparating for 1-2 more seconds before it shows the cast-release animation.

**Comment by KnowOne134** [comment]
It here in the sql file under cast time. 
https://github.com/DarkstarProject/darkstar/blob/master/sql/spell_list.sql

**Comment by kaincenteno** [comment]
Yes that's the sql file that I changed the cast time, and it still goes over 100%.

**Comment by KnowOne134** [comment]
Doesnt windower plugs manipulate it? If you are using windower turn off timers and recast plugins

**Comment by zynjec** [comment]
Setting cast time for Banish 2 to 2500/Banish 3 to 3000 (the current retail cast time) seems to have it complete correctly at 100%.

**Comment by TeoTwawki** [comment]
@kaincenteno 
> The issue is not that that it doesnt match current retail, the issue is that cast bar goes at 100% it is still casting-preparating for 1-2 more seconds before it shows the cast-release animation.

when the values in server don't match the client this is exactly what happens.
