### ISSUE TITLE
When a player /sit and /sitchait they do not get any agro like they should from mobs. (Works the same as /heal)

### ISSUE THREAD

**Issue by Jessland86** [DarkstarProject/darkstar#5032]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When you /sit ina zone with mobs you should get agroed the same as if you had /heal. This is not the case currently you can /sit all you want and monster watch with no fear of getting attacked by bunnies.

Pulled from:
http://ffxiclopedia.wikia.com/wiki/Emote/sit

> This command will generate low amounts of hate and can cause aggro (same as using /heal command).

**Comment by helixhamin** [comment]
That page is from 2010. Can someone with a retail account check if that information is still valid?

**Comment by helixhamin** [comment]
No problem, just wanted to check, as I know SE did some emote adjustments in 2015.

**Comment by Jessland86** [comment]
![immortality_2018 06 27_064020](https://user-images.githubusercontent.com/28382433/41969552-c551eb32-79d5-11e8-976f-ed61a0045860.png)
Updated topic as /sitchair should also generate hate/agro and it does not.
