### ISSUE TITLE
messageSpecial Packet 0x2A needs to be investigated into

### ISSUE THREAD

**Issue by Omnione** [DarkstarProject/darkstar#5089]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
In relation to a conversation on discord between myself, Teo and Zynjec, 
messageSpecial Packet 0x2A needs to be investigated into, to allow a string or player name inserted into the start of the message itself

Zynjec - Last Friday at 21:46
that message uses a format dsp isn't equipped to push out the format that packet is in

Zynjec - Last Friday at 21:47
it has 8 extra bytes compared to a normal 2a
and just shoves the player name in as straight ascii

Zynjec - Last Friday at 21:49
message id 40253
0x1E - 0x39 seems to just pipe directly to "[x] obtained item"

Zynjec - Last Friday at 21:49
message was sent by the pyxis itself
param1 is itemid

![](https://cdn.discordapp.com/attachments/336260623635841026/467432253522313216/unknown.png)

0x1D seems to be some weird... chat mode flag

![](https://cdn.discordapp.com/attachments/336260623635841026/467433481027452929/unknown.png)
vs

![](https://cdn.discordapp.com/attachments/336260623635841026/467433586908332043/unknown.png)

this is in relation to messages sent from an npc, in this case a sturdy pyxis in abyssea to all players
in a party giving notice of an action performed by a player to the npc, i.e taking an item from a chest or adding loot
to a treasure pool.

**Comment by teschnei** [comment]
https://github.com/DarkstarProject/darkstar/blob/master/src/map/packets/message_special.cpp#L56 ?

isn't that exactly what you're talking about?

**Comment by Omnione** [comment]
kind of yes, but it turns out it may just be the packet size is too small to handle some types of messages,
got some ppl looking into it now.

**Comment by Omnione** [comment]
Closing this for now as it seems messageName has fixed the problem.

**Comment by Omnione** [comment]
Closing this for now as it seems messageName has fixed the problem.
