### ISSUE TITLE
Incorrect Guild Points Items

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#5092]
**_Gingers have:_**

![image](https://user-images.githubusercontent.com/3845823/42745862-eb223c60-890f-11e8-94e2-34bd8357de5b.png)

- [ ] Beetle Earring in Goldsmithing
- [ ] All points and limits are era, about 1/3 of retail
- [ ] Lots of quotes in the sql, not one varchar field

**Comment by zynjec** [comment]
Invalid issue format, closing.
