### ISSUE TITLE
Crash on re-entering after a failed instance

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5124]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
instance code for toa and WotG areas use a different instance code than bcnm's. Found that if you do an instance and fail to complete it then anyone else goes and tries to enter it after that it the game crashes. Doesnt crash if a new instance is made i.e. group B goes in while group A is already in since it creates a brand new instance. Included is the crash dump.
https://www.dropbox.com/s/4y8lvt58w90byac/crash_enter_assault_after_loss.rar?dl=0

**Comment by teschnei** [comment]
you need to upload the pdb file and the exe too

**Comment by KnowOne134** [comment]
The one thats created when i build the server?

**Comment by teschnei** [comment]
yep,. DSGame-server_64.pdb

**Comment by KnowOne134** [comment]
https://www.dropbox.com/s/8i00nr87xlwvahu/Desktop.rar?dl=0

the exe and pdb
