### ISSUE TITLE
Mining Point in Newton Movalpolos Throws Error

### ISSUE THREAD

**Issue by Caladius** [DarkstarProject/darkstar#5147]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
- Travel to Newton Movalpolos
- Head to the tunnel at I-6 to find a Mining Point
- After receiving 5-6 Items successfully it will repeatedly state "You were unable to mine anything"
- This will continue to occur indefinitely

In the DSGame log you will see the error being thrown (Screenshot Attached)
![newton mining point i-6](https://user-images.githubusercontent.com/8377717/43350228-999d5cc2-91d3-11e8-8942-f68cb3c85db8.png)

In the Global Script utils.lua the function it is performing that is throwing the error is:

function utils.shuffle(tab)
    local copy = {}
    for k, v in pairs(tab) do
        copy[k] = v
    end

    local res = {}
    while next(copy) do
        res[#res + 1] = table.remove(copy, math.random(#copy))
    end
    return res
end

- the Mining Node will not disappear or relocate.

**Comment by zynjec** [comment]
Newton is missing positions setup in the mining.lua coordinates table.
