### ISSUE TITLE
Jailer of Temperence wont spawn

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5154]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180604_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
servervar isnt updating
getting an error on console when killing JoT, cant get it to spawn natually
luautilis::onMobDespawn: Jailer_of_temperence/lua 104 attempt to index a nil value
luautils::GetMobByID mob doesnts exist (0)

**Comment by zynjec** [comment]
Make sure your server is up to date, it appears to be working fine on master.

- Server variables aren't used at all on master.
- The other errors would suggest the localVar with the PH mobid isn't being set on Temperance at all.

**Comment by KnowOne134** [comment]
Will look when i get home. I got an error on that line as well. Will have to look at database
