### ISSUE TITLE
Wivre not using Demoralizing Roar in Bhaflau Thickets

### ISSUE THREAD

**Issue by Falendria** [DarkstarProject/darkstar#5159]
Date & Time:6:27 pm CST

Client Version (use /ver in game):30180629_2

Character Name:Falendria

Discord Name (if different from in game):Falendria

Nation:Windurst

Job(level)/Sub Job(level):99BLU/49DNC

NPC or Monster or item Name: Wivre

Zone name:Bhaflau Thickets

Coordinates (use !where):X:-543 Y:-11 Z:-70 (12)

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):Yes

Steps to reproduce:

Any additional information: Wivre only using Granite Skin, will not use Demoralizing Roar.

**Comment by KnowOne134** [comment]
No one has coded the ability yet. I have one but its not up to 100% accurate yet

**Comment by whasf** [comment]
I think this was meant for a private server GitHub, not the project itself. Closing
