### ISSUE TITLE
global errors on multicore server

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5161]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
if you run just a few zones per cluster that have a shops NPC but are outside the conquest ranking such as whitegate then these zones have no reference for the global conquest that attached to the global shops. so then it voids the global shops teleports and conquest

**Comment by KnowOne134** [comment]
i have commented out the global conquest in the shops global and i do not get errors anymore. Im not sure what damage will occur from doing this in other areas

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5162
