### ISSUE TITLE
wrong aftermath removed while equiping 2 relics

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5215]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180801_2

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
On sam equip GK relic and Bow relic perform Namas arrow over and over and will get - store TP every time the aftermath wears off until eventually you cat gain TP until you log or zone

**Comment by nfaletra** [comment]
Quick fix is renaming the aftermathLost functions to be unique per weapon.

**Comment by zynjec** [comment]
> Can you even have two different aftermaths active simultaneously in retail?

Nope, the only job its possible to even have 2 aftermaths is SAM (with gtk+bow). Lua is screwing up and running the wrong `aftermathLost` with two equipped.

**Comment by TeoTwawki** [comment]
> EDIT: Or at least melee vs ranged

lets just do that
