### ISSUE TITLE
Item Signatures cut off at certain lengths/ending with certain characters

### ISSUE THREAD

**Issue by nfaletra** [DarkstarProject/darkstar#5239]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30180904_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Character names that are 7 or 15 characters long, depending on the character they end in, could be cutoff by 1 character during the DecodeStringSignature process.

My character name "Autkast" appears as expected on signed items directly after they are created. However, when the owner of said item (could be traded or bazaared) logs out and logs back in, causing the signature to be reloaded from the DB, it appears as "Autkas".

After much debugging and bitwise math (my brain hurts), I have discovered that the issue lies in calculating the length of the original string (before it is 'encoded') in the DecodeStringSignature function here:

`
auto length = std::min<size_t>(15u, (strlen((const char*)signature) * 8) / 6);
`

To explain what is happening, the last 2 bits of the encoded string are 0 and are shoved into the 6th byte of signature. The way strlen works is it reads characters until it hits a null. In this case the 6th byte is null as far as it's concerned and returns 5 for strlen. Then the rest of the math happens and we end up with a length of 6. This is incorrect and the last 6 bits that are packed into the signature are ignored.

I have a few solutions (some are gross) but I wanted to open a discussion here rather in discord because of the amount of information I've collected (oh and Zynjec helped. His server now has a million items signed by Autkas.)

1. Add 1 to length if the math comes out to 6 or 14 (gross)
2. Store the encoded string into the DB and never decode again (also gross)
3. Add 1 to what strlen returns ALWAYS (not as gross)
4. Always loop through the max signature length of 15 characters (preferred)

Thoughts? All this bitwise math started to make my head hurt. If there's some voodoo way to make sure those last bits are always read in, I don't know it, but this decode happens so infrequently that I don't think it's a bad thing to just loop through the full 15 bitpacked bytes.

**Comment by teschnei** [comment]
We used to do 2 but I changed it so that the db could be understood more
clearly. It's probably fine to do 4, we know the max length is 15 anyways
so it's not like we risk an overflow

**Comment by nfaletra** [comment]
Yeah, DB readability made more sense. Will proceed with 4.

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/5240
