### ISSUE TITLE
Crash in The Shrine of Ru'Avitau.

### ISSUE THREAD

**Issue by buHtiGuyN** [DarkstarProject/darkstar#5244]
Hey.

**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor

There's quite a few issues already regarding Kirin but none suggest a DSGame-Server.exe crash.

- [x] checked the commit log to see if my issue has been resolved since my server was last updated

Everything's up to date.

**_Client Version_** (type `/ver` in game) **:** 

30180904_0

**_Source Branch_** (master/stable) **:** 

master

---

Happens when I'm standing in the Kirin's room in The Shrine of Ru'Avitau (-76 32 -4 178), even when he's not popped. Before or after a fight. Popped him only through !spawnmob 17506670 if that matters. DSGame-server.exe is crashing everytime (never crashed during a fight tho', yet), sometimes after a few minutes, sometimes after a while.

Explained the issue on Discord with this screenshot:

![1](https://user-images.githubusercontent.com/40763842/45919573-b8871600-be97-11e8-97e3-c1be45b7b74f.jpg)

and KnowOne suggested to put -- in front of the lines 7, 43 and 54 here (https://github.com/DarkstarProject/darkstar/blob/09b3ddfe5f24190203a2ceb225c479bcc699d045/scripts/zones/The_Shrine_of_RuAvitau/mobs/Kirin.lua) but nothing changed, crashed again.

(Teo tried to help too so thanks to him also.)

Tried one last time before writing this, crashed again:

![2](https://user-images.githubusercontent.com/40763842/45919582-e4a29700-be97-11e8-9cb9-0a7df5fd2c94.jpg)

Wanted to point out that it's not related to a recent update or something, game crashed like this since I made a server the first time (august 13).

Nothing edited on my part, even rebuilt the server from scratch (deleting the database, reinstalling everything, etc.).

Here's my DSGame-server.exe, DSGame-server.pdb files and my log folder:

[DarkStar.zip](https://github.com/DarkstarProject/darkstar/files/2407998/DarkStar.zip)

Oh and a big thanks for your work!

**Comment by zynjec** [comment]
Not able to repro on master. I've tried every combination of spawning him, his pets, etc.

Are you sure you have a clean build (executable + database)? any custom content?

**Comment by buHtiGuyN** [comment]
Yeah, rebuilt the server (the whole process, database and everything) three times. Nothing custom everytime (not my kind of thing).

**Comment by zynjec** [comment]
Without a dump (https://wiki.dspt.info/index.php/How_to_Dump), and/or exact reproduction steps, not much more we can do for you.

I spent the better part of an hour trying to recreate your issue with no avail.

**Comment by buHtiGuyN** [comment]
Gonna try to give as much details as I can : Teleported to The Shrine of Ru'Avitau using !pos with the location related in the first message, as a THF99/DNC49, GM level 4, godmode on, popped Kirin three times via !spawnmob 17506670.

Killed him mostly by spamming Mandalic Stab the first two times then Gust Slash on the last pop.

DSGame-server.exe crashed a few seconds after the last kill, no custom, nothing fancy.

Here's the files you required: 

https://drive.google.com/file/d/1u4XCGH8LYDjTNrmReoHTzxGIkwm7ROaL/view

Thanks again!

**Comment by zynjec** [comment]
Think I finally figured out what was going on.

Entities forcefully despawned with `DespawnMob` (in this case, the gods Kirin summons when he dies) don't have their stateStack cleared like it is with `CMobEntity::Die(), and they just keep stacking up without ever being popped, or until properly killed.
