### ISSUE TITLE
THF AF1 inaccurate, can't steal stew early

### ISSUE THREAD

**Issue by Mozzy4Ever** [DarkstarProject/darkstar#5247]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

30161227_1

**_Source Branch_** (master/stable) **:** 

Not sure what branch Kupo is on, but I can see in https://github.com/DarkstarProject/darkstar/blob/08f7115f028376eb4db577c465fc9cfc89abdeb7/scripts/globals/abilities/steal.lua that the info isn't accurate

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

According to https://ffxiclopedia.wikia.com/wiki/The_Tenshodo_Showdown you're able to go to Beadeaux and steal from the Quadavs for a stew after speaking to Harnek. On DSP, speaking to Harnek for the beginning of THF AF gives player:setVar("theTenshodoShowdownCS",2); however to steal a stew it's coded as (player:getVar("theTenshodoShowdownCS") == 3) to get a stew. You get var 3 if you talk to Elfriede ( https://github.com/DarkstarProject/darkstar/blob/09b3ddfe5f24190203a2ceb225c479bcc699d045/scripts/zones/Selbina/npcs/Elfriede.lua ). For DSP to be accurate, if (player:getVar("theTenshodoShowdownCS") == 3) in https://github.com/DarkstarProject/darkstar/blob/08f7115f028376eb4db577c465fc9cfc89abdeb7/scripts/globals/abilities/steal.lua simply needs to be changed to 2, not 3

**Comment by Hozu** [comment]
Seems like talking to the second NPC beforehand may not be necessary for advancing the var, unless it gives different text based on it. Or can you just trade the item to it on retail without talking to it at all?

In any case, the hardcoded mobIDs in steal.lua can probably be changed to a group/pool check or something, to avoid issues from shifted IDs.

**Comment by Mozzy4Ever** [comment]
> Seems like talking to the second NPC beforehand may not be necessary for advancing the var, unless it gives different text based on it. Or can you just trade the item to it on retail without talking to it at all?
> 
> In any case, the hardcoded mobIDs in steal.lua can probably be changed to a group/pool check or something, to avoid issues from shifted IDs.

From what it seems based on retail (though I can't double check as I don't have a retail account) once you talk to Harnek, you're able to steal the Stew. Once you steal the stew, you can talk to Elfriede to get CSID#10002 which applies theTenshodoShowdownCS == 3  as if you hadn't already stolen the stew, at which point you can trade the stew to Elfriede which triggers CSID#10004 which sets player:setVar("theTenshodoShowdownCS",4); and can then go back to Harnek for the final step. 

It's not a very important bug, but it did result in me wasting about an hour in Beadeaux trying to get a successful steal (my god that rng sucked), at which point I came here to see how it's coded to make sure I didn't miss something.

**Comment by TeoTwawki** [comment]
>I won't lie though, it doesn't really make sense that you can get the stew before talking to Elfriede... cause how are you supposed to know what Sneaking Tiger (the NPC that shows up in the Selbina cutscenes) wants? But hey, that's SE for ya.

the stew is a thing they have, you just don't know what its useful\* for till then but they still have it


###### \*can also use it to debuff mobs that steal your food effect like certain NM goblin and promy mobs that absorb your effect to themselves (but not Calibri, they dispel rather than absorb it)

**Comment by TeoTwawki** [comment]
>I won't lie though, it doesn't really make sense that you can get the stew before talking to Elfriede... cause how are you supposed to know what Sneaking Tiger (the NPC that shows up in the Selbina cutscenes) wants? But hey, that's SE for ya.

the stew is a thing they have, you just don't know what its useful\* for till then but they still have it

this makes sense to me because otherwise the item retroactively came into existence and didn't exist till it was mentioned, which seems much sillier.

RPG's being RPG's, the trope that makes this behave that way in universe is rule of relevance. so SE decided its relevant at that step I guess.


###### \*can also use it to debuff mobs that steal your food effect like certain NM goblin and promy mobs that absorb your effect to themselves (but not Calibri, they dispel rather than absorb it)

**Comment by Mozzy4Ever** [comment]
Heh, this is still open. Closing now though. Was fixed in base DSP https://github.com/DarkstarProject/darkstar/blob/08f7115f028376eb4db577c465fc9cfc89abdeb7/scripts/globals/abilities/steal.lua lines 58/59

**Comment by Mozzy4Ever** [comment]
Still incorrect on our server

**Comment by ibm2431** [comment]
To confirm, it's still a problem on DSP?

**Comment by TeoTwawki** [comment]
😕❓❔

**Comment by Mozzy4Ever** [comment]
Ah shit my bad, wrong github lmao.
