### ISSUE TITLE
Outpost warping to Tavnazian Archipelago doesn't work

### ISSUE THREAD

**Issue by tb1** [DarkstarProject/darkstar#5251]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180904_0

**_Source Branch_** (master/stable) **:** 
revision a90adc610d979d722be4fdf3f84bba5da4cd19eb 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Demiurge server
No custom for outpost warping.

When trying to OP warp to Tavnazian Archipelago, it shows the animation but you do not go anywhere.

Only tested with Jeanvirgaud (sandy), but I suspect other have similar issues.

Also noticed that repatriation (from FoV manual) has the same issue when under level sync, unsure if this is a related issue or not.

**Comment by zynjec** [comment]
Have you completed COP3-5 (Darkness Named)? It is a requirement of using the outpost, but not checked if you're eligible before giving out outpost supplies.

**Comment by TeoTwawki** [comment]
that shouldn't be the case. if you can deliver the supplies it should work. retail stops it by ensuring you can't deliver the supplies, which we have a setting to bypass. this breaks the use of the setting.

**Comment by zynjec** [comment]
It does actually check missions for supply runs, so I was incorrect there.

_**BUT**_, the issue stems from DSP not properly removing nations from the menu, and Demiurge giving all outposts at character creation. It's failing the mission check on the `eventFinish` but the event still plays the animation.

**Comment by nfaletra** [comment]
If anything the mission check should not exist, or happen earlier in the process.

**Comment by TeoTwawki** [comment]
testing a fix on demiurge, will pr if its all good when I get back.
> If anything the mission check should not exist, or happen earlier in the process.

this, there is no reason to check the mission during teleport since you only have the teleport if it is already unlocked.

**Comment by nfaletra** [comment]
There is a larger issue here with OPs showing up in the list when you shouldn't have access to them for other reasons, as well. E.G. You can select an outpost even if you do not meet the level requirements. The teleport event plays, player disappears, but the actual teleport doesn't happen. This code needs a bit of rework in general.

**Comment by zynjec** [comment]
Piping in the mask of all the outposts you have to an event, then limiting it in the eventFinish was a terrible idea.

**Comment by TeoTwawki** [comment]
#5208 now covers this

**Comment by zynjec** [comment]
This was not fixed #5157 nor will #5208 fix this.

**Comment by TeoTwawki** [comment]
@zynjec its working fine for me after my change..

**Comment by zynjec** [comment]
Clean master, with Tavanazia outpost unlocked, without having mission done.

![image](https://user-images.githubusercontent.com/17911103/46264340-ae919280-c4e9-11e8-8e23-dc5a9e8229f3.png)

It's not removed the outposts you have based on current level/mission status, so it fails the event check and just makes the player invisible.

**Comment by TeoTwawki** [comment]
check discord

**Comment by zynjec** [comment]
Everything fixes as of 27bd6f6240609d13dd5808767783b4d9cfdbcc16
