### ISSUE TITLE
Overflow Bug - Tartaruga Gigante (KSNM)

### ISSUE THREAD

**Issue by Delkathus** [DarkstarProject/darkstar#5252]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30180904_0

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

There seems to be a overflow bug that instantly kills the KSNM mob Tartaruga Gigante in one hit with Raiden Thrust when it heals for a ridiculous amount of hp. 

![image](https://user-images.githubusercontent.com/5308906/46222222-9ec55300-c31d-11e8-849f-09544cb53c7f.png)

**Comment by TeoTwawki** [comment]
guessing #3718 happened

**Comment by zynjec** [comment]
Was fixed with https://github.com/DarkstarProject/darkstar/pull/5498
