### ISSUE TITLE
Homepoints in sky crossed

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5316]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
If you go to homepoint 2 in Ru' Gardens it takes you to #3 and 3 takes you to 2

**Comment by DFPercush** [comment]
Works if porting from a different zone into sky. Problem is porting within same zone. In this case...
HomePoint#x.lua: onEventFinish() 'option' parameter == 3 for all ports, meaning hpTeleport() (globals/homepoint.lua) skips over its main 'if' block and has no effect. Commenting out hpTeleport() still warps you. It seems to be the client event that actually does the warp. That's all I got for now.
