### ISSUE TITLE
Jeuno conquest NPCs refusing to sell

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#5370]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181003-1

**_Source Branch_** (master/stable) **:** 
master, revision a20066de97b89c6b09059670f286f7ad9cfda14b

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Attempt to purchase scroll of instant warp - rejected. See screenshot

![teo_2018 11 05_145210](https://user-images.githubusercontent.com/6871475/48023095-d8eaf700-e10a-11e8-86ec-4fcc5ce0a0b6.png)

**Comment by zynjec** [comment]
Being caused by failing to meet a condition on overseerOnUpdate.

```lua
elseif guardNation ~= pNation and getNationRank(guardNation) <= pRank then 
```

The anti-cheat logic also causes the itemid to be zeroed out before sending some messages.

![image](https://user-images.githubusercontent.com/17911103/48099035-50dd1e00-e1ec-11e8-8fb9-a3128c4e48e9.png)

**Comment by TeoTwawki** [comment]
paging @wrenffxi
