### ISSUE TITLE
potency to enfeebling magic is off the scale

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5372]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30181003_1

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** cast paralyze or para 2 and the mob is stun locked the entire duration 
![image](https://user-images.githubusercontent.com/35616771/48036989-347bab80-e130-11e8-995a-a04c5cef5074.png)

**Comment by TeoTwawki** [comment]
does this always happen?



things to consider:
* merits for para2
* players lv
* mobs level
* players base+modifiers for mind stat
* meva debuff on mob? theres a spell for that now.

**Comment by KnowOne134** [comment]
i went and tried nakid as 74 rdm no extra stats no godmode, para 1 on mantigores lvl 76 in cape ter. para was at around a 80% rate
