### ISSUE TITLE
Embassy Signet is not working

### ISSUE THREAD

**Issue by Ayreos** [DarkstarProject/darkstar#538]
I'm not playing on the classic server, but on mine the embassy NPCs don't provide the option to obtain signet in the three main nations. I find it surprisingly important in the early game and it can be solved by copying the code from the gate guards, which function properly. The signet option should be available at any level, so it doesn't need any changes.

**Comment by teschnei** [comment]
f872a3540fce14d20073b1b4e9f84535d9ef72bf
