### ISSUE TITLE
changeSkin Error

### ISSUE THREAD

**Issue by githubigssan** [DarkstarProject/darkstar#539]
scripts\globals\harvest_festivals.lua

line 255 hfNpc:changeSkin(npc_costume_map[costumePair + 1]);

DSP_DEBUG_BREAK_IF(m_PBaseEntity->objtype != TYPE_MOB);

**Comment by xdemolish** [comment]
https://github.com/DarkstarProject/darkstar/commit/68a3967f9d6214251cc6f62de7eaea79b6d2c791
