### ISSUE TITLE
cant buy items from fishing guild

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5417]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181103_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
[0m luautils::onEventUpdate: .\scripts/globals/crafting.lua:279: attempt to index local 'i' (a nil value) is the error
you cant get items from the npc but you can get keyitems

**Comment by TeoTwawki** [comment]
```lua
    elseif (category == 0 and option ~= 1073741824) then -- HQ crystal
        local i = HQCrystals[bit.band(bit.rshift(option, 5), 15)];
        local quantity = bit.rshift(option, 9);
        local cost = quantity * i.cost;  -- Line 279 right here
        if (i and rank >= 3) then
```

**Comment by ShelbyZ** [comment]
https://github.com/DarkstarProject/darkstar/blob/2992d2ac7dbfccb2e08f30f593b484bc554c3619/scripts/globals/crafting.lua#L276

The fishing guild uses category 0 for items unlike the other guilds so it incorrectly reaches the code for HQ Crystals.

https://github.com/DarkstarProject/darkstar/blob/2992d2ac7dbfccb2e08f30f593b484bc554c3619/scripts/globals/crafting.lua#L254

We would most likely need to have a special case here for category 0 and guildID 0 (fishing guild id).  A quick test seems that the current handling code does not work correctly for fishing:

![image](https://user-images.githubusercontent.com/1033099/50048702-091da200-0088-11e9-8810-074338acd125.png)

**Comment by KnowOne134** [comment]
No longer a problem
