### ISSUE TITLE
woodworking guild npc in n. sandy borked

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#5443]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
n/a

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

> "Chaupire (Woodworking Vender) in the Woodworking guild is refusing to trade with me, the other vender (Cauzeriste) is trading as normal, I've tried to zone, relog, I have the up-to-date Darkstar ver."

https://github.com/Demiurge-DSP/feedback-and-info/issues/29

No customizations involving guilds or their npc scripts at all.

**Comment by ShelbyZ** [comment]
Not a bug, the guildshop (5132) has no daily increase set for items in the shop list.  If you sell a shop item you can reload the shop and find that it is that item is in stock.

Recommend to close or decide that guildshops should have a daily increase set for more items.
