### ISSUE TITLE
[Quest] Storms of fate

### ISSUE THREAD

**Issue by przemoc1** [DarkstarProject/darkstar#5465]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30181103_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** I'm doing all the steps that lead to "storms of fate" battlefield, i'm getting the cutscene when i click on Unstable displacement.
Next, when i select :storms of fate" battlefield i'm being transported into required zone but with the message "you cannot enter the battlefield at present. please wait a little longer." The battlefield doesn't start at all.
No one is doing that battlefield at the moment, so that is not the case.
I have tried to enter bf multiple times and the effect is always the same
 TextID shift maybe?

**Comment by Ninjistix** [comment]
I can also confirm several ppl on my server cannot enter this BC, upon entering the Battlefield you get the "you cannot enter the battlefield at present. please wait a little longer." and if you check it again the displacement gives you the prompt to "enter" then it just teleports you back to the same spot which I guess would be the battle field exit.

**Comment by Ninjistix** [comment]
@cocosolos #5499 
doesn't fix storms of fate, still unable to select the battlefield

![image](https://user-images.githubusercontent.com/12572974/50524965-b50eb680-0aa6-11e9-8ec5-2cfdd3092d6a.png)

**Comment by cocosolos** [comment]
@Ninjistix #5499 is that bcnm branch? [[Quest] Storms of fate pt 2](https://github.com/cocosolos/darkstar/commit/0eac39a0ba9b7ba22fb9a54df859715177c2850d) should fix for master

**Comment by Ninjistix** [comment]
@cocosolos this is from master branch build.
