### ISSUE TITLE
Automation WS can crash server since new build

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5471]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
newest

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
says NULL pointer on auto weaponskill skillschain
file dump:
https://www.dropbox.com/s/qqlffjd6qbowrur/auto_ws_crash.rar?dl=0

**Comment by nfaletra** [comment]
I think I have a fix for this on Homepoint. I'll compare the code around puppet skillchains and submit a PR.
