### ISSUE TITLE
Temp items dont remove after zoning

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5507]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
temp items just stay in temp area until tossed instead of being removed when you leave a zone

**Comment by TeoTwawki** [comment]
huh...

after we fix this, I think I want to do that  _on purpose_. 
>.>

**Comment by KnowOne134** [comment]
Maybe add a clearTempItem() command to player.lua zonein. Im sure theres a better cleaner way in map/zone though

**Comment by KnowOne134** [comment]
issue resolved
