### ISSUE TITLE
Quest Bait and Switch (does not activate)

### ISSUE THREAD

**Issue by IzzacSturnburg** [DarkstarProject/darkstar#5516]
NPC Salim - Metal Works
- reputation required lvl 3

Quest- Bait and Switch

- Missing / or does not trigger.

Wiki: https://ffxiclopedia.fandom.com/wiki/Salim

**Comment by whasf** [comment]
You could open a ton of issues for NPCs that don't have quests/missions implemented. Missing script isn't a bug, it is not implemented.
Thanks for the report though!
