### ISSUE TITLE
Mob level range is [min,max) when it should be [min,max]

### ISSUE THREAD

**Issue by DiscipleOfEris** [DarkstarProject/darkstar#5531]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30181205_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Mobs with a level range of [min, max] are only spawning with a level range of [min, max-1]. To reproduce, use some method of revealing the level of mobs (e.g. widescan or /check packets), such as my MobLevel addon, and just wander around inspecting mobs. Then compare the levels against those found in `mob_groups.sql`. You will never find a mob at the maximum end of its level range unless max==min. I've seen this on the ffera.com server.

https://github.com/DarkstarProject/darkstar/blob/e3a29080064d709d2e3218312acc994566ccd512/src/map/entities/mobentity.cpp#L518-L524

Lines 518-524 should be changed to:

    // Generate a random level between min and max level
    uint8 level = dsprand::GetRandomNumber(m_minLevel, m_maxLevel+1);

The `GetRandomNumber(min, max)` function uses a half closed interval. That is, [min, max). For integers, this means the maximum value the number generator will yield is max-1, unless max==min.

https://github.com/DarkstarProject/darkstar/blob/e3a29080064d709d2e3218312acc994566ccd512/src/common/dsprand.h#L18

Sorry this isn't a pull request. I haven't set up DSP for development yet, so I can't actually test to confirm with certainty that my suggested fix will work.

**Comment by wrenffxi** [comment]
this can close, was fixed by #5610
