### ISSUE TITLE
Talking to Zasshal crashes server

### ISSUE THREAD

**Issue by ibm2431** [DarkstarProject/darkstar#5567]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** n/a

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

@KnowOne134 [You lost your variable before setting it!](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Aht_Urhgan_Whitegate/npcs/Zasshal.lua#L70)

(And assuming the `if` block in the `onEventFinish` is after selecting permits, the last permit obtained date lines should probably be inside the block; I triggered/crashed after his "You suck, go away" event for not being a mercenary. Commenting L69 and L70 out alleviated the crash.)

edit: Unrelated to the crash, but he's also telling my character that I have Leujoam and Mamool assault points when I don't.

**Comment by KnowOne134** [comment]
Yep i see need to add csid to the event finish

**Comment by KnowOne134** [comment]
Actually, just needs the 2 lines moved up over that end

**Comment by nfaletra** [comment]
currentday doesn’t exist in that function scope at all. Moving code two lines up won’t fix anything.

**Comment by KnowOne134** [comment]
Local for currentday seems to have been not sent. But those 2 lines do need to be moved as they arent supose to be set unless the csid is 818 or 820

**Comment by KnowOne134** [comment]
local currentday = tonumber(os.date("%j"))
