### ISSUE TITLE
Sometimes skillchains are doing 0 damage.

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#5578]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30181222_1

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

1. be a DNC with access to Evisceration and Pyrrhic Kleos.
2. find a mob who can withstand a few weaponskills (I used Jormy).
3. toggle on !godmode so you can chain weaponskills.
4. use evisceration followed by pyrrhic kleos.  Often, the darkness chain effect will do 0 damage.

**Comment by TeoTwawki** [comment]
both ws themselves did dmg, just the sc was zero?

**Comment by wrenffxi** [comment]
Yes.

**Comment by nfaletra** [comment]
![image](https://user-images.githubusercontent.com/11480851/51014954-68f05700-1527-11e9-9bbb-999a353cc2fb.png)

Doing damage on Hydra on latest master. hmmm

**Comment by nfaletra** [comment]
64bit debug. I'll try to 32 and release.

**Comment by nfaletra** [comment]
![image](https://user-images.githubusercontent.com/11480851/51015188-78bc6b00-1528-11e9-9e6f-5a406039b444.png)
32bit debug on Jormy (for consistency)
I'm very confused

**Comment by wrenffxi** [comment]
Ah, have more information.  The issue seems to be that when you use a mythic weapon skill while wielding a relic weapon, aftermath.lua bonks on line 228: attempt to index field duration (a function value).

The 0-damage skillchain's just a side-effect.

**Comment by nfaletra** [comment]
Interesting. I'll take a look.

**Comment by nfaletra** [comment]
Okay. It's trying to apply a Relic Aftermath for a non-relic weaponskill. I'm sure any other combination would also cause issues. I'll put in a fix.
