### ISSUE TITLE
Sand'oria Mission 5-1 - Looping

### ISSUE THREAD

**Issue by Melodina** [DarkstarProject/darkstar#560]
OS: Linux
Sandoria Mission 5-1, Mission ID: 14

Problem:
Visiting the castle for the cutscene, then going to talk to the gate guard, you will find yourself in a loop.
The gate guard will point you back to the castle, and the everytime you zone into the castle you will receive the cutscene.

**Comment by TeoTwawki** [comment]
@Melodina does this still happen? If it was never fixed post back and let us know, often times people fixing bugs forget to link issues to the commit that fixed them. This might wind up closed soon in which case just open a new one if its still bugged.

**Comment by TeoTwawki** [comment]
Fixed with 0b02b46e5a4414eb2fb269d7a36d950de10cad65
