### ISSUE TITLE
Alchemy GP NCP asking for SCH Relic Belt

### ISSUE THREAD

**Issue by mrseatbelt** [DarkstarProject/darkstar#5636]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181205_0

**_Source Branch_** (master/stable) **:** 
Um? First try at this, sorry.

Demiurge

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Currently level 63 alchemy, Craftsman GP rotation. GP NPC Hemewmew is asking me for SCH relic belt from Dynamis as GP item for the day.

**Comment by TeoTwawki** [comment]
master branch. demi is always master branch. bleeding edge, bugs and all.
