### ISSUE TITLE
Guivre not regening

### ISSUE THREAD

**Issue by personaone** [DarkstarProject/darkstar#5661]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181222_1

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Looks like Guivre doesn't regen HP when it loses claim, i just died fighting it and it returned to spawn point, idling at 68% there for over 20 minutes now. I haven't tested other NM's but it's probable others might be affected.

Also i'm fairly certain that Guivre used to roam Kuftal (and wreak havoc!!), now it's just standing around the spawn point, separate issue i guess but still ;)

https://imgur.com/a/kU89lqN

**Comment by zynjec** [comment]
Guivre not roaming is a part of this issue https://github.com/DarkstarProject/darkstar/issues/4633

As for not healing up, going to need some information, unable reproduce on master, after it loses all entities on the enmity list, its healing back up to 100% for me.

**Comment by personaone** [comment]
ok i think i know what happened: 2 characters engaged, it kills the healer first, then kills the tank. Starts going back to spawn point -> the healer accepts re-raise that was on him and doesn't get aggroed again - i think that's what's causing it.
