### ISSUE TITLE
Bluemage drain spells 0 Dmg

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5662]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181205_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
recently has stopped working console error...
scripts/globals/bluemagic/lua:247 attemot to index local 'params' (a nil value)
blood_drain, blood_saber, digest

**Comment by TeoTwawki** [comment]
`BlueFinalAdjustments()` needs the params argument added
