### ISSUE TITLE
Dkhaayas Research Journal being flagged as an Assault Order

### ISSUE THREAD

**Issue by Delkathus** [DarkstarProject/darkstar#5683]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** v.30181222_1

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

When having the quest Olduum flagged while having the key item DKHAAYAS_RESEARCH_JOURNAL (767), it will flag the runic portal as if you have assault orders rendering it impossible to use runic portal to teleport to anywhere else other than an assault mission until the quest is completed or the Key Item is out of your KI list.

It seems that the for loop starts at LEBROS_ASSAULT_ORDERS which is (764) for some reason and processes 5 cycles for the for loop. So it will reach 767 and assume it's a assault order when it's not.

https://github.com/DarkstarProject/darkstar/blob/62029d2b90626114acb67f1f36d5e5d6d18459cf/scripts/globals/besieged.lua#L86

**Comment by KnowOne134** [comment]
Goes with my issue report also https://github.com/DarkstarProject/darkstar/issues/5616

**Comment by KnowOne134** [comment]
can close
