### ISSUE TITLE
[SW APOLLYON] Armoury Crate bug

### ISSUE THREAD

**Issue by przemoc1** [DarkstarProject/darkstar#5702]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:30181222_1** 

**_Source Branch_** (master/stable) **:master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:There is a bug that prevents Apollyon progression. Entering SW Apollyon. First, second and third floors are ok. Final floor: killing three elementals that corespond to current day element (earth elementals in this case). Final Armoury Crate should pop but it doesn't happen. You can find it kind of: it's invisible, you can target it, target description is greyed out and you can't claim it. We tried to reenter SW Apollyon several times, we killed every elemental and the effect is always the same. No Armoury Crate, no Charcoal Chip, no Apollyon progression.
Cheers
![gon_2019 02 03_143221](https://user-images.githubusercontent.com/12733817/52177660-b11c3580-27c4-11e9-8cbb-6d1e320bfa1a.png)
**

**Comment by wrenffxi** [comment]
Tons of Limbus stuff doesn't work in master. Most of the fixes are pending the merge of bcnmcrap branch, which is a rewrite of battlefields (BCNM, Dynamis, Limbus, etc.)

**Comment by przemoc1** [comment]
fixed after last update. Thank You
