### ISSUE TITLE
[QUEST] Shadows of the departed doesn't start

### ISSUE THREAD

**Issue by przemoc1** [DarkstarProject/darkstar#5703]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:30181222_1** 

**_Source Branch_** (master/stable) **:master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:Quest "Storms of fate" completed. Awakening completed, got both cutscenes (btw, it stays "active" in the mission log). Waited until next game day (and many days more). There should be a cutscene when entering palace in the Ru Lude Gardens that starts the quest but it never happens. No CS, no quest.
Cheers**

**Comment by ffxijuggalo** [comment]
This is because Shadows of the Departed as well as Apocalypse Nigh hasn't been scripted yet. So for those quests that you just completed, that's as far as the story goes at this point.

**Comment by przemoc1** [comment]
Thank You :)

**Comment by przemoc1** [comment]
Closing
