### ISSUE TITLE
SKY GODS don't drop seals

### ISSUE THREAD

**Issue by przemoc1** [DarkstarProject/darkstar#5706]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:30181222_1** 

**_Source Branch_** (master/stable) **:master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:Not much to say here. Like the title says, Genbu, Seiryu, Suzaku and Byakko do not drop their corresponding seals. It should be 100% drop IIRC. Tried several times. No seals, no Kirin fight.
Cheers
**

**Comment by TeoTwawki** [comment]
```sql

INSERT INTO `mob_droplist` VALUES (440,0,0,1000,658,40);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,12818,460);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1317,260);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1317,130);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1323,260);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1323,130);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1324,290);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1324,150);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1341,340);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1341,170);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,722,200);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,837,230);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,860,370);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1110,40);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1311,50);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1406,1000); -- Seal, 100%
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,1406,500);  -- 2nd Seal, 50%
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,18163,1000);
INSERT INTO `mob_droplist` VALUES (440,0,0,1000,18198,500);
```
that's byakko's full loot pool right there,  and he's dropping for me. check your servers table?

**Comment by przemoc1** [comment]
it's all good. i'm sorry for the mess.
