### ISSUE TITLE
[COP MISSION 3-3] The Road Forks no CS

### ISSUE THREAD

**Issue by przemoc1** [DarkstarProject/darkstar#5707]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:30181222_1** 

**_Source Branch_** (master/stable) **:master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:COP mission 3-3, Windurst route, Comedy of errors Act I. 
"Enter Windurst Waters to start this leg of the mission.
Head to Rhinostery's (Home Point #3, located on the south map of Windurst Waters) right-hand room (J-9) and talk to Ohbiru-Dohbiru in the southern wing.
Next, go to Windurst Walls (Home Point #1) and talk to Yoran-Oran at his house (E-5). You may need to speak to him 2 times; you'll know you've got it when you get the Cutscene" - this part is fine.
The bug occurs in next part. It should go like: 
"Go back to Windurst Waters (Home Point #4) to Timbre Timbers Tavern (F-10) and talk to Kyume-Romeh. You may be required to talk to him twice too; the correct conversation will be a cutscene"
But the cutscene never plays. 
Unable to finish the mission because of no CS.
cheers **

**Comment by zynjec** [comment]
If I had to guess, you didn't get the correct cutscene from Yoran-Oran.

Check the value of the player variable `MEMORIES_OF_A_MAIDEN_Status`, if it's not 4, that confirms you didn't get the proper cutscene at Yoran-Oran.

**Comment by zynjec** [comment]
Closing for now, feel free to open another issue if you're still having issues.
