### ISSUE TITLE
Promyvion CS not working and other issues.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#579]
The CS going into the boss fight at The Spire of Mea freezes ( might be other CSs as well). 

Also, the Memory Recepticles are able to 1 shot my group with Empty Seed and they still spawn 2 strays at a time. Last time I played on retail, it only did 1 stray at a time.

**Comment by TeoTwawki** [comment]
> The CS going into the boss fight at The Spire of Mea freezes 

issue report is 3yrs old and looks like it never got checked out but could have been client update related..If this still happens open us a new one please
