### ISSUE TITLE
smn carbuncle holy mist 

### ISSUE THREAD

**Issue by cutie33304** [DarkstarProject/darkstar#5797]
**_I have:_**

- [] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190202_0
**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**  
when using blood pact rage holy mist it does not work or do anything

**Comment by EpicTaru** [comment]
@cutie33304 wrong issue tracker, please close this ticket and open a new server issues ticket for HomepointXI server.

https://github.com/HomepointXI/Issues/issues
