### ISSUE TITLE
Gravity does not seem to do much, if anything, since pull 5340

### ISSUE THREAD

**Issue by TrueSalmon** [DarkstarProject/darkstar#5799]
Ever since pull 5340 (https://github.com/DarkstarProject/darkstar/pull/5340), Gravity does next to nothing. I just tried again as a fully decked out RDM75 on a DC crab in Boyahda and either it does nothing, or very little. Video here: http://enedin.be/Gravity_test.mp4

**_Client Version_** (type `/ver` in game) **:** 
30190305_0

**_Source Branch_** (master/stable) **:** 
master/stable

Supernova server

**Comment by TeoTwawki** [comment]
Your server may need to update to fix a broken `calculatePotency()` line.

https://github.com/DarkstarProject/darkstar/commit/9fa4b42cee43ad33a1acfae9c9e4aab21be83e79#diff-17797eb281d50afd474603e21a29ee58R17

**Comment by zynjec** [comment]
Not an issue with master, so nothing we can do.

Contact Supernova.

**Comment by TrueSalmon** [comment]
thanks!

**Comment by wrenffxi** [comment]
This isn't an issue with old code (we're on latest DSP).  It's changed in DSP too.  It's a result of commit #5427, which reduced weight effect from Gravity spell from -50% movement to -26% movement, and Gravity II from -60% to -32%.

**Comment by TeoTwawki** [comment]
Also possible that the effects are diff between hitting a player and hitting a monster, or that it was 26% of a diff expression of movement speed.

Like 0-100 vs 0-255

base movement speed on the server might matter as well. whatchu guys got?

**Comment by wrenffxi** [comment]
Our base movement speed is +20% for players and mobs both, but I don't think it's any difference between DSP and Supernova that's the issue.  I've tested on both.  The code works in both cases.  It's just the difference between the -50% it used to be and the -26% it is now.  -50% is easy to see.  -26% is less so, especially over short run distances.  I believe in OP's video, there is a -26% movement, it's just hard to tell.  I remember Gravity being more obvious, but these are very old memories.

**Comment by TeoTwawki** [comment]
honestly 26% in either direction should be pretty obvious, unless maaaaybe we're applying flat non % increases after it instead of before (I have not checked).

**Comment by Snugglesffxi** [comment]
our mobs set to +20% so i guess that would make our grav only -6%, guess that's why we can't see as it clearly.

**Comment by TeoTwawki** [comment]
maybe, maybe not. could still be something else. at work right now or I'd test the theory.

**Comment by wrenffxi** [comment]
It's not +20% - 26% = 6%.

Gravity slows a thing by 26% of whatever it's base speed is.  Our mob's base speed is higher than DSP.  But it's a 26% cut either way.

**Comment by TeoTwawki** [comment]
The 20 isn't even a percent. its 20/255 added to the base of 40. I was questioning when that 20 gets added by DSP (**again, let me point out this was conjecture without looking**)

**Comment by TeoTwawki** [comment]
sooo I'm seeing mob speed being off even without grav involved...catching up to me while my movement is enhanced and theirs isn't. just a regular ol statue in sky, not a raptor.

**Comment by TrueSalmon** [comment]
@wrenffxi thanks for getting involved

**Comment by wrenffxi** [comment]
Yup, I did a bunch of testing last night, and agree with Teo.  The root issue isn't gravity -- although its power was lowered from 50 to 26, the 26 value's probably right -- but instead, it's that the mob moves so much faster than the player, it's essentially capping its speed by following the player.

So when it takes a 26% movement hit, you don't notice, because it's still capping or nearly capping its speed.  It looks like the mob lags behind the player only because of the time it takes the client to be updated about mob's position.

So this issue should be reopened as something like what Teo said above: "mobs move faster than players with identical speed, and even players with enhanced mod::MOVE."
