### ISSUE TITLE
Incorrect animation when mob is killed by a counter attack

### ISSUE THREAD

**Issue by a351must2** [DarkstarProject/darkstar#580]
The wrong animation plays when a mob is killed by a Monk's counter attack.  I don't quite recognize the animation sound but it's currently similar to Dia.

**Comment by maxtherabbit** [comment]
this is a very old issue in darkstar, I believe it's related to the SUBEFFECT being wrong in the action packet for the counter, need retail caps of counters to fix

**Comment by teschnei** [comment]
Its not wrong.

**Comment by maxtherabbit** [comment]
hmm ok well *something* is off with the action packet for counters, every so often on darkstar the client will say "dingle's spikes do xx damage to the henious anus" when a counter procs

and I'd swear the counter damage is meant to appear above the entity who is being countered (taking the damage) but in DSP it shows above the one doing the counter - can't remember for certain though

**Comment by teschnei** [comment]
All I can tell you is that the subeffect (63) is right

**Comment by maxtherabbit** [comment]
ok I looked into this more, the action packet that is causing this problem has action type of 20 (ACTION_FALL) and the spikes params in the same packet

when the core generates the actions packets, it checks the mob's current action type. problem is by the time the finishing-move-counter packet gets sent to the client, the mob is already in ACTION_FALL

might need @teschnei  to tell me the best way to fix

**Comment by maxtherabbit** [comment]
1399543
