### ISSUE TITLE
Curaga Earring 

### ISSUE THREAD

**Issue by xerodok** [DarkstarProject/darkstar#5807]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **n/a** 

**_Source Branch_** (master/stable) **Stable** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Curaga Earring does not work. It fails 1 second after using saying you cannot use this at this time. Solo, Level Sync and standard party all affected.

**Comment by ValentineXI** [comment]
No associated script in scripts/globals/items. Anytime you get an instant *Unable to use* or *Unable to cast* it usually means a missing script.
