### ISSUE TITLE
blu spell pincone bomb has no spell script may be others like it

### ISSUE THREAD

**Issue by ziaxe427** [DarkstarProject/darkstar#5810]
**_I have:_**

- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
version 30190305_8

**_Source Branch_** (master/stable) **:** 
dont know what this is first time posting an issue lol

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
i did this on the dsp oldschool server where i am currently lvling blu wheneveri go to cast pinecone bomb at an enemy it cause ziaxe cannot cast or something like that.

also on a side note i cant confirm if this is a bug or an issue or not but sometimes blu spells do 0 dmg for no reason on  eenemys of any lvl and other times will do dmg. i cant confirm if this is an issue or an intended fature lol im new to this game so yea lol.

**Comment by whasf** [comment]
A missing script isn't a bug, it's just not implemented.

**Comment by zynjec** [comment]
Just because it's not implemented doesn't mean there can't be an issue, it's not exclusively for bugs.

**Comment by TeoTwawki** [comment]
if I recall correctly nobody has tackled the prob of it trying to apply its damage after it applies the sleep effect without giving up partway into the attempt yet.

**Comment by helixhamin** [comment]
Can you just apply the damage then apply sleep after to get around that issue?

**Comment by TeoTwawki** [comment]
The issue of effects getting removed by the damage exists precisely because you don’t have that ability in scripts - the damage happens at the end. We need to refactor how these work to let you do that.

**Comment by mrhappyasthma** [comment]
Are there any code pointers for this? I'd be interested in looking into this as a starter task.

Seems like this is mostly just a refactor and then implementing the script in `darkstar/scripts/globals/spells/bluemagic/`.

But I'm still quite unfamiliar with the code.

**Comment by mrhappyasthma** [comment]
Just by scanning through the code, seems like the damage is handed by calls to `BlueFinalAdjustments` here:
https://github.com/DarkstarProject/darkstar/blob/58539ad5a2c612b0041135b2349d99824a51e1b6/scripts/globals/bluemagic.lua#L247

Howeverany sleep status effect would be removed after that Lua script has executed, via this line:
https://github.com/DarkstarProject/darkstar/blob/2effc1ae16220a1a29faa7e489da7f37e91a12ee/src/map/entities/battleentity.cpp#L1304

This would be logical since `EFFECTFLAG_DAMAGE` is `0x0010` and the sleep effect appears to be `0x110010`. So doing a `&` operation would be true resulting in the sleep being removed.

**Comment by mrhappyasthma** [comment]
Assuming my code tracing to be correct, I see a few potential ways forward:

- Add new state to `CSpell` to indicate that the spell should not remove sleep effects after applying damage.

- Provide a new Lua method callback along the lines of `onSpellCompletion` to allow for applying effects after the damage has been applied.

- Perform a larger refactor of `CBattleEntity::OnCastFinished()` and `luautils::OnSpellCast()` to make the order of operations more explicit.

Let me know if I'm on the right track and what the preference here would be.

**Comment by TeoTwawki** [comment]
I think we need the refactor anyway so that we utilize functionality we've already added elsewhere. retails blue mage spells are more like ws that cost mp than anything else I think, and we already tackled the effect+dmg problem for those (shockwave)

**Comment by mrhappyasthma** [comment]
I'll start on a refactor that mirrors how the weapon skill works.

**Comment by mrhappyasthma** [comment]
The refactor seems to work. The sleep effect is no longer canceled by the damage. And if the target was already slept before the spell was cast, the damage undoes that sleep and then correctly applies a new sleep state afterwards.

However I'm having a bit of trouble with the message. Since this has essentially two effects: damage and sleep, I'm not clear how to print them both out.

For example: https://i.imgur.com/gDPV6jr.jpg

I would expect something more like:

>  Mrhappyasthma casts Pinecone Bomb
> The Dameselfly takes 8 points of damage.
> The Dameselfly is asleep.

**Comment by TeoTwawki** [comment]
normally you would not get 2 messages. retail usually does not do that and I'd pretty much need some kind of proof before believing we found one of those rare instances. In nearly all cases of both damage and effect at the same time, retail will just show the damage.

**Comment by mrhappyasthma** [comment]
Oh okay, great. Then that's WAI.

I'll clean up this a bit and try to get a PR out.

Is there a preference to keep both the refactor + pinecone_bomb.lua into a single PR? Or do you prefer to split them to keep PRs small?

**Comment by TeoTwawki** [comment]
sorry about not getting back to you on your earlier messages, I just kinda check my notifications in between tasks at work.

Have you joined the discord? usually more ppl around to help during the day there https://discord.gg/4dgAzfC

**Comment by mrhappyasthma** [comment]
Oh, I hadn't seen that. I'll join! Thanks :)

**Comment by TeoTwawki** [comment]
> Is there a preference to keep both the refactor + pinecone_bomb.lua into a single PR? Or do you prefer to split them to keep PRs small?

we try to keep separate things in separate pr but occasionally allow misc minor fixes lumped together and an example script of new stuff scripted allow with a refactor is usually ok

**Comment by KnowOne134** [comment]
I had found the message from a retail capture and added it but left the
spell alone like a year ago. Can search for it

**Comment by mrhappyasthma** [comment]
Just to close the loop here: still working on the refactor. It'l touch most damaging dealing spells, so being careful to audit them all first to make sure I don't miss any code paths.

Will propose the pinecone_bomb.lua after the refactor since that's the bulk of the complexity.

**Comment by mrhappyasthma** [comment]
I have the `pinecone_bomb.lua` ready. But I'm away on business travel. Will send a PR to close this out once I get home.
