### ISSUE TITLE
when version lock is set to expected version and higher will sometime still lock higher version

### ISSUE THREAD

**Issue by KnowOne134** [DarkstarProject/darkstar#5816]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
the version check only checks the last 3 digits
```expected_version = expected_version + "xx_x";```
so if the newest version changes 4 digits and the last 3 are lower it will trick it into thinking its a lower than expected

**Comment by TeoTwawki** [comment]
Its intended to be the revers:  ignoring the last 3 and not look at them at all

**Comment by TeoTwawki** [comment]
> and the last 3 are lower

Yeah its not last 3 lower causing whatver you saw, I just checked. Last 3 are 100% ignored

```cpp

                string_t client_ver_data((char*)(buff + 0x74), 6); // Full length is 10 but we drop last 4
                client_ver_data = client_ver_data + "xx_x";          // And then we replace those last 4..

                string_t expected_version(version_info.client_ver, 0, 6); // Same deal here!
                expected_version = expected_version + "xx_x";
                bool ver_mismatch = expected_version != client_ver_data;
                bool fatalMismatch = false;

                if (ver_mismatch)
                {
                    ShowError("lobbyview_parse: Incorrect client version: got %s, expected %s\n", client_ver_data.c_str(), expected_version.c_str());

                    switch (version_info.ver_lock)
                    {
                        // enabled
                        case 1:
                            if (expected_version < client_ver_data)
                            {
                                ShowError("lobbyview_parse: The server must be updated to support this client version\n");
                            }
                            else
                            {
                                ShowError("lobbyview_parse: The client must be updated to support this server version\n");
                            }
                            fatalMismatch = true;
                            break;
                        // enabled greater than or equal
                        case 2:
                            if (expected_version > client_ver_data)
                            {
                                ShowError("lobbyview_parse: The client must be updated to support this server version\n");
                                fatalMismatch = true;
                            }
                            break;
                        default:
                            // no-op - not enabled or unknown verlock type
                            break;
                    }
                }
```
If the digits before those are lower the version is nit newer, its older.

**Comment by KnowOne134** [comment]
ill update to current to test tomorrow, ive had people from what they said was newest build say they cant login and i removed version lock all together

**Comment by TeoTwawki** [comment]
Be sure and get the log messages so we see the compares

**Comment by KnowOne134** [comment]
i dont know what some of these players are doing, i didnt have the issue myself but had 3 new people say they couldnt login from a fresh build. No problem on my end with a fresh build though

**Comment by TeoTwawki** [comment]
Probably installing an older version (either official or custom installer) and think they have updated when they really have not, or their version is "unknown" from some change _after_  their update.

common mistakes include doing a file check and thinking it updated, and selecting pol viewer instead of ffxi, and applying the patch file after the update.
