### ISSUE TITLE
WSNM NPCs not accepting finished weapons

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#5839]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190305_0

**_Source Branch_** (master/stable) **:** 
oldschool.dspt.info (stable?)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Accepted quests and received trial weapon
Used weapon skills/skill chains until latent was gone
Attempted to trade weapon to quest NPC
No response from NPC

Did this with multiple characters -- tested with sword, h2h, and dagger. Same "no response" for each quest NPC.

**Comment by KnowOne134** [comment]
Seen it myself. Its skipping giving out the keyitems sometimes. Not sure why.

**Comment by xipies** [comment]
My characters did get the Weapon Training Guide keyitem.
