### ISSUE TITLE
Guard proc without native hand-to-hand skill

### ISSUE THREAD

**Issue by isotor** [DarkstarProject/darkstar#5850]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30190328_2

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Guard can proc on jobs without native hand-to-hand skill (any job attacking without a weapon). It should only be possible to guard with MNK or PUP set as main or sub job. Unsure how this interacts with skill gained from guard merits when otherwise the skill wouldn't exist.

**Comment by zach2good** [comment]
Relevant area (maybe):
https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/attackutils.cpp#L120
