### ISSUE TITLE
Learning Blue Magic

### ISSUE THREAD

**Issue by hargrave81** [DarkstarProject/darkstar#5864]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
N/A

**_Source Branch_** (master/stable) **:** 
master and stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
ffera.com

So unless there is some dark code in some corner of the source, or I am just very unlucky with learning blue spells, it appears the learning rate is very random and the AF hands do not affect the learning rate.

https://github.com/DarkstarProject/darkstar/blob/5b252b982291bbb50e597e6cb12f181a20ff4728/src/map/utils/blueutils.cpp

Function on Line 79: **void TryLearningSpells**

                // TODO: check for blue learning bonus and adjust base percent
                if (dsprand::GetRandomNumber(100) < 33) {

that code is in that function, it only checks a random number to see if its a 33% chance to learn.  The gloves do not alter the 33% in any way (say give it a 50% change to learn)  Rendering the gloves useless.

**Comment by helixhamin** [comment]
Yep, pretty much xD

**Comment by Delkathus** [comment]
rng is a bitch
