### ISSUE TITLE
Characters should be removed from Dynamis on time expiry

### ISSUE THREAD

**Issue by isotor** [DarkstarProject/darkstar#5873]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30190328_2

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Mobs correctly despawn but players can continue to derp around in the otherwise empty zone.

**Comment by whasf** [comment]
I'm not surprised... the whole "BCNM" system we have now is neglected and needs to be replaced by the new BCNM branch.

**Comment by Delkathus** [comment]
Any expected timeframe on when bcnmcrap will be considered complete enough to merge?

**Comment by TeoTwawki** [comment]
when they entire team gets so sick of it they decide its ok to temporarily break what remains on master to get it done, probably.

**Comment by TeoTwawki** [comment]
open new issue if this is still happening
