### ISSUE TITLE
Dragon Kick description?

### ISSUE THREAD

**Issue by personaone** [DarkstarProject/darkstar#5900]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190328_2

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Create a new character, cap hand-to-hand skill, take a look at Dragon Kick description, seems like Asuran Fists (8 fold attack). Cosmetic but still ;) here;s a screenshot https://imgur.com/yymKW03

**Comment by zynjec** [comment]
Bug with the client, nothing we can do about it.
