### ISSUE TITLE
Magic Burst timing

### ISSUE THREAD

**Issue by personaone** [DarkstarProject/darkstar#5912]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190328_2

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
It looks like the MB window is way shorter than i remember it on retail, right now it seems like you have to almost immediately start casting the spell as soon as the last weapon skill goes off. It used to be a pretty long window, where you could start casting a spell around when you saw the skillchain animation go off, not as soon as someone used the last WS.

**Comment by zynjec** [comment]
From [BGWiki](https://www.bg-wiki.com/bg/Magic_Burst):
>This window lasts for 10 seconds after the final Weapon Skill, just as the Skillchain animation is appearing.
> The magic burst opportunity is ended prematurely if any additional weapon skill is used on the target during the window.

We're currently applying `EFFECT_SKILLCHAIN` with a duration of 10 seconds at the end of a skillchain:
https://github.com/DarkstarProject/darkstar/blob/311b593d1f292784dd65d82eb93474e5aa4a6fc2/src/map/utils/battleutils.cpp#L2861

Unless you have more solid proof of this either not working properly (debugging/actual timing and not feels and how you remember it), or the 10 second window not being an accurate figure any more, seems to be fine.

**Comment by TeoTwawki** [comment]
Worth mentioning that you don't have retail's lag. That will throw your timing a bit.

**Comment by ibm2431** [comment]
For anyone wanting to do testing: remember to have BattleMod or something else that removes the built-in client message delay.

**Comment by personaone** [comment]
I figured a video would work best, i'll try but for now, here's a log extract of what's going on:
[11:50:23] Sapphire uses Blade: Metsu.
The Greater Manticore takes 717 points of damage.
[11:50:25] Sapphire hits the Greater Manticore for 80 points of damage.
[11:50:26] Tazzy hits the Greater Manticore for 57 points of damage.
[11:50:26] Sapphire scores a critical hit!
The Greater Manticore takes 108 points of damage.
[11:50:26] Tazzy readies Knights of Round.
[11:50:28] Sapphire hits the Greater Manticore for 85 points of damage.
[11:50:28] Sapphire's Copy Image effect wears off.
[11:50:28] 1 of Sapphire's shadows absorbs the damage and disappears.
[11:50:29] Sapphire hits the Greater Manticore for 67 points of damage.
[11:50:30] Tazzy uses Knights of Round. **This is when the 2nd WS is used**
The Greater Manticore takes 346 points of damage.
[11:50:31] Sapphire misses the Greater Manticore.
[11:50:32] Sapphire hits the Greater Manticore for 66 points of damage.
[11:50:32] Tazzy misses the Greater Manticore.
[11:50:33] Skillchain: Light.
The Greater Manticore takes 346 points of damage.
[11:50:34] Sapphire hits the Greater Manticore for 77 points of damage.
[11:50:35] Tazzy starts casting Thunder III on the Greater Manticore. **Start casting after the skillchain animation goes off or is almost finished**
[11:50:35] Sapphire hits the Greater Manticore for 74 points of damage.
[11:50:37] Sapphire parries the Greater Manticore's attack with her weapon.
[11:50:38] Sapphire scores a critical hit!
The Greater Manticore takes 348 points of damage.
[11:50:38] Sapphire hits the Greater Manticore for 69 points of damage.
[11:50:41] The Greater Manticore readies Great Sandstorm.
[11:50:41] Tazzy hits the Greater Manticore for 54 points of damage.
[11:50:41] Sapphire hits the Greater Manticore for 78 points of damage.
[11:50:42] Sapphire hits the Greater Manticore for 66 points of damage.
[11:50:42] Tazzy casts Thunder III. **No MB happens**
The Greater Manticore takes 576 points of damage.

It seems too restrictive to me, I usually used to cast a spell to MB a skillchain when i saw the animation of the skillchain appear, maybe this was the retail lag causing that....?

**Comment by ibm2431** [comment]
Skillchains happen _immediately_ after the closing weaponskill. By the time you started casting, the window was already halfway over.

Hence:
> remember to have BattleMod or something else that removes the built-in client message delay

**Comment by personaone** [comment]
> Skillchains happen _immediately_ after the closing weaponskill. By the time you started casting, the window was already halfway over.
> 
> Hence:
> 
> > remember to have BattleMod or something else that removes the built-in client message delay

I see, well I guess then it's working properly, just doesn't seem to reflect what I used to remember from playing retail. Also can't get battlemod working for Ashita, looks like it's a test version and fails to load atm.

**Comment by ibm2431** [comment]
The problem stems from how the client will sit on its hands for a bit after it receives an action packet before displaying it in the log. It's not really "server lag" per se, but a built-in delay. Your client _got_ the action message packet for KOTR and Light right when KOTR went off, but decided to wait a bit before acting on Light (playing the animation and showing the damage).

I suggested BattleMod because it doesn't screw around like the client does - it lets you know the skillchain damage the moment the action packet comes in. If you're handy with Ashita addons (I'm not, so I couldn't help there), you might be able to bang something together to print when a skillchain action packet comes in, then you can see the difference between when your client got word of Light, and when the client bothered to actually try to tell you.

**Comment by TeoTwawki** [comment]
on retail I always had to start my cast _before_ I saw the closing ws action, and on dsp that is often to soon. So I now start my cast at closing ws but before the SC animation and that works out. from their log their cast completed at at 12 seconds, and that time they started is about when they needed it to end.

/shrug

**Comment by personaone** [comment]
Aight - closing.

**Comment by helixhamin** [comment]
Yeah, that is why we had SC/MB announce macros for HNMs.
