### ISSUE TITLE
problems with @cs GM command.

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#592]
Server looks like it is treating use of the command the same as actually triggering zone-in-cs and running the zones onEventFinish.

I was already zoned in and used the (AT)cs command to test for params to help me find the value to look for in a dump gedads gave me. Log showed "[13:58:48][Warning] Lua::completeMission: completion of not current mission" and then wiped my test char's already cleared missions for that mission line as a side effect... That's not supposed to happen. While you should never be trying to re-clear a non current mission, the code to cause that situation shouldn't have been active in the first place. This shouldn't have been any different from the replay NPC's in retail.

Edit: apologies to whoever the github user "cs" is, forgot they use the at symbol that way here.

**Comment by xdemolish** [comment]
not really a bug as there's no way for a regular player to trigger cutscenes of their choosing at will (they get what they deserve if they manually force it)
as for the mission wiping, that should be in another issue entirely :p

**Comment by TeoTwawki** [comment]
Its a problem when trying to test yer shit demo. The GM characters mission log shouldn't have been touched at all.
