### ISSUE TITLE
Rank points not increasing for Fetichism mission

### ISSUE THREAD

**Issue by lyptt** [DarkstarProject/darkstar#5938]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190328_2

**_Source Branch_** (master/stable) **:** 
stable

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
I've completed the mission already once, so this is the repeated version of the mission. I've noticed that my rank points don't increase at all, even though I'm now rank 2 and the mission should in theory be giving me rank points.

This is based on what is described here: https://ffxiclopedia.fandom.com/wiki/Fetichism

**Comment by lyptt** [comment]
Added fix in PR #5939

**Comment by TeoTwawki** [comment]
see also: #1168

**Comment by lyptt** [comment]
Yeah sorry I didn't see the other issue, I believe no-one else has filed a PR for it yet at least 🙂

**Comment by TeoTwawki** [comment]
no prob; I closed the old one, it was along ago forgotten
