### ISSUE TITLE
Party/Alliance issues after retail update

### ISSUE THREAD

**Issue by vickycat** [DarkstarProject/darkstar#598]
1. While in a party, entering your mog house will show you as solo until you leave the mog house. You can still chat with the party and they can see you in the mog house.

2. If the party leader logs out, leadership is not transferred to another member

3. Forming an alliance often doesn't send an invitation. Really spotty when it works. Sometimes it will work if the other party invites you to an alliance instead.

4. If you do manage to form the alliance, the allied party shows below the party UI (they're offscreen)

**Comment by xdemolish** [comment]
wasn't able to crash the server with my 3 man alliance, guess this has been fixed
