### ISSUE TITLE
Merged code that is supposed to make Death spell ignore shadows does not do so

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#6025]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30190430_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

#5954 adds `dsp.magic.spellFlag.IGNORE_SHADOWS` to Death spell, but this flag does not exist on SpellFlag Enum in either LUA or Core.

**Comment by TeoTwawki** [comment]
fk'n hell, I coulda swore I searched that before merging..sigh

**Comment by TeoTwawki** [comment]
@isotor test this for me, we're both responsible https://github.com/DarkstarProject/darkstar/commit/261e161614186fb2a539a6d46ca2ccfccbca38a1
