### ISSUE TITLE
Conquest system sql error crashing map server

### ISSUE THREAD

**Issue by thunderdragon21** [DarkstarProject/darkstar#6047]
[02/Jun] [02:31:53][1;35m[SQL][0m DB error - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
SQL: SELECT region_control FROM conquest_system WHERE region_id = 
I am not sure what is causing it. Just updated to the new stuff of the site and now getting this problem Id appreciate any help.

**Comment by KnowOne134** [comment]
Problem with vs19. Downgrade back to vs2017 and toolset 241 until it's fixed

**Comment by thunderdragon21** [comment]
ty but where do i find toolset 241 i looked all over for it?

**Comment by TeoTwawki** [comment]
toolset 141, not 241.

![toolset](https://user-images.githubusercontent.com/6871475/58769182-82e01400-8572-11e9-9f18-058d27fed970.jpg)

**Comment by thunderdragon21** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8020	The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	DSConnect-server	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets	67	
Getting this error with 141.

**Comment by TeoTwawki** [comment]
because you need to select v141 before it can use it..it litteraly tld you how to fix it in that message you pasted.

**Comment by thunderdragon21** [comment]
ok i got it now ty sorry just dawned on me

**Comment by ZatuyouTantou** [comment]
`int` ret = Sql_Query(SqlHandle, Query.c_str(), region);`

use static_cast.

`int ret = Sql_Query(SqlHandle, Query.c_str(), static_cast<uint8>(region));`

**Comment by Begocent** [comment]
Hello, what i did to fix this error was to change the enum REGIONTYPE from uint8 to uint16 at src\map\zone.h and now i compile the project with vs19.
