### ISSUE TITLE
Hybrid-class weaponskills bonk weaponskills.lua

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#6049]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30190430_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

* Be a SAM75 using a great katana.
* Use Tachi: Jinpu (or any other hybrid-class weapon skill)
* See "{Your name} uses Tachi: Jinpu" in the log, but no damage/aggro from mob.
* See in console: `[Error] luautils::onUseWeaponSkill: .\scripts/globals/weaponskills.lua:968: attempt to perform arithmetic on local 'numHits' (a nil value)`

**Comment by ibm2431** [comment]
I did test some hybrids, I swear! (And I didn't touch `getMultiAttacks`)

Apparently Jinpu doesn't have a numHits value defined in its param table, and it being a "magical" weaponskill at the time, it never went into getMulti, so it hadn't been caught.

Blade: Teki, Blade: To, and Tachi: Jinpu are the only hybrids missing a numHits parameter; they apparently never had one. Popping them on will make `getMultiAttacks` happy.

I'm noticing that other magical weaponskills don't have a `numHits` param. They technically don't need/use them, but should they be defined anyway?

**Comment by ibm2431** [comment]
I think Kagero is one of the ones I was testing with; are your Kageros doing damage? I want to say they _should_ be.

The "former physicals" like Kagero, while still going through `doPhysicalWeaponskill` like before, seemingly never had a magical element defined in their table. Looking at the flow, this wouldn't cause any no-damage issues (hence why I didn't notice before); just the hybrid hit not having applicable bonus/penalties based on mob elemental weakness/resistance. [The logic is there](https://github.com/DarkstarProject/darkstar/blob/master/scripts/globals/weaponskills.lua#L45-L48), but being nil element, they're not getting influenced.
