### ISSUE TITLE
Shattering Stars doesn't work

### ISSUE THREAD

**Issue by JusticeTroll** [DarkstarProject/darkstar#6071]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30190430_0

**_Source Branch_** (master/stable) **:** Master updated 6/6/2019

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Trade Black Mage testimony to Maat as a level 66~70 blackmage. He will then send you to Horlais Peak and when you talk/trade the testimony to the Burning Circle nothing happens. 

server log says
[09/Jun] [20:02:48][Error] luautils::onTrade: .\scripts/globals/bcnm.lua:467: attempt to index global 'JOBS' (a nil value)

**Comment by zynjec** [comment]
Already fixed.

https://github.com/DarkstarProject/darkstar/pull/6070
