### ISSUE TITLE
bcnmcrap pet ability issue

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#6080]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

pet skills dont work in bcnm's from bcnmcrap merge:

https://github.com/DarkstarProject/darkstar/blob/746b0aeb8a54452eeaf62d754268a5e7be0730f0/src/map/ai/helpers/targetfind.cpp#L333-L334 

This should be changed to:
```cpp
    if (m_PBattleEntity->StatusEffectContainer->GetConfrontationEffect() != PTarget->StatusEffectContainer->GetConfrontationEffect() ||
        m_PBattleEntity->PInstance != PTarget->PInstance)  
```
or the equivalent that solves the issue and satisfies dsp

**Comment by teschnei** [comment]
Maybe the issue is that pets don't have PBattlefield set?
