### ISSUE TITLE
Conda doesn't resolve dependencies on environment creation

### ISSUE THREAD

**Issue by AZDserver** [DarkstarProject/darkstar#6088]
I've installed Python 3.7.3 and Anaconda from: https://www.anaconda.com/distribution/

When I try to create the conda environment "conda env create -f environment.yml" , it fails at Solving Environment: failed

ResolvePackageNotFound:
  - ruamel_yaml==0.15.46=py37h1de35cc_0
  - numpy-base==1.16.4=py37h6575580_0
  - sqlalchemy==1.3.4=py37h1de35cc_0
  - mistune==0.8.4=py37h1de35cc_0
  - icu==58.2=h4b95b61_1
  - libcxx==4.0.1=hcfea43d_1
  - libsodium==1.0.16=h3efe00b_0
  - libedit==3.1.20181209=hb402a30_0
  - matplotlib==3.1.0=py37h54f8f79_0
  - pyrsistent==0.14.11=py37h1de35cc_0
  - jupyterlab==0.35.5=py37hf63ae98_0
  - mkl==2019.4=233
  - libpng==1.6.37=ha441bb4_0
  - mkl-service==2.0.2=py37h1de35cc_0
  - freetype==2.9.1=hb4e5f40_0
  - pcre==8.43=h0a44026_0
  - libffi==3.2.1=h475c297_4
  - xz==5.2.4=h1de35cc_4
  - pillow==6.0.0=py37hb68e598_0
  - yaml==0.1.7=hc338f04_2
  - libcxxabi==4.0.1=hcfea43d_1
  - llvm-openmp==4.0.1=hcfea43d_1
  - zeromq==4.3.1=h0a44026_3
  - mkl_fft==1.0.12=py37h5e564d8_0
  - gettext==0.19.8.1=h15daf44_3
  - ptyprocess==0.6.0=py37_0
  - cryptography==2.6.1=py37ha12b0ac_0
  - numpy==1.16.4=py37hacdab7b_0
  - sqlite==3.27.2=ha441bb4_0
  - libtiff==4.0.10=hcb84e12_2
  - ncurses==6.1=h0a44026_1
  - expat==2.2.6=h0a44026_0
  - statsmodels==0.9.0=py37h1d22016_0
  - tk==8.6.8=ha441bb4_0
  - qt==5.9.7=h468cd18_1
  - dbus==1.13.6=h90a0687_0
  - pyzmq==18.0.0=py37h0a44026_0
  - zstd==1.3.7=h5bba6e5_0
  - pandas==0.24.2=py37h0a44026_0
  - python==3.7.3=h359304d_0
  - scipy==1.2.1=py37h1410ff5_0
  - intel-openmp==2019.4=233
  - mkl_random==1.0.2=py37h27c97d8_0
  - pyyaml==5.1=py37h1de35cc_0
  - libgfortran==3.0.1=h93005f0_2
  - markupsafe==1.1.1=py37h1de35cc_0
  - kiwisolver==1.1.0=py37h0a44026_0
  - python.app==2=py37_9
  - pyqt==5.9.2=py37h655552a_2
  - glib==2.56.2=hd9629dc_0
  - tornado==6.0.2=py37h1de35cc_0
  - pycosat==0.6.3=py37h1de35cc_0
  - sip==4.19.8=py37h0a44026_0
  - jpeg==9b=he5867d9_2
  - readline==7.0=h1de35cc_5
  - scikit-learn==0.21.2=py37h27c97d8_0
  - libiconv==1.15=hdd342a3_7
  - cffi==1.12.2=py37hb5b8e2f_1
  - appnope==0.1.0=py37_0
  - openssl==1.1.1c=h1de35cc_1
  - zlib==1.2.11=h1de35cc_3

Anaconda is supposed to install all these dependencies on it's own, no?

**Comment by TeoTwawki** [comment]
thsi is the sum total of all python in this repository:

**Comment by TeoTwawki** [comment]
this is the sum total of all python in this repository:
https://github.com/DarkstarProject/darkstar/tree/master/migrations
I think you are on the wrong tracker for whatever it is you are working with

**Comment by AZDserver** [comment]
I posted this issue in the wrong repo, I apologize, please close this.
