### ISSUE TITLE
shadows of player character npc and monsters by sun not following properly

### ISSUE THREAD

**Issue by kaincenteno** [DarkstarProject/darkstar#6090]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190430_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Shadows created by the sun on characters on areas that are not indoors do not progressively change by the vanadiel minutes

**Comment by TeoTwawki** [comment]
...You know thats client side right? the server doesn't have any control on this, check your settings

**Comment by kaincenteno** [comment]
@TeoTwawki you are right, just tested it on retail, it mighta been my nostalgia thinking that retail's shadow were better lol

Thank you for pointing it out. closing this
