### ISSUE TITLE
Super Jump merit doesn't work

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#6093]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/DarkstarProject/darkstar/blob/master/src/map/merit.h#L270

**Comment by nfaletra** [comment]
https://media.discordapp.net/attachments/140332416194707456/590748411100135425/header.png

**Comment by Hozu** [comment]
I'm guessing it should be 0x06 to match all of 4th group 1 merits, instead of being 0x05.

**Comment by zynjec** [comment]
Useless issue.
