### ISSUE TITLE
BCNM.lua line 470 is wrong

### ISSUE THREAD

**Issue by JusticeTroll** [DarkstarProject/darkstar#6103]
.\scripts\globals\BCNM.lua

has an error on line 470. it reads as 
        [  32] = function() return ( sandy == dsp.mission.id.sandoria.SAVE_THE_CHILDREN and ((stc and missionStatus <= 2) or (not stc and natStat == 2))                    ) end, -- Sandy 1-3: Save the Children

It should be 

        [  32] = function() return ( sandy == dsp.mission.id.sandoria.SAVE_THE_CHILDREN and ((stc and natStat <= 2) or (not stc and natStat == 2))                    ) end, -- Sandy 1-3: Save the Children

**Comment by JusticeTroll** [comment]
Fixed BCNM.lua line 470, and Added SQL information from Nyzul ilse #6104

**Comment by TeoTwawki** [comment]
#6106
