### ISSUE TITLE
Dynamis-Jeuno empty (no mobs)

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#6126]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190605_0

**_Source Branch_** (master/stable) **:** 
Old School server

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Entered Dynamis-Jeuno with the top "Ready!" entry.
Got a cutscene, which I had seen previously (the initial Dynamis-Jeuno cutscene, I think).
Upon zoning in, no mobs were visible.
Traveled entire zone.
The only visible targets were ???s and the exit.

**Comment by zynjec** [comment]
Only Dynamis - Valkurm works with new BCNM system, feel free to PR a version that works with it.
