### ISSUE TITLE
"You find a(n) <item> on the <monster>." message not displayed.

### ISSUE THREAD

**Issue by UynGH** [DarkstarProject/darkstar#6143]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** latest (version 30190702_0, waiting for Wren's PR).

**_Source Branch_** (master/stable) **:** master.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Hello, so as the title said there's a missing message on mob's death. Regarding "custom" stuff, the only thing I did is the static_cast "fix" for the Visual Studio 2019 issue so nothing that can't be reproduced on a stock DSP pull, just kill anything.

Retail behavior: 
![1](https://user-images.githubusercontent.com/40763842/61177808-b84e3780-a5dd-11e9-90cc-4d127daa7d03.jpg)

DSP issue/behavior:
![2](https://user-images.githubusercontent.com/40763842/61177809-c3a16300-a5dd-11e9-8ef5-458e565acdbb.jpg)

0xD2, 60 Bytes - (Item) Found Treasure.
0xD3, 60 Bytes - (Item) Lot Treasure.
Both logs provided by KnowOne (thank you) from two days ago:
[Logs.zip](https://github.com/DarkstarProject/darkstar/files/3389346/Logs.zip)

Teo (thank you) already said that the packets from actual DSP were really outdated.

Thanks for taking a look into this!

**Comment by zynjec** [comment]
Has nothing to do with the packet being out of date/changing, for whatever reason the entity id isn't being passed along when distributing loot, so the "found" message isn't displayed.

**Comment by TeoTwawki** [comment]
Just to clear up any misunderstanding about that:

That packet DSP uses currently doesn't perfectly match whats retail uses in general, Retail used to have more than one "version" of it and no longer does. What we have still "works" but on occasion will make the client glitchy about it (takes quite awhile and if you zone/relog its "fixed" - probably before you even noticed). And I had no idea if that had anything to do with anything but I was asked if it was different so here we are.
