### ISSUE TITLE
Conquest not working properly

### ISSUE THREAD

**Issue by Starfret** [DarkstarProject/darkstar#6166]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_**  **:30190605_0** 

**_Source Branch_** (master/stable) **: Master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **: Even if on the "Region Info" map the zones are under San Dorian control,** , vendors do not sell items just like the zones were still under beastmen control, and the guards at the gates can't assign supply quests. There are no guards at the outposts in the zones under San Dorian Control, and mobs do not drop crystals.

**Comment by zynjec** [comment]
Related to https://github.com/DarkstarProject/darkstar/issues/6047

Fails to get region owners because of VS bug.
