### ISSUE TITLE
Scission skillchain not making noise

### ISSUE THREAD

**Issue by kaincenteno** [DarkstarProject/darkstar#6207]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30190731_2

**_Source Branch_** (master/stable) **:** 
master (old school server)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
we were playing in bohyada tree defeating mandragoras and bunnies, and when doing a skillchain that resulted in scission it didn't make a noise when the animation showed up. (the animation was correct though)

**Comment by zynjec** [comment]
Client issue, nothing we can do about it.

If the animation played, the sound is tied to it.
