### ISSUE TITLE
Nation Mission 4-1 (Magicite): Incorrect Starting NPCs

### ISSUE THREAD

**Issue by ibm2431** [DarkstarProject/darkstar#6211]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** n/a

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The NPC that starts Nation Mission 4-1, Magicite, should be the _ambassador's doors_ of the embassy, _not_ the NPCs at the office counter. We are [doing this correctly for Windurst](https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/RuLude_Gardens/npcs/_6r8.lua#L22-L27), but are inaccurately using the secretaries for the [San d'Oria](https://github.com/DarkstarProject/darkstar/blob/cd5dbb8e2e33ed10940cafe1289a4eadfd5f7af1/scripts/zones/RuLude_Gardens/npcs/Nelcabrit.lua#L27-L32) and [Bastok](https://github.com/DarkstarProject/darkstar/blob/cd5dbb8e2e33ed10940cafe1289a4eadfd5f7af1/scripts/zones/RuLude_Gardens/npcs/Goggehn.lua#L28-L36) versions (we currently do not have any scripts for the correct doors).

Instead, those secretaries should be giving the player an event where they tell the player to go into the back office (Nelcabrit's is event 45; Gogghen is probably 43).

My capture video of the San d'Oria version of the mission, "Missions: San d'Oria: 4-1 (Magicite)", demonstrates this behavior at 13m55s.

**Comment by kaincenteno** [comment]
Oooo @ibm2431  that sounds like something i might work on after the Shantotto CS gets fix'd😸
Unless someone already working on it 😸

**Comment by ibm2431** [comment]
Fixed by #6244
