### ISSUE TITLE
 can't get moongate pass

### ISSUE THREAD

**Issue by tourmaline3333** [DarkstarProject/darkstar#6222]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30190731_2** 

**_Source Branch_** (master/stable) **master** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I entered moongate when full moon.and I found "???" on A-8.
I checked "???" but no motion.
Of course I did not get moongate pass

**Comment by kaincenteno** [comment]
@tourmaline3333 It looks like the logic of it hasn't been implemented for all 4 locations

Can you get the X, Y, Z location of the pass possible locations?  (https://ffxiclopedia.fandom.com/wiki/Moongate_Pass_Quest)

From the wiki it says that it will dissapear right after being obtained by a person and will go on a respawn timer of 30 minute. Can you also check if the  "???"  moves around if not being touched?

Once I get that info I can try and script it 😸

**Comment by tourmaline3333** [comment]
Thunks for your response.

???(Moongate pass)'s location is  "X:-277.7171 Y:-3.5752 Z:-17.6135"

Im only player on my server. So no one got "???".
and there is "???" on same location yesterday

**Comment by kaincenteno** [comment]
Thanks for the Coordinates.

Ah @tourmaline3333  you don't have access to retail? Let me check on the table maybe the coordinates are there, it's just a bit of a pain to go online and mark em with a character lol.

I'm currently on the DSP discord chat. Feel free to send me a direct message there. My handle is Kain

**Comment by tourmaline3333** [comment]
It's so difficult for me.I don't know "retail", and I started play DSP only 3 days ago.

**Comment by kaincenteno** [comment]
Which server do you plat @tourmaline3333 ?

**Comment by tourmaline3333** [comment]
Umm..what do you mean?
DSP Server: I build Server myself. Code -> releases -> 0.0.8318 -> darkstar_setup.exe
Official FF11 : I played on Bismark ten years ago

**Comment by kaincenteno** [comment]
@UynGH  I checked the file you shared with me and couldnt find enough points containing ??? (some of them are outside the moon gates, for example I couldnt find the one at 0-8 accourding to https://ffxiclopedia.fandom.com/wiki/Moongate_Pass_Quest)

**Comment by tourmaline3333** [comment]
thanks for research
moongate pass(???) is random pop.

upper floor :A-8, D-5, K-4,O-8
lower floor : B-8,E-5,L-6,O-9

**Comment by TeoTwawki** [comment]
DSP's moongatepass NPC(s) were never fully implemented. There are 2 ??? NPCs in DSP that can give you moongate pass, and they don't move.

To make it retail, you need to verify all the retail accurate positions and code it moving aroudn at whatever trigger/interval retail uses. Meanwhile there will be dead/useless or missing '???' NPC's that do nothing or that don't spawn at all.

**X:** 184.516,**Y:** -7.146, **Z:** 14.297
**X:** -184.516, **Y:** -7.146, **Z:** 14.298
Thats all we have right now.
Make sure you aren't clicking an NPC that is unrelated to those 2.

**Comment by TeoTwawki** [comment]
nope nope. I'm wrong. They don't exist in DSP _AT ALL_

**Comment by tourmaline3333** [comment]
It looks like that the script is so difficult.
it seems that I should give up the moogate pass, dont you?
instead, I will input command "!addkeyitem 485". is it no problem?

**Comment by kaincenteno** [comment]
@tourmaline3333 
PR that will fix this:
https://github.com/DarkstarProject/darkstar/pull/6232

Thank you @UynGH for your awesome help 😸
