### ISSUE TITLE
MNK unarmed has no weaponskills

### ISSUE THREAD

**Issue by ffxijuggalo** [DarkstarProject/darkstar#6264]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30191004_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Switched to mnk at lvl 1 and after gaining 5 lvls of hand to hand skill without a weapon equipped, I received the chat message that Combo had been learned. So I try to select it from the weaponskills menu on the next mob I was fighting, and it wasn't listed. Not listed from the main menu / abilities / weaponskills menu either. I went to the weapon shop in port windurst and bought a lvl 1 h2h weapon, equipped it, and sure enough, Combo shows up in the list of weaponskills. Unequip the weapon, and Combo disappears again. This is occuring on a branch built clean from master that is current as of writing this as well as an up to date client.

**Comment by Cryptexx** [comment]
PR #6265

**Comment by zynjec** [comment]
Fixed with https://github.com/DarkstarProject/darkstar/pull/6265
