### ISSUE TITLE
SMN tiral BCNM not working

### ISSUE THREAD

**Issue by tourmaline3333** [DarkstarProject/darkstar#6271]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
0.0.8319

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

DSGame-server crashed before enter "Trial by Lightning" Field.
I searched SMN trial BCNM working.

O:100% works
@: DSGame-server crashed after kill BCNM.(not start clear event)
X:crash before enter BF(after touched crystal)
-----
O Trial by Fire
O Trial by Water
X Trial by Lightning
O Trial by Earth
O Trial by Wind
O Trial by Ice
@ Trial Size Trial by Fire
@ Trial Size Trial by Water
O Trial Size Trial by Lightning
@ Trial Size Trial by Earth
@ Trial Size Trial by Wind
@ Trial Size Trial by Ice
----

I want "Whisper of storms".
plz tell me how to fix

**Comment by kaincenteno** [comment]
doubt this is connected to the pet release/death?

**Comment by tourmaline3333** [comment]
> doubt this is connected to the pet release/death?
No.The issue was fixed by #6212.

"Trial by Lightning" and "Trial Size *" is other reason.

**Comment by wrenffxi** [comment]
I was last to touch these files, so I'll look into it.  I see why Trial by Lightning bonks.

**Comment by wrenffxi** [comment]
That PR will fix Trial By Lightning.  I could not reproduce the Trial-Size fights crashing server on completion.  They work okay for me on master.

**Comment by wrenffxi** [comment]
This new PR fixes the rest of this issue.
