### ISSUE TITLE
ASA-4 code Prime Avatars sends errors to game server console

### ISSUE THREAD

**Issue by wrenffxi** [DarkstarProject/darkstar#6274]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30191004_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

1. Enter any of the Trial By Foo battlefields (I encountered this while fixing an issue with Trial By Lightning).
2. Note the console while fighting the mob.

![image](https://user-images.githubusercontent.com/21246949/68369153-a00fa480-0107-11ea-90d8-5c3ba96d1631.png)

I think mob:getBattlefield() is nil for some reason.

**Comment by cocosolos** [comment]
mob:getBattlefield():getBcnmID() should just be mob:getBattlefield():getID()

**Comment by Cryptexx** [comment]
GetID() with capital G (another lovely consistency in our programming style)

**Comment by cocosolos** [comment]
Not in Lua, this one is camelCase

**Comment by Cryptexx** [comment]
What? How? mob:getBattlefield returns an object of class CBattlefield, which doesn't have a getID() method, only GetID(). And it can't be using the getID() method defined in luabaseentity because that one returns a public member of id, which battlefield doesn't have (it's m_ID, which is private).

**Comment by Cryptexx** [comment]
if anything, you can probably just use mob:getBattlefieldID(), which is defined in luabaseentity, for simplicity sake.

**Comment by wrenffxi** [comment]
Cocosolos is right that LUA would access the :getID() binding
https://github.com/DarkstarProject/darkstar/blob/master/src/map/lua/lua_battlefield.cpp#L72
which calls GetID() in the core.

But yeah, Cryptexx is right that mob:getBattlefieldID is probably easiest answer.

I'll fix it.

**Comment by Cryptexx** [comment]
I'm thoroughly confused on how getID() would work lol.

**Comment by TeoTwawki** [comment]
I kept meaning to split the multiple avatar copies to separate scripts and stop checking which battlefield we are in, but never got around to it. there are further copies we don't yet have implemented and if we keep adding the different behaviors of each into one script that onMobFight is gonna get mighty bloaty.

**Comment by teschnei** [comment]
@Cryptexx https://github.com/DarkstarProject/darkstar/blob/master/src/map/lua/lua_battlefield.cpp#L457

**Comment by Cryptexx** [comment]
Yep I'm wrong. Sorry cocosolos lol
