### ISSUE TITLE
OnEventFinish 

### ISSUE THREAD

**Issue by bope12** [DarkstarProject/darkstar#630]
server will throw a "luautils::OnEventFinish: undefined procedure onEventFinish" error into log when it fails to load the method, seems to happen first time the server tries to load it, as doing the same event again will work, but fail again once server restarts or my random luck in testing has been very skewed, Not sure all the files it is happening on but can get it to fail on \Balgas_Dais\bcnm\shattering_stars every time I start my test server

**Comment by xdemolish** [comment]
ya, it'll do that in any zone if the zone's lua doesn't have an onEventFinish
not really sure why the luautils function was written that way, but the message is safe to ignore unless your zone actually needs to handle something when a particular cutscene is triggered

closing for now as it isn't *really* a bug, just a warning message for quest/mission scripting as it can be helpful with future quests/missions which make use of cutscenes on zoning in
