### ISSUE TITLE
Temple of Uggalepih/Den of Rancor Issues

### ISSUE THREAD

**Issue by ghost** [DarkstarProject/darkstar#636]
In the room to get the Paintbrugh of Souls, one of the worn books does not work, preventing getting the paintbrush.

In the room that uses the paintbrush to open the door, the door itself does not open after following the proper procedure.

In the Den of Rancor, lighting the four lamps does not open the door to the Sacrificial Chamber.

**Comment by TeoTwawki** [comment]
I had fixed paintbrush acquisition but just found and fixed another ID error (#745), door should actually open now...
