### ISSUE TITLE
Attempt to index local 'rainbow' (a nil value)

### ISSUE THREAD

**Issue by Gradius2** [DarkstarProject/darkstar#6373]
Hi all,

I just installed this today and got this error from scripts:

[13/Jan] [02:14:25][Error] luautils::OnTOTDChange: scripts/zones/La_Theine_Plateau/Zone.lua:90: attempt to index local 'rainbow' (a nil value)

The code:

function onTOTDChange(TOTD)
    local rainbow = GetNPCByID(ID.npc.RAINBOW);
    local I_Can_Hear_a_Rainbow = GetServerVariable("I_Can_Hear_a_Rainbow");

    if (I_Can_Hear_a_Rainbow == 1 and TOTD >= dsp.time.DAWN and TOTD <= dsp.time.EVENING and rainbow:getAnimation() == dsp.anim.CLOSE_DOOR) then
        rainbow:setAnimation(dsp.anim.OPEN_DOOR);
    elseif (I_Can_Hear_a_Rainbow == 1 and TOTD < dsp.time.DAWN or TOTD > dsp.time.EVENING and rainbow:getAnimation() == dsp.anim.OPEN_DOOR) then
        rainbow:setAnimation(dsp.anim.CLOSE_DOOR);
        SetServerVariable("I_Can_Hear_a_Rainbow", 0);
    end

**Comment by kaincenteno** [comment]
@Gradius2  
https://github.com/DarkstarProject/darkstar/pull/6372 should fix it (try it as long as you have december update installed, dunno if with january update SE shifted IDs)

**Comment by Gradius2** [comment]
Hi kaincenteno,

I have checked my FFXI files today, so I do have the january 2020 installed.  I haven't played FFXI since 2012, so I was forced to update.

Is the only error (so far) I'm getting.

Thanks

**Comment by TeoTwawki** [comment]
fixed in recent PR

**Comment by kaincenteno** [comment]
thanks for submitting the bug @Gradius2  :D
