### ISSUE TITLE
Killing a mob at the same time as the attacking player dies triggers a silent crash

### ISSUE THREAD

**Issue by SirGouki** [DarkstarProject/darkstar#6385]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30191227_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
A bit difficult to time, but to reproduce, kill a mob at the same time they kill the player.  

What happens? occasionally, the game server will just silently crash.  My current log just shows a gap from the last message and the new startup time when this happened.

What should happen: the player should die and not gain XP, and the mob should die.

**Comment by zynjec** [comment]
Fixed in master, please update.
