### ISSUE TITLE
MapServer error: la theine plateau 'rainbow' is nil value

### ISSUE THREAD

**Issue by SirGouki** [DarkstarProject/darkstar#6386]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30191227_0

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
GameServer log: [Error] luautils::OnTOTDChange: scripts/zones/La_Theine_Plateau/Zone.lua:90 attempt to index local 'rainbow'(a nil value) keeps popping up
Checking the appropriate lua files (zone.lua and the ID.lua) shows that rainbow is set to an id, by default, but this error is still happening. 

    in IDs.lua
    RAINBOW = 17195606,

    in Zone.lua
     elseif (I_Can_Hear_a_Rainbow == 1 and TOTD < dsp.time.DAWN or TOTD > dsp.time.EVENING and rainbow:getAnimation() == dsp.anim.OPEN_DOOR) then
        rainbow:setAnimation(dsp.anim.CLOSE_DOOR);

**Comment by TeoTwawki** [comment]
update your server, this was recently corrected.
