### ISSUE TITLE
Artisan Moogle in Rulude Garden has wrong name

### ISSUE THREAD

**Issue by NiQ1** [DarkstarProject/darkstar#6414]
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30191227_0

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
!zone 243 and look at the moogle in front of you. See screenshot.
![img_20200210_014158](https://user-images.githubusercontent.com/23407689/74112656-1d373380-4ba7-11ea-9591-4e33c2c74a1b.jpg)

**Comment by TeoTwawki** [comment]
Have server owner check what client version the server was last updated to. If this is happening a server you are running yourself, make sure you have imported the latest version of npc_list.sql to your servers database. 

![Teo_2020 02 09_190026](https://user-images.githubusercontent.com/6871475/74112906-7fc00d80-4b6e-11ea-9457-b56140ed219b.png)

**Comment by NiQ1** [comment]
OK Was my bad, was looking at the IDs.txt files, forgot about DB. Any other tables that I need to keep an eye on after every client update?
