### ISSUE TITLE
Death on Entering MogHouse after latest commit

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#736]
While hilariously funny... This bug popped after the last commit to server that updated zone stuff. (Verified on other servers)

**Comment by Vivitarut** [comment]
Same thing happened when players tried to enter dynamis and the server kept crashing until i manually set their current zone elsewhere. Breaks on line DSP_DEBUG_BREAK_IF(PChar->loc.zone->m_BattlefieldHandler == NULL); in isBcnmsFull(lua_State *L)

**Comment by xdemolish** [comment]
prolly needs to use zoneutils::GetZone(PChar->loc.destination) instead of PChar->loc.zone

**Comment by xdemolish** [comment]
seems @teschnei fixed the death on entering MH in https://github.com/DarkstarProject/darkstar/commit/0cad886cfbd02593e508920a46b9b98b122e11ca

@Vivitarut open a new issue for dynamis instead of posting it under another one and i'll have a look at it
