### ISSUE TITLE
4 Fireworks Not Working

### ISSUE THREAD

**Issue by tagban** [DarkstarProject/darkstar#739]
The following Fireworks currently don't activate/do anything, MIght be an issue with the item in SQL.
- Popstar (4215)
- Marine Bliss (5882)
- Falling Star (5883)
- Shisai Kaboku (5881)

**Comment by JoeCT** [comment]
Popstar should be working.

**Comment by JoeCT** [comment]
Submitted pull request #929 to resolve the 3 non-working fireworks listed above.

**Comment by maxtherabbit** [comment]
this can be closed
