### ISSUE TITLE
WHM Teleport Spells Cause Character Models to Disappear When Player Lacks Appropriate Gate Crystal.

### ISSUE THREAD

**Issue by JoeCT** [DarkstarProject/darkstar#744]
When casting teleport spells on players without gate crystals their character models disappear, but the players remain in the current zone.  Message "No Effect on <player name>" is given.

**Comment by teschnei** [comment]
that has always been the case

**Comment by starlightknight** [comment]
Sounds to me like the bug is the models disappearing, since they aren't supposed to teleport.

**Comment by teschnei** [comment]
there's no way to dictate whether a player should be completely skipped in receiving a beneficial aoe effect.  nobody really bothered since the only time it'd ever be useful is for those teleport spells

**Comment by Novah1** [comment]
I remember even on retail in the early days this was somewhat buggy. I teleported to Altep once after a fresh install (I had forgotten Zilart) and my character model dissapeared.

**Comment by maxtherabbit** [comment]
ugh I can't think of anyway to fix this that's not ad hoc ugly
