### ISSUE TITLE
Evasion skills/traits appear to be misbehaving. 

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#750]
We've had a few reports from our THF's that the Enhance Evasion and Evasion skills not working as well as they should be as of https://github.com/DarkstarProject/darkstar/commit/4db1f34f4984f74fc715f897613b9ed074acf219

Working on producing a parse, but wanted to get some feedback based on everyone else around here. Noticed a very high hit rate on my RDM75 against level 40 mobs.

**Comment by korietsu** [comment]
Alright, got two parses and some printout for the mobs per @teschnei's request. Thanks to @TeoTwawki for letting me know some information on getMod and getStat.

Hit rate for Boreal Courel
24 Misses
450 Hits

100 - 100*(24 (miss)/450 (hit)) = 94.66 % hit rate. 

Hit rate for Ul'hpemde
9 Misses 
192 Hits

100 - 100*(9 (miss)/192 (hit)) = 95.3125 %

Mod prints

Boreal Hound Thf 75, full eva gear 
target:getMod(MOD_EVA)
mob:getMod(MOD_ACC)
[02:58:26][LUA Script] 130
[02:58:26][LUA Script] 2521


Fafnir 75 thf, full eva. 
target:getMod(MOD_EVA)
mob:getMod(MOD_ACC)
[03:01:54][LUA Script] 263
[03:01:54][LUA Script] 2521



Logging for the Courel and Goldfish via kParse
https://drive.google.com/file/d/0B3880ehfJ1jJbERwYUluM2ZJWXM/view?usp=sharing

**Comment by Scavenge** [comment]
this sounds like what we're dealing with.  people have mentioned that they have no issue dodging on jobs like rdm, but can't dodge on nin or thf.  in my own tests i can't seem to dodge on my fully geared/merited 75 nin and yet my gm was able to dodge just fine as a 75 nin the only difference being that he was naked

**Comment by xdemolish** [comment]
think it's fixed now (if it's the same as https://github.com/DarkstarProject/darkstar/issues/872)
