### ISSUE TITLE
Zoning into Apollyon whilst in party results in "disband" from party

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#765]
I zoned into Apollyon in a party and it half disbanded my character. Meaning, on my screen it looked like I was Solo and on others screens I was still in party.

**Comment by Fiocitrine** [comment]
This is happening in other areas as well.

**Comment by teschnei** [comment]
are you able to reproduce this with a fresh party/alliance? do you know the steps taken to make this happen?

**Comment by Fiocitrine** [comment]
Step 1: Join alliance 
Step 2: Zone into Apollyon or anywhere else
Step 3: Notice random "party disbanding"
Step 4: Scream in frustration

It seems to be at random with random characters. 

Also also, you can't disband from a party is you are party leader. Parties/ alliance just seem really buggy right now. Perhaps something was done with that script recently? This has only been happening for the past week or so.

**Comment by teschnei** [comment]
Is this fixed now, Fio? You haven't seen it happen in a while?
