### ISSUE TITLE
Proto-Omega spewing out errors

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#767]
I noticed in the gameserver console a huge amount of errors coming from proto-omega's lua, looking for  GetNPCByID(16933248) and saying that npc didn't exist.  these calls to the npc were to change its animation. After looking around on here and in my own files I couldn't determine which NPC this was meant to be, and since there was a working section that changed omega's animation correctly, I decided to just remove all references to  GetNPCByID(16933248). this allowed the lua to work without errors, enabled gunpods to spawn which were not spawning before, and enabled the resistances and defense mods that were supposed to be active.

**Comment by korietsu** [comment]
Looks like this is to reference its animation for its stance. I think a change from GetNPCByID to mob: should do the trick, I'll play with it and see what happens.

**Comment by Scavenge** [comment]
there was already a reference to changing his animation that said something about 'sub' in it, and it just used his hpp markers and it is in a seperate statement above the part that threw errors.  his animation changed properly but the rest didn't. so i think maybe it was left-over vestigal code from a previous attempt?

**Comment by teschnei** [comment]
no idea what it was *trying* to do, but this'll at least stop it from trying to set SOMETHING to open/closed

**Comment by Scavenge** [comment]
a player did mention that there is no exit area so when they kill omega they have to wait for the timer to run out, maybe it was the exit door.
