### ISSUE TITLE
Crash Dumps

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#771]
Legion 3x Crashdumps

https://www.dropbox.com/s/jgzy3b7beiw2jj7/update%20entity%20fail%20on%20pet%201.7z?dl=0

https://www.dropbox.com/s/2s5061je9ddbu0h/update%20entity%20fail%20on%20pet%202.7z?dl=0

https://www.dropbox.com/s/4w3se0su2ry2gkt/update%20entity%20fail%20on%20pet%203.7z?dl=0

**Comment by TeoTwawki** [comment]
I've been told that zoning out while having a pet engaged triggers the crash in 
```C++
    if (!(actionType == ACTION_FALL && isMob))
    {
        m_PPet->UpdateEntity(); // Kaboom right here.
    }
```
