### ISSUE TITLE
Zoning causes some characters to not load.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#774]
Some characters, after zoning, do not appear on the screen. If you move out of targeting range and move back in, then they appear. They will appear to other players. 

Example: I zone characters A, B, C, and D. I am on character A. I alt-tab to character B and he cannot see character A but can see character C and D. Other players can see character A.

**Comment by Scavenge** [comment]
i can confirm this as well, as a GM just doing @goto within the same zone will randomly fix it and/or make others inivisible, hit and miss

**Comment by Fiocitrine** [comment]
Just wondering if anyone has figured this stuffs out?

**Comment by xdemolish** [comment]
not getting this on my test server as of like https://github.com/DarkstarProject/darkstar/commit/0ef4e6e09f571f3a2702698095ce88b40c53ef9c

reopen if it's still an issue though
