### ISSUE TITLE
Fields of Valor repeat not working

### ISSUE THREAD

**Issue by namronorman** [DarkstarProject/darkstar#787]
I'm a few days behind (Jan 6 2015) but didn't see this addressed anywhere in the latest commits and I just recently started playing again. I apologize if I am in the wrong.

I noticed that when I attempt to assign a regime via FoV it doesn't actually apply. Looking at the IDs in fieldsofvalor.lua, I saw:

FOV_MENU_REPEAT_REGIME1  = -2147483630; -- 2147483666;
FOV_MENU_REPEAT_REGIME2  = -2147483614; -- 2147483682;
FOV_MENU_REPEAT_REGIME3  = -2147483598; -- 2147483698;
FOV_MENU_REPEAT_REGIME4  = -2147483582; -- 2147483714;
FOV_MENU_REPEAT_REGIME5  = -2147483566; -- 2147483730;

The positive numbers commented out reflected what was being sent in from the FoV menu. If I replaced the negative numbers with the positive numbers, I was able to apply a repeating regime. Non-repeating regimes are not affected.

After fixing the above, I noticed I got the following error when killing a regime target:

[18:27:19][Error] luautils::onMobDeath: ./scripts/globals/fieldsofvalor.lua:409: attempt to index global 'player' (a nil value)

I was able to resolve the above error by changing player to killer as there was no player parameter but instead only killer. Doing all of the above seems to resolve the issue.

- Anglos

**Comment by namronorman** [comment]
I have confirmed that with the above changes, everything works in a party.

**Comment by teschnei** [comment]
mm, it depends on how lua interprets the 32-bit number it gets from the game server.

i'll do a quick update that makes that easier

**Comment by teschnei** [comment]
not sure where you were seeing "player" instead of "killer" (checkRegime function? i didn't see one in there) but the repeat should work better now
