### ISSUE TITLE
Underwater Mobs in Sea no longer hiding name. 

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#794]
While developing my commits for updates to the golfish in sea, I've noticed that the mobs as of https://github.com/DarkstarProject/darkstar/commit/bc4f2fe0cea0071cb35ed17d8b3596b9d0f06d52
are no longer hiding their names on spawn. Appears in the onMobSpawn script that the line mob:hideName(true); isn't having any sort of effect.

**Comment by teschnei** [comment]
should work now

**Comment by korietsu** [comment]
Thanks boss!
