### ISSUE TITLE
players on newest version can't equip/unequip linkshells

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#807]
seems to be related to today/yesterday's SE update for 2 linkshells.  not sure if it's just people who were linkshell leaders but so far that's who is having the problem, unable to unequip their old, black linkshell and even when i remove the items from their inventory via the database they are still unable to equip one.  people who updated prior to the update on the 14th don't have this issue.

**Comment by teschnei** [comment]
should be fixed now

**Comment by teschnei** [comment]
LS creation still broken, will be fixed in a day or two

**Comment by Scavenge** [comment]
thank you for your attention
