### ISSUE TITLE
Auction House items over 100 quantity are unable to be bought 

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#809]
Anything over 100 is unable to be purchased and putting an item on the AH locks out that item from being bought.

**Comment by teschnei** [comment]
what stacks higher than 99...?

**Comment by korietsu** [comment]
It's not a stack size issue, its that if there's over 100 listed of an item it can't be bought currently. Sorry, probably should have worded that one better.

**Comment by Fiocitrine** [comment]
are you sure it's not from people having a full DB? We've had that issue as of late on oldschool.

**Comment by bope12** [comment]
Could it be because the item is from the ah tool ?
On Jan 16, 2015 12:46 PM, "Fiocitrine" <notifications@github.com> wrote:
>
> are you sure it's not from people having a full DB? We've had that issue
as of late on oldschool.

**Comment by korietsu** [comment]
Relatively sure we have enough space. the db size is less than 100mb. Not sure how the DSP database would be full as at least as far as I can tell, isn't using any sort of partitioning or disk size limits, unless InnoDB has an innate page size limit and there wasn't a thought to add the auto extend as a system parameter.

**Comment by Fiocitrine** [comment]
Well, whasf has been clearing the delivery box of characters that haven't been on in awhile to allow us to purchase things from them. I guess when there delivery box is full, it prevents them from recieving gil and in turn doesn't not allow a purchase. 

Sorry, I didn't mean database, I meant delivery box for DB.

**Comment by whasf** [comment]
If the character has 255 items in the delivery_box table, no one will be able to buy anything that they are selling. You will see an error in the game console like:
DB error - Duplicate entry '23228-1-255' for key 'PRIMARY'
right after an AH (0E) action.
In this example character ID 23228 has a full delivery box. What I do is add all their gil entries together into one line, then delete all the small ones.

As you can only have 7 items up on the AH at a time (unless you modified that), I'm 99.9% sure this is the problem you're having.

**Comment by korietsu** [comment]
I have an empty delivery box and still can't purchase some of the items.

**Comment by korietsu** [comment]
So we can't use the AH tool to populate more than 7 items in the AH from a "ghost" seller?

**Comment by teschnei** [comment]
it's not your delivery box that matters, it's the delivery box of the seller

**Comment by korietsu** [comment]
We're able to purchase items that have <= 100 of them available in the AH. e.g. there are 99 bronze swords, we able to purchase. If there are 101, we are unable to purchase.

**Comment by whasf** [comment]
What error are you seeing on the game server console when you try to purchase an item that is up on the AH >100 ?

**Comment by korietsu** [comment]
Let me see if I can get that to you. Might take me a bit, I'm just delegating at the moment.

**Comment by korietsu** [comment]
Here's what we're getting. 

http://i.imgur.com/Ohyxnjf.png

**Comment by teschnei** [comment]
make sure the order of columns in delivery_box is correct (if you tried to update it by just appending extra to the end, that ain't gonna work)

**Comment by bope12** [comment]
Table was not setup right, had not null checked insteed of allow null, can close this
