### ISSUE TITLE
Zoning out of MH after checking delivery box and changing jobs results in blank screen.

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#810]
Just as the title suggests. I was able to teleport-holla the characters. I couldn't type, either.

**Comment by Scavenge** [comment]
this may be related to something we've been experiencing, gettings tuck on an npc after checking delivery box.  when checking delivery box, the first amount of gold you select shows what it's from i.e. 'the money for this thing you sold' but the rest of the money amounts after the first one don't update with new info and after that point npcs freeze your char until you use our custom @ moghouse command or relog.  also battle text sometimes doesn't show up if you never touch an npc and go straight for combat, can't check mobs etc.  this may be related also to the sql.cpp crashes we've been having.
