### ISSUE TITLE
audit_chat query causing crash? reportedly 1/3 of all crashes

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#814]
query    0x06358ae8 "INSERT into audit_chat (speaker,type,message,datetime) VALUES('Urathi','ALLIANCE','if the silence doesn\'t stick run',current_timestamp());"    const char *

according to another GM this has been 1/3 of all crashes since we updated, still looking for more info to get back to you with.  they might have a dump

**Comment by Scavenge** [comment]
i think saying that this has been 1/3 of the crashes is actually in reference to the crash coming from sql.cpp, some are from an error while trying 'GetZoneIPP' .  all come from a section of code commented as 'executes a query' . in the most recent instance, it was from a character who said he was simply auto-attacking a lizard.

**Comment by teschnei** [comment]
gonna close this until you can provide a dump (useless otherwise)

**Comment by Scavenge** [comment]
i'll try to get a proper dump and log on one (haven't been on)
