### ISSUE TITLE
Search crash - ZMQ

### ISSUE THREAD

**Issue by nasomi** [DarkstarProject/darkstar#818]
https://www.dropbox.com/s/5rxtp5ei9n3n99q/search.zip?dl=0

Can't keep the search up for more than 2-3min before it crashes again.

**Comment by sisternERA** [comment]
i just had a problem similar to this and it was a corrupted database table.  i was able to query repair it and stopped the crashing

**Comment by sisternERA** [comment]
i found that certain link shells will crash the search server if you search the linklist

**Comment by sisternERA** [comment]
it also seems to be when the list gets to large to truncate.  which it does not do  when you first start a ls it is good until you get too many people

**Comment by teschnei** [comment]
capped to 19 now, should be okay
