### ISSUE TITLE
Issue When Summoning Avatar

### ISSUE THREAD

**Issue by ghost** [DarkstarProject/darkstar#821]
Occasionally there is an issue when summoning an avatar. When you summon them, they appear without any animation, with no name, and when attacking everything in the chat log is blank concerning a name. In the game server console after releasing a properly summoned avatar a message appears.

For example, after releasing Titan it reads "SmallPacket0x17: Incorrect NPC<1792, 17276424> type(4)". If trying to follow up with another summon, e.g. Carbuncle, the above described issue occurs. The console writes "[Warning] Server need NPC <17276424>" This issue occurs about once every two or three summons. Typically if you release the error avatar and resummon the issue is resolved for that casting.

**Comment by Fiocitrine** [comment]
I can attest to this issue, as someone who has x4 Summoners. Sometimes the avatars don't appear until they perform a Blood Pact.

**Comment by teschnei** [comment]
2cdbad190f7a8673a8d2a7872ce0471bb10a5071
