### ISSUE TITLE
Latent Effect: Song/Roll active not implemented

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#822]
I tried to script the Melody Earring/ +1's Latent effect to activate on song/roll but I guess the Latent ID isn't implemented. The Latent ID is 25 according to latent_effect.h. https://github.com/DarkstarProject/darkstar/blob/master/src/map/latent_effect.h

**Comment by maxtherabbit** [comment]
all the bard songs and cor rolls need to have the proper EFFECTFLAG set before this can work
