### ISSUE TITLE
sql.cpp crash dump

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#824]
https://www.dropbox.com/s/t7n182vrjw27nw9/scavenge%20sql%20dump%20w%20log%201-19.rar?dl=0

i have tried to pinpoint exactly when this is happening, at first thought moghouse related because it often is trying to find zoneip, zoneport of zone 0, and while that is true often, it isn't always what is in the autos.  this crash shows delivery box, others have shown conquest update and others have just shown char_inventory being changed.  im hoping this is due to an error i made while updating or something, because we've fixed most other crashes. this seems to happen REALLY often when the server is around 100+ users, but nearly non-existant later at night when it's around 50-80 users.  uptime while crashing can be anywhere from an hour to only 10 minutes at a time. uptime at night is 4+ hour sessions.

**Comment by Scavenge** [comment]
may be related to: https://github.com/DarkstarProject/darkstar/issues/810

**Comment by teschnei** [comment]
nah, not related to 810, just a small quirk of another thread trying to use the same resource handle as the main thread at the same time - fixed now
