### ISSUE TITLE
m_pluazone = null crash

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#826]
lua_zone.cpp perhaps i have missed a commit somewhere but putting in that fix now has us crashing constantly but it is at least a savable crash. i'll gather a dump

**Comment by teschnei** [comment]
would be from a script doing player:getZone() before there's a zone, but not sure which (an item or something specific to your server maybe, but the dump will say for sure)

**Comment by Scavenge** [comment]
ok thanks

**Comment by Scavenge** [comment]
dump: https://www.dropbox.com/s/nbi6b2nelqh2deh/lua%20zone%201-20%202.dmp?dl=0

i have 'tried' removing all of our custom scripts entirely and it still happens

**Comment by Scavenge** [comment]
completely removing the scripts has made it happen a lot less often but it still does, and the only thing that stands out to me is that in the autos it mentions level restriction.  (i am poor at this though)

**Comment by teschnei** [comment]
need the pdb, .exe and .log too (and zip them, prefer 7zip)

**Comment by Scavenge** [comment]
oh woops i dropbox'd the wrong file i'm an idiot

**Comment by Scavenge** [comment]
https://www.dropbox.com/s/2bin9yibxjafqkm/luazone%20dump.7z?dl=0

**Comment by Scavenge** [comment]
i've noticed at the moment it keeps happening because a specific player is trying to log in but keeps dc'ing once i save the crash so it is coming from the login process possibly

**Comment by Scavenge** [comment]
well now he logged in without issue and said he updated his drivers so.. i'm back to being lost

**Comment by teschnei** [comment]
0bde2b86f4590bd3e1997033f2f1fd6873f4abb3

eh, my fault

**Comment by Scavenge** [comment]
ah that makes sense, he was prolly able to get in later because the weather changed. thanks, happy to be making progress; this build looks like it will be really solid
