### ISSUE TITLE
summoner flag quest causing crash on zonein

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#828]
looks like the same scenario as before the getZone():getID() was changed to getZone(), i know for a fact now that it is due to a player who is on the summoner flag quest zoning into a cutscene for it.  

in lua_baseentity.cpp , 
DSP_DEBUG_BREAK_IF(m_PBaseEntity->loc.zone == NULL); is where it breaks

in the log i see 
luautils::onZoneIn: .\scripts/globals/icanheararainbow.lua:85: attempt to index a nil value

working on how to decipher what to do about the lua but for now i have commented it out; server is running very smooth now

**Comment by TeoTwawki** [comment]
I'll second this, its still broked even after the getZoneID change. My own server as well as the legion dudes non stop exploded while someone logged into a zone with weather who had that quest active, until I moved the load inventory line back as a temp fix.

**Comment by teschnei** [comment]
that's what i get for copy/paste

**Comment by Scavenge** [comment]
which load inventory line did you move? because i'm also getting a rare query crash to do with AddItem

**Comment by teschnei** [comment]
would prefer a dump before you try to revert anything
