### ISSUE TITLE
zoning resets all abilities beside 2 hour ability

### ISSUE THREAD

**Issue by sisternERA** [DarkstarProject/darkstar#829]
after latest rebuild i have seen that most people can reset almost all abilities beside two hour by just zoning

**Comment by TeoTwawki** [comment]
Added note: this seems to only happen for the folks using multiple map servers

**Comment by teschnei** [comment]
yea, that's been the case for a few months now, regardless of how many map servers you have

**Comment by teschnei** [comment]
and now recasts are saved/loaded to the database!
