### ISSUE TITLE
 abilities unusable

### ISSUE THREAD

**Issue by sisternERA** [DarkstarProject/darkstar#832]
the following abilities was removed from the darkstar scripts folders   Agnon, Azure Lore,  convergence, cover, feint, killer instinct, random deal, retaliation, and tame.  i dont know if this was intentional or not.  this may be  causing the abilities to be unusable.   i just rebuilt my test server to current dsp again to confirm that it is not the custom content of my server causing this.  i tried adding the lua below to see if it would help and it did not.
function OnAbilityCheck(player,target,ability)
	return 0,0;
end;

function OnUseAbility(player, target, ability)

	target:addStatusEffect(EFFECT_RETALIATION,7,0,180);
end;

**Comment by teschnei** [comment]
they were never in the the darkstar scripts folder i don't think
