### ISSUE TITLE
clusters/quivers giving two stacks when used, possibly others too

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#833]
crystal clusters and quivers are reportedly giving two stacks of items when used rather than one, might be more than just those two examples.  going to test everything.

**Comment by teschnei** [comment]
test -> confirm -> open issue

**Comment by Scavenge** [comment]
confirmed that quivers and clusters do it, but not shihei toolbags

**Comment by teschnei** [comment]
don't forget to reopen after you confirm :p

**Comment by teschnei** [comment]
7722760f58b61d9ebcc83451662e73b33ab383d7
