### ISSUE TITLE
intense lag going on ever since recast table added

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#840]
ever since the other night that we put in 

https://github.com/DarkstarProject/darkstar/commit/80caa516496eef69c83afa496178a4afe1659ea8

we have been lagging really badly, the console seems to be pausing every few seconds before continuing to scroll.  

however it's worth mentioning that we did put in 

https://github.com/DarkstarProject/darkstar/commit/e51d95034b3ee268e603b2ec7c960443dd01458a

in the same update.

lag is causing up to 10+ seconds between spellcasts/job abilities being used and going off.

I am assuming it to be the recast table because it is updating consantly for every player and the lag gets worse with more people online.  restarting the server causes short-term relief.  though, I don't know enough to say these things for sure.

**Comment by teschnei** [comment]
if you delete or rename the recast table, everything should still work (except recasts saving across zones), but it'll let you know if it's that table or not for sure

**Comment by Scavenge** [comment]
ok thanks

**Comment by Scavenge** [comment]
yea that fixed it, deleting the table

**Comment by teschnei** [comment]
ok, i'll disable it for now until i can change how it works

**Comment by Scavenge** [comment]
ok that worked well until people said that using a scroll made every single spell in their lists disappear other than white magic.
