### ISSUE TITLE
New Mutex lines causing server to insta crash.

### ISSUE THREAD

**Issue by Signature420** [DarkstarProject/darkstar#843]
Had to comment out new mutex addons to stop crashing on char log in.

charentity.cpp    and header file

**Comment by Signature420** [comment]
was causing a memory issue when ran in debug to see what it was.

**Comment by Signature420** [comment]
new commit from 3 minutes ago might have fixed the issue. haven't checked though.

**Comment by teschnei** [comment]
oh, I didn't even see this issue report until after I noticed it myself >_>
