### ISSUE TITLE
Invisible Mog furniture

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#851]
Models for items placed in the mog layout are sometimes missing since the item changes.  I can still target them to remove them while they are invisible. Reloaded all item tables, removed all items from my layout and replaced them, exit mog and come back and they are missing again.

**Comment by Signature420** [comment]
I can't remove the invisible furniture... I can target it. but the remove button is grey'd out.

**Comment by TeoTwawki** [comment]
Try remove all button?

**Comment by nesstea** [comment]
Yeah it crashes the client when they try to modify it, as well.

**Comment by TeoTwawki** [comment]
Seems the reason we aren't seeing the models is the coordinates being messed up. When I go to move things, they aren't where the cursor jumps to.

![South Sandy Mog House](http://s16.postimg.org/3ymaqv6yt/image.png)
![North Sandy Mog House](http://s23.postimg.org/5l61jddij/image.png)
