### ISSUE TITLE
BCNM Maat and Shadowlord no win condition

### ISSUE THREAD

**Issue by sisternERA** [DarkstarProject/darkstar#853]
It appears that when you defeat maat by fighting or optional win condition maat just disapears.  This is also duplicated in the shadowlord fight

**Comment by sisternERA** [comment]
It looks like most of them with the exception of orb traded BCNM's dont recognize the win condition
Mob dies/despawns and event does not register

**Comment by gedads** [comment]
I'm currently having the same issue while i was testing bastok 9-2, volker's death isn't recognized and bcnm still continue

**Comment by sisternERA** [comment]
trying to track this down and only thing i have gotten in the way of errors is a [fatal error] Sql_NextRow: SQL_ERROR

that come inbetween the game adding me to bcnm and the actual registration being completed

**Comment by sisternERA** [comment]
fixed it was a capitilized o thit i missed on a update to current somehow
