### ISSUE TITLE
sql error. Char_effects and char_blacklist

### ISSUE THREAD

**Issue by Signature420** [DarkstarProject/darkstar#867]
Game server debug menu reads
[SQL] DB error - Incorrect information in file: '.\dspdp\char_effects.frm'

This is the error that comes up when I try to execute both batch files.
-----------------------------------------------------------------------------------------------------------------------
[Err] 1033 - Incorrect information in file: '.\dspdb\char_effects.frm'
[Err] CREATE TABLE IF NOT EXISTS `char_effects` (
  `charid` int(10) unsigned NOT NULL,
  `effectid` smallint(5) unsigned NOT NULL,
  `icon` smallint(5) unsigned NOT NULL DEFAULT '0',
  `power` smallint(5) unsigned NOT NULL DEFAULT '0',
  `tick` int(10) unsigned NOT NULL DEFAULT '0',
  `duration` int(10) unsigned NOT NULL DEFAULT '0',
  `subid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `subpower` smallint(5) NOT NULL DEFAULT '0',
  `tier` smallint(5) unsigned NOT NULL DEFAULT '0',
  KEY `charid` (`charid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
[Msg] Finished - Unsuccessfully
--------------------------------------------------

**Comment by Signature420** [comment]
I fixed the problem by deleting the .frm files and rerunning the batch file for char_effects and blacklist

**Comment by teschnei** [comment]
if it does that again, reopen this
