### ISSUE TITLE
charmed players character models do not move but they are moving/attacking invisibly

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#869]
this is identical to the issue that happens in many bcnms, once charmed the player does not move visually, but are shown to be attacking in the battle log.  the players attempting to target them with melee weapons would have to rotate until they found the invisible, real one while selecting the immobile model.  also there is no longer an 'attack' option when selecting the charmed player's immobile model, but you can attack with ctrl+a.  this didn't use to happen and charm worked really well recently. my optimism says maybe this could provide insight for the bcnms as well if worked out.

**Comment by Scavenge** [comment]
after relogging the character being charmed a few times, he is now using attack animations but his model is still rooted to a false spot while he moves invisibly

**Comment by Scavenge** [comment]
i think this has some relation to the crashes that come from spellcasts while charmed, because the charmed player's UI is not disabled like it had been in the past.  making a leap of logic, it seems like this all stems from one root problem to do with switching a character into 'charmed mode' somewhere deeper that causes all these smaller ones.

**Comment by teschnei** [comment]
Oh, the charmed AI is just missing one line to send updates. Those bcnms
were fixed a few months ago actually too

**Comment by Scavenge** [comment]
oh nice, i'll have to re-enable those.
