### ISSUE TITLE
onConquestUpdate: Bad Argument

### ISSUE THREAD

**Issue by Signature420** [DarkstarProject/darkstar#871]
this is what dsgameserver debug window reads...

[Error] luautils::onConquestUpdate: .\scripts/globals/conquest.lua:1307: bad argument #1 to 'band' (number expected, got nil)
[Error] luautils::onConquestUpdate: .\scripts/globals/conquest.lua:1307: bad argument #1 to 'band' (number expected, got nil)

not sure its as big of a deal as much as it is a pain to see lol

**Comment by teschnei** [comment]
7dbb5fb

**Comment by Signature420** [comment]
thank you much!
