### ISSUE TITLE
print(player:getMod(MOD_EVA)) reading extremely low evasion value after zoning consistent with combat results

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#872]
following korietsu's idea i used an npc to display my mod_eva to me in selbina, right after I changed jobs at the nomad moogle.  I found that zoning is setting my mod_eva back to an abysmal level and changing jobs fixes it.  so with the npc i coded in selbina, i can zone in, check that i have a bad evasion rating, change jobs in any way and check again to see that my evasion rating is back to normal, then zone out and back in to repeat the process consistently.

**Comment by Scavenge** [comment]
now that i continued testing and changed my subjob again, my mod_eva printout is 15 and seems to be staying at that no matter what i do.  the only way i'v ebeen able to get it back to normal is using a gm command change jobs

**Comment by teschnei** [comment]
i changed it just now so MOD_EVA does not include the evasion granted from skill - it only counts bonus evasion from buffs, gear, food, etc (like it always should have).  if you want an entity's true evasion, use getEVA() (from lua) or EVA() (from c++)

**Comment by Scavenge** [comment]
alright, using player:getEVA() returned a 50 instead of a 15, changing jobs now fixes it to say 320 instead of 269, and zoning sets it back to a 50, rinse and repeat. i'll rebuild with that change see if that fixes it, it sounds like maybe that extra evasion from skill was pushing it past the int limit and making it negative? not sure just repeating speculations i heard in irc earlier

**Comment by teschnei** [comment]
i doubt you were going over 32000 evasion, so probably not that :)

it was doing some really weird things (using setModifier, for instance..) so hopefully this fixes that

**Comment by Scavenge** [comment]
k, i deleted it since i had been wrong about my theory, but in case you didn't see it this picture shows the obvious correlation with combat results: http://i.imgur.com/BviZi25.png

ignore the comments at the bottom, i was way off in my theory.

**Comment by Scavenge** [comment]
working perfectly now :D zoning no longer resets either. thank you thank you a huge weight off my back now
