### ISSUE TITLE
dINT caps in magic.lua

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#873]
See line 71 in magic.lua for reference. I know these are guesses, and so its being upfront about not being retail accurate. But I just want to put this out there so maybe someone with an active retail account can check it out.

http://wiki.ffxiclopedia.org/wiki/Calculating_Magic_Damage doesn't state any known cap value. It seems more likely it would be per spell, or per tier with Thunder3 having a different cap than Thunder4, than to have 1 global cap for all spells. It should be pretty simple to test on retail with some INT gear and a stable target mob that has a known INT value.

**Comment by teschnei** [comment]
the formula in magic.lua is not even close to how it's known to work on retail now (most of them do not have caps, with the exception of tier 1 spells).  Check bg-wiki if you want the current formula.  (note: i don't know if the formula changed at one point to what it is now or was more easily figured out when SE changed all the values for spells.. probably the latter)

**Comment by korietsu** [comment]
@TeoTwawki if you want to know the classic and new dINT values I would suggest combing through the old FFXI advanced forum on BG. I'm sure there's a thread specifically dedicated to spells.

**Comment by TeoTwawki** [comment]
I honestly just hoped somebody else would pick this up so I wouldn't add more to my list of stuff I need to finish (I have started to many things already), after someone brought this up to me earlier the same day.

**Comment by korietsu** [comment]
Let me see if I can take a look at it.

**Comment by korietsu** [comment]
Actually, here's the full breakdown on dINT for 99 content. I'll see if I can find the old school values through the revision history on the wiki. 

http://www.bg-wiki.com/bg/Magic_Damage#Calculating_D

**Comment by teschnei** [comment]
i wouldn't bother with the old school values, they don't make sense with the new cast time/mp costs anyways

**Comment by korietsu** [comment]
It might be worth making them toggle with SOA? There are a few 75 cap servers, sorta like what was going on with the WS modifiers in the other pull request?

**Comment by teschnei** [comment]
this particular situation is different because they're not as extreme, but more importantly, mp and cast time are hard coded into the client

**Comment by korietsu** [comment]
Ok, makes sense.

**Comment by teschnei** [comment]
i think the main purpose of the change was just to balance the magic damage+ stat from adoulin gear, and didn't really change a whole lot without it (other than making tier 1 spells cast really fast and be cheaper, which is basically just a QoL change for low levelling)

**Comment by madwraith** [comment]
dINT is no longer capped with the update made to the formula #1438
