### ISSUE TITLE
Homepoints Erased for all players

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#874]
as of https://github.com/DarkstarProject/darkstar/commit/dc317f61160f2d681f46e0de532c275eb7fa5e76

Looks like adding the new homepoints might have broke some things?

**Comment by bope12** [comment]
homepoints are now stored in 2 vars per bitmask to convert old ones take
the old player var and split it at the 16th bit into your new 1 and 2

**Comment by teschnei** [comment]
dc317f6 had nothing to do with homepoints, but it was from a few weeks ago - data being erased by update in this case was not a bug, though
