### ISSUE TITLE
CoP 6-4 One to Be Feared Omega/Ultima aggro immediately upon entry

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#875]
After killing the five mammets and using the airship doors to go into the Omega fight, Omega sometimes immediately attacks or takes 3 to 4 minutes to attack. I feel that he aggros immediately when you are transported from the mammets. Same goes with Ultima.

Note: I believe he attacked one of our party memebers mid cutscene.

**Comment by Fiocitrine** [comment]
When I did the fight it wasn't like that. Something was changed since then.

**Comment by korietsu** [comment]
I can honestly say I've seen him do that for at least 6 months. 4-2 still has Ouryu flying out of the BCNM after it's over and still goes after you in the CS, that's been like that for almost a year.

**Comment by Fiocitrine** [comment]
Hmmm I can't say anything about Ouryu. But, I did Airship over 6 months ago and it wasn't like it is now.

**Comment by Hozu** [comment]
Could this be fixed by making mobs in this BCNM not superlink like Diabolos/Diabolos Prime/Promy Vahzl BCs, and just make the mammets themselves superlink with each other?

**Comment by wrenffxi** [comment]
This can be closed per #5768
