### ISSUE TITLE
onAdditionalEffect always overrides Sambas

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#899]
I added the item in the db to have an onAdditionalEffect and got it working perfectly, except it will never drain hp with drain or aspir sambas. I am trying to figure it out, but if anything could lend a hand, I can make the edit and commit.

**Comment by nesstea** [comment]
Do I have to code the samba effect in the onAdditionalEffect script when it doesn't proc (if the mob has daze)?

**Comment by teschnei** [comment]
no, either the effect is supposed to return something specific if it didn't
proc or the core is missing something to check if it didn't proc

**Comment by TeoTwawki** [comment]
Core is missing the check. The guy that originaly coded the scripted add effects never made it check sambas after a failed additional effect proc so if add effects are checked at all no other effect can happen after it.

**Comment by teschnei** [comment]
Yeah, just checked. Not a hard fix, I should have internet finally in an
hour or two for fixing

**Comment by TeoTwawki** [comment]
Cool, I just got going on the next heap of scripts for the items.

**Comment by nesstea** [comment]
@TeoTwawki I have all but two relics coded for additional effects if you'd like me to submit them.

**Comment by TeoTwawki** [comment]
yes please, no point is multiple people doing same ones more than once. I'm hitting items in a mostly level ascending order, did up to lv39 last batch so starting there and working my way up now.

**Comment by nesstea** [comment]
They currently delete the previous effect on the mob without checks and reapply it. Just a temporary fix in the meantime.
