### ISSUE TITLE
A Crystalline Prophecy: Gathering the Light I mobs not spawing

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#901]
After seeing that the mobs for this mission ( http://wiki.ffxiclopedia.org/wiki/Gatherer_of_Light_(I) ) didn't have xyz positions, I added them to my test server. I thought this might resolve the issue. I then ran into another issue of the server not finding the mob IDs, http://justpaste.it/jb8h .

IDs respectively:

Chuglix Berrypaws - 17228249

Dribblix Greasemaw - 17269144

Vegnix Greenthumb - 17207710

**Comment by TeoTwawki** [comment]
These were already in and working at one point. I'll look into it soon.
