### ISSUE TITLE
Beastmaster Pets not spawning. 

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#915]
Still having issues with beastmaster pets not spawning. I think this issue was submitted before, but wanted to make sure it was getting looked at or if anyone had ideas as to why they weren't spawning.

**Comment by Fiocitrine** [comment]
yeah I posted an issue about it

**Comment by teschnei** [comment]
there is a search bar, use it before posting a new issue (especially if you think there already is one)

**Comment by BaldrDash** [comment]
Ah, thank you, sorry about that
