### ISSUE TITLE
DSP_DEBUG_BREAK_IF(PChar->loc.zone->m_BattlefieldHandler == NULL);

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#923]
This is tripped if a player kills a dynamis boss and has an alliance member not inside the zone at the time. We had just done a spree of NM killing together and part of the group decided to go do dyna sandy. We didn't drop alliance, but not all of us were doing dyna and I think that why we found this crash while other group did the same dyna the same day without issues.

`CLuaBaseEntity::launchDynamisSecondPart` was crashing at

`DSP_DEBUG_BREAK_IF(PChar->loc.zone->m_BattlefieldHandler == NULL);`

Also seeing odd messages that don't belong when alliance members enter a dynamis zone; Everytime someone in alliance entered dyna, way back in aht urgan I saw messages saying i recovered zero mp.

Will have a dump up shortly

**Comment by TeoTwawki** [comment]
Crash dump finally uploaded, slow net tonight. https://yadi.sk/d/HDoRWq-yedBjA

**Comment by xdemolish** [comment]
scripts\zones\Dynamis-Bastok\mobs\Gu_Dha_Effigy.lua
scripts\zones\Dynamis-Jeuno\mobs\Goblin_Golem.lua
scripts\zones\Dynamis-San_dOria\mobs\Overlord_s_Tombstone.lua
scripts\zones\Dynamis-Windurst\mobs\Tzee_Xicu_Idol.lua


function onMobDeath(mob,killer)
if(killer:getZoneID() ~= mob:getZoneID()) then
        return;
    end;


should fix it

**Comment by TeoTwawki** [comment]
I'm going to try making certain chars are in zone before letting onMobDeath exec on them instead, because there will likely be non dynamis related versions of this problem.

@teschnei
I'm also concerned there may be similar issues with other things checking alliance/party members, where onMobDeath is not even involved - should we maybe exclude out of zone chars right in ForAlliance / ForParty or per situation like I am trying inside the onMobDeath lambda?

**Comment by teschnei** [comment]
Yes, I don't think onmobdeath should ever run on people outside the zone

**Comment by TeoTwawki** [comment]
@teschnei can/should we do that globally as part of ForAlliance/ForParty though or do we need it per individual function though?

**Comment by teschnei** [comment]
No, do it in onMobDeaths lambda.
