### ISSUE TITLE
Particle Gates in Temenos not opening

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#951]
The gates now spawn, but clicking on them does nothing: https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Temenos/npcs/Particle_Gate.lua

Is it the ID? 
The cut scenes aren't triggering, is the issue.

**Comment by RunAwayDSP** [comment]
npcid shift most likely

**Comment by Fiocitrine** [comment]
I think the IDs are ok. They check out when comparing to npc_list.sql.

**Comment by Scavenge** [comment]
there is an initial id somewhere....

the GateID =  (npc:getID())-16929221; 
on our server is set as 
  GateID =  (npc:getID())-16928771;  

I made this change on the 27th of february but the file was already customized at that point so I wasn't sure if it was a dsp issue yet.  If this helps I can submit a pull request on it

**Comment by nesstea** [comment]
if yours works, you should!

**Comment by maxtherabbit** [comment]
@Scavenge please do

**Comment by zynjec** [comment]
Closing, if this is still an issue please open another issue.
