### ISSUE TITLE
Walking/running sounds are missing

### ISSUE THREAD

**Issue by BrosephJ** [DarkstarProject/darkstar#979]
On a few servers that I've tried walk/run footstep sounds do not play. This is happening on the Darkstar Testing server and some other servers I've tried. I can hear the footsteps of other people around me, but not my own. When I log into live I can hear my footsteps just fine. My client isn't modified in any way. I've installed my game and done the file repair as anybody does it to join a private server. I don't have any clue at all what is causing this. When I play on DaFunk though, I can hear footsteps. They have a very high movement setting, though.

I've reported this on some forums and they claim that they can hear their footsteps just fine and that my client is broken. :/ Not sure what to say about that since I can hear everything just fine when I play on the live servers.

**Comment by teschnei** [comment]
Looks like a local issue, it's working fine for my client (both on retail and darkstar..)

**Comment by BrosephJ** [comment]
If it's a local issue can you please walk me through some steps on how to fix it? I've only ever followed the correct steps directed by private servers for installing and updating my client and yet this problem occurs. I don't understand the source of the problem.

I'm running Windows 8.1 Pro x64 and my audio card is an ASUS Xonar DG. What OS are you using teschnei? I've tried: reinstalling the game; moving the game to other drives; running as admin; running under windows xp, vista and 7 compatibility modes; re-executing the file repair in playonline viewer; bypassing ashita and only running the ffxi-bootmod through a command line. What have I missed?

I've asked for help in some forum but they won't provide anything for me.

**Comment by teschnei** [comment]
i have no idea how to fix it, as it has nothing to do with the server
for what it's worth, i use windows 7, but you're better off asking on the dsp forums and not here (this is for server issues only)
