### ISSUE TITLE
Mobskills being paralyzed when they shouldn't be. 

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#988]
http://wiki.ffxiclopedia.org/wiki/Paralyze_(Status_Effect)
http://wiki.ffxiclopedia.org/wiki/Paralyze

When paralyzed, there is a chance of standard melee/ranged attacks, spells, job abilities, and items to fail to take effect. (See Paralyze (Status Effect) for more information.)

**Weapon Skills and monster TP abilities are not affected by paralysis, and can still be used freely with no chance of paralysis failure.**

Spell accuracy (the chance of the spell successfully paralyzing the enemy) is primarily affected by Enfeebling Magic Skill and Magic Accuracy. Potency (the chance for each enemy's attack to become paralyzed) of this spell is primarily affected by MND.

**Comment by personaone** [comment]
Are you sure that Paralysis doesn't affect weapon skills? I'm pretty sure it did when i played retail- I loved it when I was skillchaining and the mage didn't remove my Paralysis on time... Used the TP but the WS didn't go off.

**Comment by korietsu** [comment]
See, thats what I thought too, but that was the old way of doing stuff on retail.

**Comment by maxtherabbit** [comment]
bloops guess I was wrong, reverted that change

player ws were not affected so they are still fine

**Comment by korietsu** [comment]
Thanks Max! I'll capture some video for the laughs of the mobs doing the paralyze dance in bibiki :)

I know I remembered the mobs working that way too, but I had to track it down cause I had about 15 people bombard me :D
